use super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 F8 API convergence review guard child-owner split",
        &[
            "runtime_15_f8_api_convergence_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/texture_import_settings.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/scaffold.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/first_party_descriptors.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/test_fixtures.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/private_fields.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/constructor_retirement.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/status_mirrors.rs",
            "review_f8_texture_import_settings_use_fallible_apply_not_with",
            "review_f8_runtime_plugin_descriptor_exposes_builder_scaffold",
            "review_f8_first_party_runtime_plugin_descriptors_use_builder",
            "review_f8_runtime_plugin_descriptor_test_fixtures_use_builder",
            "review_f8_runtime_plugin_descriptor_fields_are_private_with_accessors",
            "review_f8_runtime_plugin_descriptor_public_constructor_is_retired",
            "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
            "runtime_15_f8_api_convergence_review_guards_are_child_owners",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 F8 descriptor review guard child-owner split",
        &[
            "runtime_15_f8_descriptor_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/scaffold.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/first_party_descriptors.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/test_fixtures.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/private_fields.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/constructor_retirement.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/status_mirrors.rs",
            "review_f8_runtime_plugin_descriptor_exposes_builder_scaffold",
            "review_f8_first_party_runtime_plugin_descriptors_use_builder",
            "review_f8_runtime_plugin_descriptor_test_fixtures_use_builder",
            "review_f8_runtime_plugin_descriptor_fields_are_private_with_accessors",
            "review_f8_runtime_plugin_descriptor_public_constructor_is_retired",
            "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
            "runtime_15_f8_api_convergence_review_guards_are_child_owners",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "F8 review harness 7/7",
            "Cargo gate deferred",
        ],
    ),
];
