use super::*;

#[test]
fn runtime_15_status_support_expected_slice_row_data_exports_child_groups() {
    let status_support = read_runtime_src(STATUS_SUPPORT_ROWS_PATH);
    let runtime_15_m3 = read_runtime_src(RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15 = read_runtime_src(RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH);
    let top_level = read_runtime_src(TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH);

    assert_contains_all(
        "status-support route exports expected-slice row-data children",
        &status_support,
        &[
            "EXPECTED_SLICE_BASE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "EXPECTED_SLICE_TOP_LEVEL_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "EXPECTED_SLICE_ROUTE_METADATA_EXPECTED_STATUS_OUTPUT_SLICES",
            "EXPECTED_SLICE_STRUCTURE_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "EXPECTED_SLICE_STATUS_SUPPORT_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "EXPECTED_SLICE_REVIEW_GUARD_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES",
            "EXPECTED_SLICE_WARNING_CLEANUP_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 M3 aggregation exports expected-slice row-data children",
        &runtime_15_m3,
        &[
            "STATUS_SUPPORT_EXPECTED_SLICE_BASE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_EXPECTED_SLICE_TOP_LEVEL_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_EXPECTED_SLICE_ROUTE_METADATA_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_EXPECTED_SLICE_STRUCTURE_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_EXPECTED_SLICE_STATUS_SUPPORT_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_EXPECTED_SLICE_REVIEW_GUARD_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_EXPECTED_SLICE_WARNING_CLEANUP_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 and top-level aggregation consume expected-slice row-data children",
        &[runtime_15.as_str(), top_level.as_str()].join("\n"),
        &[
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_BASE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_TOP_LEVEL_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_ROUTE_METADATA_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_STRUCTURE_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_STATUS_SUPPORT_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_REVIEW_GUARD_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_WARNING_CLEANUP_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
}
