import { HostNativeFloatingWindowSurfaceData } from "host_components.slint";
import { HostWindowPresentationData } from "host_root.slint";
import { HostWorkbenchWindowSceneData, HostWorkbenchWindowScene } from "host_scene.slint";
import { HostWorkbenchWindowSurfaceContract } from "host_surface_contract.slint";
import { HostNativeFloatingWindowSurface } from "host_native_floating_window_surface.slint";

export component HostWorkbenchWindowSurface inherits Rectangle {
    in property <HostWorkbenchWindowSceneData> scene_data;

    HostWorkbenchWindowScene {
        width: parent.width;
        height: parent.height;
        scene_data: root.scene_data;
    }
}

export component HostNativeWorkbenchWindowSurface inherits Rectangle {
    in property <HostNativeFloatingWindowSurfaceData> surface_data;

    HostNativeFloatingWindowSurface {
        width: parent.width;
        height: parent.height;
        surface_data: root.surface_data;
    }
}

export component HostWorkbenchWindowSurfaceHost inherits Rectangle {
    in property <HostWindowPresentationData> host_presentation;

    contract := HostWorkbenchWindowSurfaceContract {
        host_presentation: root.host_presentation;
    }

    if !root.host_presentation.host_shell.native_floating_window_mode: HostWorkbenchWindowSurface {
        width: parent.width;
        height: parent.height;
        scene_data: contract.workbench_scene_data;
    }

    if root.host_presentation.host_shell.native_floating_window_mode: HostNativeWorkbenchWindowSurface {
        width: parent.width;
        height: parent.height;
        surface_data: contract.native_floating_surface_data;
    }
}
