import { HostWindowLayoutData, HostWindowShellData, HostNativeFloatingWindowSurfaceData } from "host_components.slint";
import { HostWindowSceneData } from "host_scene.slint";

export struct HostWindowPresentationData {
    host_shell: HostWindowShellData,
    host_layout: HostWindowLayoutData,
    host_scene_data: HostWindowSceneData,
    native_floating_surface_data: HostNativeFloatingWindowSurfaceData,
}
