import { HostNativeFloatingWindowSurfaceData } from "host_components.slint";
import { HostWorkbenchWindowSceneData } from "host_scene.slint";

export component HostWorkbenchWindowSurfaceContract inherits Rectangle {
    in property <HostWorkbenchWindowSceneData> workbench_scene_data;
    in property <HostNativeFloatingWindowSurfaceData> native_floating_surface_data;
    width: 0px;
    height: 0px;
}
