import { HostNativeFloatingWindowSurfaceData } from "host_components.slint";
import { HostWindowPresentationData } from "host_root.slint";
import { HostWindowSceneData, HostWindowScene } from "host_scene.slint";
import { HostWindowSurfaceContract } from "host_surface_contract.slint";
import { HostNativeFloatingWindowSurface } from "host_native_floating_window_surface.slint";

export component HostWindowSurface inherits Rectangle {
    in property <HostWindowSceneData> scene_data;

    HostWindowScene {
        width: parent.width;
        height: parent.height;
        scene_data: root.scene_data;
    }
}

export component HostNativeWindowSurface inherits Rectangle {
    in property <HostNativeFloatingWindowSurfaceData> surface_data;

    HostNativeFloatingWindowSurface {
        width: parent.width;
        height: parent.height;
        surface_data: root.surface_data;
    }
}

export component HostWindowSurfaceHost inherits Rectangle {
    in property <HostWindowPresentationData> host_presentation;

    contract := HostWindowSurfaceContract {
        host_presentation: root.host_presentation;
    }

    if !root.host_presentation.host_shell.native_floating_window_mode: HostWindowSurface {
        width: parent.width;
        height: parent.height;
        scene_data: contract.host_scene_data;
    }

    if root.host_presentation.host_shell.native_floating_window_mode: HostNativeWindowSurface {
        width: parent.width;
        height: parent.height;
        surface_data: contract.native_floating_surface_data;
    }
}
