import { HostWindowShellData, HostWindowLayoutData, HostWindowSurfaceData } from "host_components.slint";
import { HostWorkbenchWindowSurface, HostNativeWorkbenchWindowSurface } from "host_surface.slint";

export component WorkbenchHostScaffold inherits Rectangle {
    in property <HostWindowSurfaceData> host_surface_data;
    in property <HostWindowShellData> host_shell: {
        project_path: "",
        status_secondary: "",
        viewport_label: "",
        drawers_visible: false,
        left_expanded: false,
        right_expanded: false,
        bottom_expanded: false,
        save_project_enabled: false,
        undo_enabled: false,
        redo_enabled: false,
        preset_names: [],
        active_preset_name: "",
        shell_min_width_px: 0.0,
        shell_min_height_px: 0.0,
        native_floating_window_mode: false,
        native_floating_window_id: "",
        native_window_title: "Zircon Editor",
        native_window_bounds: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
    };
    in property <HostWindowLayoutData> host_layout: {
        center_band_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        status_bar_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        left_region_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        document_region_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        right_region_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        bottom_region_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        left_splitter_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        right_splitter_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        bottom_splitter_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
        viewport_content_frame: { x: 0.0, y: 0.0, width: 0.0, height: 0.0 },
    };
    out property <float> shell_width_px: root.width / 1px;
    out property <float> shell_height_px: root.height / 1px;
    out property <float> viewport_width: root.host_layout.viewport_content_frame.width;
    out property <float> viewport_height: root.host_layout.viewport_content_frame.height;
    
    if !root.host_shell.native_floating_window_mode: HostWorkbenchWindowSurface {
        width: parent.width;
        height: parent.height;
        host_surface_data: root.host_surface_data;
        host_shell: root.host_shell;
        host_layout: root.host_layout;
    }

    if root.host_shell.native_floating_window_mode: HostNativeWorkbenchWindowSurface {
        width: parent.width;
        height: parent.height;
        host_surface_data: root.host_surface_data;
        host_shell: root.host_shell;
    }
}

