export struct HostMenuStateData {
    open_menu_index: int,
    hovered_menu_index: int,
    hovered_menu_item_index: int,
    window_menu_scroll_px: float,
    window_menu_popup_height_px: float,
}

export struct HostDragStateData {
    active_drag_target_group: string,
    drag_active: bool,
    drag_tab_id: string,
    drag_tab_title: string,
    drag_tab_icon_key: string,
    drag_source_group: string,
    drag_pointer_x: float,
    drag_pointer_y: float,
}

export struct HostResizeStateData {
    resize_active: bool,
    resize_group: string,
}
