use super::*;

#[test]
fn runtime_15_lock_poison_status_row_data_export_chain_is_current() {
    let top_level = read_runtime_src(TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15 = read_runtime_src(RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15_m3 = read_runtime_src(RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH);

    assert_contains_all(
        "Runtime 15 M3 exposes every lock-poison status child group",
        &runtime_15_m3,
        &[
            "LOCK_POISON_STATUS_EXPECTED_STATUS_OUTPUT_SLICES",
            "LOCK_POISON_STATUS_POLICY_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES",
            "LOCK_POISON_STATUS_CORE_RUNTIME_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "LOCK_POISON_STATUS_RUNTIME_SERVICES_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "LOCK_POISON_STATUS_RESOURCE_RENDER_INPUT_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "LOCK_POISON_STATUS_SCRIPT_VM_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "LOCK_POISON_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 row-data parent exports every lock-poison status child group",
        &runtime_15,
        &[
            "RUNTIME_15_M3_LOCK_POISON_STATUS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_LOCK_POISON_STATUS_POLICY_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_LOCK_POISON_STATUS_CORE_RUNTIME_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_LOCK_POISON_STATUS_RUNTIME_SERVICES_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_LOCK_POISON_STATUS_RESOURCE_RENDER_INPUT_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_LOCK_POISON_STATUS_SCRIPT_VM_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_LOCK_POISON_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "top-level expected status row data consumes every lock-poison status child group",
        &top_level,
        &[
            "runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_POLICY_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_CORE_RUNTIME_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_RUNTIME_SERVICES_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_RESOURCE_RENDER_INPUT_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_SCRIPT_VM_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
}
