type Slice = super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 priority plan docs code-path integrity guard",
        &[
            "runtime_15_priority_plan_docs_code_path_integrity_guard_static_passed_cargo_deferred",
            "docs/plans/engine-code-structure-convention.md",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "structure_convention/test_file_budget/priority_plan_docs/code_paths.rs",
            "runtime_15_priority_plan_docs_code_paths_stay_current",
            "related_code",
            "implementation_files",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs test-path integrity guard",
        &[
            "runtime_15_priority_plan_docs_test_path_integrity_guard_static_passed_cargo_deferred",
            "docs/plans/engine-code-structure-convention.md",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "structure_convention/test_file_budget/priority_plan_docs/test_paths.rs",
            "runtime_15_priority_plan_docs_test_paths_stay_current",
            "tests:",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs frontmatter status guard",
        &[
            "runtime_15_priority_plan_docs_frontmatter_status_guard_static_passed_cargo_deferred",
            "docs/plans/engine-code-structure-convention.md",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "structure_convention/test_file_budget/priority_plan_docs/frontmatter_status.rs",
            "runtime_15_priority_plan_docs_frontmatter_status_stays_current",
            "doc_type: convention-authority",
            "doc_type: review-findings",
            "status: in_progress",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs frontmatter uniqueness guard",
        &[
            "runtime_15_priority_plan_docs_frontmatter_uniqueness_guard_static_passed_cargo_deferred",
            "docs/plans/engine-code-structure-convention.md",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "structure_convention/test_file_budget/priority_plan_docs/frontmatter_uniqueness.rs",
            "runtime_15_priority_plan_docs_frontmatter_sections_have_unique_entries",
            "priority_plan_docs/frontmatter_uniqueness.rs::runtime_15_priority_plan_docs_frontmatter_sections_have_unique_entries",
            "duplicate-free frontmatter",
            "related_code",
            "implementation_files",
            "plan_sources",
            "tests",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs required header sections guard",
        &[
            "runtime_15_priority_plan_docs_required_header_sections_guard_static_passed_cargo_deferred",
            "docs/plans/engine-code-structure-convention.md",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "structure_convention/test_file_budget/priority_plan_docs/header_sections.rs",
            "runtime_15_priority_plan_docs_required_header_sections_stay_complete",
            "related_code:",
            "implementation_files:",
            "plan_sources:",
            "tests:",
            "doc_type:",
            "status:",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs plan-source cross-link guard",
        &[
            "runtime_15_priority_plan_docs_plan_source_cross_link_guard_static_passed_cargo_deferred",
            "docs/plans/engine-code-structure-convention.md",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "docs/plans/zircon_runtime/runtime/15-code-structure-and-module-conventions.md",
            "structure_convention/test_file_budget/priority_plan_docs/plan_sources.rs",
            "runtime_15_priority_plan_docs_plan_sources_stay_cross_linked",
            "plan_sources:",
            "user:",
            "Cargo gate deferred",
        ],
    ),
];
