type Slice = super::Slice;

#[path = "owner_guards/inventory_rows.rs"]
mod inventory_rows;
#[path = "owner_guards/layout_rows.rs"]
mod layout_rows;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] =
    layout_rows::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] =
    inventory_rows::EXPECTED_STATUS_OUTPUT_SLICES;

pub(super) const OWNER_GUARD_ROW_ANCHOR_MIRROR: &str = r#"
Runtime 15 M3 priority plan docs guard-test listing guard
runtime_15_priority_plan_docs_guard_test_listing_guard_static_passed_cargo_deferred
Runtime 15 M3 priority plan docs guard child-owner split
runtime_15_priority_plan_docs_guard_child_owner_split_static_passed_cargo_deferred
full priority-plan-doc child inventory
Runtime 15 M3 priority plan docs child prose full inventory sync
runtime_15_priority_plan_docs_child_prose_full_inventory_sync_static_passed_cargo_deferred
Runtime 15 M3 priority plan docs guard-test child-owner split
runtime_15_priority_plan_docs_guard_test_child_owner_split_static_passed_cargo_deferred
full priority-plan-doc guard-test child inventory
Runtime 15 M3 priority plan docs guard-test child prose full inventory sync
runtime_15_priority_plan_docs_guard_test_child_prose_full_inventory_sync_static_passed_cargo_deferred
Runtime 15 M3 priority plan docs moved guard path mirror
runtime_15_priority_plan_docs_moved_guard_path_mirror_static_passed_cargo_deferred
Runtime 15 M3 priority plan docs guard inventory row-data source sync
runtime_15_priority_plan_docs_guard_inventory_row_data_source_sync_static_passed_cargo_deferred
Runtime 15 M3 priority plan docs listing prose full inventory sync
runtime_15_priority_plan_docs_listing_prose_full_inventory_sync_static_passed_cargo_deferred
Runtime 15 M3 priority plan docs moved mirror full inventory sync
runtime_15_priority_plan_docs_moved_mirror_full_inventory_sync_static_passed_cargo_deferred
structure_convention/test_file_budget/priority_plan_docs.rs
structure_convention/test_file_budget/priority_plan_docs/code_paths.rs
structure_convention/test_file_budget/priority_plan_docs/frontmatter_status.rs
structure_convention/test_file_budget/priority_plan_docs/frontmatter_uniqueness.rs
structure_convention/test_file_budget/priority_plan_docs/guard_tests.rs
structure_convention/test_file_budget/priority_plan_docs/header_sections.rs
structure_convention/test_file_budget/priority_plan_docs/plan_sources.rs
structure_convention/test_file_budget/priority_plan_docs/test_paths.rs
structure_convention/test_file_budget/priority_plan_docs/guard_tests/child_layout.rs
structure_convention/test_file_budget/priority_plan_docs/guard_tests/inventory_sync.rs
structure_convention/test_file_budget/priority_plan_docs/guard_tests/listing.rs
structure_convention/test_file_budget/priority_plan_docs/guard_tests/moved_paths.rs
structure_convention/test_file_budget/priority_plan_docs/guard_tests/nested_layout.rs
tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs/integrity_guards.rs
tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs/owner_guards.rs
runtime_15_priority_plan_docs_guard_children_are_folder_backed
runtime_15_priority_plan_docs_guard_test_children_are_folder_backed
runtime_15_priority_plan_docs_guard_test_child_prose_names_full_inventory
runtime_15_priority_plan_docs_guard_inventory_uses_child_row_data_sources
runtime_15_priority_plan_docs_listing_prose_names_full_inventory
runtime_15_priority_plan_docs_moved_mirror_names_full_inventory
priority_plan_docs/frontmatter_uniqueness.rs::runtime_15_priority_plan_docs_frontmatter_sections_have_unique_entries
priority_plan_docs/guard_tests/inventory_sync.rs::runtime_15_priority_plan_docs_guard_inventory_uses_child_row_data_sources
priority_plan_docs/guard_tests/inventory_sync.rs::runtime_15_priority_plan_docs_listing_prose_names_full_inventory
priority_plan_docs/guard_tests/nested_layout.rs::runtime_15_priority_plan_docs_guard_test_child_prose_names_full_inventory
priority_plan_docs/guard_tests/moved_paths.rs::runtime_15_priority_plan_docs_moved_mirror_names_full_inventory
full priority-plan-doc child inventory
full priority-plan-doc guard inventory
full priority-plan-doc guard-test child inventory
full priority-plan-doc moved guard inventory
child row-data source
Cargo gate deferred
"#;
