type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 status output row-data guard child-owner split",
        &[
            "runtime_15_status_output_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "runtime_15_status_output_row_data_guard_child_owner_split",
        ],
    ),
    (
        "Runtime 15 M3 status-output row-data module-layout guard folder-backed split",
        &[
            "runtime_15_status_output_row_data_module_layout_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/child_summaries.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/budgets.rs",
            "runtime_15_status_output_row_data_module_layout_guard_is_folder_backed",
            "runtime_15_status_output_row_data_guard_child_owner_split",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-mirror child split",
        &[
            "runtime_15_module_layout_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/layout_folder_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/folder_backed_status.rs",
            "runtime_15_module_layout_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout root inventory child split",
        &[
            "runtime_15_module_layout_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/root_owner_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/root_inventory.rs",
            "runtime_15_module_layout_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output row-data module-layout status-doc guard child-owner split",
        &[
            "runtime_15_status_output_row_data_module_layout_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs.rs",
            "runtime_15_status_output_row_data_module_layout_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-doc guard folder-backed split",
        &[
            "runtime_15_module_layout_status_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/source_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/budgets.rs",
            "runtime_15_module_layout_status_docs_guard_is_folder_backed",
            "runtime_15_status_output_row_data_module_layout_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-doc status-mirror child split",
        &[
            "runtime_15_module_layout_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_module_layout_status_doc_status_mirror_children_are_folder_backed",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support.rs",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-doc root inventory child split",
        &[
            "runtime_15_module_layout_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_inventory.rs",
            "runtime_15_module_layout_status_docs_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output row-data module-layout child-summary guard child-owner split",
        &[
            "runtime_15_status_output_row_data_module_layout_child_summary_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary guard folder-backed split",
        &[
            "runtime_15_module_layout_child_summary_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/owner_budgets.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary root inventory child split",
        &[
            "runtime_15_module_layout_child_summary_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/root_inventory.rs",
            "runtime_15_module_layout_child_summary_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary owner-budget guard child split",
        &[
            "runtime_15_module_layout_child_summary_owner_budget_guard_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/owner_budgets.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/owner_budgets/route_children.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/owner_budgets/nested_children.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/owner_budgets/surrounding_owners.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/owner_budgets/status_mirrors.rs",
            "runtime_15_module_layout_child_summary_guard_owner_budgets_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary milestone-groups child split",
        &[
            "runtime_15_module_layout_child_summary_milestone_groups_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups/runtime_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups/m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups/status_doc_groups.rs",
            "runtime_15_module_layout_child_summary_milestone_groups_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary foundation-review child split",
        &[
            "runtime_15_module_layout_child_summary_foundation_review_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review/runtime_foundation_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review/foundation_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review/review_guard_rows.rs",
            "runtime_15_module_layout_child_summary_foundation_review_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary status-doc guard child-owner split",
        &[
            "runtime_15_module_layout_child_summary_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs.rs",
            "runtime_15_module_layout_child_summary_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary status-doc guard folder-backed split",
        &[
            "runtime_15_module_layout_child_summary_status_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/source_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/budgets.rs",
            "runtime_15_module_layout_child_summary_status_docs_guard_is_folder_backed",
            "runtime_15_module_layout_child_summary_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary status-doc status-mirror child split",
        &[
            "runtime_15_module_layout_child_summary_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_module_layout_child_summary_status_doc_status_mirror_children_are_folder_backed",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support.rs",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary status-doc root inventory child split",
        &[
            "runtime_15_module_layout_child_summary_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/root_inventory.rs",
            "runtime_15_module_layout_child_summary_status_docs_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
];
