type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 status output review-guard row-data guard child-owner split",
        &[
            "runtime_15_status_output_review_guard_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "runtime_15_status_output_m3_review_guard_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-doc guard child-owner split",
        &[
            "runtime_15_review_guard_row_data_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs.rs",
            "runtime_15_status_output_review_guard_row_data_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data moved-row guard child-owner split",
        &[
            "runtime_15_review_guard_row_data_moved_rows_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows.rs",
            "runtime_15_status_output_m3_review_guard_row_data_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard moved-row guard folder-backed split",
        &[
            "runtime_15_review_guard_moved_row_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/typed_error_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors.rs",
            "runtime_15_status_output_m3_review_guard_row_data_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard moved-row status-mirror child split",
        &[
            "runtime_15_review_guard_moved_row_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/moved_row_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/folder_backed_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/scope_budgets.rs",
            "runtime_15_review_guard_moved_row_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard moved-row root inventory child split",
        &[
            "runtime_15_review_guard_moved_row_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/root_inventory.rs",
            "runtime_15_review_guard_row_data_moved_rows_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard moved-row code-review rows child split",
        &[
            "runtime_15_review_guard_moved_row_code_review_rows_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows/source_delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows/review_guard_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows/structure_guard_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows/typed_error_structure_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows/plugin_importer_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows/status_mirrors.rs",
            "runtime_15_review_guard_moved_row_code_review_rows_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_code_review_rows_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/root_and_children.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/export_chain.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors.rs",
            "runtime_15_review_guard_code_review_rows_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review row-data root inventory child split",
        &[
            "runtime_15_review_guard_code_review_rows_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/root_inventory.rs",
            "runtime_15_review_guard_code_review_rows_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review status-mirror child split",
        &[
            "runtime_15_review_guard_code_review_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/code_review_owner.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/structure_guard_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/folder_backed.rs",
            "runtime_15_review_guard_code_review_status_mirror_children_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer status-output guard folder-backed split",
        &[
            "runtime_15_plugin_importer_status_output_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/row_children.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/row_data_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/budgets.rs",
            "runtime_15_plugin_importer_rows_status_output_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/aggregation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/status_mirrors.rs",
            "runtime_15_review_guard_row_data_guard_is_folder_backed",
            "runtime_15_status_output_m3_review_guard_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-mirror child split",
        &[
            "runtime_15_review_guard_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/status_mirrors/folder_backed_status.rs",
            "runtime_15_review_guard_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data root inventory child split",
        &[
            "runtime_15_review_guard_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/root_inventory.rs",
            "runtime_15_review_guard_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-doc guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_status_docs_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/row_sources.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/budgets.rs",
            "runtime_15_review_guard_row_data_status_docs_guard_is_folder_backed",
            "runtime_15_status_output_review_guard_row_data_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-doc status-mirror child split",
        &[
            "runtime_15_review_guard_row_data_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/review_guard_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/status_doc_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_review_guard_row_data_status_doc_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-doc root inventory child split",
        &[
            "runtime_15_review_guard_row_data_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/root_inventory.rs",
            "runtime_15_review_guard_row_data_status_docs_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard direct-assertion row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_direct_assertion_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors.rs",
            "runtime_15_review_guard_direct_assertion_rows_guard_is_folder_backed",
            "runtime_15_status_output_review_guard_direct_assertion_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard direct-assertion status-mirror child split",
        &[
            "runtime_15_review_guard_direct_assertion_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors/child_owner_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors/folder_backed_status.rs",
            "runtime_15_review_guard_direct_assertion_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard direct-assertion row-data root inventory child split",
        &[
            "runtime_15_review_guard_direct_assertion_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/root_inventory.rs",
            "runtime_15_review_guard_direct_assertion_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
];
