type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
        (
            "Runtime 15 M3 foundation row-data status-doc guard child-owner split",
            &[
                "runtime_15_foundation_row_data_status_docs_child_owner_split_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "runtime_15_status_output_foundation_row_data_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data guard child-owner split",
        &[
            "runtime_15_m2_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "runtime_15_status_output_runtime_15_m2_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data guard folder-backed split",
        &[
            "runtime_15_m2_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/budgets.rs",
            "runtime_15_m2_row_data_guard_is_folder_backed",
            "runtime_15_status_output_runtime_15_m2_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data status-mirror child split",
        &[
            "runtime_15_m2_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/folder_backed_status.rs",
            "runtime_15_m2_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data root inventory child split",
        &[
            "runtime_15_m2_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_owner_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_inventory.rs",
            "runtime_15_m2_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-doc guard folder-backed split",
        &[
            "runtime_15_foundation_row_data_status_docs_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/doc_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count.rs",
            "runtime_15_status_output_foundation_row_data_status_docs_are_child_owner",
            "runtime_15_foundation_row_data_docs_record_current_row_count",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data row-count child split",
        &[
            "runtime_15_foundation_row_data_row_count_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/current_counts.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/priority_frontmatter.rs",
            "runtime_15_foundation_row_data_row_count_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-doc root inventory child split",
        &[
            "runtime_15_foundation_row_data_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_inventory.rs",
            "runtime_15_foundation_row_data_status_docs_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups status-doc guard child-owner split",
        &[
            "runtime_15_m3_child_groups_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "runtime_15_status_output_m3_child_group_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups status-doc guard folder-backed split",
        &[
            "runtime_15_m3_child_groups_status_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/source_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/budgets.rs",
            "runtime_15_m3_child_groups_status_docs_guard_is_folder_backed",
            "runtime_15_status_output_m3_child_group_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups status-doc status-mirror child split",
        &[
            "runtime_15_m3_child_groups_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_m3_child_group_status_doc_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups status-doc root inventory child split",
        &[
            "runtime_15_m3_child_groups_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/root_inventory.rs",
            "runtime_15_m3_child_group_status_docs_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group status-row-doc guard child-owner split",
        &[
            "runtime_15_m3_child_group_status_row_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs.rs",
            "runtime_15_status_output_m3_child_group_status_row_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group status-row-doc guard folder-backed split",
        &[
            "runtime_15_m3_child_group_status_row_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/row_sources.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors.rs",
            "runtime_15_m3_child_group_status_row_docs_guard_is_folder_backed",
            "runtime_15_status_output_m3_child_group_status_row_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group status-row-doc status-mirror child split",
        &[
            "runtime_15_m3_child_group_status_row_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/child_owner_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/m3_row_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_m3_child_group_status_row_doc_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group status-row-doc root inventory child split",
        &[
            "runtime_15_m3_child_group_status_row_docs_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/root_inventory.rs",
            "runtime_15_m3_child_group_status_row_docs_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group moved-row guard child-owner split",
        &[
            "runtime_15_m3_child_group_moved_row_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows.rs",
            "runtime_15_status_output_m3_child_group_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group moved-row guard folder-backed split",
        &[
            "runtime_15_m3_child_group_moved_row_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/lock_poison_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/module_convention_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/review_top_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/budgets.rs",
            "runtime_15_m3_child_group_moved_rows_guard_is_folder_backed",
            "runtime_15_status_output_m3_child_group_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group moved-row status-mirror child split",
        &[
            "runtime_15_m3_child_group_moved_row_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/status_mirrors/folder_backed_status.rs",
            "runtime_15_m3_child_group_moved_row_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group moved-row root inventory child split",
        &[
            "runtime_15_m3_child_group_moved_row_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/root_inventory.rs",
            "runtime_15_m3_child_group_moved_rows_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
];
