stylesheets = []

[asset]
kind = "layout"
id = "editor.host.pane.inspector.body"
version = 1
display_name = "inspector pane body"

[imports]
widgets = ["res://ui/editor/material_meta_components.ui.toml#MaterialButton"]
styles = []

[tokens]

[root]
node_id = "root"
kind = "component"
component = "InspectorPaneBody"

[components.InspectorPaneBody]
style_scope = "closed"

[components.InspectorPaneBody.root]
node_id = "inspector_pane_body_root"
kind = "native"
type = "VerticalBox"
children = [
  { node = { node_id = "inspector_header", kind = "native", type = "HorizontalBox", children = [
    { node = { node_id = "inspector_header_apply_draft_action", kind = "reference", component_ref = "res://ui/editor/material_meta_components.ui.toml#MaterialButton", control_id = "ApplyDraft", bindings = [{ id = "InspectorPaneBody/ApplyDraft", event = "Click", route = "DraftCommand.SetInspectorField" }], params = { text = "Apply Draft", height = 27.2 }, layout = { width = { min = 106.0, preferred = 106.0, max = 106.0, stretch = "Fixed" }, height = { min = 27.2, preferred = 27.2, max = 27.2, stretch = "Fixed" } } } }
  ] } },
  { node = { node_id = "inspector_body_section", kind = "native", type = "Container", control_id = "InspectorBodySection" } },
]
