//! 宿主生命周期把模板事件副作用、失效事务、重算、原生窗口同步和启动装配接到同一帧循环。
mod dispatch_effects;
mod invalidation_bridge;
mod native_window_presenters;
mod pane_payloads;
mod recompute;
mod recompute_viewport;
mod render_submission;
mod scene_hierarchy_refresh;
mod shell_metrics;
mod startup;
mod tick;
