use crate::settings::HubLanguage;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProjectMessageId {
    LocationMustBeAbsolute,
    PathMustBeAbsolute,
    ImportPathMustBeAbsolute,
    ImportFolderMustBeAbsolute,
    UnknownTemplate,
    TemplateComingSoon,
    FolderDoesNotExist,
    ManifestNotFound,
    ManifestParseFailed,
    FolderCreatedButRecordFailed,
    RootInvalid,
    NoBoundSourceEngine,
    BoundSourceEngineUnavailable,
    CreatedPath,
    ImportedPath,
    ShowingAllRecentProjects,
    ShowingFilter,
    SortingBy,
    NoRecentProjectToBuild,
    SelectedProjectStaleForBuild,
    NoRecentProjectToPackage,
    SelectedProjectStaleForPackage,
    NoRecentProjectToInstall,
    SelectedProjectStaleForInstall,
    SelectProjectBeforePackaging,
    SelectProjectBeforeInstalling,
    CheckProjectManifest,
    FillCreateProjectFields,
    ChooseRenderableTemplate,
    RegisterEngineBeforeCreate,
    ChooseEmptyTargetFolder,
    ExistingFolderUseImport,
    KeptFolderUseImport,
    ChooseFolderWithManifest,
    NoProjectFolderSelected,
    RunImportAgain,
    RegisterEngineBeforeImport,
    RemovedFromHub,
    FilesLeftOnDisk,
    ConfirmDeleteRecycleBin,
    CancelDeleteUnchanged,
    ProjectUnchanged,
    MovedToRecycleBin,
    DeletionFailureRecovery,
    WindowsDeletionOnly,
    RecycleUnsupported,
    ProjectRootRequired,
    TargetPathIsFile,
    TargetDirectoryMustBeEmpty,
    ProjectPathRequired,
}

impl ProjectMessageId {
    pub const ALL: &'static [Self] = &[
        Self::LocationMustBeAbsolute,
        Self::PathMustBeAbsolute,
        Self::ImportPathMustBeAbsolute,
        Self::ImportFolderMustBeAbsolute,
        Self::UnknownTemplate,
        Self::TemplateComingSoon,
        Self::FolderDoesNotExist,
        Self::ManifestNotFound,
        Self::ManifestParseFailed,
        Self::FolderCreatedButRecordFailed,
        Self::RootInvalid,
        Self::NoBoundSourceEngine,
        Self::BoundSourceEngineUnavailable,
        Self::CreatedPath,
        Self::ImportedPath,
        Self::ShowingAllRecentProjects,
        Self::ShowingFilter,
        Self::SortingBy,
        Self::NoRecentProjectToBuild,
        Self::SelectedProjectStaleForBuild,
        Self::NoRecentProjectToPackage,
        Self::SelectedProjectStaleForPackage,
        Self::NoRecentProjectToInstall,
        Self::SelectedProjectStaleForInstall,
        Self::SelectProjectBeforePackaging,
        Self::SelectProjectBeforeInstalling,
        Self::CheckProjectManifest,
        Self::FillCreateProjectFields,
        Self::ChooseRenderableTemplate,
        Self::RegisterEngineBeforeCreate,
        Self::ChooseEmptyTargetFolder,
        Self::ExistingFolderUseImport,
        Self::KeptFolderUseImport,
        Self::ChooseFolderWithManifest,
        Self::NoProjectFolderSelected,
        Self::RunImportAgain,
        Self::RegisterEngineBeforeImport,
        Self::RemovedFromHub,
        Self::FilesLeftOnDisk,
        Self::ConfirmDeleteRecycleBin,
        Self::CancelDeleteUnchanged,
        Self::ProjectUnchanged,
        Self::MovedToRecycleBin,
        Self::DeletionFailureRecovery,
        Self::WindowsDeletionOnly,
        Self::RecycleUnsupported,
        Self::ProjectRootRequired,
        Self::TargetPathIsFile,
        Self::TargetDirectoryMustBeEmpty,
        Self::ProjectPathRequired,
    ];

    pub(super) fn as_str(self) -> &'static str {
        match self {
            Self::LocationMustBeAbsolute => "project.location-must-be-absolute",
            Self::PathMustBeAbsolute => "project.path-must-be-absolute",
            Self::ImportPathMustBeAbsolute => "project.import-path-must-be-absolute",
            Self::ImportFolderMustBeAbsolute => "project.import-folder-must-be-absolute",
            Self::UnknownTemplate => "project.unknown-template",
            Self::TemplateComingSoon => "project.template-coming-soon",
            Self::FolderDoesNotExist => "project.folder-does-not-exist",
            Self::ManifestNotFound => "project.manifest-not-found",
            Self::ManifestParseFailed => "project.manifest-parse-failed",
            Self::FolderCreatedButRecordFailed => "project.folder-created-but-record-failed",
            Self::RootInvalid => "project.root-invalid",
            Self::NoBoundSourceEngine => "project.no-bound-source-engine",
            Self::BoundSourceEngineUnavailable => "project.bound-source-engine-unavailable",
            Self::CreatedPath => "project.created-path",
            Self::ImportedPath => "project.imported-path",
            Self::ShowingAllRecentProjects => "project.showing-all-recent-projects",
            Self::ShowingFilter => "project.showing-filter",
            Self::SortingBy => "project.sorting-by",
            Self::NoRecentProjectToBuild => "project.no-recent-project-to-build",
            Self::SelectedProjectStaleForBuild => "project.selected-project-stale-for-build",
            Self::NoRecentProjectToPackage => "project.no-recent-project-to-package",
            Self::SelectedProjectStaleForPackage => "project.selected-project-stale-for-package",
            Self::NoRecentProjectToInstall => "project.no-recent-project-to-install",
            Self::SelectedProjectStaleForInstall => "project.selected-project-stale-for-install",
            Self::SelectProjectBeforePackaging => "project.select-project-before-packaging",
            Self::SelectProjectBeforeInstalling => "project.select-project-before-installing",
            Self::CheckProjectManifest => "project.check-project-manifest",
            Self::FillCreateProjectFields => "project.fill-create-project-fields",
            Self::ChooseRenderableTemplate => "project.choose-renderable-template",
            Self::RegisterEngineBeforeCreate => "project.register-engine-before-create",
            Self::ChooseEmptyTargetFolder => "project.choose-empty-target-folder",
            Self::ExistingFolderUseImport => "project.existing-folder-use-import",
            Self::KeptFolderUseImport => "project.kept-folder-use-import",
            Self::ChooseFolderWithManifest => "project.choose-folder-with-manifest",
            Self::NoProjectFolderSelected => "project.no-project-folder-selected",
            Self::RunImportAgain => "project.run-import-again",
            Self::RegisterEngineBeforeImport => "project.register-engine-before-import",
            Self::RemovedFromHub => "project.removed-from-hub",
            Self::FilesLeftOnDisk => "project.files-left-on-disk",
            Self::ConfirmDeleteRecycleBin => "project.confirm-delete-recycle-bin",
            Self::CancelDeleteUnchanged => "project.cancel-delete-unchanged",
            Self::ProjectUnchanged => "project.project-unchanged",
            Self::MovedToRecycleBin => "project.moved-to-recycle-bin",
            Self::DeletionFailureRecovery => "project.deletion-failure-recovery",
            Self::WindowsDeletionOnly => "project.windows-deletion-only",
            Self::RecycleUnsupported => "project.recycle-unsupported",
            Self::ProjectRootRequired => "project.root-required",
            Self::TargetPathIsFile => "project.target-path-is-file",
            Self::TargetDirectoryMustBeEmpty => "project.target-directory-must-be-empty",
            Self::ProjectPathRequired => "project.path-required",
        }
    }

    pub(super) fn param_count(self) -> usize {
        match self {
            Self::LocationMustBeAbsolute
            | Self::PathMustBeAbsolute
            | Self::ImportPathMustBeAbsolute
            | Self::ImportFolderMustBeAbsolute
            | Self::UnknownTemplate
            | Self::TemplateComingSoon
            | Self::FolderDoesNotExist
            | Self::ManifestNotFound
            | Self::ManifestParseFailed
            | Self::RootInvalid
            | Self::NoBoundSourceEngine
            | Self::BoundSourceEngineUnavailable
            | Self::CreatedPath
            | Self::ImportedPath
            | Self::ShowingFilter
            | Self::SortingBy => 1,
            Self::FolderCreatedButRecordFailed => 2,
            _ => 0,
        }
    }

    pub(super) fn template(self, language: HubLanguage) -> &'static str {
        match (language, self) {
            (HubLanguage::English, Self::LocationMustBeAbsolute) => "Project location must be an absolute path: {0}",
            (HubLanguage::Chinese, Self::LocationMustBeAbsolute) => "项目位置必须是绝对路径：{0}",
            (HubLanguage::English, Self::PathMustBeAbsolute) => "Project path must be an absolute path: {0}",
            (HubLanguage::Chinese, Self::PathMustBeAbsolute) => "项目路径必须是绝对路径：{0}",
            (HubLanguage::English, Self::ImportPathMustBeAbsolute) => "Import path must be an absolute path: {0}",
            (HubLanguage::Chinese, Self::ImportPathMustBeAbsolute) => "导入路径必须是绝对路径：{0}",
            (HubLanguage::English, Self::ImportFolderMustBeAbsolute) => "Import folder must be an absolute path: {0}",
            (HubLanguage::Chinese, Self::ImportFolderMustBeAbsolute) => "导入文件夹必须是绝对路径：{0}",
            (HubLanguage::English, Self::UnknownTemplate) => "Unknown project template: {0}",
            (HubLanguage::Chinese, Self::UnknownTemplate) => "未知项目模板：{0}",
            (HubLanguage::English, Self::TemplateComingSoon) => "Project template is coming soon: {0}",
            (HubLanguage::Chinese, Self::TemplateComingSoon) => "项目模板尚未开放：{0}",
            (HubLanguage::English, Self::FolderDoesNotExist) => "Project folder does not exist: {0}",
            (HubLanguage::Chinese, Self::FolderDoesNotExist) => "项目文件夹不存在：{0}",
            (HubLanguage::English, Self::ManifestNotFound) => "zircon-project.toml was not found in {0}",
            (HubLanguage::Chinese, Self::ManifestNotFound) => "未在 {0} 找到 zircon-project.toml",
            (HubLanguage::English, Self::ManifestParseFailed) => "zircon-project.toml could not be parsed in {0}",
            (HubLanguage::Chinese, Self::ManifestParseFailed) => "无法解析 {0} 中的 zircon-project.toml",
            (HubLanguage::English, Self::FolderCreatedButRecordFailed) => "Project folder was created at {0} but Hub failed to record it: {1}",
            (HubLanguage::Chinese, Self::FolderCreatedButRecordFailed) => "项目目录已创建于 {0}，但 Hub 记录失败：{1}",
            (HubLanguage::English, Self::RootInvalid) => "Project root is not valid: {0}",
            (HubLanguage::Chinese, Self::RootInvalid) => "项目根目录无效：{0}",
            (HubLanguage::English, Self::NoBoundSourceEngine) => "Project has no bound Source Engine: {0}",
            (HubLanguage::Chinese, Self::NoBoundSourceEngine) => "项目未绑定源码引擎：{0}",
            (HubLanguage::English, Self::BoundSourceEngineUnavailable) => "Project bound Source Engine is unavailable: {0}",
            (HubLanguage::Chinese, Self::BoundSourceEngineUnavailable) => "项目绑定的源码引擎不可用：{0}",
            (HubLanguage::English, Self::CreatedPath) => "Created {0}",
            (HubLanguage::Chinese, Self::CreatedPath) => "已创建 {0}",
            (HubLanguage::English, Self::ImportedPath) => "Imported {0}",
            (HubLanguage::Chinese, Self::ImportedPath) => "已导入 {0}",
            (HubLanguage::English, Self::ShowingAllRecentProjects) => "Showing all recent projects",
            (HubLanguage::Chinese, Self::ShowingAllRecentProjects) => "显示全部最近项目",
            (HubLanguage::English, Self::ShowingFilter) => "Showing {0}",
            (HubLanguage::Chinese, Self::ShowingFilter) => "显示{0}",
            (HubLanguage::English, Self::SortingBy) => "Sorting by {0}",
            (HubLanguage::Chinese, Self::SortingBy) => "按{0}排序",
            (HubLanguage::English, Self::NoRecentProjectToBuild) => "No recent project is available to build",
            (HubLanguage::Chinese, Self::NoRecentProjectToBuild) => "没有可用于构建的最近项目",
            (HubLanguage::English, Self::SelectedProjectStaleForBuild) => "Selected project is no longer available to build",
            (HubLanguage::Chinese, Self::SelectedProjectStaleForBuild) => "已选项目不再可用于构建",
            (HubLanguage::English, Self::NoRecentProjectToPackage) => "No recent project is available to package",
            (HubLanguage::Chinese, Self::NoRecentProjectToPackage) => "没有可用于打包的最近项目",
            (HubLanguage::English, Self::SelectedProjectStaleForPackage) => "Selected project is no longer available to package",
            (HubLanguage::Chinese, Self::SelectedProjectStaleForPackage) => "已选项目不再可用于打包",
            (HubLanguage::English, Self::NoRecentProjectToInstall) => "No recent project is available to install",
            (HubLanguage::Chinese, Self::NoRecentProjectToInstall) => "没有可用于安装的最近项目",
            (HubLanguage::English, Self::SelectedProjectStaleForInstall) => "Selected project is no longer available to install",
            (HubLanguage::Chinese, Self::SelectedProjectStaleForInstall) => "已选项目不再可用于安装",
            (HubLanguage::English, Self::SelectProjectBeforePackaging) => "Select an available project before packaging",
            (HubLanguage::Chinese, Self::SelectProjectBeforePackaging) => "打包前先选择一个可用项目",
            (HubLanguage::English, Self::SelectProjectBeforeInstalling) => "Select a valid project and package it before installing to a device",
            (HubLanguage::Chinese, Self::SelectProjectBeforeInstalling) => "安装到设备前先选择一个有效项目并完成打包",
            (HubLanguage::English, Self::CheckProjectManifest) => "Check that the selected project directory contains a Zircon project manifest",
            (HubLanguage::Chinese, Self::CheckProjectManifest) => "检查已选项目目录是否包含 Zircon 项目清单",
            (HubLanguage::English, Self::FillCreateProjectFields) => "Fill in a project name, location, enabled template, and Source Engine before creating",
            (HubLanguage::Chinese, Self::FillCreateProjectFields) => "创建前填写项目名称、位置、已启用模板和源码引擎",
            (HubLanguage::English, Self::ChooseRenderableTemplate) => "Choose the Renderable Empty template for v1 local project creation",
            (HubLanguage::Chinese, Self::ChooseRenderableTemplate) => "v1 本地项目创建请选择“可渲染空项目”模板",
            (HubLanguage::English, Self::RegisterEngineBeforeCreate) => "Register or select a Source Engine before creating the project",
            (HubLanguage::Chinese, Self::RegisterEngineBeforeCreate) => "创建项目前先注册或选择源码引擎",
            (HubLanguage::English, Self::ChooseEmptyTargetFolder) => "Choose an empty target folder and retry project creation",
            (HubLanguage::Chinese, Self::ChooseEmptyTargetFolder) => "选择一个空目标文件夹后重试项目创建",
            (HubLanguage::English, Self::ExistingFolderUseImport) => "If the folder already contains a project, use Import Project; otherwise choose an empty target folder",
            (HubLanguage::Chinese, Self::ExistingFolderUseImport) => "目标文件夹已有内容：若它已是 Zircon 项目请改用「导入项目」，否则请选择空文件夹",
            (HubLanguage::English, Self::KeptFolderUseImport) => "The project folder was kept on disk; use Import Project to add it to Hub",
            (HubLanguage::Chinese, Self::KeptFolderUseImport) => "项目目录已保留在磁盘上，可通过「导入项目」将其加入 Hub",
            (HubLanguage::English, Self::ChooseFolderWithManifest) => "Choose a folder containing zircon-project.toml",
            (HubLanguage::Chinese, Self::ChooseFolderWithManifest) => "选择包含 zircon-project.toml 的文件夹",
            (HubLanguage::English, Self::NoProjectFolderSelected) => "No project folder was selected",
            (HubLanguage::Chinese, Self::NoProjectFolderSelected) => "未选择项目文件夹",
            (HubLanguage::English, Self::RunImportAgain) => "Run Import Project again and choose a Zircon project folder",
            (HubLanguage::Chinese, Self::RunImportAgain) => "重新运行导入项目并选择 Zircon 项目文件夹",
            (HubLanguage::English, Self::RegisterEngineBeforeImport) => "Register or select a Source Engine before importing the project",
            (HubLanguage::Chinese, Self::RegisterEngineBeforeImport) => "导入项目前先注册或选择源码引擎",
            (HubLanguage::English, Self::RemovedFromHub) => "Removed project from Hub recent list",
            (HubLanguage::Chinese, Self::RemovedFromHub) => "已从 Hub 最近项目列表移除",
            (HubLanguage::English, Self::FilesLeftOnDisk) => "Project files were left on disk",
            (HubLanguage::Chinese, Self::FilesLeftOnDisk) => "项目文件已保留在磁盘上",
            (HubLanguage::English, Self::ConfirmDeleteRecycleBin) => "Confirm delete to move the project to the Windows Recycle Bin",
            (HubLanguage::Chinese, Self::ConfirmDeleteRecycleBin) => "确认删除会将项目移动到 Windows 回收站",
            (HubLanguage::English, Self::CancelDeleteUnchanged) => "Cancel delete to leave the project unchanged",
            (HubLanguage::Chinese, Self::CancelDeleteUnchanged) => "取消删除以保持项目不变",
            (HubLanguage::English, Self::ProjectUnchanged) => "Project was left unchanged",
            (HubLanguage::Chinese, Self::ProjectUnchanged) => "项目保持不变",
            (HubLanguage::English, Self::MovedToRecycleBin) => "Moved project to Windows Recycle Bin",
            (HubLanguage::Chinese, Self::MovedToRecycleBin) => "已将项目移动到 Windows 回收站",
            (HubLanguage::English, Self::DeletionFailureRecovery) => "The project remains in Hub; fix the filesystem issue or cancel delete",
            (HubLanguage::Chinese, Self::DeletionFailureRecovery) => "项目仍保留在 Hub 中；修复文件系统问题或取消删除",
            (HubLanguage::English, Self::WindowsDeletionOnly) => "Project deletion is only available on Windows in this Hub build",
            (HubLanguage::Chinese, Self::WindowsDeletionOnly) => "当前 Hub 构建仅支持在 Windows 上将项目移入回收站",
            (HubLanguage::English, Self::RecycleUnsupported) => "Recycle Bin deletion is not supported on this platform; delete the folder manually, then use Remove from Hub",
            (HubLanguage::Chinese, Self::RecycleUnsupported) => "当前平台不支持回收站删除：请手动删除项目文件夹，再使用「从 Hub 移除」",
            (HubLanguage::English, Self::ProjectRootRequired) => "Project root is required",
            (HubLanguage::Chinese, Self::ProjectRootRequired) => "需要项目根目录",
            (HubLanguage::English, Self::TargetPathIsFile) => "Target path already exists as a file",
            (HubLanguage::Chinese, Self::TargetPathIsFile) => "目标路径已作为文件存在",
            (HubLanguage::English, Self::TargetDirectoryMustBeEmpty) => "Target directory must be empty",
            (HubLanguage::Chinese, Self::TargetDirectoryMustBeEmpty) => "目标目录必须为空",
            (HubLanguage::English, Self::ProjectPathRequired) => "Project path is required",
            (HubLanguage::Chinese, Self::ProjectPathRequired) => "需要项目路径",
        }
    }
}
