use super::*;

#[test]
fn runtime_15_status_support_row_data_export_chain_is_current() {
    let top_level = read_runtime_src(TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15 = read_runtime_src(RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15_m3 = read_runtime_src(RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH);

    assert_contains_all(
        "Runtime 15 M3 exposes every status-support child group",
        &runtime_15_m3,
        &[
            "STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_EXPECTED_SLICE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 row-data parent exports every status-support child group",
        &runtime_15,
        &[
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "top-level expected status row data consumes every status-support child group",
        &top_level,
        &[
            "runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
}
