use super::*;

pub(super) const STATUS_SUPPORT_ROW_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data.rs",
        STATUS_SUPPORT_ROW_DATA_GUARD_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/root_paths.rs",
        ROOT_PATHS_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        160,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support.rs",
        STATUS_SUPPORT_ROWS_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget.rs",
        STATUS_SUPPORT_ROW_DATA_AND_BUDGET_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget/test_file_budget.rs",
        STATUS_SUPPORT_ROW_DATA_TEST_FILE_BUDGET_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget/runtime_row_data.rs",
        STATUS_SUPPORT_ROW_DATA_RUNTIME_ROW_DATA_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget/hub_editor_support.rs",
        STATUS_SUPPORT_ROW_DATA_HUB_EDITOR_SUPPORT_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget/render_shader_support.rs",
        STATUS_SUPPORT_ROW_DATA_RENDER_SHADER_SUPPORT_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget/m3_m4_row_data.rs",
        STATUS_SUPPORT_ROW_DATA_M3_M4_ROW_DATA_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps.rs",
        STATUS_SUPPORT_EXPECTED_SLICE_MAPS_PATH,
        160,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/runtime_index_anchors.rs",
        STATUS_SUPPORT_RUNTIME_INDEX_ANCHORS_PATH,
        220,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs.rs",
        STATUS_SUPPORT_PRIORITY_PLAN_DOCS_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs/integrity_guards.rs",
        PRIORITY_PLAN_DOCS_INTEGRITY_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs/owner_guards.rs",
        PRIORITY_PLAN_DOCS_OWNER_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs/status_followups.rs",
        PRIORITY_PLAN_DOCS_FOLLOWUPS_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs/row_data_owner.rs",
        PRIORITY_PLAN_DOCS_ROW_DATA_PATH,
        80,
    ),
];
