use super::*;

pub(super) const M4_ROW_DATA_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data_children.rs",
        M4_ROW_DATA_CHILDREN_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data_children/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data_children/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data_children/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data_children/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        130,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data_children/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4.rs",
        RUNTIME_15_M4_EXPECTED_STATUS_ROW_DATA_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4/core_rhi_dynamic.rs",
        RUNTIME_15_M4_CORE_RHI_DYNAMIC_ROW_DATA_PATH,
        160,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4/asset_scene_render.rs",
        RUNTIME_15_M4_ASSET_SCENE_RENDER_ROW_DATA_PATH,
        180,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4/ui_text_template.rs",
        RUNTIME_15_M4_UI_TEXT_TEMPLATE_ROW_DATA_PATH,
        180,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4/ui_surface_plugin.rs",
        RUNTIME_15_M4_UI_SURFACE_PLUGIN_ROW_DATA_PATH,
        160,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4/row_data_owner.rs",
        RUNTIME_15_M4_ROW_DATA_OWNER_PATH,
        130,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4/render_shader_sync.rs",
        RUNTIME_15_M4_RENDER_SHADER_SYNC_ROW_DATA_PATH,
        120,
    ),
];
