use super::*;

pub(in super::super) const REVIEW_GUARD_ROW_DATA_CHILDREN: &[(&str, &str, &str)] = &[
    (
        "delegation",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation.rs",
        DELEGATION_GUARD_FOLDER_BACKED_GUARD_NAME,
    ),
    (
        "moved_rows",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/moved_rows.rs",
        "runtime_15_review_guard_row_data_moved_rows_are_child_owned",
    ),
    (
        "aggregation",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation.rs",
        AGGREGATION_CHILD_SPLIT_GUARD_NAME,
    ),
    (
        "budgets",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/budgets.rs",
        "runtime_15_review_guard_row_data_child_budgets_stay_focused",
    ),
    (
        "status_mirrors",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/status_mirrors.rs",
        "runtime_15_review_guard_row_data_status_mirror_children_are_child_owned",
    ),
    (
        "typed_error_rows",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/typed_error_rows.rs",
        TYPED_ERROR_ROWS_GUARD_FOLDER_BACKED_GUARD_NAME,
    ),
    (
        "root_inventory",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_inventory.rs",
        ROOT_INVENTORY_GUARD_NAME,
    ),
];
