use super::super::super::super::*;
use super::*;

pub(super) fn assert_plugin_importer_dx_status_doc_mirrors_are_synced(
    sources: &PluginImporterDxStatusDocSources,
) {
    for (label, source) in [
        ("Runtime 15 plan", sources.runtime_15_plan.as_str()),
        ("Runtime index", sources.runtime_index.as_str()),
        ("review findings", sources.review_findings.as_str()),
        (
            "structure convention",
            sources.structure_convention.as_str(),
        ),
        ("module convention doc", sources.module_doc.as_str()),
        ("status-output row data", sources.status_rows.as_str()),
    ] {
        assert_contains_all(
            label,
            source,
            &[
                "Runtime 15 M3 code review findings plugin-importer DX structure guard child-owner split",
                "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
                PLUGIN_IMPORTER_DX_STATUS_DOC_SLICE,
                PLUGIN_IMPORTER_DX_STATUS_DOC_STATUS,
                "Runtime 15 M3 plugin-importer DX source inventory guard child-owner split",
                "runtime_15_plugin_importer_dx_source_inventory_guard_child_owner_split_static_passed_cargo_deferred",
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_SLICE,
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_STATUS,
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_FOLDER_SLICE,
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_FOLDER_STATUS,
                PLUGIN_IMPORTER_D13_STRUCTURE_ASSERTIONS_SLICE,
                PLUGIN_IMPORTER_D13_STRUCTURE_ASSERTIONS_STATUS,
                "Runtime 15 M3 plugin-importer DX review guard child-owner split",
                "runtime_15_plugin_importer_dx_review_guard_child_owner_split_static_passed_cargo_deferred",
                "Runtime 15 M3 plugin-importer D13 SDK review guard child-owner split",
                "runtime_15_plugin_importer_d13_sdk_review_guard_child_owner_split_static_passed_cargo_deferred",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings.rs",
                PLUGIN_IMPORTER_DX_STRUCTURE_CHILD_OWNER,
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_OWNER,
                PLUGIN_IMPORTER_DX_REVIEW_MOUNTS_OWNER,
                PLUGIN_IMPORTER_DX_STRUCTURE_DELEGATION_OWNER,
                PLUGIN_IMPORTER_DX_STRUCTURE_CHILD_OWNERSHIP_OWNER,
                PLUGIN_IMPORTER_DX_STRUCTURE_STATUS_MIRRORS_OWNER,
                PLUGIN_IMPORTER_D13_STRUCTURE_ASSERTIONS_OWNER,
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/source_inventory.rs",
                PLUGIN_IMPORTER_DX_STATUS_DOC_OWNER,
                "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_GUARD,
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_CHILD_GUARD,
                PLUGIN_IMPORTER_DX_STRUCTURE_ASSERTIONS_FOLDER_GUARD,
                PLUGIN_IMPORTER_D13_STRUCTURE_ASSERTIONS_GUARD,
                "runtime_15_plugin_importer_dx_source_inventory_is_child_owner",
                PLUGIN_IMPORTER_DX_STATUS_DOC_GUARD,
                "runtime_15_code_review_findings_tests_are_folder_backed",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/manifest_parity.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_crates.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_exports.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_manifests.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d5_editor_authoring.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d8_registration_builder.rs",
                "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d9_editor_runtime_mirror.rs",
                "review_d10_animation_physics_tests_use_sdk_bridge_call",
                "review_d5_editor_authoring_plugins_use_sdk_macro",
                "review_d8_runtime_registration_builder_original_evidence_paths_use_sdk_builder",
                "review_d9_editor_runtime_mirror_consumers_use_sdk_declaration",
                "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
                "Cargo gate deferred",
            ],
        );
    }
}
