type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 generated-code guard folder-backed split",
        &[
            "runtime_15_generated_code_guard_folder_backed_static_passed_cargo_deferred",
            "generated_code_guard.rs",
            "generated_code_guard/behavior.rs",
            "generated_code_guard/delegation.rs",
            "generated_code_guard/markers.rs",
            "generated_code_guard/scope.rs",
            "generated_code_guard/support.rs",
            "generated_code_guard/split_layout.rs",
            "runtime_15_generated_code_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 input-stack absorption guard folder-backed split",
        &[
            "runtime_15_input_stack_absorption_guard_folder_backed_static_passed_cargo_deferred",
            "input_stack.rs",
            "input_stack/action_mapping.rs",
            "input_stack/contracts.rs",
            "input_stack/gamepad_bridge.rs",
            "input_stack/inventory.rs",
            "input_stack/split_layout.rs",
            "input_stack/support.rs",
            "runtime_15_input_stack_absorption_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 input-stack inventory guard folder-backed split",
        &[
            "runtime_15_input_stack_inventory_guard_folder_backed_static_passed_cargo_deferred",
            "input_stack/inventory.rs",
            "input_stack/inventory/module_sets.rs",
            "input_stack/inventory/public_surface.rs",
            "input_stack/inventory/guard_anchors.rs",
            "input_stack/inventory/behavior_anchors.rs",
            "input_stack/inventory/cursor_host_requests.rs",
            "input_stack/inventory/mirror_docs.rs",
            "input_stack/inventory/split_layout.rs",
            "runtime_15_input_stack_inventory_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 ECS kernel data guard folder-backed split",
        &[
            "runtime_15_ecs_kernel_data_guard_folder_backed_static_passed_cargo_deferred",
            "ecs_kernel_data.rs",
            "ecs_kernel_data/component_storage.rs",
            "ecs_kernel_data/docs.rs",
            "ecs_kernel_data/guard_coverage.rs",
            "ecs_kernel_data/identity_storage.rs",
            "ecs_kernel_data/inventory.rs",
            "ecs_kernel_data/runtime_flow.rs",
            "ecs_kernel_data/split_layout.rs",
            "ecs_kernel_data/support.rs",
            "runtime_15_ecs_kernel_data_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 script host ledger guard folder-backed split",
        &[
            "runtime_15_script_host_ledger_guard_folder_backed_static_passed_cargo_deferred",
            "script_host_ledger.rs",
            "script_host_ledger/capability.rs",
            "script_host_ledger/capability_fixture.rs",
            "script_host_ledger/catalog.rs",
            "script_host_ledger/ecs_facade.rs",
            "script_host_ledger/ledger.rs",
            "script_host_ledger/split_layout.rs",
            "runtime_15_script_host_ledger_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 dynamic API session shared data folder-backed split",
        &[
            "runtime_15_dynamic_api_session_shared_data_folder_backed_static_passed_cargo_deferred",
            "dynamic_api_session/shared.rs",
            "dynamic_api_session/shared/abi.rs",
            "dynamic_api_session/shared/behavior.rs",
            "dynamic_api_session/shared/diagnostics.rs",
            "dynamic_api_session/shared/docs.rs",
            "dynamic_api_session/shared/host_requests.rs",
            "dynamic_api_session/shared/slices.rs",
            "dynamic_api_session/shared/source_inventory.rs",
            "dynamic_api_session/shared/split_layout.rs",
            "runtime_15_dynamic_api_session_shared_data_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin surface lifecycle guard folder-backed split",
        &[
            "runtime_15_plugin_surface_lifecycle_guard_folder_backed_static_passed_cargo_deferred",
            "plugin_surface_lifecycle.rs",
            "plugin_surface_lifecycle/inventory.rs",
            "plugin_surface_lifecycle/lifecycle_fallback.rs",
            "plugin_surface_lifecycle/mirror_docs.rs",
            "plugin_surface_lifecycle/native_loader_namespace.rs",
            "plugin_surface_lifecycle/split_layout.rs",
            "plugin_surface_lifecycle/support.rs",
            "runtime_15_plugin_surface_lifecycle_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
