use super::super::super::super::*;

pub(in super::super) const M3_CHILD_GROUP_PLAN_STATUS_UI_TEST_ROW_PATHS: &[(&str, &str, usize)] = &[
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_first.rs",
        UI_TESTS_FIRST_ROW_DATA_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_first/architecture_shared_rows.rs",
        UI_TESTS_FIRST_ARCHITECTURE_SHARED_ROWS_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_first/accessibility_surface_rows.rs",
        UI_TESTS_FIRST_ACCESSIBILITY_SURFACE_ROWS_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_first/template_input_rows.rs",
        UI_TESTS_FIRST_TEMPLATE_INPUT_ROWS_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_first/row_data_owner.rs",
        UI_TESTS_FIRST_ROW_DATA_OWNER_ROWS_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_second.rs",
        UI_TESTS_SECOND_ROW_DATA_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_second/component_boundary_rows.rs",
        UI_TESTS_SECOND_COMPONENT_BOUNDARY_ROWS_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_second/asset_style_rows.rs",
        UI_TESTS_SECOND_ASSET_STYLE_ROWS_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_second/runtime_input_rows.rs",
        UI_TESTS_SECOND_RUNTIME_INPUT_ROWS_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/ui_tests_second/row_data_owner.rs",
        UI_TESTS_SECOND_ROW_DATA_OWNER_ROWS_PATH,
        80,
    ),
];
