use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const GAMEPLAY_STATE_BINDINGS: &[ExtensionBindingSpec] = &[
    click(
        "SpawnRulesEnemyRow",
        "workbench.extension.spawn_rules.enemy_row.select",
    ),
    click(
        "SpawnRulesZoneARow",
        "workbench.extension.spawn_rules.zone_a_row.select",
    ),
    click(
        "SpawnRulesConditionNightRow",
        "workbench.extension.spawn_rules.condition_night_row.select",
    ),
    click(
        "SpawnRulesZoneATableRow",
        "workbench.extension.spawn_rules.zone_a_table_row.select",
    ),
    click(
        "SpawnRulesConditionNightTableRow",
        "workbench.extension.spawn_rules.condition_night_table_row.select",
    ),
    click(
        "SpawnRulesTagCombatTableRow",
        "workbench.extension.spawn_rules.tag_combat_table_row.select",
    ),
    click(
        "SpawnRulesConflictTableRow",
        "workbench.extension.spawn_rules.conflict_table_row.select",
    ),
    click(
        "SpawnRulesSimulate",
        "workbench.extension.spawn_rules.simulate.invoke",
    ),
    click(
        "SpawnRulesValidate",
        "workbench.extension.spawn_rules.validate.invoke",
    ),
    change(
        "SpawnRulesRuleSetEdit",
        "workbench.extension.spawn_rules.rule_set.edit",
    ),
    submit(
        "SpawnRulesRuleSetCommit",
        "workbench.extension.spawn_rules.rule_set.commit",
    ),
    change(
        "SpawnRulesAuthorityEdit",
        "workbench.extension.spawn_rules.authority.edit",
    ),
    submit(
        "SpawnRulesAuthorityCommit",
        "workbench.extension.spawn_rules.authority.commit",
    ),
    change(
        "SpawnRulesSeedEdit",
        "workbench.extension.spawn_rules.seed.edit",
    ),
    submit(
        "SpawnRulesSeedCommit",
        "workbench.extension.spawn_rules.seed.commit",
    ),
    click(
        "WorldStateNightRaidRow",
        "workbench.extension.world_state.night_raid_row.select",
    ),
    click(
        "WorldStateGlobalLayerRow",
        "workbench.extension.world_state.global_layer_row.select",
    ),
    click(
        "WorldStateAlarmKeyRow",
        "workbench.extension.world_state.alarm_key_row.select",
    ),
    click(
        "WorldStateAlarmActiveTableRow",
        "workbench.extension.world_state.alarm_active_table_row.select",
    ),
    click(
        "WorldStateWeatherModeTableRow",
        "workbench.extension.world_state.weather_mode_table_row.select",
    ),
    click(
        "WorldStateAiAlertTableRow",
        "workbench.extension.world_state.ai_alert_table_row.select",
    ),
    click(
        "WorldStateQuestFlagTableRow",
        "workbench.extension.world_state.quest_flag_table_row.select",
    ),
    click(
        "WorldStateSimulate",
        "workbench.extension.world_state.simulate.invoke",
    ),
    click(
        "WorldStateValidate",
        "workbench.extension.world_state.validate.invoke",
    ),
    change(
        "WorldStateScenarioEdit",
        "workbench.extension.world_state.scenario.edit",
    ),
    submit(
        "WorldStateScenarioCommit",
        "workbench.extension.world_state.scenario.commit",
    ),
    change(
        "WorldStateLayerEdit",
        "workbench.extension.world_state.layer.edit",
    ),
    submit(
        "WorldStateLayerCommit",
        "workbench.extension.world_state.layer.commit",
    ),
    change(
        "WorldStateAuthorityEdit",
        "workbench.extension.world_state.authority.edit",
    ),
    submit(
        "WorldStateAuthorityCommit",
        "workbench.extension.world_state.authority.commit",
    ),
    click(
        "NavmeshAiMainNavmeshRow",
        "workbench.extension.navmesh_ai.main_navmesh_row.select",
    ),
    click(
        "NavmeshAiHumanoidAgentRow",
        "workbench.extension.navmesh_ai.humanoid_agent_row.select",
    ),
    click(
        "NavmeshAiPatrolQueryRow",
        "workbench.extension.navmesh_ai.patrol_query_row.select",
    ),
    click(
        "NavmeshAiTile1208TableRow",
        "workbench.extension.navmesh_ai.tile_1208_table_row.select",
    ),
    click(
        "NavmeshAiTile1209TableRow",
        "workbench.extension.navmesh_ai.tile_1209_table_row.select",
    ),
    click(
        "NavmeshAiAgentRadiusTableRow",
        "workbench.extension.navmesh_ai.agent_radius_table_row.select",
    ),
    click(
        "NavmeshAiBlockedLinkTableRow",
        "workbench.extension.navmesh_ai.blocked_link_table_row.select",
    ),
    click(
        "NavmeshAiRebuild",
        "workbench.extension.navmesh_ai.rebuild.invoke",
    ),
    click(
        "NavmeshAiQueryPath",
        "workbench.extension.navmesh_ai.query_path.invoke",
    ),
    change(
        "NavmeshAiAgentEdit",
        "workbench.extension.navmesh_ai.agent.edit",
    ),
    submit(
        "NavmeshAiAgentCommit",
        "workbench.extension.navmesh_ai.agent.commit",
    ),
    change(
        "NavmeshAiAreaEdit",
        "workbench.extension.navmesh_ai.area.edit",
    ),
    submit(
        "NavmeshAiAreaCommit",
        "workbench.extension.navmesh_ai.area.commit",
    ),
    change(
        "NavmeshAiCostEdit",
        "workbench.extension.navmesh_ai.cost.edit",
    ),
    submit(
        "NavmeshAiCostCommit",
        "workbench.extension.navmesh_ai.cost.commit",
    ),
];
