use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const GAMEPLAY_ANIMATION_BINDINGS: &[ExtensionBindingSpec] = &[
    click("SequencerOpen", "workbench.extension.sequencer.open"),
    click(
        "SequencerTracksTab",
        "workbench.extension.sequencer.tracks_tab.select",
    ),
    click(
        "SequencerCurvesTab",
        "workbench.extension.sequencer.curves_tab.select",
    ),
    click(
        "SequencerValidationTab",
        "workbench.extension.sequencer.validation_tab.select",
    ),
    click(
        "SequencerSequenceRow",
        "workbench.extension.sequencer.sequence_row.select",
    ),
    click(
        "SequencerCameraRow",
        "workbench.extension.sequencer.camera_row.select",
    ),
    click(
        "SequencerEventRow",
        "workbench.extension.sequencer.event_row.select",
    ),
    click(
        "SequencerCameraCutTableRow",
        "workbench.extension.sequencer.camera_cut_table_row.select",
    ),
    click(
        "SequencerHeroTransformTableRow",
        "workbench.extension.sequencer.hero_transform_table_row.select",
    ),
    click(
        "SequencerAudioTableRow",
        "workbench.extension.sequencer.audio_table_row.select",
    ),
    click(
        "SequencerEventCueTableRow",
        "workbench.extension.sequencer.event_cue_table_row.select",
    ),
    click(
        "SequencerOutput",
        "workbench.extension.sequencer.output.select",
    ),
    click(
        "SequencerPreview",
        "workbench.extension.sequencer.preview.invoke",
    ),
    click(
        "SequencerValidate",
        "workbench.extension.sequencer.validate.invoke",
    ),
    change(
        "SequencerSequenceEdit",
        "workbench.extension.sequencer.sequence.edit",
    ),
    submit(
        "SequencerSequenceCommit",
        "workbench.extension.sequencer.sequence.commit",
    ),
    change(
        "SequencerFrameRateEdit",
        "workbench.extension.sequencer.frame_rate.edit",
    ),
    submit(
        "SequencerFrameRateCommit",
        "workbench.extension.sequencer.frame_rate.commit",
    ),
    change(
        "SequencerWorkRangeEdit",
        "workbench.extension.sequencer.work_range.edit",
    ),
    submit(
        "SequencerWorkRangeCommit",
        "workbench.extension.sequencer.work_range.commit",
    ),
    click(
        "MontageEditorOpen",
        "workbench.extension.montage_editor.open",
    ),
    click(
        "MontageEditorSectionsTab",
        "workbench.extension.montage_editor.sections_tab.select",
    ),
    click(
        "MontageEditorNotifiesTab",
        "workbench.extension.montage_editor.notifies_tab.select",
    ),
    click(
        "MontageEditorCurvesTab",
        "workbench.extension.montage_editor.curves_tab.select",
    ),
    click(
        "MontageEditorAttackRow",
        "workbench.extension.montage_editor.attack_row.select",
    ),
    click(
        "MontageEditorComboRow",
        "workbench.extension.montage_editor.combo_row.select",
    ),
    click(
        "MontageEditorCancelWindowRow",
        "workbench.extension.montage_editor.cancel_window_row.select",
    ),
    click(
        "MontageEditorIntroTableRow",
        "workbench.extension.montage_editor.intro_table_row.select",
    ),
    click(
        "MontageEditorComboTableRow",
        "workbench.extension.montage_editor.combo_table_row.select",
    ),
    click(
        "MontageEditorNotifyTableRow",
        "workbench.extension.montage_editor.notify_table_row.select",
    ),
    click(
        "MontageEditorRootMotionTableRow",
        "workbench.extension.montage_editor.root_motion_table_row.select",
    ),
    click(
        "MontageEditorOutput",
        "workbench.extension.montage_editor.output.select",
    ),
    click(
        "MontageEditorPreview",
        "workbench.extension.montage_editor.preview.invoke",
    ),
    click(
        "MontageEditorApply",
        "workbench.extension.montage_editor.apply.invoke",
    ),
    change(
        "MontageEditorMontageEdit",
        "workbench.extension.montage_editor.montage.edit",
    ),
    submit(
        "MontageEditorMontageCommit",
        "workbench.extension.montage_editor.montage.commit",
    ),
    change(
        "MontageEditorSlotEdit",
        "workbench.extension.montage_editor.slot.edit",
    ),
    submit(
        "MontageEditorSlotCommit",
        "workbench.extension.montage_editor.slot.commit",
    ),
    change(
        "MontageEditorBlendEdit",
        "workbench.extension.montage_editor.blend.edit",
    ),
    submit(
        "MontageEditorBlendCommit",
        "workbench.extension.montage_editor.blend.commit",
    ),
    click("BlendSpaceOpen", "workbench.extension.blend_space.open"),
    click(
        "BlendSpaceSamplesTab",
        "workbench.extension.blend_space.samples_tab.select",
    ),
    click(
        "BlendSpaceAxesTab",
        "workbench.extension.blend_space.axes_tab.select",
    ),
    click(
        "BlendSpacePreviewTab",
        "workbench.extension.blend_space.preview_tab.select",
    ),
    click(
        "BlendSpaceIdleRunRow",
        "workbench.extension.blend_space.idle_run_row.select",
    ),
    click(
        "BlendSpaceStrafeRow",
        "workbench.extension.blend_space.strafe_row.select",
    ),
    click(
        "BlendSpaceSprintRow",
        "workbench.extension.blend_space.sprint_row.select",
    ),
    click(
        "BlendSpaceIdleSampleTableRow",
        "workbench.extension.blend_space.idle_sample_table_row.select",
    ),
    click(
        "BlendSpaceWalkSampleTableRow",
        "workbench.extension.blend_space.walk_sample_table_row.select",
    ),
    click(
        "BlendSpaceRunSampleTableRow",
        "workbench.extension.blend_space.run_sample_table_row.select",
    ),
    click(
        "BlendSpaceDiagonalSampleTableRow",
        "workbench.extension.blend_space.diagonal_sample_table_row.select",
    ),
    click(
        "BlendSpaceOutput",
        "workbench.extension.blend_space.output.select",
    ),
    click(
        "BlendSpacePreview",
        "workbench.extension.blend_space.preview.invoke",
    ),
    click(
        "BlendSpaceApply",
        "workbench.extension.blend_space.apply.invoke",
    ),
    change(
        "BlendSpaceAssetEdit",
        "workbench.extension.blend_space.asset.edit",
    ),
    submit(
        "BlendSpaceAssetCommit",
        "workbench.extension.blend_space.asset.commit",
    ),
    change(
        "BlendSpaceXAxisEdit",
        "workbench.extension.blend_space.x_axis.edit",
    ),
    submit(
        "BlendSpaceXAxisCommit",
        "workbench.extension.blend_space.x_axis.commit",
    ),
    change(
        "BlendSpaceInterpolationEdit",
        "workbench.extension.blend_space.interpolation.edit",
    ),
    submit(
        "BlendSpaceInterpolationCommit",
        "workbench.extension.blend_space.interpolation.commit",
    ),
    click("PoseLibraryOpen", "workbench.extension.pose_library.open"),
    click(
        "PoseLibraryPosesTab",
        "workbench.extension.pose_library.poses_tab.select",
    ),
    click(
        "PoseLibraryTagsTab",
        "workbench.extension.pose_library.tags_tab.select",
    ),
    click(
        "PoseLibraryMirrorTab",
        "workbench.extension.pose_library.mirror_tab.select",
    ),
    click(
        "PoseLibraryCombatRow",
        "workbench.extension.pose_library.combat_row.select",
    ),
    click(
        "PoseLibraryLocomotionRow",
        "workbench.extension.pose_library.locomotion_row.select",
    ),
    click(
        "PoseLibraryEmoteRow",
        "workbench.extension.pose_library.emote_row.select",
    ),
    click(
        "PoseLibraryIdlePoseTableRow",
        "workbench.extension.pose_library.idle_pose_table_row.select",
    ),
    click(
        "PoseLibraryAimPoseTableRow",
        "workbench.extension.pose_library.aim_pose_table_row.select",
    ),
    click(
        "PoseLibraryCrouchPoseTableRow",
        "workbench.extension.pose_library.crouch_pose_table_row.select",
    ),
    click(
        "PoseLibraryMirrorPoseTableRow",
        "workbench.extension.pose_library.mirror_pose_table_row.select",
    ),
    click(
        "PoseLibraryOutput",
        "workbench.extension.pose_library.output.select",
    ),
    click(
        "PoseLibraryPreview",
        "workbench.extension.pose_library.preview.invoke",
    ),
    click(
        "PoseLibraryApply",
        "workbench.extension.pose_library.apply.invoke",
    ),
    change(
        "PoseLibraryAssetEdit",
        "workbench.extension.pose_library.asset.edit",
    ),
    submit(
        "PoseLibraryAssetCommit",
        "workbench.extension.pose_library.asset.commit",
    ),
    change(
        "PoseLibraryTagEdit",
        "workbench.extension.pose_library.tag.edit",
    ),
    submit(
        "PoseLibraryTagCommit",
        "workbench.extension.pose_library.tag.commit",
    ),
    change(
        "PoseLibraryMirrorEdit",
        "workbench.extension.pose_library.mirror.edit",
    ),
    submit(
        "PoseLibraryMirrorCommit",
        "workbench.extension.pose_library.mirror.commit",
    ),
    click("RetargetOpen", "workbench.extension.retarget.open"),
    click(
        "RetargetRigsTab",
        "workbench.extension.retarget.rigs_tab.select",
    ),
    click(
        "RetargetChainsTab",
        "workbench.extension.retarget.chains_tab.select",
    ),
    click(
        "RetargetPreviewTab",
        "workbench.extension.retarget.preview_tab.select",
    ),
    click(
        "RetargetMannequinRow",
        "workbench.extension.retarget.mannequin_row.select",
    ),
    click(
        "RetargetRobotRow",
        "workbench.extension.retarget.robot_row.select",
    ),
    click(
        "RetargetQuadrupedRow",
        "workbench.extension.retarget.quadruped_row.select",
    ),
    click(
        "RetargetRootChainTableRow",
        "workbench.extension.retarget.root_chain_table_row.select",
    ),
    click(
        "RetargetSpineChainTableRow",
        "workbench.extension.retarget.spine_chain_table_row.select",
    ),
    click(
        "RetargetArmChainTableRow",
        "workbench.extension.retarget.arm_chain_table_row.select",
    ),
    click(
        "RetargetLegChainTableRow",
        "workbench.extension.retarget.leg_chain_table_row.select",
    ),
    click(
        "RetargetOutput",
        "workbench.extension.retarget.output.select",
    ),
    click(
        "RetargetPreview",
        "workbench.extension.retarget.preview.invoke",
    ),
    click("RetargetApply", "workbench.extension.retarget.apply.invoke"),
    change(
        "RetargetSourceEdit",
        "workbench.extension.retarget.source.edit",
    ),
    submit(
        "RetargetSourceCommit",
        "workbench.extension.retarget.source.commit",
    ),
    change(
        "RetargetTargetEdit",
        "workbench.extension.retarget.target.edit",
    ),
    submit(
        "RetargetTargetCommit",
        "workbench.extension.retarget.target.commit",
    ),
    change(
        "RetargetSolverEdit",
        "workbench.extension.retarget.solver.edit",
    ),
    submit(
        "RetargetSolverCommit",
        "workbench.extension.retarget.solver.commit",
    ),
    click("ControlRigOpen", "workbench.extension.control_rig.open"),
    click(
        "ControlRigControlsTab",
        "workbench.extension.control_rig.controls_tab.select",
    ),
    click(
        "ControlRigHierarchyTab",
        "workbench.extension.control_rig.hierarchy_tab.select",
    ),
    click(
        "ControlRigSolveTab",
        "workbench.extension.control_rig.solve_tab.select",
    ),
    click(
        "ControlRigHeroRow",
        "workbench.extension.control_rig.hero_row.select",
    ),
    click(
        "ControlRigSpineRow",
        "workbench.extension.control_rig.spine_row.select",
    ),
    click(
        "ControlRigHandRow",
        "workbench.extension.control_rig.hand_row.select",
    ),
    click(
        "ControlRigSpineControlTableRow",
        "workbench.extension.control_rig.spine_control_table_row.select",
    ),
    click(
        "ControlRigArmIkTableRow",
        "workbench.extension.control_rig.arm_ik_table_row.select",
    ),
    click(
        "ControlRigHandIkTableRow",
        "workbench.extension.control_rig.hand_ik_table_row.select",
    ),
    click(
        "ControlRigOutputPoseTableRow",
        "workbench.extension.control_rig.output_pose_table_row.select",
    ),
    click(
        "ControlRigOutput",
        "workbench.extension.control_rig.output.select",
    ),
    click(
        "ControlRigPreview",
        "workbench.extension.control_rig.preview.invoke",
    ),
    click(
        "ControlRigValidate",
        "workbench.extension.control_rig.validate.invoke",
    ),
    change(
        "ControlRigControlEdit",
        "workbench.extension.control_rig.control.edit",
    ),
    submit(
        "ControlRigControlCommit",
        "workbench.extension.control_rig.control.commit",
    ),
    change(
        "ControlRigSpaceEdit",
        "workbench.extension.control_rig.space.edit",
    ),
    submit(
        "ControlRigSpaceCommit",
        "workbench.extension.control_rig.space.commit",
    ),
    change(
        "ControlRigWeightEdit",
        "workbench.extension.control_rig.weight.edit",
    ),
    submit(
        "ControlRigWeightCommit",
        "workbench.extension.control_rig.weight.commit",
    ),
    click(
        "MotionMatchingOpen",
        "workbench.extension.motion_matching.open",
    ),
    click(
        "MotionMatchingDatabaseTab",
        "workbench.extension.motion_matching.database_tab.select",
    ),
    click(
        "MotionMatchingTrajectoryTab",
        "workbench.extension.motion_matching.trajectory_tab.select",
    ),
    click(
        "MotionMatchingDebugTab",
        "workbench.extension.motion_matching.debug_tab.select",
    ),
    click(
        "MotionMatchingLocomotionRow",
        "workbench.extension.motion_matching.locomotion_row.select",
    ),
    click(
        "MotionMatchingCombatRow",
        "workbench.extension.motion_matching.combat_row.select",
    ),
    click(
        "MotionMatchingTraversalRow",
        "workbench.extension.motion_matching.traversal_row.select",
    ),
    click(
        "MotionMatchingIdleClipTableRow",
        "workbench.extension.motion_matching.idle_clip_table_row.select",
    ),
    click(
        "MotionMatchingStartClipTableRow",
        "workbench.extension.motion_matching.start_clip_table_row.select",
    ),
    click(
        "MotionMatchingPivotClipTableRow",
        "workbench.extension.motion_matching.pivot_clip_table_row.select",
    ),
    click(
        "MotionMatchingStopClipTableRow",
        "workbench.extension.motion_matching.stop_clip_table_row.select",
    ),
    click(
        "MotionMatchingOutput",
        "workbench.extension.motion_matching.output.select",
    ),
    click(
        "MotionMatchingPreview",
        "workbench.extension.motion_matching.preview.invoke",
    ),
    click(
        "MotionMatchingRebuild",
        "workbench.extension.motion_matching.rebuild.invoke",
    ),
    change(
        "MotionMatchingDatabaseEdit",
        "workbench.extension.motion_matching.database.edit",
    ),
    submit(
        "MotionMatchingDatabaseCommit",
        "workbench.extension.motion_matching.database.commit",
    ),
    change(
        "MotionMatchingTrajectoryEdit",
        "workbench.extension.motion_matching.trajectory.edit",
    ),
    submit(
        "MotionMatchingTrajectoryCommit",
        "workbench.extension.motion_matching.trajectory.commit",
    ),
    change(
        "MotionMatchingCostEdit",
        "workbench.extension.motion_matching.cost.edit",
    ),
    submit(
        "MotionMatchingCostCommit",
        "workbench.extension.motion_matching.cost.commit",
    ),
    click(
        "AnimationCompressionOpen",
        "workbench.extension.animation_compression.open",
    ),
    click(
        "AnimationCompressionClipsTab",
        "workbench.extension.animation_compression.clips_tab.select",
    ),
    click(
        "AnimationCompressionCodecsTab",
        "workbench.extension.animation_compression.codecs_tab.select",
    ),
    click(
        "AnimationCompressionErrorsTab",
        "workbench.extension.animation_compression.errors_tab.select",
    ),
    click(
        "AnimationCompressionLocomotionRow",
        "workbench.extension.animation_compression.locomotion_row.select",
    ),
    click(
        "AnimationCompressionCombatRow",
        "workbench.extension.animation_compression.combat_row.select",
    ),
    click(
        "AnimationCompressionCinematicRow",
        "workbench.extension.animation_compression.cinematic_row.select",
    ),
    click(
        "AnimationCompressionRunClipTableRow",
        "workbench.extension.animation_compression.run_clip_table_row.select",
    ),
    click(
        "AnimationCompressionAttackClipTableRow",
        "workbench.extension.animation_compression.attack_clip_table_row.select",
    ),
    click(
        "AnimationCompressionFacialClipTableRow",
        "workbench.extension.animation_compression.facial_clip_table_row.select",
    ),
    click(
        "AnimationCompressionErrorClipTableRow",
        "workbench.extension.animation_compression.error_clip_table_row.select",
    ),
    click(
        "AnimationCompressionOutput",
        "workbench.extension.animation_compression.output.select",
    ),
    click(
        "AnimationCompressionPreview",
        "workbench.extension.animation_compression.preview.invoke",
    ),
    click(
        "AnimationCompressionCompress",
        "workbench.extension.animation_compression.compress.invoke",
    ),
    change(
        "AnimationCompressionCodecEdit",
        "workbench.extension.animation_compression.codec.edit",
    ),
    submit(
        "AnimationCompressionCodecCommit",
        "workbench.extension.animation_compression.codec.commit",
    ),
    change(
        "AnimationCompressionToleranceEdit",
        "workbench.extension.animation_compression.tolerance.edit",
    ),
    submit(
        "AnimationCompressionToleranceCommit",
        "workbench.extension.animation_compression.tolerance.commit",
    ),
    change(
        "AnimationCompressionRateEdit",
        "workbench.extension.animation_compression.rate.edit",
    ),
    submit(
        "AnimationCompressionRateCommit",
        "workbench.extension.animation_compression.rate.commit",
    ),
];
