use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const GAMEPLAY_STATE_BINDINGS: &[ExtensionBindingSpec] = &[
    click("SpawnRulesOpen", "workbench.extension.spawn_rules.open"),
    click(
        "SpawnRulesRulesTab",
        "workbench.extension.spawn_rules.rules_tab.select",
    ),
    click(
        "SpawnRulesStateTab",
        "workbench.extension.spawn_rules.state_tab.select",
    ),
    click(
        "SpawnRulesValidationTab",
        "workbench.extension.spawn_rules.validation_tab.select",
    ),
    click(
        "SpawnRulesEnemyRow",
        "workbench.extension.spawn_rules.enemy_row.select",
    ),
    click(
        "SpawnRulesZoneARow",
        "workbench.extension.spawn_rules.zone_a_row.select",
    ),
    click(
        "SpawnRulesConditionNightRow",
        "workbench.extension.spawn_rules.condition_night_row.select",
    ),
    click(
        "SpawnRulesZoneATableRow",
        "workbench.extension.spawn_rules.zone_a_table_row.select",
    ),
    click(
        "SpawnRulesConditionNightTableRow",
        "workbench.extension.spawn_rules.condition_night_table_row.select",
    ),
    click(
        "SpawnRulesTagCombatTableRow",
        "workbench.extension.spawn_rules.tag_combat_table_row.select",
    ),
    click(
        "SpawnRulesConflictTableRow",
        "workbench.extension.spawn_rules.conflict_table_row.select",
    ),
    click(
        "SpawnRulesOutput",
        "workbench.extension.spawn_rules.output.select",
    ),
    click(
        "SpawnRulesSimulate",
        "workbench.extension.spawn_rules.simulate.invoke",
    ),
    click(
        "SpawnRulesValidate",
        "workbench.extension.spawn_rules.validate.invoke",
    ),
    change(
        "SpawnRulesRuleSetEdit",
        "workbench.extension.spawn_rules.rule_set.edit",
    ),
    submit(
        "SpawnRulesRuleSetCommit",
        "workbench.extension.spawn_rules.rule_set.commit",
    ),
    change(
        "SpawnRulesAuthorityEdit",
        "workbench.extension.spawn_rules.authority.edit",
    ),
    submit(
        "SpawnRulesAuthorityCommit",
        "workbench.extension.spawn_rules.authority.commit",
    ),
    change(
        "SpawnRulesSeedEdit",
        "workbench.extension.spawn_rules.seed.edit",
    ),
    submit(
        "SpawnRulesSeedCommit",
        "workbench.extension.spawn_rules.seed.commit",
    ),
    click("WorldStateOpen", "workbench.extension.world_state.open"),
    click(
        "WorldStateKeysTab",
        "workbench.extension.world_state.keys_tab.select",
    ),
    click(
        "WorldStateScenarioTab",
        "workbench.extension.world_state.scenario_tab.select",
    ),
    click(
        "WorldStateTimelineTab",
        "workbench.extension.world_state.timeline_tab.select",
    ),
    click(
        "WorldStateNightRaidRow",
        "workbench.extension.world_state.night_raid_row.select",
    ),
    click(
        "WorldStateGlobalLayerRow",
        "workbench.extension.world_state.global_layer_row.select",
    ),
    click(
        "WorldStateAlarmKeyRow",
        "workbench.extension.world_state.alarm_key_row.select",
    ),
    click(
        "WorldStateAlarmActiveTableRow",
        "workbench.extension.world_state.alarm_active_table_row.select",
    ),
    click(
        "WorldStateWeatherModeTableRow",
        "workbench.extension.world_state.weather_mode_table_row.select",
    ),
    click(
        "WorldStateAiAlertTableRow",
        "workbench.extension.world_state.ai_alert_table_row.select",
    ),
    click(
        "WorldStateQuestFlagTableRow",
        "workbench.extension.world_state.quest_flag_table_row.select",
    ),
    click(
        "WorldStateOutput",
        "workbench.extension.world_state.output.select",
    ),
    click(
        "WorldStateSimulate",
        "workbench.extension.world_state.simulate.invoke",
    ),
    click(
        "WorldStateValidate",
        "workbench.extension.world_state.validate.invoke",
    ),
    change(
        "WorldStateScenarioEdit",
        "workbench.extension.world_state.scenario.edit",
    ),
    submit(
        "WorldStateScenarioCommit",
        "workbench.extension.world_state.scenario.commit",
    ),
    change(
        "WorldStateLayerEdit",
        "workbench.extension.world_state.layer.edit",
    ),
    submit(
        "WorldStateLayerCommit",
        "workbench.extension.world_state.layer.commit",
    ),
    change(
        "WorldStateAuthorityEdit",
        "workbench.extension.world_state.authority.edit",
    ),
    submit(
        "WorldStateAuthorityCommit",
        "workbench.extension.world_state.authority.commit",
    ),
];
