use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const ONLINE_SESSIONS_BINDINGS: &[ExtensionBindingSpec] = &[
    click("LobbyEditorOpen", "workbench.extension.lobby_editor.open"),
    click(
        "LobbyEditorFlowTab",
        "workbench.extension.lobby_editor.flow_tab.select",
    ),
    click(
        "LobbyEditorSlotsTab",
        "workbench.extension.lobby_editor.slots_tab.select",
    ),
    click(
        "LobbyEditorTelemetryTab",
        "workbench.extension.lobby_editor.telemetry_tab.select",
    ),
    click(
        "LobbyEditorDefaultLobbyRow",
        "workbench.extension.lobby_editor.default_lobby_row.select",
    ),
    click(
        "LobbyEditorLeaderSlotRow",
        "workbench.extension.lobby_editor.leader_slot_row.select",
    ),
    click(
        "LobbyEditorRegionAutoRow",
        "workbench.extension.lobby_editor.region_auto_row.select",
    ),
    click(
        "LobbyEditorLeaderSlotTableRow",
        "workbench.extension.lobby_editor.leader_slot_table_row.select",
    ),
    click(
        "LobbyEditorGuest01TableRow",
        "workbench.extension.lobby_editor.guest_01_table_row.select",
    ),
    click(
        "LobbyEditorGuest02TableRow",
        "workbench.extension.lobby_editor.guest_02_table_row.select",
    ),
    click(
        "LobbyEditorCrossplayRuleTableRow",
        "workbench.extension.lobby_editor.crossplay_rule_table_row.select",
    ),
    click(
        "LobbyEditorOutput",
        "workbench.extension.lobby_editor.output.select",
    ),
    click(
        "LobbyEditorSimulateLobby",
        "workbench.extension.lobby_editor.simulate_lobby.invoke",
    ),
    click(
        "LobbyEditorValidateLobby",
        "workbench.extension.lobby_editor.validate_lobby.invoke",
    ),
    change(
        "LobbyEditorTemplateEdit",
        "workbench.extension.lobby_editor.template.edit",
    ),
    submit(
        "LobbyEditorTemplateCommit",
        "workbench.extension.lobby_editor.template.commit",
    ),
    change(
        "LobbyEditorRegionEdit",
        "workbench.extension.lobby_editor.region.edit",
    ),
    submit(
        "LobbyEditorRegionCommit",
        "workbench.extension.lobby_editor.region.commit",
    ),
    change(
        "LobbyEditorMaxPlayersEdit",
        "workbench.extension.lobby_editor.max_players.edit",
    ),
    submit(
        "LobbyEditorMaxPlayersCommit",
        "workbench.extension.lobby_editor.max_players.commit",
    ),
    click(
        "MatchmakingEditorOpen",
        "workbench.extension.matchmaking_editor.open",
    ),
    click(
        "MatchmakingEditorQueuesTab",
        "workbench.extension.matchmaking_editor.queues_tab.select",
    ),
    click(
        "MatchmakingEditorRulesTab",
        "workbench.extension.matchmaking_editor.rules_tab.select",
    ),
    click(
        "MatchmakingEditorTelemetryTab",
        "workbench.extension.matchmaking_editor.telemetry_tab.select",
    ),
    click(
        "MatchmakingEditorPlaylistRankedRow",
        "workbench.extension.matchmaking_editor.playlist_ranked_row.select",
    ),
    click(
        "MatchmakingEditorQueueSoloRow",
        "workbench.extension.matchmaking_editor.queue_solo_row.select",
    ),
    click(
        "MatchmakingEditorRuleLatencyRow",
        "workbench.extension.matchmaking_editor.rule_latency_row.select",
    ),
    click(
        "MatchmakingEditorBronzeBucketTableRow",
        "workbench.extension.matchmaking_editor.bronze_bucket_table_row.select",
    ),
    click(
        "MatchmakingEditorGoldBucketTableRow",
        "workbench.extension.matchmaking_editor.gold_bucket_table_row.select",
    ),
    click(
        "MatchmakingEditorDiamondBucketTableRow",
        "workbench.extension.matchmaking_editor.diamond_bucket_table_row.select",
    ),
    click(
        "MatchmakingEditorBackfillTableRow",
        "workbench.extension.matchmaking_editor.backfill_table_row.select",
    ),
    click(
        "MatchmakingEditorOutput",
        "workbench.extension.matchmaking_editor.output.select",
    ),
    click(
        "MatchmakingEditorSimulateMatch",
        "workbench.extension.matchmaking_editor.simulate_match.invoke",
    ),
    click(
        "MatchmakingEditorValidateRules",
        "workbench.extension.matchmaking_editor.validate_rules.invoke",
    ),
    change(
        "MatchmakingEditorPlaylistEdit",
        "workbench.extension.matchmaking_editor.playlist.edit",
    ),
    submit(
        "MatchmakingEditorPlaylistCommit",
        "workbench.extension.matchmaking_editor.playlist.commit",
    ),
    change(
        "MatchmakingEditorRegionEdit",
        "workbench.extension.matchmaking_editor.region.edit",
    ),
    submit(
        "MatchmakingEditorRegionCommit",
        "workbench.extension.matchmaking_editor.region.commit",
    ),
    change(
        "MatchmakingEditorMaxWaitEdit",
        "workbench.extension.matchmaking_editor.max_wait.edit",
    ),
    submit(
        "MatchmakingEditorMaxWaitCommit",
        "workbench.extension.matchmaking_editor.max_wait.commit",
    ),
];
