use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const RENDER_ASSET_VFX_BINDINGS: &[ExtensionBindingSpec] = &[
    click("ShaderEditorOpen", "workbench.extension.shader_editor.open"),
    click("LightingBakeOpen", "workbench.extension.lighting_bake.open"),
    click("PostProcessOpen", "workbench.extension.post_process.open"),
    click(
        "ShaderEditorSourceTab",
        "workbench.extension.shader_editor.source_tab.select",
    ),
    click(
        "ShaderEditorResourcesTab",
        "workbench.extension.shader_editor.resources_tab.select",
    ),
    click(
        "ShaderEditorIssuesTab",
        "workbench.extension.shader_editor.issues_tab.select",
    ),
    click(
        "ShaderEditorSourceRow",
        "workbench.extension.shader_editor.source_row.select",
    ),
    click(
        "ShaderEditorIncludeRow",
        "workbench.extension.shader_editor.include_row.select",
    ),
    click(
        "ShaderEditorPermutationRow",
        "workbench.extension.shader_editor.permutation_row.select",
    ),
    click(
        "ShaderEditorVertexRow",
        "workbench.extension.shader_editor.vertex_row.select",
    ),
    click(
        "ShaderEditorFragmentRow",
        "workbench.extension.shader_editor.fragment_row.select",
    ),
    click(
        "ShaderEditorComputeRow",
        "workbench.extension.shader_editor.compute_row.select",
    ),
    click(
        "ShaderEditorCommonRow",
        "workbench.extension.shader_editor.common_row.select",
    ),
    click(
        "ShaderEditorOutput",
        "workbench.extension.shader_editor.output.select",
    ),
    click(
        "ShaderEditorPreview",
        "workbench.extension.shader_editor.preview.invoke",
    ),
    click(
        "ShaderEditorCompile",
        "workbench.extension.shader_editor.compile.invoke",
    ),
    click(
        "LightingBakeLevelsTab",
        "workbench.extension.lighting_bake.levels_tab.select",
    ),
    click(
        "LightingBakeProbesTab",
        "workbench.extension.lighting_bake.probes_tab.select",
    ),
    click(
        "LightingBakeWarningsTab",
        "workbench.extension.lighting_bake.warnings_tab.select",
    ),
    click(
        "LightingBakeSceneBakeRow",
        "workbench.extension.lighting_bake.scene_bake_row.select",
    ),
    click(
        "LightingBakeInteriorBakeRow",
        "workbench.extension.lighting_bake.interior_bake_row.select",
    ),
    click(
        "LightingBakeReflectionProbeRow",
        "workbench.extension.lighting_bake.reflection_probe_row.select",
    ),
    click(
        "LightingBakeShadowMapTableRow",
        "workbench.extension.lighting_bake.shadow_map_table_row.select",
    ),
    click(
        "LightingBakeLightmapUvTableRow",
        "workbench.extension.lighting_bake.lightmap_uv_table_row.select",
    ),
    click(
        "LightingBakeProbeGridTableRow",
        "workbench.extension.lighting_bake.probe_grid_table_row.select",
    ),
    click(
        "LightingBakeBleedWarningTableRow",
        "workbench.extension.lighting_bake.bleed_warning_table_row.select",
    ),
    click(
        "LightingBakeOutput",
        "workbench.extension.lighting_bake.output.select",
    ),
    click(
        "LightingBakePreview",
        "workbench.extension.lighting_bake.preview.invoke",
    ),
    click(
        "LightingBakeBake",
        "workbench.extension.lighting_bake.bake.invoke",
    ),
    click(
        "PostProcessStackTab",
        "workbench.extension.post_process.stack_tab.select",
    ),
    click(
        "PostProcessVolumesTab",
        "workbench.extension.post_process.volumes_tab.select",
    ),
    click(
        "PostProcessWarningsTab",
        "workbench.extension.post_process.warnings_tab.select",
    ),
    click(
        "PostProcessGlobalStackRow",
        "workbench.extension.post_process.global_stack_row.select",
    ),
    click(
        "PostProcessCinematicStackRow",
        "workbench.extension.post_process.cinematic_stack_row.select",
    ),
    click(
        "PostProcessVolumeBlendRow",
        "workbench.extension.post_process.volume_blend_row.select",
    ),
    click(
        "PostProcessBloomTableRow",
        "workbench.extension.post_process.bloom_table_row.select",
    ),
    click(
        "PostProcessTonemapTableRow",
        "workbench.extension.post_process.tonemap_table_row.select",
    ),
    click(
        "PostProcessLutTableRow",
        "workbench.extension.post_process.lut_table_row.select",
    ),
    click(
        "PostProcessExposureWarningTableRow",
        "workbench.extension.post_process.exposure_warning_table_row.select",
    ),
    click(
        "PostProcessOutput",
        "workbench.extension.post_process.output.select",
    ),
    click(
        "PostProcessPreview",
        "workbench.extension.post_process.preview.invoke",
    ),
    click(
        "PostProcessApply",
        "workbench.extension.post_process.apply.invoke",
    ),
    click("DataTableOpen", "workbench.extension.data_table.open"),
    click(
        "DataTableRowsTab",
        "workbench.extension.data_table.rows_tab.select",
    ),
    click(
        "DataTableSchemaTab",
        "workbench.extension.data_table.schema_tab.select",
    ),
    click(
        "DataTableValidationTab",
        "workbench.extension.data_table.validation_tab.select",
    ),
    click(
        "DataTableItemsRow",
        "workbench.extension.data_table.items_row.select",
    ),
    click(
        "DataTableSchemaRow",
        "workbench.extension.data_table.schema_row.select",
    ),
    click(
        "DataTableLocalizationRow",
        "workbench.extension.data_table.localization_row.select",
    ),
    click(
        "DataTablePotionRow",
        "workbench.extension.data_table.potion_row.select",
    ),
    click(
        "DataTableSwordRow",
        "workbench.extension.data_table.sword_row.select",
    ),
    click(
        "DataTableArmorRow",
        "workbench.extension.data_table.armor_row.select",
    ),
    click(
        "DataTableDebugRow",
        "workbench.extension.data_table.debug_row.select",
    ),
    click(
        "DataTableOutput",
        "workbench.extension.data_table.output.select",
    ),
    click(
        "DataTableValidate",
        "workbench.extension.data_table.validate.invoke",
    ),
    click(
        "DataTableSave",
        "workbench.extension.data_table.save.invoke",
    ),
    click(
        "SourceControlOpen",
        "workbench.extension.source_control.open",
    ),
    click(
        "SourceControlDiffTab",
        "workbench.extension.source_control.diff_tab.select",
    ),
    click(
        "SourceControlOwnersTab",
        "workbench.extension.source_control.owners_tab.select",
    ),
    click(
        "SourceControlSubmitTab",
        "workbench.extension.source_control.submit_tab.select",
    ),
    click(
        "SourceControlChangelistRow",
        "workbench.extension.source_control.changelist_row.select",
    ),
    click(
        "SourceControlRuntimeRow",
        "workbench.extension.source_control.runtime_row.select",
    ),
    click(
        "SourceControlEditorRow",
        "workbench.extension.source_control.editor_row.select",
    ),
    click(
        "SourceControlRuntimeFileRow",
        "workbench.extension.source_control.runtime_file_row.select",
    ),
    click(
        "SourceControlEditorFileRow",
        "workbench.extension.source_control.editor_file_row.select",
    ),
    click(
        "SourceControlDocsFileRow",
        "workbench.extension.source_control.docs_file_row.select",
    ),
    click(
        "SourceControlConflictFileRow",
        "workbench.extension.source_control.conflict_file_row.select",
    ),
    click(
        "SourceControlOutput",
        "workbench.extension.source_control.output.select",
    ),
    click(
        "SourceControlValidate",
        "workbench.extension.source_control.validate.invoke",
    ),
    click(
        "SourceControlSubmit",
        "workbench.extension.source_control.submit.invoke",
    ),
    click("BuildExportOpen", "workbench.extension.build_export.open"),
    click(
        "BuildExportProfilesTab",
        "workbench.extension.build_export.profiles_tab.select",
    ),
    click(
        "BuildExportQueueTab",
        "workbench.extension.build_export.queue_tab.select",
    ),
    click(
        "BuildExportSigningTab",
        "workbench.extension.build_export.signing_tab.select",
    ),
    click(
        "BuildExportShippingRow",
        "workbench.extension.build_export.shipping_row.select",
    ),
    click(
        "BuildExportDevelopmentRow",
        "workbench.extension.build_export.development_row.select",
    ),
    click(
        "BuildExportPatchRow",
        "workbench.extension.build_export.patch_row.select",
    ),
    click(
        "BuildExportCookStepRow",
        "workbench.extension.build_export.cook_step_row.select",
    ),
    click(
        "BuildExportPakStepRow",
        "workbench.extension.build_export.pak_step_row.select",
    ),
    click(
        "BuildExportSignStepRow",
        "workbench.extension.build_export.sign_step_row.select",
    ),
    click(
        "BuildExportPublishStepRow",
        "workbench.extension.build_export.publish_step_row.select",
    ),
    click(
        "BuildExportOutput",
        "workbench.extension.build_export.output.select",
    ),
    click(
        "BuildExportValidate",
        "workbench.extension.build_export.validate.invoke",
    ),
    click(
        "BuildExportPackage",
        "workbench.extension.build_export.package.invoke",
    ),
    click(
        "AutomationReportOpen",
        "workbench.extension.automation_report.open",
    ),
    click(
        "AutomationReportFailuresTab",
        "workbench.extension.automation_report.failures_tab.select",
    ),
    click(
        "AutomationReportWorkersTab",
        "workbench.extension.automation_report.workers_tab.select",
    ),
    click(
        "AutomationReportArtifactsTab",
        "workbench.extension.automation_report.artifacts_tab.select",
    ),
    click(
        "AutomationReportSmokeRow",
        "workbench.extension.automation_report.smoke_row.select",
    ),
    click(
        "AutomationReportRenderingRow",
        "workbench.extension.automation_report.rendering_row.select",
    ),
    click(
        "AutomationReportGameplayRow",
        "workbench.extension.automation_report.gameplay_row.select",
    ),
    click(
        "AutomationReportRendererTestRow",
        "workbench.extension.automation_report.renderer_test_row.select",
    ),
    click(
        "AutomationReportGameplayTestRow",
        "workbench.extension.automation_report.gameplay_test_row.select",
    ),
    click(
        "AutomationReportAssetTestRow",
        "workbench.extension.automation_report.asset_test_row.select",
    ),
    click(
        "AutomationReportUiFailureRow",
        "workbench.extension.automation_report.ui_failure_row.select",
    ),
    click(
        "AutomationReportOutput",
        "workbench.extension.automation_report.output.select",
    ),
    click(
        "AutomationReportValidate",
        "workbench.extension.automation_report.validate.invoke",
    ),
    click(
        "AutomationReportPublish",
        "workbench.extension.automation_report.publish.invoke",
    ),
    click(
        "ProjectOverviewOpen",
        "workbench.extension.project_overview.open",
    ),
    click(
        "ProjectOverviewSummaryTab",
        "workbench.extension.project_overview.summary_tab.select",
    ),
    click(
        "ProjectOverviewTargetsTab",
        "workbench.extension.project_overview.targets_tab.select",
    ),
    click(
        "ProjectOverviewReleasesTab",
        "workbench.extension.project_overview.releases_tab.select",
    ),
    click(
        "ProjectOverviewProjectRow",
        "workbench.extension.project_overview.project_row.select",
    ),
    click(
        "ProjectOverviewMilestoneRow",
        "workbench.extension.project_overview.milestone_row.select",
    ),
    click(
        "ProjectOverviewRiskRow",
        "workbench.extension.project_overview.risk_row.select",
    ),
    click(
        "ProjectOverviewHealthRow",
        "workbench.extension.project_overview.health_row.select",
    ),
    click(
        "ProjectOverviewBuildRow",
        "workbench.extension.project_overview.build_row.select",
    ),
    click(
        "ProjectOverviewCoverageRow",
        "workbench.extension.project_overview.coverage_row.select",
    ),
    click(
        "ProjectOverviewDependencyRow",
        "workbench.extension.project_overview.dependency_row.select",
    ),
    click(
        "ProjectOverviewOutput",
        "workbench.extension.project_overview.output.select",
    ),
    click(
        "ProjectOverviewRefresh",
        "workbench.extension.project_overview.refresh.invoke",
    ),
    click(
        "ProjectOverviewPublish",
        "workbench.extension.project_overview.publish.invoke",
    ),
    click(
        "PluginManagerOpen",
        "workbench.extension.plugin_manager.open",
    ),
    click(
        "PluginManagerInstalledTab",
        "workbench.extension.plugin_manager.installed_tab.select",
    ),
    click(
        "PluginManagerDependenciesTab",
        "workbench.extension.plugin_manager.dependencies_tab.select",
    ),
    click(
        "PluginManagerUpdatesTab",
        "workbench.extension.plugin_manager.updates_tab.select",
    ),
    click(
        "PluginManagerAudioRow",
        "workbench.extension.plugin_manager.audio_row.select",
    ),
    click(
        "PluginManagerRenderdocRow",
        "workbench.extension.plugin_manager.renderdoc_row.select",
    ),
    click(
        "PluginManagerGameplayRow",
        "workbench.extension.plugin_manager.gameplay_row.select",
    ),
    click(
        "PluginManagerAudioRuntimeTableRow",
        "workbench.extension.plugin_manager.audio_runtime_table_row.select",
    ),
    click(
        "PluginManagerRenderdocBridgeTableRow",
        "workbench.extension.plugin_manager.renderdoc_bridge_table_row.select",
    ),
    click(
        "PluginManagerGameplayPackTableRow",
        "workbench.extension.plugin_manager.gameplay_pack_table_row.select",
    ),
    click(
        "PluginManagerVersionWarningTableRow",
        "workbench.extension.plugin_manager.version_warning_table_row.select",
    ),
    click(
        "PluginManagerOutput",
        "workbench.extension.plugin_manager.output.select",
    ),
    click(
        "PluginManagerHotReload",
        "workbench.extension.plugin_manager.hot_reload.invoke",
    ),
    click(
        "PluginManagerValidate",
        "workbench.extension.plugin_manager.validate.invoke",
    ),
    click(
        "ParticleLibraryOpen",
        "workbench.extension.particle_library.open",
    ),
    click(
        "ParticleLibraryEmittersTab",
        "workbench.extension.particle_library.emitters_tab.select",
    ),
    click(
        "ParticleLibraryMetadataTab",
        "workbench.extension.particle_library.metadata_tab.select",
    ),
    click(
        "ParticleLibraryCompileTab",
        "workbench.extension.particle_library.compile_tab.select",
    ),
    click(
        "ParticleLibrarySparksRow",
        "workbench.extension.particle_library.sparks_row.select",
    ),
    click(
        "ParticleLibraryDustRow",
        "workbench.extension.particle_library.dust_row.select",
    ),
    click(
        "ParticleLibraryImpactRow",
        "workbench.extension.particle_library.impact_row.select",
    ),
    click(
        "ParticleLibraryGpuSparkRow",
        "workbench.extension.particle_library.gpu_spark_row.select",
    ),
    click(
        "ParticleLibraryCpuDustRow",
        "workbench.extension.particle_library.cpu_dust_row.select",
    ),
    click(
        "ParticleLibraryImpactGpuRow",
        "workbench.extension.particle_library.impact_gpu_row.select",
    ),
    click(
        "ParticleLibraryArchivedRow",
        "workbench.extension.particle_library.archived_row.select",
    ),
    click(
        "ParticleLibraryOutput",
        "workbench.extension.particle_library.output.select",
    ),
    click(
        "ParticleLibrarySimulate",
        "workbench.extension.particle_library.simulate.invoke",
    ),
    click(
        "ParticleLibraryCompile",
        "workbench.extension.particle_library.compile.invoke",
    ),
    change(
        "ShaderEditorTargetEdit",
        "workbench.extension.shader_editor.target.edit",
    ),
    submit(
        "ShaderEditorTargetCommit",
        "workbench.extension.shader_editor.target.commit",
    ),
    change(
        "ShaderEditorEntryEdit",
        "workbench.extension.shader_editor.entry.edit",
    ),
    submit(
        "ShaderEditorEntryCommit",
        "workbench.extension.shader_editor.entry.commit",
    ),
    change(
        "ShaderEditorLiveCompileEdit",
        "workbench.extension.shader_editor.live_compile.edit",
    ),
    submit(
        "ShaderEditorLiveCompileCommit",
        "workbench.extension.shader_editor.live_compile.commit",
    ),
    change(
        "LightingBakeQualityEdit",
        "workbench.extension.lighting_bake.quality.edit",
    ),
    submit(
        "LightingBakeQualityCommit",
        "workbench.extension.lighting_bake.quality.commit",
    ),
    change(
        "LightingBakeTargetEdit",
        "workbench.extension.lighting_bake.target.edit",
    ),
    submit(
        "LightingBakeTargetCommit",
        "workbench.extension.lighting_bake.target.commit",
    ),
    change(
        "LightingBakeDenoiseEdit",
        "workbench.extension.lighting_bake.denoise.edit",
    ),
    submit(
        "LightingBakeDenoiseCommit",
        "workbench.extension.lighting_bake.denoise.commit",
    ),
    change(
        "PostProcessProfileEdit",
        "workbench.extension.post_process.profile.edit",
    ),
    submit(
        "PostProcessProfileCommit",
        "workbench.extension.post_process.profile.commit",
    ),
    change(
        "PostProcessVolumeEdit",
        "workbench.extension.post_process.volume.edit",
    ),
    submit(
        "PostProcessVolumeCommit",
        "workbench.extension.post_process.volume.commit",
    ),
    change(
        "PostProcessBlendEdit",
        "workbench.extension.post_process.blend.edit",
    ),
    submit(
        "PostProcessBlendCommit",
        "workbench.extension.post_process.blend.commit",
    ),
    change(
        "DataTableRowEdit",
        "workbench.extension.data_table.row.edit",
    ),
    submit(
        "DataTableRowCommit",
        "workbench.extension.data_table.row.commit",
    ),
    change(
        "DataTableTypeEdit",
        "workbench.extension.data_table.type.edit",
    ),
    submit(
        "DataTableTypeCommit",
        "workbench.extension.data_table.type.commit",
    ),
    change(
        "DataTableVersionEdit",
        "workbench.extension.data_table.version.edit",
    ),
    submit(
        "DataTableVersionCommit",
        "workbench.extension.data_table.version.commit",
    ),
    change(
        "SourceControlChangelistEdit",
        "workbench.extension.source_control.changelist.edit",
    ),
    submit(
        "SourceControlChangelistCommit",
        "workbench.extension.source_control.changelist.commit",
    ),
    change(
        "SourceControlOwnerEdit",
        "workbench.extension.source_control.owner.edit",
    ),
    submit(
        "SourceControlOwnerCommit",
        "workbench.extension.source_control.owner.commit",
    ),
    change(
        "SourceControlGateEdit",
        "workbench.extension.source_control.gate.edit",
    ),
    submit(
        "SourceControlGateCommit",
        "workbench.extension.source_control.gate.commit",
    ),
    change(
        "BuildExportPlatformEdit",
        "workbench.extension.build_export.platform.edit",
    ),
    submit(
        "BuildExportPlatformCommit",
        "workbench.extension.build_export.platform.commit",
    ),
    change(
        "BuildExportChannelEdit",
        "workbench.extension.build_export.channel.edit",
    ),
    submit(
        "BuildExportChannelCommit",
        "workbench.extension.build_export.channel.commit",
    ),
    change(
        "BuildExportCompressionEdit",
        "workbench.extension.build_export.compression.edit",
    ),
    submit(
        "BuildExportCompressionCommit",
        "workbench.extension.build_export.compression.commit",
    ),
    change(
        "AutomationReportSuiteEdit",
        "workbench.extension.automation_report.suite.edit",
    ),
    submit(
        "AutomationReportSuiteCommit",
        "workbench.extension.automation_report.suite.commit",
    ),
    change(
        "AutomationReportPlatformEdit",
        "workbench.extension.automation_report.platform.edit",
    ),
    submit(
        "AutomationReportPlatformCommit",
        "workbench.extension.automation_report.platform.commit",
    ),
    change(
        "AutomationReportRetryEdit",
        "workbench.extension.automation_report.retry.edit",
    ),
    submit(
        "AutomationReportRetryCommit",
        "workbench.extension.automation_report.retry.commit",
    ),
    change(
        "ProjectOverviewOwnerEdit",
        "workbench.extension.project_overview.owner.edit",
    ),
    submit(
        "ProjectOverviewOwnerCommit",
        "workbench.extension.project_overview.owner.commit",
    ),
    change(
        "ProjectOverviewChannelEdit",
        "workbench.extension.project_overview.channel.edit",
    ),
    submit(
        "ProjectOverviewChannelCommit",
        "workbench.extension.project_overview.channel.commit",
    ),
    change(
        "ProjectOverviewHealthEdit",
        "workbench.extension.project_overview.health.edit",
    ),
    submit(
        "ProjectOverviewHealthCommit",
        "workbench.extension.project_overview.health.commit",
    ),
    change(
        "PluginManagerPluginEdit",
        "workbench.extension.plugin_manager.plugin.edit",
    ),
    submit(
        "PluginManagerPluginCommit",
        "workbench.extension.plugin_manager.plugin.commit",
    ),
    change(
        "PluginManagerChannelEdit",
        "workbench.extension.plugin_manager.channel.edit",
    ),
    submit(
        "PluginManagerChannelCommit",
        "workbench.extension.plugin_manager.channel.commit",
    ),
    change(
        "PluginManagerVersionEdit",
        "workbench.extension.plugin_manager.version.edit",
    ),
    submit(
        "PluginManagerVersionCommit",
        "workbench.extension.plugin_manager.version.commit",
    ),
    change(
        "ParticleLibraryEmitterEdit",
        "workbench.extension.particle_library.emitter.edit",
    ),
    submit(
        "ParticleLibraryEmitterCommit",
        "workbench.extension.particle_library.emitter.commit",
    ),
    change(
        "ParticleLibraryDurationEdit",
        "workbench.extension.particle_library.duration.edit",
    ),
    submit(
        "ParticleLibraryDurationCommit",
        "workbench.extension.particle_library.duration.commit",
    ),
    change(
        "ParticleLibraryBoundsEdit",
        "workbench.extension.particle_library.bounds.edit",
    ),
    submit(
        "ParticleLibraryBoundsCommit",
        "workbench.extension.particle_library.bounds.commit",
    ),
];
