use super::types::{ExtensionBindingSpec, change, click, submit};

pub(super) const RUNTIME_STATE_BINDINGS: &[ExtensionBindingSpec] = &[
    click("SaveDataOpen", "workbench.extension.save_data.open"),
    click(
        "SaveDataSlotsTab",
        "workbench.extension.save_data.slots_tab.select",
    ),
    click(
        "SaveDataMigrationTab",
        "workbench.extension.save_data.migration_tab.select",
    ),
    click(
        "SaveDataValidationTab",
        "workbench.extension.save_data.validation_tab.select",
    ),
    click(
        "SaveDataAutoSaveRow",
        "workbench.extension.save_data.auto_save_row.select",
    ),
    click(
        "SaveDataManualRow",
        "workbench.extension.save_data.manual_row.select",
    ),
    click(
        "SaveDataCloudRow",
        "workbench.extension.save_data.cloud_row.select",
    ),
    click(
        "SaveDataPlayerStateRow",
        "workbench.extension.save_data.player_state_row.select",
    ),
    click(
        "SaveDataInventoryRow",
        "workbench.extension.save_data.inventory_row.select",
    ),
    click(
        "SaveDataQuestLogRow",
        "workbench.extension.save_data.quest_log_row.select",
    ),
    click(
        "SaveDataDebugSlotRow",
        "workbench.extension.save_data.debug_slot_row.select",
    ),
    click(
        "SaveDataOutput",
        "workbench.extension.save_data.output.select",
    ),
    click(
        "SaveDataSaveSlot",
        "workbench.extension.save_data.save_slot.invoke",
    ),
    click(
        "SaveDataLoadSlot",
        "workbench.extension.save_data.load_slot.invoke",
    ),
    change(
        "SaveDataSchemaEdit",
        "workbench.extension.save_data.schema.edit",
    ),
    submit(
        "SaveDataSchemaCommit",
        "workbench.extension.save_data.schema.commit",
    ),
    change(
        "SaveDataSlotEdit",
        "workbench.extension.save_data.slot.edit",
    ),
    submit(
        "SaveDataSlotCommit",
        "workbench.extension.save_data.slot.commit",
    ),
    change(
        "SaveDataCompressionEdit",
        "workbench.extension.save_data.compression.edit",
    ),
    submit(
        "SaveDataCompressionCommit",
        "workbench.extension.save_data.compression.commit",
    ),
];
