use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const SIMULATION_PHYSICS_BINDINGS: &[ExtensionBindingSpec] = &[
    click(
        "CollisionProxyOpen",
        "workbench.extension.collision_proxy.open",
    ),
    click(
        "CollisionProxyProxyTab",
        "workbench.extension.collision_proxy.proxy_tab.select",
    ),
    click(
        "CollisionProxyChannelsTab",
        "workbench.extension.collision_proxy.channels_tab.select",
    ),
    click(
        "CollisionProxyContactsTab",
        "workbench.extension.collision_proxy.contacts_tab.select",
    ),
    click(
        "CollisionProxyRockCliffRow",
        "workbench.extension.collision_proxy.rock_cliff_row.select",
    ),
    click(
        "CollisionProxyHullProxyARow",
        "workbench.extension.collision_proxy.hull_proxy_a_row.select",
    ),
    click(
        "CollisionProxyChannelPlayerRow",
        "workbench.extension.collision_proxy.channel_player_row.select",
    ),
    click(
        "CollisionProxySourceMeshTableRow",
        "workbench.extension.collision_proxy.source_mesh_table_row.select",
    ),
    click(
        "CollisionProxyDecimatorTableRow",
        "workbench.extension.collision_proxy.decimator_table_row.select",
    ),
    click(
        "CollisionProxyHullMergeTableRow",
        "workbench.extension.collision_proxy.hull_merge_table_row.select",
    ),
    click(
        "CollisionProxyChannelMaskTableRow",
        "workbench.extension.collision_proxy.channel_mask_table_row.select",
    ),
    click(
        "CollisionProxyOutput",
        "workbench.extension.collision_proxy.output.select",
    ),
    click(
        "CollisionProxyBake",
        "workbench.extension.collision_proxy.bake.invoke",
    ),
    click(
        "CollisionProxyTestContacts",
        "workbench.extension.collision_proxy.test_contacts.invoke",
    ),
    change(
        "CollisionProxyProxyEdit",
        "workbench.extension.collision_proxy.proxy.edit",
    ),
    submit(
        "CollisionProxyProxyCommit",
        "workbench.extension.collision_proxy.proxy.commit",
    ),
    change(
        "CollisionProxyChannelEdit",
        "workbench.extension.collision_proxy.channel.edit",
    ),
    submit(
        "CollisionProxyChannelCommit",
        "workbench.extension.collision_proxy.channel.commit",
    ),
    change(
        "CollisionProxyLodEdit",
        "workbench.extension.collision_proxy.lod.edit",
    ),
    submit(
        "CollisionProxyLodCommit",
        "workbench.extension.collision_proxy.lod.commit",
    ),
];
