use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const SIMULATION_PHYSICS_BINDINGS: &[ExtensionBindingSpec] = &[
    click(
        "CollisionProxyOpen",
        "workbench.extension.collision_proxy.open",
    ),
    click(
        "CollisionProxyProxyTab",
        "workbench.extension.collision_proxy.proxy_tab.select",
    ),
    click(
        "CollisionProxyChannelsTab",
        "workbench.extension.collision_proxy.channels_tab.select",
    ),
    click(
        "CollisionProxyContactsTab",
        "workbench.extension.collision_proxy.contacts_tab.select",
    ),
    click(
        "CollisionProxyRockCliffRow",
        "workbench.extension.collision_proxy.rock_cliff_row.select",
    ),
    click(
        "CollisionProxyHullProxyARow",
        "workbench.extension.collision_proxy.hull_proxy_a_row.select",
    ),
    click(
        "CollisionProxyChannelPlayerRow",
        "workbench.extension.collision_proxy.channel_player_row.select",
    ),
    click(
        "CollisionProxySourceMeshTableRow",
        "workbench.extension.collision_proxy.source_mesh_table_row.select",
    ),
    click(
        "CollisionProxyDecimatorTableRow",
        "workbench.extension.collision_proxy.decimator_table_row.select",
    ),
    click(
        "CollisionProxyHullMergeTableRow",
        "workbench.extension.collision_proxy.hull_merge_table_row.select",
    ),
    click(
        "CollisionProxyChannelMaskTableRow",
        "workbench.extension.collision_proxy.channel_mask_table_row.select",
    ),
    click(
        "CollisionProxyOutput",
        "workbench.extension.collision_proxy.output.select",
    ),
    click(
        "CollisionProxyBake",
        "workbench.extension.collision_proxy.bake.invoke",
    ),
    click(
        "CollisionProxyTestContacts",
        "workbench.extension.collision_proxy.test_contacts.invoke",
    ),
    change(
        "CollisionProxyProxyEdit",
        "workbench.extension.collision_proxy.proxy.edit",
    ),
    submit(
        "CollisionProxyProxyCommit",
        "workbench.extension.collision_proxy.proxy.commit",
    ),
    change(
        "CollisionProxyChannelEdit",
        "workbench.extension.collision_proxy.channel.edit",
    ),
    submit(
        "CollisionProxyChannelCommit",
        "workbench.extension.collision_proxy.channel.commit",
    ),
    change(
        "CollisionProxyLodEdit",
        "workbench.extension.collision_proxy.lod.edit",
    ),
    submit(
        "CollisionProxyLodCommit",
        "workbench.extension.collision_proxy.lod.commit",
    ),
    click(
        "PhysicsCollisionOpen",
        "workbench.extension.physics_collision.open",
    ),
    click(
        "PhysicsCollisionBodiesTab",
        "workbench.extension.physics_collision.bodies_tab.select",
    ),
    click(
        "PhysicsCollisionMaterialsTab",
        "workbench.extension.physics_collision.materials_tab.select",
    ),
    click(
        "PhysicsCollisionContactsTab",
        "workbench.extension.physics_collision.contacts_tab.select",
    ),
    click(
        "PhysicsCollisionPlayerCapsuleRow",
        "workbench.extension.physics_collision.player_capsule_row.select",
    ),
    click(
        "PhysicsCollisionMaterialIceRow",
        "workbench.extension.physics_collision.material_ice_row.select",
    ),
    click(
        "PhysicsCollisionContactWallRow",
        "workbench.extension.physics_collision.contact_wall_row.select",
    ),
    click(
        "PhysicsCollisionPlayerCapsuleTableRow",
        "workbench.extension.physics_collision.player_capsule_table_row.select",
    ),
    click(
        "PhysicsCollisionIceMaterialTableRow",
        "workbench.extension.physics_collision.ice_material_table_row.select",
    ),
    click(
        "PhysicsCollisionWallContactTableRow",
        "workbench.extension.physics_collision.wall_contact_table_row.select",
    ),
    click(
        "PhysicsCollisionCcdWarningTableRow",
        "workbench.extension.physics_collision.ccd_warning_table_row.select",
    ),
    click(
        "PhysicsCollisionOutput",
        "workbench.extension.physics_collision.output.select",
    ),
    click(
        "PhysicsCollisionSimulate",
        "workbench.extension.physics_collision.simulate.invoke",
    ),
    click(
        "PhysicsCollisionValidate",
        "workbench.extension.physics_collision.validate.invoke",
    ),
    change(
        "PhysicsCollisionProfileEdit",
        "workbench.extension.physics_collision.profile.edit",
    ),
    submit(
        "PhysicsCollisionProfileCommit",
        "workbench.extension.physics_collision.profile.commit",
    ),
    change(
        "PhysicsCollisionSolverEdit",
        "workbench.extension.physics_collision.solver.edit",
    ),
    submit(
        "PhysicsCollisionSolverCommit",
        "workbench.extension.physics_collision.solver.commit",
    ),
    change(
        "PhysicsCollisionMassEdit",
        "workbench.extension.physics_collision.mass.edit",
    ),
    submit(
        "PhysicsCollisionMassCommit",
        "workbench.extension.physics_collision.mass.commit",
    ),
];
