mod observability;

use super::types::{ExtensionBindingSpec, change, click, submit};

pub(super) use self::observability::DIAGNOSTICS_OBSERVABILITY_BINDINGS;

pub(super) const UI_AUTHORING_BINDINGS: &[ExtensionBindingSpec] = &[
    click(
        "UiAssetEditorOpen",
        "workbench.extension.ui_asset_editor.open",
    ),
    click(
        "UiAssetEditorHierarchyTab",
        "workbench.extension.ui_asset_editor.hierarchy_tab.select",
    ),
    click(
        "UiAssetEditorStatesTab",
        "workbench.extension.ui_asset_editor.states_tab.select",
    ),
    click(
        "UiAssetEditorBindingsTab",
        "workbench.extension.ui_asset_editor.bindings_tab.select",
    ),
    click(
        "UiAssetEditorInventoryRow",
        "workbench.extension.ui_asset_editor.inventory_row.select",
    ),
    click(
        "UiAssetEditorPanelRootRow",
        "workbench.extension.ui_asset_editor.panel_root_row.select",
    ),
    click(
        "UiAssetEditorEquipButtonRow",
        "workbench.extension.ui_asset_editor.equip_button_row.select",
    ),
    click(
        "UiAssetEditorRootPanelRow",
        "workbench.extension.ui_asset_editor.root_panel_row.select",
    ),
    click(
        "UiAssetEditorInventoryGridRow",
        "workbench.extension.ui_asset_editor.inventory_grid_row.select",
    ),
    click(
        "UiAssetEditorSelectedButtonRow",
        "workbench.extension.ui_asset_editor.selected_button_row.select",
    ),
    click(
        "UiAssetEditorBindingRow",
        "workbench.extension.ui_asset_editor.binding_row.select",
    ),
    click(
        "UiAssetEditorOutput",
        "workbench.extension.ui_asset_editor.output.select",
    ),
    click(
        "UiAssetEditorPreview",
        "workbench.extension.ui_asset_editor.preview.invoke",
    ),
    click(
        "UiAssetEditorValidate",
        "workbench.extension.ui_asset_editor.validate.invoke",
    ),
    click("UiBindingOpen", "workbench.extension.ui_binding.open"),
    click(
        "UiBindingBindingsTab",
        "workbench.extension.ui_binding.bindings_tab.select",
    ),
    click(
        "UiBindingExpressionsTab",
        "workbench.extension.ui_binding.expressions_tab.select",
    ),
    click(
        "UiBindingValidationTab",
        "workbench.extension.ui_binding.validation_tab.select",
    ),
    click(
        "UiBindingViewModelRow",
        "workbench.extension.ui_binding.view_model_row.select",
    ),
    click(
        "UiBindingHealthRow",
        "workbench.extension.ui_binding.health_row.select",
    ),
    click(
        "UiBindingAmmoRow",
        "workbench.extension.ui_binding.ammo_row.select",
    ),
    click(
        "UiBindingViewModelTableRow",
        "workbench.extension.ui_binding.view_model_table_row.select",
    ),
    click(
        "UiBindingHealthTableRow",
        "workbench.extension.ui_binding.health_table_row.select",
    ),
    click(
        "UiBindingConverterTableRow",
        "workbench.extension.ui_binding.converter_table_row.select",
    ),
    click(
        "UiBindingValidationTableRow",
        "workbench.extension.ui_binding.validation_table_row.select",
    ),
    click(
        "UiBindingOutput",
        "workbench.extension.ui_binding.output.select",
    ),
    click(
        "UiBindingPreview",
        "workbench.extension.ui_binding.preview.invoke",
    ),
    click(
        "UiBindingValidate",
        "workbench.extension.ui_binding.validate.invoke",
    ),
    click("IconLibraryOpen", "workbench.extension.icon_library.open"),
    click(
        "IconLibraryIconTab",
        "workbench.extension.icon_library.icon_tab.select",
    ),
    click(
        "IconLibraryUsageTab",
        "workbench.extension.icon_library.usage_tab.select",
    ),
    click(
        "IconLibraryExportTab",
        "workbench.extension.icon_library.export_tab.select",
    ),
    click(
        "IconLibraryEditorCoreRow",
        "workbench.extension.icon_library.editor_core_row.select",
    ),
    click(
        "IconLibraryWarningRow",
        "workbench.extension.icon_library.warning_row.select",
    ),
    click(
        "IconLibraryUsageTopbarRow",
        "workbench.extension.icon_library.usage_topbar_row.select",
    ),
    click(
        "IconLibrarySaveTableRow",
        "workbench.extension.icon_library.save_table_row.select",
    ),
    click(
        "IconLibraryPlayTableRow",
        "workbench.extension.icon_library.play_table_row.select",
    ),
    click(
        "IconLibraryWarningTableRow",
        "workbench.extension.icon_library.warning_table_row.select",
    ),
    click(
        "IconLibraryArchivedTableRow",
        "workbench.extension.icon_library.archived_table_row.select",
    ),
    click(
        "IconLibraryOutput",
        "workbench.extension.icon_library.output.select",
    ),
    click(
        "IconLibraryFindUsage",
        "workbench.extension.icon_library.find_usage.invoke",
    ),
    click(
        "IconLibraryValidate",
        "workbench.extension.icon_library.validate.invoke",
    ),
    click(
        "AccessibilityAuditOpen",
        "workbench.extension.accessibility_audit.open",
    ),
    click(
        "AccessibilityAuditIssuesTab",
        "workbench.extension.accessibility_audit.issues_tab.select",
    ),
    click(
        "AccessibilityAuditRulesTab",
        "workbench.extension.accessibility_audit.rules_tab.select",
    ),
    click(
        "AccessibilityAuditFixesTab",
        "workbench.extension.accessibility_audit.fixes_tab.select",
    ),
    click(
        "AccessibilityAuditGameplayHudRow",
        "workbench.extension.accessibility_audit.gameplay_hud_row.select",
    ),
    click(
        "AccessibilityAuditContrastIssueRow",
        "workbench.extension.accessibility_audit.contrast_issue_row.select",
    ),
    click(
        "AccessibilityAuditFocusIssueRow",
        "workbench.extension.accessibility_audit.focus_issue_row.select",
    ),
    click(
        "AccessibilityAuditContrastTableRow",
        "workbench.extension.accessibility_audit.contrast_table_row.select",
    ),
    click(
        "AccessibilityAuditFocusTableRow",
        "workbench.extension.accessibility_audit.focus_table_row.select",
    ),
    click(
        "AccessibilityAuditTargetSizeTableRow",
        "workbench.extension.accessibility_audit.target_size_table_row.select",
    ),
    click(
        "AccessibilityAuditMotionTableRow",
        "workbench.extension.accessibility_audit.motion_table_row.select",
    ),
    click(
        "AccessibilityAuditOutput",
        "workbench.extension.accessibility_audit.output.select",
    ),
    click(
        "AccessibilityAuditAuditScreen",
        "workbench.extension.accessibility_audit.audit_screen.invoke",
    ),
    click(
        "AccessibilityAuditPreviewFix",
        "workbench.extension.accessibility_audit.preview_fix.invoke",
    ),
    click("MenuFlowOpen", "workbench.extension.menu_flow.open"),
    click(
        "MenuFlowRoutesTab",
        "workbench.extension.menu_flow.routes_tab.select",
    ),
    click(
        "MenuFlowFocusTab",
        "workbench.extension.menu_flow.focus_tab.select",
    ),
    click(
        "MenuFlowSimulationTab",
        "workbench.extension.menu_flow.simulation_tab.select",
    ),
    click(
        "MenuFlowMainMenuRow",
        "workbench.extension.menu_flow.main_menu_row.select",
    ),
    click(
        "MenuFlowStartScreenRow",
        "workbench.extension.menu_flow.start_screen_row.select",
    ),
    click(
        "MenuFlowFocusPlayButtonRow",
        "workbench.extension.menu_flow.focus_play_button_row.select",
    ),
    click(
        "MenuFlowStartNodeRow",
        "workbench.extension.menu_flow.start_node_row.select",
    ),
    click(
        "MenuFlowOptionsNodeRow",
        "workbench.extension.menu_flow.options_node_row.select",
    ),
    click(
        "MenuFlowMatchNodeRow",
        "workbench.extension.menu_flow.match_node_row.select",
    ),
    click(
        "MenuFlowExitRouteRow",
        "workbench.extension.menu_flow.exit_route_row.select",
    ),
    click(
        "MenuFlowOutput",
        "workbench.extension.menu_flow.output.select",
    ),
    click(
        "MenuFlowPreviewFlow",
        "workbench.extension.menu_flow.preview_flow.invoke",
    ),
    click(
        "MenuFlowValidateFocus",
        "workbench.extension.menu_flow.validate_focus.invoke",
    ),
    click("FontAtlasOpen", "workbench.extension.font_atlas.open"),
    click(
        "FontAtlasGlyphsTab",
        "workbench.extension.font_atlas.glyphs_tab.select",
    ),
    click(
        "FontAtlasKerningTab",
        "workbench.extension.font_atlas.kerning_tab.select",
    ),
    click(
        "FontAtlasCoverageTab",
        "workbench.extension.font_atlas.coverage_tab.select",
    ),
    click(
        "FontAtlasInterUiRow",
        "workbench.extension.font_atlas.inter_ui_row.select",
    ),
    click(
        "FontAtlasLatinRangeRow",
        "workbench.extension.font_atlas.latin_range_row.select",
    ),
    click(
        "FontAtlasCjkRangeRow",
        "workbench.extension.font_atlas.cjk_range_row.select",
    ),
    click(
        "FontAtlasLatinTableRow",
        "workbench.extension.font_atlas.latin_table_row.select",
    ),
    click(
        "FontAtlasCyrillicTableRow",
        "workbench.extension.font_atlas.cyrillic_table_row.select",
    ),
    click(
        "FontAtlasCjkTableRow",
        "workbench.extension.font_atlas.cjk_table_row.select",
    ),
    click(
        "FontAtlasIconsTableRow",
        "workbench.extension.font_atlas.icons_table_row.select",
    ),
    click(
        "FontAtlasOutput",
        "workbench.extension.font_atlas.output.select",
    ),
    click(
        "FontAtlasBakeAtlas",
        "workbench.extension.font_atlas.bake_atlas.invoke",
    ),
    click(
        "FontAtlasInspectGlyph",
        "workbench.extension.font_atlas.inspect_glyph.invoke",
    ),
    change(
        "UiAssetEditorWidgetEdit",
        "workbench.extension.ui_asset_editor.widget.edit",
    ),
    submit(
        "UiAssetEditorWidgetCommit",
        "workbench.extension.ui_asset_editor.widget.commit",
    ),
    change(
        "UiAssetEditorBreakpointEdit",
        "workbench.extension.ui_asset_editor.breakpoint.edit",
    ),
    submit(
        "UiAssetEditorBreakpointCommit",
        "workbench.extension.ui_asset_editor.breakpoint.commit",
    ),
    change(
        "UiAssetEditorThemeEdit",
        "workbench.extension.ui_asset_editor.theme.edit",
    ),
    submit(
        "UiAssetEditorThemeCommit",
        "workbench.extension.ui_asset_editor.theme.commit",
    ),
    change(
        "UiBindingFieldEdit",
        "workbench.extension.ui_binding.field.edit",
    ),
    submit(
        "UiBindingFieldCommit",
        "workbench.extension.ui_binding.field.commit",
    ),
    change(
        "UiBindingWidgetEdit",
        "workbench.extension.ui_binding.widget.edit",
    ),
    submit(
        "UiBindingWidgetCommit",
        "workbench.extension.ui_binding.widget.commit",
    ),
    change(
        "UiBindingConverterEdit",
        "workbench.extension.ui_binding.converter.edit",
    ),
    submit(
        "UiBindingConverterCommit",
        "workbench.extension.ui_binding.converter.commit",
    ),
    change(
        "IconLibraryIconEdit",
        "workbench.extension.icon_library.icon.edit",
    ),
    submit(
        "IconLibraryIconCommit",
        "workbench.extension.icon_library.icon.commit",
    ),
    change(
        "IconLibrarySetEdit",
        "workbench.extension.icon_library.set.edit",
    ),
    submit(
        "IconLibrarySetCommit",
        "workbench.extension.icon_library.set.commit",
    ),
    change(
        "IconLibraryColorTokenEdit",
        "workbench.extension.icon_library.color_token.edit",
    ),
    submit(
        "IconLibraryColorTokenCommit",
        "workbench.extension.icon_library.color_token.commit",
    ),
    change(
        "AccessibilityAuditScreenEdit",
        "workbench.extension.accessibility_audit.screen.edit",
    ),
    submit(
        "AccessibilityAuditScreenCommit",
        "workbench.extension.accessibility_audit.screen.commit",
    ),
    change(
        "AccessibilityAuditRuleSetEdit",
        "workbench.extension.accessibility_audit.rule_set.edit",
    ),
    submit(
        "AccessibilityAuditRuleSetCommit",
        "workbench.extension.accessibility_audit.rule_set.commit",
    ),
    change(
        "AccessibilityAuditBreakpointEdit",
        "workbench.extension.accessibility_audit.breakpoint.edit",
    ),
    submit(
        "AccessibilityAuditBreakpointCommit",
        "workbench.extension.accessibility_audit.breakpoint.commit",
    ),
    change(
        "MenuFlowScreenEdit",
        "workbench.extension.menu_flow.screen.edit",
    ),
    submit(
        "MenuFlowScreenCommit",
        "workbench.extension.menu_flow.screen.commit",
    ),
    change(
        "MenuFlowBreakpointEdit",
        "workbench.extension.menu_flow.breakpoint.edit",
    ),
    submit(
        "MenuFlowBreakpointCommit",
        "workbench.extension.menu_flow.breakpoint.commit",
    ),
    change(
        "MenuFlowTransitionEdit",
        "workbench.extension.menu_flow.transition.edit",
    ),
    submit(
        "MenuFlowTransitionCommit",
        "workbench.extension.menu_flow.transition.commit",
    ),
    change(
        "FontAtlasFontEdit",
        "workbench.extension.font_atlas.font.edit",
    ),
    submit(
        "FontAtlasFontCommit",
        "workbench.extension.font_atlas.font.commit",
    ),
    change(
        "FontAtlasRangeEdit",
        "workbench.extension.font_atlas.range.edit",
    ),
    submit(
        "FontAtlasRangeCommit",
        "workbench.extension.font_atlas.range.commit",
    ),
    change(
        "FontAtlasSizeEdit",
        "workbench.extension.font_atlas.size.edit",
    ),
    submit(
        "FontAtlasSizeCommit",
        "workbench.extension.font_atlas.size.commit",
    ),
];
