use super::types::{change, click, submit, ExtensionBindingSpec};

pub(super) const WORLD_BUILDING_BINDINGS: &[ExtensionBindingSpec] = &[
    click(
        "TerrainEditorOpen",
        "workbench.extension.terrain_editor.open",
    ),
    click(
        "TerrainEditorSculptTab",
        "workbench.extension.terrain_editor.sculpt_tab.select",
    ),
    click(
        "TerrainEditorPaintTab",
        "workbench.extension.terrain_editor.paint_tab.select",
    ),
    click(
        "TerrainEditorStreamingTab",
        "workbench.extension.terrain_editor.streaming_tab.select",
    ),
    click(
        "TerrainEditorLandscapeRow",
        "workbench.extension.terrain_editor.landscape_row.select",
    ),
    click(
        "TerrainEditorHeightfieldRow",
        "workbench.extension.terrain_editor.heightfield_row.select",
    ),
    click(
        "TerrainEditorLayerRockRow",
        "workbench.extension.terrain_editor.layer_rock_row.select",
    ),
    click(
        "TerrainEditorCellA1208TableRow",
        "workbench.extension.terrain_editor.cell_a_1208_table_row.select",
    ),
    click(
        "TerrainEditorCellA1209TableRow",
        "workbench.extension.terrain_editor.cell_a_1209_table_row.select",
    ),
    click(
        "TerrainEditorRockLayerTableRow",
        "workbench.extension.terrain_editor.rock_layer_table_row.select",
    ),
    click(
        "TerrainEditorStreamingCellTableRow",
        "workbench.extension.terrain_editor.streaming_cell_table_row.select",
    ),
    click(
        "TerrainEditorOutput",
        "workbench.extension.terrain_editor.output.select",
    ),
    click(
        "TerrainEditorPreview",
        "workbench.extension.terrain_editor.preview.invoke",
    ),
    click(
        "TerrainEditorBuild",
        "workbench.extension.terrain_editor.build.invoke",
    ),
    change(
        "TerrainEditorBrushEdit",
        "workbench.extension.terrain_editor.brush.edit",
    ),
    submit(
        "TerrainEditorBrushCommit",
        "workbench.extension.terrain_editor.brush.commit",
    ),
    change(
        "TerrainEditorRadiusEdit",
        "workbench.extension.terrain_editor.radius.edit",
    ),
    submit(
        "TerrainEditorRadiusCommit",
        "workbench.extension.terrain_editor.radius.commit",
    ),
    change(
        "TerrainEditorStrengthEdit",
        "workbench.extension.terrain_editor.strength.edit",
    ),
    submit(
        "TerrainEditorStrengthCommit",
        "workbench.extension.terrain_editor.strength.commit",
    ),
    click(
        "FoliageEditorOpen",
        "workbench.extension.foliage_editor.open",
    ),
    click(
        "FoliageEditorPaintTab",
        "workbench.extension.foliage_editor.paint_tab.select",
    ),
    click(
        "FoliageEditorEraseTab",
        "workbench.extension.foliage_editor.erase_tab.select",
    ),
    click(
        "FoliageEditorClustersTab",
        "workbench.extension.foliage_editor.clusters_tab.select",
    ),
    click(
        "FoliageEditorForestRow",
        "workbench.extension.foliage_editor.forest_row.select",
    ),
    click(
        "FoliageEditorOakRow",
        "workbench.extension.foliage_editor.oak_row.select",
    ),
    click(
        "FoliageEditorBiomeRow",
        "workbench.extension.foliage_editor.biome_row.select",
    ),
    click(
        "FoliageEditorForestA12TableRow",
        "workbench.extension.foliage_editor.forest_a_12_table_row.select",
    ),
    click(
        "FoliageEditorForestA13TableRow",
        "workbench.extension.foliage_editor.forest_a_13_table_row.select",
    ),
    click(
        "FoliageEditorRiver02TableRow",
        "workbench.extension.foliage_editor.river_02_table_row.select",
    ),
    click(
        "FoliageEditorCliff01TableRow",
        "workbench.extension.foliage_editor.cliff_01_table_row.select",
    ),
    click(
        "FoliageEditorOutput",
        "workbench.extension.foliage_editor.output.select",
    ),
    click(
        "FoliageEditorPreview",
        "workbench.extension.foliage_editor.preview.invoke",
    ),
    click(
        "FoliageEditorBuild",
        "workbench.extension.foliage_editor.build.invoke",
    ),
    change(
        "FoliageEditorTypeEdit",
        "workbench.extension.foliage_editor.type.edit",
    ),
    submit(
        "FoliageEditorTypeCommit",
        "workbench.extension.foliage_editor.type.commit",
    ),
    change(
        "FoliageEditorDensityEdit",
        "workbench.extension.foliage_editor.density.edit",
    ),
    submit(
        "FoliageEditorDensityCommit",
        "workbench.extension.foliage_editor.density.commit",
    ),
    change(
        "FoliageEditorRadiusEdit",
        "workbench.extension.foliage_editor.radius.edit",
    ),
    submit(
        "FoliageEditorRadiusCommit",
        "workbench.extension.foliage_editor.radius.commit",
    ),
    click(
        "LevelStreamingOpen",
        "workbench.extension.level_streaming.open",
    ),
    click(
        "LevelStreamingCellsTab",
        "workbench.extension.level_streaming.cells_tab.select",
    ),
    click(
        "LevelStreamingRulesTab",
        "workbench.extension.level_streaming.rules_tab.select",
    ),
    click(
        "LevelStreamingEventsTab",
        "workbench.extension.level_streaming.events_tab.select",
    ),
    click(
        "LevelStreamingWorldRow",
        "workbench.extension.level_streaming.world_row.select",
    ),
    click(
        "LevelStreamingCellA12Row",
        "workbench.extension.level_streaming.cell_a_12_row.select",
    ),
    click(
        "LevelStreamingRulePlayerDistanceRow",
        "workbench.extension.level_streaming.rule_player_distance_row.select",
    ),
    click(
        "LevelStreamingCellA12TableRow",
        "workbench.extension.level_streaming.cell_a_12_table_row.select",
    ),
    click(
        "LevelStreamingCellA13TableRow",
        "workbench.extension.level_streaming.cell_a_13_table_row.select",
    ),
    click(
        "LevelStreamingHlod04TableRow",
        "workbench.extension.level_streaming.hlod_04_table_row.select",
    ),
    click(
        "LevelStreamingCellB12TableRow",
        "workbench.extension.level_streaming.cell_b_12_table_row.select",
    ),
    click(
        "LevelStreamingOutput",
        "workbench.extension.level_streaming.output.select",
    ),
    click(
        "LevelStreamingPreview",
        "workbench.extension.level_streaming.preview.invoke",
    ),
    click(
        "LevelStreamingLoad",
        "workbench.extension.level_streaming.load.invoke",
    ),
    change(
        "LevelStreamingCellEdit",
        "workbench.extension.level_streaming.cell.edit",
    ),
    submit(
        "LevelStreamingCellCommit",
        "workbench.extension.level_streaming.cell.commit",
    ),
    change(
        "LevelStreamingRuleEdit",
        "workbench.extension.level_streaming.rule.edit",
    ),
    submit(
        "LevelStreamingRuleCommit",
        "workbench.extension.level_streaming.rule.commit",
    ),
    change(
        "LevelStreamingDistanceEdit",
        "workbench.extension.level_streaming.distance.edit",
    ),
    submit(
        "LevelStreamingDistanceCommit",
        "workbench.extension.level_streaming.distance.commit",
    ),
    click("LevelVariantOpen", "workbench.extension.level_variant.open"),
    click(
        "LevelVariantVariantTab",
        "workbench.extension.level_variant.variant_tab.select",
    ),
    click(
        "LevelVariantOverridesTab",
        "workbench.extension.level_variant.overrides_tab.select",
    ),
    click(
        "LevelVariantDiffTab",
        "workbench.extension.level_variant.diff_tab.select",
    ),
    click(
        "LevelVariantSetRow",
        "workbench.extension.level_variant.set_row.select",
    ),
    click(
        "LevelVariantRedRow",
        "workbench.extension.level_variant.red_row.select",
    ),
    click(
        "LevelVariantActorOverrideRow",
        "workbench.extension.level_variant.actor_override_row.select",
    ),
    click(
        "LevelVariantCarBodyTableRow",
        "workbench.extension.level_variant.car_body_table_row.select",
    ),
    click(
        "LevelVariantWheelFlTableRow",
        "workbench.extension.level_variant.wheel_fl_table_row.select",
    ),
    click(
        "LevelVariantLightRigTableRow",
        "workbench.extension.level_variant.light_rig_table_row.select",
    ),
    click(
        "LevelVariantDoorLTableRow",
        "workbench.extension.level_variant.door_l_table_row.select",
    ),
    click(
        "LevelVariantOutput",
        "workbench.extension.level_variant.output.select",
    ),
    click(
        "LevelVariantPreview",
        "workbench.extension.level_variant.preview.invoke",
    ),
    click(
        "LevelVariantApply",
        "workbench.extension.level_variant.apply.invoke",
    ),
    change(
        "LevelVariantVariantEdit",
        "workbench.extension.level_variant.variant.edit",
    ),
    submit(
        "LevelVariantVariantCommit",
        "workbench.extension.level_variant.variant.commit",
    ),
    change(
        "LevelVariantSetEdit",
        "workbench.extension.level_variant.set.edit",
    ),
    submit(
        "LevelVariantSetCommit",
        "workbench.extension.level_variant.set.commit",
    ),
    change(
        "LevelVariantCaptureEdit",
        "workbench.extension.level_variant.capture.edit",
    ),
    submit(
        "LevelVariantCaptureCommit",
        "workbench.extension.level_variant.capture.commit",
    ),
    click("PrefabEditorOpen", "workbench.extension.prefab_editor.open"),
    click(
        "PrefabEditorHierarchyTab",
        "workbench.extension.prefab_editor.hierarchy_tab.select",
    ),
    click(
        "PrefabEditorOverridesTab",
        "workbench.extension.prefab_editor.overrides_tab.select",
    ),
    click(
        "PrefabEditorValidationTab",
        "workbench.extension.prefab_editor.validation_tab.select",
    ),
    click(
        "PrefabEditorPrefabRootRow",
        "workbench.extension.prefab_editor.prefab_root_row.select",
    ),
    click(
        "PrefabEditorMeshComponentRow",
        "workbench.extension.prefab_editor.mesh_component_row.select",
    ),
    click(
        "PrefabEditorLootSocketRow",
        "workbench.extension.prefab_editor.loot_socket_row.select",
    ),
    click(
        "PrefabEditorMeshTableRow",
        "workbench.extension.prefab_editor.mesh_table_row.select",
    ),
    click(
        "PrefabEditorLootSocketTableRow",
        "workbench.extension.prefab_editor.loot_socket_table_row.select",
    ),
    click(
        "PrefabEditorLightTableRow",
        "workbench.extension.prefab_editor.light_table_row.select",
    ),
    click(
        "PrefabEditorOverrideTableRow",
        "workbench.extension.prefab_editor.override_table_row.select",
    ),
    click(
        "PrefabEditorOutput",
        "workbench.extension.prefab_editor.output.select",
    ),
    click(
        "PrefabEditorApply",
        "workbench.extension.prefab_editor.apply.invoke",
    ),
    click(
        "PrefabEditorValidate",
        "workbench.extension.prefab_editor.validate.invoke",
    ),
    change(
        "PrefabEditorPrefabEdit",
        "workbench.extension.prefab_editor.prefab.edit",
    ),
    submit(
        "PrefabEditorPrefabCommit",
        "workbench.extension.prefab_editor.prefab.commit",
    ),
    change(
        "PrefabEditorVariantEdit",
        "workbench.extension.prefab_editor.variant.edit",
    ),
    submit(
        "PrefabEditorVariantCommit",
        "workbench.extension.prefab_editor.variant.commit",
    ),
    change(
        "PrefabEditorInstanceEdit",
        "workbench.extension.prefab_editor.instance.edit",
    ),
    submit(
        "PrefabEditorInstanceCommit",
        "workbench.extension.prefab_editor.instance.commit",
    ),
    click(
        "ScatterEditorOpen",
        "workbench.extension.scatter_editor.open",
    ),
    click(
        "ScatterEditorRulesTab",
        "workbench.extension.scatter_editor.rules_tab.select",
    ),
    click(
        "ScatterEditorConstraintsTab",
        "workbench.extension.scatter_editor.constraints_tab.select",
    ),
    click(
        "ScatterEditorOutputTab",
        "workbench.extension.scatter_editor.output_tab.select",
    ),
    click(
        "ScatterEditorSetRow",
        "workbench.extension.scatter_editor.set_row.select",
    ),
    click(
        "ScatterEditorRocksRuleRow",
        "workbench.extension.scatter_editor.rocks_rule_row.select",
    ),
    click(
        "ScatterEditorFernsRuleRow",
        "workbench.extension.scatter_editor.ferns_rule_row.select",
    ),
    click(
        "ScatterEditorBiomeMaskTableRow",
        "workbench.extension.scatter_editor.biome_mask_table_row.select",
    ),
    click(
        "ScatterEditorSlopeFilterTableRow",
        "workbench.extension.scatter_editor.slope_filter_table_row.select",
    ),
    click(
        "ScatterEditorSpawnRuleTableRow",
        "workbench.extension.scatter_editor.spawn_rule_table_row.select",
    ),
    click(
        "ScatterEditorCollisionTestTableRow",
        "workbench.extension.scatter_editor.collision_test_table_row.select",
    ),
    click(
        "ScatterEditorOutput",
        "workbench.extension.scatter_editor.output.select",
    ),
    click(
        "ScatterEditorGenerate",
        "workbench.extension.scatter_editor.generate.invoke",
    ),
    click(
        "ScatterEditorValidate",
        "workbench.extension.scatter_editor.validate.invoke",
    ),
    change(
        "ScatterEditorRuleSetEdit",
        "workbench.extension.scatter_editor.rule_set.edit",
    ),
    submit(
        "ScatterEditorRuleSetCommit",
        "workbench.extension.scatter_editor.rule_set.commit",
    ),
    change(
        "ScatterEditorSeedEdit",
        "workbench.extension.scatter_editor.seed.edit",
    ),
    submit(
        "ScatterEditorSeedCommit",
        "workbench.extension.scatter_editor.seed.commit",
    ),
    change(
        "ScatterEditorDensityEdit",
        "workbench.extension.scatter_editor.density.edit",
    ),
    submit(
        "ScatterEditorDensityCommit",
        "workbench.extension.scatter_editor.density.commit",
    ),
    click("VolumeEditorOpen", "workbench.extension.volume_editor.open"),
    click(
        "VolumeEditorBoundsTab",
        "workbench.extension.volume_editor.bounds_tab.select",
    ),
    click(
        "VolumeEditorOverlapsTab",
        "workbench.extension.volume_editor.overlaps_tab.select",
    ),
    click(
        "VolumeEditorEventsTab",
        "workbench.extension.volume_editor.events_tab.select",
    ),
    click(
        "VolumeEditorDamageZoneRow",
        "workbench.extension.volume_editor.damage_zone_row.select",
    ),
    click(
        "VolumeEditorProfileDefaultRow",
        "workbench.extension.volume_editor.profile_default_row.select",
    ),
    click(
        "VolumeEditorOverlapPlayerRow",
        "workbench.extension.volume_editor.overlap_player_row.select",
    ),
    click(
        "VolumeEditorBoundsTableRow",
        "workbench.extension.volume_editor.bounds_table_row.select",
    ),
    click(
        "VolumeEditorPlayerOverlapTableRow",
        "workbench.extension.volume_editor.player_overlap_table_row.select",
    ),
    click(
        "VolumeEditorDamageRuleTableRow",
        "workbench.extension.volume_editor.damage_rule_table_row.select",
    ),
    click(
        "VolumeEditorOnEnterEventTableRow",
        "workbench.extension.volume_editor.on_enter_event_table_row.select",
    ),
    click(
        "VolumeEditorOutput",
        "workbench.extension.volume_editor.output.select",
    ),
    click(
        "VolumeEditorInspect",
        "workbench.extension.volume_editor.inspect.invoke",
    ),
    click(
        "VolumeEditorValidate",
        "workbench.extension.volume_editor.validate.invoke",
    ),
    change(
        "VolumeEditorVolumeEdit",
        "workbench.extension.volume_editor.volume.edit",
    ),
    submit(
        "VolumeEditorVolumeCommit",
        "workbench.extension.volume_editor.volume.commit",
    ),
    change(
        "VolumeEditorProfileEdit",
        "workbench.extension.volume_editor.profile.edit",
    ),
    submit(
        "VolumeEditorProfileCommit",
        "workbench.extension.volume_editor.profile.commit",
    ),
    change(
        "VolumeEditorPriorityEdit",
        "workbench.extension.volume_editor.priority.edit",
    ),
    submit(
        "VolumeEditorPriorityCommit",
        "workbench.extension.volume_editor.priority.commit",
    ),
    click(
        "WeatherEditorOpen",
        "workbench.extension.weather_editor.open",
    ),
    click(
        "WeatherEditorLayersTab",
        "workbench.extension.weather_editor.layers_tab.select",
    ),
    click(
        "WeatherEditorCurvesTab",
        "workbench.extension.weather_editor.curves_tab.select",
    ),
    click(
        "WeatherEditorTimelineTab",
        "workbench.extension.weather_editor.timeline_tab.select",
    ),
    click(
        "WeatherEditorStormRow",
        "workbench.extension.weather_editor.storm_row.select",
    ),
    click(
        "WeatherEditorMountainsRegionRow",
        "workbench.extension.weather_editor.mountains_region_row.select",
    ),
    click(
        "WeatherEditorCloudLayerRow",
        "workbench.extension.weather_editor.cloud_layer_row.select",
    ),
    click(
        "WeatherEditorCloudBuildTimelineRow",
        "workbench.extension.weather_editor.cloud_build_timeline_row.select",
    ),
    click(
        "WeatherEditorRainBurstTimelineRow",
        "workbench.extension.weather_editor.rain_burst_timeline_row.select",
    ),
    click(
        "WeatherEditorWindGustTimelineRow",
        "workbench.extension.weather_editor.wind_gust_timeline_row.select",
    ),
    click(
        "WeatherEditorLightningTimelineRow",
        "workbench.extension.weather_editor.lightning_timeline_row.select",
    ),
    click(
        "WeatherEditorOutput",
        "workbench.extension.weather_editor.output.select",
    ),
    click(
        "WeatherEditorPreview",
        "workbench.extension.weather_editor.preview.invoke",
    ),
    click(
        "WeatherEditorBuild",
        "workbench.extension.weather_editor.build.invoke",
    ),
    change(
        "WeatherEditorPresetEdit",
        "workbench.extension.weather_editor.preset.edit",
    ),
    submit(
        "WeatherEditorPresetCommit",
        "workbench.extension.weather_editor.preset.commit",
    ),
    change(
        "WeatherEditorRegionEdit",
        "workbench.extension.weather_editor.region.edit",
    ),
    submit(
        "WeatherEditorRegionCommit",
        "workbench.extension.weather_editor.region.commit",
    ),
    change(
        "WeatherEditorBlendTimeEdit",
        "workbench.extension.weather_editor.blend_time.edit",
    ),
    submit(
        "WeatherEditorBlendTimeCommit",
        "workbench.extension.weather_editor.blend_time.commit",
    ),
];
