//! Physics framework contracts for backend status, world stepping, queries, contacts, and scene sync.

mod backend_state;
mod backend_status;
mod body_sync_state;
mod body_type;
mod collider_shape;
mod collider_sync_state;
mod contact_event;
mod joint_sync_state;
mod joint_type;
mod manager;
mod material_sync_state;
mod mesh_asset;
mod query_filter;
mod query_interface;
mod query_mode;
mod ray_cast_hit;
mod ray_cast_query;
mod scene_step_result;
mod settings;
mod settings_store_error;
mod shape_cast_hit;
mod shape_cast_query;
mod shape_overlap_hit;
mod shape_overlap_query;
mod simulation_mode;
mod skeletal_pose;
mod trigger_event;
mod trigger_event_kind;
mod world_step_plan;
mod world_sync_state;

pub use backend_state::PhysicsBackendState;
pub use backend_status::PhysicsBackendStatus;
pub use body_sync_state::PhysicsBodySyncState;
pub use body_type::PhysicsBodyType;
pub use collider_shape::PhysicsColliderShape;
pub use collider_sync_state::PhysicsColliderSyncState;
pub use contact_event::PhysicsContactEvent;
pub use joint_sync_state::PhysicsJointSyncState;
pub use joint_type::PhysicsJointType;
pub use manager::PhysicsManager;
pub use material_sync_state::PhysicsMaterialSyncState;
pub use mesh_asset::PhysicsMeshAsset;
pub use query_filter::PhysicsQueryFilter;
pub use query_interface::{PhysicsQueryInterface, PHYSICS_QUERY_INTERFACE_ID};
pub use query_mode::PhysicsQueryMode;
pub use ray_cast_hit::PhysicsRayCastHit;
pub use ray_cast_query::PhysicsRayCastQuery;
pub use scene_step_result::PhysicsSceneStepResult;
pub use settings::PhysicsSettings;
pub use settings_store_error::PhysicsSettingsStoreError;
pub use shape_cast_hit::PhysicsShapeCastHit;
pub use shape_cast_query::PhysicsShapeCastQuery;
pub use shape_overlap_hit::PhysicsShapeOverlapHit;
pub use shape_overlap_query::PhysicsShapeOverlapQuery;
pub use simulation_mode::PhysicsSimulationMode;
pub use skeletal_pose::{SimulatedPoseFeed, SkeletalPoseTarget, SkeletalPoseTargets};
pub use trigger_event::PhysicsTriggerEvent;
pub use trigger_event_kind::PhysicsTriggerEventKind;
pub use world_step_plan::PhysicsWorldStepPlan;
pub use world_sync_state::PhysicsWorldSyncState;

#[cfg(test)]
mod tests;
