//! Workbench layout model and mutation logic for the editor shell.

mod activity_drawer_layout;
mod activity_drawer_mode;
mod activity_drawer_slot;
mod dock_edge;
mod document_node;
mod drag_payload;
mod drop_target;
mod floating_window_layout;
mod hit_target;
mod layout_command;
mod layout_diff;
mod layout_manager;
mod layout_normalization_report;
mod main_host_page_layout;
mod main_page_id;
mod manager;
mod restore_policy;
mod split_axis;
mod split_placement;
mod tab_insertion_anchor;
mod tab_insertion_side;
mod tab_stack_layout;
mod workbench_layout;
mod workspace_target;

pub use activity_drawer_layout::ActivityDrawerLayout;
pub use activity_drawer_mode::ActivityDrawerMode;
pub use activity_drawer_slot::ActivityDrawerSlot;
pub use dock_edge::DockEdge;
pub use document_node::DocumentNode;
pub use drag_payload::DragPayload;
pub use drop_target::DropTarget;
pub use floating_window_layout::FloatingWindowLayout;
pub use hit_target::HitTarget;
pub use layout_command::LayoutCommand;
pub use layout_diff::LayoutDiff;
pub use layout_manager::LayoutManager;
pub use layout_normalization_report::LayoutNormalizationReport;
pub use main_host_page_layout::MainHostPageLayout;
pub use main_page_id::MainPageId;
pub use restore_policy::RestorePolicy;
pub use split_axis::SplitAxis;
pub use split_placement::SplitPlacement;
pub use tab_insertion_anchor::TabInsertionAnchor;
pub use tab_insertion_side::TabInsertionSide;
pub use tab_stack_layout::TabStackLayout;
pub use workbench_layout::WorkbenchLayout;
pub use workspace_target::WorkspaceTarget;
