type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 child-groups production guard owner-path budget child split",
        &[
            "runtime_15_m3_child_groups_production_guard_owner_path_budget_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/core_and_evidence.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/runtime_row_data_guard.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/review_guard.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/module_layout.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/status_docs.rs",
            "PRODUCTION_GUARD_CORE_AND_EVIDENCE_OWNER_PATHS",
            "PRODUCTION_GUARD_RUNTIME_ROW_DATA_GUARD_OWNER_PATHS",
            "PRODUCTION_GUARD_REVIEW_GUARD_OWNER_PATHS",
            "PRODUCTION_GUARD_MODULE_LAYOUT_OWNER_PATHS",
            "PRODUCTION_GUARD_STATUS_DOCS_OWNER_PATHS",
            "scoped rustfmt/static scans passed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups root owner-path inventory child split",
        &[
            "runtime_15_m3_child_groups_root_owner_path_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/m3_child_group_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/core_and_evidence.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/runtime_row_data_guard.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/review_guard.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/module_layout.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/production_guard_row_owner_paths/status_docs.rs",
            "M3_CHILD_GROUP_OWNER_PATH_GROUPS",
            "runtime_15_m3_child_groups_row_data_guard_children_stay_focused",
            "scoped rustfmt/static scans passed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups owner-path budget groups folder-backed split",
        &[
            "runtime_15_m3_child_groups_owner_path_budget_groups_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/m3_child_group_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/m3_child_group_owner_paths/root_guard_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/m3_child_group_owner_paths/owner_path_routes.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/m3_child_group_owner_paths/plan_status_row_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups/root_owner_paths/m3_child_group_owner_paths/folder_backed.rs",
            "M3_CHILD_GROUP_OWNER_PATH_GROUPS",
            "runtime_15_m3_child_group_owner_paths_are_folder_backed",
            "runtime_15_m3_child_groups_row_data_guard_children_stay_focused",
            "scoped rustfmt/static scans passed",
            "Cargo gate deferred",
        ],
    ),
];
