import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const sourcePath = join(projectRoot, 'reference', 'current-head', 'command_catalog.json');
const zrOutput = join(projectRoot, 'scripts', 'woc_game', 'src', 'protocol', 'commands.zr');
const rustOutput = join(
  projectRoot,
  'native',
  'crates',
  'woc_protocol',
  'src',
  'generated_commands.rs',
);
const checkOnly = process.argv.includes('--check');
const SOURCE_COMMIT = '5ef9f7cb21cd8875b6d2c49701015dfcd78de35a';
const EXPECTED_COMMAND_COUNT = 165;

main();

function main() {
  const document = JSON.parse(readFileSync(sourcePath, 'utf8'));
  invariant(document.schema_version === 1, 'command catalog schema must be 1');
  invariant(document.source_commit === SOURCE_COMMIT, 'command catalog source commit drifted');
  invariant(Array.isArray(document.entries), 'command catalog entries must be an array');
  invariant(
    document.entries.length === EXPECTED_COMMAND_COUNT,
    `expected ${EXPECTED_COMMAND_COUNT} commands, found ${document.entries.length}`,
  );

  const names = new Set();
  let dispatchOnly = 0;
  for (const [index, entry] of document.entries.entries()) {
    invariant(entry.index === index, `command index ${index} is not contiguous`);
    invariant(typeof entry.name === 'string' && entry.name.length > 0, `command ${index} has no name`);
    invariant(!names.has(entry.name), `duplicate command name ${entry.name}`);
    names.add(entry.name);
    invariant(
      entry.kind === 'client_send' || entry.kind === 'dispatch_only',
      `command ${entry.name} has invalid kind ${entry.kind}`,
    );
    if (entry.kind === 'dispatch_only') dispatchOnly++;
    invariant(
      entry.woc_owner === 'scripts/woc_game/src/protocol/commands.zr',
      `command ${entry.name} has unexpected WOC owner`,
    );
  }
  invariant(dispatchOnly === 9, `expected 9 dispatch-only commands, found ${dispatchOnly}`);

  const fingerprintSource = document.entries
    .map((entry) => `${entry.index}\0${entry.name}\0${entry.kind}\0${entry.facet ?? ''}\n`)
    .join('');
  const sha256 = createHash('sha256').update(fingerprintSource, 'utf8').digest('hex');
  const fingerprintHex = sha256.slice(0, 15);
  const fingerprint = BigInt(`0x${fingerprintHex}`);
  const outputs = new Map([
    [zrOutput, renderZr(document.entries, fingerprint, fingerprintHex)],
    [rustOutput, renderRust(document.entries, sha256)],
  ]);
  for (const [path, content] of outputs) writeOrCheck(path, content);
  process.stdout.write(
    `${checkOnly ? 'checked' : 'generated'} ${document.entries.length} WOC commands (${fingerprintHex})\n`,
  );
}

function renderZr(entries, fingerprint, fingerprintHex) {
  const first = entries[0];
  const last = entries.at(-1);
  const talentSelection = entries.find((entry) => entry.name === 'selectTalentRow');
  invariant(talentSelection?.index === 163, 'current talent-selection command id drifted');
  const names = entries
    .map((entry) => `    if (id == <uint>${entry.index}) { return ${JSON.stringify(entry.name)}; }`)
    .join('\n');
  const dispatchIds = entries
    .filter((entry) => entry.kind === 'dispatch_only')
    .map((entry) => `id == <uint>${entry.index}`)
    .join(' || ');
  const facets = entries
    .filter((entry) => entry.facet)
    .map((entry) => `    if (id == <uint>${entry.index}) { return ${JSON.stringify(entry.facet)}; }`)
    .join('\n');
  return `// Generated by examples/woc/tools/command_codegen.mjs. Do not edit.\n` +
    `pub fingerprint(): uint {\n    return <uint>${fingerprint};\n}\n\n` +
    `pub fingerprintHex(a: int, b: int, c: int, d: int, e: int, f: int, g: int, h: int): string {\n` +
    `    if (a != 1 || b != 1 || c != 2 || d != 3 || e != 5 || f != 8 || g != 13 || h != 21) {\n` +
    `        throw "WOC command fingerprint marker is invalid";\n    }\n` +
    `    return ${JSON.stringify(fingerprintHex)};\n}\n\n` +
    `pub isKnown(id: uint): bool {\n    return id < <uint>${entries.length};\n}\n\n` +
    `pub name(id: uint, required: bool): string {\n` +
    `    if (!required) { throw "WOC command name is required"; }\n${names}\n` +
    `    throw "WOC command id is out of range";\n}\n\n` +
    `pub kind(id: uint, a: int, b: int): string {\n` +
    `    if (a != 1 || b != 1 || !isKnown(id)) { throw "WOC command kind id is invalid"; }\n` +
    `    return isDispatchOnly(id, 1, 1, 2, 3) ? "dispatch_only" : "client_send";\n}\n\n` +
    `pub facet(id: uint, a: int, b: int, c: int): string {\n` +
    `    if (a != 1 || b != 1 || c != 2 || !isKnown(id)) {\n` +
    `        throw "WOC command facet id is invalid";\n    }\n${facets}\n` +
    `    return "";\n}\n\n` +
    `pub isDispatchOnly(id: uint, a: int, b: int, c: int, d: int): bool {\n` +
    `    if (a != 1 || b != 1 || c != 2 || d != 3 || !isKnown(id)) {\n` +
    `        throw "WOC command transport id is invalid";\n    }\n` +
    `    return ${dispatchIds};\n}\n\n` +
    `pub count(a: int, b: int, c: int, d: int, e: int, f: int): int {\n` +
    `    if (a != 1 || b != 1 || c != 2 || d != 3 || e != 5 || f != 8) {\n` +
    `        throw "WOC command count marker is invalid";\n    }\n` +
    `    return ${entries.length};\n}\n\n` +
    `pub contractTest(a: int, b: int, c: int, d: int, e: int, f: int, g: int): int {\n` +
    `    if (a != 1 || b != 1 || c != 2 || d != 3 || e != 5 || f != 8 || g != 13) {\n` +
    `        return -1;\n    }\n` +
    `    if (count(1, 1, 2, 3, 5, 8) != ${entries.length} ||\n` +
    `        fingerprintHex(1, 1, 2, 3, 5, 8, 13, 21) != ${JSON.stringify(fingerprintHex)} ||\n` +
    `        name(<uint>0, true) != ${JSON.stringify(first.name)} ||\n` +
    `        name(<uint>${last.index}, true) != ${JSON.stringify(last.name)} ||\n` +
    `        name(<uint>${talentSelection.index}, true) != "selectTalentRow" ||\n` +
    `        isKnown(<uint>${entries.length}) || facet(<uint>42, 1, 1, 2) != "IWorldParty") {\n` +
    `        return -2;\n    }\n` +
    `    var dispatchCount = 0;\n    var id: uint = <uint>0;\n` +
    `    while (id < <uint>${entries.length}) {\n` +
    `        if (name(id, true).length <= 0 || kind(id, 1, 1).length <= 0) { return -3; }\n` +
    `        if (isDispatchOnly(id, 1, 1, 2, 3)) { dispatchCount = dispatchCount + 1; }\n` +
    `        id = id + <uint>1;\n    }\n` +
    `    return dispatchCount == 9 ? 1 : -4;\n}\n`;
}

function renderRust(entries, sha256) {
  const rows = entries.map((entry) => {
    const kind = entry.kind === 'dispatch_only' ? 'CommandKind::DispatchOnly' : 'CommandKind::ClientSend';
    const facet = entry.facet ? `Some(${JSON.stringify(entry.facet)})` : 'None';
    return `    CommandDescriptor {\n` +
      `        id: ${entry.index},\n` +
      `        name: ${JSON.stringify(entry.name)},\n` +
      `        kind: ${kind},\n` +
      `        facet: ${facet},\n` +
      `    },`;
  });
  return `// Generated by examples/woc/tools/command_codegen.mjs. Do not edit.\n` +
    `pub const COMMAND_CATALOG_SHA256: &str =\n    ${JSON.stringify(sha256)};\n\n` +
    `#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n` +
    `pub enum CommandKind {\n    ClientSend,\n    DispatchOnly,\n}\n\n` +
    `#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n` +
    `pub struct CommandDescriptor {\n` +
    `    pub id: u16,\n    pub name: &'static str,\n    pub kind: CommandKind,\n` +
    `    pub facet: Option<&'static str>,\n}\n\n` +
    `pub const COMMAND_CATALOG: &[CommandDescriptor] = &[\n${rows.join('\n')}\n];\n\n` +
    `pub fn command_descriptor(id: u16) -> Option<&'static CommandDescriptor> {\n` +
    `    COMMAND_CATALOG.get(usize::from(id))\n}\n`;
}

function writeOrCheck(path, content) {
  if (checkOnly) {
    invariant(existsSync(path), `${path} is missing; run npm run generate`);
    invariant(readFileSync(path, 'utf8') === content, `${path} is stale; run npm run generate`);
    return;
  }
  writeFileSync(path, content, 'utf8');
}

function invariant(condition, message) {
  if (!condition) throw new Error(message);
}
