import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SOURCE_COMMIT = '5ef9f7cb21cd8875b6d2c49701015dfcd78de35a';
const EXPECTED_MOB_COUNT = 47;
const EXPECTED_FIRST_ID = 'forest_wolf';
const EXPECTED_DUMMY_INDEX = 26;
const EXPECTED_LAST_ID = 'grix_the_tunnelking';
const NUMERIC_FIELDS = [
  'min_level', 'max_level', 'hp_base', 'hp_per_level', 'dmg_base',
  'dmg_per_level', 'attack_speed', 'armor_per_level', 'move_speed',
  'aggro_radius', 'scale', 'color', 'respawn_seconds', 'respawn_mult',
];
const FLAG_FIELDS = [
  'elite', 'boss', 'rare', 'dummy', 'can_swim', 'has_respawn_seconds', 'has_respawn_mult',
];
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const sourceRoot = resolve(projectRoot, '..', '..', 'dev', 'world-of-claudecraft');
const sourceManifestPath = join(projectRoot, 'reference', 'current-head', 'source_manifest.json');
const extractorPath = join(scriptDirectory, 'm3_camp_mob_core_source_extract.mjs');
const loaderUrl = pathToFileURL(join(scriptDirectory, 'typescript_git_loader.mjs')).href;
const contractPath = join(projectRoot, 'contracts', 'm3_camp_mob_core.json');
const zrPath = join(projectRoot, 'scripts', 'woc_game', 'src', 'generated', 'm3_camp_mob_core.zr');
const checkOnly = process.argv.includes('--check');

main();

function main() {
  execFileSync('git', ['-C', sourceRoot, 'cat-file', '-e', `${SOURCE_COMMIT}^{commit}`]);
  const manifest = JSON.parse(readFileSync(sourceManifestPath, 'utf8'));
  assert(manifest.source_commit === SOURCE_COMMIT, 'WOC source manifest commit drifted');
  const extracted = extractContent();
  assert(extracted.mobs.length === EXPECTED_MOB_COUNT, 'camp mob template count drifted');
  assert(
    extracted.mobs[0].id === EXPECTED_FIRST_ID &&
      extracted.mobs[EXPECTED_DUMMY_INDEX].id === 'training_dummy' &&
      extracted.mobs[EXPECTED_DUMMY_INDEX].dummy &&
      extracted.mobs.at(-1).id === EXPECTED_LAST_ID,
    'camp mob template identity or source order drifted',
  );
  assert(
    extracted.mobs.every((mob) =>
      typeof mob.id === 'string' && mob.id.length > 0 &&
      typeof mob.name === 'string' && mob.name.length > 0 &&
      typeof mob.family === 'string' && mob.family.length > 0 &&
      Number.isInteger(mob.min_level) && Number.isInteger(mob.max_level) &&
      mob.min_level >= 1 && mob.max_level >= mob.min_level &&
      NUMERIC_FIELDS.every((field) => Number.isFinite(mob[field])) &&
      FLAG_FIELDS.every((field) => typeof mob[field] === 'boolean'),
    ),
    'camp mob core field is missing or invalid',
  );

  const dataText = gitShow('src/sim/data.ts');
  const zone1Text = gitShow('src/sim/content/zone1.ts');
  const zone2Text = gitShow('src/sim/content/zone2.ts');
  const zone3Text = gitShow('src/sim/content/zone3.ts');
  assert(
    dataText.includes('export const MOBS: Record<string, MobTemplate> = {') &&
      zone3Text.includes("training_dummy: {") && zone3Text.includes('dummy: true,'),
    'camp mob source structure drifted',
  );

  const catalog = {
    schema_version: 1,
    source_commit: SOURCE_COMMIT,
    generated_by: 'examples/woc/tools/m3_camp_mob_core_codegen.mjs',
    source_sha256: {
      'src/sim/data.ts': sha256(dataText),
      'src/sim/content/zone1.ts': sha256(zone1Text),
      'src/sim/content/zone2.ts': sha256(zone2Text),
      'src/sim/content/zone3.ts': sha256(zone3Text),
    },
    mobs: extracted.mobs,
  };
  catalog.catalog_sha256 = sha256(JSON.stringify({ mobs: catalog.mobs }));
  verifyOrWrite(contractPath, `${JSON.stringify(catalog, null, 2)}\n`);
  verifyOrWrite(zrPath, renderZr(catalog));
}

function extractContent() {
  const child = spawnSync(process.execPath, [
    '--no-warnings', '--experimental-loader', loaderUrl, extractorPath,
  ], {
    encoding: 'utf8', maxBuffer: 16 * 1024 * 1024,
    env: { ...process.env, WOC_GIT_ROOT: sourceRoot, WOC_GIT_COMMIT: SOURCE_COMMIT },
  });
  assert(child.status === 0, child.stderr || `camp mob core extractor exited ${child.status}`);
  return JSON.parse(child.stdout);
}

function gitShow(sourcePath) {
  return execFileSync('git', ['-C', sourceRoot, 'show', `${SOURCE_COMMIT}:${sourcePath}`], {
    encoding: 'utf8', maxBuffer: 16 * 1024 * 1024,
  });
}

function renderZr(catalog) {
  const { mobs } = catalog;
  const lines = [
    '// Generated by tools/m3_camp_mob_core_codegen.mjs from pinned WOC source.',
    '// Core spawn/derived-stat fields only; combat effects and loot retain their own source contracts.',
    '',
    'mobIndexIsValid(index: int): bool {',
    `    return index >= 0 && index < ${mobs.length};`,
    '}',
    '',
    'pub mobCount(required: bool): int {',
    '    if (!required) {',
    '        throw "woc camp mob count is required";',
    '    }',
    `    return ${mobs.length};`,
    '}',
    '',
    renderIndexOf(mobs), '',
    renderText(mobs), '',
    renderMetric(mobs), '',
    renderFlag(mobs), '',
    renderContractTest(mobs), '',
  ];
  return lines.join('\n');
}

function renderIndexOf(mobs) {
  const lines = [
    'pub indexOf(id: string, required: bool): int {',
    '    if (!required) {',
    '        throw "woc camp mob id is invalid";',
    '    }',
  ];
  for (let index = 0; index < mobs.length; index++) {
    lines.push(`    if (id == ${JSON.stringify(mobs[index].id)}) { return ${index}; }`);
  }
  lines.push('    return -1;', '}');
  return lines.join('\n');
}

function renderText(mobs) {
  const lines = [
    'pub text(index: int, field: string, required: bool): string {',
    '    if (!required || !mobIndexIsValid(index)) {',
    '        throw "woc camp mob text query is invalid";',
    '    }',
  ];
  for (let index = 0; index < mobs.length; index++) {
    const mob = mobs[index];
    lines.push(`    if (index == ${index}) {`);
    lines.push(`        if (field == "id") { return ${JSON.stringify(mob.id)}; }`);
    lines.push(`        if (field == "name") { return ${JSON.stringify(mob.name)}; }`);
    lines.push(`        if (field == "family") { return ${JSON.stringify(mob.family)}; }`);
    lines.push('        return "";', '    }');
  }
  lines.push('    throw "woc camp mob text query is invalid";', '}');
  return lines.join('\n');
}

function renderMetric(mobs) {
  const lines = [
    'pub metric(index: int, field: string, required: bool): float {',
    '    if (!required || !mobIndexIsValid(index)) {',
    '        throw "woc camp mob metric query is invalid";',
    '    }',
  ];
  for (let index = 0; index < mobs.length; index++) {
    lines.push(`    if (index == ${index}) {`);
    for (const field of NUMERIC_FIELDS) {
      lines.push(`        if (field == ${JSON.stringify(field)}) { return ${formatNumber(mobs[index][field])}; }`);
    }
    lines.push('        return 0.0;', '    }');
  }
  lines.push('    throw "woc camp mob metric query is invalid";', '}');
  return lines.join('\n');
}

function renderFlag(mobs) {
  const lines = [
    'pub flag(index: int, field: string, required: bool): bool {',
    '    if (!required || !mobIndexIsValid(index)) {',
    '        throw "woc camp mob flag query is invalid";',
    '    }',
  ];
  for (let index = 0; index < mobs.length; index++) {
    lines.push(`    if (index == ${index}) {`);
    for (const field of FLAG_FIELDS) {
      lines.push(`        if (field == ${JSON.stringify(field)}) { return ${mobs[index][field] ? 'true' : 'false'}; }`);
    }
    lines.push('        return false;', '    }');
  }
  lines.push('    throw "woc camp mob flag query is invalid";', '}');
  return lines.join('\n');
}

function renderContractTest(mobs) {
  const lines = [
    'pub contractTest(): int {',
    `    if (mobCount(true) != ${mobs.length}) { return -1; }`,
  ];
  for (let index = 0; index < mobs.length; index++) {
    const mob = mobs[index];
    lines.push(`    if (indexOf(${JSON.stringify(mob.id)}, true) != ${index} || text(${index}, "id", true) != ${JSON.stringify(mob.id)} ||`);
    lines.push(`        text(${index}, "name", true) != ${JSON.stringify(mob.name)} || text(${index}, "family", true) != ${JSON.stringify(mob.family)} ||`);
    for (let fieldIndex = 0; fieldIndex < NUMERIC_FIELDS.length; fieldIndex++) {
      const field = NUMERIC_FIELDS[fieldIndex];
      const suffix = fieldIndex + 1 < NUMERIC_FIELDS.length ? ' ||' : ' ||';
      lines.push(`        metric(${index}, ${JSON.stringify(field)}, true) != ${formatNumber(mob[field])}${suffix}`);
    }
    for (let fieldIndex = 0; fieldIndex < FLAG_FIELDS.length; fieldIndex++) {
      const field = FLAG_FIELDS[fieldIndex];
      const suffix = fieldIndex + 1 < FLAG_FIELDS.length ? ' ||' : ') {';
      lines.push(`        flag(${index}, ${JSON.stringify(field)}, true) != ${mob[field] ? 'true' : 'false'}${suffix}`);
    }
    lines.push(`        return -${index + 2};`, '    }');
  }
  lines.push('    return 1;', '}');
  return lines.join('\n');
}

function verifyOrWrite(path, text) {
  if (checkOnly) {
    assert(existsSync(path), `generated output is missing: ${path}`);
    assert(readFileSync(path, 'utf8') === text, `generated output drifted: ${path}`);
    return;
  }
  writeFileSync(path, text);
}

function formatNumber(value) {
  assert(Number.isFinite(value), `cannot emit non-finite number ${value}`);
  return Number.isInteger(value) ? `${value}.0` : value.toString();
}

function sha256(text) {
  return createHash('sha256').update(text).digest('hex');
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}
