import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SOURCE_COMMIT = '5ef9f7cb21cd8875b6d2c49701015dfcd78de35a';
const EXPECTED = {
  total: 35,
  static: 31,
  dynamic: 4,
  questEntries: 87,
  vendorItemEntries: 107,
  marketIds: ['the_merchant', 'auctioneer_voss'],
  bankerIds: ['bursar_fernando', 'bursar_petra_vell', 'bursar_aldous_crane'],
  heroicVendorIds: ['heroic_quartermaster'],
  cardMasterIds: ['card_master'],
  firstId: 'the_merchant',
  lastId: 'spirit_healer',
};

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const sourceRoot = resolve(projectRoot, '..', '..', 'dev', 'world-of-claudecraft');
const sourceManifestPath = join(projectRoot, 'reference', 'current-head', 'source_manifest.json');
const extractorPath = join(scriptDirectory, 'm3_npc_initialization_source_extract.mjs');
const loaderUrl = pathToFileURL(join(scriptDirectory, 'typescript_git_loader.mjs')).href;
const contractPath = join(projectRoot, 'contracts', 'm3_npc_initialization.json');
const zrPath = join(projectRoot, 'scripts', 'woc_game', 'src', 'generated', 'm3_npc_initialization.zr');
const checkOnly = process.argv.includes('--check');

main();

function main() {
  execFileSync('git', ['-C', sourceRoot, 'cat-file', '-e', `${SOURCE_COMMIT}^{commit}`]);
  const manifest = JSON.parse(readFileSync(sourceManifestPath, 'utf8'));
  assert(manifest.source_commit === SOURCE_COMMIT, 'WOC source manifest commit drifted');
  const extracted = extract();
  const entries = extracted.entries;
  assert(entries.length === EXPECTED.total, 'NPC initialization count drifted');
  assert(entries.filter((entry) => !entry.dynamic).length === EXPECTED.static, 'static NPC count drifted');
  assert(entries.filter((entry) => entry.dynamic).length === EXPECTED.dynamic, 'dynamic NPC count drifted');
  assert(entries.reduce((total, entry) => total + entry.quest_ids.length, 0) === EXPECTED.questEntries,
    'NPC quest-list cardinality drifted');
  assert(entries.reduce((total, entry) => total + entry.vendor_items.length, 0) === EXPECTED.vendorItemEntries,
    'NPC vendor-list cardinality drifted');
  assert(idsWith(entries, 'market') === JSON.stringify(EXPECTED.marketIds), 'market NPC identity/order drifted');
  assert(idsWith(entries, 'banker') === JSON.stringify(EXPECTED.bankerIds), 'banker NPC identity/order drifted');
  assert(idsWith(entries, 'heroic_vendor') === JSON.stringify(EXPECTED.heroicVendorIds),
    'heroic vendor NPC identity/order drifted');
  assert(idsWith(entries, 'card_master') === JSON.stringify(EXPECTED.cardMasterIds),
    'card master NPC identity/order drifted');
  assert(entries[0].id === EXPECTED.firstId && entries.at(-1).id === EXPECTED.lastId,
    'NPC initialization source order drifted');
  const document = {
    schema_version: 1,
    source_commit: SOURCE_COMMIT,
    generated_by: 'examples/woc/tools/m3_npc_initialization_codegen.mjs',
    source_identity: gitBlobIdentity('src/sim/data.ts'),
    npcs: entries,
  };
  document.catalog_sha256 = sha256(JSON.stringify({
    source_identity: document.source_identity,
    npcs: document.npcs,
  }));
  const contract = `${JSON.stringify(document, null, 2)}\n`;
  const zr = render(document);
  writeOrCheck(contractPath, contract, 'm3_npc_initialization.json');
  writeOrCheck(zrPath, zr, 'm3_npc_initialization.zr');
  process.stdout.write(`${checkOnly ? 'checked' : 'generated'} ${entries.length} NPC initialization records ` +
    `(${document.catalog_sha256.slice(0, 15)})\n`);
}

function extract() {
  const child = spawnSync(process.execPath, [
    '--no-warnings', '--experimental-loader', loaderUrl, extractorPath,
  ], {
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
    env: { ...process.env, WOC_GIT_ROOT: sourceRoot, WOC_GIT_COMMIT: SOURCE_COMMIT },
  });
  assert(child.status === 0, child.stderr || `NPC initialization extractor exited ${child.status}`);
  return JSON.parse(child.stdout);
}

function render(document) {
  const entries = document.npcs;
  const lines = [
    '// Generated by examples/woc/tools/m3_npc_initialization_codegen.mjs.',
    `// Source ${document.source_commit}; NPC initialization fields; do not edit.`,
    '',
    'npcIndexIsValid(index: int): bool {',
    `    return index >= 0 && index < ${entries.length};`,
    '}',
    '',
    'pub catalogSha(required: bool): string {',
    '    if (!required) { throw "woc NPC initialization catalog is required"; }',
    `    return ${zrString(document.catalog_sha256)};`,
    '}',
    '',
    'pub npcCount(required: bool): int {',
    '    if (!required) { throw "woc NPC initialization count is required"; }',
    `    return ${entries.length};`,
    '}',
    '',
    'pub npcId(index: int, required: bool): string {',
    '    if (!required || !npcIndexIsValid(index)) { throw "woc NPC initialization index is invalid"; }',
  ];
  appendIndexStringCases(lines, entries, (entry) => entry.id);
  lines.push('    throw "woc NPC initialization index is invalid";', '}', '',
    'pub npcIsDynamic(index: int, required: bool): bool {',
    '    if (!required || !npcIndexIsValid(index)) { throw "woc NPC dynamic index is invalid"; }');
  appendIndexValueCases(lines, entries, (entry) => entry.dynamic ? 'true' : 'false');
  lines.push('    throw "woc NPC dynamic index is invalid";', '}', '',
    'pub rawCoordinate(index: int, axis: int, required: bool): float {',
    '    if (!required || !npcIndexIsValid(index) || (axis != 1 && axis != 2)) {',
    '        throw "woc NPC coordinate is invalid";',
    '    }');
  appendIndexValueCases(lines, entries, (entry) => `axis == 1 ? ${zrNumber(entry.x)} : ${zrNumber(entry.z)}`);
  lines.push('    throw "woc NPC coordinate is invalid";', '}', '',
    'pub facing(index: int, required: bool): float {',
    '    if (!required || !npcIndexIsValid(index)) { throw "woc NPC facing index is invalid"; }');
  appendIndexValueCases(lines, entries, (entry) => zrNumber(entry.facing));
  lines.push('    throw "woc NPC facing index is invalid";', '}', '',
    'pub color(index: int, required: bool): int {',
    '    if (!required || !npcIndexIsValid(index)) { throw "woc NPC color index is invalid"; }');
  appendIndexValueCases(lines, entries, (entry) => String(entry.color));
  lines.push('    throw "woc NPC color index is invalid";', '}', '');
  appendStringFields(lines, entries);
  appendFlagFields(lines, entries);
  appendListField(lines, entries, 'quest', 'quest_ids');
  appendListField(lines, entries, 'vendorItem', 'vendor_items');
  lines.push('pub contractTest(): int {',
    `    if (npcCount(true) != ${entries.length} || npcId(0, true) != ${zrString(entries[0].id)} ||`,
    `        npcId(${entries.length - 1}, true) != ${zrString(entries.at(-1).id)} ||`,
    '        npcStringField(0, "name", true) != "The Merchant" ||',
    '        !npcFlag(0, "market", true) || !npcFlag(8, "banker", true) ||',
    '        !npcFlag(9, "cardMaster", true) || !npcIsDynamic(31, true)) {',
    '        return -1;',
    '    }',
    '    return 1;',
    '}',
  );
  return `${lines.join('\n')}\n`;
}

function appendIndexStringCases(lines, entries, value) {
  appendIndexValueCases(lines, entries, (entry) => zrString(value(entry)));
}

function appendIndexValueCases(lines, entries, value) {
  entries.forEach((entry, index) => lines.push(`    if (index == ${index}) { return ${value(entry)}; }`));
}

function appendStringFields(lines, entries) {
  lines.push(`pub npcStringField(index: int, field: string, required: bool): string {`);
  lines.push('    if (!required || !npcIndexIsValid(index)) { throw "woc NPC string field is invalid"; }');
  for (const name of ['name', 'title', 'greeting']) {
    lines.push(`    if (field == ${zrString(name)}) {`);
    appendIndexStringCases(lines, entries, (entry) => entry[name]);
    lines.push('    }');
  }
  lines.push('    throw "woc NPC string field is invalid";', '}', '');
}

function appendFlagFields(lines, entries) {
  lines.push(`pub npcFlag(index: int, field: string, required: bool): bool {`);
  lines.push('    if (!required || !npcIndexIsValid(index)) { throw "woc NPC flag is invalid"; }');
  for (const [name, key] of [
    ['devVendor', 'dev_vendor'], ['market', 'market'], ['banker', 'banker'],
    ['heroicVendor', 'heroic_vendor'], ['cardMaster', 'card_master'],
  ]) {
    lines.push(`    if (field == ${zrString(name)}) {`);
    appendIndexValueCases(lines, entries, (entry) => entry[key] ? 'true' : 'false');
    lines.push('    }');
  }
  lines.push('    throw "woc NPC flag is invalid";', '}', '');
}

function appendListField(lines, entries, publicName, sourceName) {
  lines.push(`pub ${publicName}Count(index: int, required: bool): int {`);
  lines.push('    if (!required || !npcIndexIsValid(index)) { throw "woc NPC list count is invalid"; }');
  appendIndexValueCases(lines, entries, (entry) => String(entry[sourceName].length));
  lines.push('    throw "woc NPC list count is invalid";', '}', '',
    `pub ${publicName}Id(index: int, valueIndex: int, required: bool): string {`,
    `    if (!required || !npcIndexIsValid(index) || valueIndex < 0 || valueIndex >= ${publicName}Count(index, true)) {`,
    '        throw "woc NPC list value is invalid";',
    '    }');
  entries.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) {`);
    entry[sourceName].forEach((value, valueIndex) => lines.push(
      `        if (valueIndex == ${valueIndex}) { return ${zrString(value)}; }`,
    ));
    lines.push('        throw "woc NPC list value is invalid";', '    }');
  });
  lines.push('    throw "woc NPC list value is invalid";', '}', '');
}

function idsWith(entries, field) {
  return JSON.stringify(entries.filter((entry) => entry[field]).map((entry) => entry.id));
}

function gitBlobIdentity(sourcePath) {
  const sourceText = execFileSync('git', ['-C', sourceRoot, 'show', `${SOURCE_COMMIT}:${sourcePath}`], {
    encoding: 'utf8',
  });
  const blob = execFileSync('git', ['-C', sourceRoot, 'rev-parse', `${SOURCE_COMMIT}:${sourcePath}`], {
    encoding: 'utf8',
  }).trim();
  return { source_path: sourcePath, git_blob: blob, sha256: sha256Text(sourceText) };
}

function writeOrCheck(path, content, name) {
  if (checkOnly) {
    assert(existsSync(path), `${name} is missing; run the NPC initialization generator`);
    assert(readFileSync(path, 'utf8') === content, `${name} is stale; run the NPC initialization generator`);
    return;
  }
  writeFileSync(path, content, 'utf8');
}

function zrString(value) { return JSON.stringify(value); }
function zrNumber(value) {
  assert(Number.isFinite(value), 'NPC initialization contains a non-finite number');
  return String(value);
}
function sha256(value) { return sha256Text(value); }
function sha256Text(value) { return createHash('sha256').update(value).digest('hex'); }
function assert(condition, message) { if (!condition) throw new Error(message); }
