import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SOURCE_COMMIT = '5ef9f7cb21cd8875b6d2c49701015dfcd78de35a';
const EXPECTED = {
  healer: { id: 'spirit_healer', name: 'The Pale Keeper', facing: Math.PI, color: 0xfff4d0 },
  graveyards: [
    { id: 'gy_eastbrook', name: 'Eastbrook Rest', x: -14, z: -14 },
    { id: 'gy_vale_chapel', name: 'Vale Chapel Yard', x: 4, z: -56 },
    { id: 'gy_fenbridge', name: 'Fenbridge Barrow', x: -18, z: 286 },
    { id: 'gy_thornpeak', name: 'Thornpeak Cairns', x: 15, z: 645 },
    { id: 'gy_thornpeak_east', name: 'East Ridge Graves', x: 141, z: 712 },
    { id: 'gy_thornpeak_south', name: 'Sanctum Approach Graves', x: 138, z: 838 },
    { id: 'gy_thornpeak_west', name: 'West Spire Graves', x: -139, z: 787 },
  ],
};

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const sourceRoot = resolve(projectRoot, '..', '..', 'dev', 'world-of-claudecraft');
const sourceManifestPath = join(projectRoot, 'reference', 'current-head', 'source_manifest.json');
const extractorPath = join(scriptDirectory, 'm3_spirit_healer_placement_source_extract.mjs');
const loaderUrl = pathToFileURL(join(scriptDirectory, 'typescript_git_loader.mjs')).href;
const contractPath = join(projectRoot, 'contracts', 'm3_spirit_healer_placement.json');
const zrPath = join(projectRoot, 'scripts', 'woc_game', 'src', 'generated', 'm3_spirit_healer_placement.zr');
const checkOnly = process.argv.includes('--check');

main();

function main() {
  execFileSync('git', ['-C', sourceRoot, 'cat-file', '-e', `${SOURCE_COMMIT}^{commit}`]);
  const manifest = JSON.parse(readFileSync(sourceManifestPath, 'utf8'));
  assert(manifest.source_commit === SOURCE_COMMIT, 'WOC source manifest commit drifted');
  const extracted = extract();
  assert(JSON.stringify(extracted.healer) === JSON.stringify(EXPECTED.healer), 'spirit healer definition drifted');
  assert(JSON.stringify(extracted.graveyards) === JSON.stringify(EXPECTED.graveyards),
    'overworld graveyard identity or order drifted');
  const document = {
    schema_version: 1,
    source_commit: SOURCE_COMMIT,
    generated_by: 'examples/woc/tools/m3_spirit_healer_placement_codegen.mjs',
    source_identity: gitBlobIdentity('src/sim/content/graveyards.ts'),
    healer: extracted.healer,
    graveyards: extracted.graveyards,
  };
  document.catalog_sha256 = sha256(JSON.stringify({
    source_identity: document.source_identity,
    healer: document.healer,
    graveyards: document.graveyards,
  }));
  const contract = `${JSON.stringify(document, null, 2)}\n`;
  const zr = render(document);
  writeOrCheck(contractPath, contract, 'm3_spirit_healer_placement.json');
  writeOrCheck(zrPath, zr, 'm3_spirit_healer_placement.zr');
  process.stdout.write(`${checkOnly ? 'checked' : 'generated'} ${document.graveyards.length} spirit-healer placements ` +
    `(${document.catalog_sha256.slice(0, 15)})\n`);
}

function extract() {
  const child = spawnSync(process.execPath, [
    '--no-warnings', '--experimental-loader', loaderUrl, extractorPath,
  ], {
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
    env: { ...process.env, WOC_GIT_ROOT: sourceRoot, WOC_GIT_COMMIT: SOURCE_COMMIT },
  });
  assert(child.status === 0, child.stderr || `spirit-healer extractor exited ${child.status}`);
  return JSON.parse(child.stdout);
}

function render(document) {
  const entries = document.graveyards;
  const lines = [
    '// Generated by examples/woc/tools/m3_spirit_healer_placement_codegen.mjs.',
    `// Source ${document.source_commit}; overworld graveyard order; do not edit.`,
    '',
    'graveyardIndexIsValid(index: int): bool {',
    `    return index >= 0 && index < ${entries.length};`,
    '}',
    '',
    'pub catalogSha(required: bool): string {',
    '    if (!required) { throw "woc spirit healer placement catalog is required"; }',
    `    return ${zrString(document.catalog_sha256)};`,
    '}',
    '',
    'pub graveyardCount(required: bool): int {',
    '    if (!required) { throw "woc spirit healer graveyard count is required"; }',
    `    return ${entries.length};`,
    '}',
    '',
    'pub healerId(required: bool): string {',
    '    if (!required) { throw "woc spirit healer id is required"; }',
    `    return ${zrString(document.healer.id)};`,
    '}',
    '',
    'pub healerName(required: bool): string {',
    '    if (!required) { throw "woc spirit healer name is required"; }',
    `    return ${zrString(document.healer.name)};`,
    '}',
    '',
    'pub healerFacing(required: bool): float {',
    '    if (!required) { throw "woc spirit healer facing is required"; }',
    `    return ${zrNumber(document.healer.facing)};`,
    '}',
    '',
    'pub healerColor(required: bool): int {',
    '    if (!required) { throw "woc spirit healer color is required"; }',
    `    return ${document.healer.color};`,
    '}',
    '',
  ];
  appendString(lines, entries, 'graveyardId', 'id');
  appendString(lines, entries, 'graveyardName', 'name');
  lines.push('pub rawCoordinate(index: int, axis: int, required: bool): float {',
    '    if (!required || !graveyardIndexIsValid(index) || (axis != 1 && axis != 2)) {',
    '        throw "woc spirit healer coordinate is invalid";',
    '    }');
  entries.forEach((entry, index) => lines.push(
    `    if (index == ${index}) { return axis == 1 ? ${zrNumber(entry.x)} : ${zrNumber(entry.z)}; }`,
  ));
  lines.push('    throw "woc spirit healer coordinate is invalid";', '}', '', 'pub contractTest(): int {',
    `    if (graveyardCount(true) != ${entries.length} || healerId(true) != ${zrString(document.healer.id)} ||`,
    `        healerName(true) != ${zrString(document.healer.name)} || healerFacing(true) != ${zrNumber(document.healer.facing)} ||`,
    `        graveyardId(0, true) != ${zrString(entries[0].id)} || graveyardId(${entries.length - 1}, true) != ${zrString(entries.at(-1).id)} ||`,
    `        rawCoordinate(3, 1, true) != ${zrNumber(entries[3].x)} || rawCoordinate(3, 2, true) != ${zrNumber(entries[3].z)}) {`,
    '        return -1;',
    '    }',
    '    return 1;',
    '}',
  );
  return `${lines.join('\n')}\n`;
}

function appendString(lines, entries, functionName, field) {
  lines.push(`pub ${functionName}(index: int, required: bool): string {`,
    '    if (!required || !graveyardIndexIsValid(index)) { throw "woc spirit healer graveyard index is invalid"; }');
  entries.forEach((entry, index) => lines.push(`    if (index == ${index}) { return ${zrString(entry[field])}; }`));
  lines.push('    throw "woc spirit healer graveyard index is invalid";', '}', '');
}

function gitBlobIdentity(sourcePath) {
  const sourceText = execFileSync('git', ['-C', sourceRoot, 'show', `${SOURCE_COMMIT}:${sourcePath}`], {
    encoding: 'utf8',
  });
  const blob = execFileSync('git', ['-C', sourceRoot, 'rev-parse', `${SOURCE_COMMIT}:${sourcePath}`], {
    encoding: 'utf8',
  }).trim();
  return { source_path: sourcePath, git_blob: blob, sha256: sha256Text(sourceText) };
}

function writeOrCheck(path, content, name) {
  if (checkOnly) {
    assert(existsSync(path), `${name} is missing; run the spirit-healer placement generator`);
    assert(readFileSync(path, 'utf8') === content, `${name} is stale; run the spirit-healer placement generator`);
    return;
  }
  writeFileSync(path, content, 'utf8');
}

function zrString(value) { return JSON.stringify(value); }
function zrNumber(value) {
  assert(Number.isFinite(value), 'spirit-healer placement contains a non-finite number');
  return String(value);
}
function sha256(value) { return sha256Text(value); }
function sha256Text(value) { return createHash('sha256').update(value).digest('hex'); }
function assert(condition, message) { if (!condition) throw new Error(message); }
