import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const inputPath = join(projectRoot, 'contracts', 'm5_content.json');
const outputPath = join(
  projectRoot,
  'scripts',
  'woc_game',
  'src',
  'generated',
  'm5_content_catalog.zr',
);
const checkOnly = process.argv.includes('--check');

const CATEGORIES = [
  ['item', 'items'],
  ['quest', 'quests'],
  ['mob', 'mobs'],
  ['npc', 'npcs'],
  ['talent_option', 'talent_options'],
  ['ability', 'abilities'],
  ['spec', 'specs'],
];

main();

function main() {
  const document = JSON.parse(readFileSync(inputPath, 'utf8'));
  invariant(document.schema_version === 6, 'unsupported M5 content schema');
  const fingerprint = hashText(JSON.stringify({
    scenarios: document.scenarios,
    market_cut: document.market_cut,
    heroic_vendor: document.heroic_vendor,
    delve_shops: document.delve_shops,
    mech_chromas: document.mech_chromas,
    constants: document.constants,
    specs: document.specs,
    items: document.items,
    quests: document.quests,
    mobs: document.mobs,
    npcs: document.npcs,
    talent_options: document.talent_options,
    abilities: document.abilities,
  }));
  invariant(document.catalog_sha256 === fingerprint, 'M5 content catalog fingerprint drifted');
  validate(document);
  writeOrCheck(outputPath, render(document));
  process.stdout.write(
    `${checkOnly ? 'checked' : 'generated'} WOC M5 Zr content projection ` +
      `(${document.catalog_sha256.slice(0, 15)})\n`,
  );
}

function validate(document) {
  const expectedCounts = {
    items: 82,
    quests: 2,
    mobs: 1,
    npcs: 6,
    talent_options: 3,
    abilities: 3,
    specs: 2,
  };
  for (const [, field] of CATEGORIES) {
    invariant(document[field].length === expectedCounts[field], `M5 ${field} count drifted`);
    const ids = new Set();
    for (const entry of document[field]) {
      invariant(typeof entry.id === 'string' && entry.id.length > 0, `M5 ${field} id missing`);
      invariant(!ids.has(entry.id), `duplicate M5 ${field} id ${entry.id}`);
      invariant(entry.definition.id === entry.id, `M5 ${field} definition drifted at ${entry.id}`);
      ids.add(entry.id);
    }
  }
  invariant(document.constants.xp_for_level.length === document.constants.max_level,
    'M5 XP table length drifted');
  invariant(document.constants.bank_expansion_prices.length === 12,
    'M5 bank expansion table length drifted');
  invariant(document.heroic_vendor?.npc_id === 'heroic_quartermaster',
    'M5 heroic vendor NPC drifted');
  invariant(document.heroic_vendor?.currency_item_id === 'heroic_mark',
    'M5 heroic vendor currency drifted');
  invariant(document.heroic_vendor?.stock?.length === 10,
    'M5 heroic vendor stock drifted');
  invariant(document.delve_shops?.length === 2 &&
    document.delve_shops.every((shop) => shop.stock?.length === 9) &&
    document.delve_shops[0].auto_companion_id === 'companion_tessa' &&
    document.delve_shops[1].auto_companion_id === 'companion_edda',
  'M5 Delve shop stock drifted');
  invariant(document.mech_chromas?.length === 15 &&
    document.mech_chromas[0].id === 'amber_crimson' &&
    document.mech_chromas[14].id === 'vanguard_chrome',
  'M5 mech chroma order drifted');
  document.mech_chromas.forEach((chroma, index) => {
    invariant(chroma.skin_index === index, `M5 mech chroma skin index drifted at ${chroma.id}`);
    const item = document.items.find((entry) => entry.id === chroma.item_id);
    invariant(item, `M5 mech chroma item is missing: ${chroma.item_id}`);
    invariant(item.definition.use?.type === 'mechChroma' &&
      item.definition.use.chromaId === chroma.id,
    `M5 mech chroma item use drifted: ${chroma.item_id}`);
  });
}

function render(document) {
  const lines = [
    '// Generated by examples/woc/tools/m5_content_zr_codegen.mjs.',
    `// Source ${document.source_commit}; scalar M5 content projection; do not edit.`,
    '',
    'pub catalogSha(): string {',
    `    return ${zrString(document.catalog_sha256)};`,
    '}',
    '',
    'pub count(kind: string): int {',
  ];
  for (const [kind, field] of CATEGORIES) {
    lines.push(`    if (kind == ${zrString(kind)}) { return ${document[field].length}; }`);
  }
  lines.push('    throw "unknown WOC M5 content kind";', '}', '',
    'pub indexOf(kind: string, id: string): int {');
  for (const [kind, field] of CATEGORIES) {
    lines.push(`    if (kind == ${zrString(kind)}) {`);
    document[field].forEach((entry, index) => {
      lines.push(`        if (id == ${zrString(entry.id)}) { return ${index}; }`);
    });
    lines.push('        return -1;', '    }');
  }
  lines.push('    throw "unknown WOC M5 content kind";', '}', '');
  lines.push(...renderItemIdBytes(document), '');
  renderValueFunction(lines, document, 'text', textValues, 'string', '""');
  lines.push('');
  renderValueFunction(lines, document, 'metric', metricValues, 'float', '0.0');
  lines.push('');
  renderValueFunction(lines, document, 'flag', flagValues, 'bool', 'false');
  lines.push('', ...renderItemAllowsClass(document));
  lines.push('', ...renderVendor(document), '', ...renderHeroicVendor(document), '',
    ...renderDelveShops(document), '',
    ...renderMechChromas(document), '',
    ...renderMobLoot(document), '',
    'pub maxLevel(): int {',
    `    return ${document.constants.max_level};`,
    '}',
    '',
    'pub prestigeXpPerRank(): int {',
    `    return ${document.constants.prestige_xp_per_rank};`,
    '}',
    '',
    'pub marketCut(): float {',
    `    return ${zrNumber(document.market_cut)};`,
    '}',
    '',
    'pub xpForLevel(level: int): int {');
  document.constants.xp_for_level.forEach((value, index) => {
    lines.push(`    if (level == ${index + 1}) { return ${value}; }`);
  });
  lines.push('    throw "unknown WOC M5 level";', '}', '',
    'pub bankExpansionCount(): int {',
    `    return ${document.constants.bank_expansion_prices.length};`,
    '}',
    '',
    'pub bankExpansionPrice(index: int): int {');
  document.constants.bank_expansion_prices.forEach((value, index) => {
    lines.push(`    if (index == ${index}) { return ${value}; }`);
  });
  lines.push('    throw "unknown WOC M5 bank expansion index";', '}', '',
    'pub abilityRankAtLevel(index: int, level: int): int {');
  document.abilities.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) {`);
    lines.push(`        if (level < ${entry.definition.learnLevel}) { return 0; }`);
    for (const rank of [...(entry.definition.ranks ?? [])].reverse()) {
      lines.push(`        if (level >= ${rank.level}) { return ${rank.rank}; }`);
    }
    lines.push('        return 1;', '    }');
  });
  lines.push('    throw "unknown WOC M5 ability index";', '}');
  return `${lines.join('\n')}\n`;
}

function renderValueFunction(lines, document, name, valuesFor, returnType, fallback) {
  lines.push(`pub ${name}(kind: string, index: int, field: string): ${returnType} {`);
  for (const [kind, collection] of CATEGORIES) {
    lines.push(`    if (kind == ${zrString(kind)}) {`);
    document[collection].forEach((entry, index) => {
      lines.push(`        if (index == ${index}) {`);
      for (const [field, value] of Object.entries(valuesFor(kind, entry.definition))) {
        lines.push(`            if (field == ${zrString(field)}) { return ${renderValue(value)}; }`);
      }
      lines.push(`            return ${fallback};`, '        }');
    });
    lines.push('        throw "unknown WOC M5 content index";', '    }');
  }
  lines.push('    throw "unknown WOC M5 content kind";', '}');
}

function renderItemIdBytes(document) {
  const lines = [
    'pub itemIdUtf8Length(index: int): int {',
  ];
  document.items.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) { return ${Buffer.byteLength(entry.id, 'utf8')}; }`);
  });
  lines.push('    throw "unknown WOC M5 item index";', '}', '',
    'pub itemIdUtf8Byte(index: int, byteIndex: int): uint {');
  document.items.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) {`);
    for (const [byteIndex, value] of Buffer.from(entry.id, 'utf8').entries()) {
      lines.push(`        if (byteIndex == ${byteIndex}) { return <uint>${value}; }`);
    }
    lines.push('        throw "unknown WOC M5 item id byte";', '    }');
  });
  lines.push('    throw "unknown WOC M5 item index";', '}');
  return lines;
}

function textValues(kind, definition) {
  const objective = definition.objectives?.[0] ?? {};
  const byKind = {
    item: {
      ...pickText(definition, [
        'id', 'name', 'kind', 'quality', 'slot', 'armorType', 'requiredClass', 'questId',
      ]),
      weaponHand: definition.weapon?.hand ?? '',
    },
    quest: {
      ...pickText(definition, ['id', 'name', 'giverNpcId', 'turnInNpcId']),
      objectiveType: objective.type ?? '',
      objectiveItemId: objective.itemId ?? '',
      objectiveMobId: objective.targetMobId ?? '',
    },
    mob: pickText(definition, ['id', 'name', 'family']),
    npc: pickText(definition, ['id', 'name', 'title']),
    talent_option: {
      ...pickText(definition, ['id', 'name', 'description']),
      grantAbilityId: definition.effect?.grant?.ability ?? '',
    },
    ability: pickText(definition, ['id', 'name', 'class', 'school']),
    spec: pickText(definition, ['id', 'name', 'class', 'role', 'signature']),
  };
  return byKind[kind];
}

function renderItemAllowsClass(document) {
  const lines = ['pub itemAllowsClass(index: int, cls: string): bool {'];
  document.items.forEach((entry, index) => {
    const classes = entry.definition.requiredClass ?? [];
    const expression = classes.length === 0
      ? 'true'
      : classes.map((cls) => 'cls == ' + zrString(cls)).join(' || ');
    lines.push('    if (index == ' + index + ') { return ' + expression + '; }');
  });
  lines.push('    throw "unknown WOC M5 item index";', '}');
  return lines;
}

function metricValues(kind, definition) {
  const objective = definition.objectives?.[0] ?? {};
  const explicitRequiredLevel = Number.isFinite(definition.requiredLevel)
    ? Math.floor(definition.requiredLevel)
    : 0;
  const byKind = {
    item: compactNumbers({
      sellValue: definition.sellValue,
      buyValue: definition.buyValue,
      foodHp: definition.foodHp,
      drinkMana: definition.drinkMana,
      potionHp: definition.potionHp,
      weaponMin: definition.weapon?.min,
      weaponMax: definition.weapon?.max,
      weaponSpeed: definition.weapon?.speed,
      requiredLevel: explicitRequiredLevel,
      statStr: definition.stats?.str,
      statSta: definition.stats?.sta,
      statAgi: definition.stats?.agi,
      statInt: definition.stats?.int,
      statSpi: definition.stats?.spi,
      statArmor: definition.stats?.armor,
      bagSlots: definition.bagSlots,
      stackSize: definition.stackSize,
      elixirValue: definition.elixir?.value,
      elixirDuration: definition.elixir?.duration,
    }),
    quest: compactNumbers({
      objectiveCount: objective.count,
      xpReward: definition.xpReward,
      copperReward: definition.copperReward,
    }),
    mob: compactNumbers(pick(definition, [
      'minLevel', 'maxLevel', 'hpBase', 'hpPerLevel', 'dmgBase', 'dmgPerLevel',
      'attackSpeed', 'armorPerLevel', 'moveSpeed', 'aggroRadius', 'scale',
    ])),
    npc: compactNumbers({ posX: definition.pos?.x, posZ: definition.pos?.z }),
    talent_option: compactNumbers({
      rowLevel: definition.row_level,
      bonusCharges: definition.effect?.ability?.[0]?.bonusCharges,
    }),
    ability: compactNumbers({
      learnLevel: definition.learnLevel,
      cost: definition.cost,
      castTime: definition.castTime,
      cooldown: definition.cooldown,
      range: definition.range,
      threatFlat: definition.threat?.flat,
      threatMult: definition.threat?.mult,
    }),
    spec: {},
  };
  return byKind[kind];
}

function renderHeroicVendor(document) {
  const lines = [
    'pub heroicVendorNpcId(): string {',
    `    return ${zrString(document.heroic_vendor.npc_id)};`,
    '}',
    '',
    'pub heroicVendorCurrencyItemId(): string {',
    `    return ${zrString(document.heroic_vendor.currency_item_id)};`,
    '}',
    '',
    'pub heroicVendorOfferCount(): int {',
    `    return ${document.heroic_vendor.stock.length};`,
    '}',
    '',
    'pub heroicVendorOfferItemIndex(index: int): int {',
  ];
  document.heroic_vendor.stock.forEach((entry, index) => {
    const itemIndex = document.items.findIndex((item) => item.id === entry.item_id);
    invariant(itemIndex >= 0, `heroic vendor item ${entry.item_id} is outside M5 scope`);
    lines.push(`    if (index == ${index}) { return ${itemIndex}; }`);
  });
  lines.push('    throw "unknown WOC M5 heroic vendor offer";', '}', '',
    'pub heroicVendorOfferMarks(index: int): int {');
  document.heroic_vendor.stock.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) { return ${entry.marks}; }`);
  });
  lines.push('    throw "unknown WOC M5 heroic vendor offer";', '}');
  return lines;
}

function renderDelveShops(document) {
  const offers = document.delve_shops.flatMap((shop, shopIndex) =>
    shop.stock.map((offer, offerIndex) => ({ ...offer, shopIndex, offerIndex })));
  const lines = [
    'pub delveShopCount(): int {',
    `    return ${document.delve_shops.length};`,
    '}',
    '',
    'pub delveShopIndex(id: string): int {',
  ];
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (id == ${zrString(shop.id)}) { return ${index}; }`);
  });
  lines.push('    return -1;', '}', '', 'pub delveShopId(index: int): string {');
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (index == ${index}) { return ${zrString(shop.id)}; }`);
  });
  lines.push('    throw "unknown WOC M5 Delve shop";', '}', '',
    'pub delveShopIdUtf8Length(index: int): int {');
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (index == ${index}) { return ${Buffer.byteLength(shop.id, 'utf8')}; }`);
  });
  lines.push('    throw "unknown WOC M5 Delve shop";', '}', '',
    'pub delveShopIdUtf8Byte(index: int, byteIndex: int): uint {');
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (index == ${index}) {`);
    [...Buffer.from(shop.id, 'utf8')].forEach((byte, byteIndex) => {
      lines.push(`        if (byteIndex == ${byteIndex}) { return <uint>${byte}; }`);
    });
    lines.push('        throw "unknown WOC M5 Delve shop id byte";', '    }');
  });
  lines.push('    throw "unknown WOC M5 Delve shop";', '}', '',
    'pub delveShopCompanionId(index: int): string {');
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (index == ${index}) { return ${zrString(shop.auto_companion_id)}; }`);
  });
  lines.push('    throw "unknown WOC M5 Delve shop";', '}', '',
    'pub delveShopDoorX(index: int): float {');
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (index == ${index}) { return ${zrNumber(shop.door_pos.x)}; }`);
  });
  lines.push('    throw "unknown WOC M5 Delve shop";', '}', '',
    'pub delveShopDoorZ(index: int): float {');
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (index == ${index}) { return ${zrNumber(shop.door_pos.z)}; }`);
  });
  lines.push('    throw "unknown WOC M5 Delve shop";', '}', '',
    'pub delveShopOfferCount(index: int): int {');
  document.delve_shops.forEach((shop, index) => {
    lines.push(`    if (index == ${index}) { return ${shop.stock.length}; }`);
  });
  lines.push('    return 0;', '}', '',
    'pub delveShopOfferItemIndex(shopIndex: int, offerIndex: int): int {');
  for (const offer of offers) {
    const itemIndex = document.items.findIndex((item) => item.id === offer.item_id);
    invariant(itemIndex >= 0, `Delve shop item ${offer.item_id} is outside M5 scope`);
    lines.push(`    if (shopIndex == ${offer.shopIndex} && offerIndex == ${offer.offerIndex}) { return ${itemIndex}; }`);
  }
  lines.push('    throw "unknown WOC M5 Delve shop offer";', '}', '',
    'pub delveShopOfferMarks(shopIndex: int, offerIndex: int): int {');
  for (const offer of offers) {
    lines.push(`    if (shopIndex == ${offer.shopIndex} && offerIndex == ${offer.offerIndex}) { return ${offer.marks}; }`);
  }
  lines.push('    throw "unknown WOC M5 Delve shop offer";', '}', '',
    'pub delveShopOfferGateKind(shopIndex: int, offerIndex: int): int {');
  for (const offer of offers) {
    const gateKind = offer.gate === 'available' ? 1 :
      offer.gate.startsWith('clears:') ? 2 : 3;
    lines.push(`    if (shopIndex == ${offer.shopIndex} && offerIndex == ${offer.offerIndex}) { return ${gateKind}; }`);
  }
  lines.push('    throw "unknown WOC M5 Delve shop offer";', '}', '',
    'pub delveShopOfferRequiredClears(shopIndex: int, offerIndex: int): int {');
  for (const offer of offers) {
    const clears = offer.gate.startsWith('clears:') ? Number(offer.gate.slice(7)) : 0;
    lines.push(`    if (shopIndex == ${offer.shopIndex} && offerIndex == ${offer.offerIndex}) { return ${clears}; }`);
  }
  lines.push('    throw "unknown WOC M5 Delve shop offer";', '}');
  return lines;
}

function flagValues(kind, definition) {
  const byKind = {
    item: {
      requiredLevelPresent: Number.isFinite(definition.requiredLevel),
      noDiscard: definition.noDiscard === true,
      noVendorSell: definition.noVendorSell === true,
      noMarketList: definition.noMarketList === true,
      soulbound: definition.soulbound === true,
      weaponDagger: definition.weapon?.dagger === true,
    },
    quest: {},
    mob: {},
    npc: { banker: definition.banker === true, market: definition.market === true },
    talent_option: {},
    ability: {
      requiresTarget: definition.requiresTarget === true,
      requiresDodgeProc: definition.requiresDodgeProc === true,
    },
    spec: {},
  };
  return byKind[kind];
}

function renderMechChromas(document) {
  const lines = [
    'pub mechChromaCount(): int {',
    `    return ${document.mech_chromas.length};`,
    '}',
    '',
    'pub mechChromaId(index: int): string {',
  ];
  document.mech_chromas.forEach((chroma, index) => {
    lines.push(`    if (index == ${index}) { return ${zrString(chroma.id)}; }`);
  });
  lines.push('    throw "unknown WOC M5 mech chroma";', '}', '',
    'pub mechChromaIdUtf8Length(index: int): int {');
  document.mech_chromas.forEach((chroma, index) => {
    lines.push(`    if (index == ${index}) { return ${Buffer.byteLength(chroma.id, 'utf8')}; }`);
  });
  lines.push('    throw "unknown WOC M5 mech chroma";', '}', '',
    'pub mechChromaIdUtf8Byte(index: int, byteIndex: int): uint {');
  document.mech_chromas.forEach((chroma, index) => {
    lines.push(`    if (index == ${index}) {`);
    [...Buffer.from(chroma.id, 'utf8')].forEach((byte, byteIndex) => {
      lines.push(`        if (byteIndex == ${byteIndex}) { return <uint>${byte}; }`);
    });
    lines.push('        throw "unknown WOC M5 mech chroma UTF-8 byte";', '    }');
  });
  lines.push('    throw "unknown WOC M5 mech chroma";', '}', '',
    'pub mechChromaItemIndex(index: int): int {');
  document.mech_chromas.forEach((chroma, index) => {
    const itemIndex = document.items.findIndex((entry) => entry.id === chroma.item_id);
    invariant(itemIndex >= 0, `M5 mech chroma item is outside scope: ${chroma.item_id}`);
    lines.push(`    if (index == ${index}) { return ${itemIndex}; }`);
  });
  lines.push('    throw "unknown WOC M5 mech chroma";', '}', '',
    'pub mechChromaSkinIndex(index: int): int {');
  document.mech_chromas.forEach((chroma, index) => {
    lines.push(`    if (index == ${index}) { return ${chroma.skin_index}; }`);
  });
  lines.push('    throw "unknown WOC M5 mech chroma";', '}');
  return lines;
}

function renderVendor(document) {
  const lines = ['pub npcHasVendorStock(index: int): bool {'];
  document.npcs.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) { return ${(entry.definition.vendorItems ?? []).length > 0}; }`);
  });
  lines.push('    throw "unknown WOC M5 NPC index";', '}', '',
    'pub npcSells(index: int, itemId: string): bool {');
  document.npcs.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) {`);
    for (const itemId of entry.definition.vendorItems ?? []) {
      lines.push(`        if (itemId == ${zrString(itemId)}) { return true; }`);
    }
    lines.push('        return false;', '    }');
  });
  lines.push('    throw "unknown WOC M5 NPC index";', '}');
  return lines;
}

function renderMobLoot(document) {
  const lines = ['pub mobLootCount(index: int): int {'];
  document.mobs.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) { return ${(entry.definition.loot ?? []).length}; }`);
  });
  lines.push('    throw "unknown WOC M5 mob index";', '}', '',
    'pub mobLootText(index: int, lootIndex: int, field: string): string {');
  document.mobs.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) {`);
    (entry.definition.loot ?? []).forEach((loot, lootIndex) => {
      lines.push(`        if (lootIndex == ${lootIndex}) {`);
      if (typeof loot.itemId === 'string') {
        lines.push(`            if (field == "itemId") { return ${zrString(loot.itemId)}; }`);
      }
      lines.push('            return "";', '        }');
    });
    lines.push('        throw "unknown WOC M5 mob loot index";', '    }');
  });
  lines.push('    throw "unknown WOC M5 mob index";', '}', '',
    'pub mobLootMetric(index: int, lootIndex: int, field: string): float {');
  document.mobs.forEach((entry, index) => {
    lines.push(`    if (index == ${index}) {`);
    (entry.definition.loot ?? []).forEach((loot, lootIndex) => {
      lines.push(`        if (lootIndex == ${lootIndex}) {`);
      for (const field of ['copper', 'chance']) {
        if (typeof loot[field] === 'number') {
          lines.push(`            if (field == ${zrString(field)}) { return ${zrNumber(loot[field])}; }`);
        }
      }
      lines.push('            return 0.0;', '        }');
    });
    lines.push('        throw "unknown WOC M5 mob loot index";', '    }');
  });
  lines.push('    throw "unknown WOC M5 mob index";', '}');
  return lines;
}

function pickText(value, fields) {
  return Object.fromEntries(fields.map((field) => [field, textValue(value[field])]));
}

function textValue(value) {
  if (Array.isArray(value)) return value.join(',');
  return typeof value === 'string' ? value : '';
}

function pick(value, fields) {
  return Object.fromEntries(fields.map((field) => [field, value[field]]));
}

function compactNumbers(values) {
  return Object.fromEntries(Object.entries(values).filter(([, value]) => Number.isFinite(value)));
}

function renderValue(value) {
  if (typeof value === 'string') return zrString(value);
  if (typeof value === 'boolean') return String(value);
  return zrNumber(value);
}

function writeOrCheck(path, content) {
  if (checkOnly) {
    invariant(existsSync(path), `${path} is missing; run npm run generate:m5`);
    invariant(readFileSync(path, 'utf8') === content,
      `${path} is stale; run npm run generate:m5`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
}

function zrString(value) {
  return JSON.stringify(value);
}

function zrNumber(value) {
  invariant(Number.isFinite(value), `non-finite Zr number ${value}`);
  return Number.isInteger(value) ? `${value}.0` : String(value);
}

function hashText(value) {
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

function invariant(condition, message) {
  if (!condition) throw new Error(message);
}
