use super::Slice;

pub(super) const ROWS: [Slice; 4] = [
    (
        "Runtime 15 M3 scene-script row-data owner child split",
        &[
            "runtime_15_scene_script_row_data_owner_child_split_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/runtime_07_performance.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/script_vm_runtime.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/plugin_extension_tests.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/script_vm_gameplay_shader.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/scene_ecs_tests.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/scene_asset_world.rs",
            "runtime_15_scene_script_row_data_owner_is_child_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 scene-script row-data guard folder-backed split",
        &[
            "runtime_15_scene_script_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/export_chain.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/budgets.rs",
            "runtime_15_scene_script_row_data_guard_is_folder_backed",
            "runtime_15_scene_script_row_data_owner_is_child_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 scene-script row-data status-mirror child split",
        &[
            "runtime_15_scene_script_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors/folder_backed_status.rs",
            "runtime_15_scene_script_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 scene-script row-data root inventory child split",
        &[
            "runtime_15_scene_script_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/root_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/root_statuses.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/root_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/root_inventory.rs",
            "runtime_15_scene_script_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 scene-script row-data source/status-map sync",
        &[
            "runtime_15_scene_script_row_data_source_status_map_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/root_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors/folder_backed_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_scene_script_row_data/status_mirrors/historical_status.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/runtime_row_data/lock_poison_scene_script_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/row_data_owner.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/row_data_maps/other_row_data_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps/row_data_maps/other_row_data_maps.rs",
            "runtime_15_scene_script_row_data_guard_is_folder_backed",
            "runtime_15_scene_script_row_data_root_inventory_is_child_owned",
            "runtime_15_scene_script_row_data_owner_is_child_backed",
            "runtime_15_scene_script_row_data_status_mirror_status_rows_are_current",
            "runtime_15_scene_script_row_data_guard_folder_backed_status_mirrors_are_current",
            "runtime_15_scene_script_row_data_historical_status_is_current",
            "Cargo gate deferred",
        ],
    ),
];
