pub(super) const STATUS_DOC_FOLDER_BACKED_SUMMARY_ANCHORS: &[&str] = &[
    "Runtime 15 M3 code review findings folder-backed summary child-owner split",
    "runtime_15_code_review_findings_folder_backed_summary_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary.rs",
    "runtime_15_code_review_findings_folder_backed_summary_is_child_owner",
    "Runtime 15 M3 code review findings folder-backed summary guard folder-backed split",
    "runtime_15_code_review_findings_folder_backed_summary_guard_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/status_mirrors.rs",
    "runtime_15_code_review_findings_folder_backed_summary_guard_folder_backed_status_is_current",
    "Runtime 15 M3 code review findings source inventory child-owner split",
    "runtime_15_code_review_findings_source_inventory_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory.rs",
    "runtime_15_code_review_findings_source_inventory_is_child_owner",
    "Runtime 15 M3 code review findings source inventory status-mirror child-owner split",
    "runtime_15_code_review_findings_source_inventory_status_mirror_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/status_mirrors.rs",
    "runtime_15_code_review_findings_source_inventory_status_mirrors_are_child_owner",
    "Runtime 15 M3 code review findings direct assertions child-owner split",
    "runtime_15_code_review_findings_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions.rs",
    "runtime_15_code_review_findings_direct_assertions_are_child_owner",
    "Runtime 15 M3 code review findings direct assertions guard folder-backed split",
    "runtime_15_code_review_findings_direct_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/status_mirrors.rs",
    "runtime_15_code_review_findings_direct_assertions_children_are_child_owned",
    "runtime_15_code_review_findings_direct_assertions_guard_folder_backed_status_is_current",
    "Runtime 15 M3 code review findings F12 direct assertions child-owner split",
    "runtime_15_code_review_findings_f12_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/f12.rs",
    "runtime_15_code_review_findings_f12_direct_assertions_are_child_owner",
    "Runtime 15 M3 code review findings F8 direct assertions child-owner split",
    "runtime_15_code_review_findings_f8_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/f8.rs",
    "runtime_15_code_review_findings_f8_direct_assertions_are_child_owner",
    "Runtime 15 M3 code review findings P0 direct assertions child-owner split",
    "runtime_15_code_review_findings_p0_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/p0.rs",
    "runtime_15_code_review_findings_p0_direct_assertions_are_child_owner",
    "Runtime 15 M3 code review findings root-parent direct assertions child-owner split",
    "runtime_15_code_review_findings_root_parent_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/root_parent.rs",
    "runtime_15_code_review_findings_root_parent_direct_assertions_are_child_owner",
    "Runtime 15 M3 code review findings render direct assertions child-owner split",
    "runtime_15_code_review_findings_render_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/render.rs",
    "runtime_15_code_review_findings_render_direct_assertions_are_child_owner",
];

pub(super) const STATUS_DOC_FOLDER_BACKED_SUMMARY_BOUNDARY_ANCHORS: &[&str] =
    &["Runtime 15 M3 code review findings F12 direct assertions child-owner split"];
