pub(super) const STATUS_DOC_STRUCTURE_GUARD_ANCHORS: &[&str] = &[
    "Runtime 15 M3 code review findings structure guard folder-backed summary child-owner split",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary.rs",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_is_child_owner",
    "Runtime 15 M3 code review findings structure guard folder-backed summary guard folder-backed split",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_guard_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/direct_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/source_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/status_mirrors.rs",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_direct_assertions_are_child_owned",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_source_inventory_is_child_owned",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_children_line_budgets_are_current",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_guard_folder_backed_status_is_current",
    "Runtime 15 M3 code review findings structure guard typed-error child-owner split",
    "runtime_15_code_review_findings_structure_guard_typed_error_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/typed_error.rs",
    "runtime_15_code_review_findings_structure_guard_typed_error_is_child_owner",
    "Runtime 15 M3 typed-error structure assertions guard folder-backed split",
    "runtime_15_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/convergence_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/status_mirrors.rs",
    "runtime_15_typed_error_structure_assertions_children_are_child_owned",
    "runtime_15_typed_error_structure_assertions_guard_folder_backed_status_is_current",
    "Runtime 15 M3 typed-error structure status-doc guard folder-backed split",
    "runtime_15_typed_error_structure_status_docs_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/status_docs/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/status_docs/doc_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/status_docs/status_maps.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/status_docs/status_mirrors.rs",
    "runtime_15_typed_error_status_docs_are_folder_backed",
    "runtime_15_typed_error_status_docs_folder_backed_status_is_current",
    "Runtime 15 M3 plugin-importer DX structure assertions guard child-owner split",
    "runtime_15_plugin_importer_dx_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions.rs",
    "runtime_15_plugin_importer_dx_structure_assertions_are_child_owner",
    "Runtime 15 M3 plugin-importer DX structure assertions guard folder-backed split",
    "runtime_15_plugin_importer_dx_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/review_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/status_mirrors.rs",
    "runtime_15_plugin_importer_dx_structure_assertions_children_are_child_owned",
    "runtime_15_plugin_importer_dx_structure_assertions_guard_folder_backed_status_is_current",
    "Runtime 15 M3 plugin-importer D13 SDK structure assertions guard child-owner split",
    "runtime_15_plugin_importer_d13_sdk_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk.rs",
    "runtime_15_plugin_importer_d13_sdk_structure_assertions_are_child_owner",
    "Runtime 15 M3 plugin-importer D13 SDK parent-mount guard child split",
    "runtime_15_plugin_importer_d13_sdk_parent_mounts_guard_child_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk/parent_mounts/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk/parent_mounts/review_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk/parent_mounts/folder_backed.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk/parent_mounts/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk/parent_mounts/status_mirrors.rs",
    "runtime_15_plugin_importer_d13_sdk_parent_mounts_guard_is_child_backed",
    "runtime_15_plugin_importer_d13_sdk_parent_mounts_status_mirrors_are_current",
];

pub(super) const STATUS_DOC_STRUCTURE_GUARD_BOUNDARY_ANCHORS: &[&str] = &[
    "runtime_15_plugin_importer_d13_sdk_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_plugin_importer_d13_sdk_parent_mounts_guard_child_split_static_passed_cargo_deferred",
];
