pub(in super::super) const ROOT_PATHS_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths.rs",
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/owner_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/owner_paths.rs",
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/status_output_guard_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/status_output_guard_paths.rs",
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/status_row_base_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/status_row_base_paths.rs",
        70,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_support_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_support_paths.rs",
        70,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_core_and_evidence_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_core_and_evidence_paths.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_module_layout_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_module_layout_paths.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_review_guard_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_review_guard_paths.rs",
        70,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_runtime_row_data_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_runtime_row_data_paths.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_status_docs_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/production_guard_status_docs_paths.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/status_support_map_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths/status_support_map_paths.rs",
        40,
    ),
];
