use super::*;

pub(super) fn assert_runtime_structure_exports_are_current() {
    let foundation_guards_parent = read_runtime_src(FOUNDATION_GUARDS_ROWS_PATH);
    let runtime_15_m3 = read_runtime_src(RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15 = read_runtime_src(RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH);
    let top_level = read_runtime_src(TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH);

    assert_contains_all(
        "foundation-guards parent exports runtime-structure children",
        &foundation_guards_parent,
        &[
            "RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 M3 aggregation exports runtime-structure children",
        &runtime_15_m3,
        &[
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 and top-level aggregation consume runtime-structure children",
        &[runtime_15.as_str(), top_level.as_str()].join("\n"),
        &[
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
}
