use super::*;

pub(super) fn assert_review_source_anchors(label: &str, source: &str) {
    assert_contains_all(
        label,
        source,
        &[
            "Runtime 15 M3 code review findings test folder split",
            "runtime_15_code_review_findings_tests_folder_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/mod.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/animation_binary.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/artifact_importer.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/mesh_obj.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/texture.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f11_shading_model_registry.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f15_editor_pane_data_conversion.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f17_entity_path_lookup.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f18_asset_manager_resolution.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f19_scene_renderer_construction.rs",
            "Runtime 15 M3 late API cleanup review guard child-owner split",
            "runtime_15_late_api_cleanup_review_guard_child_owner_split_static_passed_cargo_deferred",
            "runtime_15_late_api_cleanup_review_guards_are_child_owners",
            "review_f11_shading_model_registry_has_no_dead_plugin_registration_surface",
            "review_f15_editor_pane_data_conversion_top_row_uses_projection_owners",
            "review_f17_entity_path_option_lookup_uses_get_verb",
            "review_f18_asset_manager_resolution_returns_registered_handle",
            "review_f19_scene_renderer_construction_modules_use_construct_names",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/diagnostics.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/authoring.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/font.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/meta.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/navigation.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/sound.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/zshader.rs",
            "Runtime 15 M3 asset loader typed-error review guard child-owner split",
            "runtime_15_asset_loader_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 asset records typed-error review guard child-owner split",
            "runtime_15_asset_records_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 shader prewarm CLI typed-error review guard child-owner split",
            "runtime_15_shader_prewarm_cli_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "review_f5_asset_authoring_uses_typed_error",
            "review_f5_navigation_asset_uses_typed_error",
            "review_f5_font_asset_uses_typed_error_source",
            "review_f5_sound_asset_uses_typed_error",
            "review_f5_zshader_v2_replaces_user_shader_definitions",
            "review_f5_asset_meta_uses_typed_error",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/shader_prewarm_cli.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/shader_prewarm_cli/args_boundary.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/shader_prewarm_cli/run_boundary.rs",
            "Runtime 15 M3 UI input typed-error review guard child-owner split",
            "runtime_15_ui_input_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/ui_input.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/ui_input/surface_effects.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/ui_input/surrounding_text.rs",
            "review_f5_shader_prewarm_args_use_typed_usage_errors_before_cli_boundary",
            "review_f5_shader_prewarm_cli_typed_error_sweep_is_closed_at_run_boundary",
            "review_f5_ui_surface_input_effects_use_typed_errors_before_rejected_reason_boundary",
            "review_f5_ui_input_surrounding_text_error_implements_std_error",
        ],
    );
}
