use super::*;

pub(super) fn assert_structure_owner_source_anchors(label: &str, source: &str) {
    assert_contains_all(
        label,
        source,
        &[
            "Runtime 15 M3 code review findings structure guard child-owner split",
            "runtime_15_code_review_findings_structure_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 code review findings typed-error structure guard child-owner split",
            "runtime_15_code_review_findings_typed_error_structure_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 typed-error structure assertions guard child-owner split",
            "runtime_15_typed_error_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 code review findings plugin-importer DX structure guard child-owner split",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 plugin-importer DX status-doc guard child-owner split",
            "runtime_15_plugin_importer_dx_status_docs_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 plugin-importer DX source inventory guard child-owner split",
            "runtime_15_plugin_importer_dx_source_inventory_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 plugin-importer DX review guard child-owner split",
            "runtime_15_plugin_importer_dx_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 plugin-importer D13 SDK review guard child-owner split",
            "runtime_15_plugin_importer_d13_sdk_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/source_inventory.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status_docs.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/f12.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/f8.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/p0.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/render.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/root_parent.rs",
            "runtime_15_code_review_findings_structure_guard_children_are_mounted",
            "runtime_15_code_review_findings_typed_error_structure_guard_is_child_owner",
            "runtime_15_typed_error_structure_assertions_are_child_owner",
            "runtime_15_code_review_findings_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_f12_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_f8_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_p0_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_render_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_root_parent_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "runtime_15_plugin_importer_dx_source_inventory_is_child_owner",
            "runtime_15_plugin_importer_dx_status_docs_are_child_owner",
            SOURCE_ANCHOR_OWNER_GUARD,
        ],
    );
}
