use super::super::sources::OwnerBudgetSources;

pub(super) fn assert_owner_budget_budgets(sources: &OwnerBudgetSources) {
    for (path, source) in [
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget.rs",
            sources.owner_budget,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes.rs",
            sources.owner_budget_child_routes,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/artifact_render_diagnostics.rs",
            sources.owner_budget_child_routes_artifact_render_diagnostics,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/hotspot_inventory.rs",
            sources.owner_budget_child_routes_hotspot_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/owner_budget.rs",
            sources.owner_budget_child_routes_owner_budget,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/scene_project.rs",
            sources.owner_budget_child_routes_scene_project,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/submit_context.rs",
            sources.owner_budget_child_routes_submit_context,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/large_file_gate.rs",
            sources.owner_budget_large_file_gate,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets.rs",
            sources.owner_budget_line_budgets,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/artifact_render_diagnostics.rs",
            sources.owner_budget_line_budgets_artifact_render_diagnostics,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/hotspot_inventory.rs",
            sources.owner_budget_line_budgets_hotspot_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/owner_budget.rs",
            sources.owner_budget_line_budgets_owner_budget,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/root.rs",
            sources.owner_budget_line_budgets_root,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/scene_project.rs",
            sources.owner_budget_line_budgets_scene_project,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/submit_context.rs",
            sources.owner_budget_line_budgets_submit_context,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/mirror_docs.rs",
            sources.owner_budget_mirror_docs,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/parent_routes.rs",
            sources.owner_budget_parent_routes,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/source_inventory.rs",
            sources.owner_budget_source_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/sources.rs",
            sources.owner_budget_sources,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/sources/load.rs",
            sources.owner_budget_sources_load,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout.rs",
            sources.owner_budget_split_layout,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route.rs",
            sources.owner_budget_split_layout_route,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/parent_route.rs",
            sources.owner_budget_split_layout_route_parent_route,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/split_route.rs",
            sources.owner_budget_split_layout_route_split_route,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/support_routes.rs",
            sources.owner_budget_split_layout_route_support_routes,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/source_inventory.rs",
            sources.owner_budget_split_layout_source_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/status_docs.rs",
            sources.owner_budget_status_docs,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/virtual_geometry_debug_snapshot.rs",
            sources.owner_budget_virtual_geometry_debug_snapshot,
        ),
    ] {
        super::assert_runtime_15_test_file_budget(path, source);
    }
}
