type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 production guard status-doc row-data folder-backed split",
        &[
            "runtime_15_production_guard_status_docs_row_data_folder_backed_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/status_docs.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/status_docs/foundation_m2_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/status_docs/child_group_status_doc_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/status_docs/child_group_status_row_doc_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/status_docs/child_group_moved_row_rows.rs",
            "Cargo gate deferred active Render Plan08/text lanes",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-doc guard child-owner split",
        &[
            "runtime_15_foundation_row_data_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "runtime_15_status_output_foundation_row_data_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data guard child-owner split",
        &[
            "runtime_15_m2_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "runtime_15_status_output_runtime_15_m2_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data guard folder-backed split",
        &[
            "runtime_15_m2_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/budgets.rs",
            "runtime_15_m2_row_data_guard_is_folder_backed",
            "runtime_15_status_output_runtime_15_m2_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data status-mirror child split",
        &[
            "runtime_15_m2_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/folder_backed_status.rs",
            "runtime_15_m2_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data root inventory child split",
        &[
            "runtime_15_m2_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_owner_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_inventory.rs",
            "runtime_15_m2_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data source/status-map sync",
        &[
            "runtime_15_m2_row_data_source_status_map_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data_children/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data_children/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data_children/delegation.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/m2_row_data_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps/m2_row_data_maps.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/naming_boundary/core_bootstrap.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/naming_boundary/core_bootstrap.rs",
            "runtime_15_m2_row_data_guard_is_folder_backed",
            "runtime_15_m2_row_data_children_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-doc guard folder-backed split",
        &[
            "runtime_15_foundation_row_data_status_docs_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/doc_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count.rs",
            "runtime_15_status_output_foundation_row_data_status_docs_are_child_owner",
            "runtime_15_foundation_row_data_docs_record_current_row_count",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data row-count child split",
        &[
            "runtime_15_foundation_row_data_row_count_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/current_counts.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/priority_frontmatter.rs",
            "runtime_15_foundation_row_data_row_count_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-doc root inventory child split",
        &[
            "runtime_15_foundation_row_data_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_source_blobs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_inventory.rs",
            "runtime_15_foundation_row_data_status_docs_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-doc source/status-map sync",
        &[
            "runtime_15_foundation_row_data_status_docs_source_status_map_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/root_child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/current_counts.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/priority_frontmatter.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/foundation_row_data_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps/foundation_row_data_maps.rs",
            "runtime_15_status_output_foundation_row_data_status_docs_are_child_owner",
            "runtime_15_foundation_row_data_status_doc_maps_are_child_owned",
            "runtime_15_foundation_row_data_row_count_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
];
