type Slice = super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 review-guard expected-slice route child sources folder-backed split",
        &[
            "runtime_15_review_guard_expected_slice_route_child_sources_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/guard_body.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/helpers.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/status_docs.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/status_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "runtime_15_review_guard_expected_slice_route_child_sources_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard expected-slice route metadata budgets folder-backed split",
        &[
            "runtime_15_review_guard_expected_slice_route_metadata_budgets_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets/guard_body.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets/parent_routes.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets/source_children.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets/status_docs.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/route_metadata/budgets/status_mirrors.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "runtime_15_review_guard_expected_slice_route_metadata_budgets_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard expected-slice route metadata source constants folder-backed split",
        &[
            "runtime_15_review_guard_expected_slice_route_metadata_source_constants_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/child_sources.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/guard_routes.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/status_docs.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/review_route_children/sources/route_metadata/structure_routes.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "runtime_15_review_guard_expected_slice_route_metadata_source_constants_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
