use super::super::super::super::super::*;
use super::*;

pub(super) fn assert_typed_error_status_doc_source_paths_are_synced(
    sources: &TypedErrorStatusDocSources,
) {
    for (label, source) in typed_error_status_doc_mirror_sources(sources) {
        assert_contains_all(
            label,
            source,
            &[
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/delegation.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/child_ownership.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/status_mirrors.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/source_inventory.rs",
                "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status_docs.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/mod.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/animation_binary.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/artifact_importer.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/mesh_obj.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders/texture.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/authoring.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/font.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/meta.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/navigation.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/sound.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records/zshader.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces/behavior_bridge.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces/plugin_descriptor.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces/plugin_descriptor/string_helpers.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces/plugin_descriptor/descriptor_abi.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces/plugin_descriptor/entry_abi.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces/host_adapter.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/lifecycle_paths.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/lifecycle_paths/hot_reload.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/lifecycle_paths/lifecycle.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/lifecycle_paths/loading.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/replay_and_runtime.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/replay_and_runtime/bridge_methods.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/replay_and_runtime/registration_replay.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/replay_and_runtime/runtime_behavior.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/manifest_sources.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/manifest_sources/compat_registration.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/manifest_sources/collection_candidate.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/scene_world.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/scene_world/typed_mutation_surface.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/scene_world/fixed_mutation.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/scene_world/dynamic_components.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/scene_world/property_access.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/script_host.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/script_host/gameplay_scene.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/script_host/plugin_management.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/script_host/host_reflection_docs.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/shader_prewarm_cli.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/shader_prewarm_cli/args_boundary.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/shader_prewarm_cli/run_boundary.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/ui_input.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/ui_input/surface_effects.rs",
                "tests/runtime_absorption/code_review_findings/typed_error_convergence/ui_input/surrounding_text.rs",
            ],
        );
    }
}
