use super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 code review findings folder-backed summary child-owner split",
        &[
            "runtime_15_code_review_findings_folder_backed_summary_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary.rs",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "runtime_15_code_review_findings_folder_backed_summary_is_child_owner",
            "runtime_15_code_review_findings_structure_guard_children_are_mounted",
            "runtime_15_code_review_findings_status_docs_are_child_owner",
            "78 review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings folder-backed summary guard folder-backed split",
        &[
            "runtime_15_code_review_findings_folder_backed_summary_guard_folder_backed_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/child_ownership.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/status_mirrors.rs",
            "runtime_15_code_review_findings_folder_backed_summary_is_child_owner",
            "runtime_15_code_review_findings_folder_backed_summary_children_are_child_owned",
            "runtime_15_code_review_findings_folder_backed_summary_guard_folder_backed_status_is_current",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings folder-backed summary child-ownership guard folder-backed split",
        &[
            "runtime_15_code_review_findings_folder_backed_summary_child_ownership_guard_folder_backed_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/child_ownership.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/ownership/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/ownership/parent_absence.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/ownership/direct_assertions.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/ownership/source_inventory.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/ownership/budgets.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/ownership/status_mirrors.rs",
            "runtime_15_code_review_findings_folder_backed_summary_children_are_child_owned",
            "runtime_15_code_review_findings_folder_backed_summary_child_ownership_guard_is_folder_backed",
            "runtime_15_code_review_findings_folder_backed_summary_child_ownership_guard_folder_backed_status_is_current",
            "runtime_15_code_review_findings_folder_backed_summary_child_ownership_children_line_budgets_are_current",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings source inventory child-owner split",
        &[
            "runtime_15_code_review_findings_source_inventory_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory.rs",
            "runtime_15_code_review_findings_source_inventory_is_child_owner",
            "runtime_15_code_review_findings_folder_backed_summary_is_child_owner",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "runtime_15_code_review_findings_status_docs_are_child_owner",
            "15 directly counted review guards",
            "78 review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings source inventory folder-backed split",
        &[
            "runtime_15_code_review_findings_source_inventory_folder_backed_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/model.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/reads.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/budgets.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/status_mirrors.rs",
            "runtime_15_code_review_findings_source_inventory_is_child_owner",
            "15 directly counted review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings source inventory status-mirror child-owner split",
        &[
            "runtime_15_code_review_findings_source_inventory_status_mirror_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/status_mirrors.rs",
            "runtime_15_code_review_findings_source_inventory_is_child_owner",
            "runtime_15_code_review_findings_source_inventory_status_mirrors_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings source inventory map-source sync",
        &[
            "runtime_15_code_review_findings_source_inventory_map_source_sync_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/status_mirrors.rs",
            "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/code_review_guard_maps/source_inventory_rows.rs",
            "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/code_review_guard_maps/source_inventory_rows.rs",
            "source_inventory_status_map_source",
            "source_inventory_date_map_source",
            "runtime_15_code_review_findings_source_inventory_status_mirrors_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings structure guard folder-backed summary child-owner split",
        &[
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary.rs",
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_is_child_owner",
            "runtime_15_code_review_findings_structure_guard_children_are_mounted",
            "runtime_15_code_review_findings_folder_backed_summary_is_child_owner",
            "runtime_15_code_review_findings_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_source_inventory_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings structure guard folder-backed summary guard folder-backed split",
        &[
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_guard_folder_backed_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/direct_assertions.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/source_inventory.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/budgets.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/status_mirrors.rs",
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_is_child_owner",
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_direct_assertions_are_child_owned",
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_source_inventory_is_child_owned",
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_children_line_budgets_are_current",
            "runtime_15_code_review_findings_structure_guard_folder_backed_summary_guard_folder_backed_status_is_current",
            "runtime_15_code_review_findings_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_source_inventory_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
];
