"""Generated plugin package manifest templates."""

from __future__ import annotations

from typing import Any, Sequence

from .native_dynamic_templates import toml_string


def feature_provider_package_manifest_template(
    *,
    owner_manifest: dict[str, Any],
    feature: dict[str, Any],
    provider_package_id: str,
    distribution: dict[str, Any],
) -> str:
    feature_id = feature_string(feature, "id", provider_package_id)
    display_name = feature_string(feature, "display_name", feature_id)
    capabilities = feature_string_array(feature.get("capabilities"))
    supported_targets = feature_provider_supported_targets(owner_manifest, feature)
    supported_platforms = feature_string_array(owner_manifest.get("supported_platforms")) or [
        "windows",
        "linux",
        "macos",
    ]
    default_packaging = feature_string_array(
        distribution.get("default_packaging")
    ) or ["native_dynamic"]
    owner_plugin_id = feature_string(feature, "owner_plugin_id", owner_manifest.get("id", ""))
    runtime_module = feature_provider_runtime_module(feature, distribution)
    lines = [
        "# Generated by Zircon export. Feature provider package manifest.",
        f"id = {toml_string(provider_package_id)}",
        f"version = {toml_string(feature_string(owner_manifest, 'version', '0.1.0'))}",
        'package_kind = "feature_extension"',
        f"display_name = {toml_string(display_name + ' Provider')}",
        f"description = {toml_string(f'Native dynamic provider for optional feature {feature_id}.')}",
        f"sdk_api_version = {toml_string(feature_string(owner_manifest, 'sdk_api_version', '0.1.0'))}",
        f"category = {toml_string(feature_string(owner_manifest, 'category', 'runtime'))}",
        f"maturity = {toml_string(feature_string(owner_manifest, 'maturity', 'beta'))}",
        f"supported_targets = {toml_string_array(supported_targets)}",
        f"supported_platforms = {toml_string_array(supported_platforms)}",
        f"capabilities = {toml_string_array(capabilities)}",
        f"default_packaging = {toml_string_array(default_packaging)}",
        "",
        "[distribution]",
        f"forms = {toml_string_array(feature_string_array(distribution.get('forms')))}",
        f"default_packaging = {toml_string_array(default_packaging)}",
    ]
    abi_version = distribution.get("abi_version")
    if type(abi_version) is int:
        lines.append(f"abi_version = {abi_version}")
    for field in ("engine_compat", "dist_crate", "descriptor_symbol", "runtime_entry"):
        lines.append(f"{field} = {toml_string(feature_string(distribution, field, ''))}")
    editor_entry = distribution.get("editor_entry")
    if isinstance(editor_entry, str) and editor_entry.strip():
        lines.append(f"editor_entry = {toml_string(editor_entry)}")
    assets = feature_string_array(distribution.get("assets"))
    if assets:
        lines.append(f"assets = {toml_string_array(assets)}")

    lines.extend(
        [
            "",
            "[[feature_extensions]]",
            f"id = {toml_string(feature_id)}",
            f"display_name = {toml_string(display_name)}",
            f"owner_plugin_id = {toml_string(owner_plugin_id)}",
            f"capabilities = {toml_string_array(capabilities)}",
            f"default_packaging = {toml_string_array(default_packaging)}",
            f"enabled_by_default = {toml_bool(feature.get('enabled_by_default'))}",
            "",
        ]
    )
    for dependency in feature_provider_dependencies(feature):
        lines.extend(
            [
                "[[feature_extensions.dependencies]]",
                f"plugin_id = {toml_string(dependency['plugin_id'])}",
                f"capability = {toml_string(dependency['capability'])}",
                f"primary = {toml_bool(dependency['primary'])}",
                "",
            ]
        )
    lines.extend(
        [
            "[[feature_extensions.modules]]",
            f"name = {toml_string(runtime_module['name'])}",
            'kind = "runtime"',
            f"crate_name = {toml_string(runtime_module['crate_name'])}",
            f"target_modes = {toml_string_array(runtime_module['target_modes'])}",
            f"capabilities = {toml_string_array(runtime_module['capabilities'])}",
            "",
        ]
    )
    return "\n".join(lines)


def feature_provider_supported_targets(
    owner_manifest: dict[str, Any],
    feature: dict[str, Any],
) -> list[str]:
    runtime_module = first_feature_module(feature, "runtime")
    if runtime_module is not None:
        target_modes = feature_string_array(runtime_module.get("target_modes"))
        if target_modes:
            return target_modes
    return feature_string_array(owner_manifest.get("supported_targets")) or [
        "client_runtime",
        "editor_host",
    ]


def feature_provider_runtime_module(
    feature: dict[str, Any],
    distribution: dict[str, Any],
) -> dict[str, list[str] | str]:
    feature_id = feature_string(feature, "id", "feature")
    dist_crate = feature_string(distribution, "dist_crate", "")
    feature_capabilities = feature_string_array(feature.get("capabilities"))
    source_module = first_feature_module(feature, "runtime")
    if source_module is None:
        return {
            "name": f"{feature_id}.runtime",
            "crate_name": dist_crate,
            "target_modes": ["client_runtime", "editor_host"],
            "capabilities": feature_capabilities,
        }
    return {
        "name": feature_string(source_module, "name", f"{feature_id}.runtime"),
        "crate_name": dist_crate,
        "target_modes": feature_string_array(source_module.get("target_modes"))
        or ["client_runtime", "editor_host"],
        "capabilities": feature_string_array(source_module.get("capabilities"))
        or feature_capabilities,
    }


def first_feature_module(
    feature: dict[str, Any],
    module_kind: str,
) -> dict[str, Any] | None:
    modules = feature.get("modules")
    if not isinstance(modules, list):
        return None
    for module in modules:
        if isinstance(module, dict) and module.get("kind") == module_kind:
            return module
    return None


def feature_provider_dependencies(feature: dict[str, Any]) -> list[dict[str, object]]:
    dependencies = feature.get("dependencies")
    if not isinstance(dependencies, list):
        return []
    output: list[dict[str, object]] = []
    for dependency in dependencies:
        if not isinstance(dependency, dict):
            continue
        plugin_id = dependency.get("plugin_id")
        capability = dependency.get("capability")
        if not isinstance(plugin_id, str) or not isinstance(capability, str):
            continue
        output.append(
            {
                "plugin_id": plugin_id,
                "capability": capability,
                "primary": dependency.get("primary") is True,
            }
        )
    return output


def feature_string(mapping: dict[str, Any], field: str, default: object) -> str:
    value = mapping.get(field)
    if isinstance(value, str) and value.strip():
        return value
    return str(default)


def feature_string_array(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, str) and item.strip() == item]


def toml_string_array(values: Sequence[str]) -> str:
    return "[" + ", ".join(toml_string(value) for value in values) + "]"


def toml_bool(value: object) -> str:
    return "true" if value is True else "false"
