use super::*;

pub(super) fn assert_status_support_review_rows_exports_are_current() {
    assert_contains_all(
        "review_guard_splits exports status-support review row groups",
        &read_runtime_src(REVIEW_GUARD_SPLITS_PATH),
        &[
            "STATUS_SUPPORT_REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 M3 exports status-support review row groups",
        &read_runtime_src(RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH),
        &[
            "REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 root exports status-support review row groups",
        &read_runtime_src(RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH),
        &[
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "top-level expected status rows include status-support review row groups",
        &read_runtime_src(TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH),
        &[
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
}
