type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 foundation row-data guard child-owner split",
        &[
            "runtime_15_foundation_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data.rs",
            "runtime_15_status_output_runtime_15_foundation_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data guard folder-backed split",
        &[
            "runtime_15_foundation_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/exports.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/topic_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/budgets.rs",
            "runtime_15_foundation_row_data_guard_is_folder_backed",
            "runtime_15_status_output_runtime_15_foundation_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-mirror child split",
        &[
            "runtime_15_foundation_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/status_mirrors/folder_backed_status.rs",
            "runtime_15_foundation_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data root inventory child split",
        &[
            "runtime_15_foundation_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/root_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/root_statuses.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/root_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/root_inventory.rs",
            "runtime_15_foundation_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data source/status-map sync",
        &[
            "runtime_15_foundation_row_data_source_status_map_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/root_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/status_mirrors/historical_status.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/row_data_maps/foundation_row_data_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps/row_data_maps/foundation_row_data_maps.rs",
            "runtime_15_foundation_row_data_guard_is_folder_backed",
            "runtime_15_status_output_runtime_15_foundation_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation-guards row-data guard folder-backed split",
        &[
            "runtime_15_foundation_guards_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/export_chain.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/budgets.rs",
            "runtime_15_foundation_guards_row_data_guard_is_folder_backed",
            "runtime_15_foundation_guards_row_data_owner_is_child_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation-guards row-data status-mirror child split",
        &[
            "runtime_15_foundation_guards_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/status_mirrors/folder_backed_status.rs",
            "runtime_15_foundation_guards_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation-guards row-data root inventory child split",
        &[
            "runtime_15_foundation_guards_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/root_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/root_statuses.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/root_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/root_inventory.rs",
            "runtime_15_foundation_guards_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
];
