[package]
name = "zircon_plugin_native_window_hosting_editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Native window hosting editor plugin package for Zircon."

[features]
default = ["editor"]
declaration = ["zircon_plugin_sdk/declaration"]
editor = [
    "declaration",
    "dep:zircon_editor",
    "dep:zircon_plugin_editor_support",
    "dep:zircon_runtime",
    "zircon_plugin_sdk/runtime",
]

[dependencies]
zircon_editor = { workspace = true, optional = true }
zircon_plugin_editor_support = { path = "../../editor_support", optional = true }
zircon_plugin_sdk = { workspace = true, default-features = false }
zircon_runtime = { workspace = true, optional = true }
