type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 D10 animation/physics bridge call migration",
        &[
            "d10_animation_physics_bridge_call_static_passed_cargo_deferred",
            "zircon_runtime/src/core/framework/physics/query_interface.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
            "zircon_plugins/plugin_sdk/src/registration.rs",
            "zircon_plugins/physics/runtime/src/plugin.rs",
            "zircon_plugins/animation/runtime/tests/runtime_physics_animation_tick_contract.rs",
            "zircon_plugins/animation/runtime/tests/runtime_physics_animation_tick_contract/runtime_helpers.rs",
            "physics.query.v1",
            "WeakBridge<dyn PhysicsQueryInterface>",
            "review_d10_animation_physics_tests_use_sdk_bridge_call",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D11 animation/physics TestRuntime fixture migration",
        &[
            "d11_animation_physics_test_runtime_fixture_static_passed_cargo_deferred",
            "zircon_plugins/animation/runtime/tests/runtime_physics_animation_tick_contract.rs",
            "zircon_plugins/animation/runtime/tests/runtime_physics_animation_tick_contract/animation_assets.rs",
            "zircon_plugins/animation/runtime/tests/runtime_physics_animation_tick_contract/runtime_helpers.rs",
            "zircon_plugins/animation/runtime/tests/runtime_physics_animation_tick_contract/target_resolution.rs",
            "zircon_plugin_sdk::TestRuntime",
            "TestRuntime::builder()",
            "runtime.tick_level_seconds(&level,",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d11_test_runtime_fixture.rs",
            "review_d11_animation_physics_tests_use_sdk_test_runtime_fixture",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D13 importer manifest parity guard",
        &[
            "d13_importer_manifest_parity_guard_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
            "zircon_plugins/plugin_sdk/src/manifest/tests.rs",
            "zircon_plugins/plugin_sdk/src/manifest/importer_runtime.rs",
            "zircon_plugins/plugin_sdk/src/lib.rs",
            "zircon_plugins/plugin_sdk/src/prelude.rs",
            "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
            "importer_runtime_manifest_builder_keeps_targets_platforms_modules_and_distribution_in_parity",
            "ImporterRuntimeManifestBuilder",
            "importer_runtime_supported_targets()",
            "importer_runtime_supported_platforms()",
            "NATIVE_ABI_VERSION_V3",
            "NATIVE_DESCRIPTOR_SYMBOL_V3",
            "runtime_module_manifest()",
            "dist_module_manifest()",
            "build_package_manifest",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 P0/DX priority D13 parity sync",
        &[
            "review_priority_recommendation_d13_parity_sync_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "docs/plans/engine-code-structure-convention.md",
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            "review_priority_recommendation_tracks_current_remaining_work",
            "D13 importer manifest parity guard 已由 `d13_importer_manifest_parity_guard_static_passed_cargo_deferred` 闭合",
            "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
            "importer_runtime_manifest_builder_keeps_targets_platforms_modules_and_distribution_in_parity",
            "P0/DX priority recommendation D13 manifest parity sync",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D7 core workspace dependency inheritance guard",
        &[
            "d7_core_workspace_dependency_inheritance_guard_static_passed_cargo_deferred",
            "tools/plugin_structure_audits/skeleton.py",
            "tools/audit_plugin_structure.py",
            "zircon_plugins/Cargo.toml",
            "zircon_plugins/Cargo.lock",
            "core_workspace_dependency_status = core-workspace-deps-clean",
            "core_workspace_dependency_count = 117",
            "core_workspace_dependency_violation_count = 0",
            "cargo metadata --manifest-path zircon_plugins/Cargo.toml --locked --offline",
            "zircon_runtime = { workspace = true }",
            "zircon_editor = { workspace = true }",
            "zircon_runtime_interface = { workspace = true }",
            "插件间 path 依赖仍归后续切片",
        ],
    ),
];
