type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 F8 RuntimePluginDescriptor status mirror cleanup",
        &[
            "runtime_15_runtime_plugin_descriptor_status_mirror_cleanup_static_passed_cargo_deferred",
            "f8_f9_f10_runtime_surface_top_row_closed_status_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
            "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
            "RuntimePluginDescriptor private fields 15/15",
            "RuntimePluginDescriptor public-field convergence complete",
            "RuntimePluginDescriptor::new retired",
        ],
    ),
    (
        "Runtime 15 M3 D8 runtime registration builder original evidence paths",
        &[
            "d8_runtime_registration_builder_original_paths_static_passed_cargo_deferred",
            "zircon_plugins/plugin_sdk/src/registration.rs",
            "zircon_plugins/animation/runtime/src/plugin.rs",
            "zircon_plugins/physics/runtime/src/plugin.rs",
            "zircon_plugins/net/runtime/src/plugin.rs",
            "RuntimePluginRegistrationBuilder",
            "RuntimePluginModuleRegistration::event",
            "runtime_registration_builder_violation_count = 0",
            "m3_t2_runtime_registration_builder_status = runtime-registration-builder-clean",
            "review_d8_runtime_registration_builder_original_evidence_paths_use_sdk_builder",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D6 RuntimePluginId open string-newtype review sync",
        &[
            "d6_runtime_plugin_id_open_string_newtype_review_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d6_runtime_plugin_id.rs",
            "review_d6_runtime_plugin_id_accepts_external_string_keys",
            "zircon_runtime/src/builtin/runtime_modules/ids/plugin_id.rs",
            "RuntimePluginId",
            "开放 string-newtype",
            "runtime_plugin_id_accepts_external_keys_without_core_variant",
            "第三方合法 key 不需 core enum 分支",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D9 editor/runtime mirror consumer guard",
        &[
            "d9_editor_runtime_mirror_consumers_static_passed_cargo_deferred",
            "zircon_plugins/animation/editor/src/plugin.rs",
            "zircon_plugins/physics/editor/src/plugin.rs",
            "zircon_plugins/net/editor/src/plugin.rs",
            "EditorPluginDeclaration::mirrors_runtime_manifest",
            "mirrored_runtime_package_id()",
            "editor_runtime_mirror_violations = 0",
            "d9_editor_runtime_mirror_gate_status = editor-runtime-mirror-clean",
            "review_d9_editor_runtime_mirror_consumers_use_sdk_declaration",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D5 editor authoring macro consumer guard",
        &[
            "d5_editor_authoring_macro_consumers_static_passed_cargo_deferred",
            "zircon_plugins/plugin_sdk/src/editor.rs",
            "zircon_plugins/animation/editor/src/plugin.rs",
            "zircon_plugins/physics/editor/src/plugin.rs",
            "zircon_plugins/net/editor/src/plugin.rs",
            "zircon_plugin_sdk::authoring_plugin!",
            "mirrors_runtime_manifest:",
            "register_animation_authoring_extensions",
            "register_physics_authoring_extensions",
            "register_net_editor_extensions",
            "review_d5_editor_authoring_plugins_use_sdk_macro",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D12 runtime helper export macro review sync",
        &[
            "d12_runtime_export_macro_review_synced_static_passed_cargo_deferred",
            "plugins_12_runtime_export_macro_rollout_check_passed",
            "zircon_plugins/plugin_sdk/src/runtime_exports.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d12_runtime_exports.rs",
            "zircon_plugin_sdk::runtime_plugin_exports!",
            "15 个 first-party trait-backed runtime roots",
            "review_d12_runtime_helper_exports_use_sdk_macro",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D1 capability single-source review sync",
        &[
            "d1_capability_single_source_review_synced_static_passed_cargo_deferred",
            "plugins_12_runtime_capability_single_source_guard_passed",
            "plugins_12_capability_single_source_conformance",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source.rs",
            "review_d1_plugin_capabilities_use_single_source_and_sdk_builder_mirror",
            "zircon_plugins/plugin_sdk/src/manifest/feature_bundle_builder.rs",
            "PluginFeatureBundleBuilder",
            "15 个 trait-backed first-party runtime roots",
            "m4_runtime_capability_gate_status = runtime-capability-single-source-clean",
            "capability_source_mismatches = 0",
            "m4_t2_builder_mirror_gate_status = sdk-builder-mirror-clean",
            "sdk_builder_mirror_violations = 0",
            "cargo deferred",
        ],
    ),
];
