[package]
name = "zircon_plugin_timeline_sequence_editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Timeline sequence editor plugin package for Zircon."

[dependencies]
zircon_editor = { workspace = true }
zircon_plugin_editor_support = { path = "../../editor_support" }
zircon_plugin_sdk = { workspace = true }
zircon_runtime = { workspace = true }
zircon_runtime_interface = { workspace = true }
