use super::super::{assert_contains_all, sources::OwnerBudgetSources};

pub(super) fn assert_owner_budget_source_inventory(sources: &OwnerBudgetSources) {
    assert_contains_all(
        "performance hotpath source inventory",
        sources.source_inventory,
        &[
            "RUNTIME_07_TEST_FILES = (",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/artifact_render_diagnostics.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/hotspot_inventory.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/owner_budget.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/scene_project.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/submit_context.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/artifact_render_diagnostics.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/hotspot_inventory.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/owner_budget.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/root.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/scene_project.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/submit_context.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/source_inventory.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/sources.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/sources/load.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/split_layout.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/parent_route.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/split_route.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/support_routes.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/source_inventory.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/status_docs.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/status_docs.rs",
            "zircon_runtime/src/tests/runtime_absorption/performance_hotspots/owner_budget/mirror_docs.rs",
        ],
    );
    assert_contains_all(
        "owner-budget source inventory child",
        sources.owner_budget_source_inventory,
        &[
            "assert_performance_hotpath_source_inventory",
            "RUNTIME_07_TEST_FILES = (",
            "owner_budget/child_routes/artifact_render_diagnostics.rs",
            "owner_budget/child_routes/hotspot_inventory.rs",
            "owner_budget/child_routes/owner_budget.rs",
            "owner_budget/child_routes/scene_project.rs",
            "owner_budget/child_routes/submit_context.rs",
            "owner_budget/line_budgets/artifact_render_diagnostics.rs",
            "owner_budget/line_budgets/hotspot_inventory.rs",
            "owner_budget/line_budgets/owner_budget.rs",
            "owner_budget/line_budgets/root.rs",
            "owner_budget/line_budgets/scene_project.rs",
            "owner_budget/line_budgets/submit_context.rs",
            "owner_budget/sources/load.rs",
            "owner_budget/split_layout/route.rs",
            "owner_budget/split_layout/route/parent_route.rs",
            "owner_budget/split_layout/route/split_route.rs",
            "owner_budget/split_layout/route/support_routes.rs",
            "owner_budget/split_layout/source_inventory.rs",
            "owner_budget/split_layout/status_docs.rs",
        ],
    );
    assert_contains_all(
        "owner-budget mirror-docs source inventory child",
        sources.owner_budget_mirror_docs_source_inventory,
        &[
            "assert_source_inventory_anchors",
            "RUNTIME_07_TEST_FILES = (",
            "owner_budget/child_routes/artifact_render_diagnostics.rs",
            "owner_budget/child_routes/hotspot_inventory.rs",
            "owner_budget/child_routes/owner_budget.rs",
            "owner_budget/child_routes/scene_project.rs",
            "owner_budget/child_routes/submit_context.rs",
            "owner_budget/line_budgets/artifact_render_diagnostics.rs",
            "owner_budget/line_budgets/hotspot_inventory.rs",
            "owner_budget/line_budgets/owner_budget.rs",
            "owner_budget/line_budgets/root.rs",
            "owner_budget/line_budgets/scene_project.rs",
            "owner_budget/line_budgets/submit_context.rs",
            "owner_budget/sources/load.rs",
            "owner_budget/split_layout/route.rs",
            "owner_budget/split_layout/route/parent_route.rs",
            "owner_budget/split_layout/route/split_route.rs",
            "owner_budget/split_layout/route/support_routes.rs",
            "owner_budget/split_layout/source_inventory.rs",
            "owner_budget/split_layout/status_docs.rs",
        ],
    );
}

pub(super) fn assert_owner_budget_split_budgets(sources: &OwnerBudgetSources) {
    for (path, source) in [
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget.rs",
            sources.owner_budget,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes.rs",
            sources.owner_budget_child_routes,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/artifact_render_diagnostics.rs",
            sources.owner_budget_child_routes_artifact_render_diagnostics,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/hotspot_inventory.rs",
            sources.owner_budget_child_routes_hotspot_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/owner_budget.rs",
            sources.owner_budget_child_routes_owner_budget,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/scene_project.rs",
            sources.owner_budget_child_routes_scene_project,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/child_routes/submit_context.rs",
            sources.owner_budget_child_routes_submit_context,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets.rs",
            sources.owner_budget_line_budgets,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/artifact_render_diagnostics.rs",
            sources.owner_budget_line_budgets_artifact_render_diagnostics,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/hotspot_inventory.rs",
            sources.owner_budget_line_budgets_hotspot_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/owner_budget.rs",
            sources.owner_budget_line_budgets_owner_budget,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/root.rs",
            sources.owner_budget_line_budgets_root,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/scene_project.rs",
            sources.owner_budget_line_budgets_scene_project,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/line_budgets/submit_context.rs",
            sources.owner_budget_line_budgets_submit_context,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/mirror_docs.rs",
            sources.owner_budget_mirror_docs,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/parent_routes.rs",
            sources.owner_budget_parent_routes,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/source_inventory.rs",
            sources.owner_budget_source_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/sources.rs",
            sources.owner_budget_sources,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/sources/load.rs",
            sources.owner_budget_sources_load,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout.rs",
            sources.owner_budget_split_layout,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route.rs",
            sources.owner_budget_split_layout_route,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/parent_route.rs",
            sources.owner_budget_split_layout_route_parent_route,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/split_route.rs",
            sources.owner_budget_split_layout_route_split_route,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/route/support_routes.rs",
            sources.owner_budget_split_layout_route_support_routes,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/source_inventory.rs",
            sources.owner_budget_split_layout_source_inventory,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/split_layout/status_docs.rs",
            sources.owner_budget_split_layout_status_docs,
        ),
        (
            "tests/runtime_absorption/performance_hotspots/owner_budget/status_docs.rs",
            sources.owner_budget_status_docs,
        ),
    ] {
        let line_count = source.lines().count();
        assert!(
            line_count < 260,
            "{path} should stay below the focused owner-budget split guard budget; got {line_count} lines"
        );
    }
}
