pub(in super::super::super) const STATUS_REVIEW_PLUGIN_IMPORTER_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/plugin_importer_maps.rs";
pub(in super::super::super) const STATUS_REVIEW_TOP_ROW_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/top_row_review_maps.rs";
pub(in super::super::super) const STATUS_NAMING_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/naming_guard_maps.rs";
pub(in super::super::super) const STATUS_SUPPORT_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps.rs";
pub(in super::super::super) const STATUS_SUPPORT_ROW_DATA_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/row_data_maps.rs";
pub(in super::super::super) const STATUS_SUPPORT_PLAN_DOC_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/plan_doc_support_maps.rs";

pub(in super::super::super) const DATE_REVIEW_PLUGIN_IMPORTER_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/plugin_importer_maps.rs";
pub(in super::super::super) const DATE_REVIEW_TOP_ROW_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/top_row_review_maps.rs";
pub(in super::super::super) const DATE_NAMING_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/naming_guard_maps.rs";
pub(in super::super::super) const DATE_SUPPORT_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps.rs";
pub(in super::super::super) const DATE_SUPPORT_ROW_DATA_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps/row_data_maps.rs";
pub(in super::super::super) const DATE_SUPPORT_PLAN_DOC_CHILD: &str = "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps/plan_doc_support_maps.rs";
