pub(super) const STATUS_DOC_MAP_ANCHORS: &[&str] = &[
    "Runtime 15 M3 code review findings status-doc guard child-owner split",
    "runtime_15_code_review_findings_status_docs_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc status-mirror child-owner split",
    "runtime_15_code_review_findings_status_docs_status_mirror_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc source anchors child-owner split",
    "runtime_15_code_review_findings_status_docs_source_anchors_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc source anchors folder-backed split",
    "runtime_15_code_review_findings_status_docs_source_anchors_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-row source child-tree sync",
    "runtime_15_code_review_findings_status_row_source_child_tree_sync_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc status anchors child-owner split",
    "runtime_15_code_review_findings_status_docs_status_anchors_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc status anchors folder-backed split",
    "runtime_15_code_review_findings_status_docs_status_anchors_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc status anchor guard folder-backed split",
    "runtime_15_code_review_findings_status_docs_status_anchor_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc status-anchor child-ownership child split",
    "runtime_15_code_review_findings_status_docs_status_anchor_child_ownership_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc child-anchor list child split",
    "runtime_15_code_review_findings_status_docs_child_anchor_list_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings status-doc root inventory child split",
    "runtime_15_code_review_findings_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings folder-backed summary child-owner split",
    "runtime_15_code_review_findings_folder_backed_summary_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings folder-backed summary guard folder-backed split",
    "runtime_15_code_review_findings_folder_backed_summary_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings source inventory child-owner split",
    "runtime_15_code_review_findings_source_inventory_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings source inventory status-mirror child-owner split",
    "runtime_15_code_review_findings_source_inventory_status_mirror_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings direct assertions child-owner split",
    "runtime_15_code_review_findings_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings direct assertions guard folder-backed split",
    "runtime_15_code_review_findings_direct_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings F12 direct assertions child-owner split",
    "runtime_15_code_review_findings_f12_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings F8 direct assertions child-owner split",
    "runtime_15_code_review_findings_f8_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings P0 direct assertions child-owner split",
    "runtime_15_code_review_findings_p0_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings root-parent direct assertions child-owner split",
    "runtime_15_code_review_findings_root_parent_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings render direct assertions child-owner split",
    "runtime_15_code_review_findings_render_direct_assertions_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings structure guard folder-backed summary child-owner split",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings structure guard folder-backed summary guard folder-backed split",
    "runtime_15_code_review_findings_structure_guard_folder_backed_summary_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings structure guard typed-error child-owner split",
    "runtime_15_code_review_findings_structure_guard_typed_error_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure assertions guard folder-backed split",
    "runtime_15_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure status-doc guard folder-backed split",
    "runtime_15_typed_error_structure_status_docs_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 plugin-importer DX structure assertions guard child-owner split",
    "runtime_15_plugin_importer_dx_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 plugin-importer DX structure assertions guard folder-backed split",
    "runtime_15_plugin_importer_dx_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 plugin-importer D13 SDK structure assertions guard child-owner split",
    "runtime_15_plugin_importer_d13_sdk_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 plugin-importer D13 SDK parent-mount guard child split",
    "runtime_15_plugin_importer_d13_sdk_parent_mounts_guard_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure assertions guard child-owner split",
    "runtime_15_typed_error_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
    "2026-07-05",
    "2026-07-04",
    "2026-07-02",
    "2026-06-30",
];

#[test]
fn runtime_15_code_review_findings_status_docs_status_map_anchors_are_child_owned() {
    assert!(STATUS_DOC_MAP_ANCHORS.contains(
        &"runtime_15_code_review_findings_status_docs_status_anchors_child_owner_split_static_passed_cargo_deferred"
    ));
}
