mod authoring;
mod capability;
mod plugin;

pub use authoring::{
    NET_AUTHORING_SURFACES, NET_AUTHORING_VIEW_ID, NET_DIAGNOSTICS_VIEW_ID, NET_DRAWER_ID,
    NET_LISTENER_CONFIG_OPERATION, NET_REPLICATION_SCHEMA_ASSET_KIND,
    NET_REPLICATION_SCHEMA_COMPILE_OPERATION, NET_REPLICATION_SCHEMA_CREATE_OPERATION,
    NET_REPLICATION_SCHEMA_OPEN_OPERATION, NET_REPLICATION_SCHEMA_PALETTE_ID,
    NET_REPLICATION_SCHEMA_TEMPLATE_ID, NET_REPLICATION_SCHEMA_VALIDATE_OPERATION,
    NET_ROUTE_CONFIG_OPERATION, NET_TEMPLATE_ID,
};
pub use capability::{EDITOR_CAPABILITIES, NET_AUTHORING_CAPABILITY, PLUGIN_ID};
pub use plugin::{
    editor_capabilities, editor_host_contract_marker, editor_plugin, editor_plugin_descriptor,
    package_manifest, plugin_registration, NetEditorPlugin,
};

#[cfg(test)]
mod tests;
