use super::super::super::super::root_paths::{
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_OWNERSHIP_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SOURCES_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_BUDGETS_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_CHILD_INVENTORY_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_PARENT_BACKFLOW_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_PARENT_MOUNTS_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_SOURCES_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_SPLIT_LAYOUT_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_STATUS_SYNC_CHILD,
};
use super::super::super::super::status_slices::{
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_GUARD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_DATE,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_ID,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_DATE,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_DATE,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_GUARD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_ID,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_NAME,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_ID,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_NAME,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_DATE,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_ID,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_NAME,
    TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_NAME,
};

pub(in super::super) fn assert_typed_error_status_doc_paths_status_current_status_is_current() {
    let anchors = [
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_OWNERSHIP_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_STATUS_SYNC_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SOURCES_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_GUARD,
        "Cargo gate deferred",
    ];

    assert_documents_and_maps(
        "typed-error status-doc paths status-current split",
        &anchors,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_DATE,
    );
}

pub(in super::super) fn assert_typed_error_status_doc_paths_status_current_split_layout_status_is_current(
) {
    let anchors = [
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_BUDGETS_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_CHILD_INVENTORY_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_PARENT_BACKFLOW_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_PARENT_MOUNTS_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD,
        "Cargo gate deferred",
    ];

    assert_documents_and_maps(
        "typed-error status-doc paths status-current split-layout split",
        &anchors,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_DATE,
    );
}

pub(in super::super) fn assert_typed_error_status_doc_paths_status_current_split_layout_guard_status_is_current(
) {
    let anchors = [
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_BUDGETS_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_CHILD_INVENTORY_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_PARENT_BACKFLOW_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_PARENT_MOUNTS_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_SOURCES_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_SPLIT_LAYOUT_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_GUARD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_GUARD,
        "Cargo gate deferred",
    ];

    assert_documents_and_maps(
        "typed-error status-doc paths status-current split-layout guard split",
        &anchors,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_GUARD_DATE,
    );
    super::status_documents::assert_frameworks_contain("Frameworks 02 plan", &anchors);
}

pub(super) fn assert_typed_error_status_doc_paths_status_current_split_layout_status_mirrors_guard_status_is_current(
) {
    let anchors = [
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD,
        "Cargo gate deferred",
    ];

    assert_documents_and_maps(
        "typed-error status-doc paths status-current split-layout status mirrors guard folder-backed split",
        &anchors,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_STATUS_CURRENT_SPLIT_LAYOUT_STATUS_MIRRORS_GUARD_DATE,
    );
    super::status_documents::assert_frameworks_contain("Frameworks 02 plan", &anchors);
}

fn assert_documents_and_maps(
    label: &str,
    anchors: &[&str],
    split_name: &str,
    split_id: &str,
    split_date: &str,
) {
    super::status_documents::assert_status_documents_contain(label, anchors);
    super::status_maps::assert_status_maps_contain(label, split_name, split_id, split_date);
}
