use super::ExpectedStatusOutputSlice;

#[path = "m3/asset_budget_tests.rs"]
mod asset_budget_tests;
#[path = "m3/foundation_guards.rs"]
mod foundation_guards;
#[path = "m3/lock_poison_status.rs"]
mod lock_poison_status;
#[path = "m3/module_convention_status.rs"]
mod module_convention_status;
#[path = "m3/production_guard_support.rs"]
mod production_guard_support;
#[path = "m3/review_guard_splits.rs"]
mod review_guard_splits;
#[path = "m3/review_status_sync.rs"]
mod review_status_sync;
#[path = "m3/scene_script_tests.rs"]
mod scene_script_tests;
#[path = "m3/status_support.rs"]
mod status_support;
#[path = "m3/ui_tests_first.rs"]
mod ui_tests_first;
#[path = "m3/ui_tests_second.rs"]
mod ui_tests_second;

pub(super) const FOUNDATION_GUARD_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    foundation_guards::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    foundation_guards::RUNTIME_STRUCTURE_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const FOUNDATION_GUARD_PLUGIN_IMPORTER_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    foundation_guards::PLUGIN_IMPORTER_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const FOUNDATION_GUARD_PLUGIN_IMPORTER_MIGRATIONS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    foundation_guards::PLUGIN_IMPORTER_MIGRATIONS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const FOUNDATION_GUARD_RUNTIME_ABSORPTION_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    foundation_guards::RUNTIME_ABSORPTION_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const FOUNDATION_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = foundation_guards::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const LOCK_POISON_STATUS_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    lock_poison_status::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const LOCK_POISON_STATUS_POLICY_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = lock_poison_status::POLICY_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const LOCK_POISON_STATUS_CORE_RUNTIME_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    lock_poison_status::CORE_RUNTIME_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const LOCK_POISON_STATUS_RUNTIME_SERVICES_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    lock_poison_status::RUNTIME_SERVICES_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const LOCK_POISON_STATUS_RESOURCE_RENDER_INPUT_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    lock_poison_status::RESOURCE_RENDER_INPUT_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const LOCK_POISON_STATUS_SCRIPT_VM_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    lock_poison_status::SCRIPT_VM_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const LOCK_POISON_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = lock_poison_status::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const MODULE_CONVENTION_STATUS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = module_convention_status::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_STATUS_SYNC_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    review_status_sync::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = review_guard_splits::CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_FOLDER_BACKED_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_FOLDER_BACKED_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_CODE_REVIEW_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = review_guard_splits::TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_TYPED_ERROR_RUNTIME_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::TYPED_ERROR_RUNTIME_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const REVIEW_GUARD_TYPED_ERROR_ASSET_SHADER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::TYPED_ERROR_ASSET_SHADER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const UI_TESTS_FIRST_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    ui_tests_first::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const ASSET_BUDGET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    asset_budget_tests::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const ASSET_BUDGET_ASSET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = asset_budget_tests::ASSET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const ASSET_BUDGET_BUDGET_RENDER_UI_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    asset_budget_tests::BUDGET_RENDER_UI_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const ASSET_BUDGET_NAMING_CORE_ASSET_DYNAMIC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    asset_budget_tests::NAMING_CORE_ASSET_DYNAMIC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const ASSET_BUDGET_NAMING_GRAPHICS_MISC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    asset_budget_tests::NAMING_GRAPHICS_MISC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const ASSET_BUDGET_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = asset_budget_tests::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const SCENE_SCRIPT_TESTS_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    scene_script_tests::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const SCENE_SCRIPT_TESTS_SCRIPT_VM_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    scene_script_tests::SCRIPT_VM_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    scene_script_tests::PLUGIN_EXTENSION_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const SCENE_SCRIPT_TESTS_SCRIPT_VM_GAMEPLAY_SHADER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    scene_script_tests::SCRIPT_VM_GAMEPLAY_SHADER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const SCENE_SCRIPT_TESTS_SCENE_ECS_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    scene_script_tests::SCENE_ECS_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const SCENE_SCRIPT_TESTS_SCENE_ASSET_WORLD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    scene_script_tests::SCENE_ASSET_WORLD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const SCENE_SCRIPT_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = scene_script_tests::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_ROW_DATA_AND_BUDGET_TEST_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::ROW_DATA_AND_BUDGET_TEST_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_ROW_DATA_AND_BUDGET_RUNTIME_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::ROW_DATA_AND_BUDGET_RUNTIME_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_ROW_DATA_AND_BUDGET_HUB_EDITOR_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::ROW_DATA_AND_BUDGET_HUB_EDITOR_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_ROW_DATA_AND_BUDGET_RENDER_SHADER_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::ROW_DATA_AND_BUDGET_RENDER_SHADER_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_ROW_DATA_AND_BUDGET_M3_M4_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::ROW_DATA_AND_BUDGET_M3_M4_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_EXPECTED_SLICE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::EXPECTED_SLICE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = status_support::PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::PRIORITY_PLAN_DOCS_OWNER_GUARDS_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support::PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const UI_TESTS_SECOND_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    ui_tests_second::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::MODULE_LAYOUT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::REVIEW_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_LOCK_POISON_SCENE_SCRIPT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_LOCK_POISON_SCENE_SCRIPT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_ASSET_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_ASSET_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRODUCTION_GUARD_SUPPORT_EXPECTED_SLICE_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::EXPECTED_SLICE_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
