//! 代码审查回归护栏核对已迁移接口、错误边界、插件入口及镜像状态。集中挂载下级测试；所有行为断言留在被挂载模块。
mod animation_resource;
mod asset_loaders;
mod asset_records;
mod diagnostics;
mod dynamic_api;
mod export_cli;
mod native_plugin_loader;
mod scene_world;
mod script_host;
mod shader_prewarm_cli;
mod ui_asset_documents;
mod ui_input;
mod ui_template_resource;
