[package]
name = "zircon_plugin_rendering_contact_shadow_editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zircon_editor = { workspace = true }
zircon_plugin_rendering_contact_shadow_runtime = { path = "../runtime" }
zircon_runtime = { workspace = true }
