use super::*;

pub(super) const TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_CHILDREN: &[(&str, &str, &str)] =
    &[
        (
            "parent_paths",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_PARENT_PATHS_CHILD,
            "TYPED_ERROR_PARENT_PATHS",
        ),
        (
            "guard_names",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_GUARD_NAMES_CHILD,
            "PARENT_BACKFLOW_GUARDS",
        ),
        (
            "guard_body",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_GUARD_BODY_CHILD,
            "assert_typed_error_parent_backflow_guards_are_absent",
        ),
        (
            "metadata",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_METADATA_CHILD,
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_CHILD_SPLIT,
        ),
        (
            "child_inventory",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_CHILD_INVENTORY_CHILD,
            "TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_CHILDREN",
        ),
        (
            "sources",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_SOURCES_CHILD,
            "typed_error_parent_backflow_child_sources",
        ),
        (
            "child_ownership",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_CHILD_OWNERSHIP_CHILD,
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_CHILD_OWNERSHIP_GUARD,
        ),
        (
            "status_current",
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_STATUS_CURRENT_CHILD,
            TYPED_ERROR_MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_STATUS_GUARD,
        ),
    ];
