from __future__ import annotations


SOURCE_FILES = (
    "zircon_runtime_interface/src/buffer.rs",
    "zircon_runtime_interface/src/handles.rs",
    "zircon_runtime_interface/src/runtime_api/abi/api_table.rs",
    "zircon_runtime_interface/src/runtime_api/host/host_requests.rs",
    "zircon_runtime_interface/src/runtime_api/frame/viewport_pick.rs",
    "zircon_runtime_interface/src/runtime_api/session/operation.rs",
    "zircon_runtime_interface/src/runtime_api/session/plugin_event_mirror.rs",
    "zircon_runtime_interface/src/world_sync/query.rs",
    "zircon_runtime_interface/src/world_sync/watch.rs",
    "zircon_runtime_interface/src/world_sync/invalidation.rs",
    "zircon_runtime_interface/src/plugin_api.rs",
    "zircon_runtime_interface/src/profiling.rs",
    "zircon_runtime_interface/src/tests/abi_safety_contracts.rs",
    "zircon_runtime_interface/src/tests/contracts.rs",
    "zircon_runtime_interface/src/tests/runtime_owned_result.rs",
    "zircon_runtime/src/dynamic_api/exports.rs",
    "zircon_runtime/src/dynamic_api/session.rs",
    "zircon_runtime/src/dynamic_api/session/construction.rs",
    "zircon_runtime/src/dynamic_api/session/ffi.rs",
    "zircon_runtime/src/dynamic_api/session/world_sync.rs",
    "zircon_runtime/src/dynamic_api/session/viewport_pick.rs",
    "zircon_runtime/src/dynamic_api/session/registry/mod.rs",
    "zircon_runtime/src/dynamic_api/session/linked_session.rs",
    "zircon_runtime/src/dynamic_api/session/state.rs",
    "zircon_runtime/src/dynamic_api/session/profile.rs",
    "zircon_runtime/src/dynamic_api/session/diagnostics.rs",
    "zircon_runtime/src/dynamic_api/session/event_mirror.rs",
    "zircon_runtime/src/dynamic_api/session/events.rs",
    "zircon_runtime/src/dynamic_api/session/host_requests.rs",
    "zircon_runtime/src/dynamic_api/session/linked_plugins.rs",
    "zircon_runtime/src/dynamic_api/session/operation.rs",
    "zircon_runtime/src/dynamic_api/session/registry/allocation_registry.rs",
    "zircon_runtime/src/dynamic_api/tests/api_table.rs",
    "zircon_runtime/src/dynamic_api/tests/host_request_payloads.rs",
    "zircon_runtime/src/dynamic_api/tests/host_requests.rs",
    "zircon_runtime/src/dynamic_api/tests/linked_plugins.rs",
    "zircon_runtime/src/dynamic_api/tests/profile_control.rs",
    "zircon_runtime/src/dynamic_api/tests/operation.rs",
    "zircon_runtime/src/dynamic_api/tests/session_lifecycle.rs",
    "zircon_runtime/src/dynamic_api/tests/session_entry_points.rs",
    "zircon_runtime/src/dynamic_api/tests/session_profiles.rs",
    "zircon_runtime/src/dynamic_api/tests/viewport_pick.rs",
    "zircon_runtime/src/core/framework/render/viewport_pick.rs",
    "zircon_runtime/tests/runtime_owned_result_v8.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/shared.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/headless_profiles.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/event_split.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/test_owner_split.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/ffi_panic_boundary.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/ui_contract.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/v2_contract.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/runtime_diagnostics.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/mirror_docs.rs",
    "zircon_app/src/entry/runtime_library/loaded_runtime.rs",
    "zircon_app/src/entry/runtime_library/runtime_session.rs",
    "zircon_app/src/entry/runtime_library/runtime_session/operation.rs",
    "zircon_app/src/entry/runtime_library/tests.rs",
    "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
    "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
    "zircon_runtime_host/src/foreign_output/owned_buffer.rs",
    "zircon_runtime_host/src/foreign_output/state.rs",
    "zircon_editor/src/core/gateway/session/gateway.rs",
    "zircon_editor/src/core/gateway/session/output.rs",
    "zircon_editor/src/core/gateway/session/viewport_pick.rs",
    "zircon_editor/src/core/gateway/contract.rs",
    "zircon_editor/src/core/gateway/viewport_pick_route.rs",
)
EXPECTED_SOURCE_FILE_COUNT = 67

EXPECTED_FUNCTION_TABLES = (
    ("zircon_runtime_interface/src/runtime_api/abi/api_table.rs", "ZrHostApiV1", 4),
    ("zircon_runtime_interface/src/runtime_api/abi/api_table.rs", "ZrRuntimeApiV8", 28),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostApiV3", 7),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostApiV4", 7),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostEcsApiV1", 3),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostEcsApiV2", 3),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostAssetApiV1", 1),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostEventApiV1", 2),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostBridgeApiV1", 1),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrHostDiagnosticsApiV1", 2),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrPluginStateSnapshotApiV1", 4),
    ("zircon_runtime_interface/src/plugin_api.rs", "ZrPluginApiV1", 4),
)

RUNTIME_SESSION_OPERATIONS = (
    "create_session",
    "destroy_session",
    "release_allocation",
    "handle_event",
    "capture_frame",
    "capture_accessibility_tree",
    "bind_viewport_surface",
    "unbind_viewport_surface",
    "present_viewport",
    "submit_highlight_set",
    "profile_control",
    "tick_frame",
    "drain_host_requests",
    "subscribe_plugin_event",
    "unsubscribe_plugin_event",
    "drain_plugin_events",
    "submit_operation",
    "poll_operation",
    "harvest_operation",
    "query_world",
    "watch_world",
    "unwatch_world",
    "drain_world_invalidations",
    "request_viewport_pick",
    "poll_viewport_pick",
    "cancel_viewport_pick",
)
