from __future__ import annotations


EXPECTED_SOURCE_FILE_COUNT = 75
EXPECTED_TEST_FILE_COUNT = 10

RUNTIME_08_SOURCE_FILES = (
    "zircon_runtime/src/scene/ecs/archetype/mod.rs",
    "zircon_runtime/src/scene/ecs/archetype/id.rs",
    "zircon_runtime/src/scene/ecs/archetype/index.rs",
    "zircon_runtime/src/scene/ecs/archetype/record.rs",
    "zircon_runtime/src/scene/ecs/archetype/signature.rs",
    "zircon_runtime/src/scene/ecs/archetype/table/mod.rs",
    "zircon_runtime/src/scene/ecs/archetype/table/column.rs",
    "zircon_runtime/src/scene/ecs/archetype/table/error.rs",
    "zircon_runtime/src/scene/ecs/archetype/table/preflighted_row.rs",
    "zircon_runtime/src/scene/ecs/archetype/table/table.rs",
    "zircon_runtime/src/scene/ecs/archetype/table/taken_row.rs",
    "zircon_runtime/src/scene/ecs/bundle.rs",
    "zircon_runtime/src/scene/ecs/storage_type.rs",
    "zircon_runtime/src/scene/ecs/storage/component_storage/mod.rs",
    "zircon_runtime/src/scene/ecs/storage/component_storage/entry.rs",
    "zircon_runtime/src/scene/ecs/storage/component_storage/location.rs",
    "zircon_runtime/src/scene/ecs/storage/component_storage/sparse.rs",
    "zircon_runtime/src/scene/ecs/storage/component_storage/store.rs",
    "zircon_runtime/src/scene/ecs/storage/component_storage/component_results.rs",
    "zircon_runtime/src/scene/ecs/component/mod.rs",
    "zircon_runtime/src/scene/ecs/component/id.rs",
    "zircon_runtime/src/scene/ecs/component/marker.rs",
    "zircon_runtime/src/scene/ecs/component/registry.rs",
    "zircon_runtime/src/scene/ecs/entity/mod.rs",
    "zircon_runtime/src/scene/ecs/entity/despawned.rs",
    "zircon_runtime/src/scene/ecs/entity/error.rs",
    "zircon_runtime/src/scene/ecs/entity/internal.rs",
    "zircon_runtime/src/scene/ecs/entity/location.rs",
    "zircon_runtime/src/scene/ecs/entity/registry.rs",
    "zircon_runtime/src/scene/ecs/entity/slot.rs",
    "zircon_runtime/src/scene/ecs/entity/stable_location.rs",
    "zircon_runtime/src/scene/ecs/observer/mod.rs",
    "zircon_runtime/src/scene/ecs/observer/callbacks.rs",
    "zircon_runtime/src/scene/ecs/observer/entry.rs",
    "zircon_runtime/src/scene/ecs/observer/id.rs",
    "zircon_runtime/src/scene/ecs/observer/store.rs",
    "zircon_runtime/src/scene/ecs/observer/callback_registry.rs",
    "zircon_runtime/src/scene/ecs/commands/command.rs",
    "zircon_runtime/src/scene/ecs/commands/command_queue.rs",
    "zircon_runtime/src/scene/ecs/commands/commands/mod.rs",
    "zircon_runtime/src/scene/ecs/commands/commands/entity_commands.rs",
    "zircon_runtime/src/scene/ecs/commands/commands/facade.rs",
    "zircon_runtime/src/scene/ecs/commands/commands/param.rs",
    "zircon_runtime/src/scene/ecs/events/mod.rs",
    "zircon_runtime/src/scene/ecs/events/cursor.rs",
    "zircon_runtime/src/scene/ecs/events/id.rs",
    "zircon_runtime/src/scene/ecs/events/metrics.rs",
    "zircon_runtime/src/scene/ecs/events/queue.rs",
    "zircon_runtime/src/scene/ecs/events/store.rs",
    "zircon_runtime/src/scene/ecs/events/subscription.rs",
    "zircon_runtime/src/scene/ecs/messages/mod.rs",
    "zircon_runtime/src/scene/ecs/messages/cursor.rs",
    "zircon_runtime/src/scene/ecs/messages/id.rs",
    "zircon_runtime/src/scene/ecs/messages/queue.rs",
    "zircon_runtime/src/scene/ecs/messages/store.rs",
    "zircon_runtime/src/scene/ecs/resource/mod.rs",
    "zircon_runtime/src/scene/ecs/resource/id.rs",
    "zircon_runtime/src/core/framework/scene/resource.rs",
    "zircon_runtime/src/scene/ecs/resource/registry.rs",
    "zircon_runtime/src/scene/ecs/resource_store/mod.rs",
    "zircon_runtime/src/scene/ecs/resource_store/stored_resource.rs",
    "zircon_runtime/src/scene/ecs/resource_store/store.rs",
    "zircon_runtime/src/scene/ecs/change_detection/mod.rs",
    "zircon_runtime/src/scene/ecs/change_detection/change_tick.rs",
    "zircon_runtime/src/scene/ecs/change_detection/change_tick_window.rs",
    "zircon_runtime/src/scene/ecs/change_detection/component_ticks.rs",
    "zircon_runtime/src/scene/ecs/change_detection/stats.rs",
    "zircon_runtime/src/scene/ecs/change_detection/wrappers.rs",
    "zircon_runtime/src/scene/ecs/removal.rs",
    "zircon_runtime/src/scene/world/identity.rs",
    "zircon_runtime/src/scene/world/typed_api/component_row.rs",
    "zircon_runtime/src/scene/world/typed_api/projection_rebuild.rs",
    "zircon_runtime/src/scene/world/observers.rs",
    "zircon_runtime/src/scene/world/events.rs",
    "zircon_runtime/src/scene/world/messages.rs",
)

RUNTIME_08_TEST_FILES = (
    "zircon_runtime/src/scene/tests/ecs_identity_storage.rs",
    "zircon_runtime/src/scene/tests/ecs_observers_messages.rs",
    "zircon_runtime/src/scene/tests/ecs_commands.rs",
    "zircon_runtime/src/scene/tests/ecs_events_messages.rs",
    "zircon_runtime/src/scene/tests/ecs_change_detection.rs",
    "zircon_runtime/src/scene/tests/component_structure/runtime_08_owner_tree.rs",
    "zircon_runtime/src/tests/runtime_absorption/ecs_kernel_data.rs",
    "zircon_runtime/src/tests/runtime_absorption/ecs_kernel_data/inventory.rs",
    "zircon_runtime/src/tests/runtime_absorption/ecs_kernel_data/guard_coverage.rs",
    "zircon_runtime/src/tests/runtime_absorption/ecs_kernel_data/docs.rs",
)

MIRROR_DOCS_GUARD = (
    "runtime_08_ecs_kernel_data_mirror_docs_match_structure_audit_counts"
)
