from __future__ import annotations


INPUT_MOD_DECLARATIONS = (
    "mod module;",
    "pub mod prelude;",
    "mod runtime;",
    "pub use crate::core::framework::input::INPUT_MODULE_NAME;",
    "pub use crate::core::framework::input::{",
    "DefaultInputActionManager, DefaultInputManager, InputActionEvaluator, InputDriver,",
)
RUNTIME_MOD_DECLARATIONS = (
    "mod action_evaluator;",
    "mod default_input_action_manager;",
    "mod default_input_manager;",
    "mod event_buffer;",
    "mod input_driver;",
    "mod recording;",
    "mod input_state;",
)
EVENT_BUFFER_VISIBILITY_ANCHORS = (
    (
        "zircon_runtime/src/input/runtime/event_buffer/frame.rs",
        "pub(in crate::input::runtime) struct FrameEventBuffer",
    ),
    (
        "zircon_runtime/src/input/runtime/event_buffer/recorder.rs",
        "pub(in crate::input::runtime) struct InputEventRecorder",
    ),
)
FRAMEWORK_MOD_DECLARATIONS = (
    "mod button_input_state;",
    "mod cursor;",
    "mod event_retention;",
    "mod gamepad;",
    "mod input_action;",
    "mod input_action_context;",
    "mod input_action_manager;",
    "mod input_action_map;",
    "mod input_action_state;",
    "mod input_binding;",
    "mod input_event;",
    "mod input_frame_snapshot;",
    "mod input_manager;",
    "mod module_identity;",
    "pub use input_manager::InputManager;",
    "pub use module_identity::INPUT_MODULE_NAME;",
)
INPUT_PRELUDE_ANCHORS = (
    "pub use super::{",
    "DefaultInputManager",
    "InputActionManager",
    "InputEventRecordingStatus",
    "InputRecordingFrame",
    "INPUT_MODULE_NAME",
    "DEFAULT_INPUT_EVENT_RECORDING_CAPACITY",
)
CRATE_PRELUDE_ANCHORS = ("pub use crate::input::prelude::*;",)
INPUT_TEST_DECLARATIONS = (
    "mod action_axis_transitions;",
    "mod action_mapping;",
    "mod boundary;",
    "mod gamepad_bridge;",
    "mod input_manager;",
    "mod recording_replay;",
)
PUBLIC_SURFACE_ANCHORS = (
    "CursorGrabMode",
    "CursorHostRequest",
    "CursorPosition",
    "DefaultInputManager",
    "DefaultInputActionManager",
    "InputActionEvaluator",
    "InputActionManager",
    "InputAction",
    "InputActionContext",
    "InputBinding",
    "InputAxisBinding",
    "InputAxisDirection",
    "InputActionMap",
    "InputActionState",
    "InputConfig",
    "InputFrameSnapshot",
    "InputSnapshot",
    "GamepadConnectionInfo",
    "GamepadAxisInput",
    "GamepadAxisTransition",
    "GamepadRumbleRequest",
    "InputRecording",
    "InputRecordingFrame",
    "InputReplayCursor",
    "InputReplayFrameReport",
    "InputEventQueueStatus",
    "InputEventRecordingConfig",
    "InputEventRecordingStatus",
    "DEFAULT_INPUT_EVENT_RECORDING_CAPACITY",
    "INPUT_ACTION_MANAGER_NAME",
    "INPUT_MODULE_NAME",
)
ACTION_EVALUATOR_ANCHORS = (
    "pub struct InputActionEvaluator",
    "evaluate_with_consumed_buttons",
    "evaluate_with_consumed_input",
    "evaluate_with_active_contexts",
    "evaluate_with_active_contexts_and_consumed_buttons",
    "evaluate_with_active_contexts_and_consumed_input",
    "consumed_buttons.contains(button)",
    "consumed_axes.contains",
    "action_context_is_active",
    "InputActionState::from_sets_and_values",
    "binding_axis_consumed",
    "evaluate_binding_axes",
    "BindingAxisEvaluation",
    "dominant_action_value",
    "binding_index.indices_for_action",
    "FrameAxisIndex::from_frame",
)
AXIS_FRAME_INDEX_ANCHORS = (
    "pub(super) struct FrameAxisIndex",
    "GamepadAxisInput::new",
    "pub(super) fn value",
    "pub(super) fn transition",
    "source_visit_count",
)
GAMEPAD_ABI_ANCHORS = (
    "ZrRuntimeEventV1::gamepad_connection_with_ids",
    "ZrRuntimeEventV1::gamepad_button",
    "ZrRuntimeEventV1::gamepad_axis",
    "handle_gamepad_connection",
    "handle_gamepad_button",
    "handle_gamepad_axis",
    "InputEvent::GamepadConnection",
    "InputEvent::GamepadButton",
    "InputEvent::GamepadAxis",
)
CURSOR_HOST_REQUEST_ANCHORS = (
    "CursorHostRequest",
    "InputEvent::CursorHostRequest",
    "drain_cursor_host_requests",
    "runtime_cursor_host_request",
    "ZrRuntimeCursorHostRequestV1",
    "ZrRuntimeHostRequestV1::Cursor",
    "apply_runtime_cursor_host_request",
    "set_cursor_visible",
    "set_cursor_grab",
    "set_cursor_hittest",
    "set_cursor_position",
    "platform.cursor_options=supported:winit_window_options",
)
RUNTIME_12_GUARDS = (
    "runtime_12_input_stack_contracts_stay_documented_and_exported",
    "runtime_12_action_mapping_keeps_ui_filtered_evaluation_path",
    "runtime_12_gamepad_bridge_keeps_runtime_abi_path",
    "runtime_12_input_stack_mirror_docs_match_structure_audit_counts",
    "runtime_12_input_stack_cargo_pending_gate_stays_explicit_until_input_validation",
)
MIRROR_DOCS_GUARD = "runtime_12_input_stack_mirror_docs_match_structure_audit_counts"
RUNTIME_12_DOC_ANCHORS = (
    "Frame Input Contract",
    "input_frame_contract_static_passed_cargo_pending",
    "arbitration_judgement_documented_static_passed",
    "action_contract_static_passed_cargo_pending",
    "action_evaluator_static_passed_cargo_pending",
    "action_context_static_passed_cargo_pending",
    "action_axis_value_static_passed_cargo_deferred",
    "action_config_static_passed_cargo_deferred",
    "action_manager_registration_static_passed_cargo_deferred",
    "action_axis_consumption_static_passed_cargo_deferred",
    "input_recording_replay_static_passed_cargo_deferred",
    "cursor_host_request_static_passed_cargo_deferred",
    "gamepad_bridge_static_passed_cargo_pending",
    "missing_cursor_host_request_anchors = []",
    "missing_input_prelude_anchors = []",
    "missing_crate_prelude_anchors = []",
    "missing_axis_frame_index_anchors = []",
    "runtime_12_input_stack_cargo_pending_gate_stays_explicit_until_input_validation",
)
RUNTIME_12_TEST_ANCHORS = (
    "input_snapshot_just_pressed_is_true_for_exactly_one_frame",
    "frame_input_clears_after_level_tick_not_before",
    "action_map_resolves_chords_and_reports_just_activated",
    "rebinding_action_does_not_require_recompilation",
    "action_contexts_filter_gameplay_and_menu_maps_without_rebinding",
    "gamepad_axis_binding_reports_continuous_action_value",
    "consumed_gamepad_axis_does_not_activate_gameplay_action",
    "gamepad_axis_action_reports_deadzone_transition_edges",
    "input_config_builds_action_evaluator_from_serialized_action_map",
    "input_action_manager_resolves_from_runtime_module_descriptor",
    "gamepad_disconnect_clears_held_state_without_panic",
    "gamepad_host_bridge_uses_runtime_gamepad_abi_constructors",
    "input_recording_captures_drainable_event_records_by_frame",
    "input_replay_restores_frame_snapshots_in_recorded_order",
    "cursor_host_requests_are_frame_local_and_drainable",
    "pointer_event_streams_are_frame_bounded_at_common_polling_rates",
    "pointer_coalescing_preserves_button_and_touch_edges_in_order",
    "recording_is_opt_in_bounded_and_reports_discarded_raw_records",
    "input_recording_marks_a_bounded_capture_incomplete_after_discard",
    "action_evaluator_indexes_10_100_and_1000_bindings_once",
    "action_evaluator_indexes_axis_frame_sources_once_for_10_100_and_1000_bindings",
)
RUNTIME_12_BEHAVIOR_TEST_ANCHORS = RUNTIME_12_TEST_ANCHORS
CARGO_GATE_ANCHORS = (
    "cargo test -p zircon_runtime --lib input --locked -- --nocapture",
    "cargo test -p zircon_runtime --lib action_map --locked -- --nocapture",
    "cargo test -p zircon_runtime --lib gamepad --locked -- --nocapture",
    "cargo test -p zircon_app --locked",
)
