from __future__ import annotations


JOB_SYSTEM_REQUIRED_DECLARATIONS = (
    "mod bounded_stream_io;",
    "mod callback_dispatcher;",
    "mod diagnostic_observation;",
    "mod diagnostics;",
    "mod task_graph;",
    "mod job_handle;",
    "mod job_scheduler;",
    "mod parallel_for;",
    "mod pool;",
    "mod pools;",
    "mod report;",
    "mod retained_byte_budget;",
    "mod task_cancellation_policy;",
    "mod task_descriptor;",
    "mod task_id;",
    "mod task_pool_descriptor;",
    "mod task_pool_kind;",
    "mod task_state;",
    "mod task_status;",
    "mod thread_assignment;",
    "mod timer;",
)
JOB_SYSTEM_REQUIRED_PUBLIC_SURFACE = {
    "BoundedStreamIoLane": "BoundedStreamIoLane,",
    "BoundedStreamIoCapture": "BoundedStreamIoCapture,",
    "BoundedStreamIoLimits": "BoundedStreamIoLimits,",
    "BoundedStreamIoRecord": "BoundedStreamIoRecord,",
    "JobHandle": "pub use job_handle::JobHandle;",
    "JobScheduler": "pub use job_scheduler::JobScheduler;",
    "parallel_for": "pub use parallel_for::parallel_for;",
    "EngineTaskGraph": "EngineTaskGraph,",
    "EngineTaskGraphOptions": "EngineTaskGraphOptions,",
    "TaskGraphScope": "TaskGraphScope,",
    "TaskHandle": "TaskHandle,",
    "TaskGraphWorkerInventory": "TaskGraphWorkerInventory,",
    "TaskCancellationPolicy": "pub use task_cancellation_policy::TaskCancellationPolicy;",
    "TaskDescriptor": "pub use task_descriptor::TaskDescriptor;",
    "TaskId": "pub use task_id::TaskId;",
    "TaskPoolDescriptor": "pub use task_pool_descriptor::TaskPoolDescriptor;",
    "TaskPoolKind": "pub use task_pool_kind::TaskPoolKind;",
    "TaskState": "pub use task_state::TaskState;",
    "TaskStatus": "pub use task_status::TaskStatus;",
    "RetainedByteBudget": "RetainedByteBudget,",
    "RetainedByteLease": "RetainedByteLease,",
    "TaskDiagnosticSource": "TaskDiagnosticSource,",
    "TaskDiagnosticCursor": "TaskDiagnosticCursor,",
    "JobSchedulerReport": "JobSchedulerReport",
    "TASKS_SCHEDULED_DIAGNOSTIC": "TASKS_SCHEDULED_DIAGNOSTIC",
    "TASKS_COMPLETED_DIAGNOSTIC": "TASKS_COMPLETED_DIAGNOSTIC",
    "TASKS_DEPENDENCY_WAITING_DIAGNOSTIC": "TASKS_DEPENDENCY_WAITING_DIAGNOSTIC",
    "TASKS_QUEUED_DIAGNOSTIC": "TASKS_QUEUED_DIAGNOSTIC",
    "TASKS_ACTIVE_DIAGNOSTIC": "TASKS_ACTIVE_DIAGNOSTIC",
    "TASKS_QUEUE_WAIT_SAMPLES_DIAGNOSTIC": "TASKS_QUEUE_WAIT_SAMPLES_DIAGNOSTIC",
    "TASKS_QUEUE_WAIT_MS_DIAGNOSTIC": "TASKS_QUEUE_WAIT_MS_DIAGNOSTIC",
    "TASKS_PANICKED_DIAGNOSTIC": "TASKS_PANICKED_DIAGNOSTIC",
    "TASKS_CANCELLED_DIAGNOSTIC": "TASKS_CANCELLED_DIAGNOSTIC",
    "TASKS_DEPENDENCY_WAIT_MS_DIAGNOSTIC": "TASKS_DEPENDENCY_WAIT_MS_DIAGNOSTIC",
    "TASKS_EXPLICIT_WAIT_MS_DIAGNOSTIC": "TASKS_EXPLICIT_WAIT_MS_DIAGNOSTIC",
}
JOB_SYSTEM_FORBIDDEN_SCHEDULER_OWNER_SNIPPETS = (
    "impl Default for JobScheduler",
    "pub fn process_io(",
)
JOB_SYSTEM_FORBIDDEN_GRAPHICS_OWNER_SNIPPETS = (
    "TaskPool::new(",
    "TaskPool::try_new(",
    "TaskPools::process_default()",
    "EngineTaskGraph::try_new(",
    "pub fn new_with_plugin_render_extensions_and_solari(",
)
JOB_SYSTEM_FORBIDDEN_NAVIGATION_OWNER_SNIPPETS = (
    "TaskPool::new(",
    "TaskPool::try_new(",
    "TaskPools::process_default()",
    "EngineTaskGraph::try_new(",
)
JOB_SYSTEM_FORBIDDEN_NAVIGATION_MANAGER_SNIPPETS = (
    "impl Default for DefaultNavigationManager",
    "pub fn new() -> Self",
)
JOB_SYSTEM_REQUIRED_NAVIGATION_MANAGER_SNIPPETS = (
    "pub fn new(bake_pool: TaskPool) -> Self",
    "bake_pool,",
)
JOB_SYSTEM_REQUIRED_NAVIGATION_MODULE_SNIPPETS = (
    "ModuleDependencySpec::named(TASKS_MODULE_NAME)",
    "core.task_graph().worker_pool().clone()",
)
JOB_SYSTEM_FORBIDDEN_PLATFORM_OWNER_SNIPPETS = (
    "impl Default for PlatformDriver",
    "TaskPools::process_default()",
    "Self::default()",
)
JOB_SYSTEM_FORBIDDEN_PLATFORM_DEFAULT_CALL = "PlatformDriver::default()"
JOB_SYSTEM_REQUIRED_PLATFORM_DRIVER_SNIPPETS = (
    "pub fn with_preference_storage_backend(",
    "preference_io_pool: TaskPool",
    "Self::with_io_task_pool(preference_io_pool)",
)
JOB_SYSTEM_FORBIDDEN_PLATFORM_ADAPTER_OWNER_SNIPPETS = (
    "TaskPools::process_default()",
    "pub fn new(",
)
JOB_SYSTEM_REQUIRED_PLATFORM_ADAPTER_SNIPPETS = (
    "pub(crate) fn with_pool(",
    "pool: TaskPool",
    "JobScheduler::from_pool(pool)",
)
JOB_SYSTEM_REQUIRED_PLATFORM_ADAPTER_TEST_SNIPPETS = (
    "struct TestPreferencePersistenceAdapter",
    "adapter: PreferencePersistenceAdapter,\n    _io_pool: TaskPool,",
    "PreferencePersistenceAdapter::with_pool(",
    '.with_thread_name("preference-test-io")',
)
JOB_SYSTEM_REQUIRED_PLATFORM_MODULE_SNIPPETS = (
    "ModuleDependencySpec::named(TASKS_MODULE_NAME)",
    "PlatformDriver::with_io_task_pool(",
    "core.task_graph().worker_pool().clone()",
)
JOB_SYSTEM_REQUIRED_PLATFORM_APP_SNIPPETS = (
    "PlatformDriver::with_preference_storage_backend(",
    "core.task_graph().worker_pool().clone()",
)
JOB_SYSTEM_REQUIRED_PLATFORM_TEST_SUPPORT_SNIPPETS = (
    "pub(crate) fn platform_driver() -> TestPlatformDriver",
    "pub(crate) fn platform_manager() -> TestPlatformManager",
    ".with_worker_threads(1)",
    '.with_thread_name("platform-test-io")',
    "driver: Arc<PlatformDriver>,\n    _io_pool: TaskPool,",
    "manager: PlatformManager,\n    _io_pool: TaskPool,",
)
JOB_SYSTEM_API_SNIPPETS = {
    "bounded_stream_io/lane.rs": (
        "pub struct BoundedStreamIoLane",
        "pub fn try_new(",
        "pub fn reader_capacity(&self)",
        "pub fn capture(",
        "TaskCancellationPolicy::FinishOnShutdown",
        ".min(runtime.worker_pool().parallelism())",
    ),
    "bounded_stream_io/capture.rs": (
        "pub struct BoundedStreamIoCapture",
        "pub fn request_cancellation(&self)",
        "pub fn wait_until_terminal(&self",
        "pub fn drain(&self",
    ),
    "bounded_stream_io/state.rs": (
        "VecDeque<BoundedStreamIoRecord>",
        "queue_entry_capacity",
        "queue_byte_capacity",
        "dropped_records",
        "oldest_age",
    ),
    "bounded_stream_io/worker.rs": (
        "pub(super) fn run_reader(",
        "ReaderStartGate",
        "TaskCancellationToken",
        "ReaderTerminalGuard",
    ),
    "callback_dispatcher.rs": (
        "pub(super) struct TaskCallbackDispatcher",
        "pub(super) fn process_default()",
        "pub(super) fn dispatch(",
        "MAX_CALLBACKS_PER_RUN",
        "MAX_CONCURRENT_DISPATCH_RUNNERS",
    ),
    "task_graph/engine_task_graph.rs": (
        "pub struct EngineTaskGraph",
        "pub fn try_new",
        "pub fn shutdown(",
        "pub fn worker_inventory(&self)",
        "worker_pool: TaskPool",
        "EngineTaskGraphLifecycle",
    ),
    "task_graph/lease.rs": (
        "pub(super) struct TaskGraphClientLease",
        "AtomicUsize",
        "fetch_add",
        "fetch_sub",
    ),
    "task_graph/scope/cancellation.rs": (
        "pub struct TaskCancellationToken",
        "pub fn is_cancellation_requested",
        "pub fn acknowledge_cancellation",
    ),
    "task_graph/scope/scheduler_admission.rs": (
        "struct SchedulerTaskAdmission",
        "TaskPoolSubmission",
    ),
    "task_graph/scope.rs": (
        "pub struct TaskGraphScope",
        "pub fn close_admission",
        "pub fn schedule(",
        "pub fn schedule_after(",
        "pub fn submit(",
        "Result<TaskHandle",
        "dependencies: &[TaskHandle]",
        "wait_until_quiescent",
        "TaskIdAlreadyActive",
    ),
    "task_graph/task_handle.rs": (
        "pub struct TaskHandle",
        "pub fn descriptor(&self)",
        "pub fn status(&self)",
        "pub fn is_complete(&self)",
        "pub fn is_cancelled(&self)",
        "pub fn wait(&self)",
        "pub fn on_terminal",
        "pub fn request_cancellation(&self)",
        "pub(crate) fn schedule_detached",
        "pub(crate) fn completed",
        "completion: JobHandle",
    ),
    "task_cancellation_policy.rs": (
        "pub enum TaskCancellationPolicy",
        "CancelOnDrop",
        "DetachOnDrop",
        "FinishOnShutdown",
    ),
    "task_descriptor.rs": (
        "pub struct TaskDescriptor",
        "pub id: TaskId",
        "pub kind: TaskPoolKind",
        "pub cancellation_policy: TaskCancellationPolicy",
        "pub fn with_cancellation_policy",
    ),
    "task_id.rs": (
        "pub struct TaskId(u64)",
        "pub const fn new",
        "pub const fn raw",
    ),
    "task_pool_descriptor.rs": (
        "pub struct TaskPoolDescriptor",
        "pub fn with_worker_threads",
        "pub fn with_thread_name",
    ),
    "task_pool_kind.rs": (
        "pub enum TaskPoolKind",
        "pub const fn default_thread_name",
    ),
    "task_state.rs": (
        "pub enum TaskState",
        "pub const fn is_terminal",
    ),
    "task_status.rs": (
        "pub struct TaskStatus",
        "pub fn pending",
        "pub const fn is_terminal",
        "runtime_task_status_has_one_terminal_state_and_no_poll_clock",
    ),
    "diagnostic_observation/mod.rs": (
        "pub use batch::TaskDiagnosticBatch;",
        "pub use cursor::TaskDiagnosticCursor;",
        "pub use identity::TaskDiagnosticIdentity;",
        "pub use source::TaskDiagnosticSource;",
        "TASK_DIAGNOSTIC_RETENTION_CAPACITY: usize = 256",
        "TASK_DIAGNOSTIC_MAX_BATCH_ENTRIES: usize = 64",
    ),
    "diagnostic_observation/journal.rs": (
        "VecDeque<TaskDiagnosticObservation>",
        "dropped_count",
        "read_after(",
        "TASK_DIAGNOSTIC_RETENTION_CAPACITY",
    ),
    "job_scheduler.rs": (
        "pub fn schedule(&self",
        "pub fn schedule_after(",
        "schedule_after_with_submission_and_prelaunch_terminal",
        "pub fn wait_all(&self",
        "PendingScheduledJob",
        "record_started",
        "record_active_terminal",
        "record_active_cancelled",
        "JobExecutionOutcome",
        "run_detached_task",
        "catch_unwind",
        "complete_scheduled_task",
    ),
    "job_scheduler/tests.rs": (
        "detached_spawn_counts_panicked_tasks_as_completed",
    ),
    "job_scheduler/pending.rs": (
        "pub(super) struct PendingScheduledJob",
        "pub(super) struct PendingScheduledWork",
        "PrelaunchTerminalHook",
        "TaskPoolSubmission",
        "record_dependency_wait",
        "record_enqueued",
        "record_terminal_without_launch",
        "record_cancelled",
        "complete_scheduled_task",
    ),
    "pool.rs": (
        "pub(in crate::core::runtime) struct TaskPoolSubmission",
        "pub(super) fn try_acquire_submission",
        "fn try_acquire_continuation",
        "fn wait_until_submissions_quiescent",
        "active_submission_count",
        "impl Drop for TaskPoolSubmission",
    ),
    "job_handle.rs": (
        "pub fn combine(handles: &[JobHandle])",
        "pub fn completed() -> Self",
        "pub fn on_terminal",
        "pub fn is_cancelled",
        "pub fn terminal_state",
        "pub fn terminal_observer_panic_count",
        "pub fn wait(&self)",
        "assist_current_thread_once",
        "WORKER_WAIT_IDLE_PARK",
        "terminal_observers",
        "catch_unwind",
        "panic_message",
        "mark_panicked",
        "mark_cancelled",
        "Condvar",
    ),
    "parallel_for.rs": (
        "pub fn parallel_for",
        "pool.install",
        "par_chunks_mut",
    ),
    "diagnostics.rs": (
        '"tasks.scheduled"',
        '"tasks.completed"',
        '"tasks.dependency_waiting"',
        '"tasks.queued"',
        '"tasks.active"',
        '"tasks.queue_wait_samples"',
        '"tasks.queue_wait_ms"',
        '"tasks.panicked"',
        '"tasks.cancelled"',
        '"tasks.dependency_wait_ms"',
        '"tasks.explicit_wait_ms"',
    ),
    "report.rs": (
        "pub struct JobSchedulerReport",
        "record_diagnostics",
    ),
    "retained_byte_budget.rs": (
        "pub struct RetainedByteBudget",
        "pub struct RetainedByteLease",
        "pub fn with_max_leases",
        "pub fn try_reserve",
        "impl Drop for RetainedByteLeaseInner",
    ),
    "timer.rs": (
        "pub(crate) fn process_default()",
        "pub(crate) fn schedule_at(",
        "pub(crate) struct TaskTimerSubscription",
        "spawn_named_thread(PROCESS_TIMER_THREAD_NAME",
    ),
}
SCHEDULE_EXECUTOR_REQUIRED_SNIPPETS = (
    "JobHandle::completed()",
    ".schedule_after(",
    "run_parallel_tasks(",
    "scheduler.join(",
)
JOB_SYSTEM_BEHAVIOR_TEST_ANCHORS = (
    "scoped_submission_binds_descriptor_status_and_wait_to_one_handle",
    "canonical_status_never_precedes_or_lags_completion_fence_under_race",
    "dependency_wiring_retains_cancel_on_drop_prerequisite_until_terminal",
    "detached_cancellation_keeps_status_and_dependency_fence_consistent",
    "detached_panic_keeps_status_and_dependency_fence_consistent",
    "late_terminal_observer_runs_after_task_graph_workers_join",
    "capture_preserves_per_stream_order_identity_and_terminal_tail",
    "line_decoder_bounds_unterminated_input_and_reports_lossy_utf8",
    "queue_entry_budget_drops_new_records_without_exceeding_retained_bytes",
    "live_drain_defers_records_after_count_or_byte_budget",
    "reader_capacity_is_reserved_for_the_whole_lane",
    "oversized_multi_reader_capture_aborts_before_reading_any_stream",
    "capture_never_admits_more_blocking_readers_than_physical_io_workers",
    "cancellation_after_pipe_close_reaches_terminal_without_losing_residual_output",
    "dropping_capture_is_nonblocking_but_runtime_keeps_blocked_reader_accounted",
    "read_failures_are_typed_and_bounded_to_the_source_stream",
    "interrupted_reads_are_retried_without_terminal_failure",
    "runtime_stream_owner_does_not_create_private_reader_threads",
    "terminal_observation_source_does_not_enable_full_lifecycle_sampling",
    "journal_retention_is_bounded_and_reports_the_exact_cursor_gap",
    "terminal_kinds_preserve_runtime_neutral_severity_and_task_identity",
    "observation_messages_are_utf8_safely_bounded",
    "task_identity_sequences_are_unique_without_a_scheduler_global_allocator",
    "dependency_panic_is_not_misclassified_as_prelaunch_cancellation",
    "first_dependency_terminal_winner_owns_handle_metrics_and_observation",
    "job_handle_wait_blocks_until_task_completes",
    "job_handle_wait_reports_task_panic_without_leaking_completion",
    "schedule_after_runs_task_only_after_all_dependencies",
    "schedule_after_propagates_dependency_panic_without_running_dependent_task",
    "combined_handle_completes_when_all_children_complete",
    "combined_handle_waits_for_all_children_before_propagating_panic",
    "schedule_after_does_not_consume_worker_while_waiting_on_dependencies",
    "job_terminal_observer_registered_before_completion_runs_once",
    "job_terminal_observer_registered_after_completion_runs_once",
    "multiple_job_terminal_observers_each_run_exactly_once",
    "job_terminal_observer_panic_is_contained_and_recorded",
    "job_terminal_observer_preserves_dependency_continuation_order",
    "job_terminal_observer_can_reenter_handle_accessors",
    "job_terminal_observer_runs_once_when_dependency_continuation_unwinds",
    "job_diagnostics_track_schedule_complete_and_wait_times",
    "task_diagnostics_track_ready_queue_active_and_queue_wait",
    "task_diagnostics_track_dependency_waiting_through_release_and_cancellation",
    "task_diagnostics_queue_pressure_matrix_drains_without_gauge_leaks",
    "task_diagnostics_reports_conserved_lifecycle_snapshots_during_transitions",
    "worker_side_wait_is_reported_as_explicit_wait",
    "task_diagnostics_distinguish_panics_from_dependency_cancellation",
    "deep_dependency_chain_completes_in_order",
    "wide_fanout_combine_waits_for_all",
    "scheduler_wait_all_waits_for_all_handles_and_records_sync_time",
    "worker_thread_wait_does_not_deadlock_scheduler",
    "parallel_for_visits_every_item_exactly_once",
    "parallel_for_chunk_size_bounds_task_granularity",
    "acquired_submission_survives_external_admission_close",
    "accepted_dependency_chain_completes_after_external_admission_closes",
    "shutdown_waits_for_accepted_terminal_observers_before_worker_quit",
    "dropping_empty_scopes_retires_graph_registration_immediately",
    "close_admission_cancels_queued_cancel_on_drop_work_before_user_code_runs",
    "shutdown_timeout_keeps_the_runtime_closing_and_reports_the_running_scope",
    "scheduler_submission_uses_scope_cancellation_and_drain_accounting",
    "scheduler_submission_rejects_closed_full_and_unrelated_pool_scopes",
    "scheduler_dependency_failure_retires_scope_admission_without_running_user_work",
    "dropping_the_last_cancel_on_drop_handle_cancels_queued_work",
    "dropping_the_last_scope_handle_closes_admission_while_task_handles_remain",
    "cancelled_handle_reports_typed_terminal_state_without_panicking_wait",
    "schedule_after_propagates_dependency_cancellation_without_running_dependent_work",
    "running_work_that_ignores_a_cancellation_request_completes",
    "running_work_reports_cancelled_only_after_acknowledgement",
    "scoped_dynamic_scene_prepare_cancels_before_a_queued_loader_starts",
    "cloned_lease_releases_bytes_only_after_the_last_owner_drops",
    "closed_budget_rejects_new_reservations_without_revoking_live_leases",
    "oversized_reservation_reports_the_exact_remaining_capacity",
    "lease_capacity_bounds_many_small_retained_results",
    "standalone_level_manager_rejects_artifact_io_without_an_implicit_process_owner",
)
MIRROR_DOCS_GUARD = "runtime_11_job_system_mirror_docs_match_structure_audit_counts"
