from __future__ import annotations


FRAME_SPAN_ANCHORS = (
    "profile_scope!(\"runtime\", \"frame\", \"runtime_frame_time_update\")",
    "profile_scope!(\"runtime\", \"frame\", \"runtime_frame_update\")",
    "profile_scope!(\"runtime\", \"frame\", \"runtime_frame_extract\")",
    "profile_scope!(\"runtime\", \"frame\", \"runtime_frame_submit\")",
    "profile_dynamic_scope!(",
    "runtime_frame_schedule_stage.{stage:?}",
    "macro_rules! profile_scope",
    "macro_rules! profile_dynamic_scope",
    "macro_rules! profile_frame",
)
QUERY_COUNTER_ANCHORS = (
    'pub const ECS_QUERY_ARCHETYPE_CACHE_HITS_DIAGNOSTIC: &str = "ecs.query.archetype_cache_hits";',
    'pub const ECS_QUERY_ARCHETYPE_CACHE_MISSES_DIAGNOSTIC: &str = "ecs.query.archetype_cache_misses";',
    '"ecs.query.archetype_cache_rebuilds"',
    'pub const ECS_QUERY_CANDIDATE_ENTITIES_DIAGNOSTIC: &str = "ecs.query.candidate_entities";',
    'pub const ECS_QUERY_MATCHED_ENTITIES_DIAGNOSTIC: &str = "ecs.query.matched_entities";',
    "pub struct QueryStateCacheStats",
    "pub fn record_diagnostics(&self, store: &mut DiagnosticStore, frame_index: u64)",
    "pub fn cache_stats(&self) -> QueryStateCacheStats",
    "self.cache_hits = self.cache_hits.saturating_add(1);",
    "self.cache_misses = self.cache_misses.saturating_add(1);",
    "self.cache_rebuilds = self.cache_rebuilds.saturating_add(1);",
    "last_candidate_entity_count",
    "last_matched_entity_count",
    "last_reported_cache_stats",
    "change_detection_stats: Cell<ChangeDetectionScanStats>",
    "last_reported_change_detection_stats",
    "pub fn saturating_delta_since(self, baseline: Self) -> Self",
    "pub(crate) fn take_unreported_cache_stats(&mut self) -> QueryStateCacheStats",
    "pub(crate) fn take_unreported_change_detection_stats(&mut self) -> ChangeDetectionScanStats",
    "fn record_performance_diagnostics(world: &mut World, state: &mut Self::State)",
    "world.record_ecs_query_cache_stats(query_stats);",
    "world.record_ecs_change_detection_stats(change_detection_stats);",
    "state.record_change_detection_stats(self.change_detection_stats);",
    "state: Option<NonNull<QueryState<D, F>>>",
    "P::record_performance_diagnostics(world, &mut self.state);",
    "P::record_performance_diagnostics(world, state);",
    "A::record_performance_diagnostics(world, &mut state.0);",
    "pub fn reset_ecs_frame_performance_diagnostics(&mut self)",
    "pub fn ecs_frame_performance_diagnostics(&self) -> EcsFramePerformanceDiagnostics",
    "pub(crate) fn record_ecs_query_cache_stats(&mut self, stats: QueryStateCacheStats)",
    "pub(crate) fn record_ecs_change_detection_stats(&mut self, stats: ChangeDetectionScanStats)",
    "level.with_world_mut(|world| world.reset_ecs_frame_performance_diagnostics());",
)
CHANGE_COUNTER_ANCHORS = (
    '"ecs.change_detection.scanned_marks"',
    '"ecs.change_detection.added_matches"',
    '"ecs.change_detection.changed_matches"',
    "pub struct ChangeDetectionScanStats",
    "pub fn scan_added(&mut self, ticks: ComponentTicks, window: ChangeTickWindow) -> bool",
    "pub fn scan_changed(&mut self, ticks: ComponentTicks, window: ChangeTickWindow) -> bool",
    "pub fn saturating_delta_since(self, baseline: Self) -> Self",
    "pub fn merge(&mut self, other: Self)",
    "pub fn record_diagnostics(&self, store: &mut DiagnosticStore, frame_index: u64)",
    "self.scanned_marks = self.scanned_marks.saturating_add(1);",
    "fn matches_component_locations_with_stats(",
    "stats.scan_added(component_ticks, ticks)",
    "stats.scan_changed(component_ticks, ticks)",
)
EXTRACT_COUNTER_ANCHORS = (
    'pub(super) const EXTRACT_REBUILD_CLONES_DIAGNOSTIC: &str = "extract.rebuild_clones";',
    'pub(super) const EXTRACT_OUTPUT_BYTES_DIAGNOSTIC: &str = "extract.output_bytes";',
    'pub(super) const EXTRACT_CACHE_HITS_DIAGNOSTIC: &str = "extract.cache_hits";',
    'pub(super) const EXTRACT_CACHE_MISSES_DIAGNOSTIC: &str = "extract.cache_misses";',
    "pub(super) struct RuntimeFrameExtractStats",
    "pub cache_hits: u64",
    "pub cache_misses: u64",
    "RuntimeFrameExtractCacheStatus::Rebuilt => 1",
    "RuntimeFrameExtractCacheStatus::Reused => 0",
    "pub(super) struct RuntimeFrameExtractCache",
    "struct RuntimeFrameExtractCacheKey",
    "change_tick: world.read_change_tick()",
    "query_cache_revision: world.query_cache_revision()",
    "active_camera: world.active_camera()",
    "estimate_extract_output_bytes(extract)",
    "record_frame_extract_stats(&self.runtime, &extract, status);",
    "pub(super) fn current_extract(&mut self) -> RenderFrameExtract",
    ".current_extract(&self.level, viewport_size)",
    "to_render_frame_extract()",
    "runtime.record_diagnostic(",
    "slice_bytes(",
)
ASSET_WORKER_ANCHORS = (
    "pub const ASSET_WORKER_BUDGETED_THREADS_DIAGNOSTIC: &str = \"asset.worker.budgeted_threads\";",
    "pub const ASSET_WORKER_FRAME_COMPLETED_DIAGNOSTIC: &str =",
    "pub const ASSET_WORKER_FRAME_FAILED_DIAGNOSTIC: &str = \"asset.worker.frame_failed\";",
    "pub struct AssetWorkerPoolDiagnostics",
    "pub struct AssetWorkerPoolFrameSampler",
    "pub fn spawn_worker_pool_with_frame_sampler(",
    "AssetWorkerPoolFrameSampler::from_pool(&pool)",
    "pub budgeted_threads: usize",
    "pub completed_delta: u64",
    "pub fn sample(&mut self, pool: &AssetWorkerPool) -> AssetWorkerPoolFrameDiagnostics",
    "pub fn record_diagnostics(&self, store: &mut DiagnosticStore, frame_index: u64)",
    "diagnostics.budgeted_threads as f64",
    "self.completed_delta as f64",
)
ANIMATION_SCENE_ANCHORS = (
    'pub(super) const ANIMATION_SCENE_SCANNED_ENTITIES_DIAGNOSTIC: &str =',
    '"animation.scene.scanned_entities"',
    '"animation.scene.sequence_samples"',
    '"animation.scene.output_poses"',
    '"animation.scene.applied_transforms"',
    '"animation.scene.published_events"',
    '"animation.scene.state_transitions"',
    "pub(super) struct AnimationSceneFrameDiagnostics",
    "pub(super) fn from_scan(scan: &AnimationSceneScan) -> Self",
    "pub(super) fn record(self, core: &CoreHandle)",
    "scanned_entities: entity_ids.len()",
    "pub(super) fn publish_events(level: &LevelSystem, events: Vec<AnimationClipEvent>) -> usize",
    "let event_count = events.len();",
    "let update_count = updates.len();",
    "AnimationSceneFrameDiagnostics::from_scan(&scan)",
    "frame_diagnostics.published_events += publish_events(level, graph_events);",
    "frame_diagnostics.applied_transforms =",
    "frame_diagnostics.state_transitions = transition_updates.len();",
    "AnimationSceneFrameDiagnostics::default().record(core);",
)
PROFILE_COUNTER_HOTSPOT_ANCHORS = (
    'pub const PROFILE_COUNTER_HOTSPOTS_FILE: &str = "counter_hotspots.json";',
    "pub struct CounterHotspotReport",
    "pub struct CounterHotspotEntry",
    "pub fn analyze_counter_hotspots",
    "PROFILE_COUNTER_HOTSPOTS_FILE",
    "summary.push_str(\"\\n## Counter Hotspots\\n\");",
    "response.counter_hotspot_report = Some(report.counter_hotspots);",
    "counter_hotspots.json",
)
HOTSPOT_GUARD_ANCHORS = (
    "runtime_07_hotspot_inventory_requires_counted_evidence_before_m2",
    "runtime_07_large_file_owner_budget_gate_stays_in_sync_with_structure_audit",
    "runtime_07_virtual_geometry_debug_snapshot_owner_split_keeps_contracts_folder_backed",
    "runtime_07_performance_hotpath_mirror_docs_match_structure_audit_counts",
    "runtime_07_scene_asset_folder_split_keeps_public_surface_and_single_owner",
    "runtime_07_project_io_folder_split_keeps_entry_and_converter_owners",
    "runtime_07_dynamic_session_event_split_keeps_abi_entry_and_event_owner",
    "runtime_07_artifact_cache_payload_owner_split_keeps_wire_types_folder_backed",
    "runtime_07_render_product_diagnostics_owner_split_keeps_families_folder_backed",
    "runtime_07_profile_counter_hotspot_export_keeps_generic_counter_evidence_visible",
    "AnimationSceneFrameDiagnostics",
    "animation.scene.scanned_entities",
    "animation_scene_frame_diagnostics_static_passed_cargo_deferred",
    "runtime_07_performance_hotpath_cargo_gate_stays_visible_until_performance_validation",
    "profiling_build_tooling_static_passed_cargo_deferred_active_lanes",
    "python tools/zircon_build.py --targets runtime --out E:\\builds\\zircon-profile --mode profiling --runtime-features target-client,profiling,profiling-tracy",
    "./tools/dev-fast-build.ps1 -Profile client -Action check -Package zircon_runtime -CargoProfile profiling -FeatureOverride \"target-client profiling profiling-tracy\"",
    "No Runtime 07 M2 optimization slice may start from an unmeasured suspicion",
    "Authoritative Top List",
    "Pending authoritative runtime sample",
    "Candidate Evidence Matrix",
    "Render-Plan Diversions",
    "Runtime 07 M2 is not allowed to fix render submission",
    "frame_extract_rebuild_skips_unchanged_entities",
    "query_state_reuses_archetype_matches_across_unchanged_frames",
    "change_detection_scan_skips_unmarked_archetypes",
    "asset.worker.budgeted_threads",
    "CounterHotspotReport",
    "counter_hotspots.json",
    "230 draws",
    "231 pre-draw",
    "31 render passes",
)
MIRROR_DOCS_GUARD = (
    "runtime_07_performance_hotpath_mirror_docs_match_structure_audit_counts"
)
RUNTIME_07_TEST_ANCHORS = (
    "query_state_cache_stats_record_reuse_and_rebuild_counts",
    "query_state_reuses_archetype_matches_across_unchanged_frames",
    "const ENTITY_COUNT: usize = 128;",
    "const REPEATED_QUERY_RUNS: usize = 8;",
    "assert_eq!(reused.cache_hits, REPEATED_QUERY_RUNS as u64)",
    "change_detection_scan_stats_record_mark_checks_and_diagnostics",
    "change_detection_scan_skips_unmarked_archetypes",
    "assert_eq!(stats.scanned_marks, unmarked.len() as u64 * 2)",
    "ecs_frame_performance_diagnostics_record_query_and_change_counts",
    "system_state_records_query_cache_stats_into_world_frame_diagnostics",
    "system_state_records_change_detection_stats_into_world_frame_diagnostics",
    "world.reset_ecs_frame_performance_diagnostics();",
    "assert_eq!(first_frame.query.cache_hits, 2)",
    "third_frame.change_detection.changed_matches",
    "headless_session_capture_records_frame_extract_diagnostics",
    "frame_extract_rebuild_skips_unchanged_entities",
    "EXTRACT_CACHE_HITS_DIAGNOSTIC",
    "EXTRACT_CACHE_MISSES_DIAGNOSTIC",
    "rebuilds.history[1].value, 0.0",
    "cache_hits.history[1].value, 1.0",
    "cache_misses.history[0].value, 1.0",
    "unchanged headless capture should reuse the cached extract",
    "frame_extract_rebuilds_after_scene_change",
    "scene mutations should invalidate the dynamic-session extract cache",
    "vec![1.0, 1.0]",
    "output_bytes.history[0].value, output_bytes.history[1].value",
    "CounterHotspotReport",
    "counter_hotspots.json",
    "ProfileControlResponse.counter_hotspot_report",
)
RUNTIME_07_DOC_ANCHORS = (
    "performance_hotpath_boundary",
    "Runtime 07 Hotspot Inventory Guard",
    "Runtime 07 Performance Hotpath Guard",
    "Runtime 07 owner-budgeted optimization gate",
    "large_file_ownership_gate",
    "runtime_07_hotspot_inventory_requires_counted_evidence_before_m2",
    "runtime_07_large_file_owner_budget_gate_stays_in_sync_with_structure_audit",
    MIRROR_DOCS_GUARD,
    "runtime_07_performance_hotpath_cargo_gate_stays_visible_until_performance_validation",
    "runtime_frame_schedule_stage.<SystemStage>",
    "extract/ecs_query/performance profiling/FPS gates",
    "profiling_build_tooling_static_passed_cargo_deferred_active_lanes",
    "tools/zircon_build.py --mode profiling --runtime-features target-client,profiling,profiling-tracy",
    "tools/dev-fast-build.ps1 -CargoProfile profiling",
    "No Runtime 07 M2 optimization slice may start from an unmeasured suspicion",
    "large production files remain above the owner budget",
    "Pending authoritative runtime sample",
    "Candidate Evidence Matrix",
    "Runtime Frame Extract Cache",
    "RuntimeFrameExtractCache",
    "extract.cache_hits",
    "extract.cache_misses",
    "AnimationSceneFrameDiagnostics",
    "animation.scene.scanned_entities",
    "animation.scene.output_poses",
    "animation_scene_frame_diagnostics_static_passed_cargo_deferred",
    "extract_rebuild_cache_static_passed_cargo_deferred",
    "EcsFramePerformanceDiagnostics",
    "asset.worker.budgeted_threads",
    "asset.worker.frame_completed",
    "CounterHotspotReport",
    "counter_hotspots.json",
    "render 计划 02/04",
    "render_product_diagnostics_owner_split_static_passed_cargo_deferred",
    "render_stats_store/product/{camera,mesh_queue,gpu_scene}.rs",
)
CARGO_GATE_ANCHORS = (
    "cargo test -p zircon_runtime --lib vampire_project_session_reports_runtime_fps_and_render_work --features backend-zr-vm --locked -- --nocapture --test-threads=1",
    "cargo check -p zircon_runtime --lib --locked",
    "cargo test -p zircon_runtime --lib extract --locked -- --nocapture",
    "cargo test -p zircon_runtime --lib ecs_query --locked -- --nocapture",
    "runtime_07_performance_hotpath_cargo_gate_stays_visible_until_performance_validation",
)
