//! 命名策略扫描需区分生产源码、测试夹具和已分类的历史名称。保存同组守卫使用的局部数据或辅助变换。
mod asset_dynamic;
mod asset_schema;
mod banned_names;
mod core_framework;
mod core_scene;
mod editor_workbench;
mod graphics;
mod hub;
mod input;
mod net;
mod plugin_static_manifest;
mod scene_tests;
mod ui;
