#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum BuiltinRenderFeature {
    Mesh,
    Sprite,
    DeferredGeometry,
    DeferredLighting,
    ClusteredLighting,
    ScreenSpaceAmbientOcclusion,
    Bloom,
    ColorGrading,
    ReflectionProbes,
    BakedLighting,
    HistoryResolve,
    Shadows,
    PostProcess,
    Ui,
    DebugOverlay,
    Particle,
    GlobalIllumination,
    RayTracing,
    VirtualGeometry,
}
