#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum BuiltinRenderFeature {
    Mesh,
    SkinnedMesh,
    MeshLod,
    Sprite,
    DeferredGeometry,
    DeferredLighting,
    ClusteredLighting,
    Hzb,
    ScreenSpaceAmbientOcclusion,
    Bloom,
    ColorGrading,
    ReflectionProbes,
    BakedLighting,
    HistoryResolve,
    AntiAlias,
    Shadows,
    PostProcess,
    Ui,
    DebugOverlay,
    Particle,
    GlobalIllumination,
    RayTracing,
    NeuralCompute,
    SparseTexture,
    Terrain,
    Tree,
    Decal,
    Projector,
    Halo,
    LensFlare,
    Trail,
    Billboard,
    Tilemap,
    TextShaping,
    Skybox,
    Cubemap,
    Texture2dArray,
    NormalMap,
    Mipmap,
    ColorSpace,
    VirtualGeometry,
}

impl BuiltinRenderFeature {
    pub const ALL: &[Self] = &[
        Self::Mesh,
        Self::SkinnedMesh,
        Self::MeshLod,
        Self::Sprite,
        Self::DeferredGeometry,
        Self::DeferredLighting,
        Self::ClusteredLighting,
        Self::Hzb,
        Self::ScreenSpaceAmbientOcclusion,
        Self::Bloom,
        Self::ColorGrading,
        Self::ReflectionProbes,
        Self::BakedLighting,
        Self::HistoryResolve,
        Self::AntiAlias,
        Self::Shadows,
        Self::PostProcess,
        Self::Ui,
        Self::DebugOverlay,
        Self::Particle,
        Self::GlobalIllumination,
        Self::RayTracing,
        Self::NeuralCompute,
        Self::SparseTexture,
        Self::Terrain,
        Self::Tree,
        Self::Decal,
        Self::Projector,
        Self::Halo,
        Self::LensFlare,
        Self::Trail,
        Self::Billboard,
        Self::Tilemap,
        Self::TextShaping,
        Self::Skybox,
        Self::Cubemap,
        Self::Texture2dArray,
        Self::NormalMap,
        Self::Mipmap,
        Self::ColorSpace,
        Self::VirtualGeometry,
    ];

    pub const fn authoring_name(self) -> &'static str {
        match self {
            Self::Mesh => "Mesh",
            Self::SkinnedMesh => "SkinnedMesh",
            Self::MeshLod => "MeshLod",
            Self::Sprite => "Sprite",
            Self::DeferredGeometry => "DeferredGeometry",
            Self::DeferredLighting => "DeferredLighting",
            Self::ClusteredLighting => "ClusteredLighting",
            Self::Hzb => "Hzb",
            Self::ScreenSpaceAmbientOcclusion => "ScreenSpaceAmbientOcclusion",
            Self::Bloom => "Bloom",
            Self::ColorGrading => "ColorGrading",
            Self::ReflectionProbes => "ReflectionProbes",
            Self::BakedLighting => "BakedLighting",
            Self::HistoryResolve => "HistoryResolve",
            Self::AntiAlias => "AntiAlias",
            Self::Shadows => "Shadows",
            Self::PostProcess => "PostProcess",
            Self::Ui => "Ui",
            Self::DebugOverlay => "DebugOverlay",
            Self::Particle => "Particle",
            Self::GlobalIllumination => "GlobalIllumination",
            Self::RayTracing => "RayTracing",
            Self::NeuralCompute => "NeuralCompute",
            Self::SparseTexture => "SparseTexture",
            Self::Terrain => "Terrain",
            Self::Tree => "Tree",
            Self::Decal => "Decal",
            Self::Projector => "Projector",
            Self::Halo => "Halo",
            Self::LensFlare => "LensFlare",
            Self::Trail => "Trail",
            Self::Billboard => "Billboard",
            Self::Tilemap => "Tilemap",
            Self::TextShaping => "TextShaping",
            Self::Skybox => "Skybox",
            Self::Cubemap => "Cubemap",
            Self::Texture2dArray => "Texture2dArray",
            Self::NormalMap => "NormalMap",
            Self::Mipmap => "Mipmap",
            Self::ColorSpace => "ColorSpace",
            Self::VirtualGeometry => "VirtualGeometry",
        }
    }

    pub fn from_authoring_name(value: &str) -> Option<Self> {
        Self::ALL
            .iter()
            .copied()
            .find(|feature| feature.authoring_name() == value)
    }
}
