use std::sync::Arc;

use zircon_runtime::core::framework::render::{
    RenderVirtualGeometryExecutionSegment, RenderVirtualGeometrySelectedCluster,
    RenderVirtualGeometrySelectedClusterSource,
};

use super::super::virtual_geometry_hardware_rasterization_pass::VirtualGeometryHardwareRasterizationPassOutput;
use super::super::virtual_geometry_indirect_stats_store_parts::VirtualGeometryIndirectStatsStoreParts;
use super::super::virtual_geometry_node_and_cluster_cull_pass::VirtualGeometryNodeAndClusterCullPassOutput;
use super::super::virtual_geometry_visbuffer64_pass::VirtualGeometryVisBuffer64PassOutput;

pub(in crate::virtual_geometry::renderer) struct VirtualGeometryIndirectStats {
    draw_count: u32,
    buffer_count: u32,
    segment_count: u32,
    execution_segment_count: u32,
    execution_page_count: u32,
    execution_resident_segment_count: u32,
    execution_pending_segment_count: u32,
    execution_missing_segment_count: u32,
    execution_repeated_draw_count: u32,
    execution_indirect_offsets: Vec<u64>,
    execution_segments: Vec<RenderVirtualGeometryExecutionSegment>,
    executed_selected_clusters: Vec<RenderVirtualGeometrySelectedCluster>,
    executed_selected_cluster_source: RenderVirtualGeometrySelectedClusterSource,
    executed_selected_cluster_count: u32,
    executed_selected_cluster_buffer: Option<Arc<wgpu::Buffer>>,
    node_and_cluster_cull_pass: VirtualGeometryNodeAndClusterCullPassOutput,
    hardware_rasterization_pass: VirtualGeometryHardwareRasterizationPassOutput,
    visbuffer64_pass: VirtualGeometryVisBuffer64PassOutput,
    draw_submission_order: Vec<(Option<u32>, u64, u32)>,
    draw_submission_records: Vec<(u64, u32, u32, usize)>,
    draw_submission_token_records: Vec<(u64, u32, u32, u32, usize)>,
    args_buffer: Option<Arc<wgpu::Buffer>>,
    args_count: u32,
    submission_buffer: Option<Arc<wgpu::Buffer>>,
    authority_buffer: Option<Arc<wgpu::Buffer>>,
    draw_ref_buffer: Option<Arc<wgpu::Buffer>>,
    segment_buffer: Option<Arc<wgpu::Buffer>>,
    execution_submission_buffer: Option<Arc<wgpu::Buffer>>,
    execution_args_buffer: Option<Arc<wgpu::Buffer>>,
    execution_authority_buffer: Option<Arc<wgpu::Buffer>>,
}

impl VirtualGeometryIndirectStats {
    #[allow(clippy::too_many_arguments)]
    pub(super) fn new(
        draw_count: u32,
        buffer_count: u32,
        segment_count: u32,
        execution_segment_count: u32,
        execution_page_count: u32,
        execution_resident_segment_count: u32,
        execution_pending_segment_count: u32,
        execution_missing_segment_count: u32,
        execution_repeated_draw_count: u32,
        execution_indirect_offsets: Vec<u64>,
        execution_segments: Vec<RenderVirtualGeometryExecutionSegment>,
        executed_selected_clusters: Vec<RenderVirtualGeometrySelectedCluster>,
        executed_selected_cluster_source: RenderVirtualGeometrySelectedClusterSource,
        executed_selected_cluster_count: u32,
        executed_selected_cluster_buffer: Option<Arc<wgpu::Buffer>>,
        node_and_cluster_cull_pass: VirtualGeometryNodeAndClusterCullPassOutput,
        hardware_rasterization_pass: VirtualGeometryHardwareRasterizationPassOutput,
        visbuffer64_pass: VirtualGeometryVisBuffer64PassOutput,
        draw_submission_order: Vec<(Option<u32>, u64, u32)>,
        draw_submission_records: Vec<(u64, u32, u32, usize)>,
        draw_submission_token_records: Vec<(u64, u32, u32, u32, usize)>,
        args_buffer: Option<Arc<wgpu::Buffer>>,
        args_count: u32,
        submission_buffer: Option<Arc<wgpu::Buffer>>,
        authority_buffer: Option<Arc<wgpu::Buffer>>,
        draw_ref_buffer: Option<Arc<wgpu::Buffer>>,
        segment_buffer: Option<Arc<wgpu::Buffer>>,
        execution_submission_buffer: Option<Arc<wgpu::Buffer>>,
        execution_args_buffer: Option<Arc<wgpu::Buffer>>,
        execution_authority_buffer: Option<Arc<wgpu::Buffer>>,
    ) -> Self {
        Self {
            draw_count,
            buffer_count,
            segment_count,
            execution_segment_count,
            execution_page_count,
            execution_resident_segment_count,
            execution_pending_segment_count,
            execution_missing_segment_count,
            execution_repeated_draw_count,
            execution_indirect_offsets,
            execution_segments,
            executed_selected_clusters,
            executed_selected_cluster_source,
            executed_selected_cluster_count,
            executed_selected_cluster_buffer,
            node_and_cluster_cull_pass,
            hardware_rasterization_pass,
            visbuffer64_pass,
            draw_submission_order,
            draw_submission_records,
            draw_submission_token_records,
            args_buffer,
            args_count,
            submission_buffer,
            authority_buffer,
            draw_ref_buffer,
            segment_buffer,
            execution_submission_buffer,
            execution_args_buffer,
            execution_authority_buffer,
        }
    }

    pub(in crate::virtual_geometry::renderer) fn into_store_parts(
        self,
    ) -> VirtualGeometryIndirectStatsStoreParts {
        VirtualGeometryIndirectStatsStoreParts {
            draw_count: self.draw_count,
            buffer_count: self.buffer_count,
            segment_count: self.segment_count,
            execution_segment_count: self.execution_segment_count,
            execution_page_count: self.execution_page_count,
            execution_resident_segment_count: self.execution_resident_segment_count,
            execution_pending_segment_count: self.execution_pending_segment_count,
            execution_missing_segment_count: self.execution_missing_segment_count,
            execution_repeated_draw_count: self.execution_repeated_draw_count,
            execution_indirect_offsets: self.execution_indirect_offsets,
            execution_segments: self.execution_segments,
            executed_selected_clusters: self.executed_selected_clusters,
            executed_selected_cluster_source: self.executed_selected_cluster_source,
            executed_selected_cluster_count: self.executed_selected_cluster_count,
            executed_selected_cluster_buffer: self.executed_selected_cluster_buffer,
            node_and_cluster_cull_pass: self.node_and_cluster_cull_pass,
            hardware_rasterization_pass: self.hardware_rasterization_pass,
            visbuffer64_pass: self.visbuffer64_pass,
            draw_submission_order: self.draw_submission_order,
            draw_submission_records: self.draw_submission_records,
            draw_submission_token_records: self.draw_submission_token_records,
            args_buffer: self.args_buffer,
            args_count: self.args_count,
            submission_buffer: self.submission_buffer,
            authority_buffer: self.authority_buffer,
            draw_ref_buffer: self.draw_ref_buffer,
            segment_buffer: self.segment_buffer,
            execution_submission_buffer: self.execution_submission_buffer,
            execution_args_buffer: self.execution_args_buffer,
            execution_authority_buffer: self.execution_authority_buffer,
        }
    }
}
