pub(super) const BUILD_EXPORT_ACTION_COUNT: usize = 4;
pub(super) const BUILD_EXPORT_NODES_PER_TARGET: usize = BUILD_EXPORT_ACTION_COUNT + 5;
pub(super) const BUILD_EXPORT_ROW_HEIGHT: f32 = 118.0;
pub(super) const BUILD_EXPORT_ROW_GAP: f32 = 8.0;
pub(super) const BUILD_EXPORT_ROW_PADDING: f32 = 8.0;
pub(super) const BUILD_EXPORT_BUTTON_HEIGHT: f32 = 24.0;
pub(super) const BUILD_EXPORT_PRIMARY_BUTTON_WIDTH: f32 = 84.0;
pub(super) const BUILD_EXPORT_SECONDARY_BUTTON_WIDTH: f32 = 72.0;
pub(super) const BUILD_EXPORT_BUTTON_GAP: f32 = 6.0;
