use super::ExpectedStatusOutputSlice;

#[path = "runtime_15/f12_resource.rs"]
mod f12_resource;
#[path = "runtime_15/foundation.rs"]
mod foundation;
#[path = "runtime_15/m2.rs"]
mod m2;
#[path = "runtime_15/m3.rs"]
mod m3;
#[path = "runtime_15/m3_review_guard_exports.rs"]
mod m3_review_guard_exports;
#[path = "runtime_15/m4.rs"]
mod m4;

pub(super) const RUNTIME_15_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = foundation::FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_FOUNDATION_TYPED_ERROR_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    foundation::FOUNDATION_TYPED_ERROR_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_FOUNDATION_TYPED_ERROR_PLUGIN_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    foundation::FOUNDATION_TYPED_ERROR_PLUGIN_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_FOUNDATION_TYPED_ERROR_SCENE_ASSET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    foundation::FOUNDATION_TYPED_ERROR_SCENE_ASSET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M2_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    m2::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M2_RENDER_GRAPHICS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m2::RENDER_GRAPHICS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M2_UI_PLATFORM_EDITOR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m2::UI_PLATFORM_EDITOR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M2_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m2::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M4_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    m4::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M4_ASSET_SCENE_RENDER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m4::ASSET_SCENE_RENDER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M4_UI_TEXT_TEMPLATE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m4::UI_TEXT_TEMPLATE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M4_UI_SURFACE_PLUGIN_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m4::UI_SURFACE_PLUGIN_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M4_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m4::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M4_RENDER_SHADER_SYNC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m4::RENDER_SHADER_SYNC_EXPECTED_STATUS_OUTPUT_SLICES;

pub(super) const RUNTIME_15_F12_RESOURCE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = f12_resource::EXPECTED_STATUS_OUTPUT_SLICES;

pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::FOUNDATION_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_PLUGIN_IMPORTER_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_PLUGIN_IMPORTER_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_PLUGIN_IMPORTER_MIGRATIONS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_PLUGIN_IMPORTER_MIGRATIONS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_ABSORPTION_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_RUNTIME_ABSORPTION_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_FOUNDATION_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::FOUNDATION_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_LOCK_POISON_STATUS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::LOCK_POISON_STATUS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_LOCK_POISON_STATUS_POLICY_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::LOCK_POISON_STATUS_POLICY_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_LOCK_POISON_STATUS_CORE_RUNTIME_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::LOCK_POISON_STATUS_CORE_RUNTIME_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_LOCK_POISON_STATUS_RUNTIME_SERVICES_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::LOCK_POISON_STATUS_RUNTIME_SERVICES_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_LOCK_POISON_STATUS_RESOURCE_RENDER_INPUT_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::LOCK_POISON_STATUS_RESOURCE_RENDER_INPUT_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_LOCK_POISON_STATUS_SCRIPT_VM_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::LOCK_POISON_STATUS_SCRIPT_VM_RECOVERY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_LOCK_POISON_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::LOCK_POISON_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_MODULE_CONVENTION_STATUS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::MODULE_CONVENTION_STATUS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_MODULE_CONVENTION_STATUS_FRONTMATTER_AND_GATE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::MODULE_CONVENTION_STATUS_FRONTMATTER_AND_GATE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_MODULE_CONVENTION_STATUS_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::MODULE_CONVENTION_STATUS_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_MODULE_CONVENTION_STATUS_AUDIT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::MODULE_CONVENTION_STATUS_AUDIT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_MODULE_CONVENTION_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::MODULE_CONVENTION_STATUS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_STATUS_SYNC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::REVIEW_STATUS_SYNC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_STATUS_SYNC_P0_CORE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::REVIEW_STATUS_SYNC_P0_CORE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_STATUS_SYNC_TYPED_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_STATUS_SYNC_TYPED_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_STATUS_SYNC_PROVIDER_LOOKUP_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_STATUS_SYNC_PROVIDER_LOOKUP_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_STATUS_SYNC_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_STATUS_SYNC_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_CODE_REVIEW_PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_CODE_REVIEW_PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_CODE_REVIEW_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_CODE_REVIEW_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::REVIEW_GUARD_STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::REVIEW_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_TYPED_ERROR_RUNTIME_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::REVIEW_GUARD_TYPED_ERROR_RUNTIME_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_REVIEW_GUARD_TYPED_ERROR_ASSET_SHADER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::REVIEW_GUARD_TYPED_ERROR_ASSET_SHADER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) use m3_review_guard_exports::*;
pub(super) const RUNTIME_15_M3_UI_TESTS_FIRST_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_FIRST_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_UI_TESTS_FIRST_ACCESSIBILITY_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_FIRST_ACCESSIBILITY_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_UI_TESTS_FIRST_TEMPLATE_INPUT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_FIRST_TEMPLATE_INPUT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_UI_TESTS_FIRST_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_FIRST_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::ASSET_BUDGET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_ASSET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::ASSET_BUDGET_ASSET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_ASSET_TESTS_ASSET_RESOURCE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_ASSET_TESTS_ASSET_RESOURCE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_ASSET_TESTS_UI_PIPELINE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_ASSET_TESTS_UI_PIPELINE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_ASSET_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_ASSET_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_BUDGET_RENDER_UI_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::ASSET_BUDGET_BUDGET_RENDER_UI_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_NAMING_CORE_ASSET_DYNAMIC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_NAMING_CORE_ASSET_DYNAMIC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_NAMING_GRAPHICS_MISC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_NAMING_GRAPHICS_MISC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_NAMING_GRAPHICS_MISC_GRAPHICS_ASSET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_NAMING_GRAPHICS_MISC_GRAPHICS_ASSET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_NAMING_GRAPHICS_MISC_SCENE_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_NAMING_GRAPHICS_MISC_SCENE_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_NAMING_GRAPHICS_MISC_PLUGIN_BANNED_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_NAMING_GRAPHICS_MISC_PLUGIN_BANNED_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_NAMING_GRAPHICS_MISC_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::ASSET_BUDGET_NAMING_GRAPHICS_MISC_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_ASSET_BUDGET_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::ASSET_BUDGET_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::SCENE_SCRIPT_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_RUNTIME_07_PERFORMANCE_SPLIT_LAYOUT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_RUNTIME_07_PERFORMANCE_SPLIT_LAYOUT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_RUNTIME_07_PERFORMANCE_OWNER_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_RUNTIME_07_PERFORMANCE_OWNER_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_RUNTIME_07_PERFORMANCE_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_RUNTIME_07_PERFORMANCE_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCRIPT_VM_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_SCRIPT_VM_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_MANIFEST_PACKAGE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_MANIFEST_PACKAGE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_RUNTIME_CATALOG_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_RUNTIME_CATALOG_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPORT_BUILD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPORT_BUILD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCRIPT_VM_GAMEPLAY_SHADER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_SCRIPT_VM_GAMEPLAY_SHADER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCENE_ECS_TESTS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_SCENE_ECS_TESTS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCENE_ASSET_WORLD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_SCENE_ASSET_WORLD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_SCENE_SCRIPT_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::SCENE_SCRIPT_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_AND_BUDGET_TEST_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_ROW_DATA_AND_BUDGET_TEST_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_AND_BUDGET_RUNTIME_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_ROW_DATA_AND_BUDGET_RUNTIME_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_AND_BUDGET_ANCHOR_MIRROR_ROW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_ROW_DATA_AND_BUDGET_ANCHOR_MIRROR_ROW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_AND_BUDGET_HUB_EDITOR_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_ROW_DATA_AND_BUDGET_HUB_EDITOR_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_AND_BUDGET_RENDER_SHADER_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_ROW_DATA_AND_BUDGET_RENDER_SHADER_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_AND_BUDGET_M3_M4_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_ROW_DATA_AND_BUDGET_M3_M4_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_BASE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_EXPECTED_SLICE_BASE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_TOP_LEVEL_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_EXPECTED_SLICE_TOP_LEVEL_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_ROUTE_METADATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_EXPECTED_SLICE_ROUTE_METADATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_STRUCTURE_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_EXPECTED_SLICE_STRUCTURE_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_STATUS_SUPPORT_MAPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_EXPECTED_SLICE_STATUS_SUPPORT_MAPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_REVIEW_GUARD_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_EXPECTED_SLICE_REVIEW_GUARD_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_SLICE_WARNING_CLEANUP_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_EXPECTED_SLICE_WARNING_CLEANUP_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_PRIORITY_PLAN_DOCS_OWNER_GUARDS_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_STATUS_SUPPORT_PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::STATUS_SUPPORT_PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_UI_TESTS_SECOND_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_SECOND_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_UI_TESTS_SECOND_ASSET_STYLE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_SECOND_ASSET_STYLE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_UI_TESTS_SECOND_RUNTIME_INPUT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_SECOND_RUNTIME_INPUT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_UI_TESTS_SECOND_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = m3::UI_TESTS_SECOND_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_PRODUCTION_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_PRODUCTION_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_EVIDENCE_ANCHOR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_EVIDENCE_ANCHOR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_OWNER_PATH_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_OWNER_PATH_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_PATH_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_PATH_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_GUARD_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_GUARD_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_BASE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_BASE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_CHILD_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_CHILD_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_CHILD_SUMMARY_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_CHILD_SUMMARY_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_BASE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_BASE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_LOCK_POISON_SCENE_SCRIPT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_LOCK_POISON_SCENE_SCRIPT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_ASSET_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_ASSET_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_FOUNDATION_M2_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_FOUNDATION_M2_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_STATUS_ROW_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_STATUS_ROW_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_EXPECTED_SLICE_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    m3::PRODUCTION_GUARD_SUPPORT_EXPECTED_SLICE_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
