import { WorkbenchHostContext } from "workbench/host_context.slint";
import { WorkbenchHostScaffold } from "workbench/host_scaffold.slint";
import { HostWindowShellData, HostWindowLayoutData, HostWindowSurfaceData } from "workbench/host_components.slint";
import { PaneSurfaceHostContext } from "workbench/pane_surface.slint";

export { WorkbenchHostContext } from "workbench/host_context.slint";
export { PaneSurfaceHostContext } from "workbench/pane_surface.slint";

export component UiHostWindow inherits Window {
    in property <HostWindowSurfaceData> host_surface_data <=> host.host_surface_data;
    in property <HostWindowShellData> host_shell <=> host.host_shell;
    in property <HostWindowLayoutData> host_layout <=> host.host_layout;
    out property <float> shell_width_px <=> host.shell_width_px;
    out property <float> shell_height_px <=> host.shell_height_px;
    out property <float> viewport_width <=> host.viewport_width;
    out property <float> viewport_height <=> host.viewport_height;
    preferred-width: 1600px;
    preferred-height: 980px;
    min-width: root.host_shell.shell_min_width_px * 1px;
    min-height: root.host_shell.shell_min_height_px * 1px;
    max-width: 16777215px;
    max-height: 16777215px;
    no-frame: false;
    resize-border-width: 8px;
    title: root.host_shell.native_window_title != "" ? root.host_shell.native_window_title : "Zircon Editor";
    background: #1f232a;
    default-font-family: "JetBrains Sans, Segoe UI, Microsoft YaHei UI, Noto Sans";

    host := WorkbenchHostScaffold {
        width: root.width;
        height: root.height;
    }
}
