import { UiHostContext } from "workbench/host_context.slint";
import { UiHostScaffold } from "workbench/host_scaffold.slint";
import { HostWindowBootstrapData } from "workbench/host_components.slint";
import { HostWindowPresentationData } from "workbench/host_root.slint";

export { UiHostContext } from "workbench/host_context.slint";
export { PaneSurfaceHostContext } from "workbench/pane_surface_host_context.slint";
export { FrameRect, FloatingWindowData, HostWindowBootstrapData, HostWindowLayoutData, HostWindowShellData, HostWindowSurfaceData, HostNativeFloatingWindowSurfaceData } from "workbench/host_components.slint";
export { HostWindowPresentationData } from "workbench/host_root.slint";
export { ModulePluginStatusData, ModulePluginsPaneData, PaneData, ProjectOverviewData, SceneNodeData } from "workbench/pane_data.slint";
export { HostWindowSceneData } from "workbench/host_scene.slint";

export component UiHostWindow inherits Window {
    in property <HostWindowPresentationData> host_presentation;
    out property <HostWindowBootstrapData> host_window_bootstrap <=> host.host_window_bootstrap;
    preferred-width: 1600px;
    preferred-height: 980px;
    min-width: root.host_presentation.host_shell.shell_min_width_px * 1px;
    min-height: root.host_presentation.host_shell.shell_min_height_px * 1px;
    max-width: 16777215px;
    max-height: 16777215px;
    no-frame: false;
    resize-border-width: 8px;
    title: root.host_presentation.host_shell.native_window_title != "" ? root.host_presentation.host_shell.native_window_title : "Zircon Editor";
    background: #1f232a;
    default-font-family: "JetBrains Sans, Segoe UI, Microsoft YaHei UI, Noto Sans";

    host := UiHostScaffold {
        width: root.width;
        height: root.height;
        host_presentation: root.host_presentation;
    }
}
