use crate::core::framework::render::PostProcessGraphResourceNames;
use crate::graphics::pipeline::RenderPassStage;
use crate::graphics::shader::motion_vector_tile_max_pass_plan;
use crate::render_graph::{QueueLane, RenderGraphAttachmentOps, RenderGraphComputeWorkload};

use super::super::render_feature_descriptor::RenderFeatureDescriptor;
use super::super::render_feature_pass_descriptor::RenderFeaturePassDescriptor;
use super::compute_workload::{
    COLOR_LUT_BAKE_PIPELINE_LABEL, COLOR_LUT_BAKE_WORKGROUP_SIZE,
    EXPOSURE_HISTOGRAM_PIPELINE_LABEL, EXPOSURE_HISTOGRAM_WORKGROUP_SIZE,
    EXPOSURE_RESOLVE_PIPELINE_LABEL, EXPOSURE_RESOLVE_WORKGROUP_SIZE,
};

pub(in crate::graphics::feature::builtin_render_feature_descriptor) fn descriptor(
) -> RenderFeatureDescriptor {
    let motion_vector_tile_max_plan = motion_vector_tile_max_pass_plan();

    RenderFeatureDescriptor::new(
        "post_process",
        vec!["view".to_string(), "post_process".to_string()],
        Vec::new(),
        vec![
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-tile-max",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-tile-max")
            .with_fullscreen_pass_plan(motion_vector_tile_max_plan)
            .read_texture(PostProcessGraphResourceNames::SCENE_VELOCITY)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-tile-max-coarse",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-tile-max-coarse")
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-neighbor-max",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-neighbor-max")
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "depth-of-field-prepare",
                QueueLane::Graphics,
            )
            .with_executor_id("post.depth-of-field-prepare")
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::DEPTH_OF_FIELD_COC,
                RenderGraphAttachmentOps::clear_store(),
            )
            .write_texture_with_ops(
                PostProcessGraphResourceNames::DEPTH_OF_FIELD_BOKEH,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "depth-of-field",
                QueueLane::Graphics,
            )
            .with_executor_id("post.depth-of-field")
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::TAA_OUTPUT)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELD_COC)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELD_BOKEH)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::DEPTH_OF_FIELDED,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-blur",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-blur")
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELDED)
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::TAA_OUTPUT)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::MOTION_BLURRED,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "exposure-histogram",
                QueueLane::AsyncCompute,
            )
            .with_executor_id("post.exposure.histogram")
            .with_compute_workload(RenderGraphComputeWorkload::per_pixel(
                EXPOSURE_HISTOGRAM_PIPELINE_LABEL,
                EXPOSURE_HISTOGRAM_WORKGROUP_SIZE,
                PostProcessGraphResourceNames::SCENE_COLOR,
                [
                    EXPOSURE_HISTOGRAM_WORKGROUP_SIZE[0],
                    EXPOSURE_HISTOGRAM_WORKGROUP_SIZE[1],
                ],
            ))
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .write_buffer(PostProcessGraphResourceNames::EXPOSURE_HISTOGRAM),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "exposure-resolve",
                QueueLane::AsyncCompute,
            )
            .with_executor_id("post.exposure.resolve")
            .with_compute_workload(RenderGraphComputeWorkload::fixed(
                EXPOSURE_RESOLVE_PIPELINE_LABEL,
                EXPOSURE_RESOLVE_WORKGROUP_SIZE,
                [1, 1, 1],
            ))
            .read_buffer(PostProcessGraphResourceNames::EXPOSURE_HISTOGRAM)
            .read_external_buffer(PostProcessGraphResourceNames::EXPOSURE_PREVIOUS)
            .write_buffer(PostProcessGraphResourceNames::EXPOSURE_CURRENT),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-reflection-pyramid",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-reflection-pyramid")
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_buffer(PostProcessGraphResourceNames::LIGHT_LIST)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-reflection-pyramid-coarse",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-reflection-pyramid-coarse")
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID)
            .read_buffer(PostProcessGraphResourceNames::LIGHT_LIST)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID_COARSE,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-specular-occlusion",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-specular-occlusion")
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::GBUFFER_MATERIAL)
            .read_external_texture(PostProcessGraphResourceNames::AMBIENT_OCCLUSION)
            .read_buffer(PostProcessGraphResourceNames::LIGHT_LIST)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_SPECULAR_OCCLUSION,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-resolve",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-resolve")
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::GBUFFER_NORMAL)
            .read_texture(PostProcessGraphResourceNames::GBUFFER_MATERIAL)
            .read_texture(PostProcessGraphResourceNames::HZB_FURTHEST)
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID)
            .read_texture(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID_COARSE,
            )
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_SPECULAR_OCCLUSION)
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX)
            .read_buffer(PostProcessGraphResourceNames::LIGHT_LIST)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_HISTORY,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "scene-composite",
                QueueLane::Graphics,
            )
            .with_executor_id("post.scene-composite")
            .read_texture(PostProcessGraphResourceNames::MOTION_BLURRED)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELDED)
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::TAA_OUTPUT)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_HISTORY)
            .read_buffer(PostProcessGraphResourceNames::EXPOSURE_CURRENT)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCENE_COMPOSITED,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "blur",
                QueueLane::Graphics,
            )
            .with_executor_id("post.blur")
            .read_texture(PostProcessGraphResourceNames::SCENE_COMPOSITED)
            .read_texture(PostProcessGraphResourceNames::MOTION_BLURRED)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELDED)
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::TAA_OUTPUT)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::BLURRED,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "color-lut-bake",
                QueueLane::AsyncCompute,
            )
            .with_executor_id("post.color-lut-bake")
            .with_compute_workload(RenderGraphComputeWorkload::fixed(
                COLOR_LUT_BAKE_PIPELINE_LABEL,
                COLOR_LUT_BAKE_WORKGROUP_SIZE,
                [8, 8, 8],
            ))
            .read_buffer(PostProcessGraphResourceNames::EXPOSURE_CURRENT)
            .write_storage_texture(PostProcessGraphResourceNames::COLOR_LUT),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "uber",
                QueueLane::Graphics,
            )
            .with_executor_id("post.uber")
            .with_side_effects()
            .read_texture(PostProcessGraphResourceNames::BLURRED)
            .read_texture(PostProcessGraphResourceNames::SCENE_COMPOSITED)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELDED)
            .read_texture(PostProcessGraphResourceNames::MOTION_BLURRED)
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::TAA_OUTPUT)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX)
            .read_external_texture(PostProcessGraphResourceNames::AMBIENT_OCCLUSION)
            .read_texture(PostProcessGraphResourceNames::CONTACT_SHADOW_OCCLUSION)
            .read_texture(PostProcessGraphResourceNames::BLOOM)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELD_COC)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELD_BOKEH)
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_HISTORY)
            .read_texture(PostProcessGraphResourceNames::COLOR_LUT)
            .read_texture(PostProcessGraphResourceNames::HYBRID_GI_LIGHTING)
            .read_buffer(PostProcessGraphResourceNames::LIGHT_LIST)
            .read_buffer(PostProcessGraphResourceNames::EXPOSURE_CURRENT)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::TONEMAPPED,
                RenderGraphAttachmentOps::clear_store(),
            )
            .write_texture(PostProcessGraphResourceNames::GLOBAL_ILLUMINATION),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "upscale",
                QueueLane::Graphics,
            )
            .with_executor_id("post.upscale")
            .read_texture(PostProcessGraphResourceNames::TONEMAPPED)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::UPSCALED,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "output-transfer",
                QueueLane::Graphics,
            )
            .with_executor_id("post.output-transfer")
            .read_texture(PostProcessGraphResourceNames::TONEMAPPED)
            .write_external_texture_with_ops(
                PostProcessGraphResourceNames::FINAL_COLOR,
                RenderGraphAttachmentOps::clear_store(),
            ),
        ],
    )
}
