use crate::core::framework::render::PostProcessGraphResourceNames;
use crate::graphics::pipeline::RenderPassStage;
use crate::render_graph::{QueueLane, RenderGraphAttachmentOps};

use super::super::render_feature_descriptor::RenderFeatureDescriptor;
use super::super::render_feature_pass_descriptor::RenderFeaturePassDescriptor;

pub(in crate::graphics::feature::builtin_render_feature_descriptor) fn descriptor(
) -> RenderFeatureDescriptor {
    RenderFeatureDescriptor::new(
        "post_process",
        vec!["view".to_string(), "post_process".to_string()],
        Vec::new(),
        vec![
            RenderFeaturePassDescriptor::new(
                RenderPassStage::DepthPrepass,
                "motion-vector-clear",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-clear")
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCENE_MOTION_VECTOR,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-camera",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-camera")
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCENE_MOTION_VECTOR,
                RenderGraphAttachmentOps::load_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-object",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-object")
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCENE_MOTION_VECTOR,
                RenderGraphAttachmentOps::load_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-tile-max",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-tile-max")
            .read_texture(PostProcessGraphResourceNames::SCENE_MOTION_VECTOR)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-tile-max-coarse",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-tile-max-coarse")
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "motion-vector-neighbor-max",
                QueueLane::Graphics,
            )
            .with_executor_id("post.motion-vector-neighbor-max")
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "depth-of-field-prepare",
                QueueLane::Graphics,
            )
            .with_executor_id("post.depth-of-field-prepare")
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::DEPTH_OF_FIELD_COC,
                RenderGraphAttachmentOps::clear_store(),
            )
            .write_texture_with_ops(
                PostProcessGraphResourceNames::DEPTH_OF_FIELD_BOKEH,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-reflection-pyramid",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-reflection-pyramid")
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-reflection-pyramid-coarse",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-reflection-pyramid-coarse")
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID_COARSE,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-specular-occlusion",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-specular-occlusion")
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::GBUFFER_MATERIAL)
            .read_external(PostProcessGraphResourceNames::AMBIENT_OCCLUSION)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_SPECULAR_OCCLUSION,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "screen-space-reflection-resolve",
                QueueLane::Graphics,
            )
            .with_executor_id("post.screen-space-reflection-resolve")
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::GBUFFER_NORMAL)
            .read_texture(PostProcessGraphResourceNames::GBUFFER_MATERIAL)
            .read_texture(PostProcessGraphResourceNames::HZB_FURTHEST)
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID)
            .read_texture(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID_COARSE,
            )
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_SPECULAR_OCCLUSION)
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX)
            .write_texture_with_ops(
                PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_HISTORY,
                RenderGraphAttachmentOps::clear_store(),
            ),
            RenderFeaturePassDescriptor::new(
                RenderPassStage::PostProcess,
                "post-process",
                QueueLane::Graphics,
            )
            .with_executor_id("post.stack")
            .with_side_effects()
            .read_texture(PostProcessGraphResourceNames::SCENE_COLOR)
            .read_texture(PostProcessGraphResourceNames::SCENE_DEPTH)
            .read_texture(PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX)
            .read_external(PostProcessGraphResourceNames::AMBIENT_OCCLUSION)
            .read_texture(PostProcessGraphResourceNames::CONTACT_SHADOW_OCCLUSION)
            .read_external(PostProcessGraphResourceNames::BLOOM)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELD_COC)
            .read_texture(PostProcessGraphResourceNames::DEPTH_OF_FIELD_BOKEH)
            .read_texture(PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_HISTORY)
            .write_external(PostProcessGraphResourceNames::FINAL_COMPOSITED)
            .write_external(PostProcessGraphResourceNames::FINAL_COLOR)
            .write_external(PostProcessGraphResourceNames::GLOBAL_ILLUMINATION),
        ],
    )
}
