#[path = "inventory/audit.rs"]
mod audit;
#[path = "inventory/behavior.rs"]
mod behavior;
#[path = "inventory/task_model.rs"]
mod task_model;

pub(super) const JOB_SYSTEM_MODULE_MAX_LINES: usize = 500;

pub(super) use audit::{
    EXPECTED_DIRECT_RAYON_PATHS, FORBIDDEN_LEGACY_DIAGNOSTIC_ANCHORS,
    FORBIDDEN_SCHEDULE_EXECUTOR_RAYON_ANCHORS, MIRROR_DOC_ANCHORS, SCHEDULE_EXECUTOR_ANCHORS,
};
pub(super) use behavior::BEHAVIOR_TEST_ANCHORS;
pub(super) use task_model::{
    BOUNDED_STREAM_IO_CAPTURE_ANCHORS, BOUNDED_STREAM_IO_LANE_ANCHORS,
    BOUNDED_STREAM_IO_STATE_ANCHORS, BOUNDED_STREAM_IO_WORKER_ANCHORS, CALLBACK_DISPATCHER_ANCHORS,
    DIAGNOSTIC_ANCHORS, ENGINE_TASK_GRAPH_ANCHORS, EXPECTED_JOB_SYSTEM_MODULES, JOB_HANDLE_ANCHORS,
    JOB_SCHEDULER_ANCHORS, JOB_SCHEDULER_PENDING_ANCHORS, JOB_SCHEDULER_TEST_ANCHORS,
    PARALLEL_FOR_ANCHORS, REPORT_ANCHORS, RETAINED_BYTE_BUDGET_ANCHORS, TASKS_MOD_DECLARATIONS,
    TASKS_MOD_PUBLIC_ANCHORS, TASK_CANCELLATION_POLICY_ANCHORS, TASK_DESCRIPTOR_ANCHORS,
    TASK_DIAGNOSTIC_JOURNAL_ANCHORS, TASK_DIAGNOSTIC_OBSERVATION_ANCHORS,
    TASK_GRAPH_CANCELLATION_ANCHORS, TASK_GRAPH_HANDLE_ANCHORS, TASK_GRAPH_LEASE_ANCHORS,
    TASK_GRAPH_SCHEDULER_ADMISSION_ANCHORS, TASK_GRAPH_SCOPE_ANCHORS, TASK_ID_ANCHORS,
    TASK_POOL_DESCRIPTOR_ANCHORS, TASK_POOL_KIND_ANCHORS, TASK_POOL_SUBMISSION_ANCHORS,
    TASK_STATE_ANCHORS, TASK_STATUS_ANCHORS, TIMER_ANCHORS,
};
