// @generated by woc_contract_codegen; do not edit.
pub const CONTRACT_SCHEMA_VERSION: u16 = 1;
pub const PROTOCOL_VERSION: u16 = 3;
pub const SCHEMA_FINGERPRINT_HEX: &str =
    "7e69e47677529a0cbe4352a5f555cdddb5e8586fed885cca5612abaa93752719";
pub const SCHEMA_FINGERPRINT_BYTES: [u8; 32] = [
    0x7e, 0x69, 0xe4, 0x76, 0x77, 0x52, 0x9a, 0x0c, 0xbe, 0x43, 0x52, 0xa5, 0xf5, 0x55, 0xcd, 0xdd,
    0xb5, 0xe8, 0x58, 0x6f, 0xed, 0x88, 0x5c, 0xca, 0x56, 0x12, 0xab, 0xaa, 0x93, 0x75, 0x27, 0x19,
];

pub mod contract_id {
    pub const ENTITY_REF: u16 = 1;
    pub const FIXED_TICK_INPUT: u16 = 2;
    pub const COMMAND: u16 = 3;
    pub const EVENT: u16 = 4;
    pub const WORLD_SNAPSHOT: u16 = 5;
    pub const SAVE_STATE: u16 = 6;
    pub const NETWORK_ENVELOPE: u16 = 7;
    pub const RL_OBSERVATION_BATCH: u16 = 8;
    pub const RL_ACTION_BATCH: u16 = 9;
    pub const MOVEMENT_FRAME: u16 = 10;
    pub const OFFLINE_SESSION_BOOTSTRAP: u16 = 11;
}

pub mod entity_ref_field_id {
    pub const ID: u16 = 1;
    pub const GENERATION: u16 = 2;
}

pub mod fixed_tick_input_field_id {
    pub const TICK: u16 = 1;
    pub const COMMANDS: u16 = 2;
    pub const COMMANDS_MAX_LENGTH: u64 = 4096;
    pub const WALL_TIME_FORBIDDEN: u16 = 3;
    pub const COMMITTED_STATE: u16 = 4;
    pub const COMMITTED_STATE_MAX_LENGTH: u64 = 67108864;
    pub const COMMITTED_STATE_DIGEST: u16 = 5;
    pub const GENERATION: u16 = 6;
    pub const MOVEMENT_FRAMES: u16 = 7;
    pub const MOVEMENT_FRAMES_MAX_LENGTH: u64 = 65536;
    pub const OFFLINE_BOOTSTRAP: u16 = 8;
    pub const OFFLINE_BOOTSTRAP_MAX_LENGTH: u64 = 66;
}

pub mod command_field_id {
    pub const COMMAND_ID: u16 = 1;
    pub const ACTOR: u16 = 2;
    pub const SEQUENCE: u16 = 3;
    pub const PAYLOAD: u16 = 4;
    pub const PAYLOAD_MAX_LENGTH: u64 = 65536;
}

pub mod event_field_id {
    pub const EVENT_ID: u16 = 1;
    pub const SEQUENCE: u16 = 2;
    pub const PAYLOAD: u16 = 3;
    pub const PAYLOAD_MAX_LENGTH: u64 = 65536;
}

pub mod world_snapshot_field_id {
    pub const TICK: u16 = 1;
    pub const STATE_DIGEST: u16 = 2;
    pub const EVENT_DIGEST: u16 = 3;
    pub const STATE: u16 = 4;
    pub const STATE_MAX_LENGTH: u64 = 67108864;
    pub const EVENTS: u16 = 5;
    pub const EVENTS_MAX_LENGTH: u64 = 8192;
}

pub mod save_state_field_id {
    pub const SCHEMA_FINGERPRINT: u16 = 1;
    pub const SCHEMA_FINGERPRINT_MAX_LENGTH: u64 = 32;
    pub const GENERATION: u16 = 2;
    pub const TICK: u16 = 3;
    pub const STATE: u16 = 4;
    pub const STATE_MAX_LENGTH: u64 = 67108864;
}

pub mod network_envelope_field_id {
    pub const PROTOCOL_VERSION: u16 = 1;
    pub const KIND: u16 = 2;
    pub const SEQUENCE: u16 = 3;
    pub const ACKNOWLEDGEMENT: u16 = 4;
    pub const PAYLOAD: u16 = 5;
    pub const PAYLOAD_MAX_LENGTH: u64 = 1048576;
}

pub mod rl_observation_batch_field_id {
    pub const TICK: u16 = 1;
    pub const ENVIRONMENT_IDS: u16 = 2;
    pub const ENVIRONMENT_IDS_MAX_LENGTH: u64 = 4096;
    pub const OFFSETS: u16 = 3;
    pub const OFFSETS_MAX_LENGTH: u64 = 4097;
    pub const OBSERVATIONS: u16 = 4;
    pub const OBSERVATIONS_MAX_LENGTH: u64 = 67108864;
}

pub mod rl_action_batch_field_id {
    pub const TICK: u16 = 1;
    pub const ENVIRONMENT_IDS: u16 = 2;
    pub const ENVIRONMENT_IDS_MAX_LENGTH: u64 = 4096;
    pub const OFFSETS: u16 = 3;
    pub const OFFSETS_MAX_LENGTH: u64 = 4097;
    pub const ACTIONS: u16 = 4;
    pub const ACTIONS_MAX_LENGTH: u64 = 16777216;
}

pub mod movement_frame_field_id {
    pub const ACTOR: u16 = 1;
    pub const SEQUENCE: u16 = 2;
    pub const FORWARD: u16 = 3;
    pub const BACK: u16 = 4;
    pub const TURN_LEFT: u16 = 5;
    pub const TURN_RIGHT: u16 = 6;
    pub const STRAFE_LEFT: u16 = 7;
    pub const STRAFE_RIGHT: u16 = 8;
    pub const JUMP: u16 = 9;
    pub const HAS_FACING: u16 = 10;
    pub const FACING: u16 = 11;
}

pub mod offline_session_bootstrap_field_id {
    pub const LAUNCH_VERSION: u16 = 1;
    pub const WORLD_SEED: u16 = 2;
    pub const PLAYER_CLASS: u16 = 3;
    pub const PLAYER_NAME: u16 = 4;
    pub const PLAYER_NAME_MAX_LENGTH: u64 = 16;
    pub const SKIN_VARIANT: u16 = 5;
    pub const WEAPON_SKIN_OWNED: u16 = 6;
    pub const WEAPON_SKIN_OWNED_MAX_LENGTH: u64 = 29;
    pub const WEAPON_SKIN_LOADOUT_CODES: u16 = 7;
    pub const WEAPON_SKIN_LOADOUT_CODES_MAX_LENGTH: u64 = 8;
}

pub mod message_kind_value {
    pub const FIXED_TICK_INPUT: u16 = 1;
    pub const COMMAND: u16 = 2;
    pub const EVENT: u16 = 3;
    pub const WORLD_SNAPSHOT: u16 = 4;
    pub const SAVE_STATE: u16 = 5;
    pub const NETWORK_ENVELOPE: u16 = 6;
    pub const RL_OBSERVATION_BATCH: u16 = 7;
    pub const RL_ACTION_BATCH: u16 = 8;
}

pub mod limit {
    pub const COMMANDS_PER_TICK: u64 = 4096;
    pub const ENTITIES_PER_SNAPSHOT: u64 = 65536;
    pub const EVENTS_PER_TICK: u64 = 8192;
    pub const FRAME_PAYLOAD_BYTES: u64 = 134217728;
    pub const OPAQUE_STATE_BYTES: u64 = 67108864;
    pub const RL_ENVIRONMENTS_PER_BATCH: u64 = 4096;
}
