mod assign_execution_owned_indirect_args;
mod bind_compiled_scene_graph_resources;
mod bind_environment_ibl_graph_resources;
mod bind_execution_owned_graph_resources;
mod bind_frame_graph_resources;
mod bind_history_graph_resources;
mod bind_plugin_graph_resources;
mod bind_ssao_compute_graph_resources;
mod bind_taa_reactive_mask_graph_resource;
mod build_compiled_scene_draws;
mod commit_compiled_scene_frame_success;
mod compiled_scene_frame_foundation;
mod execute_compiled_scene_graph_stages;
#[cfg(test)]
mod execute_compiled_scene_graph_stages_tests;
pub(in crate::graphics::scene::scene_renderer::core::scene_renderer_core_render_compiled_scene) mod execute_graph_stage;
mod final_target_output;
mod frame_lifecycle;
mod irradiance_volume_selection;
mod pipeline_resource_usage;
mod prepare_compiled_scene_graph_frame;
mod prepare_compiled_scene_mesh_submission;
mod prepare_overlay_buffers;
mod render;
mod render_graph_pass_frame_services;
mod sprite_stage_selection;
mod terminal_frame_packet;

pub(in crate::graphics::scene::scene_renderer::core::scene_renderer_core_render_compiled_scene) use render_graph_pass_frame_services::RenderGraphPassFrameServices;
mod submit_compiled_scene_frame;
