mod assign_execution_owned_indirect_args;
mod bind_compiled_scene_graph_resources;
mod bind_execution_owned_graph_resources;
mod bind_frame_graph_resources;
mod bind_history_graph_resources;
mod bind_plugin_graph_resources;
mod build_compiled_scene_draws;
mod execute_compiled_scene_graph_stages;
pub(in crate::graphics::scene::scene_renderer::core::scene_renderer_core_render_compiled_scene) mod execute_graph_stage;
mod final_target_output;
mod prepare_overlay_buffers;
mod render;
mod submit_compiled_scene_frame;
