use super::*;

pub(super) const LOCK_POISON_ROW_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children.rs",
        LOCK_POISON_ROW_DATA_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status.rs",
        LOCK_POISON_STATUS_ROWS_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status/status_rows.rs",
        LOCK_POISON_STATUS_STATUS_ROWS_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status/policy_guards.rs",
        LOCK_POISON_STATUS_POLICY_GUARDS_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status/core_runtime_recovery.rs",
        LOCK_POISON_STATUS_CORE_RUNTIME_RECOVERY_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status/runtime_services_recovery.rs",
        LOCK_POISON_STATUS_RUNTIME_SERVICES_RECOVERY_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status/resource_render_input_recovery.rs",
        LOCK_POISON_STATUS_RESOURCE_RENDER_INPUT_RECOVERY_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status/script_vm_recovery.rs",
        LOCK_POISON_STATUS_SCRIPT_VM_RECOVERY_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/lock_poison_status/row_data_owner.rs",
        LOCK_POISON_STATUS_ROW_DATA_OWNER_PATH,
        90,
    ),
];
