use super::*;

pub(super) const STATUS_DOC_SELF_ANCHORS: &[&str] = &[
    "Runtime 15 M3 code review findings status-doc guard child-owner split",
    "runtime_15_code_review_findings_status_docs_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status_docs.rs",
    "runtime_15_code_review_findings_status_docs_are_child_owner",
    "Runtime 15 M3 code review findings status-doc status-mirror child-owner split",
    "runtime_15_code_review_findings_status_docs_status_mirror_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_mirrors.rs",
    "runtime_15_code_review_findings_status_docs_status_mirrors_are_child_owner",
    "Runtime 15 M3 code review findings status-doc root inventory child split",
    "runtime_15_code_review_findings_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_row_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_inventory.rs",
    "runtime_15_code_review_findings_status_docs_root_inventory_is_child_owned",
    "Runtime 15 M3 code review findings status-doc source anchors child-owner split",
    "runtime_15_code_review_findings_status_docs_source_anchors_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors.rs",
    "runtime_15_code_review_findings_status_docs_source_anchors_are_child_owner",
    "Runtime 15 M3 code review findings status-doc source anchors folder-backed split",
    "runtime_15_code_review_findings_status_docs_source_anchors_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/review_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/native_typed_error.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/runtime_surface.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/structure_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/status_mirrors.rs",
    "runtime_15_code_review_findings_status_docs_source_anchors_folder_backed_status_is_current",
    "Runtime 15 M3 code review findings status-row source child-tree sync",
    "runtime_15_code_review_findings_status_row_source_child_tree_sync_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/sync.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/sources/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/status_mirrors.rs",
    "runtime_15_code_review_findings_status_row_source_reads_structure_guard_children",
    "Runtime 15 M3 code review findings status-doc status anchors child-owner split",
    "runtime_15_code_review_findings_status_docs_status_anchors_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors.rs",
    "runtime_15_code_review_findings_status_docs_status_anchors_are_child_owner",
    "Runtime 15 M3 code review findings status-doc status anchors folder-backed split",
    "runtime_15_code_review_findings_status_docs_status_anchors_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/map_anchors.rs",
    "runtime_15_code_review_findings_status_docs_status_child_anchors_are_child_owned",
    "runtime_15_code_review_findings_status_docs_status_map_anchors_are_child_owned",
    "runtime_15_code_review_findings_status_docs_status_anchors_are_folder_backed",
    "Runtime 15 M3 code review findings status-doc status anchor guard folder-backed split",
    "runtime_15_code_review_findings_status_docs_status_anchor_guard_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/folder_backing.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/status_mirrors.rs",
    "runtime_15_code_review_findings_status_docs_status_anchor_guard_is_folder_backed",
    "runtime_15_code_review_findings_status_docs_status_anchor_guard_folder_backed_status_is_current",
    "runtime_15_code_review_findings_status_docs_status_anchor_guard_children_line_budgets_are_current",
    "Runtime 15 M3 code review findings status-doc status-anchor child-ownership child split",
    "runtime_15_code_review_findings_status_docs_status_anchor_child_ownership_child_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/moved_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/forwarding.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/status_mirrors.rs",
    "runtime_15_code_review_findings_status_docs_status_anchor_child_ownership_is_child_backed",
    STATUS_DOC_CHILD_ANCHOR_LIST_SPLIT_NAME,
    STATUS_DOC_CHILD_ANCHOR_LIST_SPLIT_ID,
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/structure_guards.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/folder_backed_summary.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/status_docs.rs",
    STATUS_DOC_CHILD_ANCHOR_LIST_SPLIT_GUARD,
    STATUS_DOC_CHILD_ANCHOR_ROUTE_FOLDER_BACKED_SPLIT_NAME,
    STATUS_DOC_CHILD_ANCHOR_ROUTE_FOLDER_BACKED_SPLIT_ID,
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/aggregation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/boundary_samples.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/source_blob.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/split_layout.rs",
    STATUS_DOC_CHILD_ANCHOR_ROUTE_FOLDER_BACKED_SPLIT_GUARD,
];

pub(super) const STATUS_DOC_SELF_BOUNDARY_ANCHORS: &[&str] = &[
    "Runtime 15 M3 code review findings status-doc guard child-owner split",
    "runtime_15_code_review_findings_status_docs_status_anchor_guard_folder_backed_status_is_current",
];
