use super::*;

pub(super) fn assert_runtime_surface_source_anchors(label: &str, source: &str) {
    assert_contains_all(
        label,
        source,
        &[
            "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/texture_import_settings.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/scaffold.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/first_party_descriptors.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/test_fixtures.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/private_fields.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/constructor_retirement.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/status_mirrors.rs",
            "review_f8_texture_import_settings_use_fallible_apply_not_with",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d11_test_runtime_fixture.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d12_runtime_exports.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/manifest_parity.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_crates.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_exports.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_manifests.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d5_editor_authoring.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d6_runtime_plugin_id.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d8_registration_builder.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d9_editor_runtime_mirror.rs",
            "review_d10_animation_physics_tests_use_sdk_bridge_call",
            "review_d1_plugin_capabilities_use_single_source_and_sdk_builder_mirror",
            "review_d11_animation_physics_tests_use_sdk_test_runtime_fixture",
            "review_d6_runtime_plugin_id_accepts_external_string_keys",
            "review_d8_runtime_registration_builder_original_evidence_paths_use_sdk_builder",
            "review_d12_runtime_helper_exports_use_sdk_macro",
            "review_d9_editor_runtime_mirror_consumers_use_sdk_declaration",
            "review_d13_importer_runtime_exports_use_sdk_macro",
            "review_d13_importer_runtime_manifests_use_sdk_builder",
            "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
            "d13_importer_manifest_parity_guard_static_passed_cargo_deferred",
            "d13_importer_top_row_closed_status_static_passed_cargo_deferred",
            "ds8_d3_native_fixture_top_row_closed_status_static_passed_cargo_deferred",
            "p0_f1_f2_f4_top_row_closed_status_static_passed_cargo_deferred",
            "d7_core_workspace_dependency_top_row_closed_status_static_passed_cargo_deferred",
            "f5_f6_f7_typed_error_top_row_closed_status_static_passed_cargo_deferred",
            "f8_f9_f10_runtime_surface_top_row_closed_status_static_passed_cargo_deferred",
            "f17_f18_lookup_manager_top_row_closed_status_static_passed_cargo_deferred",
            "review_priority_recommendation_d13_parity_sync_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/f12_dead_code.rs",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "Runtime 15 M3 P0 robustness review guard child-owner split",
            "runtime_15_p0_robustness_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_host_callbacks.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/lock_poison.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/render_submit.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/priority_recommendation.rs",
            "review_f1_native_host_callbacks_catch_unwind_before_crossing_ffi",
            "review_f2_scene_eventbus_locks_recover_after_poison",
            "review_f4_render_submit_capability_gaps_return_typed_errors",
            "runtime_15_p0_robustness_review_guards_are_child_owners",
            "Runtime 15 M3 P0 native fixture review guard leaf-owner split",
            "runtime_15_p0_native_fixture_review_guard_leaf_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 F8 API convergence review guard child-owner split",
            "runtime_15_f8_api_convergence_review_guard_child_owner_split_static_passed_cargo_deferred",
            "runtime_15_f8_api_convergence_review_guards_are_child_owners",
            "Runtime 15 M3 F8 descriptor review guard child-owner split",
            "runtime_15_f8_descriptor_review_guard_child_owner_split_static_passed_cargo_deferred",
        ],
    );
}
