use super::native_dynamic_package_plan::{
    append_native_dynamic_abi_contract_toml, NativeDynamicPackageExportPlan,
};

pub(super) fn native_plugin_load_manifest_template(
    packages: &[NativeDynamicPackageExportPlan],
) -> String {
    let mut output = String::from(
        "# Generated by Zircon export. Native dynamic plugins are loaded from these packages.\n",
    );
    for package in packages {
        output.push_str("\n[[plugins]]\n");
        output.push_str(&format!("id = {:?}\n", package.package_id));
        output.push_str(&format!("path = {:?}\n", package.path));
        output.push_str(&format!("manifest = {:?}\n", package.manifest));
        output.push_str(&format!(
            "package_report = {:?}\n",
            format!("{}/native_dynamic_package.toml", package.path)
        ));
        append_native_dynamic_abi_contract_toml(&mut output, "plugins.abi", &package.abi);
    }
    output
}
