//! 为原生加载器生成包目录与 ABI 绑定清单；仅在计划含 NativeDynamic 包时进入生成文件列表。
use std::fmt::Write as _;

use super::native_dynamic_package_plan::{
    append_native_dynamic_abi_contract_toml, NativeDynamicPackageExportPlan,
};

/// 把计划中的包路径及 ABI 信息写给导出后的 loader；条目顺序沿用原生包计划。
pub(super) fn native_plugin_load_manifest_template(
    packages: &[NativeDynamicPackageExportPlan],
) -> String {
    let mut output = String::from(
        "# Generated by Zircon export. Native dynamic plugins are loaded from these packages.\n",
    );
    for package in packages {
        let package_report = format!("{}/native_dynamic_package.toml", package.path);
        writeln!(
            output,
            "\n[[plugins]]\nid = {:?}\npath = {:?}\nmanifest = {:?}\npackage_report = {:?}",
            package.package_id, package.path, package.manifest, package_report
        )
        .expect("writing native plugin load manifest to String cannot fail");
        append_native_dynamic_abi_contract_toml(&mut output, "plugins.abi", &package.abi);
    }
    output
}

#[cfg(test)]
#[path = "tests/native_plugin_load_manifest_template.rs"]
mod tests;
