pub(super) fn native_plugin_load_manifest_template(package_ids: &[String]) -> String {
    let mut output = String::from(
        "# Generated by Zircon export. Native dynamic plugins are loaded from these packages.\n",
    );
    for package_id in package_ids {
        output.push_str("\n[[plugins]]\n");
        output.push_str(&format!("id = {package_id:?}\n"));
        output.push_str(&format!("path = {:?}\n", format!("plugins/{package_id}")));
        output.push_str(&format!(
            "manifest = {:?}\n",
            format!("plugins/{package_id}/plugin.toml")
        ));
    }
    output
}
