export function accountCopy(language: string) {
  const chinese = language === "Chinese";
  const pair = (en: string, zh: string) => chinese ? zh : en;
  return {
    pair,
    title: pair("Account and teams", "账号与团队"),
    unavailable: pair("Account service is not configured", "账号服务未配置"),
    signedOut: pair("Signed out", "尚未登录"),
    signIn: pair("Sign in", "登录"),
    signOut: pair("Sign out", "退出登录"),
    refresh: pair("Refresh session", "刷新会话"),
    cancel: pair("Cancel sign-in", "取消登录"),
    pending: pair("Signing in...", "正在登录..."),
    loading: pair("Loading...", "正在加载..."),
    retry: pair("Retry", "重试"),
    refreshList: pair("Refresh list", "刷新列表"),
    more: pair("Load more", "加载更多"),
    none: pair("No records", "暂无记录"),
    select: pair("No organization selected", "未选择组织"),
    organizations: pair("Organizations", "组织"),
    members: pair("Members", "成员"),
    projects: pair("Projects", "项目"),
    memberProjectTabs: pair("Members and projects", "成员与项目"),
    invitations: pair("Invitations", "邀请"),
    issuedInvitations: pair("Sent invitations", "已发送邀请"),
    organizationName: pair("Organization name", "组织名称"),
    projectName: pair("Project name", "项目名称"),
    selectLocalProjectToLink: pair("Select a local project in Hub to link it with an existing team project.", "请先在 Hub 中选择本地项目，再与现有团队项目关联。"),
    linkSelectedProject: pair("Link selected local project", "关联已选本地项目"),
    linkedLocalProject: pair("Linked to selected local project", "已关联已选本地项目"),
    createOrganization: pair("Create organization", "创建组织"),
    createProject: pair("Create project", "创建项目"),
    editMember: pair("Edit member", "编辑成员"),
    saveMember: pair("Save member", "保存成员"),
    role: pair("Role", "角色"),
    active: pair("Active membership", "启用成员资格"),
    transferOwnership: pair("Transfer ownership", "移交所有权"),
    confirmTransfer: pair("Confirm transfer", "确认移交"),
    transferWarning: pair("This member will become the owner. Your role will change to Admin.", "此成员将成为所有者，你的角色将变为管理员。"),
    inviteMember: pair("Invite member", "邀请成员"),
    createInvitation: pair("Create invitation", "创建邀请"),
    revokeInvitation: pair("Revoke invitation", "撤销邀请"),
    confirmRevoke: pair("Confirm revocation", "确认撤销"),
    revokeWarning: pair("The recipient will no longer be able to accept this invitation.", "接收方将无法再接受此邀请。"),
    invitationUnavailable: pair("This invitation can no longer be revoked.", "此邀请当前无法撤销。"),
    expiresAt: pair("Expires", "到期时间"),
    identityIssuer: pair("Identity issuer", "身份签发方"),
    identitySubject: pair("Account ID", "账号 ID"),
    expiresIn: pair("Expires in", "有效期"),
    oneDay: pair("1 day", "1 天"),
    threeDays: pair("3 days", "3 天"),
    sevenDays: pair("7 days", "7 天"),
    closeDialog: pair("Cancel", "取消"),
    refreshOrganization: pair("Refresh organization", "刷新组织"),
    refreshRequired: pair("Refresh the organization before confirming another change.", "请先刷新组织，再确认新的变更。"),
    refreshInvitations: pair("Refresh invitations before confirming again.", "请刷新邀请后再次确认。"),
    confirmAgain: pair("Organization refreshed. Review this change and confirm again.", "组织已刷新。请核对变更并再次确认。"),
    policyChanged: pair("Organization permissions changed. Refresh before confirming.", "组织权限已变化，请刷新后再确认。"),
    memberUnavailable: pair("This member is no longer available for this change.", "此成员当前无法执行该变更。"),
    permissionUnavailable: pair("Your current membership does not allow this change.", "你的当前成员资格不允许执行该变更。"),
    duplicateMember: pair("This account is already a member.", "此账号已经是组织成员。"),
    identityInvalid: pair("Use 1 to 256 bytes without control characters.", "请输入 1 至 256 字节，且不包含控制字符。"),
    accept: pair("Accept invitation", "接受邀请"),
    expired: pair("Expired", "已过期"),
    inactive: pair("Inactive", "已停用"),
    checkResult: pair("Check result", "查询结果"),
    unknown: pair("Operation outcome unknown", "操作结果未知"),
    failed: pair("Operation failed", "操作失败"),
    committed: pair("Operation committed", "操作已提交"),
    organizationChange: pair("Organization change", "组织变更"),
    catalogLicense: pair("Accept package license", "接受包许可"),
    packageInstall: pair("Install package", "安装包"),
    cloudOperation: pair("Cloud snapshot operation", "云快照操作"),
    cloudUnknown: pair("Cloud outcome unknown. Check the service receipt before another write.", "云端结果未知。再次写入前请查询服务回执。"),
    cloudConflict: pair("Remote head changed. This operation did not publish a snapshot.", "远端版本已变化。此操作未发布快照。"),
    cloudIdConflict: pair("This operation ID was already used. This request did not publish a snapshot.", "此操作 ID 已被使用。该请求未发布快照。"),
    cloudCommitted: pair("Cloud operation receipt confirmed.", "云端操作回执已确认。"),
    cloudSyncTitle: pair("Project cloud sync", "项目云同步"),
    cloudSyncUnavailable: pair("Select the linked local project and load its latest cloud revision before syncing.", "请选择已关联的本地项目，并先加载最新云端版本再同步。"),
    cloudSyncProjectChanged: pair("This cloud operation belongs to a different local project. Select that project to continue recovery.", "此云同步操作属于另一个本地项目。请切换到该项目后继续恢复。"),
    cloudPush: pair("Upload local snapshot", "上传本地快照"),
    cloudLinkFromTeam: pair("Link a local project to a team project in Account before syncing.", "请先在账号页面将本地项目关联到团队项目，再开始同步。"),
    cloudRetrySnapshot: pair("Resume same upload", "继续此上传"),
    cloudUploading: pair("Capturing and uploading the selected project snapshot…", "正在采集并上传已选项目快照…"),
    cloudDownloading: pair("Downloading and verifying the cloud snapshot…", "正在下载并校验云端快照…"),
    cloudApplying: pair("Checking local files before adding the staged snapshot…", "正在检查本地文件，并准备添加暂存快照…"),
    cloudRetryStage: pair("Retry download", "重试下载"),
    cloudRefreshHead: pair("Refresh cloud revision", "刷新云端版本"),
    cloudDownload: pair("Stage cloud snapshot", "暂存云端快照"),
    cloudApply: pair("Apply staged additions", "应用暂存文件"),
    cloudRetryApply: pair("Retry apply", "重试应用"),
    cloudDiscardStage: pair("Discard staged download", "丢弃已暂存下载"),
    cloudConfirmDiscard: pair("Confirm discard", "确认丢弃"),
    cloudCancelDiscard: pair("Keep staged data", "保留暂存数据"),
    cloudDiscardHelp: pair("Discarding removes this local recovery copy. The cloud snapshot and your local files stay unchanged.", "丢弃会删除此本地恢复副本。云端快照和本地文件均不会更改。"),
    cloudStageDiscarded: pair("Staged recovery data was removed. The cloud snapshot is unchanged.", "已移除暂存恢复数据。云端快照未更改。"),
    cloudRevision: pair("Cloud revision", "云端版本"),
    cloudNoRemoteSnapshot: pair("No cloud snapshot has been published yet.", "尚未发布云端快照。"),
    cloudStageReady: pair("Verified download is staged. Applying adds files only when no local file would be replaced.", "已校验下载内容并暂存。只有不会覆盖本地文件时才会应用。"),
    cloudStageStale: pair("The cloud revision changed after staging. Refresh and stage the latest revision before applying.", "暂存后云端版本已变化。请刷新并暂存最新版本后再应用。"),
    cloudApplyComplete: pair("Cloud files were added. Local-only files were left in place.", "已添加云端文件。本地独有文件保持不变。"),
    cloudLocalConflicts: (count: number) => pair(`${count} local file${count === 1 ? "" : "s"} differ from this cloud snapshot. Nothing was applied; resolve them and try again.`, `有 ${count} 个本地文件与此云端快照不同。未应用任何文件；解决冲突后请重试。`),
    cloudOperationId: pair("Operation reference", "操作编号"),
    dismiss: pair("Dismiss", "关闭"),
    roles: { owner: pair("Owner", "所有者"), admin: pair("Admin", "管理员"), member: pair("Member", "成员"), viewer: pair("Viewer", "访客") },
    invitationStates: { pending: pair("Pending", "待接受"), accepted: pair("Accepted", "已接受"), revoked: pair("Revoked", "已撤销"), expired: pair("Expired", "已过期") },
    error: (code: string) => {
      const values: Record<string, [string, string]> = {
        account_configuration_invalid: ["Account configuration is invalid", "账号配置无效"],
        account_not_configured: ["Account service is not configured", "账号服务未配置"],
        account_login_cancelled: ["Sign-in cancelled", "登录已取消"],
        account_login_timed_out: ["Sign-in timed out", "登录超时"],
        account_operation_busy: ["An account operation is in progress", "已有账号操作正在进行"],
        account_session_expired: ["Session expired", "会话已过期"],
        identity_provider_unavailable: ["Identity service is unavailable", "身份服务不可用"],
        account_credential_store_unavailable: ["Credential storage is unavailable", "凭据存储不可用"],
        account_operation_store_unavailable: ["Operation history is unavailable", "操作记录不可用"],
        account_operation_id_conflict: ["Operation reference conflicts with an existing request", "操作编号与已有请求冲突"],
        account_revocation_pending: ["Session revocation is pending", "会话撤销尚未完成"],
        account_browser_unavailable: ["The sign-in browser could not open", "无法打开登录浏览器"],
        account_service_outcome_unknown: ["Operation outcome unknown", "操作结果未知"],
        account_protocol_invalid: ["Account response is invalid", "账号服务响应无效"],
        account_package_service_unavailable: ["Package service is unavailable", "包服务不可用"],
        account_package_trust_denied: ["Package signature or contents were rejected", "包签名或内容未通过验证"],
        account_package_capacity_exceeded: ["Package storage or size limit exceeded", "包存储或大小超过限制"],
        account_package_inventory_conflict: ["Installation inventory changed. Refresh the organization and inventory before confirming again.", "安装清单已变化，请刷新组织与安装清单后再次确认。"],
        account_package_policy_unconfigured: ["Package installation is not configured on this device. Configure the trusted host package policy index, then try again.", "此设备尚未配置包安装。请先配置可信的主机包策略索引，然后重试。"],
        account_package_target_unconfigured: ["Package installation is not configured for this runtime on this device. Configure a trusted policy for this target, then try again.", "此设备尚未为该运行目标配置包安装。请先为此目标配置可信策略，然后重试。"],
        hub_cloud_sync_project_unavailable: ["Select a valid linked local project before syncing.", "请先选择有效且已关联的本地项目。"],
        hub_cloud_sync_project_changed: ["The local project changed during sync. Review it and retry.", "同步期间本地项目发生变化。请检查后重试。"],
        hub_cloud_sync_project_busy: ["Close the Editor before syncing this project.", "请先关闭 Editor，再同步此项目。"],
        hub_cloud_sync_snapshot_invalid: ["The project contains an unsupported, oversized, or unsafe file.", "项目中包含不受支持、过大或不安全的文件。"],
        hub_cloud_sync_stage_invalid: ["The staged cloud snapshot is incomplete or no longer valid.", "暂存的云端快照不完整或已失效。"],
        hub_cloud_sync_storage_quota_exceeded: ["Cloud sync recovery storage is full. Apply or discard older staged downloads, then retry.", "云同步恢复存储已满。请应用或丢弃较早的暂存下载，然后重试。"],
        hub_cloud_sync_cleanup_pending: ["The sync result is saved, but local recovery data could not be removed. Retry Cloud Sync to finish cleanup.", "同步结果已保存，但无法清理本地恢复数据。请重试云同步以完成清理。"],
        hub_cloud_sync_remote_changed: ["The cloud revision changed after download. Stage the latest snapshot again.", "下载后云端版本已变化。请重新暂存最新快照。"],
        hub_cloud_sync_local_conflict: ["Local files differ from the cloud snapshot. No files were replaced.", "本地文件与云端快照不同。未替换任何文件。"],
        hub_cloud_binding_project_unavailable: ["Select a valid local project before linking.", "关联前请选择有效的本地项目。"],
        hub_cloud_binding_project_changed: ["The selected local project changed. Select it again and retry the link.", "已选本地项目已变更，请重新选择后再试。"],
        hub_cloud_binding_invalid: ["The project link could not be validated.", "无法验证项目关联。"],
        hub_cloud_binding_capacity: ["Too many local project links are saved.", "已保存的本地项目关联过多。"],
        hub_cloud_binding_unavailable: ["Local project links are unavailable.", "本地项目关联不可用。"],
        hub_state_epoch_stale: ["Hub session changed", "Hub 会话已变化"],
        account_package_target_migration_required: ["This older install has no saved runtime target. Checking or retrying it would guess where it belongs, so account changes stay blocked. Review both EditorHost and ClientRuntime inventories, then contact your administrator with this operation reference to migrate its recovery record. Do not retry or dismiss it.", "此旧安装没有保存运行目标。检查或重试会猜测其所属位置，因此账号更改会保持锁定。请检查 EditorHost 和 ClientRuntime 两个清单，然后将此操作编号提供给管理员迁移恢复记录。请勿重试或关闭记录。"],
      };
      const value = values[code];
      return value ? pair(...value) : pair("Account operation failed", "账号操作失败");
    },
  };
}

export type AccountCopy = ReturnType<typeof accountCopy>;
