[package]
name = "zircon_plugin_net_editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Network editor plugin package for Zircon."

[dependencies]
zircon_editor = { workspace = true }
zircon_plugin_editor_support = { path = "../../editor_support" }
zircon_plugin_net_runtime = { path = "../runtime" }
zircon_plugin_sdk = { workspace = true, features = ["editor"] }
zircon_runtime = { workspace = true }
