import contextlib
import hashlib
import io
import json
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path
from unittest.mock import patch

from tools import source_comment_audit as audit


class SourceCommentAuditTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.data = self.root / "docs/cli-and-tooling/source-comment-audit"
        subprocess.run(["git", "init", "-q"], cwd=self.root, check=True)

    def write(self, relative: str, content: str | bytes) -> Path:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8") if isinstance(content, str) else content)
        return path

    def run_cli(self, *arguments: str) -> tuple[int, str]:
        output = io.StringIO()
        with contextlib.redirect_stdout(output), contextlib.redirect_stderr(output):
            result = audit.main(
                ["--repo-root", str(self.root), "--data-dir", str(self.data), *arguments]
            )
        return result, output.getvalue()

    def rows(self, relative: str) -> dict[str, dict]:
        return {
            item["path"]: item
            for item in (
                json.loads(line)
                for line in (self.data / relative).read_text(encoding="utf-8").splitlines()
            )
        }

    def batch_input(self, name: str, rows: list[dict]) -> Path:
        path = self.data / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "".join(json.dumps(row) + "\n" for row in rows), encoding="utf-8"
        )
        return path

    def test_inventory_classifies_live_source_and_explains_exclusions(self) -> None:
        self.write("zircon_runtime/src/lib.rs", "pub fn start() {}\n")
        self.write("zircon_runtime/tests/script.zr", "pub run() {}\n")
        self.write("templates/projects/example/shader.wgsl", "fn main() {}\n")
        self.write("zircon_editor/assets/ui/editor/modules/generated/panel.zui", "[asset]\nkind = 'component'\n")
        self.write("examples/woc/scripts/src/generated/catalog.zr", "// Generated by tools/codegen.mjs; do not edit by hand.\n")
        self.write("examples/woc/scripts/bin/main.zro", b"\x01ZR\x02\x00")
        self.write("examples/vampire/assets/actor.zmeta", "source_digest = '123'\n")
        self.write("examples/vampire/assets/animation/attack.zranim", "[graph]\nname = 'attack'\n")
        self.write("templates/projects/example/export/desktop.zpreset", "[export]\n")
        self.write("tools/zircon_export/export-templates/macos/Info.plist", "<plist></plist>\n")
        self.write("zircon_plugins/navigation/native/vendor/recastnavigation/lib.cpp", "void f() {}\n")
        self.write("zircon_runtime/.zircon-cache/shader_variants/v1/cache.meta", "digest = '123'\n")
        self.write("tools/session_tray/gen/schemas/windows-schema.json", "{}\n")
        self.write("docs/tests/editor/compile.log", "compilation output\n")
        self.write("docs/plans/review.md", "# A plan\n")
        self.write("zircon_runtime/src/new_extension.zfoo", "some future source syntax\n")
        self.write("dev/UnrealEngine/Source/f.cpp", "void f() {}\n")
        subprocess.run(["git", "add", "zircon_runtime/src/lib.rs"], cwd=self.root, check=True)

        result, _ = self.run_cli("inventory", "--write")
        self.assertEqual(0, result)
        rows = self.rows("inventory.jsonl")
        self.assertEqual("included", rows["zircon_runtime/src/lib.rs"]["scope"])
        self.assertTrue(rows["zircon_runtime/src/lib.rs"]["tracked"])
        self.assertFalse(rows["zircon_runtime/tests/script.zr"]["tracked"])
        self.assertEqual("included", rows["templates/projects/example/shader.wgsl"]["scope"])
        self.assertEqual("included", rows["zircon_editor/assets/ui/editor/modules/generated/panel.zui"]["scope"])
        self.assertEqual("generated", rows["examples/woc/scripts/src/generated/catalog.zr"]["reason"])
        self.assertEqual("binary_output", rows["examples/woc/scripts/bin/main.zro"]["reason"])
        self.assertEqual("generated_metadata", rows["examples/vampire/assets/actor.zmeta"]["reason"])
        self.assertEqual("included", rows["examples/vampire/assets/animation/attack.zranim"]["scope"])
        self.assertEqual("included", rows["templates/projects/example/export/desktop.zpreset"]["scope"])
        self.assertEqual("included", rows["tools/zircon_export/export-templates/macos/Info.plist"]["scope"])
        self.assertEqual("third_party", rows["zircon_plugins/navigation/native/vendor/recastnavigation/lib.cpp"]["reason"])
        self.assertEqual("cache_or_build_output", rows["zircon_runtime/.zircon-cache/shader_variants/v1/cache.meta"]["reason"])
        self.assertEqual("generated", rows["tools/session_tray/gen/schemas/windows-schema.json"]["reason"])
        self.assertEqual("recorded_evidence", rows["docs/tests/editor/compile.log"]["reason"])
        self.assertEqual("unclassified", rows["zircon_runtime/src/new_extension.zfoo"]["scope"])
        self.assertEqual("reference_repository", rows["dev/UnrealEngine/Source/f.cpp"]["reason"])
        self.assertEqual(64, len(rows["zircon_runtime/src/lib.rs"]["source_sha256"]))
        self.assertEqual(0, self.run_cli("inventory", "--check")[0])

    def test_review_freshness_tracks_edits_deletion_and_new_files(self) -> None:
        original = "pub fn start() {}\n"
        self.write("zircon_runtime/src/lib.rs", original)
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        self.assertEqual(
            0,
            self.run_cli(
                "mark", "--owner", "runtime", "--path", "zircon_runtime/src/lib.rs",
                "--evidence-ref", "notes/runtime.md#entry", "--disposition", "annotated",
            )[0],
        )
        coverage = self.rows("coverage/runtime.jsonl")["zircon_runtime/src/lib.rs"]
        self.assertEqual("annotated", coverage["disposition"])
        self.assertEqual("notes/runtime.md#entry", coverage["evidence_ref"])
        self.assertEqual(1, json.loads(self.run_cli("status", "--json")[1])["counts"]["reviewed_current"])
        self.assertEqual(0, self.run_cli("verify", "--complete")[0])

        self.write("zircon_runtime/src/lib.rs", original + "// changed\n")
        self.assertEqual(1, json.loads(self.run_cli("status", "--json")[1])["counts"]["stale"])
        self.assertNotEqual(0, self.run_cli("inventory", "--check")[0])
        self.assertNotEqual(0, self.run_cli("verify", "--complete")[0])
        (self.root / "zircon_runtime/src/lib.rs").unlink()
        self.assertEqual(1, json.loads(self.run_cli("status", "--json")[1])["counts"]["missing_source"])
        self.write("zircon_runtime/src/lib.rs", original)
        self.assertEqual(1, json.loads(self.run_cli("status", "--json")[1])["counts"]["reviewed_current"])
        self.write("zircon_runtime/src/new.rs", "pub fn new() {}\n")
        self.assertEqual(1, json.loads(self.run_cli("status", "--json")[1])["counts"]["new_source"])
        self.assertNotEqual(0, self.run_cli("verify", "--complete")[0])

    def test_issue_tags_match_open_ledger_rows_and_ignore_historical_examples(self) -> None:
        self.write(
            "zircon_runtime/src/lib.rs",
            'const EXAMPLE: &str = "// TODO: [CR-runtime-9999] string";\n'
            "// TODO: old historical note\n"
            "// TODO: [CR-runtime-0001] Investigate the loader.\n",
        )
        self.write("zircon_hub/deploy/local/deployment.json", '{}\n')
        self.write("docs/cli-and-tooling/source-comment-audit/README.md", "// BUG: [CR-runtime-8888] sample\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        issues = self.data / "issues/runtime.jsonl"
        issues.parent.mkdir(parents=True, exist_ok=True)
        valid = {
            "schema": 1, "id": "CR-runtime-0001", "kind": "TODO",
            "path": "zircon_hub/deploy/local/deployment.json",
            "anchor_path": "zircon_runtime/src/lib.rs", "evidence": "loader call graph",
            "impact_or_question": "Deployment values are consumed without a contract",
            "next_action": "Inspect loader callsites", "existing_owner": "hub-identity",
            "state": "open",
        }
        issues.write_text(json.dumps(valid) + "\n", encoding="utf-8")
        self.assertEqual(0, self.run_cli("verify")[0])

        issues.write_text(json.dumps({**valid, "kind": "BUG"}) + "\n", encoding="utf-8")
        self.assertNotEqual(0, self.run_cli("verify")[0])
        issues.write_text(json.dumps(valid) + "\n" + json.dumps(valid) + "\n", encoding="utf-8")
        self.assertNotEqual(0, self.run_cli("verify")[0])
        issues.write_text("", encoding="utf-8")
        self.assertNotEqual(0, self.run_cli("verify")[0])

    def test_mark_rejects_generated_and_uninventoried_paths(self) -> None:
        self.write("examples/woc/scripts/src/generated/catalog.zr", "// Generated by codegen\n")
        self.write("zircon_runtime/src/lib.rs", "pub fn start() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        mark = ("mark", "--owner", "runtime", "--evidence-ref", "review.md", "--disposition", "annotated")
        self.assertNotEqual(0, self.run_cli(*mark, "--path", "examples/woc/scripts/src/generated/catalog.zr")[0])
        self.write("zircon_runtime/src/later.rs", "pub fn later() {}\n")
        self.assertNotEqual(0, self.run_cli(*mark, "--path", "zircon_runtime/src/later.rs")[0])

    def test_complete_verification_rejects_unsubstantiated_review_row(self) -> None:
        self.write("zircon_runtime/src/lib.rs", "pub fn start() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        source = self.rows("inventory.jsonl")["zircon_runtime/src/lib.rs"]
        coverage = self.data / "coverage/runtime.jsonl"
        coverage.parent.mkdir(parents=True, exist_ok=True)
        coverage.write_text(
            json.dumps({
                "schema": 1, "path": source["path"], "owner": "runtime",
                "reviewed_sha256": source["source_sha256"], "disposition": "annotated",
            }) + "\n",
            encoding="utf-8",
        )
        self.assertNotEqual(0, self.run_cli("verify", "--complete")[0])

    def test_invalid_issue_target_reports_violation_without_crashing(self) -> None:
        self.write("zircon_runtime/src/lib.rs", "// TODO: [CR-runtime-0001] Inspect caller.\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        issue_path = self.data / "issues/runtime.jsonl"
        issue_path.parent.mkdir(parents=True, exist_ok=True)
        valid = {
            "schema": 1, "id": "CR-runtime-0001", "kind": "TODO",
            "path": "zircon_runtime/src/lib.rs",
            "anchor_path": "zircon_runtime/src/lib.rs",
            "evidence": "caller scan", "impact_or_question": "caller purpose unclear",
            "next_action": "inspect direct callers", "state": "open",
        }
        for field, invalid in (
            ("path", ["zircon_runtime/src/lib.rs"]),
            ("path", {"unexpected": "object"}),
            ("anchor_path", ["zircon_runtime/src/lib.rs"]),
            ("kind", 7),
            ("state", {"unexpected": "object"}),
        ):
            with self.subTest(field=field, invalid=invalid):
                issue_path.write_text(json.dumps({**valid, field: invalid}) + "\n", encoding="utf-8")
                result, output = self.run_cli("verify")
                self.assertEqual(1, result)
                self.assertIn("CR-runtime-0001", output)

    def test_coverage_owner_must_match_shard_name(self) -> None:
        self.write("zircon_runtime/src/lib.rs", "pub fn start() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        source = self.rows("inventory.jsonl")["zircon_runtime/src/lib.rs"]
        shard = self.data / "coverage/editor.jsonl"
        shard.parent.mkdir(parents=True, exist_ok=True)
        shard.write_text(
            json.dumps({
                "schema": 1, "path": source["path"], "owner": "runtime",
                "reviewed_sha256": source["source_sha256"],
                "reviewed_at": "2026-09-26T00:00:00+00:00", "reviewer": "agent",
                "evidence_ref": "notes.md", "disposition": "annotated",
            }) + "\n",
            encoding="utf-8",
        )
        result, output = self.run_cli("status", "--json")
        self.assertEqual(2, result)
        self.assertIn("owner", output)
        self.assertIn("editor.jsonl", output)

    def test_complete_verification_detects_saved_exclusion_of_live_source(self) -> None:
        self.write("zircon_runtime/src/lib.rs", "pub fn start() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        inventory = self.rows("inventory.jsonl")
        source = inventory["zircon_runtime/src/lib.rs"]
        inventory[source["path"]] = {
            **source, "scope": "excluded", "source_sha256": None, "reason": "documentation",
        }
        self.data.joinpath("inventory.jsonl").write_text(
            "".join(json.dumps(row) + "\n" for row in inventory.values()), encoding="utf-8"
        )

        result, output = self.run_cli("status", "--json")
        self.assertEqual(0, result)
        counts = json.loads(output)["counts"]
        self.assertEqual(1, counts["scope_changed"])
        self.assertEqual(1, counts["inventory_drift"])
        self.assertEqual(1, counts["unreviewed"])
        self.assertNotEqual(0, self.run_cli("verify", "--complete")[0])

        coverage = self.data / "coverage/runtime.jsonl"
        coverage.parent.mkdir(parents=True, exist_ok=True)
        coverage.write_text(
            json.dumps({
                "schema": 1, "path": source["path"], "owner": "runtime",
                "reviewed_sha256": source["source_sha256"],
                "reviewed_at": "2026-09-26T00:00:00+00:00", "reviewer": "agent",
                "evidence_ref": "notes.md", "disposition": "annotated",
            }) + "\n",
            encoding="utf-8",
        )
        self.assertNotEqual(0, self.run_cli("verify", "--complete")[0])

    def test_complete_verification_detects_excluded_record_attribute_drift(self) -> None:
        self.write("docs/plans/record.md", "# Plan\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        inventory = self.rows("inventory.jsonl")
        record = inventory["docs/plans/record.md"]
        inventory[record["path"]] = {**record, "reason": "incorrect_reason", "tracked": True}
        self.data.joinpath("inventory.jsonl").write_text(
            "".join(json.dumps(row) + "\n" for row in inventory.values()), encoding="utf-8"
        )
        counts = json.loads(self.run_cli("status", "--json")[1])["counts"]
        self.assertEqual(1, counts["inventory_drift"])
        self.assertEqual(0, counts["scope_changed"])
        self.assertNotEqual(0, self.run_cli("verify", "--complete")[0])

    def test_multibyte_character_at_header_boundary_remains_source(self) -> None:
        source = b"// " + b"a" * 4092 + "中".encode("utf-8") + b"\npub fn start() {}\n"
        self.write("zircon_runtime/src/lib.rs", source)
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        row = self.rows("inventory.jsonl")["zircon_runtime/src/lib.rs"]
        self.assertEqual("included", row["scope"])
        self.assertEqual(64, len(row["source_sha256"]))

    def test_verify_detects_source_change_between_inventory_and_label_read(self) -> None:
        original = "pub fn start() {}\n"
        self.write("zircon_runtime/src/lib.rs", original)
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        self.assertEqual(0, self.run_cli(
            "mark", "--owner", "runtime", "--path", "zircon_runtime/src/lib.rs",
            "--evidence-ref", "notes.md", "--disposition", "annotated",
        )[0])
        actual_scan = audit.scan_inventory

        def scan_then_edit(root: Path, data: Path | None = None):
            snapshot = actual_scan(root, data)
            self.write("zircon_runtime/src/lib.rs", original + "// concurrent edit\n")
            return snapshot

        with patch.object(audit, "scan_inventory", side_effect=scan_then_edit):
            result, output = self.run_cli("verify", "--complete")
        self.assertNotEqual(0, result)
        self.assertIn("source changed after inventory scan", output)

    def test_root_pip_requirements_is_included_but_other_text_notes_are_not(self) -> None:
        self.write("requirements-docs.txt", "mkdocs>=1.0\n")
        self.write("docs/testing/notes.txt", "historical test output\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        rows = self.rows("inventory.jsonl")
        self.assertEqual("included", rows["requirements-docs.txt"]["scope"])
        self.assertEqual("excluded", rows["docs/testing/notes.txt"]["scope"])

    def test_mark_batch_records_per_file_evidence_and_retries_without_churn(self) -> None:
        first = "zircon_runtime/src/first.rs"
        second = "zircon_runtime/src/second.rs"
        self.write(first, "pub fn first() {}\n")
        self.write(second, "pub fn second() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        inventory = self.rows("inventory.jsonl")
        batch = self.batch_input("batch.jsonl", [
            {
                "schema": 1, "path": first,
                "expected_sha256": inventory[first]["source_sha256"],
                "evidence_ref": "notes.md#first", "disposition": "annotated",
                "reviewer": "agent-a",
            },
            {
                "schema": 1, "path": second,
                "expected_sha256": inventory[second]["source_sha256"],
                "evidence_ref": "notes.md#second", "disposition": "no_comment_needed",
            },
        ])
        command = ("mark-batch", "--owner", "runtime", "--input-file", str(batch))
        self.assertEqual(0, self.run_cli(*command)[0])
        shard = self.data / "coverage/runtime.jsonl"
        original_bytes = shard.read_bytes()
        coverage = self.rows("coverage/runtime.jsonl")
        self.assertEqual("notes.md#first", coverage[first]["evidence_ref"])
        self.assertEqual("notes.md#second", coverage[second]["evidence_ref"])
        self.assertEqual("agent-a", coverage[first]["reviewer"])
        self.assertEqual("runtime", coverage[second]["reviewer"])
        self.assertEqual(2, json.loads(self.run_cli("status", "--json")[1])["counts"]["reviewed_current"])
        self.assertEqual(0, self.run_cli(*command)[0])
        self.assertEqual(original_bytes, shard.read_bytes())

        changed = "pub fn second() { /* reviewed update */ }\n"
        self.write(second, changed)
        self.batch_input("batch.jsonl", [{
            "schema": 1, "path": second,
            "expected_sha256": hashlib.sha256(changed.encode()).hexdigest(),
            "evidence_ref": "notes.md#second-recheck", "disposition": "annotated",
        }])
        self.assertEqual(0, self.run_cli(*command)[0])
        updated = self.rows("coverage/runtime.jsonl")
        self.assertEqual(coverage[first], updated[first])
        self.assertEqual("notes.md#second-recheck", updated[second]["evidence_ref"])

    def test_mark_batch_failure_never_publishes_partial_review(self) -> None:
        first = "zircon_runtime/src/first.rs"
        second = "zircon_runtime/src/second.rs"
        self.write(first, "pub fn first() {}\n")
        self.write(second, "pub fn second() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        inventory = self.rows("inventory.jsonl")
        good = {
            "schema": 1, "path": first, "expected_sha256": inventory[first]["source_sha256"],
            "evidence_ref": "notes.md#first", "disposition": "annotated",
        }
        bad = {
            "schema": 1, "path": second, "expected_sha256": "0" * 64,
            "evidence_ref": "notes.md#second", "disposition": "annotated",
        }
        batch = self.batch_input("batch.jsonl", [good, bad])
        command = ("mark-batch", "--owner", "runtime", "--input-file", str(batch))
        self.assertNotEqual(0, self.run_cli(*command)[0])
        shard = self.data / "coverage/runtime.jsonl"
        self.assertFalse(shard.exists())

        self.batch_input("batch.jsonl", [good])
        self.assertEqual(0, self.run_cli(*command)[0])
        original = shard.read_bytes()
        self.batch_input("batch.jsonl", [good, bad])
        self.assertNotEqual(0, self.run_cli(*command)[0])
        self.assertEqual(original, shard.read_bytes())

    def test_mark_batch_invalid_utf8_reports_path_without_traceback(self) -> None:
        self.write("zircon_runtime/src/lib.rs", "pub fn start() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        batch = self.data / "invalid-batch.jsonl"
        batch.write_bytes(b'{"schema":1,"path":"zircon_runtime/src/lib.rs"}\xff\n')

        result, output = self.run_cli(
            "mark-batch", "--owner", "runtime", "--input-file", str(batch)
        )
        self.assertEqual(2, result)
        self.assertIn("invalid UTF-8", output)
        self.assertIn(str(batch), output)
        self.assertNotIn("Traceback", output)
        self.assertFalse((self.data / "coverage/runtime.jsonl").exists())

    def test_concurrent_owners_cannot_publish_the_same_review(self) -> None:
        source = "zircon_runtime/src/lib.rs"
        self.write(source, "pub fn start() {}\n")
        self.assertFalse(audit._review_write_lock_path(self.data).is_relative_to(self.root))
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        digest = self.rows("inventory.jsonl")[source]["source_sha256"]
        batch = self.batch_input("batch.jsonl", [{
            "schema": 1, "path": source, "expected_sha256": digest,
            "evidence_ref": "runtime.md", "disposition": "annotated",
        }])
        ready = self.data / "writer-ready"
        release = self.data / "writer-release"
        child_script = (
            "import sys, time\n"
            "from pathlib import Path\n"
            "from unittest.mock import patch\n"
            "from tools import source_comment_audit as audit\n"
            "ready, release = Path(sys.argv[1]), Path(sys.argv[2])\n"
            "real_write = audit._write_jsonl\n"
            "def gated_write(path, rows):\n"
            "    if path.name == 'runtime.jsonl':\n"
            "        ready.write_text('ready', encoding='utf-8')\n"
            "        for _ in range(200):\n"
            "            if release.exists():\n"
            "                break\n"
            "            time.sleep(0.05)\n"
            "        else:\n"
            "            raise RuntimeError('test writer gate timed out')\n"
            "    return real_write(path, rows)\n"
            "with patch.object(audit, '_write_jsonl', side_effect=gated_write):\n"
            "    raise SystemExit(audit.main(sys.argv[3:]))\n"
        )
        writer = subprocess.Popen(
            [sys.executable, "-c", child_script, str(ready), str(release),
             "--repo-root", str(self.root), "--data-dir", str(self.data),
             "mark-batch", "--owner", "runtime", "--input-file", str(batch)],
            cwd=Path(__file__).resolve().parents[2],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )

        def stop_writer() -> None:
            if writer.poll() is None:
                writer.kill()
            writer.communicate(timeout=10)

        self.addCleanup(stop_writer)
        for _ in range(200):
            if ready.exists() or writer.poll() is not None:
                break
            time.sleep(0.05)
        self.assertTrue(ready.exists(), "writer did not reach the locked publication step")
        result, output = self.run_cli(
            "mark", "--owner", "editor", "--path", source,
            "--evidence-ref", "editor.md", "--disposition", "annotated",
        )
        self.assertEqual(2, result)
        self.assertIn("review write already in progress", output)
        self.assertFalse((self.data / "coverage/editor.jsonl").exists())
        release.touch()
        stdout, stderr = writer.communicate(timeout=10)
        self.assertEqual(0, writer.returncode, stderr or stdout)
        self.assertEqual("runtime", self.rows("coverage/runtime.jsonl")[source]["owner"])
        self.assertEqual(2, self.run_cli(
            "mark", "--owner", "editor", "--path", source,
            "--evidence-ref", "editor.md", "--disposition", "annotated",
        )[0])

    def test_mark_releases_write_lock_after_publication_failure(self) -> None:
        source = "zircon_runtime/src/lib.rs"
        self.write(source, "pub fn start() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        command = (
            "mark", "--owner", "runtime", "--path", source,
            "--evidence-ref", "runtime.md", "--disposition", "annotated",
        )
        with patch.object(audit, "_write_jsonl", side_effect=OSError("write failed")):
            self.assertEqual(2, self.run_cli(*command)[0])
        self.assertFalse((self.data / "coverage/runtime.jsonl").exists())
        self.assertEqual(0, self.run_cli(*command)[0])

    def test_mark_batch_rejects_foreign_owner_generated_and_duplicate_paths(self) -> None:
        source = "zircon_runtime/src/lib.rs"
        generated = "examples/woc/scripts/src/generated/catalog.zr"
        self.write(source, "pub fn start() {}\n")
        self.write(generated, "// Generated by codegen.mjs\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        digest = self.rows("inventory.jsonl")[source]["source_sha256"]
        row = {
            "schema": 1, "path": source, "expected_sha256": digest,
            "evidence_ref": "notes.md", "disposition": "annotated",
        }
        batch = self.batch_input("batch.jsonl", [row, row])
        self.assertNotEqual(0, self.run_cli(
            "mark-batch", "--owner", "runtime", "--input-file", str(batch)
        )[0])
        self.assertFalse((self.data / "coverage/runtime.jsonl").exists())

        self.batch_input("batch.jsonl", [{**row, "path": generated}])
        self.assertNotEqual(0, self.run_cli(
            "mark-batch", "--owner", "runtime", "--input-file", str(batch)
        )[0])
        for invalid in ({**row, "evidence_ref": ""}, {**row, "disposition": "unknown"}):
            self.batch_input("batch.jsonl", [invalid])
            self.assertNotEqual(0, self.run_cli(
                "mark-batch", "--owner", "runtime", "--input-file", str(batch)
            )[0])
        self.assertEqual(0, self.run_cli(
            "mark", "--owner", "editor", "--path", source,
            "--evidence-ref", "editor.md", "--disposition", "annotated",
        )[0])
        self.batch_input("batch.jsonl", [row])
        self.assertNotEqual(0, self.run_cli(
            "mark-batch", "--owner", "runtime", "--input-file", str(batch)
        )[0])
        self.assertFalse((self.data / "coverage/runtime.jsonl").exists())

    def test_mark_batch_detects_late_source_change_and_replace_failure(self) -> None:
        source = "zircon_runtime/src/lib.rs"
        original = "pub fn start() {}\n"
        self.write(source, original)
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        digest = self.rows("inventory.jsonl")[source]["source_sha256"]
        row = {
            "schema": 1, "path": source, "expected_sha256": digest,
            "evidence_ref": "notes.md", "disposition": "annotated",
        }
        batch = self.batch_input("batch.jsonl", [row])
        command = ("mark-batch", "--owner", "runtime", "--input-file", str(batch))
        actual_digest = audit._stable_digest
        calls = 0

        def edit_after_first_hash(path: Path):
            nonlocal calls
            result = actual_digest(path)
            if path == self.root / source:
                calls += 1
                if calls == 1:
                    self.write(source, original + "// changed during batch\n")
            return result

        with patch.object(audit, "_stable_digest", side_effect=edit_after_first_hash):
            self.assertNotEqual(0, self.run_cli(*command)[0])
        self.assertFalse((self.data / "coverage/runtime.jsonl").exists())

        self.write(source, original)
        self.assertEqual(0, self.run_cli(*command)[0])
        shard = self.data / "coverage/runtime.jsonl"
        original_shard = shard.read_bytes()
        self.batch_input("batch.jsonl", [{**row, "evidence_ref": "notes.md#updated"}])
        with patch.object(audit.os, "replace", side_effect=OSError("simulated replace failure")):
            self.assertEqual(2, self.run_cli(*command)[0])
        self.assertEqual(original_shard, shard.read_bytes())
        self.assertEqual([], list(shard.parent.glob(f".{shard.name}.*.tmp")))

    def test_mark_batch_input_change_and_temporary_write_failure_roll_back(self) -> None:
        source = "zircon_runtime/src/lib.rs"
        self.write(source, "pub fn start() {}\n")
        self.assertEqual(0, self.run_cli("inventory", "--write")[0])
        digest = self.rows("inventory.jsonl")[source]["source_sha256"]
        batch = self.batch_input("batch.jsonl", [{
            "schema": 1, "path": source, "expected_sha256": digest,
            "evidence_ref": "notes.md", "disposition": "annotated",
        }])
        actual_digest = audit._stable_digest
        input_reads = 0

        def edit_input_after_parse(path: Path):
            nonlocal input_reads
            result = actual_digest(path)
            if path == batch:
                input_reads += 1
                if input_reads == 2:
                    batch.write_text(batch.read_text(encoding="utf-8") + "\n", encoding="utf-8")
            return result

        with patch.object(audit, "_stable_digest", side_effect=edit_input_after_parse):
            self.assertNotEqual(0, self.run_cli(
                "mark-batch", "--owner", "runtime", "--input-file", str(batch)
            )[0])
        shard = self.data / "coverage/runtime.jsonl"
        self.assertFalse(shard.exists())

        shard.parent.mkdir(parents=True, exist_ok=True)
        shard.write_text("previous shard bytes\n", encoding="utf-8")
        before = shard.read_bytes()
        with self.assertRaises(TypeError):
            audit._write_jsonl(shard, {"broken": {"not_json": object()}})
        self.assertEqual(before, shard.read_bytes())
        self.assertEqual([], list(shard.parent.glob(f".{shard.name}.*.tmp")))


if __name__ == "__main__":
    unittest.main()
