"""Static contract tests for Editor12 plugin-owned V2 UI documents."""

from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
RUNTIME = ROOT / "zircon_editor" / "src" / "ui" / "template_runtime" / "runtime"


class PluginV2DocumentRuntimeContractTests(unittest.TestCase):
    def test_runtime_exposes_a_generation_owned_plugin_document_catalog(self) -> None:
        catalog = (RUNTIME / "plugin_documents.rs").read_text(encoding="utf-8")
        catalog_tests = (RUNTIME / "plugin_documents" / "tests.rs").read_text(
            encoding="utf-8"
        )
        runtime = (RUNTIME / "runtime_host.rs").read_text(encoding="utf-8")

        self.assertIn("EditorPluginV2DocumentOwner", catalog)
        self.assertIn("EditorPluginV2DocumentSource", catalog)
        self.assertIn("plugins://", catalog)
        self.assertIn('#[path = "plugin_documents/tests.rs"]', catalog)
        self.assertIn(
            "plugin_document_inputs_reject_invalid_owner_generation_uri_and_sources",
            catalog_tests,
        )
        self.assertIn(
            "runtime_sync_builds_a_shared_surface_from_the_owned_plugin_document",
            catalog_tests,
        )
        self.assertIn(
            "runtime_sync_removes_an_owner_document_when_its_descriptor_set_is_empty",
            catalog_tests,
        )
        self.assertIn("plugin_v2_documents", runtime)
        self.assertIn("if let Some(document) = self.v2_document(document_id)", runtime)
        self.assertIn("replace_plugin_v2_documents", catalog)
        self.assertIn("replace_plugin_v2_documents_for_owner", catalog)
        self.assertIn("unregister_plugin_v2_documents", catalog)

    def test_replacement_builds_candidates_before_publishing_and_reports_retired_ids(
        self,
    ) -> None:
        catalog = (RUNTIME / "plugin_documents.rs").read_text(encoding="utf-8")
        catalog_tests = (RUNTIME / "plugin_documents" / "tests.rs").read_text(
            encoding="utf-8"
        )
        runtime = (RUNTIME / "runtime_host.rs").read_text(encoding="utf-8")

        self.assertIn("candidate_documents", catalog)
        self.assertIn("load_store", catalog)
        self.assertIn("retain", catalog)
        self.assertIn("retired_document_ids", catalog)
        self.assertIn(
            "replacement_preserves_a_same_id_route_for_the_new_generation", catalog_tests
        )
        self.assertIn("owner_scoped_replacement_advances_generation_across_unload", catalog_tests)
        self.assertIn(
            "owner_scoped_replacement_returns_invalid_owner_errors_without_publishing",
            catalog_tests,
        )
        self.assertIn("stale_generation_cannot_replace_a_newer_plugin_document", catalog_tests)
        self.assertIn("same_generation_cannot_replace_a_current_plugin_document", catalog_tests)
        self.assertIn(
            "owner_scoped_replacement_advances_after_an_explicit_catalog_generation",
            catalog_tests,
        )
        self.assertIn("current_generation >= owner.generation()", catalog)
        self.assertIn("max(catalog_generation)", catalog)
        self.assertIn("PluginDocumentGenerationStale", runtime)
        self.assertNotIn("generated by the host runtime should be valid", catalog)
        self.assertIn("plugin_v2_document_owner", catalog)
        self.assertIn("PluginDocumentUri", catalog)
        self.assertNotIn("navigation", catalog.lower())

    def test_runtime_hard_cuts_direct_owner_mutation_from_the_public_surface(self) -> None:
        catalog = (RUNTIME / "plugin_documents.rs").read_text(encoding="utf-8")
        runtime_module = (RUNTIME / "mod.rs").read_text(encoding="utf-8")
        template_runtime_module = (RUNTIME.parent / "mod.rs").read_text(
            encoding="utf-8"
        )

        self.assertIn("pub(crate) fn sync_plugin_v2_template_descriptor_sets", catalog)
        for direct_type in (
            "EditorPluginV2DocumentOwner",
            "EditorPluginV2DocumentSource",
            "EditorPluginV2DocumentUpdate",
        ):
            self.assertNotIn(f"{direct_type},", runtime_module)
            self.assertNotIn(f"{direct_type},", template_runtime_module)
        for direct_method in (
            "replace_plugin_v2_documents",
            "replace_plugin_v2_documents_for_owner",
            "unregister_plugin_v2_documents",
            "unregister_plugin_v2_documents_for_owner",
        ):
            self.assertIn(f"#[cfg(test)]\n    pub(super) fn {direct_method}", catalog)
            self.assertNotIn(f"pub fn {direct_method}", catalog)
        self.assertIn(
            "#[cfg(test)]\n#[derive(Clone, Debug, PartialEq, Eq)]\n"
            "pub(super) struct EditorPluginV2DocumentUpdate",
            catalog,
        )
        self.assertIn("pub(super) fn plugin_v2_document_owner", catalog)
        self.assertIn("EditorPluginV2DocumentSourceError", runtime_module)
        self.assertIn("EditorPluginV2DocumentSourceError", template_runtime_module)


if __name__ == "__main__":
    unittest.main()
