type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 status output M3 row data child-owner split",
        &[
            "runtime_15_status_output_m3_row_data_child_owner_split_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support.rs",
            "runtime_15_status_output_m3_row_data_child_owner_split",
        ],
    ),
    (
        "Runtime 15 M3 child-groups row-data guard folder-backed split",
        &[
            "runtime_15_m3_child_groups_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/exports.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/budgets.rs",
            "runtime_15_m3_child_groups_row_data_guard_is_folder_backed",
            "runtime_15_status_output_m3_row_data_child_owner_split",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups row-data status-mirror child split",
        &[
            "runtime_15_m3_child_groups_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors/folder_backed_status.rs",
            "runtime_15_m3_child_groups_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups folder-backed source reconciliation",
        &[
            "runtime_15_m3_child_groups_folder_backed_source_reconciliation_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/exports.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/production_guard_runtime_row_data/child_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_paths/status_output_guard_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_paths/status_support_map_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_paths/production_guard_runtime_row_data_paths.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_statuses/core_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_statuses/core_statuses/base_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_statuses/core_statuses/inventory_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_statuses/core_statuses/production_statuses.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/delegation.rs",
            "runtime_15_m3_child_groups_row_data_guard_is_folder_backed",
            "runtime_15_m3_child_groups_row_data_status_mirror_children_are_child_owned",
            "runtime_15_status_output_m3_row_data_child_owner_split",
            "runtime_15_m3_child_groups status filter passed 22/22",
            "Cargo gate deferred",
        ],
    ),
];
