pub(super) struct WorkbenchOverlayPrimitiveContract {
    pub(super) file_name: &'static str,
    pub(super) component_name: &'static str,
    pub(super) placement: &'static str,
    pub(super) required_props: &'static [&'static str],
}

const OVERLAY_REQUIRED_PROPS: &[&str] = &[
    "open",
    "popup_open",
    "options",
    "focused_index",
    "keyboard_navigation",
    "typeahead_buffer",
    "typeahead_buffer_expired",
    "typeahead_timeout_ms",
    "hovered_option_id",
    "submenu_pending_option_id",
    "submenu_open_option_id",
    "submenu_hover_ready",
    "submenu_hover_delay_ms",
    "submenu_focus_scope",
    "submenu_focus_loop",
    "placement",
    "anchor_origin_vertical",
    "anchor_origin_horizontal",
    "transform_origin_vertical",
    "transform_origin_horizontal",
    "popup_offset_x",
    "popup_offset_y",
    "disable_auto_focus",
    "disable_enforce_focus",
    "disable_restore_focus",
    "disable_escape_key_down",
    "close_on_backdrop_click",
    "keep_mounted",
    "aria_modal",
    "aria_labelledby",
    "aria_describedby",
    "z_index",
    "disable_portal",
    "portal_layer",
];

pub(super) const WORKBENCH_OVERLAY_PRIMITIVE_CONTRACTS: &[WorkbenchOverlayPrimitiveContract] = &[
    WorkbenchOverlayPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_command_palette.zui",
        component_name: "WorkbenchCommandPalette",
        placement: "top",
        required_props: COMMAND_PALETTE_REQUIRED_PROPS,
    },
    WorkbenchOverlayPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_notification_center.zui",
        component_name: "WorkbenchNotificationCenter",
        placement: "bottom-end",
        required_props: NOTIFICATION_CENTER_REQUIRED_PROPS,
    },
    WorkbenchOverlayPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_dialog.zui",
        component_name: "WorkbenchDialog",
        placement: "center",
        required_props: DIALOG_REQUIRED_PROPS,
    },
    WorkbenchOverlayPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_confirm_dialog.zui",
        component_name: "WorkbenchConfirmDialog",
        placement: "center",
        required_props: CONFIRM_DIALOG_REQUIRED_PROPS,
    },
    WorkbenchOverlayPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_context_menu.zui",
        component_name: "WorkbenchContextMenu",
        placement: "right-start",
        required_props: OVERLAY_REQUIRED_PROPS,
    },
    WorkbenchOverlayPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_dropdown_popup.zui",
        component_name: "WorkbenchDropdownPopup",
        placement: "bottom-start",
        required_props: OVERLAY_REQUIRED_PROPS,
    },
];

const COMMAND_PALETTE_REQUIRED_PROPS: &[&str] = &[
    "open",
    "popup_open",
    "query",
    "placeholder",
    "commands",
    "filtered_commands",
    "recent_commands",
    "selected_command_id",
    "focused_index",
    "keyboard_navigation",
    "empty_text",
    "command_source",
    "placement",
    "anchor_origin_vertical",
    "anchor_origin_horizontal",
    "transform_origin_vertical",
    "transform_origin_horizontal",
    "popup_offset_x",
    "popup_offset_y",
    "disable_auto_focus",
    "disable_enforce_focus",
    "disable_restore_focus",
    "disable_escape_key_down",
    "close_on_backdrop_click",
    "keep_mounted",
    "aria_modal",
    "aria_labelledby",
    "aria_describedby",
    "z_index",
    "disable_portal",
    "portal_layer",
];

const NOTIFICATION_CENTER_REQUIRED_PROPS: &[&str] = &[
    "open",
    "popup_open",
    "title",
    "unread_count",
    "notifications",
    "selected_notification_id",
    "focused_index",
    "visible_limit",
    "empty_text",
    "placement",
    "anchor_origin_vertical",
    "anchor_origin_horizontal",
    "transform_origin_vertical",
    "transform_origin_horizontal",
    "popup_offset_x",
    "popup_offset_y",
    "disable_auto_focus",
    "disable_enforce_focus",
    "disable_restore_focus",
    "disable_escape_key_down",
    "close_on_backdrop_click",
    "keep_mounted",
    "aria_modal",
    "aria_labelledby",
    "aria_describedby",
    "z_index",
    "disable_portal",
    "portal_layer",
];

pub(super) const DRAG_OVERLAY_REQUIRED_PROPS: &[&str] = &[
    "open",
    "dragging",
    "drop_hovered",
    "active_drag_target",
    "payload_kind",
    "payload_label",
    "payload_reference",
    "source_control_id",
    "target_control_id",
    "cursor_x",
    "cursor_y",
    "offset_x",
    "offset_y",
    "preview_width",
    "preview_height",
    "drop_allowed",
    "drop_target_x",
    "drop_target_y",
    "drop_target_width",
    "drop_target_height",
    "drop_indicator_edge",
    "drop_indicator_text",
    "z_index",
    "disable_portal",
    "portal_layer",
];

const DIALOG_REQUIRED_PROPS: &[&str] = &[
    "open",
    "popup_open",
    "text",
    "title",
    "message",
    "placement",
    "anchor_origin_vertical",
    "anchor_origin_horizontal",
    "transform_origin_vertical",
    "transform_origin_horizontal",
    "popup_offset_x",
    "popup_offset_y",
    "disable_auto_focus",
    "disable_enforce_focus",
    "disable_restore_focus",
    "disable_escape_key_down",
    "close_on_backdrop_click",
    "keep_mounted",
    "aria_modal",
    "aria_labelledby",
    "aria_describedby",
    "z_index",
    "disable_portal",
    "portal_layer",
];

const CONFIRM_DIALOG_REQUIRED_PROPS: &[&str] = &[
    "open",
    "popup_open",
    "title",
    "message",
    "confirm_text",
    "cancel_text",
    "confirm_action_id",
    "cancel_action_id",
    "severity",
    "default_action",
    "destructive",
    "confirm_enabled",
    "requires_explicit_action",
    "placement",
    "anchor_origin_vertical",
    "anchor_origin_horizontal",
    "transform_origin_vertical",
    "transform_origin_horizontal",
    "popup_offset_x",
    "popup_offset_y",
    "disable_auto_focus",
    "disable_enforce_focus",
    "disable_restore_focus",
    "disable_escape_key_down",
    "close_on_backdrop_click",
    "keep_mounted",
    "aria_modal",
    "aria_labelledby",
    "aria_describedby",
    "z_index",
    "disable_portal",
    "portal_layer",
];
