pub(super) struct WorkbenchPrimitiveContract {
    pub(super) file_name: &'static str,
    pub(super) component_name: &'static str,
    pub(super) root_component: &'static str,
    pub(super) interactive: bool,
    pub(super) sampled_in_component_drawer: bool,
}

pub(super) const WORKBENCH_PRIMITIVE_CONTRACTS: &[WorkbenchPrimitiveContract] = &[
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_button.zui",
        component_name: "WorkbenchButton",
        root_component: "Button",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_icon_button.zui",
        component_name: "WorkbenchIconButton",
        root_component: "IconButton",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/chrome/workbench_rail_button.zui",
        component_name: "WorkbenchRailButton",
        root_component: "IconButton",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_field.zui",
        component_name: "WorkbenchField",
        root_component: "InputField",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_search_input.zui",
        component_name: "WorkbenchSearchInput",
        root_component: "SearchField",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_checkbox.zui",
        component_name: "WorkbenchCheckbox",
        root_component: "Checkbox",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_radio.zui",
        component_name: "WorkbenchRadio",
        root_component: "Radio",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_toggle.zui",
        component_name: "WorkbenchToggle",
        root_component: "Toggle",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_tab.zui",
        component_name: "WorkbenchTab",
        root_component: "ToggleButton",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_segmented_control.zui",
        component_name: "WorkbenchSegmentedControl",
        root_component: "SegmentedControl",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_dropdown.zui",
        component_name: "WorkbenchDropdown",
        root_component: "Dropdown",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_slider.zui",
        component_name: "WorkbenchSlider",
        root_component: "RangeField",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_range_slider.zui",
        component_name: "WorkbenchRangeSlider",
        root_component: "RangeSlider",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_number_field.zui",
        component_name: "WorkbenchNumberField",
        root_component: "NumberField",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/inputs/workbench_tab_strip.zui",
        component_name: "WorkbenchTabStrip",
        root_component: "Tabs",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_label.zui",
        component_name: "WorkbenchLabel",
        root_component: "Label",
        interactive: false,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_icon.zui",
        component_name: "WorkbenchIcon",
        root_component: "Icon",
        interactive: false,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_list_row.zui",
        component_name: "WorkbenchListRow",
        root_component: "ListRow",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_tree_row.zui",
        component_name: "WorkbenchTreeRow",
        root_component: "TreeRow",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_table_row.zui",
        component_name: "WorkbenchTableRow",
        root_component: "Table",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_divider.zui",
        component_name: "WorkbenchDivider",
        root_component: "Divider",
        interactive: false,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_popup_menu.zui",
        component_name: "WorkbenchPopupMenu",
        root_component: "ContextActionMenu",
        interactive: true,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_context_menu.zui",
        component_name: "WorkbenchContextMenu",
        root_component: "ContextMenu",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_dropdown_popup.zui",
        component_name: "WorkbenchDropdownPopup",
        root_component: "DropdownPopup",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_command_palette.zui",
        component_name: "WorkbenchCommandPalette",
        root_component: "CommandPalette",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_notification_center.zui",
        component_name: "WorkbenchNotificationCenter",
        root_component: "NotificationCenter",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_drag_overlay.zui",
        component_name: "WorkbenchDragOverlay",
        root_component: "DragOverlay",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_alert.zui",
        component_name: "WorkbenchAlert",
        root_component: "Alert",
        interactive: false,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_dialog.zui",
        component_name: "WorkbenchDialog",
        root_component: "Dialog",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_confirm_dialog.zui",
        component_name: "WorkbenchConfirmDialog",
        root_component: "ConfirmDialog",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_progress_bar.zui",
        component_name: "WorkbenchProgressBar",
        root_component: "Progress",
        interactive: false,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_skeleton.zui",
        component_name: "WorkbenchSkeleton",
        root_component: "Skeleton",
        interactive: false,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_tooltip.zui",
        component_name: "WorkbenchTooltip",
        root_component: "Tooltip",
        interactive: false,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_toast.zui",
        component_name: "WorkbenchToast",
        root_component: "Alert",
        interactive: false,
        sampled_in_component_drawer: true,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_property_row.zui",
        component_name: "WorkbenchPropertyRow",
        root_component: "PropertyRow",
        interactive: false,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/data/workbench_component_property_row.zui",
        component_name: "WorkbenchComponentPropertyRow",
        root_component: "InputField",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/chrome/workbench_chip.zui",
        component_name: "WorkbenchChip",
        root_component: "Label",
        interactive: false,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/chrome/workbench_axis_value_field.zui",
        component_name: "WorkbenchAxisValueField",
        root_component: "InputField",
        interactive: true,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/chrome/workbench_section_title.zui",
        component_name: "WorkbenchSectionTitle",
        root_component: "Label",
        interactive: false,
        sampled_in_component_drawer: false,
    },
    WorkbenchPrimitiveContract {
        file_name: "workbench/primitives/feedback/workbench_status_item.zui",
        component_name: "WorkbenchStatusItem",
        root_component: "Label",
        interactive: false,
        sampled_in_component_drawer: false,
    },
];
