pub(super) struct WorkbenchShellSurfaceContract {
    pub(super) file_name: &'static str,
    pub(super) component_name: &'static str,
    pub(super) root_node: &'static str,
    pub(super) root_component: &'static str,
    pub(super) root_control_id: &'static str,
    pub(super) root_classes: &'static [&'static str],
    pub(super) required_widget_imports: &'static [&'static str],
    pub(super) required_mounted_components: &'static [&'static str],
    pub(super) required_control_ids: &'static [&'static str],
}

pub(super) const WORKBENCH_SHELL_SURFACE_CONTRACTS: &[WorkbenchShellSurfaceContract] = &[
    WorkbenchShellSurfaceContract {
        file_name: "workbench/shell/workbench_activity_rail.zui",
        component_name: "WorkbenchActivityRail",
        root_node: "activity_rail",
        root_component: "VerticalGroup",
        root_control_id: "WorkbenchWindowActivityRail",
        root_classes: &["workbench-rail"],
        required_widget_imports: &[
            "res://ui/editor/components/workbench/primitives/chrome/workbench_rail_button.zui#WorkbenchRailButton",
        ],
        required_mounted_components: &["WorkbenchRailButton"],
        required_control_ids: &[
            "WorkbenchRailScene",
            "WorkbenchRailCube",
            "WorkbenchRailGraph",
            "WorkbenchRailImage",
            "WorkbenchRailAudio",
            "WorkbenchRailCode",
        ],
    },
    WorkbenchShellSurfaceContract {
        file_name: "workbench/shell/workbench_top_toolbar.zui",
        component_name: "WorkbenchTopToolbar",
        root_node: "top_toolbar",
        root_component: "VerticalGroup",
        root_control_id: "WorkbenchWindowTopToolbar",
        root_classes: &["workbench-topbar"],
        required_widget_imports: &[
            "res://ui/editor/components/workbench/primitives/inputs/workbench_button.zui#WorkbenchButton",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_icon_button.zui#WorkbenchIconButton",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_tab.zui#WorkbenchTab",
        ],
        required_mounted_components: &["WorkbenchButton", "WorkbenchIconButton", "WorkbenchTab"],
        required_control_ids: &[
            "WorkbenchToolbarCommandRow",
            "WorkbenchToolbarFileGroup",
            "WorkbenchModuleTabs",
            "WorkbenchModuleCommands",
            "WorkbenchToolbarToolGroup",
            "WorkbenchToolbarRunGroup",
        ],
    },
    WorkbenchShellSurfaceContract {
        file_name: "workbench/shell/workbench_scene_tree_panel.zui",
        component_name: "WorkbenchSceneTreePanel",
        root_node: "scene_tree_panel",
        root_component: "VerticalGroup",
        root_control_id: "WorkbenchSceneTreePanel",
        root_classes: &["workbench-panel", "workbench-left-panel"],
        required_widget_imports: &[
            "res://ui/editor/components/workbench/primitives/inputs/workbench_search_input.zui#WorkbenchSearchInput",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_icon_button.zui#WorkbenchIconButton",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_tab.zui#WorkbenchTab",
            "res://ui/editor/components/workbench/primitives/data/workbench_tree_row.zui#WorkbenchTreeRow",
        ],
        required_mounted_components: &[
            "WorkbenchSearchInput",
            "WorkbenchIconButton",
            "WorkbenchTab",
            "WorkbenchTreeRow",
        ],
        required_control_ids: &[
            "LeftDrawerHeaderRoot",
            "WorkbenchSceneSearchField",
            "WorkbenchSceneFilter",
            "WorkbenchSceneTree",
            "WorkbenchSceneRootItem",
        ],
    },
    WorkbenchShellSurfaceContract {
        file_name: "workbench/shell/workbench_viewport_panel.zui",
        component_name: "WorkbenchViewportPanel",
        root_node: "viewport_panel",
        root_component: "VerticalGroup",
        root_control_id: "WorkbenchViewportPanel",
        root_classes: &["workbench-viewport-panel"],
        required_widget_imports: &[
            "res://ui/editor/components/workbench/primitives/chrome/workbench_chip.zui#WorkbenchChip",
        ],
        required_mounted_components: &["WorkbenchChip"],
        required_control_ids: &[
            "WorkbenchViewportToolbar",
            "WorkbenchViewportSurface",
            "WorkbenchViewportMode",
            "WorkbenchViewportGizmoPanel",
        ],
    },
    WorkbenchShellSurfaceContract {
        file_name: "workbench/shell/workbench_inspector_panel.zui",
        component_name: "WorkbenchInspectorPanel",
        root_node: "inspector_panel",
        root_component: "VerticalGroup",
        root_control_id: "WorkbenchInspectorPanel",
        root_classes: &["workbench-panel", "workbench-right-panel"],
        required_widget_imports: &[
            "res://ui/editor/components/workbench/primitives/chrome/workbench_axis_value_field.zui#WorkbenchAxisValueField",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_button.zui#WorkbenchButton",
            "res://ui/editor/components/workbench/primitives/data/workbench_component_property_row.zui#WorkbenchComponentPropertyRow",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_dropdown.zui#WorkbenchDropdown",
            "res://ui/editor/components/workbench/primitives/chrome/workbench_section_title.zui#WorkbenchSectionTitle",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_tab.zui#WorkbenchTab",
        ],
        required_mounted_components: &[
            "WorkbenchAxisValueField",
            "WorkbenchButton",
            "WorkbenchComponentPropertyRow",
            "WorkbenchDropdown",
            "WorkbenchSectionTitle",
            "WorkbenchTab",
        ],
        required_control_ids: &[
            "RightDrawerHeaderRoot",
            "WorkbenchInspectorTransform",
            "WorkbenchInspectorMesh",
            "WorkbenchAddComponent",
        ],
    },
    WorkbenchShellSurfaceContract {
        file_name: "workbench/shell/workbench_status_bar.zui",
        component_name: "WorkbenchStatusBar",
        root_node: "status_bar",
        root_component: "HorizontalGroup",
        root_control_id: "WorkbenchWindowStatusBar",
        root_classes: &["workbench-status"],
        required_widget_imports: &[
            "res://ui/editor/components/workbench/primitives/chrome/workbench_chip.zui#WorkbenchChip",
            "res://ui/editor/components/workbench/primitives/inputs/workbench_icon_button.zui#WorkbenchIconButton",
            "res://ui/editor/components/workbench/primitives/feedback/workbench_status_item.zui#WorkbenchStatusItem",
        ],
        required_mounted_components: &[
            "WorkbenchChip",
            "WorkbenchIconButton",
            "WorkbenchStatusItem",
        ],
        required_control_ids: &[
            "WorkbenchStatusReady",
            "WorkbenchStatusErrors",
            "WorkbenchStatusWarnings",
            "WorkbenchStatusGrid",
            "WorkbenchStatusZoom",
        ],
    },
    WorkbenchShellSurfaceContract {
        file_name: "workbench/shell/workbench_main_band.zui",
        component_name: "WorkbenchMainBand",
        root_node: "main_band",
        root_component: "Overlay",
        root_control_id: "WorkbenchMainBand",
        root_classes: &["workbench-main-band"],
        required_widget_imports: &[
            "res://ui/editor/components/workbench/shell/workbench_activity_rail.zui#WorkbenchActivityRail",
            "res://ui/editor/components/workbench/shell/workbench_inspector_panel.zui#WorkbenchInspectorPanel",
            "res://ui/editor/components/workbench/modules/core/index/workbench_module_workspace.zui#WorkbenchModuleWorkspace",
            "res://ui/editor/components/workbench/shell/workbench_scene_tree_panel.zui#WorkbenchSceneTreePanel",
            "res://ui/editor/components/workbench/shell/workbench_viewport_panel.zui#WorkbenchViewportPanel",
        ],
        required_mounted_components: &[
            "WorkbenchActivityRail",
            "WorkbenchInspectorPanel",
            "WorkbenchModuleWorkspace",
            "WorkbenchSceneTreePanel",
            "WorkbenchViewportPanel",
        ],
        required_control_ids: &[
            "WorkbenchSceneWorkspace",
            "WorkbenchMainBandActivityRail",
            "WorkbenchMainBandSceneTreePanel",
            "WorkbenchMainBandViewportPanel",
            "WorkbenchMainBandInspectorPanel",
            "WorkbenchMainBandModuleWorkspace",
        ],
    },
];
