//! Stable ABI and DTO contracts shared by runtime hosts, editors, and plugins.

pub mod buffer;
pub mod handles;
pub mod manifest;
pub mod math;
pub mod plugin_api;
pub mod plugin_events;
pub mod profiling;
pub mod reflect;
pub mod resource;
pub mod runtime_api;
pub mod status;
pub mod ui;
pub mod version;

pub use buffer::{ZrByteSlice, ZrFreeBytesFn, ZrOwnedByteBuffer};
pub use handles::{ZrRuntimePluginHandle, ZrRuntimeSessionHandle, ZrRuntimeViewportHandle};
pub use manifest::{ZrPluginModuleDescriptorV1, ZrPluginModuleKind, ZrRuntimeTargetMode};
pub use plugin_api::{
    ZrPluginApiV1, ZrPluginEntryFnV1, ZrPluginEntryReportV1, ZR_PLUGIN_ENTRY_SYMBOL_V1,
};
pub use plugin_events::{
    ZrPluginEventCallbackFnV1, ZrPluginEventCallbackRequestV1, ZrPluginEventCallbackResultV1,
};
pub use profiling::{
    HotspotEntry, HotspotReport, ProfileCaptureConfig, ProfileControlCommand,
    ProfileControlRequest, ProfileControlResponse, ProfileCounterSnapshot, ProfileFrameSnapshot,
    ProfileSnapshot, ProfileSpanSnapshot, UiHotspotAlert, UiHotspotReport, UiScenarioHotspot,
    ZrRuntimeProfileControlFnV1, PROFILE_DEFAULT_FRAME_BUDGET_MS, PROFILE_DEFAULT_MAX_COUNTERS,
    PROFILE_DEFAULT_MAX_FRAMES, PROFILE_DEFAULT_MAX_SPANS, PROFILE_DEFAULT_OUTPUT_ROOT,
    PROFILE_DEFAULT_SESSION_ID, PROFILE_HOTSPOTS_FILE, PROFILE_SUMMARY_FILE,
    PROFILE_TIMELINE_NATIVE_FILE, PROFILE_TIMELINE_PERFETTO_FILE, PROFILE_UI_HOTSPOTS_FILE,
};
pub use runtime_api::{
    ZrHostApiV1, ZrRuntimeAccessibilityTreeRequestV1, ZrRuntimeApiV1,
    ZrRuntimeBindViewportSurfaceFnV1, ZrRuntimeBindViewportSurfaceRequestV1,
    ZrRuntimeCaptureAccessibilityTreeFnV1, ZrRuntimeDrainHostRequestsFnV1, ZrRuntimeEventV1,
    ZrRuntimeFrameRequestV1, ZrRuntimeFrameV1, ZrRuntimeGamepadRumbleRequestKindV1,
    ZrRuntimeGamepadRumbleRequestV1, ZrRuntimeGetApiFnV1, ZrRuntimeHostFetchFnV1,
    ZrRuntimeHostFetchRequestV1, ZrRuntimeHostRequestBatchV1, ZrRuntimeHostRequestV1,
    ZrRuntimeImeCursorAreaV1, ZrRuntimeImeHostRequestKindV1, ZrRuntimeImeHostRequestV1,
    ZrRuntimeImeSurroundingTextV1, ZrRuntimeNativeSurfaceTargetV1, ZrRuntimePresentViewportFnV1,
    ZrRuntimeSessionConfigV1, ZrRuntimeTickFrameFnV1, ZrRuntimeTranslatedEventV1,
    ZrRuntimeUnbindViewportSurfaceFnV1, ZrRuntimeViewportMetricsV1, ZrRuntimeViewportSizeV1,
    ZR_RUNTIME_BUTTON_STATE_PRESSED_V1, ZR_RUNTIME_BUTTON_STATE_RELEASED_V1,
    ZR_RUNTIME_EVENT_KIND_ACCESSIBILITY_ACTION_V1, ZR_RUNTIME_EVENT_KIND_CURSOR_ENTERED_V1,
    ZR_RUNTIME_EVENT_KIND_CURSOR_LEFT_V1, ZR_RUNTIME_EVENT_KIND_FILE_DRAG_DROP_V1,
    ZR_RUNTIME_EVENT_KIND_GAMEPAD_AXIS_V1, ZR_RUNTIME_EVENT_KIND_GAMEPAD_BUTTON_V1,
    ZR_RUNTIME_EVENT_KIND_GAMEPAD_CONNECTION_V1, ZR_RUNTIME_EVENT_KIND_IME_V1,
    ZR_RUNTIME_EVENT_KIND_KEYBOARD_V1, ZR_RUNTIME_EVENT_KIND_LIFECYCLE_V1,
    ZR_RUNTIME_EVENT_KIND_MOUSE_BUTTON_V1, ZR_RUNTIME_EVENT_KIND_MOUSE_MOTION_V1,
    ZR_RUNTIME_EVENT_KIND_MOUSE_WHEEL_V1, ZR_RUNTIME_EVENT_KIND_POINTER_MOVED_V1,
    ZR_RUNTIME_EVENT_KIND_TOUCH_V1, ZR_RUNTIME_EVENT_KIND_VIEWPORT_RESIZED_V1,
    ZR_RUNTIME_EVENT_KIND_WINDOW_STATUS_V1, ZR_RUNTIME_FETCH_FLAG_STREAMING_V1,
    ZR_RUNTIME_FILE_DRAG_CANCELLED_V1, ZR_RUNTIME_FILE_DRAG_DROPPED_V1,
    ZR_RUNTIME_FILE_DRAG_HOVERED_V1, ZR_RUNTIME_GAMEPAD_AXIS_DPAD_X_V1,
    ZR_RUNTIME_GAMEPAD_AXIS_DPAD_Y_V1, ZR_RUNTIME_GAMEPAD_AXIS_LEFT_STICK_X_V1,
    ZR_RUNTIME_GAMEPAD_AXIS_LEFT_STICK_Y_V1, ZR_RUNTIME_GAMEPAD_AXIS_LEFT_Z_V1,
    ZR_RUNTIME_GAMEPAD_AXIS_RIGHT_STICK_X_V1, ZR_RUNTIME_GAMEPAD_AXIS_RIGHT_STICK_Y_V1,
    ZR_RUNTIME_GAMEPAD_AXIS_RIGHT_Z_V1, ZR_RUNTIME_GAMEPAD_AXIS_UNKNOWN_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_C_V1, ZR_RUNTIME_GAMEPAD_BUTTON_DPAD_DOWN_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_DPAD_LEFT_V1, ZR_RUNTIME_GAMEPAD_BUTTON_DPAD_RIGHT_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_DPAD_UP_V1, ZR_RUNTIME_GAMEPAD_BUTTON_EAST_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_LEFT_THUMB_V1, ZR_RUNTIME_GAMEPAD_BUTTON_LEFT_TRIGGER2_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_LEFT_TRIGGER_V1, ZR_RUNTIME_GAMEPAD_BUTTON_MODE_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_NORTH_V1, ZR_RUNTIME_GAMEPAD_BUTTON_RIGHT_THUMB_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_RIGHT_TRIGGER2_V1, ZR_RUNTIME_GAMEPAD_BUTTON_RIGHT_TRIGGER_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_SELECT_V1, ZR_RUNTIME_GAMEPAD_BUTTON_SOUTH_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_START_V1, ZR_RUNTIME_GAMEPAD_BUTTON_UNKNOWN_V1,
    ZR_RUNTIME_GAMEPAD_BUTTON_WEST_V1, ZR_RUNTIME_GAMEPAD_BUTTON_Z_V1,
    ZR_RUNTIME_GAMEPAD_CONNECTION_CONNECTED_V1, ZR_RUNTIME_GAMEPAD_CONNECTION_DISCONNECTED_V1,
    ZR_RUNTIME_GET_API_SYMBOL_V1, ZR_RUNTIME_IME_CURSOR_HIDDEN_V1, ZR_RUNTIME_IME_STATE_COMMIT_V1,
    ZR_RUNTIME_IME_STATE_CURSOR_AREA_V1, ZR_RUNTIME_IME_STATE_DELETE_SURROUNDING_V1,
    ZR_RUNTIME_IME_STATE_DISABLED_V1, ZR_RUNTIME_IME_STATE_ENABLED_V1,
    ZR_RUNTIME_IME_STATE_PREEDIT_V1, ZR_RUNTIME_IME_STATE_REQUEST_DISABLE_V1,
    ZR_RUNTIME_IME_STATE_REQUEST_ENABLE_V1, ZR_RUNTIME_IME_STATE_SURROUNDING_TEXT_V1,
    ZR_RUNTIME_KEY_ACTION_PRESSED_V1, ZR_RUNTIME_KEY_ACTION_RELEASED_V1,
    ZR_RUNTIME_KEY_ACTION_TEXT_V1, ZR_RUNTIME_LIFECYCLE_STATE_BACKGROUND_V1,
    ZR_RUNTIME_LIFECYCLE_STATE_FOREGROUND_V1, ZR_RUNTIME_LIFECYCLE_STATE_LOW_MEMORY_V1,
    ZR_RUNTIME_LIFECYCLE_STATE_RESUMED_V1, ZR_RUNTIME_LIFECYCLE_STATE_SUSPENDED_V1,
    ZR_RUNTIME_MOUSE_BUTTON_LEFT_V1, ZR_RUNTIME_MOUSE_BUTTON_MIDDLE_V1,
    ZR_RUNTIME_MOUSE_BUTTON_RIGHT_V1, ZR_RUNTIME_MOUSE_WHEEL_UNIT_LINE_V1,
    ZR_RUNTIME_MOUSE_WHEEL_UNIT_PIXEL_V1, ZR_RUNTIME_NATIVE_SURFACE_KIND_NONE_V1,
    ZR_RUNTIME_NATIVE_SURFACE_KIND_WIN32_V1, ZR_RUNTIME_TOUCH_PHASE_CANCELLED_V1,
    ZR_RUNTIME_TOUCH_PHASE_ENDED_V1, ZR_RUNTIME_TOUCH_PHASE_MOVED_V1,
    ZR_RUNTIME_TOUCH_PHASE_STARTED_V1, ZR_RUNTIME_WINDOW_BOOL_FALSE_V1,
    ZR_RUNTIME_WINDOW_BOOL_TRUE_V1, ZR_RUNTIME_WINDOW_STATUS_BACKEND_SCALE_FACTOR_CHANGED_V1,
    ZR_RUNTIME_WINDOW_STATUS_CLOSE_REQUESTED_V1, ZR_RUNTIME_WINDOW_STATUS_DESTROYED_V1,
    ZR_RUNTIME_WINDOW_STATUS_MOVED_V1, ZR_RUNTIME_WINDOW_STATUS_OCCLUDED_V1,
    ZR_RUNTIME_WINDOW_STATUS_SCALE_FACTOR_CHANGED_V1, ZR_RUNTIME_WINDOW_STATUS_THEME_CHANGED_V1,
    ZR_RUNTIME_WINDOW_THEME_DARK_V1, ZR_RUNTIME_WINDOW_THEME_LIGHT_V1,
    ZR_RUNTIME_WINDOW_THEME_UNKNOWN_V1,
};
pub use status::{ZrStatus, ZrStatusCode};
pub use version::ZIRCON_RUNTIME_ABI_VERSION_V1;

#[cfg(test)]
mod tests;
