use super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 code review findings direct assertions child-owner split",
        &[
            "runtime_15_code_review_findings_direct_assertions_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions.rs",
            "runtime_15_code_review_findings_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_f12_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_f8_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_p0_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_root_parent_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_folder_backed_summary_is_child_owner",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "runtime_15_code_review_findings_status_docs_are_child_owner",
            "render/F12 direct source checks delegated or owned",
            "78 review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings direct assertions guard folder-backed split",
        &[
            "runtime_15_code_review_findings_direct_assertions_guard_folder_backed_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/child_ownership.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/status_mirrors.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/f12.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/f8.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/p0.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/render.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/root_parent.rs",
            "runtime_15_code_review_findings_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_direct_assertions_children_are_child_owned",
            "runtime_15_code_review_findings_direct_assertions_guard_folder_backed_status_is_current",
            "runtime_15_code_review_findings_f12_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_f8_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_p0_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_render_direct_assertions_are_child_owner",
            "runtime_15_code_review_findings_root_parent_direct_assertions_are_child_owner",
            "direct_review_assertion_child_sources",
            "78 review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 code review findings direct assertions child-ownership guard folder-backed split",
        &[
            "runtime_15_code_review_findings_direct_assertions_child_ownership_guard_folder_backed_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/child_ownership.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/ownership/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/ownership/parent_absence.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/ownership/entry_points.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/ownership/budgets.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/ownership/status_mirrors.rs",
            "runtime_15_code_review_findings_direct_assertions_children_are_child_owned",
            "runtime_15_code_review_findings_direct_assertions_child_ownership_guard_is_folder_backed",
            "runtime_15_code_review_findings_direct_assertions_child_ownership_guard_folder_backed_status_is_current",
            "runtime_15_code_review_findings_direct_assertions_child_ownership_children_line_budgets_are_current",
            "Cargo gate deferred",
        ],
    ),
];
