use super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[(
    "Runtime 15 M3 review-guard direct-assertion row-data folder-backed split",
    &[
        "runtime_15_review_guard_direct_assertion_row_data_folder_backed_static_passed_cargo_deferred",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/core_rows.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/f12_rows.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/root_parent_rows.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/render_rows.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/f8_rows.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/p0_rows.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/row_data_owner_rows.rs",
        "DIRECT_ASSERTION_F12_EXPECTED_STATUS_OUTPUT_SLICES",
        "DIRECT_ASSERTION_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        "runtime_15_review_guard_direct_assertion_row_data_is_folder_backed",
        "scoped rustfmt/static scans passed",
        "Cargo gate deferred",
    ],
),
(
    "Runtime 15 M3 review-guard direct-assertion row-ownership guard child split",
    &[
        "runtime_15_review_guard_direct_assertion_row_ownership_guard_child_split_static_passed_cargo_deferred",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership/child_owner_rows.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership/folder_backed_rows.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership/folder_backed_rows/exports.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership/folder_backed_rows/status_maps.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership/status_current.rs",
        "runtime_15_status_output_review_guard_direct_assertion_rows_are_child_owner",
        "runtime_15_review_guard_direct_assertion_row_data_is_folder_backed",
        "runtime_15_review_guard_direct_assertion_row_ownership_guard_is_child_backed",
        "scoped rustfmt/static scans passed",
        "Cargo gate deferred",
    ],
),
(
    "Runtime 15 M3 review-guard direct-assertion export-chain guard child split",
    &[
        "runtime_15_review_guard_direct_assertion_export_chain_guard_child_split_static_passed_cargo_deferred",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain/review_guard_row_data.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain/code_review_rows.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain/review_guard_splits.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain/runtime_aggregation.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain/status_current.rs",
        "runtime_15_review_guard_direct_assertion_export_chain_guard_is_child_backed",
        "scoped rustfmt/static scans passed",
        "Cargo gate deferred",
    ],
),
(
    "Runtime 15 M3 code review findings direct assertions child-source sync",
    &[
        "runtime_15_code_review_findings_direct_assertions_child_source_sync_static_passed_cargo_deferred",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/child_ownership.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/direct_review_assertions/child_ownership/delegation.rs",
        "direct_review_assertion_child_source_blob",
        "direct_assertion_child_ownership_child_source_blob",
        "runtime_15_code_review_findings_direct_assertions_children_are_child_owned",
        "runtime_15_code_review_findings_folder_backed_summary_children_are_child_owned",
        "Cargo gate deferred",
    ],
)];
