pub(super) const ANCHORS: &[&str] = &[
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/budgets/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/budgets/top_level_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/mounts/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/mounts/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/runtime_15_expected_slice_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/top_level_maps/support_layout.rs",
    "structure_convention/test_file_budget/status_slices/maps/top_level_maps/support_layout/split_layout.rs",
    "structure_convention/test_file_budget/status_slices/module_layout/body/budgets.rs",
    "structure_convention/test_file_budget/status_slices/module_layout/body/child_ownership.rs",
    "structure_convention/test_file_budget/status_slices/module_layout/body/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/module_layout/body/paths.rs",
    "structure_convention/test_file_budget/status_slices/module_layout/body/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/module_layout/body/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/module_layout/guard_body.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/sources/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/sources/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/sources/model.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/sources/reads.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/sources/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/sources/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/sources/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/sources/paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/sources/reads.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/sources/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/doc_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/root_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/status_maps.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/status/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/parent_mounts/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/parent_mounts/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/parent_mounts/folder_backed.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/parent_mounts/review_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/parent_mounts/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/review_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/d13_sdk/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/review_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/review_mounts/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/review_mounts/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/review_mounts/paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/review_mounts/review_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/review_mounts/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/review_mounts/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_owners/structure/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_row_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchor_guard.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/native_typed_error.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/review_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/runtime_surface.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/source_anchors/structure_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/folder_backing.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/forwarding.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/moved_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/aggregation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/boundary_samples.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/folder_backed_summary.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/source_blob.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/status_docs.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/child_anchors/structure_guards.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchors/map_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/sync.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/typed_error/structure/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/typed_error/structure/current_checks.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/typed_error/structure/folder_backed.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/typed_error/structure/source_trees.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/typed_error/structure/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/review_guards.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/root_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/ownership/structure_subtree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/child_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/child_sources/structure_guard.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/child_sources/structure_guard/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/child_sources/structure_guard/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/child_sources/structure_guard/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/guard_body.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/ownership/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/ownership/delegation_parent.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/ownership/folder_backed_parent.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/ownership/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/ownership/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/folder_backed/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/parent_delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/source_inventory_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/source_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/delegation/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/inventory/current/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/inventory/current/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/inventory/current/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/child_inventory_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/current/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/current/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/current/source_blobs.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/current/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/delegation_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/review_guard_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/metadata/status_slices.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/reads.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/source_helper_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/source_helper_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/sources/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/child_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/child_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/sources/delegation_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/sources/status_current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/sources/current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/sources/split_layout_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/status_sync.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/status_doc_parent.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/typed_error_parent.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/guard_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/source_helper_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/source_helper_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/source_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/doc_mirrors/status_slices.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/sources/status_current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/sources/status_maps_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/sources/current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/sources/split_layout_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/status_sync.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/review_slices.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/sources/status_current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/sources/status_mirrors_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/sources/current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/sources/split_layout_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/status_sync.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/folder_backed_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/sources/paths_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/sources/status_current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/split/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/status_sync.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/guard_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/paths_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/source_helper_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/parent_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/sources/current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/sources/source_split.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/sources/split_layout_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/split_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/status_current_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/review_guard_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/status_slices.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/source_helper_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/source_helper_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/status_maps.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts/asset_parents.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts/runtime_parents.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts/top_level.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/child_ownership_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/guard_body.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/guard_names.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/parent_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/parent_backflow/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/root_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/moved_guard_absence/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/abi_surfaces.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/lifecycle_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/live_host.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/manifest_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/plugin_descriptor.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/replay_runtime.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/source_helper_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/source_helper_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/routes/top_level.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/source_helper_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/source_helper_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/native_plugin_loader/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/status_support_review_guard_rows.rs",
    "use lifecycle_fixtures::*;",
    "#[path = \"code_review/direct_assertion_rows.rs\"]",
    "#[path = \"code_review/expected_slice_rows.rs\"]",
    "#[path = \"code_review/folder_backed_summary_rows.rs\"]",
    "#[path = \"code_review/source_inventory_rows.rs\"]",
    "#[path = \"code_review/status_doc_rows.rs\"]",
    "#[path = \"code_review/structure_guard_rows.rs\"]",
    "#[path = \"review/code_review_guard_maps.rs\"]",
    "#[path = \"review/foundation_review_maps.rs\"]",
    "#[path = \"review/plugin_importer_maps.rs\"]",
    "#[path = \"review/top_row_review_maps.rs\"]",
    "#[path = \"review/typed_error_maps.rs\"]",
    "#[path = \"review/typed_error_structure_maps.rs\"]",
    "#[path = \"route_meta/child_owner_budget_rows.rs\"]",
    "#[path = \"route_meta/child_owner_guard_rows.rs\"]",
    "#[path = \"route_meta/naming_boundary_rows.rs\"]",
    "#[path = \"route_meta/row_data_owner_rows.rs\"]",
    "#[path = \"runtime_plugin_lifecycle/lifecycle_fixtures.rs\"]",
    "#[path = \"status/delegation.rs\"]",
    "#[path = \"structure/convergence_mounts.rs\"]",
    "frameworks_02_m3_code_review_findings_structure_guard_typed_error_structure_assertions_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_review_guard_expected_slice_root_route_metadata_status_mirror_guard_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_review_guard_source_status_maps_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 code review findings structure guard typed-error structure assertions folder-backed split",
    "Runtime 15 M3 review-guard direct-assertion export-chain guard child split",
    "Runtime 15 M3 review-guard rows row-data owner child split",
    "Runtime 15 M3 review-guard source status maps folder-backed split",
    "Runtime 15 M3 review-guard typed-error status-doc guard folder-backed split",
    "Runtime 15 M3 review-guard typed-error structure-assertions guard folder-backed split",
    "Runtime 15 M3 status-support expected-slice row-data guard folder-backed split",
    "Runtime 15 M3 typed-error status-doc delegation status-current sources child split",
    "Runtime 15 M3 typed-error status-doc delegation status-current split-layout sources child split",
    "Runtime 15 M3 typed-error status-doc paths child inventory child split",
    "Runtime 15 M3 typed-error status-doc paths child inventory split-layout folder-backed split",
    "Runtime 15 M3 typed-error status-doc paths child inventory split-layout guard folder-backed split",
    "Runtime 15 M3 typed-error status-doc paths child inventory split-layout sources child split",
    "Runtime 15 M3 typed-error status-doc paths status-current child split",
    "Runtime 15 M3 typed-error status-doc paths status-current sources child split",
    "Runtime 15 M3 typed-error status-doc paths status-current split-layout folder-backed split",
    "Runtime 15 M3 typed-error status-doc paths status-current split-layout guard folder-backed split",
    "Runtime 15 M3 typed-error status-doc root paths folder-backed split",
    "Runtime 15 M3 typed-error status-doc status maps status-current sources child split",
    "Runtime 15 M3 typed-error status-doc status maps status-current split-layout sources child split",
    "Runtime 15 M3 typed-error status-doc status mirrors status-current sources child split",
    "Runtime 15 M3 typed-error status-doc status mirrors status-current split-layout sources child split",
    "Runtime 15 M3 typed-error status-doc status-slices folder-backed split",
    "runtime_15_code_review_findings_structure_guard_typed_error_structure_assertions_folder_backed_static_passed_cargo_deferred",
    "runtime_15_code_review_findings_structure_guard_typed_error_structure_assertions_guard_is_folder_backed",
    "runtime_15_review_guard_direct_assertion_export_chain_guard_child_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_rows_row_data_owner_child_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_rows_row_data_owner_is_child_backed",
    "runtime_15_review_guard_source_status_maps_are_child_owned",
    "runtime_15_review_guard_source_status_maps_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_typed_error_status_doc_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_typed_error_status_docs_guard_is_folder_backed",
    "runtime_15_review_guard_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_typed_error_structure_assertions_guard_is_folder_backed",
    "runtime_15_status_support_expected_slice_row_data_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_status_support_expected_slice_row_data_guard_is_folder_backed",
    "runtime_15_typed_error_status_doc_delegation_status_current_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_delegation_status_current_sources_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_delegation_status_current_split_layout_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_delegation_status_current_split_layout_sources_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_child_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_child_inventory_is_child_backed",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_guard_is_folder_backed",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_is_folder_backed",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_sources_child_split_static_passed_cargo_deferred",
    "#[path = \"code_review/direct_assertion_rows.rs\"]",
    "#[path = \"code_review/expected_slice_rows.rs\"]",
    "#[path = \"code_review/folder_backed_summary_rows.rs\"]",
    "#[path = \"code_review/source_inventory_rows.rs\"]",
    "#[path = \"code_review/status_doc_rows.rs\"]",
    "#[path = \"code_review/structure_guard_rows.rs\"]",
    "#[path = \"review/code_review_guard_maps.rs\"]",
    "#[path = \"review/foundation_review_maps.rs\"]",
    "#[path = \"review/plugin_importer_maps.rs\"]",
    "#[path = \"review/top_row_review_maps.rs\"]",
    "#[path = \"review/typed_error_maps.rs\"]",
    "#[path = \"review/typed_error_structure_maps.rs\"]",
    "#[path = \"route_meta/child_owner_budget_rows.rs\"]",
    "#[path = \"route_meta/child_owner_guard_rows.rs\"]",
    "#[path = \"route_meta/naming_boundary_rows.rs\"]",
    "#[path = \"route_meta/row_data_owner_rows.rs\"]",
    "#[path = \"runtime_plugin_lifecycle/lifecycle_fixtures.rs\"]",
    "#[path = \"status/delegation.rs\"]",
    "#[path = \"structure/convergence_mounts.rs\"]",
    "runtime_15_typed_error_status_doc_paths_status_current_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_status_current_is_child_backed",
    "runtime_15_typed_error_status_doc_paths_status_current_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_paths_status_current_sources_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_status_current_split_layout_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_status_current_split_layout_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_status_current_split_layout_guard_is_folder_backed",
    "runtime_15_typed_error_status_doc_paths_status_current_split_layout_is_folder_backed",
    "runtime_15_typed_error_status_doc_root_paths_are_folder_backed",
    "runtime_15_typed_error_status_doc_root_paths_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_status_maps_status_current_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_status_maps_status_current_sources_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_status_maps_status_current_split_layout_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_status_maps_status_current_split_layout_sources_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_status_mirrors_status_current_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_status_mirrors_status_current_sources_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_status_mirrors_status_current_split_layout_sources_are_child_backed",
    "runtime_15_typed_error_status_doc_status_mirrors_status_current_split_layout_sources_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_status_slices_are_folder_backed",
    "runtime_15_typed_error_status_doc_status_slices_folder_backed_static_passed_cargo_deferred",
    "Some(\"2026-06-24\")",
    "split/body/budgets/status_docs.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/aggregation.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/folder_backed.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/route_mounts.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_status_docs.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions.rs",
    "structure_convention/test_file_budget/status_slices/legacy_group_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/body/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/review_route_children/route_meta/budgets/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/review_route_children/route_meta/budgets/guard_body.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/review_route_children/route_meta/budgets/parent_routes.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/review_route_children/route_meta/budgets/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/review_route_children/route_meta/budgets/source_children.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/review_route_children/route_meta/budgets/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/review_route_children/route_meta/budgets/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/foundation_review_maps/expected_slice_rows/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/foundation_review_maps/expected_slice_rows/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/foundation_review_maps/expected_slice_rows/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/foundation_review_maps/expected_slice_rows/route_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/foundation_review_maps/expected_slice_rows/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/foundation_review_maps/expected_slice_rows/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/route_children/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/route_children/ownership.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/route_children/route_inventory.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/route_children/source_reads.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/route_children/status_metadata.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/route_children/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/sources/route_children/structure_rows.rs",
    "#[path = \"code_review/direct_assertion_rows.rs\"]",
    "#[path = \"code_review/expected_slice_rows.rs\"]",
    "#[path = \"code_review/folder_backed_summary_rows.rs\"]",
    "#[path = \"code_review/source_inventory_rows.rs\"]",
    "#[path = \"code_review/status_doc_rows.rs\"]",
    "#[path = \"code_review/structure_guard_rows.rs\"]",
    "#[path = \"review/code_review_guard_maps.rs\"]",
    "#[path = \"review/foundation_review_maps.rs\"]",
    "#[path = \"review/plugin_importer_maps.rs\"]",
    "#[path = \"review/top_row_review_maps.rs\"]",
    "#[path = \"review/typed_error_maps.rs\"]",
    "#[path = \"review/typed_error_structure_maps.rs\"]",
    "#[path = \"route_meta/child_owner_budget_rows.rs\"]",
    "#[path = \"route_meta/child_owner_guard_rows.rs\"]",
    "#[path = \"route_meta/naming_boundary_rows.rs\"]",
    "#[path = \"route_meta/row_data_owner_rows.rs\"]",
    "#[path = \"runtime_plugin_lifecycle/lifecycle_fixtures.rs\"]",
    "#[path = \"status/delegation.rs\"]",
    "#[path = \"structure/convergence_mounts.rs\"]",
    "Some(\"2026-06-24\")",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/child_group_row_data_map_rows/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/child_group_row_data_map_rows/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/child_group_row_data_map_rows/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/child_group_row_data_map_rows/route_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/child_group_row_data_map_rows/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/child_group_row_data_map_rows/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/m3_m4_map_rows/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/m3_m4_map_rows/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/m3_m4_map_rows/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/m3_m4_map_rows/route_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/m3_m4_map_rows/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/m3_m4_map_rows/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/priority_plan_doc_map_rows.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/mirrors/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/mirrors/row_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/mirrors/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_meta/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/route_metadata.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/runtime_index_anchor_map_rows/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/runtime_index_anchor_map_rows/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/runtime_index_anchor_map_rows/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/runtime_index_anchor_map_rows/route_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/runtime_index_anchor_map_rows/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/status/runtime_index_anchor_map_rows/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/literal/mirrors/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/literal/mirrors/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/literal/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/mirrors/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/mirrors/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/parent_routes/body/route_meta/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/parent_routes/body/route_meta/doc_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/parent_routes/body/route_meta/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/parent_routes/body/route_meta/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/parent_routes/body/route_meta/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/parent_routes/body/route_meta/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/runtime07_script_map_rows/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/runtime07_script_map_rows/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/runtime07_script_map_rows/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/runtime07_script_map_rows/route_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/runtime07_script_map_rows/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/runtime07_script_map_rows/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/structure_route_maps/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/structure_route_maps/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/structure_route_maps/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/structure_route_maps/route_maps.rs",
    "#[path = \"code_review/direct_assertion_rows.rs\"]",
    "#[path = \"code_review/expected_slice_rows.rs\"]",
    "#[path = \"code_review/folder_backed_summary_rows.rs\"]",
    "#[path = \"code_review/source_inventory_rows.rs\"]",
    "#[path = \"code_review/status_doc_rows.rs\"]",
    "#[path = \"code_review/structure_guard_rows.rs\"]",
    "#[path = \"review/code_review_guard_maps.rs\"]",
    "#[path = \"review/foundation_review_maps.rs\"]",
    "#[path = \"review/plugin_importer_maps.rs\"]",
    "#[path = \"review/top_row_review_maps.rs\"]",
    "#[path = \"review/typed_error_maps.rs\"]",
    "#[path = \"review/typed_error_structure_maps.rs\"]",
    "#[path = \"route_meta/child_owner_budget_rows.rs\"]",
    "#[path = \"route_meta/child_owner_guard_rows.rs\"]",
    "#[path = \"route_meta/naming_boundary_rows.rs\"]",
    "#[path = \"route_meta/row_data_owner_rows.rs\"]",
    "#[path = \"runtime_plugin_lifecycle/lifecycle_fixtures.rs\"]",
    "#[path = \"status/delegation.rs\"]",
    "#[path = \"structure/convergence_mounts.rs\"]",
    "Some(\"2026-06-24\")",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/structure_route_maps/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/structure/structure_route_maps/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/route_meta/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/route_meta/doc_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/route_meta/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/route_meta/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/route_meta/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/route_meta/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/status_doc_map_rows/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/status_doc_map_rows/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/status_doc_map_rows/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/status_doc_map_rows/route_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/status_doc_map_rows/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/status_doc_map_rows/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/structure_map_rows/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/structure_map_rows/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/structure_map_rows/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/structure_map_rows/route_maps.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/structure_map_rows/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/review/typed_error/structure_map_rows/status_docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/foundation/mirrors/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/foundation/mirrors/docs.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/foundation/mirrors/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/foundation/mirrors/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/foundation/mirrors/row_data.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/budgets/route_meta/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/budgets/route_meta/doc_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/budgets/route_meta/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/budgets/route_meta/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/budgets/route_meta/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/budgets/route_meta/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/body/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/body/doc_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/body/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/body/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/body/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/route_meta/budgets.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/route_meta/doc_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/route_meta/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/route_meta/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/route_meta/route_mounts.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/owners/split/route_meta/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/doc_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/folder_backed.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/paths.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/body/status_mirrors.rs",
    "structure_convention/test_file_budget/status_slices/maps/rt15/rt15_slices/split/guard_body.rs",
    "structure_convention/test_file_budget/status_slices/module_layout.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure/convergence_mounts/root_inventory.rs",
    // current owner anchors appended below
];
