pub(super) const ANCHORS: &[&str] = &[
    "#[path = \"code_review/direct_assertion_rows.rs\"]",
    "#[path = \"code_review/expected_slice_rows.rs\"]",
    "#[path = \"code_review/folder_backed_summary_rows.rs\"]",
    "#[path = \"code_review/source_inventory_rows.rs\"]",
    "#[path = \"code_review/status_doc_rows.rs\"]",
    "#[path = \"code_review/structure_guard_rows.rs\"]",
    "#[path = \"review/code_review_guard_maps.rs\"]",
    "#[path = \"review/foundation_review_maps.rs\"]",
    "#[path = \"review/plugin_importer_maps.rs\"]",
    "#[path = \"review/top_row_review_maps.rs\"]",
    "#[path = \"review/typed_error_maps.rs\"]",
    "#[path = \"review/typed_error_structure_maps.rs\"]",
    "#[path = \"route_meta/child_owner_budget_rows.rs\"]",
    "#[path = \"route_meta/child_owner_guard_rows.rs\"]",
    "#[path = \"route_meta/naming_boundary_rows.rs\"]",
    "#[path = \"route_meta/row_data_owner_rows.rs\"]",
    "#[path = \"status/delegation.rs\"]",
    "#[path = \"structure/convergence_mounts.rs\"]",
    "2026-07-04",
    "Cargo gate deferred",
    "impl RuntimePlugin for OptionalDependencyProbe",
    "impl RuntimePluginFeature for ReadyOrderFeature",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/status_docs/foundation_m2_rows.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/base_maps.rs",
    "pub(super) struct LifecycleOrderFeature",
    "pub(super) struct LifecycleOrderPlugin",
    "pub(super) struct OptionalDependencyProbe",
    "pub(super) struct OrderedLifecyclePlugin",
    "pub(super) struct ReadyOrderFeature",
    "pub(super) struct ReadyOrderPlugin",
    "Runtime 15 M3 asset-budget asset-tests guard folder-backed split",
    "Runtime 15 M3 asset-budget asset-tests row-data child split",
    "Runtime 15 M3 asset-budget naming graphics misc guard folder-backed split",
    "Runtime 15 M3 asset-budget naming graphics misc row-data child split",
    "Runtime 15 M3 child-group status-row-doc guard child-owner split",
    "Runtime 15 M3 foundation-guards runtime-structure guard folder-backed split",
    "Runtime 15 M3 foundation-guards runtime-structure row-data child split",
    "Runtime 15 M3 review-guard typed-error row-data child split",
    "Runtime 15 M3 review-guard typed-error structure-assertions guard folder-backed split",
    "Runtime 15 M3 scene-script plugin-extension guard folder-backed split",
    "Runtime 15 M3 scene-script plugin-extension row-data child split",
    "Runtime 15 M3 scene-script Runtime 07 performance guard folder-backed split",
    "Runtime 15 M3 scene-script Runtime 07 performance row-data child split",
    "Runtime 15 M3 test file budget root-layout UI child split",
    "Runtime 15 M3 typed-error structure row-data guard folder-backed split",
    "Runtime 15 M3 typed-error structure row-data owner child split",
    "Runtime 15 M3 UI accessibility test folder split",
    "Runtime 15 M3 UI accessibility widget actions test folder split",
    "Runtime 15 M3 UI architecture test folder split",
    "Runtime 15 M3 UI asset MUI web form style test folder split",
    "Runtime 15 M3 UI asset MUI web style test folder split",
    "Runtime 15 M3 UI asset MUI X web style test folder split",
    "Runtime 15 M3 UI asset surface index test folder split",
    "Runtime 15 M3 UI asset test folder split",
    "Runtime 15 M3 UI boundary test folder split",
    "Runtime 15 M3 UI component catalog test folder split",
    "Runtime 15 M3 UI component state keyboard test folder split",
    "Runtime 15 M3 UI component state test folder split",
    "Runtime 15 M3 UI event routing test folder split",
    "Runtime 15 M3 UI focus navigation test folder split",
    "Runtime 15 M3 UI layout slots test folder split",
    "Runtime 15 M3 UI Material foundation test folder split",
    "Runtime 15 M3 UI material layout test folder split",
    "Runtime 15 M3 UI runtime input manager test folder split",
    "Runtime 15 M3 UI runtime input ownership test folder split",
    "Runtime 15 M3 UI runtime input reply route child folder split",
    "Runtime 15 M3 UI runtime input reply route guard child-owner split",
    "Runtime 15 M3 UI runtime input reply routes test folder split",
    "Runtime 15 M3 UI runtime input reply table pointer route folder split",
    "Runtime 15 M3 UI runtime window event ABI child folder split",
    "Runtime 15 M3 UI runtime window input pump test folder split",
    "Runtime 15 M3 UI shared core guard child-owner split",
    "Runtime 15 M3 UI shared core input visibility child folder split",
    "Runtime 15 M3 UI shared core layout surface child folder split",
    "Runtime 15 M3 UI shared core scroll mutation child folder split",
    "Runtime 15 M3 UI surface dirty domains test folder split",
    "Runtime 15 M3 UI surface-frame authority test folder split",
    "Runtime 15 M3 UI taffy layout pass test folder split",
    "Runtime 15 M3 UI template test folder split",
    "Runtime 15 M3 UI widget text input keyboard test folder split",
    "runtime_15_asset_budget_asset_tests_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_asset_budget_asset_tests_guard_is_folder_backed",
    "runtime_15_asset_budget_asset_tests_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_asset_budget_asset_tests_row_data_is_child_backed",
    "runtime_15_asset_budget_naming_graphics_misc_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_asset_budget_naming_graphics_misc_guard_is_folder_backed",
    "runtime_15_asset_budget_naming_graphics_misc_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_asset_budget_naming_graphics_misc_row_data_is_child_backed",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_guard_is_folder_backed",
    "runtime_15_foundation_guards_runtime_structure_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_row_data_is_child_backed",
    "runtime_15_m3_child_group_moved_rows_guard_is_folder_backed",
    "runtime_15_m3_child_group_status_row_docs_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_plugin_importer_d13_sdk_review_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_typed_error_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_typed_error_structure_assertions_guard_is_folder_backed",
    "runtime_15_scene_script_plugin_extension_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_scene_script_plugin_extension_guard_is_folder_backed",
    "runtime_15_scene_script_plugin_extension_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_scene_script_plugin_extension_row_data_is_child_backed",
    "runtime_15_scene_script_runtime_07_performance_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_scene_script_runtime_07_performance_guard_is_folder_backed",
    "runtime_15_scene_script_runtime_07_performance_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_scene_script_runtime_07_performance_row_data_is_child_backed",
    "runtime_15_status_output_m3_child_group_moved_rows_are_child_owner",
    "runtime_15_test_file_budget_root_layout_ui_child_scan_is_child_owner",
    "runtime_15_test_file_budget_root_layout_ui_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_structure_row_data_owner_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_structure_rows_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_structure_rows_guard_is_folder_backed",
    "runtime_15_typed_error_structure_rows_row_data_owner_is_child_backed",
    "runtime_15_ui_accessibility_tests_are_folder_backed",
    "runtime_15_ui_accessibility_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_accessibility_widget_actions_tests_are_folder_backed",
    "runtime_15_ui_accessibility_widget_actions_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_architecture_tests_are_folder_backed",
    "runtime_15_ui_architecture_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_asset_mui_web_form_style_tests_are_folder_backed",
    "runtime_15_ui_asset_mui_web_form_style_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_asset_mui_web_mui_x_style_tests_are_folder_backed",
    "runtime_15_ui_asset_mui_web_mui_x_style_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_asset_mui_web_style_tests_are_folder_backed",
    "runtime_15_ui_asset_mui_web_style_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_asset_surface_index_tests_are_folder_backed",
    "runtime_15_ui_asset_surface_index_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_asset_tests_are_folder_backed",
    "runtime_15_ui_asset_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_boundary_tests_are_folder_backed",
    "runtime_15_ui_boundary_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_component_catalog_component_state_keyboard_tests_are_folder_backed",
    "runtime_15_ui_component_catalog_component_state_keyboard_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_component_catalog_component_state_tests_are_folder_backed",
    "runtime_15_ui_component_catalog_component_state_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_component_catalog_material_foundation_tests_are_folder_backed",
    "runtime_15_ui_component_catalog_material_foundation_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_component_catalog_tests_are_folder_backed",
    "runtime_15_ui_component_catalog_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_event_routing_tests_are_folder_backed",
    "runtime_15_ui_event_routing_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_focus_navigation_tests_are_folder_backed",
    "runtime_15_ui_focus_navigation_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_layout_slots_tests_are_folder_backed",
    "runtime_15_ui_layout_slots_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_material_layout_tests_are_folder_backed",
    "runtime_15_ui_material_layout_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_input_manager_tests_are_folder_backed",
    "runtime_15_ui_runtime_input_manager_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_input_ownership_tests_are_folder_backed",
    "runtime_15_ui_runtime_input_ownership_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_input_reply_route_children_are_folder_backed",
    "runtime_15_ui_runtime_input_reply_route_children_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_input_reply_route_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_input_reply_route_guard_child_owners_are_folder_backed",
    "runtime_15_ui_runtime_input_reply_routes_tests_are_folder_backed",
    "runtime_15_ui_runtime_input_reply_routes_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_input_reply_table_pointer_routes_are_folder_backed",
    "runtime_15_ui_runtime_input_reply_table_pointer_routes_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_window_event_abi_children_are_folder_backed",
    "runtime_15_ui_runtime_window_event_abi_children_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_runtime_window_input_pump_tests_are_folder_backed",
    "runtime_15_ui_runtime_window_input_pump_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_shared_core_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_ui_shared_core_guard_child_owners_are_folder_backed",
    "runtime_15_ui_shared_core_input_visibility_child_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_shared_core_input_visibility_children_are_folder_backed",
    "runtime_15_ui_shared_core_layout_surface_child_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_shared_core_layout_surface_children_are_folder_backed",
    "runtime_15_ui_shared_core_scroll_mutation_child_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_shared_core_scroll_mutation_children_are_folder_backed",
    "runtime_15_ui_surface_dirty_domains_tests_are_folder_backed",
    "runtime_15_ui_surface_dirty_domains_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_surface_frame_authority_tests_are_folder_backed",
    "runtime_15_ui_surface_frame_authority_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_taffy_layout_pass_tests_are_folder_backed",
    "runtime_15_ui_taffy_layout_pass_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_template_tests_are_folder_backed",
    "runtime_15_ui_template_tests_folder_split_static_passed_cargo_deferred",
    "runtime_15_ui_widget_text_input_keyboard_tests_are_folder_backed",
    "runtime_15_ui_widget_text_input_keyboard_tests_folder_split_static_passed_cargo_deferred",
    "Some(\"2026-06-24\")",
    "structure_convention/test_file_budget/root_layout/ui_children.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/anchor_mirror.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/aggregation.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/folder_backed.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/route_mounts.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/lock_poison_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/module_convention_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/review_top_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_row_data/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_row_data/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_row_data/row_ownership.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m4_row_data/row_ownership.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/folder_backed.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/row_groups.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/status_doc_paths.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/folder_backed.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/row_routes.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/status_mirrors.rs",
    "structure_convention/test_file_budget/ui_runtime_input_reply_routes.rs",
    "structure_convention/test_file_budget/ui_runtime_input_reply_routes/route_children.rs",
    "structure_convention/test_file_budget/ui_shared_core.rs",
    "structure_convention/test_file_budget/ui_shared_core/layout_surface.rs",
    "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/status/core.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status/status_anchor_guard/ownership/mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/sources/source/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/sources/source/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/maps/current/split/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/sources/source/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/sources/source/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/sources/source/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/sources/source/status_current.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/root_paths/status_doc_core.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/status_slices/paths.rs",
    "tests/runtime_absorption/ui_architecture.rs",
    "tests/runtime_absorption/ui_architecture/architecture_boundaries.rs",
    "tests/runtime_absorption/ui_architecture/legacy_renames.rs",
    "ui/tests/accessibility_widget_actions.rs",
    "ui/tests/accessibility_widget_actions/popup_actions.rs",
    "ui/tests/accessibility.rs",
    "ui/tests/accessibility/extraction.rs",
    "ui/tests/accessibility/value_actions.rs",
    "ui/tests/asset_mui_web_form_style.rs",
    "ui/tests/asset_mui_web_form_style/form_controls.rs",
    "ui/tests/asset_mui_web_mui_x_style.rs",
    "ui/tests/asset_mui_web_mui_x_style/data_grid.rs",
    "ui/tests/asset_mui_web_style.rs",
    "ui/tests/asset_mui_web_style/state_icons.rs",
    "ui/tests/asset_surface_index.rs",
    "ui/tests/asset_surface_index/dirty_targets.rs",
    "ui/tests/asset_surface_index/surface_edges.rs",
    "ui/tests/asset.rs",
    "ui/tests/asset/style_rule_ids.rs",
    "ui/tests/boundary.rs",
    "ui/tests/boundary/template_namespace.rs",
    "ui/tests/component_catalog.rs",
    "ui/tests/component_catalog/catalog_inventory.rs",
    "ui/tests/component_catalog/component_state.rs",
    "ui/tests/component_catalog/component_state/keyboard.rs",
    "ui/tests/component_catalog/component_state/keyboard/action_selection.rs",
    "ui/tests/component_catalog/component_state/reference_sources.rs",
    "ui/tests/component_catalog/material_foundation/mod.rs",
    "ui/tests/component_catalog/material_foundation/planned_layers.rs",
    "ui/tests/event_routing.rs",
    "ui/tests/event_routing/pointer_state.rs",
    "ui/tests/event_routing/shared_input.rs",
    "ui/tests/focus_navigation.rs",
    "ui/tests/focus_navigation/focus_state.rs",
    "ui/tests/layout_slots.rs",
    "ui/tests/layout_slots/linear_free.rs",
    "ui/tests/material_layout.rs",
    "ui/tests/material_layout/button_icon_metrics.rs",
    "ui/tests/runtime_input_manager.rs",
    "ui/tests/runtime_input_manager/route_matrix.rs",
    "ui/tests/runtime_input_ownership.rs",
    "ui/tests/runtime_input_ownership/input_method.rs",
    "ui/tests/runtime_input_reply_routes.rs",
    "ui/tests/runtime_input_reply_routes/focus_text_accessibility_routes.rs",
    "ui/tests/runtime_input_reply_routes/keyboard_navigation_routes.rs",
    "ui/tests/runtime_input_reply_routes/keyboard_navigation_routes/focus_path.rs",
    "ui/tests/runtime_input_reply_routes/route_trace_routes.rs",
    "ui/tests/runtime_input_reply_routes/table_pointer_routes.rs",
    "ui/tests/runtime_input_reply_routes/table_pointer_routes/resize.rs",
    "ui/tests/runtime_input_reply_routes/table_pointer_routes/virtualization.rs",
    "ui/tests/runtime_input_reply_routes/tree_view_pointer_routes/selection.rs",
    "ui/tests/runtime_ui_window_event_routes/abi.rs",
    "ui/tests/runtime_ui_window_event_routes/abi/batch_adapter.rs",
    "ui/tests/runtime_window_input_pump.rs",
    "ui/tests/runtime_window_input_pump/lifecycle.rs",
    "ui/tests/shared_core/input_visibility.rs",
    "ui/tests/shared_core/input_visibility/hit_visibility.rs",
    "ui/tests/shared_core/input_visibility/pointer_routes.rs",
    "ui/tests/shared_core/layout_surface.rs",
    "ui/tests/shared_core/layout_surface/layout_measurement.rs",
    "ui/tests/shared_core/layout_surface/render_extract.rs",
    "ui/tests/shared_core/scroll_mutation.rs",
    "ui/tests/shared_core/scroll_mutation/property_mutation.rs",
    "ui/tests/shared_core/scroll_mutation/virtual_scroll.rs",
    "ui/tests/surface_dirty_domains.rs",
    "ui/tests/surface_dirty_domains/rebuild_domains.rs",
    "ui/tests/surface_frame_authority.rs",
    "ui/tests/surface_frame_authority/arranged_authority.rs",
    "ui/tests/taffy_layout_pass.rs",
    "ui/tests/taffy_layout_pass/routing_diagnostics.rs",
    "ui/tests/template.rs",
    "ui/tests/template/interaction_bindings.rs",
    "ui/tests/widget_text_input_keyboard.rs",
    "ui/tests/widget_text_input_keyboard/basic_editing.rs",
    "use super::*;",
];
