pub(super) const ANCHORS: &[&str] = &[
    "#[path = \"code_review/direct_assertion_rows.rs\"]",
    "#[path = \"code_review/expected_slice_rows.rs\"]",
    "#[path = \"code_review/folder_backed_summary_rows.rs\"]",
    "#[path = \"code_review/source_inventory_rows.rs\"]",
    "#[path = \"code_review/status_doc_rows.rs\"]",
    "#[path = \"code_review/structure_guard_rows.rs\"]",
    "#[path = \"review/code_review_guard_maps.rs\"]",
    "#[path = \"review/foundation_review_maps.rs\"]",
    "#[path = \"review/plugin_importer_maps.rs\"]",
    "#[path = \"review/top_row_review_maps.rs\"]",
    "#[path = \"review/typed_error_maps.rs\"]",
    "#[path = \"review/typed_error_structure_maps.rs\"]",
    "#[path = \"route_meta/child_owner_budget_rows.rs\"]",
    "#[path = \"route_meta/child_owner_guard_rows.rs\"]",
    "#[path = \"route_meta/naming_boundary_rows.rs\"]",
    "#[path = \"route_meta/row_data_owner_rows.rs\"]",
    "#[path = \"runtime_plugin_lifecycle/lifecycle_fixtures.rs\"]",
    "#[path = \"status/delegation.rs\"]",
    "#[path = \"structure/convergence_mounts.rs\"]",
    "2026-06-23",
    "2026-07-03",
    "2026-07-05",
    "21/23/18/11",
    "73",
    "Cargo gate deferred",
    "frameworks_02_m3_review_guard_source_metadata_folder_backed_static_passed_cargo_deferred",
    "mod lifecycle_fixtures;",
    "plan_status/status_output_tables/expected_slices/status.rs",
    "plan_status/status_output_tables/expected_slices/status/runtime_15.rs",
    "plan_status/status_output_tables/expected_status_row_data.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/asset_tests.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/budget_render_ui.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_core_asset_dynamic.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_graphics_misc.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/runtime_rhi.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/priority_plan_docs.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/runtime_index_anchors.rs",
    "render_product_camera_targets/custom_target/composite.rs",
    "render_product_camera_targets/custom_target/material_sampling.rs",
    "render_product_camera_targets/custom_target/viewport.rs",
    "Runtime 15 M3 asset-budget asset-tests guard folder-backed split",
    "Runtime 15 M3 asset-budget asset-tests row-data child split",
    "Runtime 15 M3 asset-budget naming graphics misc guard folder-backed split",
    "Runtime 15 M3 asset-budget naming graphics misc row-data child split",
    "Runtime 15 M3 child-group status-row-doc guard child-owner split",
    "Runtime 15 M3 foundation row-data 73-row docs sync",
    "Runtime 15 M3 foundation-guards runtime-structure guard folder-backed split",
    "Runtime 15 M3 foundation-guards runtime-structure row-data child split",
    "Runtime 15 M3 lock-poison status row-data guard folder-backed split",
    "Runtime 15 M3 lock-poison status row-data root inventory child split",
    "Runtime 15 M3 lock-poison status row-data status-mirror child split",
    "Runtime 15 M3 review-guard source metadata folder-backed split",
    "Runtime 15 M3 review-guard typed-error structure-assertions guard folder-backed split",
    "Runtime 15 M3 Runtime 15 row-data guard folder-backed split",
    "Runtime 15 M3 scene-script plugin-extension guard folder-backed split",
    "Runtime 15 M3 scene-script plugin-extension row-data child split",
    "Runtime 15 M3 scene-script Runtime 07 performance guard folder-backed split",
    "Runtime 15 M3 scene-script Runtime 07 performance row-data child split",
    "Runtime 15 M3 typed-error status-doc paths child inventory split-layout status mirrors guard folder-backed split",
    "Runtime 15 M3 typed-error status-doc paths status-current split-layout status mirrors guard folder-backed split",
    "Runtime 15 M3 typed-error status-doc status maps status-current sources guard folder-backed split",
    "Runtime 15 M3 typed-error status-doc status maps status-current split-layout sources guard folder-backed split",
    "Runtime 15 M3 typed-error structure row-data guard folder-backed split",
    "Runtime 15 M3 typed-error structure row-data owner child split",
    "runtime_15_asset_budget_asset_tests_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_asset_budget_asset_tests_guard_is_folder_backed",
    "runtime_15_asset_budget_asset_tests_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_asset_budget_asset_tests_row_data_is_child_backed",
    "runtime_15_asset_budget_naming_graphics_misc_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_asset_budget_naming_graphics_misc_guard_is_folder_backed",
    "runtime_15_asset_budget_naming_graphics_misc_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_asset_budget_naming_graphics_misc_row_data_is_child_backed",
    "runtime_15_asset_budget_row_data_owner_is_child_backed",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_guard_is_folder_backed",
    "runtime_15_foundation_guards_runtime_structure_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_row_data_is_child_backed",
    "runtime_15_foundation_row_data_71_row_docs_sync_static_passed_cargo_deferred",
    "runtime_15_foundation_row_data_docs_record_current_row_count",
    "runtime_15_lock_poison_status_row_data_children_guard_is_folder_backed",
    "runtime_15_lock_poison_status_row_data_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_lock_poison_status_row_data_owner_is_child_backed",
    "runtime_15_lock_poison_status_row_data_root_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_lock_poison_status_row_data_root_inventory_is_child_owned",
    "runtime_15_lock_poison_status_row_data_status_mirror_child_split_static_passed_cargo_deferred",
    "runtime_15_lock_poison_status_row_data_status_mirror_children_are_child_owned",
    "runtime_15_m3_child_group_status_row_docs_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_plugin_importer_d13_sdk_review_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_source_metadata_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_source_metadata_is_folder_backed",
    "runtime_15_review_guard_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_typed_error_structure_assertions_guard_is_folder_backed",
    "runtime_15_runtime_15_row_data_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_scene_script_plugin_extension_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_scene_script_plugin_extension_guard_is_folder_backed",
    "runtime_15_scene_script_plugin_extension_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_scene_script_plugin_extension_row_data_is_child_backed",
    "runtime_15_scene_script_runtime_07_performance_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_scene_script_runtime_07_performance_guard_is_folder_backed",
    "runtime_15_scene_script_runtime_07_performance_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_scene_script_runtime_07_performance_row_data_is_child_backed",
    "runtime_15_status_output_expected_slice_maps_are_child_owners",
    "runtime_15_status_output_runtime_15_row_data_is_child_owner",
    "runtime_15_status_output_runtime_15_row_data_split_static_passed_cargo_deferred",
    "runtime_15_structure_guard_plugin_importer_child_split_static_passed_cargo_deferred",
    "runtime_15_structure_guard_plugin_importer_is_child_backed",
    "runtime_15_structure_guard_plugin_importer_status_mirrors_are_current",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_status_mirrors_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_child_inventory_split_layout_status_mirrors_guard_is_folder_backed",
    "runtime_15_typed_error_status_doc_paths_status_current_split_layout_status_mirrors_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_paths_status_current_split_layout_status_mirrors_guard_is_folder_backed",
    "runtime_15_typed_error_status_doc_status_maps_status_current_sources_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_status_maps_status_current_sources_guard_is_folder_backed",
    "runtime_15_typed_error_status_doc_status_maps_status_current_split_layout_sources_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_status_doc_status_maps_status_current_split_layout_sources_guard_is_folder_backed",
    "runtime_15_typed_error_structure_row_data_owner_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_structure_rows_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_structure_rows_guard_is_folder_backed",
    "runtime_15_typed_error_structure_rows_row_data_owner_is_child_backed",
    "Some(\"2026-06-24\")",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/aggregation.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/folder_backed.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/route_mounts.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/export_chain.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_child_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_inventory.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_owner_paths.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_paths.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/root_statuses.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/row_ownership.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/folder_backed.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/row_groups.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/status_doc_paths.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/folder_backed.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/row_routes.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_row_data/budgets.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_row_data/delegation.rs",
    "structure_convention/test_file_budget/status_slices/maps/runtime_15_topics.rs",
    "tests/runtime_absorption/plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/plugin_importer/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/plugin_importer/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/plugin_importer/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/plugin_importer/top_level_children.rs",
    "use lifecycle_fixtures::*;",
    "Runtime 15 M3 code review findings status-doc child-anchor route folder-backed split",
    "runtime_15_code_review_findings_status_docs_child_anchor_route_folder_backed_static_passed_cargo_deferred",
    "runtime_15_code_review_findings_status_docs_child_anchor_route_is_folder_backed",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/delegation/current/split/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/mirrors/current/split/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/current/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/inventory/split/sources/source/source_tree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/root_paths/path_children.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status/paths/status_slices/core.rs",
];
