pub(super) const ANCHORS: &[&str] = &[
    "#[path = \"code_review/direct_assertion_rows.rs\"]",
    "#[path = \"code_review/expected_slice_rows.rs\"]",
    "#[path = \"code_review/folder_backed_summary_rows.rs\"]",
    "#[path = \"code_review/source_inventory_rows.rs\"]",
    "#[path = \"code_review/status_doc_rows.rs\"]",
    "#[path = \"code_review/structure_guard_rows.rs\"]",
    "#[path = \"review/typed_error_maps.rs\"]",
    "#[path = \"route_meta/child_owner_budget_rows.rs\"]",
    "#[path = \"route_meta/child_owner_guard_rows.rs\"]",
    "#[path = \"route_meta/naming_boundary_rows.rs\"]",
    "#[path = \"route_meta/row_data_owner_rows.rs\"]",
    "#[path = \"runtime_plugin_lifecycle/lifecycle_fixtures.rs\"]",
    "#[path = \"status/delegation.rs\"]",
    "#[path = \"structure/convergence_mounts.rs\"]",
    "Cargo gate deferred",
    "frameworks_02_m3_foundation_expected_slice_maps_guard_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_foundation_expected_slice_maps_status_mirrors_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_review_guard_foundation_route_mount_guard_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_review_guard_foundation_status_date_map_guard_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_review_guard_foundation_status_date_maps_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_review_guard_foundation_status_mirror_guard_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_status_output_runtime_15_expected_slice_child_owner_guard_sources_folder_backed_static_passed_cargo_deferred",
    "mod lifecycle_fixtures;",
    "owners/split/sources/constants.rs",
    "owners/split/sources/row_sources.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/base_maps.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/status_support_maps.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support.rs",
    "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4.rs",
    "pub(super) const EXPECTED_STATUS_OUTPUT_SLICES",
    "render_product_camera_targets/custom_target/ordering.rs",
    "REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_F12_EXPECTED_STATUS_OUTPUT_SLICES",
    "REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_F8_EXPECTED_STATUS_OUTPUT_SLICES",
    "REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_P0_EXPECTED_STATUS_OUTPUT_SLICES",
    "REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_RENDER_EXPECTED_STATUS_OUTPUT_SLICES",
    "REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_ROOT_PARENT_EXPECTED_STATUS_OUTPUT_SLICES",
    "REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
    "review/structure_support_expected_slice.rs",
    "review/structure/status_mirrors.rs",
    "rt15_slices/foundation.rs",
    "rt15_slices/foundation/mirrors/row_data.rs",
    "rt15_slices/foundation/status_mirrors.rs",
    "Runtime 15 F9 runtime prelude required type coverage",
    "Runtime 15 M2 core runtime state module naming hard cutover",
    "Runtime 15 M3 asset-budget asset-tests guard folder-backed split",
    "Runtime 15 M3 asset-budget asset-tests row-data child split",
    "Runtime 15 M3 asset-budget naming graphics misc guard folder-backed split",
    "Runtime 15 M3 asset-budget naming graphics misc row-data child split",
    "Runtime 15 M3 child-group moved-row guard child-owner split",
    "Runtime 15 M3 child-group moved-row guard folder-backed split",
    "Runtime 15 M3 child-group moved-row root inventory child split",
    "Runtime 15 M3 child-group moved-row status-mirror child split",
    "Runtime 15 M3 child-groups status-doc guard child-owner split",
    "Runtime 15 M3 child-groups status-doc guard folder-backed split",
    "Runtime 15 M3 child-groups status-doc root inventory child split",
    "Runtime 15 M3 child-groups status-doc status-mirror child split",
    "Runtime 15 M3 foundation expected-slice maps folder-backed split",
    "Runtime 15 M3 foundation expected-slice maps guard folder-backed split",
    "Runtime 15 M3 foundation expected-slice maps status mirrors folder-backed split",
    "Runtime 15 M3 foundation-guards runtime-structure guard folder-backed split",
    "Runtime 15 M3 foundation-guards runtime-structure row-data child split",
    "Runtime 15 M3 production guard status-support priority guard folder-backed split",
    "Runtime 15 M3 production guard status-support priority row-data child split",
    "Runtime 15 M3 review-guard direct-assertion row-data child-owner split",
    "Runtime 15 M3 review-guard direct-assertion row-data folder-backed split",
    "Runtime 15 M3 review-guard direct-assertion row-data guard folder-backed split",
    "Runtime 15 M3 review-guard direct-assertion row-data root inventory child split",
    "Runtime 15 M3 review-guard direct-assertion row-ownership guard child split",
    "Runtime 15 M3 review-guard direct-assertion status-mirror child split",
    "Runtime 15 M3 Runtime 15 M3 row-data guard folder-backed split",
    "Runtime 15 M3 Runtime 15 M3 row-data root inventory child split",
    "Runtime 15 M3 Runtime 15 M3 row-data status-mirror child split",
    "Runtime 15 M3 Runtime 15 M4 row-data guard folder-backed split",
    "Runtime 15 M3 Runtime 15 M4 row-data root inventory child split",
    "Runtime 15 M3 Runtime 15 M4 row-data status-mirror child split",
    "Runtime 15 M3 scene-script plugin-extension guard folder-backed split",
    "Runtime 15 M3 scene-script plugin-extension row-data child split",
    "Runtime 15 M3 scene-script Runtime 07 performance guard folder-backed split",
    "Runtime 15 M3 scene-script Runtime 07 performance row-data child split",
    "Runtime 15 M3 shader prewarm manifest guard child-owner split",
    "Runtime 15 M3 status output expected-slice legacy group child-owner split",
    "Runtime 15 M3 status output expected-slice maps split",
    "Runtime 15 M3 status output expected-slice top-level map support child-owner split",
    "Runtime 15 M3 status output M3 row data child-owner split",
    "Runtime 15 M3 status output Runtime 15 expected-slice child-owner guard sources folder-backed split",
    "Runtime 15 M3 status output Runtime 15 M3 row data split",
    "Runtime 15 M3 status output Runtime 15 M4 row data split",
    "Runtime 15 M3 status output Runtime 15 row data split",
    "Runtime 15 M3 status-support expected-slice owner paths folder-backed split",
    "Runtime 15 M3 status-support expected-slice owner paths guard folder-backed split",
    "Runtime 15 M3 status-support expected-slice row-data owner folder-backed split",
    "Runtime 15 M3 status-support row-data guard folder-backed split",
    "Runtime 15 M3 status-support row-data root inventory child split",
    "Runtime 15 M3 status-support row-data root owner paths folder-backed split",
    "Runtime 15 M3 status-support row-data status-mirror child split",
    "Runtime 15 M3 status-support runtime-index anchor row-data child split",
    "Runtime 15 M3 top-level expected-slice assertion helper child split",
    "Runtime 15 M3 top-level expected-slice support-layout guard body child split",
    "Runtime 15 M3 top-level expected-slice support-layout guard folder-backed split",
    "Runtime 15 M3 typed-error structure row-data guard folder-backed split",
    "Runtime 15 M3 typed-error structure row-data owner child split",
    "runtime_15_asset_budget_asset_tests_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_asset_budget_asset_tests_guard_is_folder_backed",
    "runtime_15_asset_budget_asset_tests_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_asset_budget_asset_tests_row_data_is_child_backed",
    "runtime_15_asset_budget_naming_graphics_misc_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_asset_budget_naming_graphics_misc_guard_is_folder_backed",
    "runtime_15_asset_budget_naming_graphics_misc_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_asset_budget_naming_graphics_misc_row_data_is_child_backed",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_foundation_expected_slice_maps_are_folder_backed",
    "runtime_15_foundation_expected_slice_maps_folder_backed_static_passed_cargo_deferred",
    "runtime_15_foundation_expected_slice_maps_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_foundation_expected_slice_maps_guard_is_folder_backed",
    "runtime_15_foundation_expected_slice_maps_status_mirrors_are_folder_backed",
    "runtime_15_foundation_expected_slice_maps_status_mirrors_folder_backed_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_guard_is_folder_backed",
    "runtime_15_foundation_guards_runtime_structure_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_foundation_guards_runtime_structure_row_data_is_child_backed",
    "runtime_15_m3_child_group_moved_row_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_m3_child_group_moved_row_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_m3_child_group_moved_row_root_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_m3_child_group_moved_row_status_mirror_child_split_static_passed_cargo_deferred",
    "runtime_15_m3_child_group_moved_row_status_mirror_children_are_child_owned",
    "runtime_15_m3_child_group_moved_rows_root_inventory_is_child_owned",
    "runtime_15_m3_child_group_status_doc_status_mirror_children_are_child_owned",
    "runtime_15_m3_child_group_status_docs_root_inventory_is_child_owned",
    "runtime_15_m3_child_groups_status_docs_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_m3_child_groups_status_docs_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_m3_child_groups_status_docs_guard_is_folder_backed",
    "runtime_15_m3_child_groups_status_docs_root_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_m3_child_groups_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
    "runtime_15_m3_row_data_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_m3_row_data_root_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_m3_row_data_status_mirror_child_split_static_passed_cargo_deferred",
    "runtime_15_m3_row_data_status_mirror_children_are_child_owned",
    "runtime_15_m4_row_data_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_m4_row_data_root_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_m4_row_data_status_mirror_child_split_static_passed_cargo_deferred",
    "runtime_15_m4_row_data_status_mirror_children_are_child_owned",
    "runtime_15_plugin_importer_d13_sdk_review_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_production_guard_status_support_priority_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_production_guard_status_support_priority_guard_is_folder_backed",
    "runtime_15_production_guard_status_support_priority_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_production_guard_status_support_priority_row_data_is_child_backed",
    "runtime_15_review_guard_direct_assertion_row_data_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_direct_assertion_row_data_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_direct_assertion_row_data_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_review_guard_direct_assertion_row_data_root_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_direct_assertion_row_data_root_inventory_is_child_owned",
    "runtime_15_review_guard_direct_assertion_row_ownership_guard_child_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_direct_assertion_rows_guard_is_folder_backed",
    "runtime_15_review_guard_direct_assertion_status_mirror_child_split_static_passed_cargo_deferred",
    "runtime_15_review_guard_direct_assertion_status_mirror_children_are_child_owned",
    "runtime_15_scene_script_plugin_extension_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_scene_script_plugin_extension_guard_is_folder_backed",
    "runtime_15_scene_script_plugin_extension_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_scene_script_plugin_extension_row_data_is_child_backed",
    "runtime_15_scene_script_runtime_07_performance_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_scene_script_runtime_07_performance_guard_is_folder_backed",
    "runtime_15_scene_script_runtime_07_performance_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_scene_script_runtime_07_performance_row_data_is_child_backed",
    "runtime_15_shader_prewarm_manifest_guard_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_status_output_expected_slice_legacy_group_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_status_output_expected_slice_maps_split_static_passed_cargo_deferred",
    "runtime_15_status_output_expected_slice_top_level_map_support_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_status_output_m3_child_group_status_docs_are_child_owner",
    "runtime_15_status_output_m3_row_data_child_owner_split_static_passed_cargo_deferred",
    "runtime_15_status_output_review_guard_direct_assertion_rows_are_child_owner",
    "runtime_15_status_output_runtime_15_expected_slice_child_owner_guard_sources_are_folder_backed",
    "runtime_15_status_output_runtime_15_expected_slice_child_owner_guard_sources_folder_backed_static_passed_cargo_deferred",
    "runtime_15_status_output_runtime_15_m3_row_data_is_child_owner",
    "runtime_15_status_output_runtime_15_m3_row_data_split_static_passed_cargo_deferred",
    "runtime_15_status_output_runtime_15_m4_row_data_is_child_owner",
    "runtime_15_status_output_runtime_15_m4_row_data_split_static_passed_cargo_deferred",
    "runtime_15_status_support_expected_slice_owner_paths_are_folder_backed",
    "runtime_15_status_support_expected_slice_owner_paths_folder_backed_static_passed_cargo_deferred",
    "runtime_15_status_support_expected_slice_owner_paths_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_status_support_expected_slice_owner_paths_guard_is_folder_backed",
    "runtime_15_status_support_expected_slice_row_data_owner_folder_backed_static_passed_cargo_deferred",
    "runtime_15_status_support_expected_slice_row_data_owner_is_folder_backed",
    "runtime_15_status_support_row_data_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_status_support_row_data_guard_is_folder_backed",
    "runtime_15_status_support_row_data_owner_is_child_backed",
    "runtime_15_status_support_row_data_root_inventory_child_split_static_passed_cargo_deferred",
    "runtime_15_status_support_row_data_root_inventory_is_child_owned",
    "runtime_15_status_support_row_data_root_owner_paths_are_folder_backed",
    "runtime_15_status_support_row_data_root_owner_paths_folder_backed_static_passed_cargo_deferred",
    "runtime_15_status_support_row_data_status_mirror_child_split_static_passed_cargo_deferred",
    "runtime_15_status_support_row_data_status_mirror_children_are_child_owned",
    "runtime_15_status_support_runtime_index_anchor_row_data_child_split_static_passed_cargo_deferred",
    "runtime_15_status_support_runtime_index_anchor_rows_are_child_owned",
    "runtime_15_top_level_expected_slice_assertion_helper_child_split_static_passed_cargo_deferred",
    "runtime_15_top_level_expected_slice_support_layout_guard_body_child_split_static_passed_cargo_deferred",
    "runtime_15_top_level_expected_slice_support_layout_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_top_level_expected_slice_support_layout_guard_is_folder_backed",
    "runtime_15_typed_error_structure_row_data_owner_child_split_static_passed_cargo_deferred",
    "runtime_15_typed_error_structure_rows_guard_folder_backed_static_passed_cargo_deferred",
    "runtime_15_typed_error_structure_rows_guard_is_folder_backed",
    "runtime_15_typed_error_structure_rows_row_data_owner_is_child_backed",
    "runtime_15/foundation.rs",
    "runtime_15/foundation/lock_poison.rs",
    "Some(\"2026-06-24\")",
    "structure_convention/test_file_budget/row_data/evidence_anchors/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/evidence_anchors/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/evidence_anchors/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/budgets.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/delegation.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_child_rows.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_inventory.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_paths.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_source_blobs.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_statuses.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/source_ownership.rs",
    "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/budgets.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/delegation.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/root_child_rows.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/root_inventory.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/root_paths.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/root_source_blobs.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/root_statuses.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/source_ownership.rs",
    "structure_convention/test_file_budget/row_data/module_layout_status/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/module_layout/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/module_layout/mirrors/layout_folder_status.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/budgets.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/delegation.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/exports.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/exports/runtime_15_m3_parent.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/exports/runtime_15_parent.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/exports/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/exports/top_level.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_child_rows.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_inventory.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_owner_paths.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_statuses.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/row_ownership.rs",
    "structure_convention/test_file_budget/row_data/rt15_m3_groups/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/budgets.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/delegation.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/export_chain.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps_folder_backed.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps/base_and_top_level.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps/review_guard_structure.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps/route_metadata.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps/status_support_maps.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps/structure_support.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/expected_slice_maps/warning_cleanup.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/priority_plan_docs.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/root_rows.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/row_data_and_budget.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/runtime_index_anchors.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/slice_maps_folder/budget_traversal.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/slice_maps_folder/route_children.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/owner_paths/slice_maps_folder/status_current.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/root_child_rows.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/root_inventory.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/root_owner_paths.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/root_paths.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/root_statuses.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/row_ownership.rs",
    "structure_convention/test_file_budget/row_data/rt15_status_support/status_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_guards_row_data/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/delegation.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/doc_mirrors.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/root_child_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/root_inventory.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/root_paths.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/root_source_blobs.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/root_statuses.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/row_count.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/row_count/current_counts.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/row_count/priority_frontmatter.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data_status/status_maps.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_foundation_row_data/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_lock_poison_status_row_data_children/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data/mirrors/historical_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/mirrors/child_split_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/mirrors/folder_backed_status.rs",
    "structure_convention/test_file_budget/row_data/runtime_15_m3_child_group_moved_rows/mirrors/historical_status.rs",
    // current owner anchors appended below
];
