version = 1

[root]
template = "FloatingWindowSource"

[components.FloatingWindowSource]
root = { component = "FloatingWindowSource", control_id = "FloatingWindowSourceRoot", attributes = { layout = { container = { kind = "VerticalBox", gap = 0.0 }, width = { stretch = "Stretch" }, height = { stretch = "Stretch" } } }, children = [
    { component = "Container", control_id = "FloatingWindowTopBarRoot", attributes = { layout = { width = { stretch = "Stretch" }, height = { min = 40.0, preferred = 40.0, max = 40.0, stretch = "Fixed" } } } },
    { component = "HorizontalBox", control_id = "FloatingWindowCenterBandRoot", attributes = { layout = { container = { kind = "HorizontalBox", gap = 0.0 }, width = { stretch = "Stretch" }, height = { stretch = "Stretch" } } }, children = [
        { component = "Container", control_id = "FloatingWindowRailRoot", attributes = { layout = { width = { min = 56.0, preferred = 56.0, max = 56.0, stretch = "Fixed" }, height = { stretch = "Stretch" } } } },
        { component = "Container", control_id = "FloatingWindowDocumentRoot", attributes = { layout = { width = { stretch = "Stretch" }, height = { stretch = "Stretch" } } } }
    ] },
    { component = "Container", control_id = "FloatingWindowStatusBarRoot", attributes = { layout = { width = { stretch = "Stretch" }, height = { min = 24.0, preferred = 24.0, max = 24.0, stretch = "Fixed" } } } }
] }
