use super::*;
mod assertions;

#[test]
fn host_scene_projection_converts_host_owned_panes_to_host_contract_panes() {
    let mut scene = host_window::HostWindowSceneData {
        layout: host_window::HostWindowLayoutData {
            center_band_frame: host_frame_rect(0.0, 0.0, 1200.0, 700.0),
            status_bar_frame: host_frame_rect(0.0, 700.0, 1200.0, 24.0),
            left_region_frame: host_frame_rect(0.0, 0.0, 240.0, 700.0),
            document_region_frame: host_frame_rect(240.0, 0.0, 720.0, 700.0),
            right_region_frame: host_frame_rect(960.0, 0.0, 240.0, 700.0),
            bottom_region_frame: host_frame_rect(240.0, 500.0, 720.0, 200.0),
            left_splitter_frame: host_frame_rect(240.0, 0.0, 4.0, 700.0),
            right_splitter_frame: host_frame_rect(956.0, 0.0, 4.0, 700.0),
            bottom_splitter_frame: host_frame_rect(240.0, 496.0, 720.0, 4.0),
            viewport_content_frame: host_frame_rect(240.0, 64.0, 720.0, 432.0),
        },
        metrics: host_window::HostWindowSurfaceMetricsData {
            outer_margin_px: 8.0,
            rail_width_px: 40.0,
            top_bar_height_px: 40.0,
            host_bar_height_px: 32.0,
            panel_header_height_px: 28.0,
            document_header_height_px: 32.0,
        },
        orchestration: host_window::HostWindowSurfaceOrchestrationData {
            left_rail_width_px: 40.0,
            right_rail_width_px: 40.0,
            left_stack_width_px: 240.0,
            right_stack_width_px: 240.0,
            left_panel_width_px: 200.0,
            right_panel_width_px: 200.0,
            bottom_panel_height_px: 200.0,
            main_content_y_px: 40.0,
            document_zone_x_px: 240.0,
            right_stack_x_px: 960.0,
            bottom_panel_y_px: 500.0,
        },
        menu_chrome: host_window::HostMenuChromeData {
            outer_margin_px: 8.0,
            top_bar_height_px: 40.0,
            template_nodes: Default::default(),
            menu_frames: host_chrome_menu_frames(1),
            save_project_enabled: true,
            undo_enabled: true,
            redo_enabled: true,
            delete_enabled: true,
            preset_names: model_rc(vec!["Default".into()]),
            active_preset_name: "Default".into(),
            resolved_preset_name: "Default".into(),
            menus: Default::default(),
        },
        page_chrome: host_window::HostPageChromeData {
            top_bar_height_px: 40.0,
            host_bar_height_px: 32.0,
            template_nodes: Default::default(),
            tab_row_frame: host_frame_rect(0.0, 40.0, 1200.0, 32.0),
            project_path_frame: host_frame_rect(900.0, 48.0, 280.0, 14.0),
            tab_frames: host_chrome_tab_frames(&["document-tab"]),
            tabs: host_tabs(&["document-tab"]),
            project_path: "res://project".into(),
        },
        status_bar: host_window::HostStatusBarData {
            status_bar_frame: host_frame_rect(0.0, 700.0, 1200.0, 24.0),
            template_nodes: Default::default(),
            status_primary: "Ready".into(),
            status_secondary: "Idle".into(),
            viewport_label: "Viewport".into(),
        },
        resize_layer: host_window::HostResizeLayerData {
            left_splitter_frame: host_frame_rect(240.0, 0.0, 4.0, 700.0),
            right_splitter_frame: host_frame_rect(956.0, 0.0, 4.0, 700.0),
            bottom_splitter_frame: host_frame_rect(240.0, 496.0, 720.0, 4.0),
        },
        drag_overlay: host_window::HostTabDragOverlayData {
            left_drop_enabled: true,
            right_drop_enabled: true,
            bottom_drop_enabled: true,
            left_drop_width_px: 120.0,
            right_drop_width_px: 120.0,
            bottom_drop_height_px: 120.0,
            main_content_y_px: 40.0,
            main_content_height_px: 660.0,
            document_zone_x_px: 240.0,
            document_zone_width_px: 720.0,
            bottom_drop_top_px: 500.0,
            drag_overlay_bottom_px: 700.0,
        },
        left_dock: host_window::HostSideDockSurfaceData {
            region_frame: host_frame_rect(0.0, 0.0, 240.0, 700.0),
            surface_key: "left-surface".into(),
            rail_before_panel: true,
            rail_nodes: Default::default(),
            rail_button_frames: Default::default(),
            rail_active_control_id: "".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 200.0, 31.0),
            content_frame: host_frame_rect(0.0, 32.0, 200.0, 668.0),
            tab_frames: host_chrome_tab_frames(&["left-tab"]),
            tabs: host_tabs(&["left-tab"]),
            pane: host_pane("left-pane", "Left"),
            rail_width_px: 40.0,
            panel_width_px: 200.0,
            panel_header_height_px: 28.0,
        },
        document_dock: host_window::HostDocumentDockSurfaceData {
            region_frame: host_frame_rect(240.0, 0.0, 720.0, 700.0),
            surface_key: "document-surface".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 720.0, 32.0),
            subtitle_frame: host_frame_rect(576.0, 9.0, 132.0, 14.0),
            content_frame: host_frame_rect(0.0, 33.0, 720.0, 667.0),
            tab_frames: host_chrome_tab_frames(&["document-tab"]),
            tabs: host_tabs(&["document-tab"]),
            pane: host_pane("document-pane", "Document"),
            header_height_px: 32.0,
        },
        right_dock: host_window::HostSideDockSurfaceData {
            region_frame: host_frame_rect(960.0, 0.0, 240.0, 700.0),
            surface_key: "right-surface".into(),
            rail_before_panel: false,
            rail_nodes: Default::default(),
            rail_button_frames: Default::default(),
            rail_active_control_id: "".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 200.0, 31.0),
            content_frame: host_frame_rect(0.0, 32.0, 200.0, 668.0),
            tab_frames: host_chrome_tab_frames(&["right-tab"]),
            tabs: host_tabs(&["right-tab"]),
            pane: host_pane("right-pane", "Right"),
            rail_width_px: 40.0,
            panel_width_px: 200.0,
            panel_header_height_px: 28.0,
        },
        bottom_dock: host_window::HostBottomDockSurfaceData {
            region_frame: host_frame_rect(240.0, 500.0, 720.0, 200.0),
            surface_key: "bottom-surface".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 720.0, 31.0),
            content_frame: host_frame_rect(0.0, 32.0, 720.0, 168.0),
            tab_frames: host_chrome_tab_frames(&["bottom-tab"]),
            tabs: host_tabs(&["bottom-tab"]),
            pane: host_pane("bottom-pane", "Bottom"),
            expanded: true,
            header_height_px: 28.0,
        },
        floating_layer: host_window::HostFloatingWindowLayerData {
            floating_windows: model_rc(vec![host_window::FloatingWindowData {
                window_id: "floating-window".into(),
                title: "Floating".into(),
                frame: host_frame_rect(320.0, 160.0, 360.0, 240.0),
                header_nodes: Default::default(),
                header_frame: host_frame_rect(0.0, 0.0, 360.0, 31.0),
                tab_frames: host_chrome_tab_frames(&["floating-tab"]),
                target_group: "floating/window".into(),
                left_edge_target_group: "floating/window/left".into(),
                right_edge_target_group: "floating/window/right".into(),
                top_edge_target_group: "floating/window/top".into(),
                bottom_edge_target_group: "floating/window/bottom".into(),
                focus_target_id: "floating-focus".into(),
                tabs: host_tabs(&["floating-tab"]),
                active_pane: host_pane("floating-pane", "Floating"),
            }]),
            header_height_px: 24.0,
        },
    };
    let ui_asset_nodes = vec![
        mount_node(
            "ui_asset/header_panel",
            "HeaderPanel",
            11.0,
            12.0,
            640.0,
            56.0,
        ),
        mount_node(
            "ui_asset/header_asset_row",
            "HeaderAssetRow",
            21.0,
            18.0,
            620.0,
            10.0,
        ),
        mount_node(
            "ui_asset/header_status_row",
            "HeaderStatusRow",
            21.0,
            28.0,
            620.0,
            10.0,
        ),
        mount_node(
            "ui_asset/header_action_row",
            "HeaderActionRow",
            21.0,
            40.0,
            620.0,
            20.0,
        ),
        mount_node(
            "ui_asset/left_column",
            "LeftColumn",
            16.0,
            80.0,
            220.0,
            240.0,
        ),
        mount_node(
            "ui_asset/palette_panel",
            "PalettePanel",
            16.0,
            80.0,
            220.0,
            240.0,
        ),
        mount_node(
            "ui_asset/center_column",
            "CenterColumn",
            260.0,
            80.0,
            420.0,
            928.0,
        ),
        mount_node(
            "ui_asset/designer_panel",
            "DesignerPanel",
            260.0,
            80.0,
            420.0,
            300.0,
        ),
        mount_node(
            "ui_asset/designer_canvas_panel",
            "DesignerCanvasPanel",
            270.0,
            108.0,
            400.0,
            214.0,
        ),
        mount_node(
            "ui_asset/render_stack_panel",
            "RenderStackPanel",
            270.0,
            328.0,
            400.0,
            80.0,
        ),
        mount_node(
            "ui_asset/action_bar_panel",
            "ActionBarPanel",
            270.0,
            414.0,
            400.0,
            88.0,
        ),
        mount_node(
            "ui_asset/action_insert_row",
            "ActionInsertRow",
            280.0,
            422.0,
            380.0,
            24.0,
        ),
        mount_node(
            "ui_asset/action_reparent_row",
            "ActionReparentRow",
            280.0,
            450.0,
            380.0,
            24.0,
        ),
        mount_node(
            "ui_asset/action_structure_row",
            "ActionStructureRow",
            280.0,
            478.0,
            380.0,
            24.0,
        ),
        mount_node(
            "ui_asset/source_info_panel",
            "SourceInfoPanel",
            270.0,
            392.0,
            400.0,
            58.0,
        ),
        mount_node(
            "ui_asset/mock_workspace_panel",
            "MockWorkspacePanel",
            270.0,
            528.0,
            400.0,
            326.0,
        ),
        mount_node(
            "ui_asset/mock_subjects_panel",
            "MockSubjectsPanel",
            270.0,
            528.0,
            400.0,
            72.0,
        ),
        mount_node(
            "ui_asset/mock_editor_panel",
            "MockEditorPanel",
            270.0,
            606.0,
            400.0,
            170.0,
        ),
        mount_node(
            "ui_asset/mock_state_graph_panel",
            "MockStateGraphPanel",
            270.0,
            782.0,
            400.0,
            72.0,
        ),
        mount_node(
            "ui_asset/source_text_panel",
            "SourceTextPanel",
            270.0,
            860.0,
            400.0,
            148.0,
        ),
        mount_node(
            "ui_asset/inspector_panel",
            "InspectorPanel",
            700.0,
            80.0,
            260.0,
            240.0,
        ),
        mount_node(
            "ui_asset/inspector_content_panel",
            "InspectorContentPanel",
            710.0,
            106.0,
            240.0,
            204.0,
        ),
        mount_node(
            "ui_asset/stylesheet_panel",
            "StylesheetPanel",
            700.0,
            330.0,
            260.0,
            170.0,
        ),
        mount_node(
            "ui_asset/stylesheet_action_row",
            "StylesheetActionRow",
            710.0,
            356.0,
            240.0,
            24.0,
        ),
        mount_node(
            "ui_asset/stylesheet_state_primary_row",
            "StylesheetStatePrimaryRow",
            710.0,
            384.0,
            240.0,
            24.0,
        ),
        mount_node(
            "ui_asset/stylesheet_state_secondary_row",
            "StylesheetStateSecondaryRow",
            710.0,
            412.0,
            240.0,
            24.0,
        ),
        mount_node(
            "ui_asset/stylesheet_content_panel",
            "StylesheetContentPanel",
            710.0,
            441.0,
            240.0,
            49.0,
        ),
    ];
    let ui_asset_node = |control_id: &str| {
        ui_asset_nodes
            .iter()
            .find(|node| node.control_id.as_str() == control_id)
            .cloned()
            .unwrap_or_else(|| panic!("missing ui asset test node `{control_id}`"))
    };
    scene.left_dock.pane.native_body.ui_asset = UiAssetEditorPanePresentation {
        asset_id: "asset://ui/test.ui.toml".to_string(),
        mode: "split".to_string(),
        last_error: "clean".to_string(),
        selection_summary: "Root".to_string(),
        palette_items: vec!["Button".to_string()],
        palette_selected_index: 0,
        nodes: ui_asset_nodes.clone(),
        center_column_node: ui_asset_node("CenterColumn"),
        designer_panel_node: ui_asset_node("DesignerPanel"),
        designer_canvas_panel_node: ui_asset_node("DesignerCanvasPanel"),
        inspector_panel_node: ui_asset_node("InspectorPanel"),
        stylesheet_panel_node: ui_asset_node("StylesheetPanel"),
        ..UiAssetEditorPanePresentation::default()
    };
    scene.right_dock.pane.native_body.animation = host_window::AnimationEditorPaneViewData {
        nodes: model_rc(vec![
            mount_node(
                "root/header_panel",
                "AnimationEditorHeaderPanel",
                14.0,
                18.0,
                520.0,
                64.0,
            ),
            mount_node(
                "root/header_mode_row",
                "AnimationEditorHeaderModeRow",
                26.0,
                28.0,
                496.0,
                12.0,
            ),
            mount_node(
                "root/header_path_row",
                "AnimationEditorHeaderPathRow",
                26.0,
                44.0,
                496.0,
                14.0,
            ),
            mount_node(
                "root/header_status_row",
                "AnimationEditorHeaderStatusRow",
                26.0,
                62.0,
                496.0,
                12.0,
            ),
            mount_node(
                "root/body_panel",
                "AnimationEditorBodyPanel",
                14.0,
                82.0,
                520.0,
                318.0,
            ),
            mount_node(
                "root/sequence_content_panel",
                "AnimationSequenceContentPanel",
                26.0,
                94.0,
                496.0,
                294.0,
            ),
            mount_node(
                "root/sequence_timeline_row",
                "AnimationSequenceTimelineRow",
                26.0,
                94.0,
                496.0,
                12.0,
            ),
            mount_node(
                "root/sequence_selection_row",
                "AnimationSequenceSelectionRow",
                26.0,
                112.0,
                496.0,
                12.0,
            ),
            mount_node(
                "root/sequence_tracks_panel",
                "AnimationSequenceTracksPanel",
                26.0,
                138.0,
                496.0,
                250.0,
            ),
            mount_node(
                "root/graph_content_panel",
                "AnimationGraphContentPanel",
                26.0,
                94.0,
                496.0,
                294.0,
            ),
            mount_node(
                "root/graph_parameters_panel",
                "AnimationGraphParametersPanel",
                26.0,
                94.0,
                496.0,
                120.0,
            ),
            mount_node(
                "root/graph_nodes_panel",
                "AnimationGraphNodesPanel",
                26.0,
                234.0,
                496.0,
                154.0,
            ),
            mount_node(
                "root/state_machine_content_panel",
                "AnimationStateMachineContentPanel",
                26.0,
                94.0,
                496.0,
                294.0,
            ),
            mount_node(
                "root/state_machine_entry_row",
                "AnimationStateMachineEntryRow",
                26.0,
                94.0,
                496.0,
                12.0,
            ),
            mount_node(
                "root/state_machine_states_panel",
                "AnimationStateMachineStatesPanel",
                26.0,
                118.0,
                496.0,
                112.0,
            ),
            mount_node(
                "root/state_machine_transitions_panel",
                "AnimationStateMachineTransitionsPanel",
                26.0,
                242.0,
                496.0,
                146.0,
            ),
        ]),
        mode: "sequence".into(),
        asset_path: "asset://animation/walk.anim".into(),
        status: "Looping".into(),
        selection: "Track: Root/Hips".into(),
        current_frame: 24,
        timeline_start_frame: 0,
        timeline_end_frame: 48,
        playback_label: "Playing".into(),
        track_items: model_rc(vec!["Root Translation".into(), "Left Hand".into()]),
        parameter_items: model_rc(vec!["Speed".into()]),
        node_items: model_rc(vec!["Blend".into()]),
        state_items: model_rc(vec!["Idle".into()]),
        transition_items: model_rc(vec!["Idle -> Walk".into()]),
    };
    scene.document_dock.pane.kind = "Project".into();
    scene.document_dock.pane.native_body.project_overview =
        host_window::ProjectOverviewPaneViewData {
            nodes: model_rc(vec![
                crate::ui::layouts::views::ViewTemplateNodeData {
                    node_id: "root/outer_panel".into(),
                    control_id: "ProjectOverviewOuterPanel".into(),
                    role: "Panel".into(),
                    text: "".into(),
                    dispatch_kind: "".into(),
                    action_id: "".into(),
                    surface_variant: "panel".into(),
                    text_tone: "".into(),
                    button_variant: "".into(),
                    font_size: 0.0,
                    font_weight: 0,
                    text_align: "left".into(),
                    overflow: "".into(),
                    corner_radius: 8.0,
                    border_width: 1.0,
                    frame: crate::ui::layouts::views::ViewTemplateFrameData {
                        x: 16.0,
                        y: 14.0,
                        width: 688.0,
                        height: 654.0,
                    },
                    ..Default::default()
                },
                crate::ui::layouts::views::ViewTemplateNodeData {
                    node_id: "root/header_path".into(),
                    control_id: "ProjectOverviewPathText".into(),
                    role: "Label".into(),
                    text: "res://project".into(),
                    dispatch_kind: "".into(),
                    action_id: "".into(),
                    surface_variant: "".into(),
                    text_tone: "muted".into(),
                    button_variant: "".into(),
                    font_size: 10.0,
                    font_weight: 400,
                    text_align: "left".into(),
                    overflow: "elide".into(),
                    corner_radius: 0.0,
                    border_width: 0.0,
                    frame: crate::ui::layouts::views::ViewTemplateFrameData {
                        x: 32.0,
                        y: 52.0,
                        width: 656.0,
                        height: 16.0,
                    },
                    ..Default::default()
                },
                crate::ui::layouts::views::ViewTemplateNodeData {
                    node_id: "root/catalog_panel".into(),
                    control_id: "ProjectOverviewCatalogPanel".into(),
                    role: "Panel".into(),
                    text: "".into(),
                    dispatch_kind: "".into(),
                    action_id: "".into(),
                    surface_variant: "inset".into(),
                    text_tone: "".into(),
                    button_variant: "".into(),
                    font_size: 0.0,
                    font_weight: 0,
                    text_align: "left".into(),
                    overflow: "".into(),
                    corner_radius: 6.0,
                    border_width: 1.0,
                    frame: crate::ui::layouts::views::ViewTemplateFrameData {
                        x: 32.0,
                        y: 206.0,
                        width: 656.0,
                        height: 68.0,
                    },
                    ..Default::default()
                },
            ]),
        };
    scene.bottom_dock.pane.kind = "Assets".into();
    scene.bottom_dock.pane.native_body.assets_activity = host_window::AssetsActivityPaneViewData {
        nodes: model_rc(vec![
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/toolbar_panel".into(),
                control_id: "AssetsActivityToolbarPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 18.0,
                    y: 16.0,
                    width: 680.0,
                    height: 122.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/tree_panel".into(),
                control_id: "AssetsActivityTreePanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 18.0,
                    y: 148.0,
                    width: 248.0,
                    height: 284.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/utility_tabs_row".into(),
                control_id: "AssetsActivityUtilityTabsRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 30.0,
                    y: 454.0,
                    width: 656.0,
                    height: 32.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/reference_right_panel".into(),
                control_id: "AssetsActivityReferenceRightPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 364.0,
                    y: 496.0,
                    width: 322.0,
                    height: 110.0,
                },
                ..Default::default()
            },
        ]),
    };
    scene.left_dock.pane.native_body.hierarchy = host_window::HierarchyPaneViewData {
        nodes: model_rc(vec![crate::ui::layouts::views::ViewTemplateNodeData {
            node_id: "root/list_panel".into(),
            control_id: "HierarchyListPanel".into(),
            role: "Mount".into(),
            text: "".into(),
            dispatch_kind: "".into(),
            action_id: "".into(),
            surface_variant: "".into(),
            text_tone: "".into(),
            button_variant: "".into(),
            font_size: 0.0,
            font_weight: 0,
            text_align: "left".into(),
            overflow: "".into(),
            corner_radius: 0.0,
            border_width: 0.0,
            frame: crate::ui::layouts::views::ViewTemplateFrameData {
                x: 8.0,
                y: 8.0,
                width: 184.0,
                height: 260.0,
            },
            ..Default::default()
        }]),
        hierarchy_nodes: model_rc(vec![
            host_window::SceneNodeData {
                id: "entity://root".into(),
                name: "Root".into(),
                depth: 0,
                selected: true,
            },
            host_window::SceneNodeData {
                id: "entity://child".into(),
                name: "Child".into(),
                depth: 1,
                selected: false,
            },
        ]),
    };
    scene.right_dock.pane.native_body.inspector = host_window::InspectorPaneViewData {
        nodes: model_rc(vec![
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/content_panel".into(),
                control_id: "InspectorContentPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 10.0,
                    width: 220.0,
                    height: 180.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/header_panel".into(),
                control_id: "InspectorHeaderPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 10.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/name_row".into(),
                control_id: "InspectorNameRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 36.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/parent_row".into(),
                control_id: "InspectorParentRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 62.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/position_row".into(),
                control_id: "InspectorPositionRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 88.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/separator_row".into(),
                control_id: "InspectorSeparatorRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 114.0,
                    width: 220.0,
                    height: 1.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/actions_row".into(),
                control_id: "InspectorActionsRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 119.0,
                    width: 220.0,
                    height: 24.0,
                },
                ..Default::default()
            },
        ]),
        info: "Node 42".into(),
        inspector_name: "CameraRig".into(),
        inspector_parent: "entity://root".into(),
        inspector_x: "1.0".into(),
        inspector_y: "2.0".into(),
        inspector_z: "3.0".into(),
        delete_enabled: true,
        plugin_components: Vec::new(),
    };
    scene.bottom_dock.pane.native_body.console = host_window::ConsolePaneViewData {
        nodes: model_rc(vec![crate::ui::layouts::views::ViewTemplateNodeData {
            node_id: "root/text_panel".into(),
            control_id: "ConsoleTextPanel".into(),
            role: "Mount".into(),
            text: "".into(),
            dispatch_kind: "".into(),
            action_id: "".into(),
            surface_variant: "".into(),
            text_tone: "".into(),
            button_variant: "".into(),
            font_size: 0.0,
            font_weight: 0,
            text_align: "left".into(),
            overflow: "".into(),
            corner_radius: 0.0,
            border_width: 0.0,
            frame: crate::ui::layouts::views::ViewTemplateFrameData {
                x: 10.0,
                y: 8.0,
                width: 640.0,
                height: 152.0,
            },
            ..Default::default()
        }]),
        status_text: "Build finished".into(),
    };

    let projected = to_host_contract_host_scene_data(&scene);
    assertions::assert_host_contract_scene(&projected);
}
