use super::super::types::{ExtensionBindingSpec, change, click, submit};

pub(in super::super) const DIAGNOSTICS_OBSERVABILITY_BINDINGS: &[ExtensionBindingSpec] = &[
    click(
        "ConsoleDiagnosticsOpen",
        "workbench.extension.console_diagnostics.open",
    ),
    click(
        "ConsoleDiagnosticsLiveLogTab",
        "workbench.extension.console_diagnostics.live_log_tab.select",
    ),
    click(
        "ConsoleDiagnosticsCountersTab",
        "workbench.extension.console_diagnostics.counters_tab.select",
    ),
    click(
        "ConsoleDiagnosticsReportTab",
        "workbench.extension.console_diagnostics.report_tab.select",
    ),
    click(
        "ConsoleDiagnosticsSessionRow",
        "workbench.extension.console_diagnostics.session_row.select",
    ),
    click(
        "ConsoleDiagnosticsRendererRow",
        "workbench.extension.console_diagnostics.renderer_row.select",
    ),
    click(
        "ConsoleDiagnosticsAssetRow",
        "workbench.extension.console_diagnostics.asset_row.select",
    ),
    click(
        "ConsoleDiagnosticsWarningTableRow",
        "workbench.extension.console_diagnostics.warning_table_row.select",
    ),
    click(
        "ConsoleDiagnosticsInfoTableRow",
        "workbench.extension.console_diagnostics.info_table_row.select",
    ),
    click(
        "ConsoleDiagnosticsGameplayTableRow",
        "workbench.extension.console_diagnostics.gameplay_table_row.select",
    ),
    click(
        "ConsoleDiagnosticsErrorTableRow",
        "workbench.extension.console_diagnostics.error_table_row.select",
    ),
    click(
        "ConsoleDiagnosticsOutput",
        "workbench.extension.console_diagnostics.output.select",
    ),
    click(
        "ConsoleDiagnosticsFilterConsole",
        "workbench.extension.console_diagnostics.filter_console.invoke",
    ),
    click(
        "ConsoleDiagnosticsClearConsole",
        "workbench.extension.console_diagnostics.clear_console.invoke",
    ),
    click(
        "RuntimeDiagnosticsOpen",
        "workbench.extension.runtime_diagnostics.open",
    ),
    click(
        "RuntimeDiagnosticsWatchTab",
        "workbench.extension.runtime_diagnostics.watch_tab.select",
    ),
    click(
        "RuntimeDiagnosticsEventsTab",
        "workbench.extension.runtime_diagnostics.events_tab.select",
    ),
    click(
        "RuntimeDiagnosticsConsoleTab",
        "workbench.extension.runtime_diagnostics.console_tab.select",
    ),
    click(
        "RuntimeDiagnosticsSessionPlayerRow",
        "workbench.extension.runtime_diagnostics.session_player_row.select",
    ),
    click(
        "RuntimeDiagnosticsWorldRuntimeRow",
        "workbench.extension.runtime_diagnostics.world_runtime_row.select",
    ),
    click(
        "RuntimeDiagnosticsEventStreamRow",
        "workbench.extension.runtime_diagnostics.event_stream_row.select",
    ),
    click(
        "RuntimeDiagnosticsActorHealthTableRow",
        "workbench.extension.runtime_diagnostics.actor_health_table_row.select",
    ),
    click(
        "RuntimeDiagnosticsAiGuardStateTableRow",
        "workbench.extension.runtime_diagnostics.ai_guard_state_table_row.select",
    ),
    click(
        "RuntimeDiagnosticsWorldTimeTableRow",
        "workbench.extension.runtime_diagnostics.world_time_table_row.select",
    ),
    click(
        "RuntimeDiagnosticsWeaponTargetTableRow",
        "workbench.extension.runtime_diagnostics.weapon_target_table_row.select",
    ),
    click(
        "RuntimeDiagnosticsOutput",
        "workbench.extension.runtime_diagnostics.output.select",
    ),
    click(
        "RuntimeDiagnosticsCaptureSnapshot",
        "workbench.extension.runtime_diagnostics.capture_snapshot.invoke",
    ),
    click(
        "RuntimeDiagnosticsExportReport",
        "workbench.extension.runtime_diagnostics.export_report.invoke",
    ),
    click("PerformanceOpen", "workbench.extension.performance.open"),
    click(
        "PerformanceFrameCaptureTab",
        "workbench.extension.performance.frame_capture_tab.select",
    ),
    click(
        "PerformanceCpuLaneTab",
        "workbench.extension.performance.cpu_lane_tab.select",
    ),
    click(
        "PerformanceGpuLaneTab",
        "workbench.extension.performance.gpu_lane_tab.select",
    ),
    click(
        "PerformanceCaptureRow",
        "workbench.extension.performance.capture_row.select",
    ),
    click(
        "PerformanceCpuGameThreadRow",
        "workbench.extension.performance.cpu_game_thread_row.select",
    ),
    click(
        "PerformanceGpuLightingRow",
        "workbench.extension.performance.gpu_lighting_row.select",
    ),
    click(
        "PerformanceGameThreadTableRow",
        "workbench.extension.performance.game_thread_table_row.select",
    ),
    click(
        "PerformanceRenderThreadTableRow",
        "workbench.extension.performance.render_thread_table_row.select",
    ),
    click(
        "PerformanceGpuLightingTableRow",
        "workbench.extension.performance.gpu_lighting_table_row.select",
    ),
    click(
        "PerformanceTextureUploadTableRow",
        "workbench.extension.performance.texture_upload_table_row.select",
    ),
    click(
        "PerformanceOutput",
        "workbench.extension.performance.output.select",
    ),
    click(
        "PerformanceCaptureFrame",
        "workbench.extension.performance.capture_frame.invoke",
    ),
    click(
        "PerformanceFilterSamples",
        "workbench.extension.performance.filter_samples.invoke",
    ),
    click(
        "TelemetryDashboardOpen",
        "workbench.extension.telemetry_dashboard.open",
    ),
    click(
        "TelemetryDashboardMetricsTab",
        "workbench.extension.telemetry_dashboard.metrics_tab.select",
    ),
    click(
        "TelemetryDashboardSegmentsTab",
        "workbench.extension.telemetry_dashboard.segments_tab.select",
    ),
    click(
        "TelemetryDashboardRawEventsTab",
        "workbench.extension.telemetry_dashboard.raw_events_tab.select",
    ),
    click(
        "TelemetryDashboardRetentionQueryRow",
        "workbench.extension.telemetry_dashboard.retention_query_row.select",
    ),
    click(
        "TelemetryDashboardNewUsersSegmentRow",
        "workbench.extension.telemetry_dashboard.new_users_segment_row.select",
    ),
    click(
        "TelemetryDashboardMetricFpsRow",
        "workbench.extension.telemetry_dashboard.metric_fps_row.select",
    ),
    click(
        "TelemetryDashboardDauTableRow",
        "workbench.extension.telemetry_dashboard.dau_table_row.select",
    ),
    click(
        "TelemetryDashboardFpsP95TableRow",
        "workbench.extension.telemetry_dashboard.fps_p95_table_row.select",
    ),
    click(
        "TelemetryDashboardCrashRateTableRow",
        "workbench.extension.telemetry_dashboard.crash_rate_table_row.select",
    ),
    click(
        "TelemetryDashboardQueueWaitTableRow",
        "workbench.extension.telemetry_dashboard.queue_wait_table_row.select",
    ),
    click(
        "TelemetryDashboardOutput",
        "workbench.extension.telemetry_dashboard.output.select",
    ),
    click(
        "TelemetryDashboardFilterTelemetry",
        "workbench.extension.telemetry_dashboard.filter_telemetry.invoke",
    ),
    click(
        "TelemetryDashboardRunQuery",
        "workbench.extension.telemetry_dashboard.run_query.invoke",
    ),
    change(
        "ConsoleDiagnosticsSubsystemEdit",
        "workbench.extension.console_diagnostics.subsystem.edit",
    ),
    submit(
        "ConsoleDiagnosticsSubsystemCommit",
        "workbench.extension.console_diagnostics.subsystem.commit",
    ),
    change(
        "ConsoleDiagnosticsSeverityEdit",
        "workbench.extension.console_diagnostics.severity.edit",
    ),
    submit(
        "ConsoleDiagnosticsSeverityCommit",
        "workbench.extension.console_diagnostics.severity.commit",
    ),
    change(
        "ConsoleDiagnosticsRegexEdit",
        "workbench.extension.console_diagnostics.regex.edit",
    ),
    submit(
        "ConsoleDiagnosticsRegexCommit",
        "workbench.extension.console_diagnostics.regex.commit",
    ),
    change(
        "RuntimeDiagnosticsSessionEdit",
        "workbench.extension.runtime_diagnostics.session.edit",
    ),
    submit(
        "RuntimeDiagnosticsSessionCommit",
        "workbench.extension.runtime_diagnostics.session.commit",
    ),
    change(
        "RuntimeDiagnosticsSubsystemEdit",
        "workbench.extension.runtime_diagnostics.subsystem.edit",
    ),
    submit(
        "RuntimeDiagnosticsSubsystemCommit",
        "workbench.extension.runtime_diagnostics.subsystem.commit",
    ),
    change(
        "RuntimeDiagnosticsFilterEdit",
        "workbench.extension.runtime_diagnostics.filter.edit",
    ),
    submit(
        "RuntimeDiagnosticsFilterCommit",
        "workbench.extension.runtime_diagnostics.filter.commit",
    ),
    change(
        "PerformanceCaptureEdit",
        "workbench.extension.performance.capture.edit",
    ),
    submit(
        "PerformanceCaptureCommit",
        "workbench.extension.performance.capture.commit",
    ),
    change(
        "PerformanceLaneEdit",
        "workbench.extension.performance.lane.edit",
    ),
    submit(
        "PerformanceLaneCommit",
        "workbench.extension.performance.lane.commit",
    ),
    change(
        "PerformanceThresholdEdit",
        "workbench.extension.performance.threshold.edit",
    ),
    submit(
        "PerformanceThresholdCommit",
        "workbench.extension.performance.threshold.commit",
    ),
    change(
        "TelemetryDashboardQueryEdit",
        "workbench.extension.telemetry_dashboard.query.edit",
    ),
    submit(
        "TelemetryDashboardQueryCommit",
        "workbench.extension.telemetry_dashboard.query.commit",
    ),
    change(
        "TelemetryDashboardRangeEdit",
        "workbench.extension.telemetry_dashboard.range.edit",
    ),
    submit(
        "TelemetryDashboardRangeCommit",
        "workbench.extension.telemetry_dashboard.range.commit",
    ),
    change(
        "TelemetryDashboardSegmentEdit",
        "workbench.extension.telemetry_dashboard.segment.edit",
    ),
    submit(
        "TelemetryDashboardSegmentCommit",
        "workbench.extension.telemetry_dashboard.segment.commit",
    ),
];
