[package]
name = "zircon_plugin_sound_runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Sound runtime plugin package for Zircon."

[features]
default = []
cpal-backend = ["dep:cpal"]

[dependencies]
zircon_runtime = { workspace = true, features = ["sound-contracts"] }
zircon_runtime_interface = { workspace = true }
cpal = { version = "0.15", optional = true }

[dev-dependencies]
zircon_plugin_sound_ray_traced_convolution_runtime = { path = "../features/ray_traced_convolution_reverb/runtime" }
zircon_plugin_sound_timeline_animation_runtime = { path = "../features/timeline_animation_track/runtime" }
