use super::ExpectedStatusOutputSlice;

#[path = "expected_status_row_data/runtime_01_04.rs"]
mod runtime_01_04;
#[path = "expected_status_row_data/runtime_05.rs"]
mod runtime_05;
#[path = "expected_status_row_data/runtime_06_09.rs"]
mod runtime_06_09;
#[path = "expected_status_row_data/runtime_10_13.rs"]
mod runtime_10_13;
#[path = "expected_status_row_data/runtime_14.rs"]
mod runtime_14;
#[path = "expected_status_row_data/runtime_15.rs"]
mod runtime_15;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICE_GROUPS: &[&[ExpectedStatusOutputSlice]] = &[
    runtime_01_04::RUNTIME_01_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_01_04::RUNTIME_02_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_01_04::RUNTIME_03_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_01_04::RUNTIME_04_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_BASELINE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_CROSS_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_SUPPORT_STRUCTURE_PLAN_STATUS_MODULE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_SUPPORT_STRUCTURE_STATUS_OUTPUT_SPLIT_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_SCENE_CLOSEOUT_DYNAMIC_SCENE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_SCENE_CLOSEOUT_FULL_SCENE_GATE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_SCENE_CLOSEOUT_SOURCE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_CARGO_EARLY_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_CARGO_LATE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_AUDIT_PLAN_COVERAGE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_AUDIT_RUNTIME_02_03_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_05::RUNTIME_05_AUDIT_RUNTIME_07_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_06_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_07_PERFORMANCE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_07_ASSET_RENDER_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_07_SCENE_ASSET_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_07_OWNER_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_08_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_09_BASELINE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_09_LEGACY_RENAME_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_06_09::RUNTIME_09_LAYOUT_PIPELINE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_10_DYNAMIC_API_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_10_SESSION_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_10_UI_CONTRACT_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_11_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_12_BASELINE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_12_ACTION_MAPPING_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_12_GAMEPAD_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_12_HOST_RECORDING_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_10_13::RUNTIME_13_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_14::RUNTIME_14_AUDIT_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_14::RUNTIME_14_GUARD_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_14::RUNTIME_14_CARGO_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M2_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M4_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_F12_RESOURCE_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_LOCK_POISON_STATUS_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_MODULE_CONVENTION_STATUS_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_REVIEW_STATUS_SYNC_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_UI_TESTS_FIRST_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_ASSET_BUDGET_TESTS_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_UI_TESTS_SECOND_EXPECTED_STATUS_OUTPUT_SLICES,
    runtime_15::RUNTIME_15_M3_PRODUCTION_GUARD_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES,
];
