use crate::text::TextLayoutSessionDiagnostics;

pub(super) fn record_text_layout_session_profile(diagnostics: TextLayoutSessionDiagnostics) {
    for (name, value) in [
        (
            "ui_text.session.layout_fallbacks",
            diagnostics.layout_fallbacks.fallback_count,
        ),
        (
            "ui_text.session.generation_deferred",
            diagnostics.layout_fallbacks.generation_deferred_count,
        ),
        (
            "ui_text.session.invalid_font_size",
            diagnostics.layout_fallbacks.invalid_font_size_count,
        ),
        (
            "ui_text.session.invalid_language",
            diagnostics.layout_fallbacks.invalid_language_count,
        ),
        (
            "ui_text.session.bidi_invariant",
            diagnostics.layout_fallbacks.bidi_invariant_count,
        ),
        (
            "ui_text.session.other_layout_error",
            diagnostics.layout_fallbacks.other_error_count,
        ),
        (
            "ui_text.session.shaping_failure_requests",
            diagnostics.shaping.failures.observed_count,
        ),
        (
            "ui_text.session.shaping_alternate_admissions",
            diagnostics.shaping.failures.alternate_backend_count,
        ),
        (
            "ui_text.session.shaping_deferred_failures",
            diagnostics.shaping.failures.deferred_count,
        ),
        (
            "ui_text.session.shaping_terminal_failures",
            diagnostics.shaping.failures.terminal_count,
        ),
        (
            "ui_text.session.backend_direct_runs",
            diagnostics.shaping.backend_routes.direct_run_count,
        ),
        (
            "ui_text.session.backend_alternate_runs",
            diagnostics.shaping.backend_routes.alternate_run_count,
        ),
        (
            "ui_text.session.backend_hybrid_runs",
            diagnostics.shaping.backend_routes.hybrid_run_count,
        ),
        (
            "ui_text.session.backend_recovered_source_ranges",
            diagnostics
                .shaping
                .backend_routes
                .recovered_source_range_count,
        ),
        (
            "ui_text.session.backend_deferred_runs",
            diagnostics.shaping.backend_routes.deferred_run_count,
        ),
        (
            "ui_text.session.backend_terminal_runs",
            diagnostics.shaping.backend_routes.terminal_run_count,
        ),
        (
            "ui_text.session.shaping_attempts",
            diagnostics.shaping.shaping_attempt_count,
        ),
        (
            "ui_text.session.font_generation_restarts",
            diagnostics.shaping.font_generation_restart_count,
        ),
        (
            "ui_text.session.font_resolution.primary_text_requests",
            diagnostics
                .shaping
                .font_resolution
                .primary_text_request_count,
        ),
        (
            "ui_text.session.font_resolution.primary_text_fast_paths",
            diagnostics
                .shaping
                .font_resolution
                .primary_text_fast_path_count,
        ),
        (
            "ui_text.session.font_resolution.cluster_requests",
            diagnostics.shaping.font_resolution.resolution_request_count,
        ),
        (
            "ui_text.session.font_resolution.resolution_cache_hits",
            diagnostics
                .shaping
                .font_resolution
                .resolution_cache_hit_count,
        ),
        (
            "ui_text.session.font_resolution.resolution_cache_misses",
            diagnostics
                .shaping
                .font_resolution
                .resolution_cache_miss_count,
        ),
        (
            "ui_text.session.font_resolution.candidate_cache_hits",
            diagnostics
                .shaping
                .font_resolution
                .candidate_cache_hit_count,
        ),
        (
            "ui_text.session.font_resolution.candidate_cache_misses",
            diagnostics
                .shaping
                .font_resolution
                .candidate_cache_miss_count,
        ),
        (
            "ui_text.session.font_resolution.decision_coverage_calls",
            diagnostics
                .shaping
                .font_resolution
                .decision_coverage_call_count,
        ),
        (
            "ui_text.session.font_resolution.primary_coverage_rejections",
            diagnostics
                .shaping
                .font_resolution
                .primary_coverage_rejection_count,
        ),
        (
            "ui_text.session.font_resolution.complete_candidate_visits",
            diagnostics
                .shaping
                .font_resolution
                .complete_candidate_visit_count,
        ),
        (
            "ui_text.session.font_resolution.complete_candidate_rejections",
            diagnostics
                .shaping
                .font_resolution
                .complete_candidate_rejection_count,
        ),
        (
            "ui_text.session.font_resolution.partial_candidate_visits",
            diagnostics
                .shaping
                .font_resolution
                .partial_candidate_visit_count,
        ),
        (
            "ui_text.session.font_resolution.primary_selections",
            diagnostics.shaping.font_resolution.primary_selection_count,
        ),
        (
            "ui_text.session.font_resolution.fallback_selections",
            diagnostics.shaping.font_resolution.fallback_selection_count,
        ),
        (
            "ui_text.session.font_resolution.partial_coverage_selections",
            diagnostics
                .shaping
                .font_resolution
                .partial_coverage_selection_count,
        ),
        (
            "ui_text.session.font_resolution.last_resort_selections",
            diagnostics
                .shaping
                .font_resolution
                .last_resort_selection_count,
        ),
        (
            "ui_text.session.font_resolution.depth_limit_selections",
            diagnostics
                .shaping
                .font_resolution
                .depth_limit_selection_count,
        ),
    ] {
        crate::profile_counter!("runtime", name, value);
    }
}
