use super::*;

pub(super) const M3_CHILD_GROUP_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
        M3_CHILD_GROUPS_GUARD_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_statuses.rs",
        ROOT_STATUSES_PATH,
        50,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/production_guard_support.rs",
        PRODUCTION_GUARD_SUPPORT_GUARD_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/production_guard_runtime_row_data.rs",
        PRODUCTION_GUARD_RUNTIME_ROW_DATA_GUARD_PATH,
        170,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data.rs",
        TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH,
        240,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15.rs",
        RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH,
        320,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
        RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH,
        220,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support.rs",
        PRODUCTION_GUARD_SUPPORT_ROWS_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/core_and_evidence.rs",
        PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_ROWS_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout.rs",
        PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_ROWS_PATH,
        220,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/review_guard.rs",
        PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_ROWS_PATH,
        220,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/runtime_row_data.rs",
        PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_ROWS_PATH,
        240,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/runtime_row_data/foundation_rows.rs",
        PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_FOUNDATION_ROWS_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/runtime_row_data/lock_poison_scene_script_rows.rs",
        PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_LOCK_POISON_SCENE_SCRIPT_ROWS_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/runtime_row_data/status_support_priority_rows.rs",
        PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROWS_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/runtime_row_data/asset_budget_rows.rs",
        PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_ASSET_BUDGET_ROWS_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/status_docs.rs",
        PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_ROWS_PATH,
        220,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/expected_slice_guards.rs",
        PRODUCTION_GUARD_SUPPORT_EXPECTED_SLICE_GUARDS_ROWS_PATH,
        120,
    ),
];
