#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(in crate::ui::retained_host::host_contract) struct HostMaterialPalette {
    pub shell_background: [u8; 4],
    pub surface: [u8; 4],
    pub surface_inset: [u8; 4],
    pub surface_hover: [u8; 4],
    pub surface_pressed: [u8; 4],
    pub surface_selected: [u8; 4],
    pub surface_disabled: [u8; 4],
    pub accent: [u8; 4],
    pub accent_soft: [u8; 4],
    pub border: [u8; 4],
    pub separator_strong: [u8; 4],
    pub separator_soft: [u8; 4],
    pub text: [u8; 4],
    pub text_muted: [u8; 4],
    pub text_disabled: [u8; 4],
    pub warning: [u8; 4],
    pub warning_container: [u8; 4],
    pub error: [u8; 4],
    pub error_container: [u8; 4],
    pub success: [u8; 4],
    pub success_container: [u8; 4],
    pub info: [u8; 4],
    pub info_container: [u8; 4],
    pub popup: [u8; 4],
    pub track: [u8; 4],
    pub focus_ring: [u8; 4],
    pub border_disabled: [u8; 4],
    pub shadow: [u8; 4],
}
