use super::*;

pub(super) const EXPECTED_SLICE_STRUCTURE_SUPPORT_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_PATH,
        50,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/parent_route_rows.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_CHILDREN[0],
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/guard_rows.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_CHILDREN[1],
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/map_rows.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_CHILDREN[2],
        130,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/foundation_rows.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_CHILDREN[3],
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/review_route_rows.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_CHILDREN[4],
        75,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/typed_error_rows.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_CHILDREN[5],
        30,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/row_data_owner_rows.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_CHILDREN[6],
        20,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/row_data_owner_rows/status_support_row_data.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_NESTED_CHILDREN[0],
        35,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/expected_slice_maps/structure_support/row_data_owner_rows/structure_route_maps.rs",
        EXPECTED_SLICE_STRUCTURE_SUPPORT_NESTED_CHILDREN[1],
        35,
    ),
];
