use super::*;

pub(super) const M2_ROW_DATA_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children.rs",
        M2_ROW_DATA_CHILDREN_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m2_row_data_children/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m2.rs",
        RUNTIME_15_M2_EXPECTED_STATUS_ROW_DATA_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m2/core_scene_asset_dynamic.rs",
        RUNTIME_15_M2_CORE_SCENE_ASSET_DYNAMIC_ROW_DATA_PATH,
        170,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m2/render_graphics.rs",
        RUNTIME_15_M2_RENDER_GRAPHICS_ROW_DATA_PATH,
        170,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m2/ui_platform_editor.rs",
        RUNTIME_15_M2_UI_PLATFORM_EDITOR_ROW_DATA_PATH,
        170,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m2/row_data_owner.rs",
        RUNTIME_15_M2_ROW_DATA_OWNER_PATH,
        120,
    ),
];
