use super::*;

pub(super) const CHILD_SUMMARY_STATUS_DOC_CHILDREN: &[(&str, &str, &str)] = &[
    (
        "budgets",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/module_layout_child_summary_status/budgets.rs",
        "runtime_15_module_layout_child_summary_status_docs_guard_children_stay_focused",
    ),
    (
        "delegation",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/module_layout_child_summary_status/delegation.rs",
        "runtime_15_module_layout_child_summary_status_docs_guard_is_folder_backed",
    ),
    (
        "source_ownership",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/module_layout_child_summary_status/source_ownership.rs",
        "runtime_15_module_layout_child_summary_status_doc_sources_are_child_owned",
    ),
    (
        "status_mirrors",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/module_layout_child_summary_status/status_mirrors.rs",
        "runtime_15_module_layout_child_summary_status_docs_are_child_owner",
    ),
    (
        "root_inventory",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_inventory.rs",
        "runtime_15_module_layout_child_summary_status_docs_root_inventory_is_child_owned",
    ),
];

pub(super) const CHILD_SUMMARY_STATUS_DOC_OWNER_BUDGETS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/module_layout_child_summaries.rs",
        CHILD_SUMMARY_GUARD_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/module_layout_child_summary_status_docs.rs",
        CHILD_SUMMARY_STATUS_DOCS_GUARD_PATH,
        110,
    ),
    (
        "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_paths.rs",
        ROOT_PATHS_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_statuses.rs",
        ROOT_STATUSES_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        110,
    ),
    (
        "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_source_blobs.rs",
        ROOT_SOURCE_BLOBS_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/module_layout_child_summary_status/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
];
