use super::*;

#[test]
fn runtime_15_review_guard_row_data_status_support_budgets_stay_focused() {
    assert_runtime_15_review_guard_row_data_budgets(&[
        (STATUS_SUPPORT_ROWS_GUARD_PATH, 30),
        (STATUS_SUPPORT_ROWS_FOLDER_BACKED_CHILD_PATH, 35),
        (STATUS_SUPPORT_ROWS_FOLDER_BACKED_ROW_LAYOUT_CHILD_PATH, 80),
        (
            STATUS_SUPPORT_ROWS_FOLDER_BACKED_STATUS_CURRENT_CHILD_PATH,
            95,
        ),
        (
            STATUS_SUPPORT_ROWS_FOLDER_BACKED_SPLIT_LAYOUT_CHILD_PATH,
            40,
        ),
        (
            STATUS_SUPPORT_ROWS_FOLDER_BACKED_SPLIT_LAYOUT_ROUTE_MOUNTS_CHILD_PATH,
            95,
        ),
        (
            STATUS_SUPPORT_ROWS_FOLDER_BACKED_SPLIT_LAYOUT_STATUS_CURRENT_CHILD_PATH,
            120,
        ),
        (
            STATUS_SUPPORT_ROWS_FOLDER_BACKED_SPLIT_LAYOUT_BUDGETS_CHILD_PATH,
            75,
        ),
        (
            STATUS_SUPPORT_ROWS_FOLDER_BACKED_SPLIT_LAYOUT_SPLIT_LAYOUT_CHILD_PATH,
            170,
        ),
        (STATUS_SUPPORT_ROWS_ANCHOR_MIRROR_CLEANUP_CHILD_PATH, 35),
        (
            STATUS_SUPPORT_ROWS_ANCHOR_MIRROR_CLEANUP_ROW_CLEANUP_CHILD_PATH,
            75,
        ),
        (
            STATUS_SUPPORT_ROWS_ANCHOR_MIRROR_CLEANUP_STATUS_CURRENT_CHILD_PATH,
            95,
        ),
        (
            STATUS_SUPPORT_ROWS_ANCHOR_MIRROR_CLEANUP_SPLIT_LAYOUT_CHILD_PATH,
            160,
        ),
        (STATUS_SUPPORT_ROWS_SPLIT_LAYOUT_CHILD_PATH, 40),
        (STATUS_SUPPORT_ROWS_SPLIT_LAYOUT_ROUTE_MOUNTS_CHILD_PATH, 70),
        (
            STATUS_SUPPORT_ROWS_SPLIT_LAYOUT_STATUS_CURRENT_CHILD_PATH,
            95,
        ),
        (STATUS_SUPPORT_ROWS_SPLIT_LAYOUT_BUDGETS_CHILD_PATH, 70),
        (
            STATUS_SUPPORT_ROWS_SPLIT_LAYOUT_SPLIT_LAYOUT_CHILD_PATH,
            170,
        ),
        (REVIEW_GUARD_STATUS_SUPPORT_ROWS_PARENT_PATH, 120),
        (REVIEW_GUARD_STATUS_SUPPORT_ROWS_PATH, 50),
        (REVIEW_GUARD_STATUS_SUPPORT_REVIEW_ROWS_CORE_PATH, 70),
        (
            REVIEW_GUARD_STATUS_SUPPORT_REVIEW_ROWS_STATUS_SUPPORT_GUARD_PATH,
            120,
        ),
        (
            REVIEW_GUARD_STATUS_SUPPORT_REVIEW_ROWS_TYPED_ERROR_GUARD_PATH,
            85,
        ),
        (
            REVIEW_GUARD_STATUS_SUPPORT_REVIEW_ROWS_ROW_DATA_GUARD_PATH,
            55,
        ),
        (
            REVIEW_GUARD_STATUS_SUPPORT_REVIEW_ROWS_ROW_DATA_OWNER_PATH,
            35,
        ),
        (
            REVIEW_GUARD_STATUS_SUPPORT_TYPED_ERROR_STATUS_DOC_ROWS_PATH,
            40,
        ),
        (
            REVIEW_GUARD_STATUS_SUPPORT_SOURCE_INVENTORY_FOUNDATION_ROWS_PATH,
            120,
        ),
        (
            REVIEW_GUARD_STATUS_SUPPORT_SOURCE_INVENTORY_INVENTORY_METADATA_ROWS_PATH,
            110,
        ),
        (
            REVIEW_GUARD_STATUS_SUPPORT_SOURCE_INVENTORY_DELEGATION_ROWS_PATH,
            90,
        ),
        (STATUS_SUPPORT_REVIEW_ROWS_GUARD_PATH, 45),
        (STATUS_SUPPORT_REVIEW_ROWS_ROUTE_CHILDREN_PATH, 45),
        (STATUS_SUPPORT_REVIEW_ROWS_EXPORT_CHAIN_PATH, 65),
        (STATUS_SUPPORT_REVIEW_ROWS_STATUS_CURRENT_PATH, 80),
        (STATUS_SUPPORT_REVIEW_ROWS_SPLIT_LAYOUT_PATH, 90),
    ]);
}
