use super::*;

#[test]
fn runtime_15_review_guard_row_data_typed_error_budgets_stay_focused() {
    assert_runtime_15_review_guard_row_data_budgets(&[
        (TYPED_ERROR_ROWS_GUARD_PATH, 40),
        (TYPED_ERROR_ROWS_ROUTE_CHILDREN_PATH, 45),
        (TYPED_ERROR_ROWS_REPRESENTATIVE_ROWS_PATH, 45),
        (TYPED_ERROR_ROWS_EXPORT_CHAIN_PATH, 45),
        (TYPED_ERROR_ROWS_STATUS_MIRRORS_PATH, 95),
        (TYPED_ERROR_ROWS_SPLIT_LAYOUT_PATH, 40),
        (TYPED_ERROR_ROWS_SPLIT_LAYOUT_ROUTE_MOUNTS_CHILD_PATH, 90),
        (TYPED_ERROR_ROWS_SPLIT_LAYOUT_STATUS_CURRENT_CHILD_PATH, 120),
        (TYPED_ERROR_ROWS_SPLIT_LAYOUT_BUDGETS_CHILD_PATH, 75),
        (TYPED_ERROR_ROWS_SPLIT_LAYOUT_SPLIT_LAYOUT_CHILD_PATH, 170),
        (TYPED_ERROR_ROWS_PATH, 80),
        (TYPED_ERROR_NATIVE_PLUGIN_ROWS_PATH, 130),
        (TYPED_ERROR_RUNTIME_SURFACE_ROWS_PATH, 80),
        (TYPED_ERROR_ASSET_SHADER_ROWS_PATH, 80),
    ]);
}
