type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 runtime index subplan map 01-15 sync",
        &[
            "runtime_15_runtime_index_subplan_map_01_15_sync_static_passed_cargo_deferred",
            "docs/plans/zircon_runtime/runtime/index.md",
            "14-runtime-module-family-closeout.md",
            "15-code-structure-and-module-conventions.md",
            "EXPECTED_SUBPLAN_COUNT = 15",
            "runtime_15_runtime_index_subplan_map_covers_01_15_status_locked",
        ],
    ),
    (
        "Runtime 15 M3 runtime index problem-row parser P01-P17 sync",
        &[
            "runtime_15_runtime_index_problem_row_parser_p01_p17_sync_static_passed_cargo_deferred",
            "runtime_plan_status_sources.py",
            "runtime_index_problem_rows",
            "EXPECTED_PROBLEM_ROW_COUNT = 17",
            "runtime_15_runtime_index_problem_row_parser_covers_p01_p17_status_locked",
        ],
    ),
    (
        "Runtime 15 M3 Runtime 03 module-doc status index anchor sync",
        &[
            "runtime_15_runtime_03_module_doc_status_index_anchor_sync_static_passed_cargo_deferred",
            "docs/plans/zircon_runtime/runtime/index.md",
            "Runtime 03 Schedule/frame-loop module-doc 镜像元数据",
            "Runtime 05 status-output Runtime 03 module-doc row",
            "frame schedule module-doc anchors 3/3",
            "guard/test files 8/8",
            "Runtime 03 guard anchors 14/14",
            "ecs_schedule/time/session/schedule_parallel Cargo gates",
            "runtime_15_runtime_03_module_doc_status_index_anchors_are_locked",
        ],
    ),
    (
        "Runtime 15 M3 Runtime 07 scene asset status anchor sync",
        &[
            "runtime_15_runtime_07_scene_asset_status_anchor_sync_static_passed_cargo_deferred",
            "docs/plans/zircon_runtime/runtime/index.md",
            "Runtime 07 scene asset owner split",
            "Runtime 07 scene asset split-drift repair",
            "Runtime 07 scene asset folder-split public-surface guard",
            "Runtime 07 scene asset guard 纳入 performance_hotpath_boundary",
            "split_drift_static_passed_cargo_deferred_active_lanes",
            "folder_split_guard_static_passed_cargo_deferred_active_lanes",
            "boundary_guard_anchor_static_passed_cargo_deferred_active_lanes",
            "hotspot_guard_anchor_count = 20",
            "standalone `rustc --edition 2021 --test ...performance_hotspots.rs` 通过 6/6",
            "`scene_asset` / Runtime 07 Cargo gates",
            "runtime_15_runtime_07_scene_asset_status_index_anchors_are_locked",
        ],
    ),
    (
        "Runtime 15 M3 Runtime 07 owner-budget status anchor sync",
        &[
            "runtime_15_runtime_07_owner_budget_status_anchor_sync_static_passed_cargo_deferred",
            "docs/plans/zircon_runtime/runtime/index.md",
            "Runtime 07 owner-budget 0-hotspot current audit sync",
            "`large_file_m1_gate_status = classified-and-clear`",
            "`large_file_hotspot_count = 0`",
            "`large_file_migration_debt_count = 0`",
            "`large_file_owner_class_count = 0`",
            "`large_file_unclassified_hotspot_count = 0`",
            "direct `performance_hotpath_boundary_audit` risks=0 / hotspots=0",
            "standalone `performance_hotspots.rs` exact owner-budget guards",
            "extract/ecs_query/performance profiling/FPS Cargo gates",
            "runtime_15_runtime_07_owner_budget_status_index_anchors_are_locked",
        ],
    ),
    (
        "Runtime 15 M3 Runtime 02 generated status anchor sync",
        &[
            "runtime_15_runtime_02_generated_status_anchor_sync_static_passed_cargo_deferred",
            "docs/plans/zircon_runtime/runtime/index.md",
            "Runtime 02 generated template count 审计同步",
            "`template_file_count=10`",
            "generated export templates 10/10",
            "0 migration debt",
            "stale 9/9 scan",
            "Runtime 02 generated/export/app/editor/plugin Cargo gates",
            "runtime_15_runtime_02_generated_status_index_anchors_are_locked",
        ],
    ),
    (
        "Runtime 15 M3 Runtime 10 behavior status anchor sync",
        &[
            "runtime_15_runtime_10_behavior_status_anchor_sync_static_passed_cargo_deferred",
            "docs/plans/zircon_runtime/runtime/index.md",
            "Runtime 10 Dynamic API 行为测试锚审计同步",
            "Runtime 05 status-output Runtime 10 behavior-test row",
            "behavior_test_anchor_count = 16",
            "missing_behavior_test_anchors = []",
            "standalone dynamic_api_session 9/9",
            "dynamic_api/app/UI gates pending",
            "runtime_15_runtime_10_behavior_status_index_anchors_are_locked",
        ],
    ),
    (
        "Runtime 15 M3 Runtime Cargo attempt status anchor sync",
        &[
            "runtime_15_runtime_cargo_attempt_status_anchor_sync_static_passed_cargo_deferred",
            "docs/plans/zircon_runtime/runtime/index.md",
            "cargo_deferred_active_lane",
            "cargo_blocked_external_compile_drift",
            "cargo_recheck_blocked_external_ui_compile_drift",
            "cargo_recheck_timeout_no_result",
            "Runtime 14 Cargo 验证窗口探测",
            "Runtime 14 animation Cargo gate 尝试",
            "Runtime 14 animation Cargo gate 修复与复验阻塞",
            "Runtime 14 animation runtime-status focused recheck timeout",
            "cargo test -p zircon_runtime --lib animation --locked",
            "runtime_status_reports_player_rig_and_gpu_readiness",
            "共享 lib-test 编译层",
            "SKINNED_MESH_MAX_JOINT_MATRICES",
            "ViewportCameraSnapshot.temporal_jitter",
            "31 passed; 3 failed",
            "AnimationPlayerRuntimeStatus::sanitized_snapshot",
            "UiInputDispatchDiagnostics.capture_started",
            "default_interactions/table.rs:257",
            "904s",
            "无测试结果",
            "cargo/rustc processes were stopped",
            "runtime_15_runtime_cargo_attempt_status_index_anchors_are_locked",
        ],
    ),
    (
        "Runtime 15 M3 plan-status index-tables child-owner split",
        &[
            "runtime_15_plan_status_index_tables_child_owner_split_static_passed_cargo_deferred",
            "plan_status/index_tables.rs",
            "plan_status/index_tables/subplan_map.rs",
            "plan_status/index_tables/status_anchors.rs",
            "plan_status/index_tables/index_consistency.rs",
            "runtime_15_plan_status_index_tables_guard_child_owner_split",
        ],
    ),
    (
        "Runtime 15 M3 plan-status support inventory review sync",
        &[
            "runtime_15_plan_status_support_inventory_review_sync_static_passed_cargo_deferred",
            "runtime_architecture_review_documents_all_absorption_guards",
            "runtime_absorption/code_review_findings.rs",
            "runtime_absorption/structure_convention.rs",
            "runtime_index_problem_row_for",
            "scene/tests/ecs_schedule/render_extract.rs",
            "world_basics/world_state.rs",
            "property_paths/runtime_mutation.rs",
            "Runtime 05 scene:: failure support-first triage",
            "Runtime 05 scene:: lower-layer diagnostic matrix",
            "standalone `plan_status.rs` 41/41 passed",
        ],
    ),
];
