use super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[(
    "Runtime 15 M3 code-review structure-guard row-data folder-backed split",
    &[
        "runtime_15_code_review_structure_guard_row_data_folder_backed_static_passed_cargo_deferred",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/status_docs.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/folder_backed_summary.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/typed_error.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/row_data_owner.rs",
        "runtime_15_code_review_structure_guard_row_data_is_folder_backed",
        "Cargo gate deferred",
    ],
),
(
    "Runtime 15 M3 code review findings status-row source child-tree sync",
    &[
        "runtime_15_code_review_findings_status_row_source_child_tree_sync_static_passed_cargo_deferred",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status_docs.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status_docs/sync.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status_docs/delegation.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status_docs/source_anchors/status_mirrors.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/status_mirrors.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/folder_backed_summary/source_inventory/delegation.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/budgets.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/folder_backed_summary/status_mirrors.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/status_docs.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/folder_backed_summary.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/typed_error.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/row_data_owner.rs",
        "runtime_15_code_review_findings_status_row_source_reads_structure_guard_children",
        "Cargo gate deferred",
    ],
),
(
    "Runtime 15 M3 code review findings split row/map source sync",
    &[
        "runtime_15_code_review_findings_split_row_map_source_sync_static_passed_cargo_deferred",
        "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/status_docs/root_row_sources.rs",
        "review_guard_status_map_source",
        "review_guard_date_map_source",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_status_sync/importer_fixture_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_status_sync/p0_core_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_status_sync/provider_lookup_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_status_sync/typed_runtime_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/review_guard_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/review_guard_rows/core_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/review_guard_rows/f8_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/review_guard_rows/p0_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/plugin_importer_rows/review_guards.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/f8_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/direct_assertion_rows/p0_rows.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/status_docs/source_anchors.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/core_rows.rs",
        "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/code_review_guard_maps/status_doc_rows.rs",
        "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/typed_error_structure_maps/top_level_maps.rs",
        "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/code_review_guard_maps/status_doc_rows.rs",
        "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/typed_error_structure_maps/top_level_maps.rs",
        "Runtime 15 M3 typed-error structure assertions guard child-owner split",
        "runtime_15_code_review_findings_status_docs_source_anchors_are_child_owner",
        "Runtime 15 M3 code review findings test folder split",
        "runtime_15_code_review_findings_tests_folder_split_static_passed_cargo_deferred",
        "tests/runtime_absorption/code_review_findings.rs",
        "runtime_15_code_review_findings_tests_are_folder_backed",
        "runtime_15_code_review_findings_folder_backed_summary_is_child_owner",
        "Cargo gate deferred",
    ],
),
(
    "Runtime 15 M3 code-review structure-guard root-and-children row-data child split",
    &[
        "runtime_15_code_review_structure_guard_root_and_children_row_data_child_split_static_passed_cargo_deferred",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children/code_review_findings.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children/p0_robustness.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children/plugin_importer_dx.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children/p0_native_fixture.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children/f8_child_owner.rs",
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/structure_guard_rows/root_and_children/late_api_cleanup.rs",
        "runtime_15_code_review_structure_guard_root_and_children_row_data_is_child_backed",
        "Cargo gate deferred",
    ],
)];
