pub(super) const PLUGIN_IMPORTER_DX_STRUCTURE_GUARD_CHILD_OWNER_SPLIT: &[&str] = &[
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
    "runtime_15_code_review_findings_tests_are_folder_backed",
    "review_d10_animation_physics_tests_use_sdk_bridge_call",
    "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
    "Cargo gate deferred",
];

pub(super) const PLUGIN_IMPORTER_DX_REVIEW_GUARD_CHILD_OWNER_SPLIT: &[&str] = &[
    "runtime_15_plugin_importer_dx_review_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d5_editor_authoring.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d8_registration_builder.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d9_editor_runtime_mirror.rs",
    "review_d5_editor_authoring_plugins_use_sdk_macro",
    "review_d8_runtime_registration_builder_original_evidence_paths_use_sdk_builder",
    "review_d9_editor_runtime_mirror_consumers_use_sdk_declaration",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
    "runtime_15_code_review_findings_tests_are_folder_backed",
    "Cargo gate deferred",
];

pub(super) const PLUGIN_IMPORTER_D13_REVIEW_GUARD_CHILD_OWNER_SPLIT: &[&str] = &[
    "runtime_15_plugin_importer_d13_sdk_review_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/manifest_parity.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_crates.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_exports.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_manifests.rs",
    "review_d13_importer_runtime_exports_use_sdk_macro",
    "review_d13_importer_runtime_manifests_use_sdk_builder",
    "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
    "runtime_15_code_review_findings_tests_are_folder_backed",
    "Cargo gate deferred",
];

pub(super) const PLUGIN_IMPORTER_D1_CAPABILITY_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "Runtime 15 M3 plugin-importer D1 capability single-source guard folder-backed split",
    "runtime_15_plugin_importer_d1_capability_guard_folder_backed_static_passed_cargo_deferred",
    "frameworks_02_m3_plugin_importer_d1_capability_guard_folder_backed_static_passed_cargo_deferred",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source/runtime_roots.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source/audit_surfaces.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source/sdk_builder.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source/status_docs.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d1_capability_single_source/split_layout.rs",
    "runtime_15_plugin_importer_d1_capability_guard_is_folder_backed",
    "review_d1_plugin_capabilities_use_single_source_and_sdk_builder_mirror",
    "D1_RUNTIME_CAPABILITY_ROOTS",
    "PluginFeatureBundleBuilder",
    "plugins_12_capability_single_source_conformance",
    "Cargo gate deferred",
];
