use std::time::Duration;

/// Aggregate, bounded-cost telemetry for dynamic scene hot reload.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct DynamicSceneAssetReloadDiagnostics {
    pub events_drained: u64,
    pub raw_events_examined: u64,
    pub filtered_events: u64,
    pub event_bytes_drained: u64,
    pub tasks_scheduled: u64,
    pub cancellation_requests: u64,
    pub cancelled_running_tasks: u64,
    pub wasted_completed_tasks: u64,
    pub dropped_events: u64,
    pub stale_results: u64,
    pub generation_gaps: u64,
    pub event_budget_overruns: u64,
    pub ready_budget_overruns: u64,
    pub apply_budget_overruns: u64,
    pub active_tasks: usize,
    pub deferred_reloads: usize,
    pub ready_results: usize,
    pub target_staging_tasks: usize,
    pub latest_entries: usize,
    pub pending_metadata_bytes: usize,
    pub ready_result_bytes: usize,
    pub target_staging_reserved_bytes: usize,
    pub resident_result_bytes: usize,
    pub max_active_tasks: usize,
    pub max_deferred_reloads: usize,
    pub max_ready_results: usize,
    pub max_target_staging_tasks: usize,
    pub max_pending_metadata_bytes: usize,
    pub max_ready_result_bytes: usize,
    pub max_target_staging_reserved_bytes: usize,
    pub max_resident_result_bytes: usize,
    pub max_target_capture_duration: Duration,
    pub oldest_active_age: Duration,
}
