use super::*;

pub(super) const FOUNDATION_GUARDS_ROW_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data.rs",
        FOUNDATION_GUARDS_ROW_DATA_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards.rs",
        FOUNDATION_GUARDS_ROWS_PATH,
        130,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards/dead_code_surface.rs",
        FOUNDATION_GUARDS_DEAD_CODE_SURFACE_PATH,
        170,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards/runtime_structure_tests.rs",
        FOUNDATION_GUARDS_RUNTIME_STRUCTURE_TESTS_PATH,
        130,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards/plugin_importer_review.rs",
        FOUNDATION_GUARDS_PLUGIN_IMPORTER_REVIEW_PATH,
        150,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards/plugin_importer_migrations.rs",
        FOUNDATION_GUARDS_PLUGIN_IMPORTER_MIGRATIONS_PATH,
        150,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards/runtime_absorption_followups.rs",
        FOUNDATION_GUARDS_RUNTIME_ABSORPTION_FOLLOWUPS_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards/row_data_owner.rs",
        FOUNDATION_GUARDS_ROW_DATA_OWNER_PATH,
        90,
    ),
];
