"""NativeDynamic TOML templates."""

from __future__ import annotations

import json
from typing import Any

from .native_dynamic_contract import NATIVE_DYNAMIC_ABI_STRING_FIELDS
from .native_dynamic_payload_file_manifest import native_dynamic_content_hash


def native_plugin_load_manifest_template(package_exports: list[dict[str, Any]]) -> str:
    parts = [
        "# Generated by Zircon export. "
        "Native dynamic plugins are loaded from these packages.\n"
    ]
    for package_export in package_exports:
        parts.extend(
            (
                "\n[[plugins]]\n",
                f"id = {toml_string(package_export['package_id'])}\n",
                f"path = {toml_string(package_export['path'])}\n",
                f"manifest = {toml_string(package_export['manifest'])}\n",
                (
                    "package_report = "
                    f"{toml_string(package_export['package_report'])}\n"
                ),
                native_dynamic_abi_contract_toml(
                    "plugins.abi",
                    package_export["abi"],
                ),
            )
        )
    return "".join(parts)


def native_dynamic_package_report_template(
    package_export: dict[str, Any],
    payload_file_manifest: list[dict[str, object]],
) -> str:
    output = "# Generated by Zircon export. Native dynamic package report.\n"
    output += "format_version = 1\n"
    output += f"package_id = {toml_string(package_export['package_id'])}\n"
    output += f"directory = {toml_string(package_export['directory'])}\n"
    output += f"path = {toml_string(package_export['path'])}\n"
    output += f"manifest = {toml_string(package_export['manifest'])}\n"
    output += native_dynamic_abi_contract_toml("abi", package_export["abi"])
    output += native_dynamic_payload_toml("payload", payload_file_manifest)
    return output


def native_dynamic_payload_toml(
    table_name: str,
    file_manifest: list[dict[str, object]],
) -> str:
    parts = [
        f"\n[{table_name}]\n",
        f"file_count = {len(file_manifest)}\n",
        (
            "content_hash = "
            f"{toml_string(native_dynamic_content_hash(file_manifest))}\n"
        ),
    ]
    for entry in file_manifest:
        parts.extend(
            (
                f"\n[[{table_name}.files]]\n",
                f"path = {toml_string(entry['path'])}\n",
                f"bytes = {entry['bytes']}\n",
                f"sha256 = {toml_string(entry['sha256'])}\n",
            )
        )
    return "".join(parts)


def native_dynamic_abi_contract_toml(table_name: str, abi: dict[str, Any]) -> str:
    output = f"\n[{table_name}]\n"
    output += f"abi_version = {abi['abi_version']}\n"
    for field in NATIVE_DYNAMIC_ABI_STRING_FIELDS:
        output += f"{field} = {toml_string(abi[field])}\n"
    return output


def toml_string(value: object) -> str:
    return json.dumps(str(value))
