pub(super) const EXPECTED_RUNTIME_10_SOURCE_FILES: &[&str] = &[
    "zircon_runtime_interface/src/runtime_api/api_table.rs",
    "zircon_runtime_interface/src/runtime_api/host_requests.rs",
    "zircon_runtime_interface/src/plugin_api.rs",
    "zircon_runtime_interface/src/profiling.rs",
    "zircon_runtime_interface/src/tests/abi_safety_contracts.rs",
    "zircon_runtime_interface/src/tests/contracts.rs",
    "zircon_runtime/src/dynamic_api/exports.rs",
    "zircon_runtime/src/dynamic_api/session.rs",
    "zircon_runtime/src/dynamic_api/session/diagnostics.rs",
    "zircon_runtime/src/dynamic_api/session/host_requests.rs",
    "zircon_runtime/src/dynamic_api/session/events.rs",
    "zircon_runtime/src/dynamic_api/tests/api_table.rs",
    "zircon_runtime/src/dynamic_api/tests/host_requests.rs",
    "zircon_runtime/src/dynamic_api/tests/profile_control.rs",
    "zircon_runtime/src/dynamic_api/tests/session_lifecycle.rs",
    "zircon_runtime/src/dynamic_api/tests/session_entry_points.rs",
    "zircon_runtime/src/dynamic_api/tests/session_profiles.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/shared.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/headless_profiles.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/event_split.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/test_owner_split.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/ffi_panic_boundary.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/ui_contract.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/v2_contract.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/runtime_diagnostics.rs",
    "zircon_runtime/src/tests/runtime_absorption/dynamic_api_session/mirror_docs.rs",
    "zircon_runtime/src/tests/runtime_absorption/plan_status/cargo_gates/late.rs",
    "zircon_app/src/entry/runtime_library/loaded_runtime.rs",
    "zircon_app/src/entry/runtime_library/runtime_session.rs",
    "zircon_app/src/entry/runtime_library/tests.rs",
    "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
    "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
];

pub(super) const EXPECTED_RUNTIME_10_FUNCTION_TABLES: &[(&str, &str, usize)] = &[
    (
        "zircon_runtime_interface/src/runtime_api/api_table.rs",
        "ZrHostApiV1",
        4,
    ),
    (
        "zircon_runtime_interface/src/runtime_api/api_table.rs",
        "ZrRuntimeApiV1",
        13,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostApiV3",
        7,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostEcsApiV1",
        3,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostAssetApiV1",
        1,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostEventApiV1",
        2,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostBridgeApiV1",
        1,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostDiagnosticsApiV1",
        2,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrPluginStateSnapshotApiV1",
        4,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrPluginApiV1",
        4,
    ),
];

pub(super) const EXPECTED_RUNTIME_10_SESSION_OPERATIONS: &[&str] = &[
    "create_session",
    "destroy_session",
    "handle_event",
    "capture_frame",
    "capture_accessibility_tree",
    "bind_viewport_surface",
    "unbind_viewport_surface",
    "present_viewport",
    "profile_control",
    "tick_frame",
    "drain_host_requests",
];

pub(super) const EXPECTED_RUNTIME_10_BEHAVIOR_TEST_ANCHORS: &[(&str, &[&str])] = &[
    (
        "zircon_runtime/src/dynamic_api/tests/api_table.rs",
        &["runtime_api_table_entries_are_panic_wrapped_at_ffi_boundary"],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/session_lifecycle.rs",
        &[
            "destroy_session_reports_explicit_not_found_for_missing_nonzero_handle",
            "destroy_session_removes_registry_entry_so_destroyed_handles_become_missing",
            "session_destroy_reports_explicit_not_found_after_headless_destroy",
        ],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/session_entry_points.rs",
        &[
            "all_session_entry_points_reject_invalid_handle",
            "destroyed_headless_session_entry_points_reject_old_handle",
            "missing_session_entry_points_reject_nonzero_handle",
        ],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/session_profiles.rs",
        &[
            "create_session_accepts_named_headless_profile_without_render_bridge",
            "minimal_and_headless_profiles_skip_render_bridge_bootstrap",
        ],
    ),
    (
        "zircon_app/src/entry/runtime_library/tests.rs",
        &[
            "runtime_api_pointer_rejects_null_from_entry_symbol",
            "runtime_api_pointer_rejects_version_mismatch_before_session_creation",
            "runtime_api_pointer_rejects_missing_required_functions_before_session_creation",
            "runtime_library_loader_reports_missing_entry_symbol_source_path",
            "runtime_library_loader_reports_missing_entry_symbol_from_dynamic_library",
            "runtime_session_create_reports_first_call_failure_context",
        ],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/profile_control.rs",
        &["profile_control_runtime_diagnostics_snapshot_returns_store_and_scene_reload_report"],
    ),
];

pub(super) const EXPECTED_RUNTIME_10_RUNTIME_DIAGNOSTICS_ANCHORS: &[(&str, &str)] = &[
    (
        "zircon_runtime_interface/src/profiling.rs",
        "pub struct RuntimeDiagnosticsSnapshot",
    ),
    (
        "zircon_runtime_interface/src/profiling.rs",
        "pub runtime_diagnostics: Option<RuntimeDiagnosticsSnapshot>",
    ),
    (
        "zircon_runtime_interface/src/profiling.rs",
        "pub struct RuntimeDiagnosticSeriesSnapshot",
    ),
    (
        "zircon_runtime_interface/src/profiling.rs",
        "pub struct RuntimeSceneAssetReloadDiagnostics",
    ),
    (
        "zircon_runtime_interface/src/lib.rs",
        "RuntimeSceneAssetReloadDiagnostics",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        "ProfileControlCommand::RuntimeDiagnosticsSnapshot",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        "runtime_diagnostics_response(session)",
    ),
    (
        "zircon_runtime/src/dynamic_api/session/diagnostics.rs",
        "pub(super) fn runtime_diagnostics_response",
    ),
    (
        "zircon_runtime/src/dynamic_api/session/diagnostics.rs",
        "collect_runtime_diagnostics(&session.runtime.handle())",
    ),
    (
        "zircon_runtime/src/dynamic_api/session/diagnostics.rs",
        "session.scene_asset_reload_queue.is_some()",
    ),
    (
        "zircon_runtime/src/dynamic_api/session/diagnostics.rs",
        "session.last_scene_asset_reload_report.as_ref()",
    ),
    (
        "zircon_runtime/src/core/runtime/diagnostics/profiling/mod.rs",
        "runtime diagnostics snapshot requires dynamic session",
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/profile_control.rs",
        "runtime_diagnostics_snapshot_returns_store_and_scene_reload_report",
    ),
    (
        "zircon_runtime_interface/src/tests/contracts.rs",
        "runtime_diagnostics_snapshot",
    ),
    (
        "docs/zircon_runtime/dynamic_api/session.md",
        "Runtime Diagnostics Profile-Control Snapshot",
    ),
];

pub(super) const EXPECTED_RUNTIME_10_SCENE_ASSET_RELOAD_DIAGNOSTIC_PATH_ANCHORS: &[(&str, &str)] =
    &[
        (
            "zircon_runtime/src/dynamic_api/session.rs",
            "queue.tick_into_level(self.runtime.handle().scheduler(), &self.level)",
        ),
        (
            "zircon_runtime/src/dynamic_api/session.rs",
            "record_scene_asset_reload_frame_report(&self.runtime, &report)",
        ),
        (
            "zircon_runtime/src/dynamic_api/session.rs",
            "self.last_scene_asset_reload_report = Some(report)",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "pub(super) fn record_scene_asset_reload_frame_report",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.events_drained",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.scheduled",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.skipped",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.skipped_removed",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.skipped_reload_failed",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.skipped_missing_locator",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.skipped_stale_revision",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.superseded_pending",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.applied",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.failed",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.stale",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.pending",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "scene.asset_reload.receiver_disconnected",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "DynamicSceneAssetReloadSkipReason::MissingLocator",
        ),
        (
            "zircon_runtime/src/dynamic_api/session/scene_asset_reload_diagnostics.rs",
            "[\"scene\", \"asset_reload\"]",
        ),
        (
            "docs/zircon_runtime/dynamic_api/session.md",
            "scene.asset_reload.*",
        ),
        (
            "docs/zircon_runtime/scene/dynamic_scene.md",
            "Dynamic runtime session scene-asset reload diagnostics",
        ),
    ];

pub(super) const EXPECTED_RUNTIME_10_HOST_REQUEST_PAYLOAD_ANCHORS: &[(&str, &str)] = &[
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "pub struct ZrRuntimeHostRequestBatchV1",
    ),
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "pub enum ZrRuntimeHostRequestV1",
    ),
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "Ime(ZrRuntimeImeHostRequestV1)",
    ),
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "GamepadRumble(ZrRuntimeGamepadRumbleRequestV1)",
    ),
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "Cursor(ZrRuntimeCursorHostRequestV1)",
    ),
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "pub struct ZrRuntimeImeHostRequestV1",
    ),
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "pub struct ZrRuntimeGamepadRumbleRequestV1",
    ),
    (
        "zircon_runtime_interface/src/runtime_api/host_requests.rs",
        "pub struct ZrRuntimeCursorHostRequestV1",
    ),
    (
        "zircon_runtime_interface/src/tests/contracts.rs",
        "runtime_host_request_batch_serializes_ime_requests",
    ),
    (
        "zircon_runtime_interface/src/tests/contracts.rs",
        "runtime_host_request_batch_serializes_gamepad_rumble_requests",
    ),
    (
        "zircon_runtime_interface/src/tests/contracts.rs",
        "runtime_host_request_batch_serializes_cursor_requests",
    ),
    (
        "zircon_runtime/src/dynamic_api/session/host_requests.rs",
        "pub(in crate::dynamic_api) fn runtime_ime_host_request",
    ),
    (
        "zircon_runtime/src/dynamic_api/session/host_requests.rs",
        "pub(in crate::dynamic_api) fn runtime_gamepad_rumble_request",
    ),
    (
        "zircon_runtime/src/dynamic_api/session/host_requests.rs",
        "pub(in crate::dynamic_api) fn runtime_cursor_host_request",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        ".drain_ime_host_requests()",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        ".drain_gamepad_rumble_requests()",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        ".drain_cursor_host_requests()",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        ".map(ZrRuntimeHostRequestV1::ime)",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        ".map(ZrRuntimeHostRequestV1::gamepad_rumble)",
    ),
    (
        "zircon_runtime/src/dynamic_api/session.rs",
        ".map(ZrRuntimeHostRequestV1::cursor)",
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/host_requests.rs",
        "host_request_batch_encodes_runtime_ime_requests",
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/host_requests.rs",
        "host_request_batch_encodes_gamepad_rumble_requests",
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/host_requests.rs",
        "host_request_batch_encodes_cursor_requests",
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/host_requests.rs",
        "host_request_free_rejects_wrong_owner_token",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
        "ZrRuntimeHostRequestV1::Ime(request)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
        "ZrRuntimeHostRequestV1::GamepadRumble(request)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
        "ZrRuntimeHostRequestV1::Cursor(request)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
        "apply_runtime_ime_host_request(window.as_ref(), request)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
        "apply_runtime_gamepad_rumble_request(request)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/routing.rs",
        "apply_runtime_cursor_host_request(window.as_ref(), request)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "ZrRuntimeCursorHostRequestKindV1::SetVisible",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "window.set_cursor_visible(request.value)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "ZrRuntimeCursorHostRequestKindV1::SetGrabMode",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "set_cursor_grab(CursorGrabMode::Confined)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "ZrRuntimeCursorHostRequestKindV1::SetHitTest",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "set_cursor_hittest(request.value)",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "ZrRuntimeCursorHostRequestKindV1::SetPosition",
    ),
    (
        "zircon_app/src/entry/runtime_entry_app/host_requests/cursor/request.rs",
        "set_cursor_position",
    ),
];

pub(super) const EXPECTED_RUNTIME_10_MIRROR_DOCS: &[&str] = &[
    "docs/zircon_runtime/dynamic_api/session.md",
    "docs/plans/zircon_runtime/runtime/10-dynamic-api-and-interface-convergence.md",
    "docs/plans/zircon_runtime/runtime/index.md",
    "docs/engine-architecture/runtime-architecture-review-m0.md",
    "docs/engine-architecture/runtime-interface-convergence.md",
    "docs/engine-architecture/runtime-interface-cdylib-loader.md",
];

pub(super) fn slice_between<'a>(source: &'a str, start_anchor: &str, end_anchor: &str) -> &'a str {
    let start = source
        .find(start_anchor)
        .unwrap_or_else(|| panic!("source should contain start anchor `{start_anchor}`"));
    let tail = &source[start..];
    let end = tail.find(end_anchor).unwrap_or_else(|| {
        panic!("source should contain end anchor `{end_anchor}` after `{start_anchor}`")
    });
    &tail[..end]
}
