use super::*;

#[test]
fn default_forward_plus_pipeline_compiles_expected_stage_order_and_passes() {
    let pipeline = RenderPipelineAsset::default_forward_plus();
    let compiled = pipeline.compile(&test_extract()).unwrap();

    assert!(pipeline.phase_mapping.contains(&RenderPhase::AlphaMask3d));

    assert_eq!(
        compiled.stages,
        vec![
            RenderPassStage::DepthPrepass,
            RenderPassStage::Shadow,
            RenderPassStage::AmbientOcclusion,
            RenderPassStage::Lighting,
            RenderPassStage::Opaque3d,
            RenderPassStage::AlphaMask3d,
            RenderPassStage::Transparent3d,
            RenderPassStage::PostProcess,
            RenderPassStage::Overlay,
            RenderPassStage::Debug,
            RenderPassStage::Ui,
        ]
    );
    assert_eq!(
        compiled
            .graph
            .passes()
            .iter()
            .map(|pass| pass.name.as_str())
            .collect::<Vec<_>>(),
        vec![
            "preview-sky",
            "depth-prepass",
            "hzb-occlusion-cull",
            "velocity-object",
            "velocity-camera",
            "shadow-atlas",
            "hzb-build",
            "light-grid-build",
            "opaque-mesh",
            "alpha-mask-mesh",
            "transparent-mesh",
            "motion-vector-tile-max",
            "motion-vector-tile-max-coarse",
            "motion-vector-neighbor-max",
            "depth-of-field-prepare",
            "depth-of-field",
            "motion-blur",
            "exposure-histogram",
            "exposure-resolve",
            "screen-space-reflection-reflection-pyramid",
            "screen-space-reflection-reflection-pyramid-coarse",
            "screen-space-reflection-specular-occlusion",
            "screen-space-reflection-resolve",
            "scene-composite",
            "blur",
            "bloom-extract",
            "uber",
            "output-transfer",
            "fxaa",
            "overlay-gizmo",
            "runtime-ui",
        ]
    );
    pass_resource_access(
        &compiled,
        "depth-prepass",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Write,
    );
    pass_resource_access(
        &compiled,
        "depth-prepass",
        PostProcessGraphResourceNames::GBUFFER_NORMAL,
        RenderGraphResourceAccessKind::Write,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "velocity-object",
            PostProcessGraphResourceNames::SCENE_VELOCITY,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "velocity-object",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "depth-of-field-prepare",
        PostProcessGraphResourceNames::SCENE_COLOR,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "depth-of-field-prepare",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "depth-of-field-prepare",
            PostProcessGraphResourceNames::DEPTH_OF_FIELD_COC,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "depth-of-field-prepare",
            PostProcessGraphResourceNames::DEPTH_OF_FIELD_BOKEH,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "hzb-occlusion-cull",
        PostProcessGraphResourceNames::HISTORY_PREVIOUS_HZB_FURTHEST,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "hzb-build",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "hzb-build",
        PostProcessGraphResourceNames::HZB_FURTHEST,
        RenderGraphResourceAccessKind::Write,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-reflection-pyramid",
        PostProcessGraphResourceNames::SCENE_COLOR,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "screen-space-reflection-reflection-pyramid",
            PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-reflection-pyramid-coarse",
        PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "screen-space-reflection-reflection-pyramid-coarse",
            PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID_COARSE,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "velocity-camera",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "velocity-camera",
            PostProcessGraphResourceNames::SCENE_VELOCITY,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::load_store())
    );
    pass_resource_access(
        &compiled,
        "motion-vector-tile-max",
        PostProcessGraphResourceNames::SCENE_VELOCITY,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "motion-vector-tile-max",
            PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "motion-vector-tile-max-coarse",
        PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "motion-vector-tile-max-coarse",
            PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "motion-vector-neighbor-max",
        PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "motion-vector-neighbor-max",
            PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-specular-occlusion",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-specular-occlusion",
        PostProcessGraphResourceNames::GBUFFER_MATERIAL,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-specular-occlusion",
        PostProcessGraphResourceNames::AMBIENT_OCCLUSION,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "screen-space-reflection-specular-occlusion",
            PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_SPECULAR_OCCLUSION,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::SCENE_COLOR,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::GBUFFER_NORMAL,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::GBUFFER_MATERIAL,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::HZB_FURTHEST,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_REFLECTION_PYRAMID_COARSE,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_SPECULAR_OCCLUSION,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX,
        RenderGraphResourceAccessKind::Read,
    );
    let screen_space_reflection_history_write = pass_resource_access(
        &compiled,
        "screen-space-reflection-resolve",
        PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_HISTORY,
        RenderGraphResourceAccessKind::Write,
    );
    assert_eq!(
        screen_space_reflection_history_write.kind,
        RenderGraphResourceKind::TransientTexture
    );
    assert_eq!(
        screen_space_reflection_history_write.attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "uber",
        PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "uber",
        PostProcessGraphResourceNames::DEPTH_OF_FIELD_COC,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "uber",
        PostProcessGraphResourceNames::DEPTH_OF_FIELD_BOKEH,
        RenderGraphResourceAccessKind::Read,
    );
    let screen_space_reflection_history_read = pass_resource_access(
        &compiled,
        "uber",
        PostProcessGraphResourceNames::SCREEN_SPACE_REFLECTION_HISTORY,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        screen_space_reflection_history_read.kind,
        RenderGraphResourceKind::TransientTexture
    );
    assert_eq!(
        compiled.required_extract_sections,
        vec![
            "debug".to_string(),
            "geometry".to_string(),
            "lighting".to_string(),
            "post_process".to_string(),
            "ui".to_string(),
            "view".to_string(),
            "visibility".to_string(),
        ]
    );
    assert_eq!(
        compiled.history_bindings,
        vec![FrameHistoryBinding::read_write(
            FrameHistorySlot::HzbFurthest
        )]
    );
}

#[test]
fn default_deferred_pipeline_compiles_expected_stage_order_and_passes() {
    let pipeline = RenderPipelineAsset::default_deferred();
    let compiled = pipeline.compile(&test_extract()).unwrap();

    assert!(pipeline.phase_mapping.contains(&RenderPhase::AlphaMask3d));

    assert_eq!(
        compiled.stages,
        vec![
            RenderPassStage::DepthPrepass,
            RenderPassStage::Shadow,
            RenderPassStage::Deferred,
            RenderPassStage::AlphaMask3d,
            RenderPassStage::AmbientOcclusion,
            RenderPassStage::Lighting,
            RenderPassStage::Transparent3d,
            RenderPassStage::PostProcess,
            RenderPassStage::Overlay,
            RenderPassStage::Debug,
            RenderPassStage::Ui,
        ]
    );
    assert_eq!(
        compiled
            .graph
            .passes()
            .iter()
            .map(|pass| pass.name.as_str())
            .collect::<Vec<_>>(),
        vec![
            "preview-sky",
            "depth-prepass",
            "hzb-occlusion-cull",
            "velocity-object",
            "velocity-camera",
            "shadow-atlas",
            "gbuffer-mesh",
            "hzb-build",
            "light-grid-build",
            "deferred-lighting",
            "transparent-mesh",
            "motion-vector-tile-max",
            "motion-vector-tile-max-coarse",
            "motion-vector-neighbor-max",
            "depth-of-field-prepare",
            "depth-of-field",
            "motion-blur",
            "exposure-histogram",
            "exposure-resolve",
            "screen-space-reflection-reflection-pyramid",
            "screen-space-reflection-reflection-pyramid-coarse",
            "screen-space-reflection-specular-occlusion",
            "screen-space-reflection-resolve",
            "scene-composite",
            "blur",
            "bloom-extract",
            "uber",
            "output-transfer",
            "fxaa",
            "overlay-gizmo",
            "runtime-ui",
        ]
    );
    pass_resource_access(
        &compiled,
        "depth-prepass",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Write,
    );
    pass_resource_access(
        &compiled,
        "depth-prepass",
        PostProcessGraphResourceNames::GBUFFER_NORMAL,
        RenderGraphResourceAccessKind::Write,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "velocity-object",
            PostProcessGraphResourceNames::SCENE_VELOCITY,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "velocity-object",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "velocity-camera",
        PostProcessGraphResourceNames::SCENE_DEPTH,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "velocity-camera",
            PostProcessGraphResourceNames::SCENE_VELOCITY,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::load_store())
    );
    pass_resource_access(
        &compiled,
        "motion-vector-tile-max",
        PostProcessGraphResourceNames::SCENE_VELOCITY,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "motion-vector-tile-max",
            PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "motion-vector-tile-max-coarse",
        PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "motion-vector-tile-max-coarse",
            PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "motion-vector-neighbor-max",
        PostProcessGraphResourceNames::MOTION_VECTOR_TILE_MAX_COARSE,
        RenderGraphResourceAccessKind::Read,
    );
    assert_eq!(
        pass_resource_access(
            &compiled,
            "motion-vector-neighbor-max",
            PostProcessGraphResourceNames::MOTION_VECTOR_NEIGHBOR_MAX,
            RenderGraphResourceAccessKind::Write,
        )
        .attachment_ops,
        Some(RenderGraphAttachmentOps::clear_store())
    );
    pass_resource_access(
        &compiled,
        "hzb-occlusion-cull",
        PostProcessGraphResourceNames::HISTORY_PREVIOUS_HZB_FURTHEST,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "gbuffer-mesh",
        PostProcessGraphResourceNames::GBUFFER_ALBEDO,
        RenderGraphResourceAccessKind::Write,
    );
    pass_resource_access(
        &compiled,
        "gbuffer-mesh",
        PostProcessGraphResourceNames::GBUFFER_MATERIAL,
        RenderGraphResourceAccessKind::Write,
    );
    pass_resource_access(
        &compiled,
        "deferred-lighting",
        PostProcessGraphResourceNames::GBUFFER_ALBEDO,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "deferred-lighting",
        PostProcessGraphResourceNames::GBUFFER_NORMAL,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "deferred-lighting",
        PostProcessGraphResourceNames::GBUFFER_MATERIAL,
        RenderGraphResourceAccessKind::Read,
    );
    pass_resource_access(
        &compiled,
        "deferred-lighting",
        PostProcessGraphResourceNames::FINAL_COLOR,
        RenderGraphResourceAccessKind::Read,
    );
    assert!(
        compiled
            .graph
            .passes()
            .iter()
            .flat_map(|pass| pass.resources.iter())
            .any(|resource| resource.name == PostProcessGraphResourceNames::GBUFFER_MATERIAL),
        "default deferred graph should declare its backed material G-buffer"
    );
    assert_eq!(
        compiled.required_extract_sections,
        vec![
            "debug".to_string(),
            "geometry".to_string(),
            "lighting".to_string(),
            "post_process".to_string(),
            "ui".to_string(),
            "view".to_string(),
            "visibility".to_string(),
        ]
    );
    assert_eq!(
        compiled.history_bindings,
        vec![FrameHistoryBinding::read_write(
            FrameHistorySlot::HzbFurthest
        )]
    );
}
