use super::*;

pub(super) const RUNTIME_15_M4_ROW_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m4_row_data.rs",
        RUNTIME_15_M4_ROW_DATA_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m4_row_data/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m4_row_data/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m4_row_data/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m4_row_data/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        110,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_m4_row_data/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data.rs",
        TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH,
        800,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15.rs",
        RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH,
        800,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
        RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH,
        800,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m4.rs",
        RUNTIME_15_M4_EXPECTED_STATUS_ROW_DATA_PATH,
        800,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support.rs",
        RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_PATH,
        800,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget.rs",
        RUNTIME_15_M3_STATUS_SUPPORT_ROW_DATA_AND_BUDGET_PATH,
        340,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/status_support/row_data_and_budget/m3_m4_row_data.rs",
        RUNTIME_15_M4_ROW_DATA_STATUS_ROWS_PATH,
        170,
    ),
];
