use crate::core::framework::render::RenderStats;

use super::super::{DiagnosticStore, record_bytes, record_count};

pub(super) fn record(store: &mut DiagnosticStore, frame_index: u64, stats: &RenderStats) {
    let report = stats.last_graph_execution_resource_report;
    record_count(
        store,
        "render.graph.execution.texture_view_count",
        frame_index,
        report.texture_view_count,
        &["render", "graph", "execution", "resource", "texture"],
    );
    record_count(
        store,
        "render.graph.execution.external_texture_view_count",
        frame_index,
        report.external_texture_view_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "texture",
            "external",
        ],
    );
    record_count(
        store,
        "render.graph.execution.owned_texture_count",
        frame_index,
        report.owned_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "texture",
            "owned",
        ],
    );
    record_count(
        store,
        "render.graph.execution.buffer_count",
        frame_index,
        report.buffer_count,
        &["render", "graph", "execution", "resource", "buffer"],
    );
    record_count(
        store,
        "render.graph.execution.bound_resource_count",
        frame_index,
        report.total_bound_resource_count,
        &["render", "graph", "execution", "resource"],
    );
    let pool = report.transient_pool_report;
    record_count(
        store,
        "render.graph.execution.transient_pool.texture_created_count",
        frame_index,
        pool.texture_created_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "created",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.texture_reused_count",
        frame_index,
        pool.texture_reused_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "reused",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.buffer_created_count",
        frame_index,
        pool.buffer_created_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "created",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.buffer_reused_count",
        frame_index,
        pool.buffer_reused_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "reused",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.texture_pool_entry_count",
        frame_index,
        pool.texture_pool_entry_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.buffer_pool_entry_count",
        frame_index,
        pool.buffer_pool_entry_count,
        &["render", "graph", "execution", "resource", "pool", "buffer"],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.texture_pool_retained_bytes",
        frame_index,
        pool.texture_pool_retained_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "retained",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.buffer_pool_retained_bytes",
        frame_index,
        pool.buffer_pool_retained_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "retained",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.texture_pool_budget_bytes",
        frame_index,
        pool.texture_pool_budget_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "budget",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.buffer_pool_budget_bytes",
        frame_index,
        pool.buffer_pool_budget_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "budget",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.evicted_texture_count",
        frame_index,
        pool.evicted_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "evicted",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.evicted_buffer_count",
        frame_index,
        pool.evicted_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "evicted",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_evicted_texture_count",
        frame_index,
        pool.budget_evicted_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "budget",
            "evicted",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_evicted_buffer_count",
        frame_index,
        pool.budget_evicted_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "budget",
            "evicted",
        ],
    );
}
