use crate::core::framework::render::RenderStats;

use super::super::{record_bytes, record_count, DiagnosticStore};

pub(super) fn record(store: &mut DiagnosticStore, frame_index: u64, stats: &RenderStats) {
    let report = stats.last_graph_execution_resource_report;
    record_count(
        store,
        "render.graph.execution.texture_view_count",
        frame_index,
        report.texture_view_count,
        &["render", "graph", "execution", "resource", "texture"],
    );
    record_count(
        store,
        "render.graph.execution.external_texture_view_count",
        frame_index,
        report.external_texture_view_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "texture",
            "external",
        ],
    );
    record_count(
        store,
        "render.graph.execution.owned_texture_count",
        frame_index,
        report.owned_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "texture",
            "owned",
        ],
    );
    record_count(
        store,
        "render.graph.execution.buffer_count",
        frame_index,
        report.buffer_count,
        &["render", "graph", "execution", "resource", "buffer"],
    );
    record_count(
        store,
        "render.graph.execution.bound_resource_count",
        frame_index,
        report.total_bound_resource_count,
        &["render", "graph", "execution", "resource"],
    );
    let pool = report.transient_pool_report;
    record_count(
        store,
        "render.graph.execution.transient_pool.persistent_texture_request_count",
        frame_index,
        pool.persistent_texture_request_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "persistent",
            "requested",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.persistent_texture_requested_bytes",
        frame_index,
        pool.persistent_texture_requested_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "persistent",
            "requested",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.persistent_texture_created_count",
        frame_index,
        pool.persistent_texture_created_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "persistent",
            "created",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.persistent_texture_reused_count",
        frame_index,
        pool.persistent_texture_reused_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "persistent",
            "reused",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.pending_retire_texture_count",
        frame_index,
        pool.pending_retire_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "pending",
            "texture",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.pending_retire_texture_bytes",
        frame_index,
        pool.pending_retire_texture_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "pending",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.pending_retire_buffer_count",
        frame_index,
        pool.pending_retire_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "pending",
            "buffer",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.pending_retire_buffer_bytes",
        frame_index,
        pool.pending_retire_buffer_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "pending",
            "buffer",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.completion_reclaimed_texture_count",
        frame_index,
        pool.completion_reclaimed_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "completed",
            "reclaimed",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.completion_reclaimed_buffer_count",
        frame_index,
        pool.completion_reclaimed_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "completed",
            "reclaimed",
            "buffer",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.completion_discarded_texture_count",
        frame_index,
        pool.completion_discarded_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "terminal",
            "discarded",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.completion_discarded_buffer_count",
        frame_index,
        pool.completion_discarded_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "terminal",
            "discarded",
            "buffer",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.completion_texture_status_query_count",
        frame_index,
        pool.completion_texture_status_query_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "status_query",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.completion_buffer_status_query_count",
        frame_index,
        pool.completion_buffer_status_query_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "submission",
            "status_query",
            "buffer",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.device_epoch_discarded_texture_count",
        frame_index,
        pool.device_epoch_discarded_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "device",
            "epoch",
            "discarded",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.device_epoch_discarded_buffer_count",
        frame_index,
        pool.device_epoch_discarded_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "device",
            "epoch",
            "discarded",
            "buffer",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.texture_created_count",
        frame_index,
        pool.texture_created_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "created",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.texture_reused_count",
        frame_index,
        pool.texture_reused_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "reused",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.buffer_created_count",
        frame_index,
        pool.buffer_created_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "created",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.buffer_reused_count",
        frame_index,
        pool.buffer_reused_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "reused",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.texture_pool_entry_count",
        frame_index,
        pool.texture_pool_entry_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.buffer_pool_entry_count",
        frame_index,
        pool.buffer_pool_entry_count,
        &["render", "graph", "execution", "resource", "pool", "buffer"],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.texture_pool_retained_bytes",
        frame_index,
        pool.texture_pool_retained_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "retained",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.buffer_pool_retained_bytes",
        frame_index,
        pool.buffer_pool_retained_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "retained",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.texture_pool_budget_bytes",
        frame_index,
        pool.texture_pool_budget_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "budget",
        ],
    );
    record_bytes(
        store,
        "render.graph.execution.transient_pool.buffer_pool_budget_bytes",
        frame_index,
        pool.buffer_pool_budget_bytes,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "budget",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.evicted_texture_count",
        frame_index,
        pool.evicted_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "evicted",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.evicted_buffer_count",
        frame_index,
        pool.evicted_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "evicted",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_evicted_texture_count",
        frame_index,
        pool.budget_evicted_texture_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "texture",
            "budget",
            "evicted",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_evicted_buffer_count",
        frame_index,
        pool.budget_evicted_buffer_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "buffer",
            "budget",
            "evicted",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.stale_texture_scan_count",
        frame_index,
        pool.stale_texture_scan_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "maintenance",
            "stale_scan",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.stale_buffer_scan_count",
        frame_index,
        pool.stale_buffer_scan_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "maintenance",
            "stale_scan",
            "buffer",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_texture_accounted_count",
        frame_index,
        pool.budget_texture_accounted_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "maintenance",
            "budget_accounting",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_buffer_accounted_count",
        frame_index,
        pool.budget_buffer_accounted_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "maintenance",
            "budget_accounting",
            "buffer",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_texture_sort_candidate_count",
        frame_index,
        pool.budget_texture_sort_candidate_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "maintenance",
            "budget_sort",
            "texture",
        ],
    );
    record_count(
        store,
        "render.graph.execution.transient_pool.budget_buffer_sort_candidate_count",
        frame_index,
        pool.budget_buffer_sort_candidate_count,
        &[
            "render",
            "graph",
            "execution",
            "resource",
            "pool",
            "maintenance",
            "budget_sort",
            "buffer",
        ],
    );
}
