use crate::core::framework::render::RenderStats;

use super::super::{record_count, DiagnosticStore};

pub(super) fn record(store: &mut DiagnosticStore, frame_index: u64, stats: &RenderStats) {
    let report = stats.last_graph_materialization_report;
    record_count(
        store,
        "render.graph.materialization.required_resource_count",
        frame_index,
        report.required_resource_count(),
        &["render", "graph", "materialization", "resource"],
    );
    record_count(
        store,
        "render.graph.materialization.bound_resource_count",
        frame_index,
        report.bound_resource_count(),
        &["render", "graph", "materialization", "resource", "bound"],
    );
    record_count(
        store,
        "render.graph.materialization.missing_resource_count",
        frame_index,
        report.missing_resource_count(),
        &["render", "graph", "materialization", "resource", "missing"],
    );
    record_count(
        store,
        "render.graph.materialization.missing_materialized_resource_count",
        frame_index,
        report.missing_materialized_resource_count(),
        &[
            "render",
            "graph",
            "materialization",
            "resource",
            "missing",
            "typed",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.required_texture_count",
        frame_index,
        report.required_texture_count,
        &["render", "graph", "materialization", "texture"],
    );
    record_count(
        store,
        "render.graph.materialization.bound_texture_count",
        frame_index,
        report.bound_texture_count,
        &["render", "graph", "materialization", "texture", "bound"],
    );
    record_count(
        store,
        "render.graph.materialization.missing_texture_count",
        frame_index,
        report.missing_texture_count,
        &["render", "graph", "materialization", "texture", "missing"],
    );
    record_count(
        store,
        "render.graph.materialization.required_buffer_count",
        frame_index,
        report.required_buffer_count,
        &["render", "graph", "materialization", "buffer"],
    );
    record_count(
        store,
        "render.graph.materialization.bound_buffer_count",
        frame_index,
        report.bound_buffer_count,
        &["render", "graph", "materialization", "buffer", "bound"],
    );
    record_count(
        store,
        "render.graph.materialization.missing_buffer_count",
        frame_index,
        report.missing_buffer_count,
        &["render", "graph", "materialization", "buffer", "missing"],
    );
    record_count(
        store,
        "render.graph.materialization.required_external_count",
        frame_index,
        report.required_external_count,
        &["render", "graph", "materialization", "external"],
    );
    record_count(
        store,
        "render.graph.materialization.bound_external_count",
        frame_index,
        report.bound_external_count(),
        &["render", "graph", "materialization", "external", "bound"],
    );
    record_count(
        store,
        "render.graph.materialization.missing_external_count",
        frame_index,
        report.missing_external_count(),
        &["render", "graph", "materialization", "external", "missing"],
    );
    record_count(
        store,
        "render.graph.materialization.bound_required_external_count",
        frame_index,
        report.bound_required_external_count,
        &[
            "render",
            "graph",
            "materialization",
            "external",
            "required",
            "bound",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.missing_required_external_count",
        frame_index,
        report.missing_required_external_count,
        &[
            "render",
            "graph",
            "materialization",
            "external",
            "required",
            "missing",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.report_only_external_count",
        frame_index,
        report.report_only_external_count,
        &[
            "render",
            "graph",
            "materialization",
            "external",
            "report_only",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.bound_report_only_external_count",
        frame_index,
        report.bound_report_only_external_count,
        &[
            "render",
            "graph",
            "materialization",
            "external",
            "report_only",
            "bound",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.missing_report_only_external_count",
        frame_index,
        report.missing_report_only_external_count,
        &[
            "render",
            "graph",
            "materialization",
            "external",
            "report_only",
            "missing",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.stale_binding_count",
        frame_index,
        report.stale_binding_count(),
        &[
            "render",
            "graph",
            "materialization",
            "resource",
            "stale_binding",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.stale_texture_binding_count",
        frame_index,
        report.stale_texture_binding_count,
        &[
            "render",
            "graph",
            "materialization",
            "texture",
            "stale_binding",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.stale_buffer_binding_count",
        frame_index,
        report.stale_buffer_binding_count,
        &[
            "render",
            "graph",
            "materialization",
            "buffer",
            "stale_binding",
        ],
    );
    record_count(
        store,
        "render.graph.materialization.sparse_texture_reservation_count",
        frame_index,
        report.sparse_texture_reservation_count,
        &[
            "render",
            "graph",
            "materialization",
            "texture",
            "sparse_texture",
        ],
    );
}
