use super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 code review findings plugin-importer DX structure guard child-owner split",
        &[
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "review_d10_animation_physics_tests_use_sdk_bridge_call",
            "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer DX status-doc guard child-owner split",
        &[
            "runtime_15_plugin_importer_dx_status_docs_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/status_docs.rs",
            "runtime_15_plugin_importer_dx_status_docs_are_child_owner",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "runtime_15_plugin_importer_dx_source_inventory_is_child_owner",
            "Runtime 15 M3 plugin-importer DX source inventory guard child-owner split",
            "runtime_15_plugin_importer_dx_source_inventory_guard_child_owner_split_static_passed_cargo_deferred",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer DX source inventory guard child-owner split",
        &[
            "runtime_15_plugin_importer_dx_source_inventory_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/source_inventory.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_exports.rs",
            "runtime_15_plugin_importer_dx_source_inventory_is_child_owner",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "11 plugin-importer DX review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer DX structure assertions guard child-owner split",
        &[
            "runtime_15_plugin_importer_dx_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_exports.rs",
            "runtime_15_plugin_importer_dx_structure_assertions_are_child_owner",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "runtime_15_plugin_importer_dx_source_inventory_is_child_owner",
            "11 plugin-importer DX review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer DX structure assertions guard folder-backed split",
        &[
            "runtime_15_plugin_importer_dx_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/review_mounts.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/delegation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/child_ownership.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/status_mirrors.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk.rs",
            "runtime_15_plugin_importer_dx_structure_assertions_are_child_owner",
            "runtime_15_plugin_importer_dx_structure_assertions_children_are_child_owned",
            "runtime_15_plugin_importer_d13_sdk_structure_assertions_are_child_owner",
            "runtime_15_plugin_importer_dx_structure_assertions_guard_folder_backed_status_is_current",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer D13 SDK structure assertions guard child-owner split",
        &[
            "runtime_15_plugin_importer_d13_sdk_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_exports.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/manifest_parity.rs",
            "runtime_15_plugin_importer_d13_sdk_structure_assertions_are_child_owner",
            "runtime_15_plugin_importer_dx_structure_assertions_are_child_owner",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "3 D13 importer SDK review guards",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer DX review guard child-owner split",
        &[
            "runtime_15_plugin_importer_dx_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d5_editor_authoring.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d8_registration_builder.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d9_editor_runtime_mirror.rs",
            "review_d5_editor_authoring_plugins_use_sdk_macro",
            "review_d8_runtime_registration_builder_original_evidence_paths_use_sdk_builder",
            "review_d9_editor_runtime_mirror_consumers_use_sdk_declaration",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer D13 SDK review guard child-owner split",
        &[
            "runtime_15_plugin_importer_d13_sdk_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/manifest_parity.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_crates.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_exports.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk/runtime_manifests.rs",
            "review_d13_importer_runtime_exports_use_sdk_macro",
            "review_d13_importer_runtime_manifests_use_sdk_builder",
            "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
            "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
