use super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 code review findings test folder split",
        &[
            "runtime_15_code_review_findings_tests_folder_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/mod.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            "review_priority_recommendation_tracks_current_remaining_work",
            "ds7_static_plugin_manifest_generation_parity_review_synced_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d6_runtime_plugin_id.rs",
            "review_d6_runtime_plugin_id_accepts_external_string_keys",
            "d6_runtime_plugin_id_open_string_newtype_review_static_passed_cargo_deferred",
            "review_d13_importer_runtime_exports_use_sdk_macro",
            "review_d13_importer_runtime_manifests_use_sdk_builder",
            "tests/runtime_absorption/code_review_findings/render_structure.rs",
            "tests/runtime_absorption/code_review_findings/f12_dead_code.rs",
            "runtime_15_code_review_findings_tests_are_folder_backed",
        ],
    ),
    (
        "Runtime 15 M3 code-review standalone harness current-path sync",
        &[
            "runtime_15_code_review_standalone_harness_current_path_sync_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings.rs",
            "#[path = \"code_review_findings/f12_dead_code.rs\"]",
            "#[path = \"code_review_findings/typed_error_convergence/mod.rs\"]",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/test_fixtures.rs",
            "review_f8_runtime_plugin_descriptor_test_fixtures_use_builder",
            "builder call count 59",
            "tests/runtime_absorption/code_review_findings/f12_dead_code.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/foundation/core_rows.rs",
            "review_f12_runtime_production_dead_code_suppression_is_globally_gated",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 P0 robustness review guard child-owner split",
        &[
            "runtime_15_p0_robustness_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_host_callbacks.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/lock_poison.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/render_submit.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/priority_recommendation.rs",
            "review_f1_native_host_callbacks_catch_unwind_before_crossing_ffi",
            "review_f2_scene_eventbus_locks_recover_after_poison",
            "review_f4_render_submit_capability_gaps_return_typed_errors",
            "review_ds8_d3_native_fixture_uses_sdk_macro_and_single_manifest",
            "review_d13_native_fixture_importer_is_manifest_described",
            "review_priority_recommendation_tracks_current_remaining_work",
            "runtime_15_p0_robustness_review_guards_are_child_owners",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 P0 native fixture review guard leaf-owner split",
        &[
            "runtime_15_p0_native_fixture_review_guard_leaf_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/sdk_macro_manifest.rs",
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/importer_manifest.rs",
            "review_ds8_d3_native_fixture_uses_sdk_macro_and_single_manifest",
            "review_d13_native_fixture_importer_is_manifest_described",
            "runtime_15_p0_native_fixture_review_guards_are_leaf_owners",
            "runtime_15_p0_robustness_review_guards_are_child_owners",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 F8 API convergence review guard child-owner split",
        &[
            "runtime_15_f8_api_convergence_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/texture_import_settings.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/scaffold.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/first_party_descriptors.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/test_fixtures.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/private_fields.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/constructor_retirement.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/status_mirrors.rs",
            "review_f8_texture_import_settings_use_fallible_apply_not_with",
            "review_f8_runtime_plugin_descriptor_exposes_builder_scaffold",
            "review_f8_first_party_runtime_plugin_descriptors_use_builder",
            "review_f8_runtime_plugin_descriptor_test_fixtures_use_builder",
            "review_f8_runtime_plugin_descriptor_fields_are_private_with_accessors",
            "review_f8_runtime_plugin_descriptor_public_constructor_is_retired",
            "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
            "runtime_15_f8_api_convergence_review_guards_are_child_owners",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 F8 descriptor review guard child-owner split",
        &[
            "runtime_15_f8_descriptor_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/scaffold.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/first_party_descriptors.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/test_fixtures.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/private_fields.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/constructor_retirement.rs",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/status_mirrors.rs",
            "review_f8_runtime_plugin_descriptor_exposes_builder_scaffold",
            "review_f8_first_party_runtime_plugin_descriptors_use_builder",
            "review_f8_runtime_plugin_descriptor_test_fixtures_use_builder",
            "review_f8_runtime_plugin_descriptor_fields_are_private_with_accessors",
            "review_f8_runtime_plugin_descriptor_public_constructor_is_retired",
            "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
            "runtime_15_f8_api_convergence_review_guards_are_child_owners",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "F8 review harness 7/7",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 late API cleanup review guard child-owner split",
        &[
            "runtime_15_late_api_cleanup_review_guard_child_owner_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f11_shading_model_registry.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f15_editor_pane_data_conversion.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f17_entity_path_lookup.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f18_asset_manager_resolution.rs",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup/f19_scene_renderer_construction.rs",
            "review_f11_shading_model_registry_has_no_dead_plugin_registration_surface",
            "review_f15_editor_pane_data_conversion_top_row_uses_projection_owners",
            "review_f17_entity_path_option_lookup_uses_get_verb",
            "review_f18_asset_manager_resolution_returns_registered_handle",
            "review_f19_scene_renderer_construction_modules_use_construct_names",
            "runtime_15_late_api_cleanup_review_guards_are_child_owners",
            "runtime_15_code_review_findings_tests_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
