pub(in super::super) const EXPECTED_RUNTIME_10_FUNCTION_TABLES: &[(&str, &str, usize)] = &[
    (
        "zircon_runtime_interface/src/runtime_api/api_table.rs",
        "ZrHostApiV1",
        4,
    ),
    (
        "zircon_runtime_interface/src/runtime_api/api_table.rs",
        "ZrRuntimeApiV2",
        19,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostApiV3",
        7,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostApiV4",
        7,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostEcsApiV1",
        3,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostEcsApiV2",
        3,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostAssetApiV1",
        1,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostEventApiV1",
        2,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostBridgeApiV1",
        1,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrHostDiagnosticsApiV1",
        2,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrPluginStateSnapshotApiV1",
        4,
    ),
    (
        "zircon_runtime_interface/src/plugin_api.rs",
        "ZrPluginApiV1",
        4,
    ),
];

pub(in super::super) const EXPECTED_RUNTIME_10_SESSION_OPERATIONS: &[&str] = &[
    "create_session",
    "destroy_session",
    "handle_event",
    "capture_frame",
    "capture_accessibility_tree",
    "bind_viewport_surface",
    "unbind_viewport_surface",
    "present_viewport",
    "profile_control",
    "tick_frame",
    "drain_host_requests",
    "subscribe_plugin_event",
    "unsubscribe_plugin_event",
    "drain_plugin_events",
    "submit_operation",
    "poll_operation",
    "harvest_operation",
];
