pub(in super::super) const EXPECTED_RUNTIME_10_BEHAVIOR_TEST_ANCHORS: &[(&str, &[&str])] = &[
    (
        "zircon_runtime/src/dynamic_api/tests/api_table.rs",
        &["runtime_api_table_entries_are_panic_wrapped_at_ffi_boundary"],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/session_lifecycle.rs",
        &[
            "destroy_session_reports_explicit_not_found_for_missing_nonzero_handle",
            "destroy_session_removes_registry_entry_only_after_event_mirror_quiescent_teardown",
            "session_destroy_reports_explicit_not_found_after_headless_destroy",
        ],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/session_entry_points.rs",
        &[
            "all_session_entry_points_reject_invalid_handle",
            "destroyed_headless_session_entry_points_reject_old_handle",
            "missing_session_entry_points_reject_nonzero_handle",
        ],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/session_profiles.rs",
        &[
            "create_session_accepts_named_headless_profile_without_render_bridge",
            "minimal_and_headless_profiles_skip_render_bridge_bootstrap",
        ],
    ),
    (
        "zircon_app/src/entry/runtime_library/tests.rs",
        &[
            "runtime_api_pointer_rejects_null_from_entry_symbol",
            "runtime_api_pointer_rejects_version_mismatch_before_session_creation",
            "runtime_api_pointer_names_every_missing_required_function",
            "runtime_library_loader_reports_missing_entry_symbol_source_path",
            "runtime_library_loader_reports_missing_entry_symbol_from_dynamic_library",
            "runtime_session_create_reports_first_call_failure_context",
        ],
    ),
    (
        "zircon_runtime/src/dynamic_api/tests/profile_control.rs",
        &["profile_control_runtime_diagnostics_snapshot_returns_store_and_scene_reload_report"],
    ),
    (
        "zircon_runtime/tests/runtime_owned_result_v8.rs",
        &[
            "runtime_v8_owned_results_require_opaque_exactly_once_release",
            "runtime_v8_release_is_concurrent_and_exactly_once",
            "runtime_v8_destroy_is_retryable_after_outstanding_result_release",
            "runtime_v8_release_rejects_a_different_session_without_changing_owner_census",
            "runtime_v8_release_performance_acceptance",
        ],
    ),
];
