pub(in super::super) const STRUCTURE_ASSERTIONS_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure assertions guard folder-backed split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/convergence_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence.rs",
    "runtime_15_typed_error_structure_assertions_are_child_owner",
    "runtime_15_typed_error_structure_assertions_children_are_child_owned",
    "runtime_15_typed_error_native_plugin_loader_structure_is_child_owner",
    "runtime_15_typed_error_structure_moved_guard_absence_is_child_owner",
    "runtime_15_typed_error_structure_assertions_guard_folder_backed_status_is_current",
    "Cargo gate deferred",
];

pub(in super::super) const STRUCTURE_ASSERTIONS_SOURCE_RECONCILIATION: &[&str] = &[
    "runtime_15_typed_error_structure_assertions_source_reconciliation_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure assertions source reconciliation",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/structure_guard_children/typed_error/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/convergence_mounts/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/source_inventory/paths.rs",
    "runtime_15_code_review_findings_structure_guard_typed_error_structure_assertions_are_child_owned",
    "runtime_15_typed_error_structure_assertions_children_are_child_owned",
    "runtime_15_typed_error_structure_assertions_guard_folder_backed_status_is_current",
    "Cargo gate deferred",
];
