pub(in super::super) const MOVED_GUARD_ABSENCE_CHILD_OWNER_SPLIT: &[&str] = &[
    "runtime_15_typed_error_structure_moved_guard_absence_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure moved-guard absence child-owner split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence.rs",
    "runtime_15_typed_error_structure_moved_guard_absence_is_child_owner",
    "runtime_15_typed_error_structure_assertions_are_child_owner",
    "runtime_15_code_review_findings_typed_error_structure_guard_is_child_owner",
    "runtime_15_code_review_findings_structure_guard_children_are_mounted",
    "47 typed-error review guards",
    "Cargo gate deferred",
];

pub(in super::super) const MOVED_GUARD_ABSENCE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_typed_error_moved_guard_absence_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error moved-guard absence guard folder-backed split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/preserved_guards.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/path_anchors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/status_mirrors.rs",
    "runtime_15_typed_error_structure_moved_guard_absence_is_child_owner",
    "runtime_15_typed_error_moved_guard_absence_preserved_guards_are_child_owned",
    "runtime_15_typed_error_moved_guard_absence_parent_backflow_guards_are_child_owned",
    "runtime_15_typed_error_moved_guard_absence_path_anchors_are_child_owned",
    "runtime_15_typed_error_moved_guard_absence_children_line_budgets_are_current",
    "runtime_15_typed_error_moved_guard_absence_guard_folder_backed_status_is_current",
    "Cargo gate deferred",
];

pub(in super::super) const MOVED_GUARD_ABSENCE_PARENT_BACKFLOW_CHILD_SPLIT: &[&str] = &[
    "runtime_15_typed_error_moved_guard_absence_parent_backflow_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error moved-guard absence parent-backflow child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/parent_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/guard_names.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/guard_body.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/parent_backflow/status_current.rs",
    "runtime_15_typed_error_moved_guard_absence_parent_backflow_is_child_backed",
    "runtime_15_typed_error_moved_guard_absence_parent_backflow_status_is_current",
    "Cargo gate deferred",
];

pub(in super::super) const MOVED_GUARD_ABSENCE_ROOT_INVENTORY_CHILD_SPLIT: &[&str] = &[
    "runtime_15_typed_error_moved_guard_absence_root_inventory_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error moved-guard absence root inventory child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_inventory.rs",
    "runtime_15_typed_error_moved_guard_absence_root_inventory_is_child_owned",
    "Cargo gate deferred",
];

pub(in super::super) const MOVED_GUARD_ABSENCE_CHILD_OWNER_ROUTE_SPLIT: &[&str] = &[
    "runtime_15_typed_error_moved_guard_absence_child_owner_route_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error moved-guard absence child-owner route split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/child_ownership_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/moved_guard_absence/root_sources.rs",
    "runtime_15_typed_error_structure_moved_guard_absence_is_child_owner",
    "runtime_15_typed_error_moved_guard_absence_child_owner_route_split_status_is_current",
    "Cargo gate deferred",
];
