pub(in super::super) const NATIVE_PLUGIN_LOADER_GUARD_CHILD_OWNER_SPLIT: &[&str] = &[
    "runtime_15_typed_error_native_plugin_loader_structure_guard_child_owner_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error native plugin loader structure guard child-owner split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/abi_surfaces.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader/live_host/replay_and_runtime.rs",
    "runtime_15_typed_error_native_plugin_loader_structure_is_child_owner",
    "runtime_15_typed_error_structure_assertions_are_child_owner",
    "runtime_15_code_review_findings_typed_error_structure_guard_is_child_owner",
    "47 typed-error review guards",
    "Cargo gate deferred",
];

pub(in super::super) const NATIVE_PLUGIN_LOADER_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_typed_error_native_plugin_loader_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error native plugin loader structure guard folder-backed split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/status_mirrors.rs",
    "runtime_15_typed_error_native_plugin_loader_structure_is_child_owner",
    "runtime_15_typed_error_native_plugin_loader_structure_guard_is_folder_backed",
    "runtime_15_typed_error_native_plugin_loader_structure_guard_folder_backed_status_is_current",
    "Cargo gate deferred",
];

pub(in super::super) const NATIVE_PLUGIN_LOADER_ROUTES_CHILD_SPLIT: &[&str] = &[
    "runtime_15_typed_error_native_plugin_loader_routes_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error native plugin loader routes child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/top_level.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/abi_surfaces.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/plugin_descriptor.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/live_host.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/lifecycle_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/replay_runtime.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/manifest_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/status_current.rs",
    "runtime_15_typed_error_native_plugin_loader_structure_guard_is_folder_backed",
    "runtime_15_typed_error_native_plugin_loader_routes_are_child_backed",
    "runtime_15_typed_error_native_plugin_loader_routes_child_split_status_is_current",
    "Cargo gate deferred",
];

pub(in super::super) const NATIVE_PLUGIN_LOADER_ROUTES_SOURCE_HELPER_CHILD_SPLIT: &[&str] = &[
    "runtime_15_typed_error_native_plugin_loader_routes_source_helper_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error native plugin loader routes source helper child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/source_helper_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/source_helper_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/routes/sources.rs",
    "runtime_15_typed_error_native_plugin_loader_routes_source_helpers_are_child_backed",
    "runtime_15_typed_error_native_plugin_loader_routes_source_helper_status_is_current",
    "Cargo gate deferred",
];

pub(in super::super) const NATIVE_PLUGIN_LOADER_SOURCE_HELPER_CHILD_SPLIT: &[&str] = &[
    "runtime_15_typed_error_native_plugin_loader_source_helper_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error native plugin loader source helper child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/child_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/metadata.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/source_helper_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/source_helper_status.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners/structure_assertions/native_plugin_loader/sources.rs",
    "runtime_15_typed_error_native_plugin_loader_structure_is_child_owner",
    "runtime_15_typed_error_native_plugin_loader_source_helpers_are_child_backed",
    "runtime_15_typed_error_native_plugin_loader_source_helper_status_is_current",
    "Cargo gate deferred",
];
