[package]
name = "zircon_plugin_ui_document_importer_runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "UI document importer runtime plugin package for Zircon."

[dependencies]
zircon_plugin_sdk = { workspace = true, features = ["runtime"] }
zircon_runtime = { workspace = true, features = ["ui"] }
zircon_runtime_interface = { workspace = true }
