pub(in super::super) struct ProjectedWorldSpace {
    pub(in super::super) enabled: bool,
    pub(in super::super) position_x: f32,
    pub(in super::super) position_y: f32,
    pub(in super::super) position_z: f32,
    pub(in super::super) rotation_x: f32,
    pub(in super::super) rotation_y: f32,
    pub(in super::super) rotation_z: f32,
    pub(in super::super) scale_x: f32,
    pub(in super::super) scale_y: f32,
    pub(in super::super) scale_z: f32,
    pub(in super::super) width: f32,
    pub(in super::super) height: f32,
    pub(in super::super) pixels_per_meter: f32,
    pub(in super::super) billboard: bool,
    pub(in super::super) depth_test: bool,
    pub(in super::super) render_order: i32,
    pub(in super::super) camera_target: String,
}
