use super::MirrorDocsSources;

impl MirrorDocsSources {
    pub(in super::super) fn performance_guard_sources(&self) -> Vec<&'static str> {
        vec![
            self.performance_guard,
            self.artifact_render_diagnostics_guard,
            self.artifact_render_diagnostics_artifact_cache_payload_guard,
            self.artifact_render_diagnostics_render_product_diagnostics_guard,
            self.artifact_render_diagnostics_split_layout_guard,
            self.artifact_render_diagnostics_split_layout_route_guard,
            self.artifact_render_diagnostics_split_layout_source_inventory_guard,
            self.artifact_render_diagnostics_split_layout_sources_guard,
            self.artifact_render_diagnostics_split_layout_status_docs_guard,
            self.hotspot_inventory_guard,
            self.hotspot_inventory_ecs_extract_guard,
            self.hotspot_inventory_ecs_extract_asset_animation_guard,
            self.hotspot_inventory_ecs_extract_extract_cache_guard,
            self.hotspot_inventory_ecs_extract_frame_diagnostics_guard,
            self.hotspot_inventory_ecs_extract_query_change_guard,
            self.hotspot_inventory_ecs_extract_split_layout_guard,
            self.hotspot_inventory_ecs_extract_split_layout_route_guard,
            self.hotspot_inventory_ecs_extract_split_layout_source_inventory_guard,
            self.hotspot_inventory_ecs_extract_split_layout_sources_guard,
            self.hotspot_inventory_ecs_extract_split_layout_status_docs_guard,
            self.hotspot_inventory_evidence_gate_guard,
            self.hotspot_inventory_profiling_trace_guard,
            self.hotspot_inventory_sources_guard,
            self.hotspot_inventory_split_layout_guard,
            self.owner_budget_guard,
            self.owner_budget_child_routes_guard,
            self.owner_budget_large_file_guard,
            self.owner_budget_line_budgets_guard,
            self.owner_budget_mirror_docs_guard,
            self.owner_budget_mirror_docs_audit_wiring_guard,
            self.owner_budget_mirror_docs_doc_mirrors_guard,
            self.owner_budget_mirror_docs_performance_guard,
            self.owner_budget_mirror_docs_source_inventory_guard,
            self.owner_budget_mirror_docs_sources_guard,
            self.owner_budget_mirror_docs_sources_assertions_guard,
            self.owner_budget_mirror_docs_sources_load_guard,
            self.owner_budget_mirror_docs_sources_views_guard,
            self.owner_budget_mirror_docs_split_layout_guard,
            self.owner_budget_parent_routes_guard,
            self.owner_budget_source_inventory_guard,
            self.owner_budget_sources_guard,
            self.owner_budget_sources_load_guard,
            self.owner_budget_split_layout_guard,
            self.owner_budget_status_docs_guard,
            self.owner_budget_virtual_geometry_debug_snapshot_guard,
            self.scene_project_splits_guard,
            self.scene_project_splits_dynamic_session_event_guard,
            self.scene_project_splits_project_io_guard,
            self.scene_project_splits_scene_asset_guard,
            self.scene_project_splits_split_layout_guard,
            self.scene_project_splits_split_layout_route_guard,
            self.scene_project_splits_split_layout_source_inventory_guard,
            self.scene_project_splits_split_layout_sources_guard,
            self.scene_project_splits_split_layout_status_docs_guard,
            self.submit_context_guard,
            self.submit_context_camera_loop_guard,
            self.submit_context_feedback_sidebands_guard,
            self.submit_context_source_extract_payloads_guard,
            self.submit_context_sources_guard,
            self.submit_context_split_layout_guard,
            self.submit_context_status_docs_guard,
            self.submit_error_paths_guard,
            self.cargo_gate_guard,
        ]
    }

    pub(in super::super) fn mirror_docs(&self) -> [(&'static str, &'static str); 1] {
        [("Runtime 07 numbered archive", self.runtime_07_archive)]
    }
}
