pub(in super::super) const EXPECTED_SLICE_BUDGET_SOURCE_PATHS: &[(&str, &str)] = &[
    (
        "plan_status/status_output_tables/expected_slices/status/runtime_15.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15.rs",
    ),
    (
        "plan_status/status_output_tables/expected_slices/date/runtime_15.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15.rs",
    ),
    (
        "status/runtime_15/foundation.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/foundation.rs",
    ),
    (
        "status/runtime_15/naming_boundary.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/naming_boundary.rs",
    ),
    (
        "status/runtime_15/naming_boundary/core_bootstrap.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/naming_boundary/core_bootstrap.rs",
    ),
    (
        "status/runtime_15/naming_boundary/scene_asset_runtime.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/naming_boundary/scene_asset_runtime.rs",
    ),
    (
        "status/runtime_15/naming_boundary/plugin_ui_platform.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/naming_boundary/plugin_ui_platform.rs",
    ),
    (
        "status/runtime_15/naming_boundary/render_graphics.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/naming_boundary/render_graphics.rs",
    ),
    (
        "status/runtime_15/m4_surface_cleanup.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m4_surface_cleanup.rs",
    ),
    (
        "status/runtime_15/m3_structure_support.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support.rs",
    ),
    (
        "status/runtime_15/m3_structure_support/review_guard_maps.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps.rs",
    ),
    (
        "status/runtime_15/m3_structure_support/naming_guard_maps.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/naming_guard_maps.rs",
    ),
    (
        "status/runtime_15/m3_structure_support/status_support_maps.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps.rs",
    ),
    (
        "date/runtime_15/foundation.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/foundation.rs",
    ),
    (
        "date/runtime_15/naming_boundary.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/naming_boundary.rs",
    ),
    (
        "date/runtime_15/naming_boundary/core_bootstrap.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/naming_boundary/core_bootstrap.rs",
    ),
    (
        "date/runtime_15/naming_boundary/scene_asset_runtime.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/naming_boundary/scene_asset_runtime.rs",
    ),
    (
        "date/runtime_15/naming_boundary/plugin_ui_platform.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/naming_boundary/plugin_ui_platform.rs",
    ),
    (
        "date/runtime_15/naming_boundary/render_graphics.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/naming_boundary/render_graphics.rs",
    ),
    (
        "date/runtime_15/m4_surface_cleanup.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m4_surface_cleanup.rs",
    ),
    (
        "date/runtime_15/m3_structure_support.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support.rs",
    ),
    (
        "date/runtime_15/m3_structure_support/review_guard_maps.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps.rs",
    ),
    (
        "date/runtime_15/m3_structure_support/naming_guard_maps.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/naming_guard_maps.rs",
    ),
    (
        "date/runtime_15/m3_structure_support/status_support_maps.rs",
        "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/status_support_maps.rs",
    ),
];
