import { HubTokens, HubVisualSpec } from "tokens.slint";
import {
    Drawer as MaterialDrawer,
    MaterialStyleMetrics,
    MaterialWindow,
    ModalDrawer as MaterialModalDrawer,
} from "material_bridge.slint";

export component HubDrawer inherits MaterialDrawer {
    in property <length> drawer-width: MaterialStyleMetrics.size_360;

    min-width: root.drawer-width;
}

export component HubModalDrawer inherits MaterialModalDrawer {
    in property <length> drawer-width: MaterialStyleMetrics.size_360;

    width: root.drawer-width;
}

export component HubWindowView inherits MaterialWindow {
    title: "Zircon Hub";
    no-frame: true;
    resize-border-width: HubTokens.window-resize-border;
    min-width: HubTokens.window-min-width;
    min-height: HubTokens.window-min-height;
    preferred-width: HubTokens.window-preferred-width;
    preferred-height: HubTokens.window-preferred-height;
    background: HubVisualSpec.page-background;
    disable-hover: false;
}
