use super::sources::*;

#[test]
fn runtime_05_dynamic_scene_asset_reload_selection_and_status_anchors_stay_visible() {
    for anchor in [
        "dynamic_scene_asset_reload_supersedes_older_pending_scene_revision",
        "DynamicSceneAssetReloadQueue::new(fixture.project.clone(), events)",
        "fixture.register_ready_revision(\"scene-v1\")",
        "fixture.register_ready_revision(\"scene-v2\")",
        "drain_until_events(&mut queue, &scheduler, 2)",
        "drain.superseded_pending[0].event().revision(), 1",
        "pending.pending[0].event().revision(), 2",
        "ready.ready[0].event().revision(), 2",
        "ready.spawn_ready_into(&mut world)",
        "world.node_records().len(), 2",
        "dynamic_scene_asset_reload_skips_removed_and_reload_failed_events",
        "DynamicSceneAssetReloadSkipReason::ReloadFailed",
        "DynamicSceneAssetReloadSkipReason::Removed",
        "dynamic_scene_asset_reload_tick_into_applies_ready_payload_to_world",
        "queue.tick_into(&scheduler, &mut world)",
        "frame.apply.applied[0].event().revision(), 1",
        "dynamic_scene_asset_reload_tick_into_level_applies_ready_payload_to_level_world",
        "queue.tick_into_level(&scheduler, &level)",
        "level.with_world(|world| world.node_records().len()), 2",
        "dynamic_scene_asset_reload_renamed_scene_event_schedules_new_project_uri",
        "AssetEventKind::Renamed",
        ".rename(&fixture.uri, renamed_uri.clone())",
        "pending.pending[0].event().previous_locator()",
        "frame.apply.applied[0].event().locator(), Some(&renamed_uri)",
        "fn drain_until_events(",
        "fn wait_for_pending(",
        "struct SceneReloadFixture",
        "unique_temp_project_root(label)",
        "create_test_project(&root)",
    ] {
        assert!(
            ASSET_RELOAD_BEHAVIOR_SOURCE.contains(anchor),
            "Runtime 05 asset reload behavior source should keep anchor `{anchor}`"
        );
    }
    for anchor in [
        "runtime_session_archive_selector_resolves_in_memory_slots",
        "RuntimeSessionSlotSelector::latest_updated_with_tag(",
        "latest_manual.selected_slot_id, \"manual-new\"",
        "RuntimeSessionArchiveError::MissingSlot",
        "runtime_session_archive_selected_retention_protects_resolved_slot",
        "preview_prune_slots_with_tag_and_selected_protection(",
        "prune_slots_with_tag_and_selected_protection(",
        "runtime_session_archive_selected_path_query_and_remove_are_atomic",
        "RuntimeSessionArchive::select_slot_from_path(",
        "RuntimeSessionArchive::remove_selected_slot_at_path_atomically(",
        "runtime_session_archive_selected_metadata_update_targets_resolved_slot",
        "update_selected_slot_metadata(",
        "runtime_session_archive_selected_transfer_helpers_use_resolved_slots",
        "copy_selected_slot(",
        "selected_single_slot_archive(",
        "import_selected_slot_from_archive_with_metadata(",
        "runtime_session_archive_selected_single_slot_export_to_path_is_atomic",
        "save_selected_single_slot_archive_to_path_atomically(",
        "runtime_session_archive_selected_restore_apply_and_diff_use_resolved_slots",
        "restore_selected_slot_to_empty_world(",
        "restore_selected_slot_into_level(",
        "apply_selected_slot_to_level(",
        "runtime_session_archive_selected_path_restore_apply_and_diff_use_resolved_slots",
        "restore_selected_slot_from_path_to_empty_world(",
        "diff_selected_slot_from_path_with_level(",
        "apply_selected_slot_from_path_to_level(",
        "temporary_archive_leftovers(",
    ] {
        assert!(
            SELECTION_BEHAVIOR_SOURCE.contains(anchor),
            "Runtime 05 selection behavior source should keep anchor `{anchor}`"
        );
    }
    for anchor in [
        "runtime_session_archive_world_capture_preview_commit_parity_rustfmt_passed_cargo_deferred_tests_deferred",
        "world capture commit delegates to preview-generated slot",
        "runtime_session_archive_world_capture_commit_matches_preview_generated_slot",
        "runtime_session_archive_level_capture_preview_from_level_semantics_rustfmt_passed_cargo_deferred_tests_deferred",
        "level capture preview preserves RuntimeSessionSlot::from_level semantics",
        "runtime_session_archive_level_capture_preview_preserves_from_level_semantics",
        "runtime_session_archive_capture_retention_shared_preview_projection_rustfmt_passed_cargo_deferred_tests_deferred",
        "capture-retention keeps shared preview report projection",
        "runtime_session_archive_capture_retention_reuses_shared_preview_report_projection",
        "runtime_session_archive_full_save_preview_no_write_targets_rustfmt_passed_cargo_deferred_tests_deferred",
        "missing-target、existing-file、non-file-target 与 no-write/no-temp 行为锚点",
        "runtime_session_archive_preview_save_to_path_reports_targets_without_writing_files",
        "runtime_session_archive_target_parent_file_preview_rustfmt_passed_cargo_deferred_tests_deferred",
        "parent-file target preview 行为锚点",
        "target parent-file preflight parity",
        "runtime_session_archive_preview_save_to_path_rejects_parent_file_without_writes",
        "runtime_session_archive_capture_retention_transaction_behavior_rustfmt_passed_cargo_deferred_tests_deferred",
        "capture-retention protects captured slot",
        "preview does not mutate archive/path",
        "tag retention prunes only tagged bucket",
        "runtime_session_archive_preview_capture_retention_prunes_clone_without_mutating_archive",
        "runtime_session_archive_capture_retention_protects_captured_slot_before_pruning",
        "runtime_session_archive_selected_retention_behavior_rustfmt_passed_cargo_deferred_tests_deferred",
        "selected retention protects latest/tagged slot",
        "tag selected protection outside tag bucket is harmless",
        "path selected retention preview does not write archive",
        "runtime_session_archive_selected_retention_protects_latest_tagged_slot",
        "runtime_session_archive_tag_selected_retention_ignores_protection_outside_bucket",
        "runtime_session_archive_path_selected_retention_preview_does_not_write_archive",
        "runtime_session_archive_mutation_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_05_dynamic_scene_mutation_behavior_anchors_rustfmt_passed_focused_cargo_timeout_no_result_scene_gate_pending",
        "runtime_session_archive_named_mutation_commits_preserve_preview_boundaries",
        "runtime_session_archive_selected_mutations_resolve_targets_before_committing",
        "runtime_session_archive_selected_path_mutations_preview_and_commit_atomically",
        "selected mutation selector resolution",
        "selected path-level preview no-write behavior",
        "runtime_session_archive_selection_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_05_dynamic_scene_slot_selector_behavior_anchors_rustfmt_passed_cargo_deferred_scene_gate_pending",
        "runtime_05_dynamic_scene_selected_transfer_behavior_anchors_rustfmt_passed_cargo_deferred_scene_gate_pending",
        "runtime_05_dynamic_scene_selected_restore_apply_diff_behavior_anchors_rustfmt_passed_cargo_deferred_scene_gate_pending",
        "runtime_session_archive_selector_resolves_in_memory_slots",
        "runtime_session_archive_selected_transfer_helpers_use_resolved_slots",
        "runtime_session_archive_selected_restore_apply_and_diff_use_resolved_slots",
        "runtime_session_archive_selected_path_restore_apply_and_diff_use_resolved_slots",
        "runtime_session_archive_selected_capture_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_05_dynamic_scene_selected_capture_behavior_anchors_rustfmt_passed_cargo_deferred_scene_gate_pending",
        "selected capture behavior anchors",
        "runtime_session_archive_selected_capture_targets_resolved_slot_and_preserves_metadata",
        "runtime_session_archive_selected_capture_to_path_previews_and_prunes_atomically",
        "runtime_session_archive_merge_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_05_dynamic_scene_merge_behavior_anchors_rustfmt_passed_cargo_deferred_scene_gate_pending",
        "dynamic scene merge behavior anchors",
        "runtime_session_archive_merge_preview_and_keep_existing_commit_are_side_effect_free",
        "runtime_session_archive_path_merge_preview_commit_and_same_path_guard_are_atomic",
        "runtime_session_archive_load_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_session_archive_load_from_path_code_check_passed_tests_deferred",
        "runtime_session_archive_restores_slot_from_path_to_empty_world",
        "runtime_session_archive_restores_slot_from_path_into_level_and_applies_metadata",
        "runtime_session_archive_applies_slot_from_path_to_live_world_and_level",
        "runtime_session_archive_path_load_helpers_report_missing_slot",
        "runtime_session_archive_query_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_session_archive_path_query_code_check_passed_tests_deferred",
        "runtime_session_archive_path_slot_summary_code_check_passed_tests_deferred",
        "runtime_session_archive_path_manifest_filter_code_static_passed_cargo_blocked_external_postprocess_drift_tests_deferred",
        "runtime_session_archive_path_slot_selection_code_static_passed_cargo_blocked_external_postprocess_drift_tests_deferred",
        "runtime_session_archive_path_retention_preview_code_static_passed_cargo_blocked_external_postprocess_drift_tests_deferred",
        "runtime_session_archive_loads_statistics_from_path",
        "runtime_session_archive_reads_slot_summaries_directly_from_path",
        "runtime_session_archive_diffs_slot_from_path_without_mutating_target",
        "runtime_session_archive_previews_path_retention_without_saving",
        "runtime_session_archive_selects_updated_slots_directly_from_path",
        "runtime_session_archive_filters_manifest_summaries_directly_from_path",
        "runtime_session_archive_path_management_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_session_archive_path_management_code_check_passed_tests_deferred",
        "runtime_session_archive_slot_mutation_preview_code_check_passed_tests_deferred",
        "runtime_session_archive_copy_preview_code_check_passed_tests_deferred",
        "runtime_session_archive_single_slot_import_preview_code_check_passed_tests_deferred",
        "runtime_session_archive_source_path_single_slot_import_code_check_passed_tests_deferred",
        "runtime_session_archive_loaded_single_slot_save_code_check_passed_tests_deferred",
        "runtime_session_archive_single_slot_export_code_check_passed_tests_deferred",
        "runtime_session_archive_merge_preview_code_check_passed_tests_deferred",
        "runtime_session_archive_source_path_merge_code_check_passed_tests_deferred",
        "runtime_session_archive_renames_slot_at_path_atomically",
        "runtime_session_archive_previews_slot_mutations_without_mutating_archive",
        "runtime_session_archive_copies_slot_at_path_atomically",
        "runtime_session_archive_previews_slot_copy_from_path_without_mutating_archive",
        "runtime_session_archive_imports_single_slot_from_path_at_path_atomically",
        "runtime_session_archive_previews_single_slot_import_from_path_without_mutating_archives",
        "runtime_session_archive_saves_single_slot_archive_from_path_atomically",
        "runtime_session_archive_saves_single_slot_archive_from_memory_atomically",
        "runtime_session_archive_merges_archive_from_path_at_path_atomically",
        "runtime_session_archive_previews_merge_from_path_without_mutating_archives",
        "runtime_05_dynamic_scene_asset_reload_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "runtime_05_dynamic_scene_asset_reload_behavior_anchors_rustfmt_passed_cargo_deferred_active_cargo_lane_scene_gate_pending",
        "runtime_05_dynamic_scene_asset_reload_frame_entrypoint_anchors_rustfmt_passed_cargo_deferred_active_cargo_lane_scene_gate_pending",
        "runtime_05_dynamic_scene_asset_reload_renamed_event_anchors_rustfmt_passed_cargo_deferred_active_cargo_lane_scene_gate_pending",
        "dynamic scene asset reload behavior anchors",
        "dynamic scene asset reload frame entrypoint anchors",
        "dynamic scene asset reload renamed event anchors",
        "dynamic_scene_asset_reload_supersedes_older_pending_scene_revision",
        "dynamic_scene_asset_reload_skips_removed_and_reload_failed_events",
        "dynamic_scene_asset_reload_tick_into_applies_ready_payload_to_world",
        "dynamic_scene_asset_reload_tick_into_level_applies_ready_payload_to_level_world",
        "dynamic_scene_asset_reload_renamed_scene_event_schedules_new_project_uri",
    ] {
        assert!(
            RUNTIME_05_PLAN.contains(anchor),
            "Runtime 05 capture/save preview status should keep anchor `{anchor}`"
        );
    }
    for anchor in [
        "Runtime session archive world capture preview/commit parity",
        "runtime_session_archive_world_capture_commit_matches_preview_generated_slot",
        "preview-generated slot",
        "Runtime session archive level capture preview/from_level semantics",
        "runtime_session_archive_level_capture_preview_preserves_from_level_semantics",
        "RuntimeSessionSlot::from_level semantics",
        "Runtime session archive capture-retention shared preview projection",
        "runtime_session_archive_capture_retention_reuses_shared_preview_report_projection",
        "report.capture",
        "Runtime session archive full-save preview target/no-write behavior",
        "runtime_session_archive_preview_save_to_path_reports_targets_without_writing_files",
        "RuntimeSessionArchiveSavePreviewReport",
        "no-write/no-temp",
        "Runtime session archive target parent-file preview behavior",
        "runtime_session_archive_preview_save_to_path_rejects_parent_file_without_writes",
        "parent-file target preview",
        "Runtime session archive capture-retention transaction behavior",
        "runtime_session_archive_preview_capture_retention_prunes_clone_without_mutating_archive",
        "runtime_session_archive_capture_retention_protects_captured_slot_before_pruning",
        "captured slot protection",
        "Runtime session archive selected retention behavior anchors",
        "runtime_session_archive_selected_retention_protects_latest_tagged_slot",
        "selected latest tagged slot protection",
        "runtime_session_archive_tag_selected_retention_ignores_protection_outside_bucket",
        "tag selected protection outside tag bucket behavior",
        "runtime_session_archive_path_selected_retention_preview_does_not_write_archive",
        "path selected retention preview no-write/no-temp behavior",
        "Runtime session archive mutation behavior anchors",
        "runtime_session_archive_named_mutation_commits_preserve_preview_boundaries",
        "runtime_session_archive_selected_mutations_resolve_targets_before_committing",
        "runtime_session_archive_selected_path_mutations_preview_and_commit_atomically",
        "Runtime session archive selection behavior static guard",
        "runtime_session_archive_selector_resolves_in_memory_slots",
        "runtime_session_archive_selected_transfer_helpers_use_resolved_slots",
        "runtime_session_archive_selected_restore_apply_and_diff_use_resolved_slots",
        "runtime_session_archive_selected_path_restore_apply_and_diff_use_resolved_slots",
        "Runtime session archive selected capture behavior static guard",
        "Runtime session archive selected capture behavior anchors",
        "runtime_session_archive_selected_capture_targets_resolved_slot_and_preserves_metadata",
        "runtime_session_archive_selected_capture_to_path_previews_and_prunes_atomically",
        "Runtime session archive merge behavior static guard",
        "Runtime session archive merge behavior anchors",
        "runtime_session_archive_merge_preview_and_keep_existing_commit_are_side_effect_free",
        "runtime_session_archive_path_merge_preview_commit_and_same_path_guard_are_atomic",
        "Runtime session archive load behavior static guard",
        "runtime_session_archive_restores_slot_from_path_to_empty_world",
        "runtime_session_archive_restores_slot_from_path_into_level_and_applies_metadata",
        "runtime_session_archive_applies_slot_from_path_to_live_world_and_level",
        "runtime_session_archive_path_load_helpers_report_missing_slot",
        "Runtime session archive query behavior static guard",
        "runtime_session_archive_loads_statistics_from_path",
        "runtime_session_archive_reads_slot_summaries_directly_from_path",
        "runtime_session_archive_diffs_slot_from_path_without_mutating_target",
        "runtime_session_archive_previews_path_retention_without_saving",
        "runtime_session_archive_selects_updated_slots_directly_from_path",
        "runtime_session_archive_filters_manifest_summaries_directly_from_path",
        "Runtime session archive path-management behavior static guard",
        "runtime_session_archive_renames_slot_at_path_atomically",
        "runtime_session_archive_previews_slot_mutations_without_mutating_archive",
        "runtime_session_archive_copies_slot_at_path_atomically",
        "runtime_session_archive_previews_slot_copy_from_path_without_mutating_archive",
        "runtime_session_archive_imports_single_slot_from_path_at_path_atomically",
        "runtime_session_archive_previews_single_slot_import_from_path_without_mutating_archives",
        "runtime_session_archive_saves_single_slot_archive_from_path_atomically",
        "runtime_session_archive_saves_single_slot_archive_from_memory_atomically",
        "runtime_session_archive_merges_archive_from_path_at_path_atomically",
        "runtime_session_archive_previews_merge_from_path_without_mutating_archives",
        "Dynamic scene asset reload behavior static guard",
        "runtime_05_dynamic_scene_asset_reload_behavior_static_guard_rustfmt_passed_cargo_deferred_tests_deferred",
        "Dynamic scene asset reload behavior anchors",
        "dynamic_scene_asset_reload_supersedes_older_pending_scene_revision",
        "dynamic_scene_asset_reload_skips_removed_and_reload_failed_events",
        "dynamic_scene_asset_reload_tick_into_applies_ready_payload_to_world",
        "dynamic_scene_asset_reload_tick_into_level_applies_ready_payload_to_level_world",
        "dynamic_scene_asset_reload_renamed_scene_event_schedules_new_project_uri",
    ] {
        assert!(
            DYNAMIC_SCENE_DOC.contains(anchor),
            "dynamic-scene module docs should keep capture/save preview semantics anchor `{anchor}`"
        );
    }
}
