use crate::core::framework::render::{
    GeometrySourceDescriptor, RenderShaderDefinitionValue, ShaderFeatureBits, ShaderPassType,
};

use super::include_registry::{
    geometry_source_include_for, gpu_scene_include, scene_runtime_include,
    standard_pbr_shading_include, surface_types_include, ShaderTemplateInclude,
    ShaderTemplateIncludeRegistry,
};
use super::pass_specialization::{pass_template_for, MATERIAL_SHADER_TEMPLATE_REVISION};

const MATERIAL_SURFACE_ENTRY_POINT: &str = "zr_material_surface";
const RESERVED_MATERIAL_SYMBOL_PREFIXES: &[&str] = &["zr_", "fetch_", "shade_"];

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct MaterialShaderTemplateRequest {
    pub(crate) geometry_source: GeometrySourceDescriptor,
    pub(crate) pass_type: ShaderPassType,
    pub(crate) features: ShaderFeatureBits,
    pub(crate) material_surface_source: String,
    pub(crate) material_surface_entry: String,
}

impl MaterialShaderTemplateRequest {
    pub(crate) fn new(
        geometry_source: GeometrySourceDescriptor,
        pass_type: ShaderPassType,
        material_surface_source: impl Into<String>,
        material_surface_entry: impl Into<String>,
    ) -> Self {
        Self {
            geometry_source,
            pass_type,
            features: ShaderFeatureBits::default(),
            material_surface_source: material_surface_source.into(),
            material_surface_entry: material_surface_entry.into(),
        }
    }

    pub(crate) fn with_features(mut self, features: ShaderFeatureBits) -> Self {
        self.features = features;
        self
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct MaterialShaderTemplateAssembly {
    pub(crate) wgsl_source: String,
    pub(crate) include_tokens: Vec<String>,
    pub(crate) include_content_hashes: Vec<String>,
    pub(crate) template_revision: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum ShaderTemplateAssemblyError {
    UnknownGeometryInclude {
        token: String,
    },
    MissingSurfaceEntry {
        entry: String,
    },
    DuplicateSurfaceEntry {
        entry: String,
    },
    ReservedMaterialSymbol {
        symbol: String,
        prefix: &'static str,
    },
}

pub(crate) fn assemble_material_shader_template(
    request: MaterialShaderTemplateRequest,
) -> Result<MaterialShaderTemplateAssembly, ShaderTemplateAssemblyError> {
    let pass_template = pass_template_for(request.pass_type, request.features);
    let mut registry = ShaderTemplateIncludeRegistry::default();
    let mut chunks = Vec::new();

    chunks.push(format_defines_header(
        &request.geometry_source,
        request.features,
    ));

    push_include_chunk(&mut registry, &mut chunks, scene_runtime_include());
    push_include_chunk(&mut registry, &mut chunks, gpu_scene_include());
    push_include_chunk(&mut registry, &mut chunks, surface_types_include());

    let geometry_include =
        geometry_source_include_for(&request.geometry_source).ok_or_else(|| {
            ShaderTemplateAssemblyError::UnknownGeometryInclude {
                token: request.geometry_source.wgsl_include.clone(),
            }
        })?;
    push_include_chunk(&mut registry, &mut chunks, geometry_include);

    for include in pass_template.support_includes.iter().cloned() {
        push_include_chunk(&mut registry, &mut chunks, include);
    }

    if pass_template.requires_shading_include {
        push_include_chunk(&mut registry, &mut chunks, standard_pbr_shading_include());
    }

    if pass_template.requires_material_surface {
        chunks.push(rename_material_surface_entry(
            &request.material_surface_source,
            &request.material_surface_entry,
        )?);
    }

    push_include_chunk(&mut registry, &mut chunks, pass_template.include);

    Ok(MaterialShaderTemplateAssembly {
        wgsl_source: chunks.join("\n\n"),
        include_tokens: registry.include_tokens(),
        include_content_hashes: registry.content_hashes(),
        template_revision: MATERIAL_SHADER_TEMPLATE_REVISION.to_string(),
    })
}

pub(super) fn push_include_chunk(
    registry: &mut ShaderTemplateIncludeRegistry,
    chunks: &mut Vec<String>,
    include: ShaderTemplateInclude,
) {
    chunks.push(format!("// include: {}\n{}", include.token, include.source));
    registry.push(include);
}

pub(super) fn format_defines_header(
    geometry_source: &GeometrySourceDescriptor,
    features: ShaderFeatureBits,
) -> String {
    let mut lines = vec![
        "// generated by zircon shader template assembler".to_string(),
        format!(
            "const ZR_GEOMETRY_SOURCE_TOKEN: u32 = {};",
            geometry_source.id.value()
        ),
        format!(
            "const ZR_FEATURE_ALPHA_TEST: bool = {};",
            features.contains(ShaderFeatureBits::ALPHA_TEST)
        ),
        format!(
            "const ZR_FEATURE_RECEIVE_SHADOWS: bool = {};",
            features.contains(ShaderFeatureBits::RECEIVE_SHADOWS)
        ),
        format!(
            "const ZR_FEATURE_DOUBLE_SIDED: bool = {};",
            features.contains(ShaderFeatureBits::DOUBLE_SIDED)
        ),
    ];
    for define in &geometry_source.shader_defines {
        lines.push(format_definition_value(define));
    }
    lines.join("\n")
}

fn format_definition_value(define: &RenderShaderDefinitionValue) -> String {
    let name = define.normalized_name();
    match define {
        RenderShaderDefinitionValue::Bool { value, .. } => {
            format!("const {name}: bool = {value};")
        }
        RenderShaderDefinitionValue::Int { value, .. } => {
            format!("const {name}: i32 = {value};")
        }
        RenderShaderDefinitionValue::UInt { value, .. } => {
            format!("const {name}: u32 = {value}u;")
        }
    }
}

pub(super) fn rename_material_surface_entry(
    source: &str,
    entry: &str,
) -> Result<String, ShaderTemplateAssemblyError> {
    reject_reserved_material_symbols(source)?;

    let entry = entry.trim();
    let needle = format!("fn {entry}(");
    let count = source.match_indices(&needle).count();
    if count == 0 {
        return Err(ShaderTemplateAssemblyError::MissingSurfaceEntry {
            entry: entry.to_string(),
        });
    }
    if count > 1 {
        return Err(ShaderTemplateAssemblyError::DuplicateSurfaceEntry {
            entry: entry.to_string(),
        });
    }
    Ok(source.replacen(&needle, &format!("fn {MATERIAL_SURFACE_ENTRY_POINT}("), 1))
}

fn reject_reserved_material_symbols(source: &str) -> Result<(), ShaderTemplateAssemblyError> {
    for symbol in declared_functions(source) {
        if let Some(prefix) = RESERVED_MATERIAL_SYMBOL_PREFIXES
            .iter()
            .copied()
            .find(|prefix| symbol.starts_with(prefix))
        {
            return Err(ShaderTemplateAssemblyError::ReservedMaterialSymbol {
                symbol: symbol.to_string(),
                prefix,
            });
        }
    }
    Ok(())
}

fn declared_functions(source: &str) -> impl Iterator<Item = &str> {
    source.lines().filter_map(|line| {
        let trimmed = line.trim_start();
        let rest = trimmed.strip_prefix("fn ")?;
        rest.split_once('(').map(|(name, _)| name.trim())
    })
}
