use super::*;

pub(super) const STATUS_SUPPORT_ROOT_ROW_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/runtime_15_status_support_row_data.rs",
        STATUS_SUPPORT_ROW_DATA_GUARD_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_paths.rs",
        ROOT_PATHS_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_paths/top_level_support.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/root_paths/top_level_support.rs",
        20,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_statuses.rs",
        ROOT_STATUSES_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_statuses/expected_slice.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/root_statuses/expected_slice.rs",
        40,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_child_rows/guard_children.rs",
        ROOT_GUARD_CHILDREN_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_status_support/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
];
