use super::super::super::super::super::scene_post_process_resources::ScenePostProcessResources;
use super::bind_group_entries::bind_group_entries;

#[allow(clippy::too_many_arguments)]
pub(in crate::graphics::scene::scene_renderer::post_process::resources) fn create_bind_group(
    resources: &ScenePostProcessResources,
    device: &wgpu::Device,
    post_process_params_buffer: &wgpu::Buffer,
    scene_color_view: &wgpu::TextureView,
    scene_depth_view: &wgpu::TextureView,
    motion_vector_neighbor_max_view: &wgpu::TextureView,
    scene_normal_view: &wgpu::TextureView,
    scene_material_view: Option<&wgpu::TextureView>,
    ao_view: &wgpu::TextureView,
    contact_shadow_view: &wgpu::TextureView,
    previous_scene_color_view: Option<&wgpu::TextureView>,
    previous_global_illumination_view: Option<&wgpu::TextureView>,
    previous_screen_space_reflection_history_view: Option<&wgpu::TextureView>,
    resolved_screen_space_reflection_history_view: Option<&wgpu::TextureView>,
    screen_space_reflection_specular_occlusion_view: Option<&wgpu::TextureView>,
    screen_space_reflection_depth_pyramid_view: Option<&wgpu::TextureView>,
    screen_space_reflection_reflection_pyramid_view: Option<&wgpu::TextureView>,
    screen_space_reflection_depth_pyramid_coarse_view: Option<&wgpu::TextureView>,
    screen_space_reflection_reflection_pyramid_coarse_view: Option<&wgpu::TextureView>,
    bloom_view: &wgpu::TextureView,
    depth_of_field_coc_view: &wgpu::TextureView,
    depth_of_field_bokeh_view: &wgpu::TextureView,
    effect_lut_view: &wgpu::TextureView,
    effect_lut_3d_view: &wgpu::TextureView,
    cluster_buffer: wgpu::BufferBinding<'_>,
    exposure_buffer: wgpu::BufferBinding<'_>,
) -> wgpu::BindGroup {
    let entries = bind_group_entries(
        resources,
        post_process_params_buffer,
        scene_color_view,
        scene_depth_view,
        motion_vector_neighbor_max_view,
        scene_normal_view,
        scene_material_view,
        ao_view,
        contact_shadow_view,
        previous_scene_color_view,
        previous_global_illumination_view,
        previous_screen_space_reflection_history_view,
        resolved_screen_space_reflection_history_view,
        screen_space_reflection_specular_occlusion_view,
        screen_space_reflection_depth_pyramid_view,
        screen_space_reflection_reflection_pyramid_view,
        screen_space_reflection_depth_pyramid_coarse_view,
        screen_space_reflection_reflection_pyramid_coarse_view,
        bloom_view,
        depth_of_field_coc_view,
        depth_of_field_bokeh_view,
        effect_lut_view,
        effect_lut_3d_view,
        cluster_buffer,
        exposure_buffer,
    );
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("zircon-post-process-bind-group"),
        layout: &resources.post_process_bind_group_layout,
        entries: &entries,
    })
}
