pub(crate) struct ScenePostProcessResources {
    pub(super) bloom_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) ssao_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) cluster_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) post_process_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) bloom_pipeline: wgpu::RenderPipeline,
    pub(super) ssao_pipeline: wgpu::ComputePipeline,
    pub(super) cluster_pipeline: wgpu::ComputePipeline,
    pub(super) post_process_pipeline: wgpu::RenderPipeline,
    pub(super) bloom_params_buffer: wgpu::Buffer,
    pub(super) ssao_params_buffer: wgpu::Buffer,
    pub(super) cluster_params_buffer: wgpu::Buffer,
    pub(super) post_process_params_buffer: wgpu::Buffer,
    pub(super) light_buffer: wgpu::Buffer,
    pub(super) hybrid_gi_probe_buffer: wgpu::Buffer,
    pub(super) reflection_probe_buffer: wgpu::Buffer,
    pub(super) black_texture_view: wgpu::TextureView,
    pub(super) white_texture_view: wgpu::TextureView,
}
