pub(super) const CHILD_OWNERSHIP_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_typed_error_child_ownership_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error child-ownership guard folder-backed split",
    "runtime_15_code_review_findings_typed_error_structure_guard_is_child_owner",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/review_guards.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/structure_subtree.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/moved_guard_absence.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/native_plugin_loader.rs",
    "runtime_15_typed_error_child_ownership_guard_is_folder_backed",
    "runtime_15_typed_error_child_ownership_guard_folder_backed_status_is_current",
    "assert_typed_error_review_guards_are_preserved",
    "assert_typed_error_structure_subtree_is_child_owned",
    "Cargo gate deferred",
];

pub(super) const CHILD_OWNERSHIP_ROOT_INVENTORY_CHILD_SPLIT: &[&str] = &[
    "runtime_15_typed_error_child_ownership_root_inventory_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error child-ownership root inventory child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership/root_inventory.rs",
    "runtime_15_typed_error_child_ownership_root_inventory_is_child_owned",
    "Cargo gate deferred",
];
