pub(super) const STRUCTURE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_typed_error_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure guard folder-backed split",
    "Runtime 15 M3 code review findings typed-error structure guard child-owner split",
    "runtime_15_code_review_findings_typed_error_structure_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/source_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/status_docs.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/convergence_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/native_plugin_loader.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/structure_assertions/moved_guard_absence.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/mod.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_records.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/ui_input.rs",
    "tests/runtime_absorption/code_review_findings/typed_error_convergence/native_plugin_loader.rs",
    "review_f5_texture_loader_uses_typed_error",
    "review_f5_mesh_loader_and_obj_decoder_use_typed_errors",
    "review_f5_asset_authoring_uses_typed_error",
    "review_f5_native_plugin_descriptor_abi_uses_typed_error",
    "review_f5_ui_surface_input_effects_use_typed_errors_before_rejected_reason_boundary",
    "review_f7_asset_artifact_errors_use_asset_import_error_sources",
    "runtime_15_code_review_findings_typed_error_structure_guard_is_child_owner",
    "runtime_15_typed_error_structure_guard_is_folder_backed",
    "runtime_15_typed_error_structure_guard_folder_backed_status_is_current",
    "runtime_15_typed_error_structure_guard_budgets_are_focused",
    "Cargo gate deferred",
];

pub(super) const STRUCTURE_GUARD_ROOT_INVENTORY_CHILD_SPLIT: &[&str] = &[
    "runtime_15_typed_error_structure_guard_root_inventory_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 typed-error structure guard root inventory child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/typed_error_owners/root_inventory.rs",
    "runtime_15_typed_error_structure_guard_root_inventory_is_child_owned",
    "Cargo gate deferred",
];
