pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[super::Slice] = &[
    (
        "Runtime 15 M3 review-guard typed-error rows guard folder-backed split",
        &[
            "runtime_15_review_guard_typed_error_rows_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/route_children.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/representative_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/export_chain.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/split_layout.rs",
            "runtime_15_review_guard_typed_error_rows_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard typed-error rows split-layout guard folder-backed split",
        &[
            "runtime_15_review_guard_typed_error_rows_split_layout_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/split_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/split_layout/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/split_layout/status_current.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/split_layout/budgets.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/typed_error_rows/split_layout/split_layout.rs",
            "runtime_15_review_guard_typed_error_rows_split_layout_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard typed-error status-doc row-data folder-backed split",
        &[
            "runtime_15_review_guard_typed_error_status_doc_row_data_folder_backed_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/status_docs.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/status_docs/foundation.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/status_docs/paths.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/status_docs/delegation.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/status_docs/status_maps.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/status_docs/status_mirrors.rs",
            "runtime_15_review_guard_typed_error_status_docs_row_data_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard typed-error status-doc guard folder-backed split",
        &[
            "runtime_15_review_guard_typed_error_status_doc_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_status_docs/row_routes.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_status_docs/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_status_docs/budgets.rs",
            "runtime_15_review_guard_typed_error_status_docs_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard typed-error structure-assertions row-data folder-backed split",
        &[
            "runtime_15_review_guard_typed_error_structure_assertions_row_data_folder_backed_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/structure_assertions.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/structure_assertions/foundation.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/structure_assertions/convergence_mounts.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/structure_assertions/native_plugin_loader.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_splits/code_review_rows/typed_error_structure_rows/structure_assertions/moved_guard_absence.rs",
            "runtime_15_review_guard_typed_error_structure_assertions_row_data_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard typed-error structure-assertions guard folder-backed split",
        &[
            "runtime_15_review_guard_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions/row_routes.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_assertions/budgets.rs",
            "runtime_15_review_guard_typed_error_structure_assertions_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
