use super::super::*;

pub(in super::super) const MODULE_CONVENTION_STATUS_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status.rs",
        MODULE_CONVENTION_STATUS_ROW_DATA_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status/status_rows.rs",
        MODULE_CONVENTION_STATUS_STATUS_ROWS_PATH,
        40,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status/frontmatter_and_gate_rows.rs",
        MODULE_CONVENTION_STATUS_FRONTMATTER_AND_GATE_ROWS_PATH,
        70,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status/structure_guard_rows.rs",
        MODULE_CONVENTION_STATUS_STRUCTURE_GUARD_ROWS_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status/audit_rows.rs",
        MODULE_CONVENTION_STATUS_AUDIT_ROWS_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status/row_data_owner.rs",
        MODULE_CONVENTION_STATUS_ROW_DATA_OWNER_ROWS_PATH,
        50,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/module_convention_status.rs",
        MODULE_CONVENTION_STATUS_GUARD_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/module_convention_status/row_groups.rs",
        MODULE_CONVENTION_STATUS_ROW_GROUPS_GUARD_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/module_convention_status/export_chain.rs",
        MODULE_CONVENTION_STATUS_EXPORT_CHAIN_GUARD_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/module_convention_status/status_current.rs",
        MODULE_CONVENTION_STATUS_STATUS_CURRENT_GUARD_PATH,
        140,
    ),
];
