use super::*;

#[test]
fn runtime_15_foundation_guards_row_data_export_chain_is_current() {
    let top_level = read_runtime_src(TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15 = read_runtime_src(RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15_m3 = read_runtime_src(RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH);

    assert_contains_all(
        "Runtime 15 M3 exposes every foundation-guards child group",
        &runtime_15_m3,
        &[
            "FOUNDATION_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_PLUGIN_IMPORTER_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_PLUGIN_IMPORTER_MIGRATIONS_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_RUNTIME_ABSORPTION_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "FOUNDATION_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 row-data parent exports every foundation-guards child group",
        &runtime_15,
        &[
            "RUNTIME_15_M3_FOUNDATION_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_PLUGIN_IMPORTER_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_PLUGIN_IMPORTER_MIGRATIONS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_ABSORPTION_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_FOUNDATION_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "top-level expected status row data consumes every foundation-guards child group",
        &top_level,
        &[
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROOT_ROUTE_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_CORE_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_RUNTIME_ABSORPTION_PLATFORM_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_TEST_GUARD_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_STRUCTURE_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_PLUGIN_IMPORTER_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_PLUGIN_IMPORTER_MIGRATIONS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_RUNTIME_ABSORPTION_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_FOUNDATION_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
}
