//! 反馈、选择和文字基础原语的共享主题与根节点行高契约。
use super::super::support::assert_tokenized_assets;
use toml::Value;

/// 用crate资产根嵌入基础原语，避免更深测试目录改变相对路径含义。
macro_rules! workbench_asset {
    ($path:literal) => {
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/assets/ui/editor/components/workbench/",
            $path
        ))
    };
}

#[test]
/// 共同固定语义色、状态色和文字度量来源，适用于被列举的真实基础资产。
fn feedback_selection_and_label_primitives_share_editor_tokens() {
    assert_tokenized_assets(&[
        (
            "workbench_tooltip.zui",
            workbench_asset!("primitives/feedback/workbench_tooltip.zui"),
            &[
                "$editor.popup",
                "$editor.separator.soft",
                "$editor.text.primary",
                "$editor.text.secondary",
                "$editor.accent",
                "$editor.control.border_width",
                "$editor.control.radius.small",
            ],
        ),
        (
            "workbench_alert.zui",
            workbench_asset!("primitives/feedback/workbench_alert.zui"),
            &[
                "$editor.semantic.warning",
                "$editor.semantic.warning.container",
                "$editor.control.border_width",
                "$editor.control.radius.small",
                "$editor.control.height.compact",
                "$editor.control.height.default",
            ],
        ),
        (
            "workbench_toast.zui",
            workbench_asset!("primitives/feedback/workbench_toast.zui"),
            &[
                "$editor.semantic.info",
                "$editor.semantic.info.container",
                "$editor.control.border_width",
                "$editor.control.radius.small",
                "$editor.control.height.compact",
                "$editor.control.height.default",
            ],
        ),
        (
            "workbench_progress_bar.zui",
            workbench_asset!("primitives/feedback/workbench_progress_bar.zui"),
            &[
                "$editor.surface.recessed",
                "$editor.surface.disabled",
                "$editor.accent",
                "$editor.separator.soft",
                "$editor.border.disabled",
                "$editor.text.primary",
                "$editor.text.disabled",
                "$editor.semantic.warning",
                "$editor.semantic.error",
                "$editor.control.border_width",
                "$editor.control.radius.small",
                "$editor.density.gap.small",
                "$editor.density.gap.medium",
                "$editor.control.height.dense",
                "$editor.control.height.compact",
                "$editor.control.height.default",
                "$editor.typography.body.size",
                "$editor.typography.line_height",
            ],
        ),
        (
            "workbench_drag_overlay.zui",
            workbench_asset!("primitives/feedback/workbench_drag_overlay.zui"),
            &[
                "$editor.accent.soft",
                "$editor.semantic.error",
                "$editor.semantic.error.container",
                "$editor.text.primary",
                "$editor.control.border_width",
                "$editor.control.radius.control",
                "$editor.density.gap.large",
                "$editor.typography.overlay.size",
                "$editor.typography.line_height",
            ],
        ),
        (
            "workbench_notification_center.zui",
            workbench_asset!("primitives/feedback/workbench_notification_center.zui"),
            &[
                "$editor.popup",
                "$editor.border",
                "$editor.surface.1",
                "$editor.surface.selected",
                "$editor.surface.disabled",
                "$editor.separator.soft",
                "$editor.text.primary",
                "$editor.text.secondary",
                "$editor.accent",
                "$editor.semantic.success",
                "$editor.semantic.warning",
                "$editor.semantic.error",
                "$editor.control.border_width",
                "$editor.control.radius.small",
                "$editor.control.radius.panel",
                "$editor.typography.body.size",
                "$editor.typography.overlay.size",
                "$editor.typography.caption.size",
            ],
        ),
        (
            "workbench_dialog.zui",
            workbench_asset!("primitives/feedback/workbench_dialog.zui"),
            &[
                "$editor.popup",
                "$editor.border",
                "$editor.accent",
                "$editor.text.primary",
                "$editor.text.secondary",
                "$editor.text.disabled",
                "$editor.semantic.info",
                "$editor.semantic.info.container",
                "$editor.semantic.warning",
                "$editor.semantic.warning.container",
                "$editor.semantic.error",
                "$editor.semantic.error.container",
                "$editor.control.border_width",
                "$editor.control.radius.panel",
                "$editor.typography.title.size",
                "$editor.typography.caption.size",
                "$editor.typography.body.size",
                "$editor.typography.line_height",
            ],
        ),
        (
            "workbench_confirm_dialog.zui",
            workbench_asset!("primitives/feedback/workbench_confirm_dialog.zui"),
            &[
                "$editor.popup",
                "$editor.border",
                "$editor.accent",
                "$editor.text.primary",
                "$editor.text.secondary",
                "$editor.text.disabled",
                "$editor.semantic.info",
                "$editor.semantic.info.container",
                "$editor.semantic.warning",
                "$editor.semantic.warning.container",
                "$editor.semantic.error",
                "$editor.semantic.error.container",
                "$editor.control.border_width",
                "$editor.control.radius.panel",
                "$editor.typography.title.size",
                "$editor.typography.caption.size",
                "$editor.typography.body.size",
                "$editor.typography.line_height",
            ],
        ),
        (
            "workbench_command_palette.zui",
            workbench_asset!("primitives/feedback/workbench_command_palette.zui"),
            &[
                "$editor.popup",
                "$editor.surface.recessed",
                "$editor.border",
                "$editor.accent",
                "$editor.text.primary",
                "$editor.text.secondary",
                "$editor.control.border_width",
                "$editor.control.radius.small",
                "$editor.control.radius.panel",
                "$editor.control.height.compact",
                "$editor.density.gap.medium",
                "$editor.density.gap.large",
                "$editor.density.row_height",
                "$editor.typography.body.size",
                "$editor.typography.line_height",
            ],
        ),
        (
            "workbench_skeleton.zui",
            workbench_asset!("primitives/feedback/workbench_skeleton.zui"),
            &[
                "$editor.surface.3",
                "$editor.surface.disabled",
                "$editor.border",
                "$editor.border.disabled",
                "$editor.control.border_width",
                "$editor.control.radius.small",
                "$editor.typography.title.size",
                "$editor.control.height.dense",
            ],
        ),
        (
            "workbench_radio.zui",
            workbench_asset!("primitives/inputs/workbench_radio.zui"),
            &[
                "$editor.surface.recessed",
                "$editor.surface.2",
                "$editor.surface.selected",
                "$editor.surface.disabled",
                "$editor.separator.strong",
                "$editor.border",
                "$editor.border.disabled",
                "$editor.text.secondary",
                "$editor.text.disabled",
                "$editor.accent",
                "$editor.control.border_width",
                "$editor.density.gap.medium",
                "$editor.control.height.dense",
                "$editor.control.height.compact",
                "$editor.typography.body.size",
                "$editor.typography.line_height",
            ],
        ),
        (
            "workbench_checkbox.zui",
            workbench_asset!("primitives/inputs/workbench_checkbox.zui"),
            &[
                "$editor.surface.recessed",
                "$editor.surface.selected",
                "$editor.surface.disabled",
                "$editor.separator.strong",
                "$editor.border.disabled",
                "$editor.text.secondary",
                "$editor.text.disabled",
                "$editor.accent",
                "$editor.control.border_width",
                "$editor.control.radius.small",
                "$editor.density.gap.medium",
                "$editor.control.height.dense",
                "$editor.control.height.compact",
                "$editor.typography.body.size",
                "$editor.typography.line_height",
            ],
        ),
        (
            "workbench_icon.zui",
            workbench_asset!("primitives/data/workbench_icon.zui"),
            &[
                "$editor.text.secondary",
                "$editor.typography.title.size",
                "$editor.control.height.dense",
            ],
        ),
        (
            "workbench_label.zui",
            workbench_asset!("primitives/data/workbench_label.zui"),
            &[
                "$editor.typography.body.size",
                "$editor.typography.medium.weight",
                "$editor.typography.line_height",
                "$editor.text.primary",
                "$editor.density.gap.xsmall",
            ],
        ),
    ]);
}

#[test]
/// 解析根节点确认可渲染Label直接消费行高比例，单纯导入主题不构成赋值。
fn label_primitives_assign_the_shared_line_height_on_their_root_node() {
    for (asset_name, asset) in [
        (
            "workbench_label.zui",
            workbench_asset!("primitives/data/workbench_label.zui"),
        ),
        (
            "workbench_caption.zui",
            workbench_asset!("primitives/data/workbench_caption.zui"),
        ),
        (
            "workbench_section_title.zui",
            workbench_asset!("primitives/chrome/workbench_section_title.zui"),
        ),
        (
            "workbench_chip.zui",
            workbench_asset!("primitives/chrome/workbench_chip.zui"),
        ),
    ] {
        let document = asset
            .parse::<Value>()
            .unwrap_or_else(|error| panic!("parse `{asset_name}`: {error}"));
        let root = document
            .get("nodes")
            .and_then(Value::as_table)
            .and_then(|nodes| nodes.get("root"))
            .unwrap_or_else(|| panic!("{asset_name} must expose a root node"));
        assert_eq!(
            root.get("component").and_then(Value::as_str),
            Some("Label"),
            "{asset_name} root must remain a renderable label primitive"
        );
        assert_eq!(
            root.get("props")
                .and_then(Value::as_table)
                .and_then(|props| props.get("line_height_ratio"))
                .and_then(Value::as_str),
            Some("$editor.typography.line_height"),
            "{asset_name} must assign the shared line-height token directly on its root"
        );
    }
}
