pub(super) const IMPORTER_RUNTIME_CRATES: &[(&str, &str, &str)] = &[
    (
        "asset_importers/audio",
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/audio/runtime/src/plugin.rs"
        ),
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/audio/runtime/Cargo.toml"
        ),
    ),
    (
        "asset_importers/data",
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/data/runtime/src/plugin.rs"
        ),
        include_str!("../../../../../../../zircon_plugins/asset_importers/data/runtime/Cargo.toml"),
    ),
    (
        "asset_importers/model",
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/model/runtime/src/plugin.rs"
        ),
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/model/runtime/Cargo.toml"
        ),
    ),
    (
        "asset_importers/shader",
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/shader/runtime/src/plugin.rs"
        ),
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/shader/runtime/Cargo.toml"
        ),
    ),
    (
        "asset_importers/texture",
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/texture/runtime/src/plugin.rs"
        ),
        include_str!(
            "../../../../../../../zircon_plugins/asset_importers/texture/runtime/Cargo.toml"
        ),
    ),
    (
        "audio_importer",
        include_str!("../../../../../../../zircon_plugins/audio_importer/runtime/src/plugin.rs"),
        include_str!("../../../../../../../zircon_plugins/audio_importer/runtime/Cargo.toml"),
    ),
    (
        "gltf_importer",
        include_str!("../../../../../../../zircon_plugins/gltf_importer/runtime/src/plugin.rs"),
        include_str!("../../../../../../../zircon_plugins/gltf_importer/runtime/Cargo.toml"),
    ),
    (
        "obj_importer",
        include_str!("../../../../../../../zircon_plugins/obj_importer/runtime/src/plugin.rs"),
        include_str!("../../../../../../../zircon_plugins/obj_importer/runtime/Cargo.toml"),
    ),
    (
        "opus_importer",
        include_str!("../../../../../../../zircon_plugins/opus_importer/runtime/src/plugin.rs"),
        include_str!("../../../../../../../zircon_plugins/opus_importer/runtime/Cargo.toml"),
    ),
    (
        "shader_wgsl_importer",
        include_str!(
            "../../../../../../../zircon_plugins/shader_wgsl_importer/runtime/src/plugin.rs"
        ),
        include_str!("../../../../../../../zircon_plugins/shader_wgsl_importer/runtime/Cargo.toml"),
    ),
    (
        "texture_importer",
        include_str!("../../../../../../../zircon_plugins/texture_importer/runtime/src/plugin.rs"),
        include_str!("../../../../../../../zircon_plugins/texture_importer/runtime/Cargo.toml"),
    ),
    (
        "ui_document_importer",
        include_str!(
            "../../../../../../../zircon_plugins/ui_document_importer/runtime/src/plugin.rs"
        ),
        include_str!("../../../../../../../zircon_plugins/ui_document_importer/runtime/Cargo.toml"),
    ),
];
