pub(super) const M3_CHILD_GROUP_OWNER_PATH_ROUTE_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/m3_child_group_owner_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/m3_child_group_owner_paths.rs",
        50,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/root_guard_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/root_guard_paths.rs",
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/owner_path_routes.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/owner_path_routes.rs",
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/plan_status_row_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/plan_status_row_paths.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/row_paths/core_rows.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/row_paths/core_rows.rs",
        50,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/row_paths/production_guard_rows.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/row_paths/production_guard_rows.rs",
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/row_paths/ui_test_rows.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/row_paths/ui_test_rows.rs",
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/folder_backed.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/group_owner_paths/folder_backed.rs",
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/core_and_evidence.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/core_and_evidence.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/runtime_row_data_guard.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/runtime_row_data_guard.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/review_guard.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/review_guard.rs",
        80,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/module_layout.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/module_layout.rs",
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/status_docs.rs",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_m3_groups/owner_paths/production_guard_row_owner_paths/status_docs.rs",
        60,
    ),
];
