use super::super::super::*;

pub(super) const M3_CHILD_GROUP_ROOT_GUARD_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/runtime_15_m3_child_groups.rs",
        M3_CHILD_GROUPS_GUARD_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_paths.rs",
        ROOT_PATHS_PATH,
        130,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_statuses.rs",
        ROOT_STATUSES_PATH,
        50,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_statuses/core_statuses.rs",
        ROOT_STATUSES_CORE_PATH,
        50,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_statuses/ui_statuses.rs",
        ROOT_STATUSES_UI_PATH,
        40,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/production_guard_support.rs",
        PRODUCTION_GUARD_SUPPORT_GUARD_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/rt15_m3_groups/production_guard_runtime_row_data.rs",
        PRODUCTION_GUARD_RUNTIME_ROW_DATA_GUARD_PATH,
        80,
    ),
];
