#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(in crate::ui::retained_host::host_contract::paint_template_nodes) enum IconButtonGlyphKind {
    Menu,
    File,
    Folder,
    Save,
    Cursor,
    Move,
    Rotate,
    Scale,
    Snap,
    Play,
    ChevronDown,
    Grid,
    Sun,
    More,
    Plus,
    Trash,
    Filter,
    Cube,
    Graph,
    Image,
    Audio,
    Code,
    Eye,
    EyeOff,
    Lock,
}
