type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 review-guard code-review row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_code_review_rows_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/row_ownership.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/root_and_children.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/export_chain.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/status_mirrors.rs",
            "runtime_15_review_guard_code_review_rows_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review row-data root inventory child split",
        &[
            "runtime_15_review_guard_code_review_rows_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/root_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/root_statuses.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/root_source_blobs.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/root_inventory.rs",
            "runtime_15_review_guard_code_review_rows_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review status-mirror child split",
        &[
            "runtime_15_review_guard_code_review_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/status_mirrors/code_review_owner.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/status_mirrors/structure_guard_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/status_mirrors/folder_backed.rs",
            "runtime_15_review_guard_code_review_status_mirror_children_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review export/status source reconciliation",
        &[
            "runtime_15_review_guard_code_review_export_status_source_reconciliation_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/export_chain.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/root_source_blobs.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_guard_exports.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3_review_guard_exports.rs",
            "runtime_15_review_guard_code_review_row_exports_are_current",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 plugin-importer status-output guard folder-backed split",
        &[
            "runtime_15_plugin_importer_status_output_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/row_children.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/row_data_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/plugin_importer_rows/budgets.rs",
            "runtime_15_plugin_importer_rows_status_output_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 typed-error structure row-data guard folder-backed split",
        &[
            "runtime_15_typed_error_structure_rows_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/row_groups.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/status_doc_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/folder_backed.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_code_review_rows/typed_error_structure_rows/budgets.rs",
            "runtime_15_typed_error_structure_rows_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
