type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 review-guard row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/moved_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/status_mirrors.rs",
            "runtime_15_review_guard_row_data_guard_is_folder_backed",
            "runtime_15_status_output_m3_review_guard_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data budgets guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_budgets_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/budgets.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/budgets/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/budgets/folder_backed.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/budgets/root_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/budgets/status_support_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/budgets/typed_error_rows.rs",
            "runtime_15_review_guard_row_data_budgets_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data delegation guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_delegation_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/route_mounts.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/status_inventory.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/child_inventory.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/split_layout.rs",
            "runtime_15_review_guard_row_data_delegation_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data delegation split-layout guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_delegation_split_layout_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/split_layout.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/split/route_mounts.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/split/status_current.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/split/budgets.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/delegation/split/split_layout.rs",
            "runtime_15_review_guard_row_data_delegation_split_layout_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-mirror child split",
        &[
            "runtime_15_review_guard_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/mirrors/folder_backed_status.rs",
            "runtime_15_review_guard_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data root inventory child split",
        &[
            "runtime_15_review_guard_row_data_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_paths.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_statuses.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_source_blobs.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_inventory.rs",
            "runtime_15_review_guard_row_data_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data root child rows folder-backed split",
        &[
            "runtime_15_review_guard_row_data_root_child_rows_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/top_level.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/delegation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/typed_error_rows.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/aggregation.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/split_layout.rs",
            "runtime_15_review_guard_row_data_root_child_rows_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data root child rows split-layout guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_root_child_rows_split_layout_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/split_layout.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/split/route_mounts.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/split/status_current.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/split/budgets.rs",
            "structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/root_child_rows/split/split_layout.rs",
            "runtime_15_review_guard_row_data_root_child_rows_split_layout_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data aggregation guard child split",
        &[
            "runtime_15_review_guard_row_data_aggregation_guard_child_split_static_passed_cargo_deferred",
            "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation/top_level_rows.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation/runtime_15_root.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation/runtime_15_m3_root.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation/review_guard_splits.rs",
            "tests/runtime_absorption/structure_convention/test_file_budget/row_data/runtime_15_review_guard_row_data/aggregation/status_current.rs",
            "runtime_15_review_guard_row_data_aggregation_guard_is_child_backed",
            "scoped rustfmt/static scans passed",
            "Cargo gate deferred",
        ],
    ),
];
