//! View descriptors, instances, and registry for the editor workbench.

mod activity_window_template_spec;
mod dock_policy;
mod pane_interaction_mode;
mod pane_payload_kind;
mod pane_route_namespace;
mod pane_template_spec;
mod preferred_host;
mod preferred_host_to_view_host;
mod view_descriptor;
mod view_descriptor_builder;
mod view_descriptor_id;
mod view_host;
mod view_instance;
mod view_instance_id;
mod view_kind;
mod view_registry;
mod view_registry_descriptor_access;
mod view_registry_instance_access;
mod view_registry_instance_mutation;
mod view_registry_open_descriptor;
mod view_registry_register_view;
mod view_registry_restore_instance;

pub use activity_window_template_spec::ActivityWindowTemplateSpec;
pub use dock_policy::DockPolicy;
pub use pane_interaction_mode::PaneInteractionMode;
pub use pane_payload_kind::PanePayloadKind;
pub use pane_payload_kind::PanePayloadKind as ViewPayloadKind;
pub use pane_route_namespace::PaneRouteNamespace;
pub use pane_template_spec::{PaneBodySpec, PaneShellSpec, PaneTemplateSpec};
pub use preferred_host::PreferredHost;
pub use view_descriptor::ViewDescriptor;
pub use view_descriptor_id::ViewDescriptorId;
pub use view_host::ViewHost;
pub use view_instance::ViewInstance;
pub use view_instance_id::ViewInstanceId;
pub use view_kind::ViewKind;
pub use view_registry::ViewRegistry;
