type Slice = super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 review-guard foundation status-date maps folder-backed split",
        &[
            "runtime_15_review_guard_foundation_status_date_maps_folder_backed_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/code_review_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/f8_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/late_api_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/p0_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/code_review_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/f8_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/late_api_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/p0_rows.rs",
            "runtime_15_review_guard_foundation_status_date_maps_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard foundation status-date map guard folder-backed split",
        &[
            "runtime_15_review_guard_foundation_status_date_map_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/status_mirrors.rs",
            "runtime_15_review_guard_foundation_status_date_map_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard foundation route-mount guard folder-backed split",
        &[
            "runtime_15_review_guard_foundation_route_mount_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/route_mounts/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/route_mounts/status_date_routes.rs",
            "runtime_15_review_guard_foundation_route_mounts_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard foundation status-mirror guard folder-backed split",
        &[
            "runtime_15_review_guard_foundation_status_mirror_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/status_mirrors/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/status_mirrors/row_maps.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/status_mirrors/status_docs.rs",
            "runtime_15_review_guard_foundation_status_mirrors_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard foundation expected-slice rows folder-backed split",
        &[
            "runtime_15_review_guard_foundation_expected_slice_rows_folder_backed_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/route_metadata_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/root_route_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/foundation_status_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/source_metadata_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/expected_slice_map_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/route_metadata_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/root_route_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/foundation_status_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/source_metadata_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/expected_slice_rows/expected_slice_map_rows.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows.rs",
            "runtime_15_review_guard_foundation_expected_slice_rows_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard foundation expected-slice rows guard folder-backed split",
        &[
            "runtime_15_review_guard_foundation_expected_slice_rows_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows/paths.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows/route_maps.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows/row_data.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/review_guard_maps/sources/foundation_review_maps/expected_slice_rows/status_docs.rs",
            "runtime_15_review_guard_foundation_expected_slice_rows_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
