use super::{component_storage, support::assert_source_anchors};

pub(super) fn assert_runtime_08_identity_and_storage_anchors() {
    assert_source_anchors(
        "Runtime 08 archetype",
        &[
            include_str!("../../../scene/ecs/archetype/mod.rs"),
            include_str!("../../../scene/ecs/archetype/id.rs"),
            include_str!("../../../scene/ecs/archetype/index.rs"),
            include_str!("../../../scene/ecs/archetype/move_result.rs"),
            include_str!("../../../scene/ecs/archetype/record.rs"),
            include_str!("../../../scene/ecs/archetype/signature.rs"),
        ],
        &[
            "pub struct ArchetypeId(usize)",
            "pub const EMPTY: Self = Self(0);",
            "pub struct ArchetypeRecord",
            "pub(super) fn push_entity(&mut self, entity: EntityId) -> usize",
            "pub(super) fn swap_remove_entity(",
            "pub struct ArchetypeMove",
            "pub struct ArchetypeIndex",
            "by_signature: HashMap<ArchetypeSignature, ArchetypeId>",
            "by_component: HashMap<ComponentId, Vec<ArchetypeId>>",
            "pub fn matching_archetypes(",
            "fn shortest_required_archetype_ids(&self, required: &[ComponentId])",
            "fn insert_archetype_id(ids: &mut Vec<ArchetypeId>, id: ArchetypeId)",
            "fn entity_row(entities: &[EntityId], entity: EntityId) -> Option<usize>",
            "pub struct ArchetypeSignature",
            "fn normalize_components(mut components: Vec<ComponentId>)",
        ],
    );
    assert_source_anchors(
        "Runtime 08 storage",
        &[
            include_str!("../../../scene/ecs/storage_type.rs"),
            include_str!("../../../scene/ecs/storage/component_storage/mod.rs"),
            include_str!("../../../scene/ecs/storage/component_storage/component_results.rs"),
            include_str!("../../../scene/ecs/storage/component_storage/entry.rs"),
            include_str!("../../../scene/ecs/storage/component_storage/location.rs"),
            include_str!("../../../scene/ecs/storage/component_storage/sparse.rs"),
            include_str!("../../../scene/ecs/storage/component_storage/store.rs"),
            include_str!("../../../scene/ecs/storage/component_storage/table.rs"),
        ],
        &[
            "pub enum StorageType",
            "Table,",
            "SparseSet,",
            "pub struct ComponentStorage",
            "table_components: HashMap<ComponentId, TableComponentStorage>,",
            "sparse_components: HashMap<ComponentId, SparseComponentStorage>,",
            "pub struct ComponentStorageLocation",
            "pub fn get_table_row<T>",
            "pub fn get_with_ticks_at_location<T>",
        ],
    );
    component_storage::assert_component_storage_private_reexport_cleanup();
    assert_source_anchors(
        "Runtime 08 component identity",
        &[
            include_str!("../../../scene/ecs/component/mod.rs"),
            include_str!("../../../scene/ecs/component/id.rs"),
            include_str!("../../../scene/ecs/component/marker.rs"),
            include_str!("../../../scene/ecs/component/registry.rs"),
        ],
        &[
            "pub trait Component: 'static + Send + Sync",
            "const STORAGE_TYPE: StorageType = StorageType::Table;",
            "pub struct ComponentId(usize)",
            "pub const fn new(index: usize) -> Self",
            "pub const fn index(self) -> usize",
            "pub struct ComponentDescriptor",
            "pub enum ComponentDescriptorSource",
            "RustType { type_id: TypeId }",
            "DynamicPlugin { component_type_id: String }",
            "pub struct ComponentRegistry",
            "rust_ids_by_type_id: HashMap<TypeId, ComponentId>",
            "dynamic_ids_by_type_id: HashMap<String, ComponentId>",
            "pub fn component_id<T>(&mut self) -> ComponentId",
            "pub fn dynamic_component_id(&mut self, component_type_id: &str) -> ComponentId",
            "pub fn registered_component_id<T>(&self) -> Option<ComponentId>",
            "pub fn registered_dynamic_component_id(&self, component_type_id: &str) -> Option<ComponentId>",
            "pub(crate) fn rust_type_for_id(&self, id: ComponentId) -> Option<(TypeId, &str)>",
            "pub fn descriptors(&self) -> &[ComponentDescriptor]",
        ],
    );
    assert_source_anchors(
        "Runtime 08 entity lifecycle",
        &[
            include_str!("../../../scene/ecs/entity/mod.rs"),
            include_str!("../../../scene/ecs/entity/despawned.rs"),
            include_str!("../../../scene/ecs/entity/error.rs"),
            include_str!("../../../scene/ecs/entity/internal.rs"),
            include_str!("../../../scene/ecs/entity/location.rs"),
            include_str!("../../../scene/ecs/entity/registry.rs"),
            include_str!("../../../scene/ecs/entity/slot.rs"),
            include_str!("../../../scene/ecs/entity/stable_location.rs"),
            include_str!("../../../scene/world/identity.rs"),
        ],
        &[
            "const FIRST_GENERATION: u32 = 1;",
            "free_slots: Vec<u32>",
            "stable_to_internal: HashMap<EntityId, InternalEntity>",
            "InternalEntity::new(slot_index, slot.generation)",
            "slot.generation = next_generation(slot.generation);",
            "self.free_slots.push(internal.index());",
            "pub const fn generation(self) -> u32",
            "self.index as u64 | ((self.generation as u64) << 32)",
            "pub struct StableEntityLocation",
            "pub struct DespawnedEntity",
        ],
    );
    assert_source_anchors(
        "Runtime 08 resource identity",
        &[
            include_str!("../../../scene/ecs/resource/mod.rs"),
            include_str!("../../../scene/ecs/resource/id.rs"),
            include_str!("../../../core/framework/scene/resource.rs"),
            include_str!("../../../scene/ecs/resource/registry.rs"),
        ],
        &[
            "pub trait SceneResource: 'static + Send + Sync",
            "pub struct ResourceId(usize)",
            "pub const fn new(index: usize) -> Self",
            "pub const fn index(self) -> usize",
            "pub struct ResourceDescriptor",
            "pub struct ResourceRegistry",
            "ids_by_type: HashMap<TypeId, ResourceId>",
            "pub fn resource_id<T>(&mut self) -> ResourceId",
            "type_name::<T>().to_string()",
            "pub fn registered_resource_id<T>(&self) -> Option<ResourceId>",
            "pub fn descriptor(&self, id: ResourceId) -> Option<&ResourceDescriptor>",
            "pub fn descriptors(&self) -> &[ResourceDescriptor]",
        ],
    );
    assert_source_anchors(
        "Runtime 08 change tick",
        &[
            include_str!("../../../scene/ecs/change_detection/mod.rs"),
            include_str!("../../../scene/ecs/change_detection/change_tick.rs"),
            include_str!("../../../scene/ecs/change_detection/change_tick_window.rs"),
            include_str!("../../../scene/ecs/change_detection/component_ticks.rs"),
            include_str!("../../../scene/ecs/change_detection/stats.rs"),
            include_str!("../../../scene/ecs/change_detection/wrappers.rs"),
        ],
        &[
            "pub const MAX_CHANGE_AGE: u64",
            "Self(self.0.wrapping_add(1))",
            "Self(self.0.wrapping_sub(older.0))",
            "pub fn is_newer_than(self, last_run: Self, this_run: Self) -> bool",
            "this_run.relative_to(self).0.min(Self::MAX_CHANGE_AGE)",
            "last_run: last_run.clamp_older_than(this_run)",
        ],
    );
}
