use super::ScreenSpaceUiTextPrepareReport;

#[path = "profile/artifact_routes.rs"]
mod artifact_routes;
#[path = "profile/dto_residency.rs"]
mod dto_residency;
#[path = "profile/runtime_budget.rs"]
mod runtime_budget;
#[path = "profile/sdf_residency.rs"]
mod sdf_residency;

#[cfg(feature = "profiling")]
pub(in super::super) fn record_text_prepare_profile(report: &ScreenSpaceUiTextPrepareReport) {
    artifact_routes::record_resolved_glyph_artifact_route_profile(
        &report.resolved_glyph_artifact_routes,
        report.post_layout_stale_artifact_batch_rejection_count,
    );
    dto_residency::record_dto_residency_profile(report);
    runtime_budget::record_runtime_budget_profile(report);
    let raster = &report.raster_upload;
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_hits",
        raster.source_cache_hit_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_approximate_hits",
        raster.source_cache_approximate_hit_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_misses",
        raster.source_cache_miss_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_inserts",
        raster.source_cache_insert_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_capacity",
        raster.source_cache_capacity
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_entries",
        raster.source_cache_entry_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_persistent_raster_keys",
        raster.source_cache_persistent_raster_key_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_resident_bytes",
        raster.source_cache_resident_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_max_bytes",
        raster.source_cache_max_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_approximate_probes",
        raster.source_cache_approximate_probe_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_lru_repairs",
        raster.source_cache_lru_repair_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_lru_touches",
        raster.source_cache_lru_touch_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_evicted",
        raster.source_cache_evicted_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_evicted_bytes",
        raster.source_cache_evicted_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_budget_linked_evictions",
        raster.source_cache_budget_linked_eviction_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_linked_invalidations",
        raster.source_cache_linked_raster_invalidation_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_budget_rejections",
        raster.source_cache_rejected_byte_budget_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.source_cache_invalidated",
        raster.source_cache_invalidated_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.slot_cache_hits",
        raster.atlas_slot_cache_hit_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.slot_cache_misses",
        raster.atlas_slot_cache_miss_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pending",
        raster.worker_pending_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_deferred",
        raster.worker_request_deferred_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_failed",
        raster.worker_failed_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_request_backpressured",
        raster.worker_request_backpressured_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_font_copied_bytes",
        raster.worker_request_font_copied_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_font_resident_bytes",
        raster.worker_raster_font_resident_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_font_resident_entries",
        raster.worker_raster_font_entry_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_cancelled",
        raster.worker_request_cancelled_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_applied_bytes",
        raster.worker_completion_applied_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_drained_bytes",
        raster.worker_completion_drained_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_budget_deferred",
        raster.worker_completion_byte_budget_deferred_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_oversized_accepted",
        raster.worker_completion_oversized_accepted_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_threads",
        raster.worker_pool_budgeted_thread_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_in_flight",
        raster.worker_pool_in_flight_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_queued",
        raster.worker_pool_queued_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_queued_bytes",
        raster.worker_pool_queued_input_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_running",
        raster.worker_pool_running_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_completed_total",
        raster.worker_pool_completed_total
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_failed_total",
        raster.worker_pool_failed_total
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_pool_queue_peak",
        raster.worker_pool_queue_peak_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_backlog",
        raster.worker_pool_completion_backlog_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_backlog_bytes",
        raster.worker_pool_completion_backlog_byte_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_backpressured_total",
        raster.worker_pool_completion_backpressured_total
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_budget_rejected_total",
        raster.worker_pool_completion_budget_rejected_total
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_completion_rejected_bytes_total",
        raster.worker_pool_completion_rejected_byte_total
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_request_backpressured_total",
        raster.worker_pool_request_backpressured_total
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.worker_cancelled_total",
        raster.worker_pool_cancelled_total
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.native_raster_plan.visible_placeholders",
        raster.visible_placeholder_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.atlas_upload.native_copy_count",
        raster.upload_copy_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.atlas_upload.native_bytes",
        raster.upload_byte_len
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.atlas_upload.native_requeues",
        raster.renderer_upload_requeued_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.atlas_upload.native_failures",
        raster.renderer_upload_failure_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.atlas_upload.native_instances",
        report
            .bitmap_atlas_renderer
            .storage_pass_visible_glyph_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.atlas_upload.native_draws",
        report.bitmap_atlas_renderer.draw_command_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.text_batches",
        report.sdf_renderer.text_batch_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.atlas_slots",
        report.sdf_renderer.atlas_slot_count
    );
    sdf_residency::record_sdf_residency_profile(report);
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.vertices",
        report.sdf_renderer.vertex_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.draws",
        report.sdf_renderer.draw_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.compiled_segment_visits",
        report.sdf_renderer.compiled_segment_visit_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.compiled_vertex_visits",
        report.sdf_renderer.compiled_vertex_visit_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.compiled_material_visits",
        report.sdf_renderer.compiled_material_visit_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.compiled_full_rebuilds",
        report.sdf_renderer.compiled_full_rebuild_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.vertex_buffer_write_count",
        report.sdf_renderer.vertex_buffer_write_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.vertex_buffer_write_bytes",
        report.sdf_renderer.vertex_buffer_write_byte_len
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.material_buffer_write_count",
        report.sdf_renderer.material_buffer_write_count
    );
    crate::profile_counter!(
        "runtime",
        "ui_text.sdf_prepare.material_buffer_write_bytes",
        report.sdf_renderer.material_buffer_write_byte_len
    );
}
#[cfg(all(test, feature = "profiling"))]
#[path = "tests/profile.rs"]
mod tests;
