pub(super) fn expected_status_for_slice(_slice: &str) -> Option<&'static str> {
    None
}

// Files: structure_convention/production_file_budget/render_shader_template_assembly.rs; structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions.rs; structure_convention/production_file_budget/render_shader_template_assembly/docs_anchors.rs; structure_convention/production_file_budget/render_shader_template_assembly/sources.rs.
// Guard: runtime_15_render_shader_template_assembly_support_children_are_folder_backed.
// Files: structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions.rs; structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/template_contracts.rs; structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/mesh_cache_contracts.rs; structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/mesh_pipeline_shadow_graph_contracts.rs; structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/owner_budget.rs.
// Guard: runtime_15_render_shader_template_assembly_support_children_are_folder_backed.
// Files: graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/shader_source.rs; graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/shader_source/tests.rs; graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/shader_source/tests/runtime_shading_model_sources.rs.
// Guard: runtime_15_render_shader_template_assembly_support_children_are_folder_backed.
