[package]
name = "zircon_plugin_ui_asset_authoring_editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "UI asset authoring editor plugin package for Zircon."

[dependencies]
zircon_editor = { workspace = true }
zircon_plugin_editor_support = { path = "../../editor_support" }
zircon_runtime = { workspace = true }
zircon_runtime_interface = { workspace = true }
