pub(crate) const POST_PROCESS_REQUIRED_SAMPLED_TEXTURES_PER_SHADER_STAGE: u32 = 21;
pub(crate) const GPU_SCENE_COMPUTE_STORAGE_BUFFERS_PER_SHADER_STAGE: u32 = 9;
pub(crate) const HZB_OCCLUSION_PASS_STORAGE_BUFFERS_PER_SHADER_STAGE: u32 = 6;
pub(crate) const HZB_OCCLUSION_REQUIRED_STORAGE_BUFFERS_PER_SHADER_STAGE: u32 =
    GPU_SCENE_COMPUTE_STORAGE_BUFFERS_PER_SHADER_STAGE
        + HZB_OCCLUSION_PASS_STORAGE_BUFFERS_PER_SHADER_STAGE;
pub(crate) const MESH_FORWARD_PIPELINE_REQUIRED_STORAGE_BUFFERS_PER_SHADER_STAGE: u32 = 12;
