use super::*;

pub(super) fn host_scene() -> host_window::HostWindowSceneData {
    host_window::HostWindowSceneData {
        layout: host_window::HostWindowLayoutData {
            center_band_frame: host_frame_rect(0.0, 0.0, 1200.0, 700.0),
            status_bar_frame: host_frame_rect(0.0, 700.0, 1200.0, 24.0),
            left_region_frame: host_frame_rect(0.0, 0.0, 240.0, 700.0),
            document_region_frame: host_frame_rect(240.0, 0.0, 720.0, 700.0),
            right_region_frame: host_frame_rect(960.0, 0.0, 240.0, 700.0),
            bottom_region_frame: host_frame_rect(240.0, 500.0, 720.0, 200.0),
            left_splitter_frame: host_frame_rect(240.0, 0.0, 4.0, 700.0),
            right_splitter_frame: host_frame_rect(956.0, 0.0, 4.0, 700.0),
            bottom_splitter_frame: host_frame_rect(240.0, 496.0, 720.0, 4.0),
            viewport_content_frame: host_frame_rect(240.0, 64.0, 720.0, 432.0),
        },
        metrics: host_window::HostWindowSurfaceMetricsData {
            outer_margin_px: 8.0,
            rail_width_px: 40.0,
            top_bar_height_px: 40.0,
            host_bar_height_px: 32.0,
            panel_header_height_px: 28.0,
            document_header_height_px: 32.0,
        },
        orchestration: host_window::HostWindowSurfaceOrchestrationData {
            left_rail_width_px: 40.0,
            right_rail_width_px: 40.0,
            left_stack_width_px: 240.0,
            right_stack_width_px: 240.0,
            left_panel_width_px: 200.0,
            right_panel_width_px: 200.0,
            bottom_panel_height_px: 200.0,
            main_content_y_px: 40.0,
            document_zone_x_px: 240.0,
            right_stack_x_px: 960.0,
            bottom_panel_y_px: 500.0,
        },
        menu_chrome: host_window::HostMenuChromeData {
            outer_margin_px: 8.0,
            top_bar_height_px: 40.0,
            template_nodes: Default::default(),
            menu_frames: host_chrome_menu_frames(1),
            save_project_enabled: true,
            undo_enabled: true,
            redo_enabled: true,
            delete_enabled: true,
            preset_names: model_rc(vec!["Default".into()]),
            active_preset_name: "Default".into(),
            resolved_preset_name: "Default".into(),
            menus: Default::default(),
        },
        page_chrome: host_window::HostPageChromeData {
            top_bar_height_px: 40.0,
            host_bar_height_px: 32.0,
            template_nodes: Default::default(),
            tab_row_frame: host_frame_rect(0.0, 40.0, 1200.0, 32.0),
            project_path_frame: host_frame_rect(900.0, 48.0, 280.0, 14.0),
            overflow_frame: Default::default(),
            overflow_hidden_tab_indices: Vec::new(),
            overflow_widest_title_width_px: 123.0,
            tab_frames: host_chrome_tab_frames(&["document-tab"]),
            tabs: host_tabs(&["document-tab"]),
            project_path: "res://project".into(),
        },
        status_bar: host_window::HostStatusBarData {
            status_bar_frame: host_frame_rect(0.0, 700.0, 1200.0, 24.0),
            template_nodes: Default::default(),
            status_primary: "Ready".into(),
            status_secondary: "Idle".into(),
            viewport_label: "Viewport".into(),
        },
        resize_layer: host_window::HostResizeLayerData {
            left_splitter_frame: host_frame_rect(240.0, 0.0, 4.0, 700.0),
            right_splitter_frame: host_frame_rect(956.0, 0.0, 4.0, 700.0),
            bottom_splitter_frame: host_frame_rect(240.0, 496.0, 720.0, 4.0),
        },
        drag_overlay: host_window::HostTabDragOverlayData {
            left_drop_enabled: true,
            right_drop_enabled: true,
            bottom_drop_enabled: true,
            left_drop_width_px: 120.0,
            right_drop_width_px: 120.0,
            bottom_drop_height_px: 120.0,
            main_content_y_px: 40.0,
            main_content_height_px: 660.0,
            document_zone_x_px: 240.0,
            document_zone_width_px: 720.0,
            bottom_drop_top_px: 500.0,
            drag_overlay_bottom_px: 700.0,
        },
        left_dock: host_window::HostSideDockSurfaceData {
            region_frame: host_frame_rect(0.0, 0.0, 240.0, 700.0),
            surface_key: "left-surface".into(),
            rail_before_panel: true,
            rail_nodes: Default::default(),
            rail_button_frames: Default::default(),
            rail_active_control_id: "".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 200.0, 31.0),
            overflow_frame: Default::default(),
            content_frame: host_frame_rect(0.0, 32.0, 200.0, 668.0),
            tab_frames: host_chrome_tab_frames(&["left-tab"]),
            tabs: host_tabs(&["left-tab"]),
            pane: host_pane("left-pane", "Left"),
            rail_width_px: 40.0,
            panel_width_px: 200.0,
            panel_header_height_px: 28.0,
        },
        document_dock: host_window::HostDocumentDockSurfaceData {
            region_frame: host_frame_rect(240.0, 0.0, 720.0, 700.0),
            surface_key: "document-surface".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 720.0, 32.0),
            overflow_frame: Default::default(),
            subtitle_frame: host_frame_rect(576.0, 9.0, 132.0, 14.0),
            content_frame: host_frame_rect(0.0, 33.0, 720.0, 667.0),
            tab_frames: host_chrome_tab_frames(&["document-tab"]),
            tabs: host_tabs(&["document-tab"]),
            pane: host_pane("document-pane", "Document"),
            header_height_px: 32.0,
        },
        right_dock: host_window::HostSideDockSurfaceData {
            region_frame: host_frame_rect(960.0, 0.0, 240.0, 700.0),
            surface_key: "right-surface".into(),
            rail_before_panel: false,
            rail_nodes: Default::default(),
            rail_button_frames: Default::default(),
            rail_active_control_id: "".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 200.0, 31.0),
            overflow_frame: Default::default(),
            content_frame: host_frame_rect(0.0, 32.0, 200.0, 668.0),
            tab_frames: host_chrome_tab_frames(&["right-tab"]),
            tabs: host_tabs(&["right-tab"]),
            pane: host_pane("right-pane", "Right"),
            rail_width_px: 40.0,
            panel_width_px: 200.0,
            panel_header_height_px: 28.0,
        },
        bottom_dock: host_window::HostBottomDockSurfaceData {
            region_frame: host_frame_rect(240.0, 500.0, 720.0, 200.0),
            surface_key: "bottom-surface".into(),
            header_nodes: Default::default(),
            header_frame: host_frame_rect(0.0, 0.0, 720.0, 31.0),
            overflow_frame: Default::default(),
            content_frame: host_frame_rect(0.0, 32.0, 720.0, 168.0),
            tab_frames: host_chrome_tab_frames(&["bottom-tab"]),
            tabs: host_tabs(&["bottom-tab"]),
            pane: host_pane("bottom-pane", "Bottom"),
            expanded: true,
            header_height_px: 28.0,
        },
        floating_layer: host_window::HostFloatingWindowLayerData {
            floating_windows: model_rc(vec![host_window::FloatingWindowData {
                window_id: "floating-window".into(),
                title: "Floating".into(),
                frame: host_frame_rect(320.0, 160.0, 360.0, 240.0),
                header_nodes: Default::default(),
                header_frame: host_frame_rect(0.0, 0.0, 360.0, 31.0),
                overflow_frame: Default::default(),
                tab_frames: host_chrome_tab_frames(&["floating-tab"]),
                target_group: "floating/window".into(),
                left_edge_target_group: "floating/window/left".into(),
                right_edge_target_group: "floating/window/right".into(),
                top_edge_target_group: "floating/window/top".into(),
                bottom_edge_target_group: "floating/window/bottom".into(),
                focus_target_id: "floating-focus".into(),
                tabs: host_tabs(&["floating-tab"]),
                active_pane: host_pane("floating-pane", "Floating"),
            }]),
            header_height_px: 24.0,
        },
    }
}
