use super::*;

pub(super) fn populate(scene: &mut host_window::HostWindowSceneData) {
    scene.document_dock.pane.kind = "Project".into();
    scene.document_dock.pane.native_body.project_overview =
        host_window::ProjectOverviewPaneViewData {
            nodes: model_rc(vec![
                crate::ui::layouts::views::ViewTemplateNodeData {
                    node_id: "root/outer_panel".into(),
                    control_id: "ProjectOverviewOuterPanel".into(),
                    role: "Panel".into(),
                    text: "".into(),
                    dispatch_kind: "".into(),
                    action_id: "".into(),
                    surface_variant: "panel".into(),
                    text_tone: "".into(),
                    button_variant: "".into(),
                    font_size: 0.0,
                    font_weight: 0,
                    text_align: "left".into(),
                    overflow: "".into(),
                    corner_radius: 8.0,
                    border_width: 1.0,
                    frame: crate::ui::layouts::views::ViewTemplateFrameData {
                        x: 16.0,
                        y: 14.0,
                        width: 688.0,
                        height: 654.0,
                    },
                    ..Default::default()
                },
                crate::ui::layouts::views::ViewTemplateNodeData {
                    node_id: "root/header_path".into(),
                    control_id: "ProjectOverviewPathText".into(),
                    role: "Label".into(),
                    text: "res://project".into(),
                    dispatch_kind: "".into(),
                    action_id: "".into(),
                    surface_variant: "".into(),
                    text_tone: "muted".into(),
                    button_variant: "".into(),
                    font_size: 10.0,
                    font_weight: 400,
                    text_align: "left".into(),
                    overflow: "elide".into(),
                    corner_radius: 0.0,
                    border_width: 0.0,
                    frame: crate::ui::layouts::views::ViewTemplateFrameData {
                        x: 32.0,
                        y: 52.0,
                        width: 656.0,
                        height: 16.0,
                    },
                    ..Default::default()
                },
                crate::ui::layouts::views::ViewTemplateNodeData {
                    node_id: "root/catalog_panel".into(),
                    control_id: "ProjectOverviewCatalogPanel".into(),
                    role: "Panel".into(),
                    text: "".into(),
                    dispatch_kind: "".into(),
                    action_id: "".into(),
                    surface_variant: "inset".into(),
                    text_tone: "".into(),
                    button_variant: "".into(),
                    font_size: 0.0,
                    font_weight: 0,
                    text_align: "left".into(),
                    overflow: "".into(),
                    corner_radius: 6.0,
                    border_width: 1.0,
                    frame: crate::ui::layouts::views::ViewTemplateFrameData {
                        x: 32.0,
                        y: 206.0,
                        width: 656.0,
                        height: 68.0,
                    },
                    ..Default::default()
                },
            ]),
        };
    scene.bottom_dock.pane.kind = "Assets".into();
    scene.bottom_dock.pane.native_body.assets_activity = host_window::AssetsActivityPaneViewData {
        nodes: model_rc(vec![
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/toolbar_panel".into(),
                control_id: "AssetsActivityToolbarPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 18.0,
                    y: 16.0,
                    width: 680.0,
                    height: 122.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/tree_panel".into(),
                control_id: "AssetsActivityTreePanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 18.0,
                    y: 148.0,
                    width: 248.0,
                    height: 284.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/utility_tabs_row".into(),
                control_id: "AssetsActivityUtilityTabsRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 30.0,
                    y: 454.0,
                    width: 656.0,
                    height: 32.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/reference_right_panel".into(),
                control_id: "AssetsActivityReferenceRightPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 364.0,
                    y: 496.0,
                    width: 322.0,
                    height: 110.0,
                },
                ..Default::default()
            },
        ]),
        ..host_window::AssetsActivityPaneViewData::default()
    };
    scene.left_dock.pane.native_body.hierarchy = host_window::HierarchyPaneViewData {
        nodes: model_rc(vec![crate::ui::layouts::views::ViewTemplateNodeData {
            node_id: "root/list_panel".into(),
            control_id: "HierarchyListPanel".into(),
            role: "Mount".into(),
            text: "".into(),
            dispatch_kind: "".into(),
            action_id: "".into(),
            surface_variant: "".into(),
            text_tone: "".into(),
            button_variant: "".into(),
            font_size: 0.0,
            font_weight: 0,
            text_align: "left".into(),
            overflow: "".into(),
            corner_radius: 0.0,
            border_width: 0.0,
            frame: crate::ui::layouts::views::ViewTemplateFrameData {
                x: 8.0,
                y: 8.0,
                width: 184.0,
                height: 260.0,
            },
            ..Default::default()
        }]),
        hierarchy_nodes: model_rc(vec![
            host_window::SceneNodeData {
                id: "entity://root".into(),
                name: "Root".into(),
                depth: 0,
                selected: true,
            },
            host_window::SceneNodeData {
                id: "entity://child".into(),
                name: "Child".into(),
                depth: 1,
                selected: false,
            },
        ]),
    };
    scene.right_dock.pane.native_body.inspector = host_window::InspectorPaneViewData {
        nodes: model_rc(vec![
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/content_panel".into(),
                control_id: "InspectorContentPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 10.0,
                    width: 220.0,
                    height: 180.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/header_panel".into(),
                control_id: "InspectorHeaderPanel".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 10.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/name_row".into(),
                control_id: "InspectorNameRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 36.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/parent_row".into(),
                control_id: "InspectorParentRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 62.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/position_row".into(),
                control_id: "InspectorPositionRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 88.0,
                    width: 220.0,
                    height: 22.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/separator_row".into(),
                control_id: "InspectorSeparatorRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 114.0,
                    width: 220.0,
                    height: 1.0,
                },
                ..Default::default()
            },
            crate::ui::layouts::views::ViewTemplateNodeData {
                node_id: "root/actions_row".into(),
                control_id: "InspectorActionsRow".into(),
                role: "Mount".into(),
                text: "".into(),
                dispatch_kind: "".into(),
                action_id: "".into(),
                surface_variant: "".into(),
                text_tone: "".into(),
                button_variant: "".into(),
                font_size: 0.0,
                font_weight: 0,
                text_align: "left".into(),
                overflow: "".into(),
                corner_radius: 0.0,
                border_width: 0.0,
                frame: crate::ui::layouts::views::ViewTemplateFrameData {
                    x: 10.0,
                    y: 119.0,
                    width: 220.0,
                    height: 24.0,
                },
                ..Default::default()
            },
        ]),
        info: "Node 42".into(),
        inspector_name: "CameraRig".into(),
        inspector_parent: "entity://root".into(),
        inspector_x: "1.0".into(),
        inspector_y: "2.0".into(),
        inspector_z: "3.0".into(),
        delete_enabled: true,
        plugin_components: Vec::new(),
    };
    scene.bottom_dock.pane.native_body.console = host_window::ConsolePaneViewData {
        nodes: model_rc(vec![crate::ui::layouts::views::ViewTemplateNodeData {
            node_id: "root/text_panel".into(),
            control_id: "ConsoleTextPanel".into(),
            role: "Mount".into(),
            text: "".into(),
            dispatch_kind: "".into(),
            action_id: "".into(),
            surface_variant: "".into(),
            text_tone: "".into(),
            button_variant: "".into(),
            font_size: 0.0,
            font_weight: 0,
            text_align: "left".into(),
            overflow: "".into(),
            corner_radius: 0.0,
            border_width: 0.0,
            frame: crate::ui::layouts::views::ViewTemplateFrameData {
                x: 10.0,
                y: 8.0,
                width: 640.0,
                height: 152.0,
            },
            ..Default::default()
        }]),
        output: "Build finished".into(),
    };
}
