use super::super::*;
use super::super::{guard_names::GuardNames, sources::GuardSources};

pub(super) fn assert_parent_mounts_and_moved_guards(sources: &GuardSources, guards: &GuardNames) {
    assert!(
        !sources.old_parent.exists(),
        "test-file budget guard root should live at test_file_budget/mod.rs, not the retired flat test_file_budget.rs"
    );
    assert_contains_all(
        "test file budget parent mounts folder-backed guard owners",
        &sources.parent,
        &[
            "mod asset_tests;",
            "mod asset_gltf_importer;",
            "mod asset_gltf_primitive_fixtures;",
            "mod asset_importer;",
            "mod asset_project_flow_sample;",
            "mod asset_scene;",
            "mod code_review_findings;",
            "mod core_framework;",
            "mod core_runtime_deactivation;",
            "mod dynamic_scene_absorption;",
            "mod historical_oversized_roots;",
            "mod module_layout;",
            "mod render_products;",
            "mod rhi_command_list;",
            "mod rhi_device_contract;",
            "mod runtime_diagnostics;",
            "mod root_layout;",
            "mod scene_component_structure;",
            "mod scene_derived_state;",
            "mod scene_dynamic_scene_root;",
            "mod scene_dynamic_session;",
            "mod scene_ecs_reflect_foundation;",
            "mod scene_ecs_query;",
            "mod scene_ecs_query_structure;",
            "mod scene_ecs_schedule;",
            "mod scene_ecs_systems;",
            "mod shader_prewarm_manifest;",
            "mod status_output_expected_slices;",
            "mod status_output_row_data;",
            "mod script_vm_tests;",
            "mod ui_architecture;",
            "mod ui_asset;",
            "mod ui_asset_mui_web_mui_x_style;",
            "mod ui_asset_mui_web_style;",
            "mod ui_accessibility;",
            "mod ui_accessibility_widget_actions;",
            "mod ui_boundary;",
            "mod ui_component_catalog;",
            "mod ui_component_catalog_component_state;",
            "mod ui_component_catalog_component_state_keyboard;",
            "mod ui_component_catalog_material_foundation;",
            "mod ui_event_routing;",
            "mod ui_layout_slots;",
            "mod ui_material_layout;",
            "mod ui_surface_dirty_domains;",
            "mod ui_surface_frame_authority;",
            "mod ui_taffy_layout_pass;",
            "mod ui_template;",
            "mod ui_widget_text_input_keyboard;",
            "mod ui_runtime_input_reply_routes;",
            "mod ui_runtime_window_event_abi;",
            "mod ui_runtime_window_input_pump;",
            "mod ui_shared_core;",
            "mod ui_v2_asset;",
        ],
    );

    for moved_guard in [
        guards.asset_pack_guard.as_str(),
        guards.asset_facade_guard.as_str(),
        guards.asset_project_zmeta_guard.as_str(),
        guards.asset_project_manager_guard.as_str(),
        guards.asset_material_guard.as_str(),
        guards.asset_gltf_importer_guard.as_str(),
        guards.asset_gltf_primitive_fixtures_guard.as_str(),
        guards.asset_importer_guard.as_str(),
        guards.asset_project_flow_sample_guard.as_str(),
        guards.asset_scene_guard.as_str(),
        guards.code_review_findings_guard.as_str(),
        guards.core_runtime_deactivation_guard.as_str(),
        guards.dynamic_scene_absorption_guard.as_str(),
        guards.render_products_guard.as_str(),
        guards.root_layout_guard.as_str(),
        guards.runtime_diagnostics_guard.as_str(),
        guards.rhi_command_list_guard.as_str(),
        guards.rhi_device_contract_guard.as_str(),
        guards.scene_component_structure_guard.as_str(),
        guards.scene_derived_state_guard.as_str(),
        guards.scene_dynamic_scene_root_guard.as_str(),
        guards.scene_dynamic_session_guard.as_str(),
        guards.scene_ecs_reflect_foundation_guard.as_str(),
        guards.scene_ecs_query_guard.as_str(),
        guards.scene_ecs_query_structure_guard.as_str(),
        guards.scene_ecs_schedule_guard.as_str(),
        guards.scene_ecs_systems_guard.as_str(),
        guards.shader_prewarm_manifest_guard.as_str(),
        guards.status_output_row_data_guard.as_str(),
        "fn runtime_15_core_framework_tests_are_folder_backed",
        "fn runtime_15_test_file_budget_parent_guard_child_owner_split",
        "fn runtime_15_ui_shared_core_tests_are_folder_backed",
        "fn runtime_15_ui_v2_asset_tests_are_folder_backed",
        guards.script_vm_tests_guard.as_str(),
        guards.gameplay_host_tests_guard.as_str(),
    ] {
        assert!(
            !sources.parent.contains(moved_guard),
            "test_file_budget/mod.rs should mount child guard owners instead of defining {moved_guard}"
        );
    }
}
