use super::{generate_slot_catalog_from_source, render_trusted_host_build_set};

const CURRENT_INTERFACE_SPEC: &str =
    include_str!("../../src/runtime_build_set/interface_spec_v1.json");

fn interface_spec_with_slots(required: &str, optional: &str, host_optional: &str) -> String {
    format!(
        r#"{{
                "family": "zircon.runtime.internal",
                "spec_version": 1,
                "runtime_api_version": 8,
                "entry_symbol": "zircon_runtime_get_api_v8",
                "runtime_api_required_slots": {required},
                "runtime_api_optional_slots": {optional},
                "host_api_optional_slots": {host_optional}
            }}"#
    )
}

#[test]
fn trusted_host_build_set_renderer_rejects_untrusted_values() {
    assert_eq!(
        render_trusted_host_build_set(None).unwrap(),
        "// @generated by build.rs from the curated cargo-zircon BuildSet environment.\n\npub const ZR_TRUSTED_HOST_BUILD_SET_ID_V1: Option<&str> = None;\n"
    );
    assert!(render_trusted_host_build_set(Some(&"A".repeat(64))).is_err());
    assert!(render_trusted_host_build_set(Some(&"z".repeat(64))).is_err());
    assert!(render_trusted_host_build_set(Some(&"a".repeat(64)))
        .unwrap()
        .contains("Some(\""));
}

#[test]
fn slot_catalog_generator_emits_the_current_interface_inventory() {
    let catalog = generate_slot_catalog_from_source(CURRENT_INTERFACE_SPEC)
        .expect("current InterfaceSpec must generate a Rust slot catalog");

    assert!(catalog.starts_with("// @generated by build.rs"));
    assert!(catalog.contains("pub const ZR_RUNTIME_INTERFACE_FAMILY_V1"));
    assert!(catalog.contains("pub const ZIRCON_RUNTIME_API_VERSION_V8: u32 = 8;"));
    assert!(catalog.contains("pub const ZR_RUNTIME_GET_API_SYMBOL_V8"));
    assert!(catalog.contains("pub const ZR_RUNTIME_API_V8_REQUIRED_SLOT_NAMES"));
    assert!(catalog.contains("pub const ZR_RUNTIME_API_V8_OPTIONAL_SLOT_NAMES"));
    assert!(catalog.contains("pub const ZR_HOST_API_V1_OPTIONAL_SLOT_NAMES"));
    assert!(catalog.contains("\"create_session\""));
    assert!(catalog.contains("\"present_viewport\""));
    assert!(catalog.contains("\"diagnostics_sink\""));
}

#[test]
fn slot_catalog_generator_rejects_duplicate_runtime_slots_across_partitions() {
    let source = interface_spec_with_slots("[\"create_session\"]", "[\"create_session\"]", "[]");
    let error = generate_slot_catalog_from_source(&source)
        .expect_err("a V8 slot cannot be both required and optional");

    assert!(error.contains("runtime_api_optional_slots"));
    assert!(error.contains("create_session"));
}

#[test]
fn slot_catalog_generator_keeps_host_slots_in_a_separate_namespace() {
    let source =
        interface_spec_with_slots("[\"release_allocation\"]", "[]", "[\"release_allocation\"]");
    let catalog = generate_slot_catalog_from_source(&source)
        .expect("host and runtime tables may reuse a field label");

    assert_eq!(catalog.matches("\"release_allocation\"").count(), 2);
}

#[test]
fn slot_catalog_generator_rejects_non_rust_slot_identifiers() {
    let source = interface_spec_with_slots("[\"1bad\"]", "[]", "[]");
    let error = generate_slot_catalog_from_source(&source)
        .expect_err("a generated Rust catalog must reject invalid identifiers");

    assert!(error.contains("runtime_api_required_slots"));
    assert!(error.contains("1bad"));
}

#[test]
fn slot_catalog_generator_rejects_metadata_that_does_not_describe_v8() {
    let source =
        CURRENT_INTERFACE_SPEC.replace("\"runtime_api_version\": 8", "\"runtime_api_version\": 9");
    let error = generate_slot_catalog_from_source(&source)
        .expect_err("the V8 Rust table cannot be generated from a V9 InterfaceSpec");

    assert!(error.contains("runtime_api_version"));
    assert!(error.contains("must be 8"));
}
