use super::super::super::super::super::root_paths::{
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_GUARD_CHILDREN_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_PATHS_CHILDREN_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SOURCE_HELPER_CHILDREN_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_LAYOUT_CHILD,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_STATUS_CURRENT_CHILDREN_CHILD,
};
use super::super::super::super::super::status_slices::{
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_GUARD,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_DATE,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_ID,
    TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_NAME,
};

pub(in super::super::super) fn assert_typed_error_status_doc_paths_child_inventory_status_is_current(
) {
    let anchors = [
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_GUARD_CHILDREN_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SOURCE_HELPER_CHILDREN_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_PATHS_CHILDREN_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_STATUS_CURRENT_CHILDREN_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_LAYOUT_CHILD,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_GUARD,
        "Cargo gate deferred",
    ];

    super::support::assert_documents_and_maps(
        "typed-error status-doc paths child-inventory split",
        &anchors,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_NAME,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_ID,
        TYPED_ERROR_STATUS_DOCS_PATHS_CHILD_INVENTORY_SPLIT_DATE,
    );
}
