use super::*;

#[test]
fn runtime_15_scene_script_row_data_export_chain_is_current() {
    let top_level = read_runtime_src(TOP_LEVEL_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15 = read_runtime_src(RUNTIME_15_EXPECTED_STATUS_ROW_DATA_PATH);
    let runtime_15_m3 = read_runtime_src(RUNTIME_15_M3_EXPECTED_STATUS_ROW_DATA_PATH);

    assert_contains_all(
        "Runtime 15 M3 exposes every scene-script child group",
        &runtime_15_m3,
        &[
            "SCENE_SCRIPT_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "SCENE_SCRIPT_TESTS_SCRIPT_VM_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES",
            "SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "SCENE_SCRIPT_TESTS_SCRIPT_VM_GAMEPLAY_SHADER_EXPECTED_STATUS_OUTPUT_SLICES",
            "SCENE_SCRIPT_TESTS_SCENE_ECS_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "SCENE_SCRIPT_TESTS_SCENE_ASSET_WORLD_EXPECTED_STATUS_OUTPUT_SLICES",
            "SCENE_SCRIPT_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "Runtime 15 row-data parent exports every scene-script child group",
        &runtime_15,
        &[
            "RUNTIME_15_M3_SCENE_SCRIPT_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCRIPT_VM_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCRIPT_VM_GAMEPLAY_SHADER_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCENE_ECS_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCENE_ASSET_WORLD_EXPECTED_STATUS_OUTPUT_SLICES",
            "RUNTIME_15_M3_SCENE_SCRIPT_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
    assert_contains_all(
        "top-level expected status row data consumes every scene-script child group",
        &top_level,
        &[
            "runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCRIPT_VM_RUNTIME_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_PLUGIN_EXTENSION_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCRIPT_VM_GAMEPLAY_SHADER_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCENE_ECS_TESTS_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_SCENE_ASSET_WORLD_EXPECTED_STATUS_OUTPUT_SLICES",
            "runtime_15::RUNTIME_15_M3_SCENE_SCRIPT_TESTS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES",
        ],
    );
}
