use super::*;

pub(super) const SCENE_SCRIPT_ROW_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data.rs",
        SCENE_SCRIPT_ROW_DATA_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        140,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests.rs",
        SCENE_SCRIPT_TESTS_ROWS_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/runtime_07_performance.rs",
        SCENE_SCRIPT_RUNTIME_07_PERFORMANCE_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/script_vm_runtime.rs",
        SCENE_SCRIPT_SCRIPT_VM_RUNTIME_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/plugin_extension_tests.rs",
        SCENE_SCRIPT_PLUGIN_EXTENSION_TESTS_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/script_vm_gameplay_shader.rs",
        SCENE_SCRIPT_GAMEPLAY_SHADER_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/scene_ecs_tests.rs",
        SCENE_SCRIPT_SCENE_ECS_TESTS_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/scene_asset_world.rs",
        SCENE_SCRIPT_SCENE_ASSET_WORLD_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/scene_script_tests/row_data_owner.rs",
        SCENE_SCRIPT_ROW_DATA_OWNER_PATH,
        90,
    ),
];
