#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RenderPassStage {
    DepthPrepass,
    Shadow,
    Deferred,
    AmbientOcclusion,
    Lighting,
    Opaque2d,
    AlphaMask2d,
    Transparent2d,
    Opaque3d,
    AlphaMask3d,
    Transparent3d,
    Opaque,
    Transparent,
    PostProcess,
    Ui,
    Overlay,
    Debug,
}
