import { Alert, Button, Chip, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import { useEffect, useMemo, useState } from "react";
import { actionClient, ControlActionError } from "../actions/actionClient";
import { canUseAction } from "../actions/catalog";
import type { ActionCatalog, ActionRecord, ControlAuthSession, JsonObject, SessionProjection } from "../api/contracts";
import { ActionDialog } from "../components/actions/ActionDialog";
import { HubPanel } from "../theme";

export function ActionsPage({ sessions, auth, onAuthChange }: { sessions: SessionProjection[]; auth: ControlAuthSession | null; onAuthChange: (session: ControlAuthSession) => void }) {
  const [catalog, setCatalog] = useState<ActionCatalog | null>(null); const [grant, setGrant] = useState(""); const [sessionId, setSessionId] = useState(() => new URLSearchParams(window.location.search).get("session") ?? "");
  const [template, setTemplate] = useState("coordinator-actions"); const [jobId, setJobId] = useState(""); const [preview, setPreview] = useState<ActionRecord | null>(null); const [history, setHistory] = useState<ActionRecord[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [comparison, setComparison] = useState<{ previous: ActionRecord; fresh: ActionRecord } | null>(null);
  useEffect(() => { actionClient.catalog().then(setCatalog).catch((issue) => setError(String(issue))); }, []);
  useEffect(() => { if (!sessionId) setSessionId(auth?.boundSessionId ?? sessions[0]?.sessionId ?? ""); }, [auth?.boundSessionId, sessionId, sessions]);
  const role = auth?.role ?? "observer"; const specs = useMemo(() => catalog?.actions ?? [], [catalog]);
  const elevate = async () => { setBusy(true); setError(null); try { const next = await actionClient.elevate(grant.trim()); onAuthChange(next); setGrant(""); } catch (issue) { setError(message(issue)); } finally { setBusy(false); } };
  const startPreview = async (kind: string) => { setBusy(true); setError(null); setComparison(null); try { const parameters: JsonObject = { sessionId }; if (kind === "validation.start") parameters.template = template; if (kind === "validation.cancel") parameters.jobId = jobId; const response = await actionClient.preview(kind, parameters); setPreview(response.action); setHistory((items) => [response.action, ...items]); } catch (issue) { setError(message(issue)); } finally { setBusy(false); } };
  const confirm = async (phrase: string, reason: string) => { if (!preview) return; const previous = preview; setBusy(true); setError(null); try { const response = await actionClient.confirm(previous.actionId, phrase, reason); setHistory((items) => [response.action, ...items.filter((item) => item.actionId !== response.action.actionId)]); setPreview(null); setComparison(null); } catch (issue) { if (issue instanceof ControlActionError && issue.code === "action_state_changed") { try { const refreshed = await actionClient.preview(previous.kind, previous.parameters); setPreview(refreshed.action); setComparison({ previous, fresh: refreshed.action }); setHistory((items) => [refreshed.action, ...items]); setError("状态已变化：已生成并显示新旧预览差异，操作尚未执行。"); } catch (refreshIssue) { setError(`状态已变化，但新预览失败：${message(refreshIssue)}`); } } else { setError(message(issue)); } } finally { setBusy(false); } };
  const cancel = async (reason: string) => { if (!preview) return; setBusy(true); try { const response = await actionClient.cancel(preview.actionId, reason); setHistory((items) => [response.action, ...items.filter((item) => item.actionId !== response.action.actionId)]); setPreview(null); setComparison(null); } catch (issue) { setError(message(issue)); } finally { setBusy(false); } };
  return <Stack spacing={2}>
    <HubPanel title="短期权限提升"><Stack spacing={1}><Typography variant="body2">在本机运行 `zircon-session control elevate --role operator --session-id &lt;id&gt;`，把一次性授权粘贴到这里。浏览器不能自行签发授权。</Typography><Stack direction={{ xs: "column", md: "row" }} spacing={1}><TextField fullWidth label="一次性提升授权" value={grant} onChange={(event) => setGrant(event.target.value)} type="password" autoComplete="off" /><Button variant="contained" onClick={elevate} disabled={busy || !grant.trim()}>提升权限</Button></Stack><Typography variant="body2">当前角色：<Chip size="small" label={role} /> {auth?.boundSessionId ? `绑定 ${auth.boundSessionId}` : "未绑定 Session"}</Typography></Stack></HubPanel>
    {error && <Alert severity="warning">{error}</Alert>}
    <HubPanel title="Action Catalog"><Stack spacing={2}><FormControl fullWidth><InputLabel id="action-session-label">目标 Session</InputLabel><Select labelId="action-session-label" label="目标 Session" value={sessionId} onChange={(event) => setSessionId(event.target.value)}>{sessions.map((session) => <MenuItem key={session.sessionId} value={session.sessionId}>{session.displayName ?? session.sessionId}</MenuItem>)}</Select></FormControl><Stack direction={{ xs: "column", md: "row" }} spacing={1}><FormControl sx={{ minWidth: 220 }}><InputLabel id="validation-template-label">验证模板</InputLabel><Select labelId="validation-template-label" label="验证模板" value={template} onChange={(event) => setTemplate(event.target.value)}><MenuItem value="coordinator-actions">协调器 Action 套件</MenuItem><MenuItem value="web-check">网页完整检查</MenuItem></Select></FormControl><TextField label="取消验证 Job ID" value={jobId} onChange={(event) => setJobId(event.target.value)} /></Stack><Stack direction="row" useFlexGap sx={{ flexWrap: "wrap", gap: 1 }}>{specs.map((spec) => { const enabled = canUseAction(role, spec.requiredRole, spec.enabled) && (!spec.sessionBound || auth?.boundSessionId === sessionId); return <Button key={spec.kind} variant="outlined" color={spec.risk === "red" ? "error" : "primary"} disabled={busy || !enabled || (spec.kind === "validation.cancel" && !jobId)} onClick={() => startPreview(spec.kind)}>{spec.title} · {spec.risk}{!spec.enabled ? "（待后续里程碑）" : ""}</Button>; })}</Stack></Stack></HubPanel>
    <HubPanel title="本页操作历史"><Stack spacing={1}>{history.length === 0 ? <Typography color="text.secondary">尚无操作</Typography> : history.map((item) => <Alert key={`${item.actionId}-${item.status}`} severity={item.status === "failed" || item.status === "state_changed" ? "warning" : "info"}>{item.kind} · {item.status} · {item.actionId.slice(0, 12)}</Alert>)}</Stack></HubPanel>
    <ActionDialog action={preview} comparison={comparison} busy={busy} error={error} onConfirm={confirm} onCancel={cancel} onClose={() => { setPreview(null); setComparison(null); }} />
  </Stack>;
}

function message(issue: unknown): string { return issue instanceof Error ? issue.message : "受控操作失败"; }
