type Slice = super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 priority plan docs guard-test listing guard",
        &[
            "runtime_15_priority_plan_docs_guard_test_listing_guard_static_passed_cargo_deferred",
            "docs/plans/engine-code-structure-convention.md",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/listing.rs",
            "runtime_15_priority_plan_docs_guard_tests_stay_listed",
            "priority_plan_docs/code_paths.rs::runtime_15_priority_plan_docs_code_paths_stay_current",
            "priority_plan_docs/test_paths.rs::runtime_15_priority_plan_docs_test_paths_stay_current",
            "priority_plan_docs/frontmatter_status.rs::runtime_15_priority_plan_docs_frontmatter_status_stays_current",
            "priority_plan_docs/frontmatter_uniqueness.rs::runtime_15_priority_plan_docs_frontmatter_sections_have_unique_entries",
            "priority_plan_docs/header_sections.rs::runtime_15_priority_plan_docs_required_header_sections_stay_complete",
            "priority_plan_docs/plan_sources.rs::runtime_15_priority_plan_docs_plan_sources_stay_cross_linked",
            "priority_plan_docs/guard_tests/child_layout.rs::runtime_15_priority_plan_docs_guard_children_are_folder_backed",
            "priority_plan_docs/guard_tests/inventory_sync.rs::runtime_15_priority_plan_docs_guard_inventory_uses_child_row_data_sources",
            "priority_plan_docs/guard_tests/inventory_sync.rs::runtime_15_priority_plan_docs_listing_prose_names_full_inventory",
            "priority_plan_docs/guard_tests/nested_layout.rs::runtime_15_priority_plan_docs_guard_test_child_prose_names_full_inventory",
            "priority_plan_docs/guard_tests/nested_layout.rs::runtime_15_priority_plan_docs_guard_test_children_are_folder_backed",
            "priority_plan_docs/guard_tests/moved_paths.rs::runtime_15_priority_plan_docs_moved_guard_paths_stay_current",
            "priority_plan_docs/guard_tests/moved_paths.rs::runtime_15_priority_plan_docs_moved_mirror_names_full_inventory",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs guard child-owner split",
        &[
            "runtime_15_priority_plan_docs_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/priority_plan_docs.rs",
            "structure_convention/test_file_budget/priority_plan_docs/code_paths.rs",
            "structure_convention/test_file_budget/priority_plan_docs/test_paths.rs",
            "structure_convention/test_file_budget/priority_plan_docs/frontmatter_status.rs",
            "structure_convention/test_file_budget/priority_plan_docs/frontmatter_uniqueness.rs",
            "structure_convention/test_file_budget/priority_plan_docs/header_sections.rs",
            "structure_convention/test_file_budget/priority_plan_docs/plan_sources.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/inventory_sync.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/moved_paths.rs",
            "runtime_15_priority_plan_docs_guard_children_are_folder_backed",
            "full priority-plan-doc child inventory",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs child prose full inventory sync",
        &[
            "runtime_15_priority_plan_docs_child_prose_full_inventory_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/child_layout.rs",
            "priority_plan_docs/guard_tests/child_layout.rs::runtime_15_priority_plan_docs_guard_children_are_folder_backed",
            "structure_convention/test_file_budget/priority_plan_docs/code_paths.rs",
            "structure_convention/test_file_budget/priority_plan_docs/frontmatter_status.rs",
            "structure_convention/test_file_budget/priority_plan_docs/frontmatter_uniqueness.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests.rs",
            "structure_convention/test_file_budget/priority_plan_docs/header_sections.rs",
            "structure_convention/test_file_budget/priority_plan_docs/plan_sources.rs",
            "structure_convention/test_file_budget/priority_plan_docs/test_paths.rs",
            "full priority-plan-doc child inventory",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs guard-test child-owner split",
        &[
            "runtime_15_priority_plan_docs_guard_test_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/child_layout.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/inventory_sync.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/listing.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/moved_paths.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/nested_layout.rs",
            "runtime_15_priority_plan_docs_guard_test_children_are_folder_backed",
            "full priority-plan-doc guard-test child inventory",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs guard-test child prose full inventory sync",
        &[
            "runtime_15_priority_plan_docs_guard_test_child_prose_full_inventory_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/nested_layout.rs",
            "runtime_15_priority_plan_docs_guard_test_child_prose_names_full_inventory",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/child_layout.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/inventory_sync.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/listing.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/moved_paths.rs",
            "structure_convention/test_file_budget/priority_plan_docs/guard_tests/nested_layout.rs",
            "full priority-plan-doc guard-test child inventory",
            "Cargo gate deferred",
        ],
    ),
];
