pub(super) mod activity_view_descriptors;
mod assets_view_descriptor;
mod build_export_view_descriptor;
mod console_view_descriptor;
mod game_view_descriptor;
mod hierarchy_view_descriptor;
mod inspector_view_descriptor;
mod module_plugins_view_descriptor;
mod project_view_descriptor;
mod runtime_diagnostics_view_descriptor;
mod scene_view_descriptor;
