import { Box, Chip, Stack, Typography } from "@mui/material";
import type { AnalyticsActiveTask, AnalyticsBucket, AnalyticsDurationRow, AnalyticsModuleShare, AnalyticsPatchStatus, AnalyticsPlanProgress, AnalyticsRecentWorkflow, AnalyticsScheduleSlot } from "./analyticsModel";

const chartColors = { completed: "#77d77a", failed: "#ef655e", started: "#21d5cf", queued: "#ffc24d", running: "#4db6ff" } as const;

export function AnalyticsLineChart({ buckets }: { buckets: AnalyticsBucket[] }) {
  const width = 720;
  const height = 230;
  const pad = { top: 20, right: 18, bottom: 34, left: 32 };
  const max = Math.max(1, ...buckets.map((bucket) => Math.max(bucket.started, bucket.completed, bucket.failed)));
  const points = (key: "started" | "completed" | "failed") => buckets.map((bucket, index) => `${pointX(index, buckets.length, width, pad)},${pointY(bucket[key], max, height, pad)}`).join(" ");
  return <Stack spacing={1} aria-label="最近二十四小时任务趋势"><Stack direction="row" spacing={1.5} sx={{ alignItems: "center", flexWrap: "wrap" }}><Legend color={chartColors.started} label="开始" /><Legend color={chartColors.completed} label="完成" /><Legend color={chartColors.failed} label="失败" /><Typography variant="caption" color="text.secondary" sx={{ ml: "auto" }}>按 ticket 创建和终态更新时间统计</Typography></Stack><Box sx={{ width: "100%", overflow: "hidden" }}><svg role="img" aria-label="最近二十四小时开始、完成、失败趋势折线图" viewBox={`0 0 ${width} ${height}`} width="100%" height="230" preserveAspectRatio="none">
    {[0, 0.5, 1].map((ratio) => <g key={ratio}><line x1={pad.left} x2={width - pad.right} y1={pointY(max * ratio, max, height, pad)} y2={pointY(max * ratio, max, height, pad)} stroke="rgba(255,255,255,.12)" strokeWidth="1" /><text x={pad.left - 6} y={pointY(max * ratio, max, height, pad) + 4} textAnchor="end" fill="#8d8d8d" fontSize="10">{Math.round(max * ratio)}</text></g>)}
    <polyline points={points("started")} fill="none" stroke={chartColors.started} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" />
    <polyline points={points("completed")} fill="none" stroke={chartColors.completed} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" />
    <polyline points={points("failed")} fill="none" stroke={chartColors.failed} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" />
    {buckets.map((bucket, index) => index % 4 === 0 && <text key={bucket.label} x={pointX(index, buckets.length, width, pad)} y={height - 10} textAnchor="middle" fill="#8d8d8d" fontSize="10">{bucket.label}</text>)}
  </svg></Box></Stack>;
}

export function AnalyticsDurationChart({ rows }: { rows: AnalyticsDurationRow[] }) {
  const max = Math.max(1, ...rows.map((row) => row.seconds));
  return <Stack spacing={1} aria-label="流程处理耗时柱状图">{rows.length === 0 ? <EmptyChart label="暂无可计算的流程耗时" /> : rows.map((row) => <Stack key={row.id} spacing={0.35} sx={{ minWidth: 0 }}><Stack direction="row" spacing={1} sx={{ alignItems: "baseline" }}><Typography variant="body2" sx={{ flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }} title={row.label}>{row.label}</Typography><Typography variant="caption" color="text.secondary">{formatDuration(row.seconds)}</Typography></Stack><Box sx={{ height: 12, bgcolor: "action.hover", borderRadius: 999, overflow: "hidden" }}><Box sx={{ width: `${Math.max(3, (row.seconds / max) * 100)}%`, height: "100%", bgcolor: row.status === "failed" ? chartColors.failed : row.status === "passed" ? chartColors.completed : row.status === "running" ? chartColors.running : chartColors.started, transition: "width 180ms ease-out" }} /></Box><Typography variant="caption" color="text.secondary">{row.detail}</Typography></Stack>)}</Stack>;
}

export function AnalyticsSchedule({ slots }: { slots: AnalyticsScheduleSlot[] }) {
  const max = Math.max(1, ...slots.map((slot) => slot.queued + slot.running + slot.completed + slot.failed));
  return <Stack spacing={1} aria-label="二十四小时任务时间轴"><Stack direction="row" spacing={0.5} sx={{ alignItems: "end", height: 142, overflow: "hidden" }}>{slots.map((slot) => { const total = slot.queued + slot.running + slot.completed + slot.failed; const height = Math.max(total ? 8 : 2, Math.round((total / max) * 112)); return <Stack key={slot.hour} spacing={0.5} sx={{ flex: 1, minWidth: 8, height: 134, justifyContent: "end", alignItems: "center" }} title={`${slot.label} · 排队 ${slot.queued} · 运行 ${slot.running} · 完成 ${slot.completed} · 失败 ${slot.failed}`}><Box sx={{ width: "100%", maxWidth: 22, height, bgcolor: slot.failed ? chartColors.failed : slot.running ? chartColors.running : slot.queued ? chartColors.queued : slot.completed ? chartColors.completed : "rgba(255,255,255,.12)", borderRadius: "4px 4px 1px 1px" }} /><Typography variant="caption" color="text.secondary" sx={{ fontSize: 10, visibility: slot.hour % 4 === 0 ? "visible" : "hidden" }}>{String(slot.hour).padStart(2, "0")}</Typography></Stack>; })}</Stack><Stack direction="row" spacing={1.25} sx={{ flexWrap: "wrap" }}><Legend color={chartColors.queued} label="排队/登记" /><Legend color={chartColors.running} label="运行" /><Legend color={chartColors.completed} label="完成" /><Legend color={chartColors.failed} label="失败" /></Stack><Typography variant="caption" color="text.secondary">每根柱代表该小时内观察到的任务活动；无数据的小时仍保留时间位置。</Typography></Stack>;
}

export function FailureDonut({ open, fixed, ratio, loading = false }: { open: number; fixed: number; ratio: number; loading?: boolean }) {
  const radius = 43;
  const circumference = 2 * Math.PI * radius;
  const openLength = circumference * Math.max(0, Math.min(1, ratio));
  return <Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ alignItems: "center" }} aria-label="当前 Failure 占比环图"><Box sx={{ width: 150, height: 150, flex: "0 0 auto" }}><svg role="img" aria-label={loading ? `Failure 历史采样中，当前开放 ${open}` : `当前开放 Failure ${open}，已修复 ${fixed}`} viewBox="0 0 120 120" width="150" height="150"><circle cx="60" cy="60" r={radius} fill="none" stroke="rgba(255,255,255,.12)" strokeWidth="14" /><circle cx="60" cy="60" r={radius} fill="none" stroke={loading ? "#8d8d8d" : chartColors.failed} strokeWidth="14" strokeDasharray={loading ? "10 8" : `${openLength} ${circumference - openLength}`} transform="rotate(-90 60 60)" strokeLinecap="butt" /><text x="60" y="56" textAnchor="middle" fill="#eee" fontSize={loading ? "11" : "18"} fontWeight="700">{loading ? "采样中" : `${Math.round(ratio * 100)}%`}</text><text x="60" y="72" textAnchor="middle" fill="#b9b9b9" fontSize="9">当前开放</text></svg></Box><Stack spacing={1} sx={{ minWidth: 0 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center" }}><Legend color={chartColors.failed} label="开放" /><Typography variant="h6">{open}</Typography></Stack><Stack direction="row" spacing={1} sx={{ alignItems: "center" }}><Legend color={chartColors.completed} label="已修复" /><Typography variant="h6">{loading ? "—" : fixed}</Typography></Stack><Typography variant="caption" color="text.secondary">{loading ? "当前开放数来自实时快照；占比和已修复数正在加载历史窗口。" : "占比只在当前 Failure 历史窗口内计算；修复平均耗时由已闭合链路计算。"}</Typography></Stack></Stack>;
}

export function AnalyticsFlow({ rows }: { rows: Array<{ label: string; value: number; tone: "info" | "warning" | "success" | "danger" | "neutral" }> }) {
  const max = Math.max(1, ...rows.map((row) => row.value));
  const colors = { info: chartColors.running, warning: chartColors.queued, success: chartColors.completed, danger: chartColors.failed, neutral: "#8d8d8d" };
  return <Stack spacing={1} aria-label="验证任务流转图">{rows.map((row) => <Stack key={row.label} direction="row" spacing={1} sx={{ alignItems: "center" }}><Typography variant="body2" sx={{ width: 48 }}>{row.label}</Typography><Box sx={{ flex: 1, height: 16, bgcolor: "action.hover", borderRadius: 1, overflow: "hidden" }}><Box sx={{ width: `${Math.max(row.value ? 4 : 0, (row.value / max) * 100)}%`, height: "100%", bgcolor: colors[row.tone] }} /></Box><Typography variant="body2" sx={{ width: 44, textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{row.value}</Typography></Stack>)}</Stack>;
}

export function ModuleShareChart({ rows }: { rows: AnalyticsModuleShare[] }) {
  const colors = ["#21d5cf", "#4db6ff", "#77d77a", "#ffc24d", "#ef655e", "#b8a7ff"];
  return <Stack spacing={1} aria-label="模块目录占比图">{rows.length === 0 ? <EmptyChart label="当前没有可归类的计划目录" /> : rows.map((row, index) => <Stack key={row.label} spacing={0.35}><Stack direction="row" spacing={1} sx={{ alignItems: "baseline" }}><Typography variant="body2" sx={{ flex: 1, overflowWrap: "anywhere" }}>{row.label}</Typography><Typography variant="caption" color="text.secondary">{row.count} · {Math.round(row.ratio * 100)}%</Typography></Stack><Box sx={{ height: 8, bgcolor: "action.hover", borderRadius: 999, overflow: "hidden" }}><Box sx={{ width: `${Math.max(row.count ? 3 : 0, row.ratio * 100)}%`, height: "100%", bgcolor: colors[index % colors.length] }} /></Box></Stack>)}</Stack>;
}

export function PlanProgressChart({ rows }: { rows: AnalyticsPlanProgress[] }) {
  return <Stack spacing={1} aria-label="计划完成与 Todo 进度">{rows.length === 0 ? <EmptyChart label="暂无计划进度样本" /> : rows.map((row) => { const checklistSize = Math.min(16, row.nodeCount); return <Stack key={row.id} spacing={0.5} sx={{ minWidth: 0 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center" }}><Typography variant="body2" sx={{ flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }} title={row.id}>{row.label}</Typography><Chip size="small" variant="outlined" color={row.status === "blocked" ? "error" : row.status === "complete" ? "success" : "default"} label={row.status === "blocked" ? "阻塞" : row.status === "complete" ? "完成" : row.status === "in_progress" ? "进行中" : "排队"} /><Typography variant="caption">{row.ratio}%</Typography></Stack><Box sx={{ height: 10, bgcolor: "action.hover", borderRadius: 999, overflow: "hidden" }}><Box sx={{ width: `${row.ratio}%`, height: "100%", bgcolor: row.status === "blocked" ? chartColors.failed : row.status === "complete" ? chartColors.completed : chartColors.started }} /></Box><Stack direction="row" spacing={0.45} sx={{ alignItems: "center", flexWrap: "wrap" }} aria-label={`${row.label} 完成清单`} title="每格代表一个已完成或 Todo 节点"><Typography variant="caption" color="text.secondary">清单</Typography>{Array.from({ length: checklistSize }, (_, index) => <Box key={index} component="span" sx={{ width: 12, height: 12, border: "1px solid", borderColor: index < row.completedCount ? "success.main" : row.failedCount && index < row.completedCount + row.failedCount ? "error.main" : "text.disabled", bgcolor: index < row.completedCount ? "success.main" : "transparent", position: "relative" }} aria-label={index < row.completedCount ? "已完成" : row.failedCount && index < row.completedCount + row.failedCount ? "失败" : "Todo"}>{index < row.completedCount ? <Box component="span" sx={{ position: "absolute", left: 2, top: 1, width: 6, height: 3, borderLeft: "1px solid", borderBottom: "1px solid", borderColor: "common.black", transform: "rotate(-45deg)" }} /> : null}</Box>)}{checklistSize < row.nodeCount ? <Typography variant="caption" color="text.secondary">+{row.nodeCount - checklistSize}</Typography> : null}</Stack><Typography variant="caption" color="text.secondary">完成 {row.completedCount} · Todo {row.todoCount} · Failure {row.failedCount} · {row.workflowCount} 个工作流</Typography></Stack>; })}</Stack>;
}

export function PatchStatusChart({ rows }: { rows: AnalyticsPatchStatus[] }) {
  return <Stack spacing={1} aria-label="Failure 链补丁状态">{rows.map((row) => <Stack key={row.label} direction="row" spacing={1} sx={{ alignItems: "center" }}><Typography variant="body2" sx={{ width: 68 }}>{row.label}</Typography><Box sx={{ flex: 1, height: 16, bgcolor: "action.hover", borderRadius: 1, overflow: "hidden" }}><Box sx={{ width: `${row.value ? Math.max(5, (row.value / Math.max(1, ...rows.map((item) => item.value))) * 100) : 0}%`, height: "100%", bgcolor: row.tone === "danger" ? chartColors.failed : row.tone === "success" ? chartColors.completed : row.tone === "warning" ? chartColors.queued : row.tone === "info" ? chartColors.running : "#8d8d8d" }} /></Box><Typography variant="body2" sx={{ width: 36, textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{row.value}</Typography></Stack>)}</Stack>;
}

export function ActiveTaskTable({ rows }: { rows: AnalyticsActiveTask[] }) {
  return <Stack spacing={0.75} aria-label="当前 CPU 和验证任务">{rows.length === 0 ? <EmptyChart label="当前没有占用验证通道的任务" /> : rows.map((row) => <Stack key={row.id} direction="row" spacing={1} sx={{ alignItems: "center", minWidth: 0, borderLeft: 3, borderColor: row.lane === "gpu" ? chartColors.running : chartColors.started, pl: 1 }}><Stack spacing={0.15} sx={{ minWidth: 0, flex: 1 }}><Typography variant="body2" sx={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }} title={row.sessionId}>{row.sessionId}</Typography><Typography variant="caption" color="text.secondary">{row.lane.toUpperCase()} · {row.status} · {row.id}</Typography></Stack><Typography variant="caption" sx={{ fontVariantNumeric: "tabular-nums" }}>{row.elapsedSeconds === null ? "耗时未知" : formatDuration(row.elapsedSeconds)}</Typography></Stack>)}</Stack>;
}

export function RecentWorkflowList({ rows }: { rows: AnalyticsRecentWorkflow[] }) {
  return <Stack spacing={0.8} aria-label="最近工作流">{rows.length === 0 ? <EmptyChart label="暂无最近工作流" /> : rows.map((row) => <Stack key={row.id} spacing={0.35} sx={{ minWidth: 0, borderLeft: 3, borderColor: row.failedCount ? chartColors.failed : row.progress === 100 ? chartColors.completed : chartColors.started, pl: 1 }}><Stack direction="row" spacing={1}><Typography variant="body2" sx={{ flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }} title={row.label}>{row.label}</Typography><Typography variant="caption">{row.progress}%</Typography></Stack><Box sx={{ height: 7, bgcolor: "action.hover", borderRadius: 999, overflow: "hidden" }}><Box sx={{ width: `${row.progress}%`, height: "100%", bgcolor: row.failedCount ? chartColors.failed : row.progress === 100 ? chartColors.completed : chartColors.started }} /></Box><Typography variant="caption" color="text.secondary" sx={{ overflowWrap: "anywhere" }}>{row.planPath} · {row.state}{row.failedCount ? ` · ${row.failedCount} 失败` : ""}</Typography></Stack>)}</Stack>;
}

function Legend({ color, label }: { color: string; label: string }) { return <Stack direction="row" spacing={0.5} sx={{ alignItems: "center" }}><Box sx={{ width: 9, height: 9, borderRadius: "50%", bgcolor: color }} /><Typography variant="caption" color="text.secondary">{label}</Typography></Stack>; }
function EmptyChart({ label }: { label: string }) { return <Typography variant="body2" color="text.secondary" sx={{ py: 1 }}>{label}</Typography>; }
function pointX(index: number, count: number, width: number, pad: { left: number; right: number }): number { return pad.left + (index / Math.max(1, count - 1)) * (width - pad.left - pad.right); }
function pointY(value: number, max: number, height: number, pad: { top: number; bottom: number }): number { return height - pad.bottom - (value / Math.max(1, max)) * (height - pad.top - pad.bottom); }
export function formatDuration(seconds: number): string { if (!Number.isFinite(seconds)) return "耗时未知"; if (seconds < 60) return `${seconds} 秒`; const minutes = Math.floor(seconds / 60); if (minutes < 60) return `${minutes} 分 ${seconds % 60} 秒`; return `${Math.floor(minutes / 60)} 小时 ${minutes % 60} 分`; }
