use super::types::{ActionControl, ExtensionNavigationSpec, action, spec};

const SHADER_EDITOR_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionShaderSourceTab",
    "WorkbenchExtensionShaderResourcesTab",
    "WorkbenchExtensionShaderIssuesTab",
];
const SHADER_EDITOR_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.shader_editor.source_tab.select",
        "WorkbenchExtensionShaderSourceTab",
    ),
    action(
        "workbench.extension.shader_editor.resources_tab.select",
        "WorkbenchExtensionShaderResourcesTab",
    ),
    action(
        "workbench.extension.shader_editor.issues_tab.select",
        "WorkbenchExtensionShaderIssuesTab",
    ),
];
const SHADER_EDITOR_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionShaderSourceRow",
    "WorkbenchExtensionShaderIncludeRow",
    "WorkbenchExtensionShaderPermutationRow",
    "WorkbenchExtensionShaderVertexRow",
    "WorkbenchExtensionShaderFragmentRow",
    "WorkbenchExtensionShaderComputeRow",
    "WorkbenchExtensionShaderCommonRow",
    "WorkbenchExtensionShaderOutputRow",
];
const SHADER_EDITOR_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.shader_editor.source_row.select",
        "WorkbenchExtensionShaderSourceRow",
    ),
    action(
        "workbench.extension.shader_editor.include_row.select",
        "WorkbenchExtensionShaderIncludeRow",
    ),
    action(
        "workbench.extension.shader_editor.permutation_row.select",
        "WorkbenchExtensionShaderPermutationRow",
    ),
    action(
        "workbench.extension.shader_editor.vertex_row.select",
        "WorkbenchExtensionShaderVertexRow",
    ),
    action(
        "workbench.extension.shader_editor.fragment_row.select",
        "WorkbenchExtensionShaderFragmentRow",
    ),
    action(
        "workbench.extension.shader_editor.compute_row.select",
        "WorkbenchExtensionShaderComputeRow",
    ),
    action(
        "workbench.extension.shader_editor.common_row.select",
        "WorkbenchExtensionShaderCommonRow",
    ),
    action(
        "workbench.extension.shader_editor.output.select",
        "WorkbenchExtensionShaderOutputRow",
    ),
];
const SHADER_EDITOR_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchRenderShaderEditorButton",
    "WorkbenchExtensionShaderPreviewButton",
    "WorkbenchExtensionShaderCompileButton",
];
const SHADER_EDITOR_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.shader_editor.open",
        "WorkbenchRenderShaderEditorButton",
    ),
    action(
        "workbench.extension.shader_editor.preview.invoke",
        "WorkbenchExtensionShaderPreviewButton",
    ),
    action(
        "workbench.extension.shader_editor.compile.invoke",
        "WorkbenchExtensionShaderCompileButton",
    ),
];
const SHADER_EDITOR_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.shader_editor.target.edit",
    "workbench.extension.shader_editor.target.commit",
    "workbench.extension.shader_editor.entry.edit",
    "workbench.extension.shader_editor.entry.commit",
    "workbench.extension.shader_editor.live_compile.edit",
    "workbench.extension.shader_editor.live_compile.commit",
];

pub(super) const SHADER_EDITOR_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.shader_editor.open",
    "WorkbenchExtensionShaderEditorWorkspace",
    SHADER_EDITOR_TAB_CONTROLS,
    SHADER_EDITOR_TAB_ACTIONS,
    SHADER_EDITOR_ROW_CONTROLS,
    SHADER_EDITOR_ROW_ACTIONS,
    SHADER_EDITOR_COMMAND_CONTROLS,
    SHADER_EDITOR_COMMAND_ACTIONS,
    SHADER_EDITOR_FIELD_ACTIONS,
);
const LIGHTING_BAKE_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionLightingBakeLevelsTab",
    "WorkbenchExtensionLightingBakeProbesTab",
    "WorkbenchExtensionLightingBakeWarningsTab",
];
const LIGHTING_BAKE_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.lighting_bake.levels_tab.select",
        "WorkbenchExtensionLightingBakeLevelsTab",
    ),
    action(
        "workbench.extension.lighting_bake.probes_tab.select",
        "WorkbenchExtensionLightingBakeProbesTab",
    ),
    action(
        "workbench.extension.lighting_bake.warnings_tab.select",
        "WorkbenchExtensionLightingBakeWarningsTab",
    ),
];
const LIGHTING_BAKE_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionLightingBakeSceneBakeRow",
    "WorkbenchExtensionLightingBakeInteriorBakeRow",
    "WorkbenchExtensionLightingBakeReflectionProbeRow",
    "WorkbenchExtensionLightingBakeShadowMapTableRow",
    "WorkbenchExtensionLightingBakeLightmapUvTableRow",
    "WorkbenchExtensionLightingBakeProbeGridTableRow",
    "WorkbenchExtensionLightingBakeBleedWarningTableRow",
    "WorkbenchExtensionLightingBakeOutputRow",
];
const LIGHTING_BAKE_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.lighting_bake.scene_bake_row.select",
        "WorkbenchExtensionLightingBakeSceneBakeRow",
    ),
    action(
        "workbench.extension.lighting_bake.interior_bake_row.select",
        "WorkbenchExtensionLightingBakeInteriorBakeRow",
    ),
    action(
        "workbench.extension.lighting_bake.reflection_probe_row.select",
        "WorkbenchExtensionLightingBakeReflectionProbeRow",
    ),
    action(
        "workbench.extension.lighting_bake.shadow_map_table_row.select",
        "WorkbenchExtensionLightingBakeShadowMapTableRow",
    ),
    action(
        "workbench.extension.lighting_bake.lightmap_uv_table_row.select",
        "WorkbenchExtensionLightingBakeLightmapUvTableRow",
    ),
    action(
        "workbench.extension.lighting_bake.probe_grid_table_row.select",
        "WorkbenchExtensionLightingBakeProbeGridTableRow",
    ),
    action(
        "workbench.extension.lighting_bake.bleed_warning_table_row.select",
        "WorkbenchExtensionLightingBakeBleedWarningTableRow",
    ),
    action(
        "workbench.extension.lighting_bake.output.select",
        "WorkbenchExtensionLightingBakeOutputRow",
    ),
];
const LIGHTING_BAKE_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchRenderLightingBakeButton",
    "WorkbenchExtensionLightingBakePreviewButton",
    "WorkbenchExtensionLightingBakeBakeButton",
];
const LIGHTING_BAKE_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.lighting_bake.open",
        "WorkbenchRenderLightingBakeButton",
    ),
    action(
        "workbench.extension.lighting_bake.preview.invoke",
        "WorkbenchExtensionLightingBakePreviewButton",
    ),
    action(
        "workbench.extension.lighting_bake.bake.invoke",
        "WorkbenchExtensionLightingBakeBakeButton",
    ),
];
const LIGHTING_BAKE_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.lighting_bake.quality.edit",
    "workbench.extension.lighting_bake.quality.commit",
    "workbench.extension.lighting_bake.target.edit",
    "workbench.extension.lighting_bake.target.commit",
    "workbench.extension.lighting_bake.denoise.edit",
    "workbench.extension.lighting_bake.denoise.commit",
];

pub(super) const LIGHTING_BAKE_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.lighting_bake.open",
    "WorkbenchExtensionLightingBakeWorkspace",
    LIGHTING_BAKE_TAB_CONTROLS,
    LIGHTING_BAKE_TAB_ACTIONS,
    LIGHTING_BAKE_ROW_CONTROLS,
    LIGHTING_BAKE_ROW_ACTIONS,
    LIGHTING_BAKE_COMMAND_CONTROLS,
    LIGHTING_BAKE_COMMAND_ACTIONS,
    LIGHTING_BAKE_FIELD_ACTIONS,
);
const POST_PROCESS_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionPostProcessStackTab",
    "WorkbenchExtensionPostProcessVolumesTab",
    "WorkbenchExtensionPostProcessWarningsTab",
];
const POST_PROCESS_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.post_process.stack_tab.select",
        "WorkbenchExtensionPostProcessStackTab",
    ),
    action(
        "workbench.extension.post_process.volumes_tab.select",
        "WorkbenchExtensionPostProcessVolumesTab",
    ),
    action(
        "workbench.extension.post_process.warnings_tab.select",
        "WorkbenchExtensionPostProcessWarningsTab",
    ),
];
const POST_PROCESS_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionPostProcessGlobalStackRow",
    "WorkbenchExtensionPostProcessCinematicStackRow",
    "WorkbenchExtensionPostProcessVolumeBlendRow",
    "WorkbenchExtensionPostProcessBloomTableRow",
    "WorkbenchExtensionPostProcessTonemapTableRow",
    "WorkbenchExtensionPostProcessLutTableRow",
    "WorkbenchExtensionPostProcessExposureWarningTableRow",
    "WorkbenchExtensionPostProcessOutputRow",
];
const POST_PROCESS_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.post_process.global_stack_row.select",
        "WorkbenchExtensionPostProcessGlobalStackRow",
    ),
    action(
        "workbench.extension.post_process.cinematic_stack_row.select",
        "WorkbenchExtensionPostProcessCinematicStackRow",
    ),
    action(
        "workbench.extension.post_process.volume_blend_row.select",
        "WorkbenchExtensionPostProcessVolumeBlendRow",
    ),
    action(
        "workbench.extension.post_process.bloom_table_row.select",
        "WorkbenchExtensionPostProcessBloomTableRow",
    ),
    action(
        "workbench.extension.post_process.tonemap_table_row.select",
        "WorkbenchExtensionPostProcessTonemapTableRow",
    ),
    action(
        "workbench.extension.post_process.lut_table_row.select",
        "WorkbenchExtensionPostProcessLutTableRow",
    ),
    action(
        "workbench.extension.post_process.exposure_warning_table_row.select",
        "WorkbenchExtensionPostProcessExposureWarningTableRow",
    ),
    action(
        "workbench.extension.post_process.output.select",
        "WorkbenchExtensionPostProcessOutputRow",
    ),
];
const POST_PROCESS_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchRenderPostProcessButton",
    "WorkbenchExtensionPostProcessPreviewButton",
    "WorkbenchExtensionPostProcessApplyButton",
];
const POST_PROCESS_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.post_process.open",
        "WorkbenchRenderPostProcessButton",
    ),
    action(
        "workbench.extension.post_process.preview.invoke",
        "WorkbenchExtensionPostProcessPreviewButton",
    ),
    action(
        "workbench.extension.post_process.apply.invoke",
        "WorkbenchExtensionPostProcessApplyButton",
    ),
];
const POST_PROCESS_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.post_process.profile.edit",
    "workbench.extension.post_process.profile.commit",
    "workbench.extension.post_process.volume.edit",
    "workbench.extension.post_process.volume.commit",
    "workbench.extension.post_process.blend.edit",
    "workbench.extension.post_process.blend.commit",
];

pub(super) const POST_PROCESS_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.post_process.open",
    "WorkbenchExtensionPostProcessWorkspace",
    POST_PROCESS_TAB_CONTROLS,
    POST_PROCESS_TAB_ACTIONS,
    POST_PROCESS_ROW_CONTROLS,
    POST_PROCESS_ROW_ACTIONS,
    POST_PROCESS_COMMAND_CONTROLS,
    POST_PROCESS_COMMAND_ACTIONS,
    POST_PROCESS_FIELD_ACTIONS,
);
const PARTICLE_LIBRARY_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionParticleLibraryEmittersTab",
    "WorkbenchExtensionParticleLibraryMetadataTab",
    "WorkbenchExtensionParticleLibraryCompileTab",
];
const PARTICLE_LIBRARY_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.particle_library.emitters_tab.select",
        "WorkbenchExtensionParticleLibraryEmittersTab",
    ),
    action(
        "workbench.extension.particle_library.metadata_tab.select",
        "WorkbenchExtensionParticleLibraryMetadataTab",
    ),
    action(
        "workbench.extension.particle_library.compile_tab.select",
        "WorkbenchExtensionParticleLibraryCompileTab",
    ),
];
const PARTICLE_LIBRARY_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionParticleLibrarySparksRow",
    "WorkbenchExtensionParticleLibraryDustRow",
    "WorkbenchExtensionParticleLibraryImpactRow",
    "WorkbenchExtensionParticleLibraryGpuSparkRow",
    "WorkbenchExtensionParticleLibraryCpuDustRow",
    "WorkbenchExtensionParticleLibraryImpactGpuRow",
    "WorkbenchExtensionParticleLibraryArchivedRow",
    "WorkbenchExtensionParticleLibraryOutputRow",
];
const PARTICLE_LIBRARY_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.particle_library.sparks_row.select",
        "WorkbenchExtensionParticleLibrarySparksRow",
    ),
    action(
        "workbench.extension.particle_library.dust_row.select",
        "WorkbenchExtensionParticleLibraryDustRow",
    ),
    action(
        "workbench.extension.particle_library.impact_row.select",
        "WorkbenchExtensionParticleLibraryImpactRow",
    ),
    action(
        "workbench.extension.particle_library.gpu_spark_row.select",
        "WorkbenchExtensionParticleLibraryGpuSparkRow",
    ),
    action(
        "workbench.extension.particle_library.cpu_dust_row.select",
        "WorkbenchExtensionParticleLibraryCpuDustRow",
    ),
    action(
        "workbench.extension.particle_library.impact_gpu_row.select",
        "WorkbenchExtensionParticleLibraryImpactGpuRow",
    ),
    action(
        "workbench.extension.particle_library.archived_row.select",
        "WorkbenchExtensionParticleLibraryArchivedRow",
    ),
    action(
        "workbench.extension.particle_library.output.select",
        "WorkbenchExtensionParticleLibraryOutputRow",
    ),
];
const PARTICLE_LIBRARY_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchVfxParticleLibraryButton",
    "WorkbenchExtensionParticleLibrarySimulateButton",
    "WorkbenchExtensionParticleLibraryCompileButton",
];
const PARTICLE_LIBRARY_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.particle_library.open",
        "WorkbenchVfxParticleLibraryButton",
    ),
    action(
        "workbench.extension.particle_library.simulate.invoke",
        "WorkbenchExtensionParticleLibrarySimulateButton",
    ),
    action(
        "workbench.extension.particle_library.compile.invoke",
        "WorkbenchExtensionParticleLibraryCompileButton",
    ),
];
const PARTICLE_LIBRARY_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.particle_library.emitter.edit",
    "workbench.extension.particle_library.emitter.commit",
    "workbench.extension.particle_library.duration.edit",
    "workbench.extension.particle_library.duration.commit",
    "workbench.extension.particle_library.bounds.edit",
    "workbench.extension.particle_library.bounds.commit",
];

pub(super) const PARTICLE_LIBRARY_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.particle_library.open",
    "WorkbenchExtensionParticleLibraryWorkspace",
    PARTICLE_LIBRARY_TAB_CONTROLS,
    PARTICLE_LIBRARY_TAB_ACTIONS,
    PARTICLE_LIBRARY_ROW_CONTROLS,
    PARTICLE_LIBRARY_ROW_ACTIONS,
    PARTICLE_LIBRARY_COMMAND_CONTROLS,
    PARTICLE_LIBRARY_COMMAND_ACTIONS,
    PARTICLE_LIBRARY_FIELD_ACTIONS,
);
