use super::types::{ActionControl, ExtensionNavigationSpec, action, spec};

const TERRAIN_EDITOR_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionTerrainEditorSculptTab",
    "WorkbenchExtensionTerrainEditorPaintTab",
    "WorkbenchExtensionTerrainEditorStreamingTab",
];
const TERRAIN_EDITOR_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.terrain_editor.sculpt_tab.select",
        "WorkbenchExtensionTerrainEditorSculptTab",
    ),
    action(
        "workbench.extension.terrain_editor.paint_tab.select",
        "WorkbenchExtensionTerrainEditorPaintTab",
    ),
    action(
        "workbench.extension.terrain_editor.streaming_tab.select",
        "WorkbenchExtensionTerrainEditorStreamingTab",
    ),
];
const TERRAIN_EDITOR_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionTerrainEditorLandscapeRow",
    "WorkbenchExtensionTerrainEditorHeightfieldRow",
    "WorkbenchExtensionTerrainEditorLayerRockRow",
    "WorkbenchExtensionTerrainEditorCellA1208Row",
    "WorkbenchExtensionTerrainEditorCellA1209Row",
    "WorkbenchExtensionTerrainEditorRockLayerTableRow",
    "WorkbenchExtensionTerrainEditorStreamingCellTableRow",
    "WorkbenchExtensionTerrainEditorOutputRow",
];
const TERRAIN_EDITOR_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.terrain_editor.landscape_row.select",
        "WorkbenchExtensionTerrainEditorLandscapeRow",
    ),
    action(
        "workbench.extension.terrain_editor.heightfield_row.select",
        "WorkbenchExtensionTerrainEditorHeightfieldRow",
    ),
    action(
        "workbench.extension.terrain_editor.layer_rock_row.select",
        "WorkbenchExtensionTerrainEditorLayerRockRow",
    ),
    action(
        "workbench.extension.terrain_editor.cell_a_1208_table_row.select",
        "WorkbenchExtensionTerrainEditorCellA1208Row",
    ),
    action(
        "workbench.extension.terrain_editor.cell_a_1209_table_row.select",
        "WorkbenchExtensionTerrainEditorCellA1209Row",
    ),
    action(
        "workbench.extension.terrain_editor.rock_layer_table_row.select",
        "WorkbenchExtensionTerrainEditorRockLayerTableRow",
    ),
    action(
        "workbench.extension.terrain_editor.streaming_cell_table_row.select",
        "WorkbenchExtensionTerrainEditorStreamingCellTableRow",
    ),
    action(
        "workbench.extension.terrain_editor.output.select",
        "WorkbenchExtensionTerrainEditorOutputRow",
    ),
];
const TERRAIN_EDITOR_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsTerrainEditorButton",
    "WorkbenchExtensionTerrainEditorPreviewButton",
    "WorkbenchExtensionTerrainEditorBuildButton",
];
const TERRAIN_EDITOR_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.terrain_editor.open",
        "WorkbenchAssetsTerrainEditorButton",
    ),
    action(
        "workbench.extension.terrain_editor.preview.invoke",
        "WorkbenchExtensionTerrainEditorPreviewButton",
    ),
    action(
        "workbench.extension.terrain_editor.build.invoke",
        "WorkbenchExtensionTerrainEditorBuildButton",
    ),
];
const TERRAIN_EDITOR_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.terrain_editor.brush.edit",
    "workbench.extension.terrain_editor.brush.commit",
    "workbench.extension.terrain_editor.radius.edit",
    "workbench.extension.terrain_editor.radius.commit",
    "workbench.extension.terrain_editor.strength.edit",
    "workbench.extension.terrain_editor.strength.commit",
];

pub(super) const TERRAIN_EDITOR_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.terrain_editor.open",
    "WorkbenchExtensionTerrainEditorWorkspace",
    TERRAIN_EDITOR_TAB_CONTROLS,
    TERRAIN_EDITOR_TAB_ACTIONS,
    TERRAIN_EDITOR_ROW_CONTROLS,
    TERRAIN_EDITOR_ROW_ACTIONS,
    TERRAIN_EDITOR_COMMAND_CONTROLS,
    TERRAIN_EDITOR_COMMAND_ACTIONS,
    TERRAIN_EDITOR_FIELD_ACTIONS,
);

const FOLIAGE_EDITOR_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionFoliageEditorPaintTab",
    "WorkbenchExtensionFoliageEditorEraseTab",
    "WorkbenchExtensionFoliageEditorClustersTab",
];
const FOLIAGE_EDITOR_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.foliage_editor.paint_tab.select",
        "WorkbenchExtensionFoliageEditorPaintTab",
    ),
    action(
        "workbench.extension.foliage_editor.erase_tab.select",
        "WorkbenchExtensionFoliageEditorEraseTab",
    ),
    action(
        "workbench.extension.foliage_editor.clusters_tab.select",
        "WorkbenchExtensionFoliageEditorClustersTab",
    ),
];
const FOLIAGE_EDITOR_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionFoliageEditorForestRow",
    "WorkbenchExtensionFoliageEditorOakRow",
    "WorkbenchExtensionFoliageEditorBiomeRow",
    "WorkbenchExtensionFoliageEditorForestA12Row",
    "WorkbenchExtensionFoliageEditorForestA13Row",
    "WorkbenchExtensionFoliageEditorRiver02Row",
    "WorkbenchExtensionFoliageEditorCliff01Row",
    "WorkbenchExtensionFoliageEditorOutputRow",
];
const FOLIAGE_EDITOR_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.foliage_editor.forest_row.select",
        "WorkbenchExtensionFoliageEditorForestRow",
    ),
    action(
        "workbench.extension.foliage_editor.oak_row.select",
        "WorkbenchExtensionFoliageEditorOakRow",
    ),
    action(
        "workbench.extension.foliage_editor.biome_row.select",
        "WorkbenchExtensionFoliageEditorBiomeRow",
    ),
    action(
        "workbench.extension.foliage_editor.forest_a_12_table_row.select",
        "WorkbenchExtensionFoliageEditorForestA12Row",
    ),
    action(
        "workbench.extension.foliage_editor.forest_a_13_table_row.select",
        "WorkbenchExtensionFoliageEditorForestA13Row",
    ),
    action(
        "workbench.extension.foliage_editor.river_02_table_row.select",
        "WorkbenchExtensionFoliageEditorRiver02Row",
    ),
    action(
        "workbench.extension.foliage_editor.cliff_01_table_row.select",
        "WorkbenchExtensionFoliageEditorCliff01Row",
    ),
    action(
        "workbench.extension.foliage_editor.output.select",
        "WorkbenchExtensionFoliageEditorOutputRow",
    ),
];
const FOLIAGE_EDITOR_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsFoliageEditorButton",
    "WorkbenchExtensionFoliageEditorPreviewButton",
    "WorkbenchExtensionFoliageEditorBuildButton",
];
const FOLIAGE_EDITOR_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.foliage_editor.open",
        "WorkbenchAssetsFoliageEditorButton",
    ),
    action(
        "workbench.extension.foliage_editor.preview.invoke",
        "WorkbenchExtensionFoliageEditorPreviewButton",
    ),
    action(
        "workbench.extension.foliage_editor.build.invoke",
        "WorkbenchExtensionFoliageEditorBuildButton",
    ),
];
const FOLIAGE_EDITOR_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.foliage_editor.type.edit",
    "workbench.extension.foliage_editor.type.commit",
    "workbench.extension.foliage_editor.density.edit",
    "workbench.extension.foliage_editor.density.commit",
    "workbench.extension.foliage_editor.radius.edit",
    "workbench.extension.foliage_editor.radius.commit",
];

pub(super) const FOLIAGE_EDITOR_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.foliage_editor.open",
    "WorkbenchExtensionFoliageEditorWorkspace",
    FOLIAGE_EDITOR_TAB_CONTROLS,
    FOLIAGE_EDITOR_TAB_ACTIONS,
    FOLIAGE_EDITOR_ROW_CONTROLS,
    FOLIAGE_EDITOR_ROW_ACTIONS,
    FOLIAGE_EDITOR_COMMAND_CONTROLS,
    FOLIAGE_EDITOR_COMMAND_ACTIONS,
    FOLIAGE_EDITOR_FIELD_ACTIONS,
);

const LEVEL_STREAMING_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionLevelStreamingCellsTab",
    "WorkbenchExtensionLevelStreamingRulesTab",
    "WorkbenchExtensionLevelStreamingEventsTab",
];
const LEVEL_STREAMING_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.level_streaming.cells_tab.select",
        "WorkbenchExtensionLevelStreamingCellsTab",
    ),
    action(
        "workbench.extension.level_streaming.rules_tab.select",
        "WorkbenchExtensionLevelStreamingRulesTab",
    ),
    action(
        "workbench.extension.level_streaming.events_tab.select",
        "WorkbenchExtensionLevelStreamingEventsTab",
    ),
];
const LEVEL_STREAMING_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionLevelStreamingWorldRow",
    "WorkbenchExtensionLevelStreamingCellA12Row",
    "WorkbenchExtensionLevelStreamingRulePlayerDistanceRow",
    "WorkbenchExtensionLevelStreamingCellA12TableRow",
    "WorkbenchExtensionLevelStreamingCellA13TableRow",
    "WorkbenchExtensionLevelStreamingHlod04TableRow",
    "WorkbenchExtensionLevelStreamingCellB12TableRow",
    "WorkbenchExtensionLevelStreamingOutputRow",
];
const LEVEL_STREAMING_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.level_streaming.world_row.select",
        "WorkbenchExtensionLevelStreamingWorldRow",
    ),
    action(
        "workbench.extension.level_streaming.cell_a_12_row.select",
        "WorkbenchExtensionLevelStreamingCellA12Row",
    ),
    action(
        "workbench.extension.level_streaming.rule_player_distance_row.select",
        "WorkbenchExtensionLevelStreamingRulePlayerDistanceRow",
    ),
    action(
        "workbench.extension.level_streaming.cell_a_12_table_row.select",
        "WorkbenchExtensionLevelStreamingCellA12TableRow",
    ),
    action(
        "workbench.extension.level_streaming.cell_a_13_table_row.select",
        "WorkbenchExtensionLevelStreamingCellA13TableRow",
    ),
    action(
        "workbench.extension.level_streaming.hlod_04_table_row.select",
        "WorkbenchExtensionLevelStreamingHlod04TableRow",
    ),
    action(
        "workbench.extension.level_streaming.cell_b_12_table_row.select",
        "WorkbenchExtensionLevelStreamingCellB12TableRow",
    ),
    action(
        "workbench.extension.level_streaming.output.select",
        "WorkbenchExtensionLevelStreamingOutputRow",
    ),
];
const LEVEL_STREAMING_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsLevelStreamingButton",
    "WorkbenchExtensionLevelStreamingPreviewButton",
    "WorkbenchExtensionLevelStreamingLoadButton",
];
const LEVEL_STREAMING_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.level_streaming.open",
        "WorkbenchAssetsLevelStreamingButton",
    ),
    action(
        "workbench.extension.level_streaming.preview.invoke",
        "WorkbenchExtensionLevelStreamingPreviewButton",
    ),
    action(
        "workbench.extension.level_streaming.load.invoke",
        "WorkbenchExtensionLevelStreamingLoadButton",
    ),
];
const LEVEL_STREAMING_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.level_streaming.cell.edit",
    "workbench.extension.level_streaming.cell.commit",
    "workbench.extension.level_streaming.rule.edit",
    "workbench.extension.level_streaming.rule.commit",
    "workbench.extension.level_streaming.distance.edit",
    "workbench.extension.level_streaming.distance.commit",
];

pub(super) const LEVEL_STREAMING_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.level_streaming.open",
    "WorkbenchExtensionLevelStreamingWorkspace",
    LEVEL_STREAMING_TAB_CONTROLS,
    LEVEL_STREAMING_TAB_ACTIONS,
    LEVEL_STREAMING_ROW_CONTROLS,
    LEVEL_STREAMING_ROW_ACTIONS,
    LEVEL_STREAMING_COMMAND_CONTROLS,
    LEVEL_STREAMING_COMMAND_ACTIONS,
    LEVEL_STREAMING_FIELD_ACTIONS,
);

const LEVEL_VARIANT_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionLevelVariantVariantTab",
    "WorkbenchExtensionLevelVariantOverridesTab",
    "WorkbenchExtensionLevelVariantDiffTab",
];
const LEVEL_VARIANT_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.level_variant.variant_tab.select",
        "WorkbenchExtensionLevelVariantVariantTab",
    ),
    action(
        "workbench.extension.level_variant.overrides_tab.select",
        "WorkbenchExtensionLevelVariantOverridesTab",
    ),
    action(
        "workbench.extension.level_variant.diff_tab.select",
        "WorkbenchExtensionLevelVariantDiffTab",
    ),
];
const LEVEL_VARIANT_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionLevelVariantSetRow",
    "WorkbenchExtensionLevelVariantRedRow",
    "WorkbenchExtensionLevelVariantActorOverrideRow",
    "WorkbenchExtensionLevelVariantCarBodyRow",
    "WorkbenchExtensionLevelVariantWheelFlRow",
    "WorkbenchExtensionLevelVariantLightRigRow",
    "WorkbenchExtensionLevelVariantDoorLRow",
    "WorkbenchExtensionLevelVariantOutputRow",
];
const LEVEL_VARIANT_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.level_variant.set_row.select",
        "WorkbenchExtensionLevelVariantSetRow",
    ),
    action(
        "workbench.extension.level_variant.red_row.select",
        "WorkbenchExtensionLevelVariantRedRow",
    ),
    action(
        "workbench.extension.level_variant.actor_override_row.select",
        "WorkbenchExtensionLevelVariantActorOverrideRow",
    ),
    action(
        "workbench.extension.level_variant.car_body_table_row.select",
        "WorkbenchExtensionLevelVariantCarBodyRow",
    ),
    action(
        "workbench.extension.level_variant.wheel_fl_table_row.select",
        "WorkbenchExtensionLevelVariantWheelFlRow",
    ),
    action(
        "workbench.extension.level_variant.light_rig_table_row.select",
        "WorkbenchExtensionLevelVariantLightRigRow",
    ),
    action(
        "workbench.extension.level_variant.door_l_table_row.select",
        "WorkbenchExtensionLevelVariantDoorLRow",
    ),
    action(
        "workbench.extension.level_variant.output.select",
        "WorkbenchExtensionLevelVariantOutputRow",
    ),
];
const LEVEL_VARIANT_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsLevelVariantButton",
    "WorkbenchExtensionLevelVariantPreviewButton",
    "WorkbenchExtensionLevelVariantApplyButton",
];
const LEVEL_VARIANT_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.level_variant.open",
        "WorkbenchAssetsLevelVariantButton",
    ),
    action(
        "workbench.extension.level_variant.preview.invoke",
        "WorkbenchExtensionLevelVariantPreviewButton",
    ),
    action(
        "workbench.extension.level_variant.apply.invoke",
        "WorkbenchExtensionLevelVariantApplyButton",
    ),
];
const LEVEL_VARIANT_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.level_variant.variant.edit",
    "workbench.extension.level_variant.variant.commit",
    "workbench.extension.level_variant.set.edit",
    "workbench.extension.level_variant.set.commit",
    "workbench.extension.level_variant.capture.edit",
    "workbench.extension.level_variant.capture.commit",
];

pub(super) const LEVEL_VARIANT_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.level_variant.open",
    "WorkbenchExtensionLevelVariantWorkspace",
    LEVEL_VARIANT_TAB_CONTROLS,
    LEVEL_VARIANT_TAB_ACTIONS,
    LEVEL_VARIANT_ROW_CONTROLS,
    LEVEL_VARIANT_ROW_ACTIONS,
    LEVEL_VARIANT_COMMAND_CONTROLS,
    LEVEL_VARIANT_COMMAND_ACTIONS,
    LEVEL_VARIANT_FIELD_ACTIONS,
);

const PREFAB_EDITOR_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionPrefabEditorHierarchyTab",
    "WorkbenchExtensionPrefabEditorOverridesTab",
    "WorkbenchExtensionPrefabEditorValidationTab",
];
const PREFAB_EDITOR_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.prefab_editor.hierarchy_tab.select",
        "WorkbenchExtensionPrefabEditorHierarchyTab",
    ),
    action(
        "workbench.extension.prefab_editor.overrides_tab.select",
        "WorkbenchExtensionPrefabEditorOverridesTab",
    ),
    action(
        "workbench.extension.prefab_editor.validation_tab.select",
        "WorkbenchExtensionPrefabEditorValidationTab",
    ),
];
const PREFAB_EDITOR_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionPrefabEditorPrefabRootRow",
    "WorkbenchExtensionPrefabEditorMeshComponentRow",
    "WorkbenchExtensionPrefabEditorLootSocketRow",
    "WorkbenchExtensionPrefabEditorMeshTableRow",
    "WorkbenchExtensionPrefabEditorLootSocketTableRow",
    "WorkbenchExtensionPrefabEditorLightTableRow",
    "WorkbenchExtensionPrefabEditorOverrideTableRow",
    "WorkbenchExtensionPrefabEditorOutputRow",
];
const PREFAB_EDITOR_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.prefab_editor.prefab_root_row.select",
        "WorkbenchExtensionPrefabEditorPrefabRootRow",
    ),
    action(
        "workbench.extension.prefab_editor.mesh_component_row.select",
        "WorkbenchExtensionPrefabEditorMeshComponentRow",
    ),
    action(
        "workbench.extension.prefab_editor.loot_socket_row.select",
        "WorkbenchExtensionPrefabEditorLootSocketRow",
    ),
    action(
        "workbench.extension.prefab_editor.mesh_table_row.select",
        "WorkbenchExtensionPrefabEditorMeshTableRow",
    ),
    action(
        "workbench.extension.prefab_editor.loot_socket_table_row.select",
        "WorkbenchExtensionPrefabEditorLootSocketTableRow",
    ),
    action(
        "workbench.extension.prefab_editor.light_table_row.select",
        "WorkbenchExtensionPrefabEditorLightTableRow",
    ),
    action(
        "workbench.extension.prefab_editor.override_table_row.select",
        "WorkbenchExtensionPrefabEditorOverrideTableRow",
    ),
    action(
        "workbench.extension.prefab_editor.output.select",
        "WorkbenchExtensionPrefabEditorOutputRow",
    ),
];
const PREFAB_EDITOR_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsPrefabEditorButton",
    "WorkbenchExtensionPrefabEditorApplyButton",
    "WorkbenchExtensionPrefabEditorValidateButton",
];
const PREFAB_EDITOR_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.prefab_editor.open",
        "WorkbenchAssetsPrefabEditorButton",
    ),
    action(
        "workbench.extension.prefab_editor.apply.invoke",
        "WorkbenchExtensionPrefabEditorApplyButton",
    ),
    action(
        "workbench.extension.prefab_editor.validate.invoke",
        "WorkbenchExtensionPrefabEditorValidateButton",
    ),
];
const PREFAB_EDITOR_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.prefab_editor.prefab.edit",
    "workbench.extension.prefab_editor.prefab.commit",
    "workbench.extension.prefab_editor.variant.edit",
    "workbench.extension.prefab_editor.variant.commit",
    "workbench.extension.prefab_editor.instance.edit",
    "workbench.extension.prefab_editor.instance.commit",
];

pub(super) const PREFAB_EDITOR_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.prefab_editor.open",
    "WorkbenchExtensionPrefabEditorWorkspace",
    PREFAB_EDITOR_TAB_CONTROLS,
    PREFAB_EDITOR_TAB_ACTIONS,
    PREFAB_EDITOR_ROW_CONTROLS,
    PREFAB_EDITOR_ROW_ACTIONS,
    PREFAB_EDITOR_COMMAND_CONTROLS,
    PREFAB_EDITOR_COMMAND_ACTIONS,
    PREFAB_EDITOR_FIELD_ACTIONS,
);

const SCATTER_EDITOR_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionScatterEditorRulesTab",
    "WorkbenchExtensionScatterEditorConstraintsTab",
    "WorkbenchExtensionScatterEditorOutputTab",
];
const SCATTER_EDITOR_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.scatter_editor.rules_tab.select",
        "WorkbenchExtensionScatterEditorRulesTab",
    ),
    action(
        "workbench.extension.scatter_editor.constraints_tab.select",
        "WorkbenchExtensionScatterEditorConstraintsTab",
    ),
    action(
        "workbench.extension.scatter_editor.output_tab.select",
        "WorkbenchExtensionScatterEditorOutputTab",
    ),
];
const SCATTER_EDITOR_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionScatterEditorSetRow",
    "WorkbenchExtensionScatterEditorRocksRuleRow",
    "WorkbenchExtensionScatterEditorFernsRuleRow",
    "WorkbenchExtensionScatterEditorBiomeMaskTableRow",
    "WorkbenchExtensionScatterEditorSlopeFilterTableRow",
    "WorkbenchExtensionScatterEditorSpawnRuleTableRow",
    "WorkbenchExtensionScatterEditorCollisionTestTableRow",
    "WorkbenchExtensionScatterEditorOutputRow",
];
const SCATTER_EDITOR_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.scatter_editor.set_row.select",
        "WorkbenchExtensionScatterEditorSetRow",
    ),
    action(
        "workbench.extension.scatter_editor.rocks_rule_row.select",
        "WorkbenchExtensionScatterEditorRocksRuleRow",
    ),
    action(
        "workbench.extension.scatter_editor.ferns_rule_row.select",
        "WorkbenchExtensionScatterEditorFernsRuleRow",
    ),
    action(
        "workbench.extension.scatter_editor.biome_mask_table_row.select",
        "WorkbenchExtensionScatterEditorBiomeMaskTableRow",
    ),
    action(
        "workbench.extension.scatter_editor.slope_filter_table_row.select",
        "WorkbenchExtensionScatterEditorSlopeFilterTableRow",
    ),
    action(
        "workbench.extension.scatter_editor.spawn_rule_table_row.select",
        "WorkbenchExtensionScatterEditorSpawnRuleTableRow",
    ),
    action(
        "workbench.extension.scatter_editor.collision_test_table_row.select",
        "WorkbenchExtensionScatterEditorCollisionTestTableRow",
    ),
    action(
        "workbench.extension.scatter_editor.output.select",
        "WorkbenchExtensionScatterEditorOutputRow",
    ),
];
const SCATTER_EDITOR_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsScatterEditorButton",
    "WorkbenchExtensionScatterEditorGenerateButton",
    "WorkbenchExtensionScatterEditorValidateButton",
];
const SCATTER_EDITOR_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.scatter_editor.open",
        "WorkbenchAssetsScatterEditorButton",
    ),
    action(
        "workbench.extension.scatter_editor.generate.invoke",
        "WorkbenchExtensionScatterEditorGenerateButton",
    ),
    action(
        "workbench.extension.scatter_editor.validate.invoke",
        "WorkbenchExtensionScatterEditorValidateButton",
    ),
];
const SCATTER_EDITOR_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.scatter_editor.rule_set.edit",
    "workbench.extension.scatter_editor.rule_set.commit",
    "workbench.extension.scatter_editor.seed.edit",
    "workbench.extension.scatter_editor.seed.commit",
    "workbench.extension.scatter_editor.density.edit",
    "workbench.extension.scatter_editor.density.commit",
];

pub(super) const SCATTER_EDITOR_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.scatter_editor.open",
    "WorkbenchExtensionScatterEditorWorkspace",
    SCATTER_EDITOR_TAB_CONTROLS,
    SCATTER_EDITOR_TAB_ACTIONS,
    SCATTER_EDITOR_ROW_CONTROLS,
    SCATTER_EDITOR_ROW_ACTIONS,
    SCATTER_EDITOR_COMMAND_CONTROLS,
    SCATTER_EDITOR_COMMAND_ACTIONS,
    SCATTER_EDITOR_FIELD_ACTIONS,
);

const VOLUME_EDITOR_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionVolumeEditorBoundsTab",
    "WorkbenchExtensionVolumeEditorOverlapsTab",
    "WorkbenchExtensionVolumeEditorEventsTab",
];
const VOLUME_EDITOR_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.volume_editor.bounds_tab.select",
        "WorkbenchExtensionVolumeEditorBoundsTab",
    ),
    action(
        "workbench.extension.volume_editor.overlaps_tab.select",
        "WorkbenchExtensionVolumeEditorOverlapsTab",
    ),
    action(
        "workbench.extension.volume_editor.events_tab.select",
        "WorkbenchExtensionVolumeEditorEventsTab",
    ),
];
const VOLUME_EDITOR_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionVolumeEditorDamageZoneRow",
    "WorkbenchExtensionVolumeEditorProfileDefaultRow",
    "WorkbenchExtensionVolumeEditorOverlapPlayerRow",
    "WorkbenchExtensionVolumeEditorBoundsTableRow",
    "WorkbenchExtensionVolumeEditorPlayerOverlapTableRow",
    "WorkbenchExtensionVolumeEditorDamageRuleTableRow",
    "WorkbenchExtensionVolumeEditorOnEnterEventTableRow",
    "WorkbenchExtensionVolumeEditorOutputRow",
];
const VOLUME_EDITOR_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.volume_editor.damage_zone_row.select",
        "WorkbenchExtensionVolumeEditorDamageZoneRow",
    ),
    action(
        "workbench.extension.volume_editor.profile_default_row.select",
        "WorkbenchExtensionVolumeEditorProfileDefaultRow",
    ),
    action(
        "workbench.extension.volume_editor.overlap_player_row.select",
        "WorkbenchExtensionVolumeEditorOverlapPlayerRow",
    ),
    action(
        "workbench.extension.volume_editor.bounds_table_row.select",
        "WorkbenchExtensionVolumeEditorBoundsTableRow",
    ),
    action(
        "workbench.extension.volume_editor.player_overlap_table_row.select",
        "WorkbenchExtensionVolumeEditorPlayerOverlapTableRow",
    ),
    action(
        "workbench.extension.volume_editor.damage_rule_table_row.select",
        "WorkbenchExtensionVolumeEditorDamageRuleTableRow",
    ),
    action(
        "workbench.extension.volume_editor.on_enter_event_table_row.select",
        "WorkbenchExtensionVolumeEditorOnEnterEventTableRow",
    ),
    action(
        "workbench.extension.volume_editor.output.select",
        "WorkbenchExtensionVolumeEditorOutputRow",
    ),
];
const VOLUME_EDITOR_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsVolumeEditorButton",
    "WorkbenchExtensionVolumeEditorInspectButton",
    "WorkbenchExtensionVolumeEditorValidateButton",
];
const VOLUME_EDITOR_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.volume_editor.open",
        "WorkbenchAssetsVolumeEditorButton",
    ),
    action(
        "workbench.extension.volume_editor.inspect.invoke",
        "WorkbenchExtensionVolumeEditorInspectButton",
    ),
    action(
        "workbench.extension.volume_editor.validate.invoke",
        "WorkbenchExtensionVolumeEditorValidateButton",
    ),
];
const VOLUME_EDITOR_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.volume_editor.volume.edit",
    "workbench.extension.volume_editor.volume.commit",
    "workbench.extension.volume_editor.profile.edit",
    "workbench.extension.volume_editor.profile.commit",
    "workbench.extension.volume_editor.priority.edit",
    "workbench.extension.volume_editor.priority.commit",
];

pub(super) const VOLUME_EDITOR_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.volume_editor.open",
    "WorkbenchExtensionVolumeEditorWorkspace",
    VOLUME_EDITOR_TAB_CONTROLS,
    VOLUME_EDITOR_TAB_ACTIONS,
    VOLUME_EDITOR_ROW_CONTROLS,
    VOLUME_EDITOR_ROW_ACTIONS,
    VOLUME_EDITOR_COMMAND_CONTROLS,
    VOLUME_EDITOR_COMMAND_ACTIONS,
    VOLUME_EDITOR_FIELD_ACTIONS,
);

const WEATHER_EDITOR_TAB_CONTROLS: &[&str] = &[
    "WorkbenchExtensionWeatherEditorLayersTab",
    "WorkbenchExtensionWeatherEditorCurvesTab",
    "WorkbenchExtensionWeatherEditorTimelineTab",
];
const WEATHER_EDITOR_TAB_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.weather_editor.layers_tab.select",
        "WorkbenchExtensionWeatherEditorLayersTab",
    ),
    action(
        "workbench.extension.weather_editor.curves_tab.select",
        "WorkbenchExtensionWeatherEditorCurvesTab",
    ),
    action(
        "workbench.extension.weather_editor.timeline_tab.select",
        "WorkbenchExtensionWeatherEditorTimelineTab",
    ),
];
const WEATHER_EDITOR_ROW_CONTROLS: &[&str] = &[
    "WorkbenchExtensionWeatherEditorStormRow",
    "WorkbenchExtensionWeatherEditorMountainsRegionRow",
    "WorkbenchExtensionWeatherEditorCloudLayerRow",
    "WorkbenchExtensionWeatherEditorCloudBuildTimelineRow",
    "WorkbenchExtensionWeatherEditorRainBurstTimelineRow",
    "WorkbenchExtensionWeatherEditorWindGustTimelineRow",
    "WorkbenchExtensionWeatherEditorLightningTimelineRow",
    "WorkbenchExtensionWeatherEditorOutputRow",
];
const WEATHER_EDITOR_ROW_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.weather_editor.storm_row.select",
        "WorkbenchExtensionWeatherEditorStormRow",
    ),
    action(
        "workbench.extension.weather_editor.mountains_region_row.select",
        "WorkbenchExtensionWeatherEditorMountainsRegionRow",
    ),
    action(
        "workbench.extension.weather_editor.cloud_layer_row.select",
        "WorkbenchExtensionWeatherEditorCloudLayerRow",
    ),
    action(
        "workbench.extension.weather_editor.cloud_build_timeline_row.select",
        "WorkbenchExtensionWeatherEditorCloudBuildTimelineRow",
    ),
    action(
        "workbench.extension.weather_editor.rain_burst_timeline_row.select",
        "WorkbenchExtensionWeatherEditorRainBurstTimelineRow",
    ),
    action(
        "workbench.extension.weather_editor.wind_gust_timeline_row.select",
        "WorkbenchExtensionWeatherEditorWindGustTimelineRow",
    ),
    action(
        "workbench.extension.weather_editor.lightning_timeline_row.select",
        "WorkbenchExtensionWeatherEditorLightningTimelineRow",
    ),
    action(
        "workbench.extension.weather_editor.output.select",
        "WorkbenchExtensionWeatherEditorOutputRow",
    ),
];
const WEATHER_EDITOR_COMMAND_CONTROLS: &[&str] = &[
    "WorkbenchAssetsWeatherEditorButton",
    "WorkbenchExtensionWeatherEditorPreviewButton",
    "WorkbenchExtensionWeatherEditorBuildButton",
];
const WEATHER_EDITOR_COMMAND_ACTIONS: &[ActionControl] = &[
    action(
        "workbench.extension.weather_editor.open",
        "WorkbenchAssetsWeatherEditorButton",
    ),
    action(
        "workbench.extension.weather_editor.preview.invoke",
        "WorkbenchExtensionWeatherEditorPreviewButton",
    ),
    action(
        "workbench.extension.weather_editor.build.invoke",
        "WorkbenchExtensionWeatherEditorBuildButton",
    ),
];
const WEATHER_EDITOR_FIELD_ACTIONS: &[&str] = &[
    "workbench.extension.weather_editor.preset.edit",
    "workbench.extension.weather_editor.preset.commit",
    "workbench.extension.weather_editor.region.edit",
    "workbench.extension.weather_editor.region.commit",
    "workbench.extension.weather_editor.blend_time.edit",
    "workbench.extension.weather_editor.blend_time.commit",
];

pub(super) const WEATHER_EDITOR_NAVIGATION_SPEC: ExtensionNavigationSpec = spec(
    "workbench.extension.weather_editor.open",
    "WorkbenchExtensionWeatherEditorWorkspace",
    WEATHER_EDITOR_TAB_CONTROLS,
    WEATHER_EDITOR_TAB_ACTIONS,
    WEATHER_EDITOR_ROW_CONTROLS,
    WEATHER_EDITOR_ROW_ACTIONS,
    WEATHER_EDITOR_COMMAND_CONTROLS,
    WEATHER_EDITOR_COMMAND_ACTIONS,
    WEATHER_EDITOR_FIELD_ACTIONS,
);
