//! VM plugin contracts, host handles, and hot reload coordination.

mod vm;

pub use vm::{
    builtin_host_capabilities, builtin_host_module_descriptors,
    current_script_runtime_call_context, discover_vm_plugin_package, discover_vm_plugin_packages,
    migrate_vm_state_blob, module_descriptor, register_bridge_host_module,
    register_builtin_host_modules, register_gameplay_host_module,
    render_script_host_modules_markdown, script_float, script_scene_fixed_update_hook_registration,
    script_scene_update_hook_registration, with_script_runtime_call_context,
    write_script_host_modules_markdown, BuiltinVmBackendFamily, CapabilitySet,
    DiscoveredVmPluginPackage, HostCapabilityRecord, HostExportCallback, HostExportFunction,
    HostExportModuleRecord, HostExportRegistry, HostHandle, HostRegistry, HostRegistryError,
    HotReloadCoordinator, PluginHostDriver, PluginSlotId, ScriptBridgeCall,
    ScriptBridgeMethodDescriptor, ScriptCallSite, ScriptCallSiteId, ScriptCallTable,
    ScriptHostInterfaceMarkdownOptions, ScriptModule, ScriptRuntimeCallContext,
    ScriptSceneLifecyclePhase, ScriptSceneRuntimeHook, UnavailableVmBackend, VmBackend,
    VmBackendFamily, VmBackendRegistry, VmBehaviorNodeRegistration, VmCallbackHandle,
    VmEditorOperationRegistration, VmError, VmGcBudget, VmGcDiagnostics, VmGcRootRegistrationError,
    VmGcRootRegistry, VmGcRootToken, VmGcSlotStepReport, VmGcStepOutcome, VmGcStepReport,
    VmHostInterfaceError, VmHostInterfaceRegistry, VmInterfaceCaller, VmObjectId, VmObjectRef,
    VmObjectRefError, VmPluginGarbageCollectionMode, VmPluginGarbageCollectionPolicy,
    VmPluginHostContext, VmPluginHotReloadPolicy, VmPluginInstance, VmPluginManagementPolicy,
    VmPluginManagementPolicyError, VmPluginManagementPolicyResult, VmPluginManager,
    VmPluginManifest, VmPluginMemoryPolicy, VmPluginPackage, VmPluginPackageSource,
    VmPluginSlotLifecycle, VmPluginSlotRecord, VmPluginSlotState, VmReflectionCatalog,
    VmReflectionError, VmReflectionRegistrySnapshot, VmReflectionSchema,
    VmReflectionSchemaInstaller, VmRpcHandlerRegistration, VmScriptBehaviorBridge, VmStateBlob,
    VmStateFieldRename, VmStateMigrationError, VmStateObject, VmStateSchema, VmStateTypeIdentity,
    VmStateTypeSchema, VmSystemRegistration, VmSystemStage, ZrVmExecutionMode,
    ZrVmPluginProjectSource, BRIDGE_HOST_CAPABILITY, BRIDGE_HOST_MODULE,
    DEFAULT_VM_GC_MAX_MICROS_PER_FRAME, PLUGIN_HOST_DRIVER_NAME, SCRIPT_MODULE_NAME,
    VM_BT_NODE_CAPABILITY, VM_EDITOR_OPERATION_CAPABILITY, VM_GC_DIAGNOSTICS_HISTORY_CAPACITY,
    VM_HOST_INTERFACE_MODULE, VM_PLUGIN_MANAGER_NAME, VM_PLUGIN_RUNTIME_NAME,
    VM_REFLECTION_WORLD_EXTENSION_NAME, VM_RPC_HANDLER_CAPABILITY, VM_STATE_SCHEMA_VERSION_V2,
    VM_SYSTEM_CAPABILITY,
};
