use super::model::CodeReviewFindingsSources;
use super::CODE_REVIEW_FINDINGS_LINE_BUDGET;

pub(super) fn assert_code_review_findings_line_budgets(sources: &CodeReviewFindingsSources) {
    for (path, source) in [
        (
            "tests/runtime_absorption/code_review_findings.rs",
            sources.parent.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
            sources.f8_api_convergence.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/texture_import_settings.rs",
            sources.f8_texture_import_settings.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder.rs",
            sources.f8_descriptor_builder.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/scaffold.rs",
            sources.f8_descriptor_builder_scaffold.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/first_party_descriptors.rs",
            sources.f8_descriptor_builder_first_party.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder/test_fixtures.rs",
            sources.f8_descriptor_builder_test_fixtures.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy.rs",
            sources.f8_descriptor_privacy.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/private_fields.rs",
            sources.f8_descriptor_privacy_private_fields.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/constructor_retirement.rs",
            sources
                .f8_descriptor_privacy_constructor_retirement
                .as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy/status_mirrors.rs",
            sources.f8_descriptor_privacy_status_mirrors.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/late_api_cleanup.rs",
            sources.late_api_cleanup.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            sources.p0_robustness.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_host_callbacks.rs",
            sources.p0_native_host_callbacks.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness/lock_poison.rs",
            sources.p0_lock_poison.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness/render_submit.rs",
            sources.p0_render_submit.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture.rs",
            sources.p0_native_fixture.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/sdk_macro_manifest.rs",
            sources.p0_native_fixture_sdk_macro.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/importer_manifest.rs",
            sources.p0_native_fixture_importer.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/p0_robustness/priority_recommendation.rs",
            sources.p0_priority_recommendation.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/render_structure.rs",
            sources.render_structure.as_str(),
        ),
        (
            "tests/runtime_absorption/code_review_findings/f12_dead_code.rs",
            sources.f12_dead_code.as_str(),
        ),
    ] {
        let line_count = source.lines().count();
        assert!(
            line_count < CODE_REVIEW_FINDINGS_LINE_BUDGET,
            "{path} should stay below the Runtime 15 test-file budget; got {line_count} lines"
        );
    }
}
