//! 这些完整服务名是 ManagerDescriptor 的注册键，resolver 的 trait 映射按同一值查询；测试固定内置和可选插件名。
pub const RESOURCE_MANAGER_NAME: &str = "AssetModule.Manager.ResourceManager";
pub const INPUT_MANAGER_NAME: &str = "InputModule.Manager.InputManager";
pub const INPUT_ACTION_MANAGER_NAME: &str = "InputModule.Manager.InputActionManager";
pub const CONFIG_MANAGER_NAME: &str = "FoundationModule.Manager.ConfigManager";
pub const RENDERING_MANAGER_NAME: &str = "GraphicsModule.Manager.RenderingManager";
pub const RENDER_FRAMEWORK_NAME: &str = "GraphicsModule.Manager.RenderFramework";
pub const LEVEL_MANAGER_NAME: &str = "SceneModule.Manager.LevelManager";
pub const PLATFORM_MANAGER_NAME: &str = "PlatformModule.Manager.PlatformManager";
#[cfg(feature = "ai-contracts")]
pub const AI_MANAGER_NAME: &str = "ai.runtime.Manager.AiManager";
#[cfg(feature = "net-contracts")]
pub const NET_MANAGER_NAME: &str = "net.runtime.Manager.NetManager";
#[cfg(feature = "physics-contracts")]
pub const PHYSICS_MANAGER_NAME: &str = "physics.runtime.Manager.PhysicsManager";
pub const ANIMATION_MANAGER_NAME: &str = "animation.runtime.Manager.AnimationManager";
#[cfg(feature = "sound-contracts")]
pub const SOUND_MANAGER_NAME: &str = "sound.runtime.Manager.SoundManager";
pub const NAVIGATION_MANAGER_NAME: &str = "navigation.runtime.Manager.NavigationManager";
