pub const RESOURCE_MANAGER_NAME: &str = "AssetModule.Manager.ResourceManager";
pub const INPUT_MANAGER_NAME: &str = "InputModule.Manager.InputManager";
pub const INPUT_ACTION_MANAGER_NAME: &str = "InputModule.Manager.InputActionManager";
pub const CONFIG_MANAGER_NAME: &str = "FoundationModule.Manager.ConfigManager";
pub const EVENT_MANAGER_NAME: &str = "FoundationModule.Manager.EventManager";
pub const RENDERING_MANAGER_NAME: &str = "GraphicsModule.Manager.RenderingManager";
pub const RENDER_FRAMEWORK_NAME: &str = "GraphicsModule.Manager.RenderFramework";
pub const LEVEL_MANAGER_NAME: &str = "SceneModule.Manager.LevelManager";
#[cfg(feature = "ai-contracts")]
pub const AI_MANAGER_NAME: &str = "ai.runtime.Manager.AiManager";
#[cfg(feature = "net-contracts")]
pub const NET_MANAGER_NAME: &str = "net.runtime.Manager.NetManager";
#[cfg(feature = "physics-contracts")]
pub const PHYSICS_MANAGER_NAME: &str = "physics.runtime.Manager.PhysicsManager";
pub const ANIMATION_MANAGER_NAME: &str = "animation.runtime.Manager.AnimationManager";
#[cfg(feature = "sound-contracts")]
pub const SOUND_MANAGER_NAME: &str = "sound.runtime.Manager.SoundManager";
pub const NAVIGATION_MANAGER_NAME: &str = "navigation.runtime.Manager.NavigationManager";
