use super::*;

pub(super) fn assert_render_shader_template_assembly_docs_are_anchored() {
    let plan_08 = read_repo("docs/plans/zircon_runtime/render/08-material-shader-permutation.md");
    let render_index = read_repo("docs/plans/zircon_runtime/render/index.md");
    let shader_doc = read_repo("docs/zircon_runtime/core/framework/render/shader.md");
    let review_findings = read_repo("docs/plans/engine-code-review-findings-2026-06.md");
    let structure_convention = read_repo("docs/plans/engine-code-structure-convention.md");
    let session_doc = read_repo(".codex/sessions/20260617-0926-render-hzb-progress.md");

    for (label, source) in [
        ("Plan 08", plan_08.as_str()),
        ("render index", render_index.as_str()),
        ("shader doc", shader_doc.as_str()),
        ("review findings", review_findings.as_str()),
        ("structure convention", structure_convention.as_str()),
        ("render session doc", session_doc.as_str()),
    ] {
        assert_contains_all(
            label,
            source,
            &[
                "Shader template assembly foundation",
                "render_plan08_shader_template_assembly_foundation_static_passed_cargo_timeout_no_result",
                "graphics/shader/template/assemble.rs",
                "graphics/shader/template/module_registry.rs",
                "graphics/shader/wgsl/zr_geometry_static.wgsl",
                "render_shader_template_assembles_static_and_skinned_geometry_sources",
                "render_shader_template_assembles_standard_material_surface_source",
                "Standard material template surface foundation",
                "render_plan08_standard_material_template_surface_static_passed_cargo_deferred_implementation_cadence",
                "graphics/shader/template/material_surface.rs",
                "standard_material_surface_source",
                "standard_material_surface_source_for_features",
                "standard_material_surface_source_can_be_built_from_runtime_features",
                "Shader template Naga validation foundation",
                "render_plan08_shader_template_naga_validation_static_passed_cargo_deferred_implementation_cadence",
                "graphics/shader/template/validation.rs",
                "validate_material_shader_template_wgsl",
                "render_shader_template_validates_standard_material_wgsl_with_naga",
                "Shader prewarm WGSL validation gate",
                "render_plan08_shader_prewarm_wgsl_validation_check_passed_test_compile_timeout_no_result",
                "graphics/shader/variant_cache/prewarm.rs",
                "validate_shader_variant_prewarm_wgsl",
                "render_shader_variant_prewarm_rejects_invalid_wgsl_before_disk_write",
                "Velocity/TAA variant-id pipeline cache owner",
                "render_plan08_velocity_taa_variant_id_pipeline_cache_static_passed_cargo_deferred_implementation_cadence",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/ensure_velocity_pipeline.rs",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/ensure_taa_reactive_mask_pipeline.rs",
                "velocity_mesh_shader_key_includes_shader_variant_identity",
                "taa_reactive_mask_shader_key_includes_shader_variant_identity",
                "Velocity/TAA WGPU device pipeline validation code",
                "render_plan08_velocity_taa_wgpu_device_pipeline_validation_implemented_validation_not_closed",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline/test_support.rs",
                "velocity_mesh_pipeline_creates_on_wgpu_device_with_template_shader",
                "taa_reactive_mask_mesh_pipeline_creates_on_wgpu_device_with_template_shader",
                "Velocity pipeline template source cache cutover",
                "render_plan08_velocity_pipeline_template_source_cache_static_passed_cargo_deferred_implementation_cadence",
                "graphics/shader/wgsl/zr_template_velocity_alpha.wgsl",
                "mesh_pipeline_velocity_template_source_for_geometry",
                "velocity_mesh_shader_key_includes_shader_variant_identity_and_source_hash",
                "TAA reactive mask template source cache cutover",
                "render_plan08_taa_reactive_mask_template_source_cache_static_passed_cargo_deferred_implementation_cadence",
                "graphics/shader/template/taa_reactive_mask.rs",
                "graphics/shader/wgsl/zr_template_taa_reactive_mask.wgsl",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline/create_taa_reactive_mask_mesh_pipeline.rs",
                "mesh_pipeline_taa_reactive_mask_template_source_for_geometry",
                "taa_reactive_mask_shader_key_includes_shader_variant_identity_and_source_hash",
                "taa_reactive_mask_pipeline_declares_template_entries_and_static_vertex_layout",
                "Shadow pipeline template source cache cutover",
                "render_plan08_shadow_pipeline_template_source_cache_static_passed_cargo_check_test_compile_wgpu_deferred",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/ensure_shadow_pipeline.rs",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline/create_shadow_mesh_pipeline.rs",
                "graphics/shader/wgsl/zr_template_shadow.wgsl",
                "graphics/shader/wgsl/zr_template_shadow_alpha.wgsl",
                "mesh_pipeline_shadow_template_source_for_geometry",
                "shadow_mesh_shader_key_includes_shader_variant_identity_and_source_hash",
                "shadow_mesh_pipeline_declares_template_entries_static_layout_and_depth_bias",
                "Shadow WGPU device pipeline validation",
                "render_plan08_shadow_wgpu_device_pipeline_validation_implemented_validation_not_closed",
                "shadow_mesh_pipeline_creates_on_wgpu_device_with_template_shader",
                "Shader template uv1 tangent interpolation foundation",
                "render_plan08_shader_template_uv1_tangent_interpolation_static_passed_cargo_deferred_implementation_cadence",
                "graphics/shader/wgsl/zr_surface_types.wgsl",
                "fetch_tangent(v, instance_index)",
                "Forward template runtime light-grid shadow shading context foundation",
                "render_plan08_forward_template_light_grid_shadow_context_static_passed_cargo_deferred_implementation_cadence",
                "zr_build_shading_context(input)",
                "ZR_FEATURE_RECEIVE_SHADOWS && ctx.shadow_params.z > 0.5",
                "Forward template built-in shading model dispatch parity foundation",
                "render_plan08_forward_template_builtin_shading_model_dispatch_static_passed_cargo_deferred_implementation_cadence",
                "standard_material_shading_model_id",
                "surface.shading_model_id == ZR_SHADING_MODEL_BLINN_PHONG_ID",
                "Descriptor-driven forward shading include dispatch",
                "render_plan08_descriptor_driven_forward_shading_include_dispatch_static_passed_cargo_deferred",
                "with_shading_model_descriptor",
                "shading_model_forward_include_for",
                "UnknownShadingInclude",
                "render_shader_template_uses_shading_model_descriptor_forward_include",
                "render_shader_template_rejects_unknown_shading_model_forward_include",
                "Custom forward shading include source dispatch",
                "render_plan08_custom_forward_shading_include_source_static_passed_cargo_deferred",
                "with_shading_model_forward_include_source",
                "render_shader_template_uses_custom_shading_model_forward_include_source",
                "Deferred GBuffer shading include source dispatch",
                "render_plan08_deferred_gbuffer_shading_include_source_static_passed_cargo_deferred",
                "with_shading_model_gbuffer_include_source",
                "shading_model_gbuffer_include_for",
                "render_deferred_gbuffer_template_uses_custom_shading_model_gbuffer_include_source",
                "Deferred lighting include source dispatch",
                "render_plan08_deferred_lighting_include_source_dispatch_static_passed_cargo_deferred",
                "with_shading_model_deferred_include_source",
                "assemble_deferred_lighting_shader_source",
                "deferred_lighting_shader_uses_custom_shading_model_deferred_include_source",
                "Mesh pipeline standard material template source cutover",
                "render_plan08_mesh_pipeline_standard_material_template_source_static_passed_cargo_deferred_implementation_cadence",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/ensure_pipeline.rs",
                "mesh_pipeline_standard_material_template_source",
                "mesh_pipeline_template_source_hashes_feed_disk_and_module_keys",
                "Mesh pipeline shader source owner split",
                "render_plan08_mesh_pipeline_shader_source_owner_split_static_passed_cargo_deferred_implementation_cadence",
                "graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/shader_source.rs",
                "mesh_pipeline_template_source_hashes_include_template_revision",
                "Shader template vertex input ABI alignment",
                "render_plan08_shader_template_vertex_input_abi_alignment_static_passed_cargo_deferred_implementation_cadence",
                "GpuMeshVertex::layout()",
                "Shader template runtime scene transform foundation",
                "render_plan08_shader_template_runtime_scene_transform_static_passed_cargo_timeout_no_result",
                "zr_scene_runtime.wgsl",
                "zr_gpu_scene.wgsl",
                "zr_world_from_local(instance_index)",
                "scene.view_proj * position_ws",
                "zr_skinned_joint_matrix(v.joints.x)",
                "Shader template runtime entry alias foundation",
                "render_plan08_shader_template_runtime_entry_alias_static_passed_cargo_timeout_no_result",
                "vs_main",
                "fs_main",
                "zr_vs_main_impl",
                "zr_fs_main_impl",
                "Standard material normal map sampling foundation",
                "render_plan08_standard_material_normal_map_sampling_static_passed_cargo_deferred_implementation_cadence",
                "standard_material_sampled_normal",
                "Standard material alpha clip pass foundation",
                "render_plan08_standard_material_alpha_clip_pass_static_passed_cargo_deferred_implementation_cadence",
                "zr_apply_alpha_clip",
                "Standard material uniform alpha cutoff foundation",
                "render_plan08_standard_material_uniform_alpha_cutoff_static_passed_cargo_deferred_implementation_cadence",
                "standard_material_alpha_cutoff",
                "standard_material_properties.data8.z",
                "runtime_15_render_shader_template_assembly_is_folder_backed",
            ],
        );
    }
}
