use super::*;

pub(super) const MODULE_LAYOUT_STATUS_DOC_CHILDREN: &[(&str, &str, &str)] = &[
    (
        "budgets",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/budgets.rs",
        "runtime_15_module_layout_status_docs_guard_children_stay_focused",
    ),
    (
        "delegation",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/delegation.rs",
        FOLDER_BACKED_GUARD_NAME,
    ),
    (
        "source_ownership",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/source_ownership.rs",
        "runtime_15_module_layout_status_doc_sources_are_child_owned",
    ),
    (
        "status_mirrors",
        "tests/runtime_absorption/structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors.rs",
        HISTORICAL_GUARD_NAME,
    ),
    (
        "root_inventory",
        ROOT_INVENTORY_GUARD_PATH,
        ROOT_INVENTORY_GUARD_NAME,
    ),
];

pub(super) const MODULE_LAYOUT_STATUS_DOC_OWNER_BUDGETS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
        MODULE_LAYOUT_GUARD_PATH,
        160,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs.rs",
        MODULE_LAYOUT_STATUS_DOCS_GUARD_PATH,
        110,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_paths.rs",
        ROOT_PATHS_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_statuses.rs",
        ROOT_STATUSES_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_source_blobs.rs",
        ROOT_SOURCE_BLOBS_PATH,
        80,
    ),
    (
        "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
];
