type Slice = super::Slice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 status output Runtime 15 expected-slice maps guard folder-backed split",
        &[
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/child_owners.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout.rs",
            "runtime_15_status_output_runtime_15_expected_slice_maps_are_child_owners",
            "runtime_15_status_output_naming_boundary_expected_slice_maps_are_folder_backed",
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output Runtime 15 expected-slice maps guard body folder-backed split",
        &[
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_body_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/doc_mirrors.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/paths.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/status_mirrors.rs",
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_body_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output Runtime 15 expected-slice maps guard body budgets folder-backed split",
        &[
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_body_budgets_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets/guard_body_children.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets/paths.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets/route_mount_children.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets/status_docs.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/budgets/top_level_maps.rs",
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_body_budgets_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output Runtime 15 expected-slice maps guard-body route mounts folder-backed split",
        &[
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_body_route_mounts_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts/child_owner_routes.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts/naming_boundary_routes.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts/parent_routes.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts/split_layout_routes.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/split_layout/guard_body/route_mounts/status_mirrors.rs",
            "runtime_15_status_output_runtime_15_expected_slice_maps_guard_body_route_mounts_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation expected-slice maps folder-backed split",
        &[
            "runtime_15_foundation_expected_slice_maps_folder_backed_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation/asset_provider_cleanup.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation/core_cleanup.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation/graphics_diagnostics.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation/lock_poison.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation/map_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation/typed_error_core.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/foundation/typed_error_plugin.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation/asset_provider_cleanup.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation/core_cleanup.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation/graphics_diagnostics.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation/lock_poison.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation/map_rows.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation/typed_error_core.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/foundation/typed_error_plugin.rs",
            "runtime_15_foundation_expected_slice_maps_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation expected-slice maps guard folder-backed split",
        &[
            "runtime_15_foundation_expected_slice_maps_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/child_sources.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/paths.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/status_mirrors.rs",
            "runtime_15_foundation_expected_slice_maps_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 naming-boundary render-graphics map rows guard folder-backed split",
        &[
            "runtime_15_naming_boundary_render_graphics_map_rows_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/render_graphics_map_rows.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/render_graphics_map_rows/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/render_graphics_map_rows/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/render_graphics_map_rows/paths.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/render_graphics_map_rows/route_mounts.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/render_graphics_map_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/render_graphics_map_rows/status_rows.rs",
            "runtime_15_status_output_naming_boundary_render_graphics_map_rows_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation expected-slice maps status mirrors folder-backed split",
        &[
            "runtime_15_foundation_expected_slice_maps_status_mirrors_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/status_mirrors/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/status_mirrors/docs.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/status_mirrors/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/status_mirrors/paths.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/foundation/status_mirrors/row_data.rs",
            "runtime_15_foundation_expected_slice_maps_status_mirrors_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 naming-boundary expected-slice sources folder-backed split",
        &[
            "runtime_15_naming_boundary_expected_slice_sources_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/budgets.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/constants.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/folder_backed.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/guard_body.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/render_graphics.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/row_sources.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/maps/runtime_15_topics/runtime_15_expected_slice_maps/naming_boundary/sources/structure_route_maps.rs",
            "runtime_15_status_output_naming_boundary_expected_slice_sources_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
