use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
};

use crate::ui::binding::{EditorUiBindingPayload, EditorUiEventKind};
use crate::ui::template_runtime::builtin::builtin_template_bindings;

use super::support::*;

const STRUCTURAL_CHILD_ROUTE_PROTOTYPES: &[&str] = &["button_group"];

const EXPECTED_INTERACTION_FEEDBACK: &[(&str, &str, &str, &str)] = &[
    (
        "accordion",
        "MaterialLab/Accordion/Toggle",
        "Toggle",
        "material_lab.accordion.toggle",
    ),
    (
        "autocomplete",
        "MaterialLab/Autocomplete/Change",
        "Change",
        "material_lab.autocomplete.change",
    ),
    (
        "backdrop",
        "MaterialLab/Backdrop/Click",
        "Click",
        "material_lab.backdrop.click",
    ),
    (
        "bottom_navigation",
        "MaterialLab/BottomNavigation/Change",
        "Change",
        "material_lab.bottom_navigation.change",
    ),
    (
        "breadcrumbs",
        "MaterialLab/Breadcrumbs/Click",
        "Click",
        "material_lab.breadcrumbs.click",
    ),
    (
        "buttons",
        "MaterialLab/Buttons/Click",
        "Click",
        "material_lab.buttons.click",
    ),
    (
        "cards",
        "MaterialLab/Cards/Click",
        "Click",
        "material_lab.cards.click",
    ),
    (
        "checkboxes",
        "MaterialLab/Checkboxes/Toggle",
        "Toggle",
        "material_lab.checkboxes.toggle",
    ),
    (
        "chips",
        "MaterialLab/Chips/Click",
        "Click",
        "material_lab.chips.click",
    ),
    (
        "dialogs",
        "MaterialLab/Dialogs/Click",
        "Click",
        "material_lab.dialogs.click",
    ),
    (
        "drawers",
        "MaterialLab/Drawers/Click",
        "Click",
        "material_lab.drawers.click",
    ),
    (
        "floating_action_button",
        "MaterialLab/FloatingActionButton/Click",
        "Click",
        "material_lab.floating_action_button.click",
    ),
    (
        "image_list",
        "MaterialLab/ImageList/Click",
        "Click",
        "material_lab.image_list.click",
    ),
    (
        "links",
        "MaterialLab/Links/Click",
        "Click",
        "material_lab.links.click",
    ),
    (
        "lists",
        "MaterialLab/Lists/Click",
        "Click",
        "material_lab.lists.click",
    ),
    (
        "menubar",
        "MaterialLab/Menubar/Click",
        "Click",
        "material_lab.menubar.click",
    ),
    (
        "menus",
        "MaterialLab/Menus/Click",
        "Click",
        "material_lab.menus.click",
    ),
    (
        "modal",
        "MaterialLab/Modal/Click",
        "Click",
        "material_lab.modal.click",
    ),
    (
        "mui_x_agent_chat",
        "MaterialLab/MuiXAgentChat/Submit",
        "Submit",
        "material_lab.mui_x_agent_chat.submit",
    ),
    (
        "mui_x_bar_chart",
        "MaterialLab/MuiXBarChart/Hover",
        "Hover",
        "material_lab.mui_x_bar_chart.hover",
    ),
    (
        "mui_x_charts",
        "MaterialLab/MuiXCharts/Hover",
        "Hover",
        "material_lab.mui_x_charts.hover",
    ),
    (
        "mui_x_chat_composer",
        "MaterialLab/MuiXChatComposer/Submit",
        "Submit",
        "material_lab.mui_x_chat_composer.submit",
    ),
    (
        "mui_x_data_grid",
        "MaterialLab/MuiXDataGrid/Click",
        "Click",
        "material_lab.mui_x_data_grid.click",
    ),
    (
        "mui_x_date_time_pickers",
        "MaterialLab/MuiXDateTimePickers/Submit",
        "Submit",
        "material_lab.mui_x_date_time_pickers.submit",
    ),
    (
        "mui_x_gauge",
        "MaterialLab/MuiXGauge/Hover",
        "Hover",
        "material_lab.mui_x_gauge.hover",
    ),
    (
        "mui_x_line_chart",
        "MaterialLab/MuiXLineChart/Hover",
        "Hover",
        "material_lab.mui_x_line_chart.hover",
    ),
    (
        "mui_x_pie_chart",
        "MaterialLab/MuiXPieChart/Hover",
        "Hover",
        "material_lab.mui_x_pie_chart.hover",
    ),
    (
        "mui_x_sparkline",
        "MaterialLab/MuiXSparkline/Hover",
        "Hover",
        "material_lab.mui_x_sparkline.hover",
    ),
    (
        "mui_x_tree_view",
        "MaterialLab/MuiXTreeView/Toggle",
        "Toggle",
        "material_lab.mui_x_tree_view.toggle",
    ),
    (
        "number_field",
        "MaterialLab/NumberField/Change",
        "Change",
        "material_lab.number_field.change",
    ),
    (
        "pagination",
        "MaterialLab/Pagination/Change",
        "Change",
        "material_lab.pagination.change",
    ),
    (
        "popover",
        "MaterialLab/Popover/Click",
        "Click",
        "material_lab.popover.click",
    ),
    (
        "popper",
        "MaterialLab/Popper/Click",
        "Click",
        "material_lab.popper.click",
    ),
    (
        "radio_buttons",
        "MaterialLab/RadioButtons/Change",
        "Change",
        "material_lab.radio_buttons.change",
    ),
    (
        "rating",
        "MaterialLab/Rating/Change",
        "Change",
        "material_lab.rating.change",
    ),
    (
        "selects",
        "MaterialLab/Selects/Change",
        "Change",
        "material_lab.selects.change",
    ),
    (
        "slider",
        "MaterialLab/Slider/DragUpdate",
        "DragUpdate",
        "material_lab.slider.drag_update",
    ),
    (
        "snackbars",
        "MaterialLab/Snackbars/Click",
        "Click",
        "material_lab.snackbars.click",
    ),
    (
        "speed_dial",
        "MaterialLab/SpeedDial/Click",
        "Click",
        "material_lab.speed_dial.click",
    ),
    (
        "steppers",
        "MaterialLab/Steppers/Change",
        "Change",
        "material_lab.steppers.change",
    ),
    (
        "switches",
        "MaterialLab/Switches/Toggle",
        "Toggle",
        "material_lab.switches.toggle",
    ),
    (
        "table",
        "MaterialLab/Table/Click",
        "Click",
        "material_lab.table.click",
    ),
    (
        "tabs",
        "MaterialLab/Tabs/Change",
        "Change",
        "material_lab.tabs.change",
    ),
    (
        "text_fields",
        "MaterialLab/TextFields/Change",
        "Change",
        "material_lab.text_fields.change",
    ),
    (
        "textarea_autosize",
        "MaterialLab/TextareaAutosize/Change",
        "Change",
        "material_lab.textarea_autosize.change",
    ),
    (
        "toggle_button",
        "MaterialLab/ToggleButton/Toggle",
        "Toggle",
        "material_lab.toggle_button.toggle",
    ),
    (
        "tooltips",
        "MaterialLab/Tooltips/Hover",
        "Hover",
        "material_lab.tooltips.hover",
    ),
    (
        "transfer_list",
        "MaterialLab/TransferList/Change",
        "Change",
        "material_lab.transfer_list.change",
    ),
];

mod events;
mod routes;
