pub(super) const STRUCTURE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_f8_child_owner_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 F8 child-owner structure guard folder-backed split",
    "Runtime 15 M3 F8 API convergence review guard child-owner split",
    "runtime_15_f8_api_convergence_review_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/budgets.rs",
    "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
    "tests/runtime_absorption/code_review_findings/f8_api_convergence/texture_import_settings.rs",
    "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_builder.rs",
    "tests/runtime_absorption/code_review_findings/f8_api_convergence/descriptor_privacy.rs",
    "runtime_15_f8_child_owner_structure_guard_is_folder_backed",
    "runtime_15_f8_api_convergence_review_guards_are_child_owners",
    "review_f8_texture_import_settings_use_fallible_apply_not_with",
    "review_f8_runtime_plugin_descriptor_exposes_builder_scaffold",
    "review_f8_first_party_runtime_plugin_descriptors_use_builder",
    "review_f8_runtime_plugin_descriptor_test_fixtures_use_builder",
    "review_f8_runtime_plugin_descriptor_fields_are_private_with_accessors",
    "review_f8_runtime_plugin_descriptor_public_constructor_is_retired",
    "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
    "runtime_15_f8_child_owner_structure_guard_folder_backed_status_is_current",
    "runtime_15_f8_child_owner_structure_guard_budgets_are_focused",
    "Cargo gate deferred",
];

pub(super) const F8_CHILD_OWNER_ROOT_INVENTORY_CHILD_SPLIT: &[&str] = &[
    "runtime_15_f8_child_owner_root_inventory_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 F8 child-owner root inventory child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/root_inventory.rs",
    "runtime_15_f8_child_owner_root_inventory_is_child_owned",
    "Cargo gate deferred",
];

pub(super) const F8_ROUTE_OWNERSHIP_GUARD_CHILD_SPLIT: &[&str] = &[
    "runtime_15_f8_route_ownership_guard_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 F8 route ownership guard child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership/parent_routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership/descriptor_builder_routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership/descriptor_privacy_routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership/leaf_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/f8_child_owners/route_ownership/status_mirrors.rs",
    "runtime_15_f8_api_convergence_review_guards_are_child_owners",
    "runtime_15_f8_route_ownership_guard_is_child_backed",
    "runtime_15_f8_route_ownership_status_mirrors_are_current",
    "review_f8_texture_import_settings_use_fallible_apply_not_with",
    "review_f8_runtime_plugin_descriptor_exposes_builder_scaffold",
    "review_f8_first_party_runtime_plugin_descriptors_use_builder",
    "review_f8_runtime_plugin_descriptor_test_fixtures_use_builder",
    "review_f8_runtime_plugin_descriptor_fields_are_private_with_accessors",
    "review_f8_runtime_plugin_descriptor_public_constructor_is_retired",
    "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
    "Cargo gate deferred",
];
