pub(super) const STRUCTURE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_late_api_cleanup_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 late API cleanup structure guard folder-backed split",
    "Runtime 15 M3 late API cleanup review guard child-owner split",
    "runtime_15_late_api_cleanup_review_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/budgets.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f11_shading_model_registry.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f15_editor_pane_data_conversion.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f17_entity_path_lookup.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f18_asset_manager_resolution.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f19_scene_renderer_construction.rs",
    "runtime_15_late_api_cleanup_structure_guard_is_folder_backed",
    "runtime_15_late_api_cleanup_review_guards_are_child_owners",
    "review_f11_shading_model_registry_has_no_dead_plugin_registration_surface",
    "review_f15_editor_pane_data_conversion_top_row_uses_projection_owners",
    "review_f17_entity_path_option_lookup_uses_get_verb",
    "review_f18_asset_manager_resolution_returns_registered_handle",
    "review_f19_scene_renderer_construction_modules_use_construct_names",
    "runtime_15_late_api_cleanup_structure_guard_folder_backed_status_is_current",
    "runtime_15_late_api_cleanup_structure_guard_budgets_are_focused",
    "Cargo gate deferred",
];

pub(super) const LATE_API_CLEANUP_ROOT_INVENTORY_CHILD_SPLIT: &[&str] = &[
    "runtime_15_late_api_cleanup_root_inventory_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 late API cleanup root inventory child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_inventory.rs",
    "runtime_15_late_api_cleanup_root_inventory_is_child_owned",
    "Cargo gate deferred",
];

pub(super) const LATE_API_CLEANUP_SOURCE_STATUS_MAP_RECONCILIATION: &[&str] = &[
    "runtime_15_late_api_cleanup_source_status_map_reconciliation_static_passed_cargo_deferred",
    "Runtime 15 M3 late API cleanup source status-map reconciliation",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/root_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_owners/status_mirrors.rs",
    "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/late_api_rows.rs",
    "runtime_15_late_api_cleanup_structure_guard_is_folder_backed",
    "runtime_15_late_api_cleanup_root_inventory_is_child_owned",
    "runtime_15_late_api_cleanup_structure_guard_folder_backed_status_is_current",
    "Cargo gate deferred",
];
