pub(super) const STRUCTURE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_late_api_cleanup_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 late API cleanup structure guard folder-backed split",
    "Runtime 15 M3 late API cleanup review guard child-owner split",
    "runtime_15_late_api_cleanup_review_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/late_api_cleanup_child_owners/budgets.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f11_shading_model_registry.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f15_editor_pane_data_conversion.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f17_entity_path_lookup.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f18_asset_manager_resolution.rs",
    "tests/runtime_absorption/code_review_findings/late_api_cleanup/f19_scene_renderer_construction.rs",
    "runtime_15_late_api_cleanup_structure_guard_is_folder_backed",
    "runtime_15_late_api_cleanup_review_guards_are_child_owners",
    "review_f11_shading_model_registry_has_no_dead_plugin_registration_surface",
    "review_f15_editor_pane_data_conversion_top_row_uses_projection_owners",
    "review_f17_entity_path_option_lookup_uses_get_verb",
    "review_f18_asset_manager_resolution_returns_registered_handle",
    "review_f19_scene_renderer_construction_modules_use_construct_names",
    "runtime_15_late_api_cleanup_structure_guard_folder_backed_status_is_current",
    "runtime_15_late_api_cleanup_structure_guard_budgets_are_focused",
    "Cargo gate deferred",
];
