pub(super) const STRUCTURE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_p0_robustness_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 P0 robustness structure guard folder-backed split",
    "Runtime 15 M3 P0 robustness review guard child-owner split",
    "runtime_15_p0_robustness_review_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners/budgets.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_host_callbacks.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/lock_poison.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/render_submit.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/sdk_macro_manifest.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/importer_manifest.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/priority_recommendation.rs",
    "runtime_15_p0_robustness_structure_guard_is_folder_backed",
    "runtime_15_p0_robustness_review_guards_are_child_owners",
    "review_f1_native_host_callbacks_catch_unwind_before_crossing_ffi",
    "review_f2_scene_eventbus_locks_recover_after_poison",
    "review_f4_render_submit_capability_gaps_return_typed_errors",
    "review_ds8_d3_native_fixture_uses_sdk_macro_and_single_manifest",
    "review_d13_native_fixture_importer_is_manifest_described",
    "review_priority_recommendation_tracks_current_remaining_work",
    "runtime_15_p0_robustness_structure_guard_folder_backed_status_is_current",
    "runtime_15_p0_robustness_structure_guard_budgets_are_focused",
    "Cargo gate deferred",
];
