pub(super) const STRUCTURE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_p0_robustness_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 P0 robustness structure guard folder-backed split",
    "Runtime 15 M3 P0 robustness review guard child-owner split",
    "runtime_15_p0_robustness_review_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/budgets.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_host_callbacks.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/lock_poison.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/render_submit.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/sdk_macro_manifest.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/native_fixture/importer_manifest.rs",
    "tests/runtime_absorption/code_review_findings/p0_robustness/priority_recommendation.rs",
    "runtime_15_p0_robustness_structure_guard_is_folder_backed",
    "runtime_15_p0_robustness_review_guards_are_child_owners",
    "review_f1_native_host_callbacks_catch_unwind_before_crossing_ffi",
    "review_f2_scene_eventbus_locks_recover_after_poison",
    "review_f4_render_submit_capability_gaps_return_typed_errors",
    "review_ds8_d3_native_fixture_uses_sdk_macro_and_single_manifest",
    "review_d13_native_fixture_importer_is_manifest_described",
    "review_priority_recommendation_tracks_current_remaining_work",
    "runtime_15_p0_robustness_structure_guard_folder_backed_status_is_current",
    "runtime_15_p0_robustness_structure_guard_budgets_are_focused",
    "Cargo gate deferred",
];

pub(super) const P0_ROBUSTNESS_ROOT_INVENTORY_CHILD_SPLIT: &[&str] = &[
    "runtime_15_p0_robustness_root_inventory_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 P0 robustness root inventory child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_inventory.rs",
    "runtime_15_p0_robustness_root_inventory_is_child_owned",
    "Cargo gate deferred",
];

pub(super) const P0_ROUTE_OWNERSHIP_GUARD_CHILD_SPLIT: &[&str] = &[
    "runtime_15_p0_route_ownership_guard_child_split_static_passed_cargo_deferred",
    "Runtime 15 M3 P0 route ownership guard child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/route_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/route_ownership/parent_routes.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/route_ownership/leaf_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/route_ownership/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/route_ownership/status_mirrors.rs",
    "runtime_15_p0_robustness_review_guards_are_child_owners",
    "runtime_15_p0_route_ownership_guard_is_child_backed",
    "runtime_15_p0_route_ownership_status_mirrors_are_current",
    "review_f1_native_host_callbacks_catch_unwind_before_crossing_ffi",
    "review_f2_scene_eventbus_locks_recover_after_poison",
    "review_f4_render_submit_capability_gaps_return_typed_errors",
    "review_ds8_d3_native_fixture_uses_sdk_macro_and_single_manifest",
    "review_d13_native_fixture_importer_is_manifest_described",
    "review_priority_recommendation_tracks_current_remaining_work",
    "Cargo gate deferred",
];

pub(super) const P0_SOURCE_STATUS_MAP_RECONCILIATION: &[&str] = &[
    "runtime_15_p0_source_status_map_reconciliation_static_passed_cargo_deferred",
    "Runtime 15 M3 P0 source status-map reconciliation",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/root_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/p0_owners/route_ownership/status_mirrors.rs",
    "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/foundation_review_maps/p0_rows.rs",
    "runtime_15_p0_robustness_structure_guard_is_folder_backed",
    "runtime_15_p0_robustness_root_inventory_is_child_owned",
    "runtime_15_p0_route_ownership_status_mirrors_are_current",
    "Cargo gate deferred",
];
