pub(super) const STRUCTURE_GUARD_FOLDER_BACKED_SPLIT: &[&str] = &[
    "runtime_15_plugin_importer_dx_structure_guard_folder_backed_static_passed_cargo_deferred",
    "Runtime 15 M3 plugin-importer DX structure guard folder-backed split",
    "Runtime 15 M3 code review findings plugin-importer DX structure guard child-owner split",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_child_owner_split_static_passed_cargo_deferred",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/budgets.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/source_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/status_docs.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/review_mounts.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/delegation.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/child_ownership.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions/d13_sdk.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d10_bridge_call.rs",
    "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
    "review_d10_animation_physics_tests_use_sdk_bridge_call",
    "review_d8_runtime_registration_builder_original_evidence_paths_use_sdk_builder",
    "review_d5_editor_authoring_plugins_use_sdk_macro",
    "review_d9_editor_runtime_mirror_consumers_use_sdk_declaration",
    "runtime_15_code_review_findings_plugin_importer_dx_structure_guard_is_child_owner",
    "runtime_15_plugin_importer_dx_structure_guard_is_folder_backed",
    "runtime_15_plugin_importer_dx_structure_guard_folder_backed_status_is_current",
    "runtime_15_plugin_importer_dx_structure_guard_budgets_are_focused",
    "Cargo gate deferred",
];

pub(super) const STRUCTURE_GUARD_ROOT_INVENTORY_CHILD_SPLIT: &[&str] = &[
    "runtime_15_plugin_importer_dx_structure_guard_root_inventory_child_split_target_server_direct_binary_passed",
    "Runtime 15 M3 plugin-importer DX structure guard root inventory child split",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_statuses.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_inventory.rs",
    "runtime_15_plugin_importer_dx_structure_guard_root_inventory_is_child_owned",
    "target-server direct binary passed",
];

pub(super) const PLUGIN_IMPORTER_DX_SOURCE_STATUS_MAP_RECONCILIATION: &[&str] = &[
    "runtime_15_plugin_importer_dx_source_status_map_reconciliation_static_passed_cargo_deferred",
    "Runtime 15 M3 plugin-importer DX source status-map reconciliation",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_paths.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_child_rows.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/root_sources.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/status_mirrors.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/source_inventory.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/status_docs.rs",
    "tests/runtime_absorption/structure_convention/test_file_budget/code_review_findings/plugin_importer_dx_child_owners/structure_assertions.rs",
    "tests/runtime_absorption/plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/review_guard_maps/plugin_importer_maps.rs",
    "runtime_15_plugin_importer_dx_structure_guard_is_folder_backed",
    "runtime_15_plugin_importer_dx_structure_guard_root_inventory_is_child_owned",
    "runtime_15_plugin_importer_dx_structure_guard_folder_backed_status_is_current",
    "Cargo gate deferred",
];
