type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 production guard module-layout row-data folder-backed split",
        &[
            "runtime_15_production_guard_module_layout_row_data_folder_backed_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout/base_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout/status_doc_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout/child_summary_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout/child_summary_status_doc_rows.rs",
            "Cargo gate deferred active Render Plan08/text lanes",
        ],
    ),
    (
        "Runtime 15 M3 status output row-data guard child-owner split",
        &[
            "runtime_15_status_output_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data.rs",
            "structure_convention/test_file_budget/row_data/module_layout.rs",
            "runtime_15_status_output_row_data_guard_child_owner_split",
        ],
    ),
    (
        "Runtime 15 M3 status-output row-data module-layout guard folder-backed split",
        &[
            "runtime_15_status_output_row_data_module_layout_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout.rs",
            "structure_convention/test_file_budget/row_data/module_layout/delegation.rs",
            "structure_convention/test_file_budget/row_data/module_layout/child_summaries.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/module_layout/budgets.rs",
            "runtime_15_status_output_row_data_module_layout_guard_is_folder_backed",
            "runtime_15_status_output_row_data_guard_child_owner_split",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-mirror child split",
        &[
            "runtime_15_module_layout_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors/layout_folder_status.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors/folder_backed_status.rs",
            "runtime_15_module_layout_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout root inventory child split",
        &[
            "runtime_15_module_layout_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout.rs",
            "structure_convention/test_file_budget/row_data/module_layout/root_paths.rs",
            "structure_convention/test_file_budget/row_data/module_layout/root_statuses.rs",
            "structure_convention/test_file_budget/row_data/module_layout/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/module_layout/root_owner_paths.rs",
            "structure_convention/test_file_budget/row_data/module_layout/root_inventory.rs",
            "runtime_15_module_layout_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout source/status-map sync",
        &[
            "runtime_15_module_layout_source_status_map_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout/root_paths.rs",
            "structure_convention/test_file_budget/row_data/module_layout/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/module_layout/child_summaries.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/row_data/module_layout/status_mirrors/layout_folder_status.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout/base_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout/child_summary_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/row_data_maps/module_layout_maps.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/row_data_maps/root_runtime_maps.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_stay_delegated",
            "runtime_15_status_output_row_data_guard_child_owner_split",
            "runtime_15_module_layout_root_inventory_is_child_owned",
            "runtime_15_module_layout_status_mirror_children_are_child_owned",
            "runtime_15_module_layout_folder_backed_status_rows_are_current",
            "runtime_15_module_layout_historical_status_rows_are_current",
            "runtime_15_status_output_row_data_module_layout_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
];
