type Slice = super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[Slice] = &[
    (
        "Runtime 15 M3 status output row-data module-layout child-summary guard child-owner split",
        &[
            "runtime_15_status_output_row_data_module_layout_child_summary_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary guard folder-backed split",
        &[
            "runtime_15_module_layout_child_summary_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/delegation.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/owner_budgets.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary root inventory child split",
        &[
            "runtime_15_module_layout_child_summary_root_inventory_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/root_paths.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/root_statuses.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/root_source_blobs.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/root_inventory.rs",
            "runtime_15_module_layout_child_summary_root_inventory_is_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary owner-budget guard child split",
        &[
            "runtime_15_module_layout_child_summary_owner_budget_guard_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/owner_budgets.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/owner_budgets/route_children.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/owner_budgets/nested_children.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/owner_budgets/surrounding_owners.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/owner_budgets/status_mirrors.rs",
            "runtime_15_module_layout_child_summary_guard_owner_budgets_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary milestone-groups child split",
        &[
            "runtime_15_module_layout_child_summary_milestone_groups_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups/runtime_row_data.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups/m3_child_groups.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups/status_doc_groups.rs",
            "runtime_15_module_layout_child_summary_milestone_groups_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary foundation-review child split",
        &[
            "runtime_15_module_layout_child_summary_foundation_review_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review/runtime_foundation_rows.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review/foundation_status_docs.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review/review_guard_rows.rs",
            "runtime_15_module_layout_child_summary_foundation_review_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary source/status-map sync",
        &[
            "runtime_15_module_layout_child_summary_source_status_map_sync_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/root_paths.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/root_child_rows.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review/runtime_foundation_rows.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review/foundation_status_docs.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/foundation_review/review_guard_rows.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups/runtime_row_data.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups/m3_child_groups.rs",
            "structure_convention/test_file_budget/row_data/module_layout_child_summaries/milestone_groups/status_doc_groups.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support/module_layout/child_summary_rows.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support/status_support_maps/row_data_maps/module_layout_maps.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_are_child_owner",
            "runtime_15_module_layout_child_summary_foundation_review_rows_are_child_owner",
            "runtime_15_module_layout_child_summary_milestone_groups_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
];
