use super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] = &[
    (
        "Runtime 15 M3 module-convention status row-data child-owner split",
        &[
            "runtime_15_module_convention_status_row_data_child_owner_split_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status.rs",
            "RUNTIME_15_M3_MODULE_CONVENTION_STATUS_EXPECTED_STATUS_OUTPUT_SLICES",
            "MODULE_CONVENTION_STATUS_EXPECTED_STATUS_OUTPUT_SLICES",
            "Runtime 15 M3 module convention gate audit-clear status mirror",
            "runtime_15_status_output_m3_row_data_child_owner_split",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 module convention module-doc frontmatter uniqueness guard",
        &[
            "runtime_15_module_convention_module_doc_frontmatter_uniqueness_static_passed_cargo_deferred",
            "docs/zircon_runtime/structure/module-convention.md",
            "structure_convention/module_convention_gate.rs",
            "runtime_15_module_convention_module_doc_frontmatter_has_unique_entries",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/module_convention_status.rs",
            "plan_status/status_output_tables/expected_slices/status/runtime_15/m3_structure_support.rs",
            "plan_status/status_output_tables/expected_slices/date/runtime_15/m3_structure_support.rs",
            "related_code duplicates 0",
            "implementation_files duplicates 0",
            "frontmatter duplicate count 0",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module convention gate output contract",
        &[
            "runtime_15_module_convention_gate_output_contract_static_passed_cargo_deferred",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/audit_runtime_structure.py",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate.py",
            "module_convention_gate",
            "runtime_15_module_convention_gate_output_contract_is_backed_by_structure_audit",
        ],
    ),
    (
        "Runtime 15 M3 module convention non-render debt guard",
        &[
            "runtime_15_module_convention_non_render_debt_guard_static_passed_cargo_deferred",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate.py",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate_markdown.py",
            "render_scoped_migration_debt_count",
            "non_render_migration_debt_count",
            "runtime_15_module_convention_gate_reports_non_render_debt_boundary",
        ],
    ),
    (
        "Runtime 15 M3 render-scoped migration debt handoff gate",
        &[
            "runtime_15_render_scoped_migration_debt_handoff_static_passed_cargo_deferred",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate.py",
            "render-scoped migration debt 0",
            "non-render migration debt 0",
            "module_convention_gate classified-and-clear",
            "runtime_15_render_scoped_migration_debt_handoff_is_status_locked",
        ],
    ),
    (
        "Runtime 15 M3 hard-cutover allowed Hyper policy risk cleanup",
        &[
            "runtime_15_hard_cutover_allowed_hyper_policy_risk_cleanup_static_passed_cargo_deferred",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/hard_cutover_migration_smells.py",
            "external-hyper-http1-client-policy",
            "risk_count=0",
            "risks=[]",
            "runtime_15_hard_cutover_allowed_hyper_policy_does_not_report_risk",
        ],
    ),
    (
        "Runtime 15 M3 module convention gate audit-clear status mirror",
        &[
            "runtime_15_module_convention_gate_audit_clear_status_mirror_core_min_cargo_passed_full_sweep_pending",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate.py",
            "module_convention_gate audit clear",
            "migration_debt_count=0",
            "risk_count=0",
            "risks=[]",
            "runtime_15_module_convention_gate_audit_clear_is_status_locked",
        ],
    ),
    (
        "Runtime 15 M3 module convention zero-debt revalidation",
        &[
            "runtime_15_module_convention_zero_debt_revalidation_static_passed_cargo_timeout_no_result",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/audit_runtime_structure.py",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate.py",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/large_file_ownership.py",
            "module_convention_gate classified-and-clear",
            "migration_debt_count=0",
            "render_scoped_migration_debt_count=0",
            "non_render_migration_debt_count=0",
            "large_file_ownership_gate classified-and-clear",
            "hotspot_count=0",
            "runtime_15_module_convention_zero_debt_revalidation_is_status_locked",
        ],
    ),
    (
        "Runtime 15 M3 module convention audit script family naming cleanup",
        &[
            "runtime_15_module_convention_audit_script_family_naming_core_min_cargo_passed_full_sweep_pending",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate.py",
            ".codex/skills/zircon-project-skills/zr-runtime-interface-convergence/scripts/runtime_structure_audits/module_convention_gate_markdown.py",
            "module_convention_boundary.py zero hits",
            "module_convention_markdown.py zero hits",
            "runtime_15_module_convention_audit_script_family_uses_gate_names",
        ],
    ),
];
