use super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] = &[
    (
        "Runtime 15 M3 production file budget guard child-owner split",
        &[
            "runtime_15_production_file_budget_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/production_file_budget.rs",
            "structure_convention/production_file_budget/module_layout.rs",
            "runtime_15_production_file_budget_guard_child_owner_split",
        ],
    ),
    (
        "Runtime 15 M3 render shader template assembly guard WGSL contracts split",
        &[
            "runtime_15_render_shader_template_assembly_guard_wgsl_contracts_split_static_passed_cargo_deferred",
            "structure_convention/production_file_budget/render_shader_template_assembly.rs",
            "structure_convention/production_file_budget/render_shader_template_assembly/wgsl_contracts.rs",
            "runtime_15_render_shader_template_wgsl_contracts_are_child_owner",
        ],
    ),
    (
        "Runtime 15 M3 status output variable evidence anchors",
        &[
            "runtime_15_status_output_variable_evidence_anchors_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_rows.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
            "runtime_15_expected_status_output_rows_accept_variable_evidence_anchors",
        ],
    ),
    (
        "Runtime 15 M3 status output evidence anchors guard folder-backed split",
        &[
            "runtime_15_status_output_evidence_anchors_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/evidence_anchors.rs",
            "structure_convention/test_file_budget/status_output_row_data/evidence_anchors/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/evidence_anchors/variable_evidence.rs",
            "structure_convention/test_file_budget/status_output_row_data/evidence_anchors/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/evidence_anchors/budgets.rs",
            "runtime_15_status_output_evidence_anchors_guard_is_folder_backed",
            "runtime_15_expected_status_output_rows_accept_variable_evidence_anchors",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output M3 row data child-owner split",
        &[
            "runtime_15_status_output_m3_row_data_child_owner_split_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support.rs",
            "runtime_15_status_output_m3_row_data_child_owner_split",
        ],
    ),
    (
        "Runtime 15 M3 child-groups row-data guard folder-backed split",
        &[
            "runtime_15_m3_child_groups_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/exports.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/budgets.rs",
            "runtime_15_m3_child_groups_row_data_guard_is_folder_backed",
            "runtime_15_status_output_m3_row_data_child_owner_split",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups row-data status-mirror child split",
        &[
            "runtime_15_m3_child_groups_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups/status_mirrors/folder_backed_status.rs",
            "runtime_15_m3_child_groups_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output row-data guard child-owner split",
        &[
            "runtime_15_status_output_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "runtime_15_status_output_row_data_guard_child_owner_split",
        ],
    ),
    (
        "Runtime 15 M3 status-output row-data module-layout guard folder-backed split",
        &[
            "runtime_15_status_output_row_data_module_layout_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/child_summaries.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/budgets.rs",
            "runtime_15_status_output_row_data_module_layout_guard_is_folder_backed",
            "runtime_15_status_output_row_data_guard_child_owner_split",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-mirror child split",
        &[
            "runtime_15_module_layout_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/layout_folder_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout/status_mirrors/folder_backed_status.rs",
            "runtime_15_module_layout_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output row-data module-layout status-doc guard child-owner split",
        &[
            "runtime_15_status_output_row_data_module_layout_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs.rs",
            "runtime_15_status_output_row_data_module_layout_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-doc guard folder-backed split",
        &[
            "runtime_15_module_layout_status_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/source_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/budgets.rs",
            "runtime_15_module_layout_status_docs_guard_is_folder_backed",
            "runtime_15_status_output_row_data_module_layout_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout status-doc status-mirror child split",
        &[
            "runtime_15_module_layout_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_module_layout_status_doc_status_mirror_children_are_folder_backed",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support.rs",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output row-data module-layout child-summary guard child-owner split",
        &[
            "runtime_15_status_output_row_data_module_layout_child_summary_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary guard folder-backed split",
        &[
            "runtime_15_module_layout_child_summary_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/owner_budgets.rs",
            "runtime_15_status_output_row_data_module_layout_child_summaries_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary milestone-groups child split",
        &[
            "runtime_15_module_layout_child_summary_milestone_groups_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups/runtime_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups/m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/milestone_groups/status_doc_groups.rs",
            "runtime_15_module_layout_child_summary_milestone_groups_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary foundation-review child split",
        &[
            "runtime_15_module_layout_child_summary_foundation_review_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review/runtime_foundation_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review/foundation_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries/foundation_review/review_guard_rows.rs",
            "runtime_15_module_layout_child_summary_foundation_review_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary status-doc guard child-owner split",
        &[
            "runtime_15_module_layout_child_summary_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summaries.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs.rs",
            "runtime_15_module_layout_child_summary_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary status-doc guard folder-backed split",
        &[
            "runtime_15_module_layout_child_summary_status_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/source_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/budgets.rs",
            "runtime_15_module_layout_child_summary_status_docs_guard_is_folder_backed",
            "runtime_15_module_layout_child_summary_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 module-layout child-summary status-doc status-mirror child split",
        &[
            "runtime_15_module_layout_child_summary_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/module_layout_child_summary_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_module_layout_child_summary_status_doc_status_mirror_children_are_folder_backed",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/production_guard_support.rs",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output review-guard row-data guard child-owner split",
        &[
            "runtime_15_status_output_review_guard_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "runtime_15_status_output_m3_review_guard_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-doc guard child-owner split",
        &[
            "runtime_15_review_guard_row_data_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs.rs",
            "runtime_15_status_output_review_guard_row_data_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data moved-row guard child-owner split",
        &[
            "runtime_15_review_guard_row_data_moved_rows_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows.rs",
            "runtime_15_status_output_m3_review_guard_row_data_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard moved-row guard folder-backed split",
        &[
            "runtime_15_review_guard_moved_row_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/code_review_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/typed_error_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors.rs",
            "runtime_15_status_output_m3_review_guard_row_data_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard moved-row status-mirror child split",
        &[
            "runtime_15_review_guard_moved_row_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/moved_row_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/folder_backed_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_moved_rows/status_mirrors/scope_budgets.rs",
            "runtime_15_review_guard_moved_row_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_code_review_rows_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/root_and_children.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/export_chain.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors.rs",
            "runtime_15_review_guard_code_review_rows_guard_is_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard code-review status-mirror child split",
        &[
            "runtime_15_review_guard_code_review_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/code_review_owner.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/structure_guard_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_code_review_rows/status_mirrors/folder_backed.rs",
            "runtime_15_review_guard_code_review_status_mirror_children_are_folder_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/aggregation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data/status_mirrors.rs",
            "runtime_15_review_guard_row_data_guard_is_folder_backed",
            "runtime_15_status_output_m3_review_guard_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-doc guard folder-backed split",
        &[
            "runtime_15_review_guard_row_data_status_docs_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/row_sources.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/budgets.rs",
            "runtime_15_review_guard_row_data_status_docs_guard_is_folder_backed",
            "runtime_15_status_output_review_guard_row_data_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard row-data status-doc status-mirror child split",
        &[
            "runtime_15_review_guard_row_data_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/review_guard_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/status_doc_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_row_data_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_review_guard_row_data_status_doc_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard direct-assertion row-data guard folder-backed split",
        &[
            "runtime_15_review_guard_direct_assertion_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/export_chain.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors.rs",
            "runtime_15_review_guard_direct_assertion_rows_guard_is_folder_backed",
            "runtime_15_status_output_review_guard_direct_assertion_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 review-guard direct-assertion status-mirror child split",
        &[
            "runtime_15_review_guard_direct_assertion_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors/child_owner_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_review_guard_direct_assertion_rows/status_mirrors/folder_backed_status.rs",
            "runtime_15_review_guard_direct_assertion_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
        (
            "Runtime 15 M3 foundation row-data guard child-owner split",
            &[
                "runtime_15_foundation_row_data_guard_child_owner_split_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data.rs",
                "runtime_15_status_output_runtime_15_foundation_row_data_is_child_owner",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 foundation row-data guard folder-backed split",
            &[
                "runtime_15_foundation_row_data_guard_folder_backed_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data/delegation.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data/row_ownership.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data/exports.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data/topic_rows.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data/budgets.rs",
                "runtime_15_foundation_row_data_guard_is_folder_backed",
                "runtime_15_status_output_runtime_15_foundation_row_data_is_child_owner",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 foundation-guards row-data guard folder-backed split",
            &[
                "runtime_15_foundation_guards_row_data_guard_folder_backed_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/delegation.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/row_ownership.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/export_chain.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/budgets.rs",
                "runtime_15_foundation_guards_row_data_guard_is_folder_backed",
                "runtime_15_foundation_guards_row_data_owner_is_child_backed",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 foundation-guards row-data status-mirror child split",
            &[
                "runtime_15_foundation_guards_row_data_status_mirror_child_split_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/status_mirrors/child_split_status.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/status_mirrors/historical_status.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_guards_row_data/status_mirrors/folder_backed_status.rs",
                "runtime_15_foundation_guards_row_data_status_mirror_children_are_child_owned",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 lock-poison status row-data guard folder-backed split",
            &[
                "runtime_15_lock_poison_status_row_data_guard_folder_backed_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/delegation.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/row_ownership.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/export_chain.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/budgets.rs",
                "runtime_15_lock_poison_status_row_data_children_guard_is_folder_backed",
                "runtime_15_lock_poison_status_row_data_owner_is_child_backed",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 lock-poison status row-data status-mirror child split",
            &[
                "runtime_15_lock_poison_status_row_data_status_mirror_child_split_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/status_mirrors/child_split_status.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/status_mirrors/historical_status.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_lock_poison_status_row_data_children/status_mirrors/folder_backed_status.rs",
                "runtime_15_lock_poison_status_row_data_status_mirror_children_are_child_owned",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 scene-script row-data guard folder-backed split",
            &[
                "runtime_15_scene_script_row_data_guard_folder_backed_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/delegation.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/row_ownership.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/export_chain.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/budgets.rs",
                "runtime_15_scene_script_row_data_guard_is_folder_backed",
                "runtime_15_scene_script_row_data_owner_is_child_backed",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 scene-script row-data status-mirror child split",
            &[
                "runtime_15_scene_script_row_data_status_mirror_child_split_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/status_mirrors/child_split_status.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/status_mirrors/historical_status.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_scene_script_row_data/status_mirrors/folder_backed_status.rs",
                "runtime_15_scene_script_row_data_status_mirror_children_are_child_owned",
                "Cargo gate deferred",
            ],
        ),
    (
        "Runtime 15 M3 status-support row-data guard folder-backed split",
        &[
            "runtime_15_status_support_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/delegation.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/row_ownership.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/export_chain.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_row_data/budgets.rs",
                "runtime_15_status_support_row_data_guard_is_folder_backed",
                "runtime_15_status_support_row_data_owner_is_child_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs row-data guard folder-backed split",
        &[
            "runtime_15_priority_plan_docs_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/export_chain.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/row_sources.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/budgets.rs",
            "runtime_15_priority_plan_docs_row_data_guard_is_folder_backed",
            "runtime_15_priority_plan_docs_row_data_owner_is_child_backed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 priority plan docs status-mirror child split",
        &[
            "runtime_15_priority_plan_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/status_mirrors/row_owner_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/status_mirrors/folder_backed_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_status_support_priority_plan_docs/status_mirrors/owner_guard_status.rs",
            "runtime_15_priority_plan_docs_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 asset-budget row-data guard folder-backed split",
        &[
            "runtime_15_asset_budget_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_asset_budget_row_data.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_asset_budget_row_data/delegation.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_asset_budget_row_data/row_ownership.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_asset_budget_row_data/export_chain.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_asset_budget_row_data/status_mirrors.rs",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_asset_budget_row_data/budgets.rs",
                "runtime_15_asset_budget_row_data_guard_is_folder_backed",
                "runtime_15_asset_budget_row_data_owner_is_child_backed",
                "Cargo gate deferred",
            ],
        ),
        (
            "Runtime 15 M3 foundation row-data status-doc guard child-owner split",
            &[
                "runtime_15_foundation_row_data_status_docs_child_owner_split_static_passed_cargo_deferred",
                "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "runtime_15_status_output_foundation_row_data_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data guard child-owner split",
        &[
            "runtime_15_m2_row_data_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "runtime_15_status_output_runtime_15_m2_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data guard folder-backed split",
        &[
            "runtime_15_m2_row_data_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/row_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/budgets.rs",
            "runtime_15_m2_row_data_guard_is_folder_backed",
            "runtime_15_status_output_runtime_15_m2_row_data_is_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 M2 row-data status-mirror child split",
        &[
            "runtime_15_m2_row_data_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m2_row_data/status_mirrors/folder_backed_status.rs",
            "runtime_15_m2_row_data_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data status-doc guard folder-backed split",
        &[
            "runtime_15_foundation_row_data_status_docs_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/doc_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count.rs",
            "runtime_15_status_output_foundation_row_data_status_docs_are_child_owner",
            "runtime_15_foundation_row_data_docs_record_current_row_count",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 foundation row-data row-count child split",
        &[
            "runtime_15_foundation_row_data_row_count_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/current_counts.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_foundation_row_data_status_docs/row_count/priority_frontmatter.rs",
            "runtime_15_foundation_row_data_row_count_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups status-doc guard child-owner split",
        &[
            "runtime_15_m3_child_groups_status_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "runtime_15_status_output_m3_child_group_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups status-doc guard folder-backed split",
        &[
            "runtime_15_m3_child_groups_status_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/source_ownership.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/budgets.rs",
            "runtime_15_m3_child_groups_status_docs_guard_is_folder_backed",
            "runtime_15_status_output_m3_child_group_status_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-groups status-doc status-mirror child split",
        &[
            "runtime_15_m3_child_groups_status_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors/historical_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_m3_child_group_status_doc_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group status-row-doc guard child-owner split",
        &[
            "runtime_15_m3_child_group_status_row_docs_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs.rs",
            "runtime_15_status_output_m3_child_group_status_row_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group status-row-doc guard folder-backed split",
        &[
            "runtime_15_m3_child_group_status_row_docs_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/row_sources.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_maps.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors.rs",
            "runtime_15_m3_child_group_status_row_docs_guard_is_folder_backed",
            "runtime_15_status_output_m3_child_group_status_row_docs_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group status-row-doc status-mirror child split",
        &[
            "runtime_15_m3_child_group_status_row_docs_status_mirror_child_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/child_split_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/child_owner_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/m3_row_status.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_status_row_docs/status_mirrors/folder_backed_status.rs",
            "runtime_15_m3_child_group_status_row_doc_status_mirror_children_are_child_owned",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group moved-row guard child-owner split",
        &[
            "runtime_15_m3_child_group_moved_row_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_groups.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows.rs",
            "runtime_15_status_output_m3_child_group_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 child-group moved-row guard folder-backed split",
        &[
            "runtime_15_m3_child_group_moved_row_guard_folder_backed_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/delegation.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/lock_poison_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/module_convention_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/review_top_rows.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/status_mirrors.rs",
            "structure_convention/test_file_budget/status_output_row_data/runtime_15_m3_child_group_moved_rows/budgets.rs",
            "runtime_15_m3_child_group_moved_rows_guard_is_folder_backed",
            "runtime_15_status_output_m3_child_group_moved_rows_are_child_owner",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 status output expected-slice legacy child-owner split",
        &[
            "runtime_15_status_output_expected_slice_legacy_child_owner_split_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_slices/status.rs",
            "plan_status/status_output_tables/expected_slices/status/pre_runtime_15.rs",
            "plan_status/status_output_tables/expected_slices/date/pre_runtime_15.rs",
            "runtime_15_status_output_expected_slice_legacy_maps_are_child_owners",
        ],
    ),
    (
        "Runtime 15 M3 status output expected-slice legacy group child-owner split",
        &[
            "runtime_15_status_output_expected_slice_legacy_group_child_owner_split_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_slices/status/pre_runtime_15.rs",
            "plan_status/status_output_tables/expected_slices/status/pre_runtime_15/runtime_01_05.rs",
            "plan_status/status_output_tables/expected_slices/date/pre_runtime_15/runtime_11_14.rs",
            "runtime_15_status_output_expected_slice_legacy_group_maps_are_child_owners",
        ],
    ),
    (
        "Runtime 15 M3 status output expected-slice guard child-owner split",
        &[
            "runtime_15_status_output_expected_slice_guard_child_owner_split_static_passed_cargo_deferred",
            "structure_convention/test_file_budget/status_output_expected_slices.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/module_layout.rs",
            "structure_convention/test_file_budget/status_output_expected_slices/legacy_group_maps.rs",
            "runtime_15_status_output_expected_slice_guard_child_owner_split",
        ],
    ),
];
