use super::{production_guard_support, ExpectedStatusOutputSlice};

pub(in super::super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_PRODUCTION_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_PRODUCTION_FILE_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_EVIDENCE_ANCHOR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_EVIDENCE_ANCHOR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_CHILD_GROUP_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_OWNER_PATH_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_OWNER_PATH_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_PATH_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_ROOT_PATH_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_GUARD_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::CORE_AND_EVIDENCE_CHILD_GROUP_INVENTORY_GUARD_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_BASE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::MODULE_LAYOUT_BASE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::MODULE_LAYOUT_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_CHILD_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::MODULE_LAYOUT_CHILD_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_MODULE_LAYOUT_CHILD_SUMMARY_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::MODULE_LAYOUT_CHILD_SUMMARY_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_BASE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::REVIEW_GUARD_BASE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::REVIEW_GUARD_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::REVIEW_GUARD_ROW_DATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::REVIEW_GUARD_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_REVIEW_GUARD_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::REVIEW_GUARD_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_LOCK_POISON_SCENE_SCRIPT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_LOCK_POISON_SCENE_SCRIPT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_STATUS_SUPPORT_PRIORITY_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_RUNTIME_ROW_DATA_ASSET_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::RUNTIME_ROW_DATA_ASSET_BUDGET_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_FOUNDATION_M2_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::STATUS_DOCS_FOUNDATION_M2_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::STATUS_DOCS_CHILD_GROUP_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_STATUS_ROW_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::STATUS_DOCS_CHILD_GROUP_STATUS_ROW_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_STATUS_DOCS_CHILD_GROUP_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::STATUS_DOCS_CHILD_GROUP_MOVED_ROW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const PRODUCTION_GUARD_SUPPORT_EXPECTED_SLICE_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    production_guard_support::EXPECTED_SLICE_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
