use super::{review_guard_splits, ExpectedStatusOutputSlice};

pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = review_guard_splits::CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_REVIEW_GUARD_P0_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_REVIEW_GUARD_P0_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_REVIEW_GUARD_F8_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_REVIEW_GUARD_F8_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_REVIEW_GUARD_LATE_API_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_REVIEW_GUARD_LATE_API_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_F12_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_F12_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_ROOT_PARENT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_ROOT_PARENT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_RENDER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_RENDER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_F8_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_F8_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_P0_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_P0_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_DIRECT_ASSERTION_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_DIRECT_ASSERTION_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_FOLDER_BACKED_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_FOLDER_BACKED_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_STRUCTURE_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_STRUCTURE_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_PATHS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_PATHS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MAPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MAPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MIRRORS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MIRRORS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_STRUCTURE_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_STRUCTURE_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_CODE_REVIEW_TYPED_ERROR_STRUCTURE_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::CODE_REVIEW_TYPED_ERROR_STRUCTURE_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_STATUS_SUPPORT_TYPED_ERROR_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::STATUS_SUPPORT_TYPED_ERROR_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_STATUS_SUPPORT_SOURCE_INVENTORY_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::STATUS_SUPPORT_SOURCE_INVENTORY_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_STATUS_SUPPORT_SOURCE_INVENTORY_INVENTORY_METADATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::STATUS_SUPPORT_SOURCE_INVENTORY_INVENTORY_METADATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(in super::super) const REVIEW_GUARD_STATUS_SUPPORT_SOURCE_INVENTORY_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    review_guard_splits::STATUS_SUPPORT_SOURCE_INVENTORY_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES;
