use super::ExpectedStatusOutputSlice;

#[path = "review_guard_splits/code_review_rows.rs"]
mod code_review_rows;
#[path = "review_guard_splits/status_support_rows.rs"]
mod status_support_rows;
#[path = "review_guard_splits/typed_error_rows.rs"]
mod typed_error_rows;

pub(super) const CODE_REVIEW_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    code_review_rows::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_REVIEW_GUARD_P0_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = code_review_rows::REVIEW_GUARD_P0_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_REVIEW_GUARD_F8_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = code_review_rows::REVIEW_GUARD_F8_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_REVIEW_GUARD_LATE_API_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::REVIEW_GUARD_LATE_API_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = code_review_rows::DIRECT_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_DIRECT_ASSERTION_F12_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::DIRECT_ASSERTION_F12_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_DIRECT_ASSERTION_ROOT_PARENT_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::DIRECT_ASSERTION_ROOT_PARENT_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_DIRECT_ASSERTION_RENDER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::DIRECT_ASSERTION_RENDER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_DIRECT_ASSERTION_F8_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::DIRECT_ASSERTION_F8_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_DIRECT_ASSERTION_P0_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::DIRECT_ASSERTION_P0_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_DIRECT_ASSERTION_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::DIRECT_ASSERTION_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = code_review_rows::PLUGIN_IMPORTER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = code_review_rows::STRUCTURE_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_STRUCTURE_GUARD_STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::STRUCTURE_GUARD_STATUS_DOCS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_STRUCTURE_GUARD_FOLDER_BACKED_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::STRUCTURE_GUARD_FOLDER_BACKED_SUMMARY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_STRUCTURE_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::STRUCTURE_GUARD_TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_STRUCTURE_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::STRUCTURE_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::TYPED_ERROR_STRUCTURE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_PATHS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::TYPED_ERROR_STRUCTURE_STATUS_DOC_PATHS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::TYPED_ERROR_STRUCTURE_STATUS_DOC_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MAPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MAPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MIRRORS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::TYPED_ERROR_STRUCTURE_STATUS_DOC_STATUS_MIRRORS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_TYPED_ERROR_STRUCTURE_STRUCTURE_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::TYPED_ERROR_STRUCTURE_STRUCTURE_ASSERTION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_TYPED_ERROR_STRUCTURE_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    code_review_rows::TYPED_ERROR_STRUCTURE_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const CODE_REVIEW_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = code_review_rows::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    status_support_rows::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::REVIEW_GUARD_STATUS_SUPPORT_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::REVIEW_GUARD_TYPED_ERROR_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::REVIEW_GUARD_ROW_DATA_GUARD_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::REVIEW_GUARD_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_TYPED_ERROR_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::TYPED_ERROR_STATUS_DOC_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_SOURCE_INVENTORY_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::SOURCE_INVENTORY_FOUNDATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_SOURCE_INVENTORY_INVENTORY_METADATA_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::SOURCE_INVENTORY_INVENTORY_METADATA_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const STATUS_SUPPORT_SOURCE_INVENTORY_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    status_support_rows::SOURCE_INVENTORY_DELEGATION_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const TYPED_ERROR_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    typed_error_rows::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const TYPED_ERROR_RUNTIME_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = typed_error_rows::RUNTIME_SURFACE_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const TYPED_ERROR_ASSET_SHADER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = typed_error_rows::ASSET_SHADER_EXPECTED_STATUS_OUTPUT_SLICES;
