use super::ExpectedStatusOutputSlice;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] = &[
    (
        "Runtime 15 M3 review top-row status row-data child-owner split",
        &[
            "runtime_15_review_top_row_status_row_data_child_owner_split_static_passed_cargo_deferred",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/foundation_guards.rs",
            "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/review_status_sync.rs",
            "RUNTIME_15_M3_REVIEW_STATUS_SYNC_EXPECTED_STATUS_OUTPUT_SLICES",
            "REVIEW_STATUS_SYNC_EXPECTED_STATUS_OUTPUT_SLICES",
            "Runtime 15 M3 F19 scene renderer construction top-row closed status sync",
            "runtime_15_status_output_m3_row_data_child_owner_split",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D13 importer top-row closed status sync",
        &[
            "d13_importer_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/plugin_importer_dx/d13_importer_sdk.rs",
            "review_d13_importer_manifest_parity_guard_lives_in_sdk_builder",
            "| D13 | importer 系列",
            "| M3 / closed |",
            "d13_importer_runtime_export_macro_convergence_static_passed_cargo_deferred",
            "d13_importer_runtime_manifest_builder_convergence_static_passed_cargo_deferred",
            "d13_importer_manifest_parity_guard_static_passed_cargo_deferred",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D-S8/D3 native fixture top-row closed status sync",
        &[
            "ds8_d3_native_fixture_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            "review_ds8_d3_native_fixture_uses_sdk_macro_and_single_manifest",
            "| D-S8 | native 插件 ABI v3 样板已由 plugin SDK macro 承接",
            "| D3 | native manifest 双写已由 plugin.toml 单源闭合",
            "| Plugins 13 M2 + Plugins 12 / closed |",
            "| Plugins 13 M1 + Plugins 12 / closed |",
            "native_dynamic_fixture_validation_plugin_review_passed_unused_import_warning_fixed",
            "native_dynamic_fixture_importer_manifest_self_description_static_passed_cargo_deferred",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 P0 F1/F2/F4 top-row closed status sync",
        &[
            "p0_f1_f2_f4_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            "review_f1_native_host_callbacks_catch_unwind_before_crossing_ffi",
            "review_f2_scene_eventbus_locks_recover_after_poison",
            "review_f4_render_submit_capability_gaps_return_typed_errors",
            "| F1 | **原生插件入站 host 回调必须在跨 FFI 前截断 panic**",
            "| F2 | **scene/EventBus shared locks recover after poison**",
            "| F4 | **render submit viewport/provider capability gaps return typed errors**",
            "| Runtime 15 + Runtime 06 + Plugins 11 / review closed |",
            "| Runtime 15 + Runtime 07 / review closed |",
            "| Runtime 07 + render index / review closed |",
            "F1/F2/F4 已有闭合守卫",
            "完整 Runtime 07 FPS/profiling/full gate 仍 pending",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 D7 core workspace dependency top-row closed status sync",
        &[
            "d7_core_workspace_dependency_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/p0_robustness.rs",
            "review_priority_recommendation_tracks_current_remaining_work",
            "| D7 | core workspace dependency inheritance 已完成首轮全局 guard",
            "| M2 / closed |",
            "d7_core_workspace_dependency_inheritance_guard_static_passed_cargo_deferred",
            "core_workspace_dependency_status = core-workspace-deps-clean",
            "core_workspace_dependency_violation_count = 0",
            "插件间 path 依赖仍归后续切片",
            "cargo deferred",
        ],
    ),
    (
        "Runtime 15 M3 F5/F6/F7 typed-error top-row closed status sync",
        &[
            "f5_f6_f7_typed_error_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/scene_world.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/animation_resource.rs",
            "tests/runtime_absorption/code_review_findings/typed_error_convergence/asset_loaders.rs",
            "review_f5_world_spawn_bundle_surface_uses_scene_error",
            "review_f6_core_resource_registry_rename_uses_core_error",
            "review_f7_asset_artifact_errors_use_asset_import_error_sources",
            "| Runtime 08 + Runtime 15 / review closed |",
            "| Runtime 02 / review closed |",
            "| Runtime 04 / review closed |",
            "world_typed_mutation_errors_coremin_check_passed_partial",
            "core_resource_registry_typed_errors_coremin_check_passed",
            "asset_artifact_importer_typed_errors_coremin_passed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 F8/F9/F10 runtime surface top-row closed status sync",
        &[
            "f8_f9_f10_runtime_surface_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/f8_api_convergence.rs",
            "tests/runtime_absorption/structure_convention/facade_surface.rs",
            "tests/runtime_absorption/structure_convention/runtime_dead_code.rs",
            "review_f8_runtime_plugin_descriptor_status_mirrors_do_not_claim_public_field_pending",
            "runtime_15_prelude_covers_required_types",
            "runtime_15_runtime_ui_dead_code_surface_is_test_support",
            "| convention + Runtime 04 + Runtime 06 + Runtime 15 / review closed |",
            "| Runtime 15 / review closed |",
            "| Runtime 09 + Runtime 15 / review closed |",
            "runtime_15_runtime_plugin_descriptor_status_mirror_cleanup_static_passed_cargo_deferred",
            "runtime_15_prelude_required_types_coremin_check_passed",
            "runtime_15_runtime_ui_dead_code_support_split_coremin_check_passed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 F13/F14 provider diagnostics top-row closed status sync",
        &[
            "f13_f14_provider_diagnostics_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/structure_convention/provider_boilerplate/full_audit.rs",
            "tests/runtime_absorption/structure_convention/diagnostics_surface.rs",
            "runtime_15_no_duplicated_provider_boilerplate",
            "runtime_15_diagnostics_use_frame_trait_without_world_wrapper",
            "| convention + Runtime 15 / review closed |",
            "| Runtime 15 / review closed |",
            "runtime_15_provider_boilerplate_full_audit_coremin_check_passed",
            "runtime_15_diagnostics_frame_trait_wrapper_removed_coremin_check_passed",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 F17/F18 lookup/manager top-row closed status sync",
        &[
            "f17_f18_lookup_manager_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup.rs",
            "review_f17_entity_path_option_lookup_uses_get_verb",
            "review_f18_asset_manager_resolution_returns_registered_handle",
            "| convention + Runtime 08 / review closed |",
            "| Runtime 10 / review closed |",
            "runtime_08_entity_path_lookup_getter_rename_coremin_check_passed",
            "runtime_10_asset_manager_resolution_handle_shape_coremin_check_passed",
            "get_entity_by_path",
            "Result<Arc<AssetManagerHandle>, CoreError>",
            "Cargo gate deferred",
        ],
    ),
    (
        "Runtime 15 M3 F19 scene renderer construction top-row closed status sync",
        &[
            "f19_scene_renderer_construction_top_row_closed_status_static_passed_cargo_deferred",
            "docs/plans/engine-code-review-findings-2026-06.md",
            "tests/runtime_absorption/code_review_findings/late_api_cleanup.rs",
            "review_f19_scene_renderer_construction_modules_use_construct_names",
            "| convention + render index / review closed |",
            "render_scene_renderer_construct_modules_coremin_passed",
            "scene_renderer_core_construct",
            "scene_renderer_construct",
            "Cargo gate deferred",
        ],
    ),
];
