use super::ExpectedStatusOutputSlice;

#[path = "status_support/expected_slice_maps.rs"]
mod expected_slice_maps;
#[path = "status_support/priority_plan_docs.rs"]
mod priority_plan_docs;
#[path = "status_support/row_data_and_budget.rs"]
mod row_data_and_budget;
#[path = "status_support/runtime_index_anchors.rs"]
mod runtime_index_anchors;

pub(super) const EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    row_data_and_budget::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const EXPECTED_SLICE_MAPS_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    expected_slice_maps::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const RUNTIME_INDEX_ANCHORS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = runtime_index_anchors::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRIORITY_PLAN_DOCS_EXPECTED_STATUS_OUTPUT_SLICES: &[ExpectedStatusOutputSlice] =
    priority_plan_docs::EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRIORITY_PLAN_DOCS_OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = priority_plan_docs::OWNER_GUARDS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRIORITY_PLAN_DOCS_OWNER_GUARDS_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    priority_plan_docs::OWNER_GUARDS_INVENTORY_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRIORITY_PLAN_DOCS_STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] =
    priority_plan_docs::STATUS_FOLLOWUPS_EXPECTED_STATUS_OUTPUT_SLICES;
pub(super) const PRIORITY_PLAN_DOCS_ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES:
    &[ExpectedStatusOutputSlice] = priority_plan_docs::ROW_DATA_OWNER_EXPECTED_STATUS_OUTPUT_SLICES;

pub(super) const STATUS_SUPPORT_ROW_DATA_ANCHOR_MIRROR: &str = r#"
Runtime 15 M3 render shader template assembly guard support child-owner split
runtime_15_render_shader_template_assembly_guard_support_child_owner_split_static_passed_cargo_deferred
structure_convention/production_file_budget/render_shader_template_assembly.rs
structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions.rs
structure_convention/production_file_budget/render_shader_template_assembly/docs_anchors.rs
structure_convention/production_file_budget/render_shader_template_assembly/sources.rs
runtime_15_render_shader_template_assembly_support_children_are_folder_backed

Runtime 15 M3 render shader template assembly assertion contract child-owner split
runtime_15_render_shader_template_assembly_assertion_contract_child_owner_split_static_passed_cargo_deferred
structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions.rs
structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/template_contracts.rs
structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/mesh_cache_contracts.rs
structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/mesh_pipeline_shadow_graph_contracts.rs
structure_convention/production_file_budget/render_shader_template_assembly/assembly_assertions/owner_budget.rs
runtime_15_render_shader_template_assembly_support_children_are_folder_backed

Runtime 15 M3 mesh pipeline shader source tests child-owner split
runtime_15_mesh_pipeline_shader_source_tests_child_owner_split_static_passed_cargo_deferred
graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/shader_source.rs
graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/shader_source/tests.rs
graphics/scene/scene_renderer/mesh/mesh_pipeline_cache/shader_source/tests/runtime_shading_model_sources.rs
runtime_15_render_shader_template_assembly_support_children_are_folder_backed
"#;
