mod half_res;

pub(crate) use half_res::{
    half_resolution_transparency_supported, HALF_RES_TRANSPARENCY_COMPOSITE_EXECUTOR_ID,
    HALF_RES_TRANSPARENCY_COMPOSITE_PASS_NAME, HALF_RES_TRANSPARENCY_DEPTH_DOWNSAMPLE_EXECUTOR_ID,
    HALF_RES_TRANSPARENCY_DEPTH_DOWNSAMPLE_PASS_NAME, HALF_RES_TRANSPARENCY_MESH_EXECUTOR_ID,
    HALF_RES_TRANSPARENCY_MESH_PASS_NAME, HALF_RES_TRANSPARENCY_PARTICLE_EXECUTOR_ID,
};
