use super::*;

pub(super) const ASSET_BUDGET_ROW_OWNER_PATHS: &[(&str, &str, usize)] = &[
    (
        "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data.rs",
        ASSET_BUDGET_ROW_DATA_GUARD_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/root_paths.rs",
        ROOT_PATHS_PATH,
        90,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/root_statuses.rs",
        ROOT_STATUSES_PATH,
        60,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/root_child_rows.rs",
        ROOT_CHILD_ROWS_PATH,
        100,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/root_owner_paths.rs",
        ROOT_OWNER_PATHS_PATH,
        120,
    ),
    (
        "structure_convention/test_file_budget/row_data/runtime_15_asset_budget_row_data/root_inventory.rs",
        ROOT_INVENTORY_GUARD_PATH,
        100,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests.rs",
        ASSET_BUDGET_ROWS_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/runtime_rhi.rs",
        ASSET_BUDGET_RUNTIME_RHI_PATH,
        120,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/asset_tests.rs",
        ASSET_BUDGET_ASSET_TESTS_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/asset_tests/project_rows.rs",
        ASSET_BUDGET_ASSET_TESTS_PROJECT_ROWS_PATH,
        130,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/asset_tests/asset_resource_rows.rs",
        ASSET_BUDGET_ASSET_TESTS_ASSET_RESOURCE_ROWS_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/asset_tests/ui_pipeline_rows.rs",
        ASSET_BUDGET_ASSET_TESTS_UI_PIPELINE_ROWS_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/asset_tests/row_data_owner.rs",
        ASSET_BUDGET_ASSET_TESTS_ROW_DATA_OWNER_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/budget_render_ui.rs",
        ASSET_BUDGET_BUDGET_RENDER_UI_PATH,
        140,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_core_asset_dynamic.rs",
        ASSET_BUDGET_NAMING_CORE_ASSET_DYNAMIC_PATH,
        160,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_graphics_misc.rs",
        ASSET_BUDGET_NAMING_GRAPHICS_MISC_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_graphics_misc/root_route_rows.rs",
        ASSET_BUDGET_NAMING_GRAPHICS_MISC_ROOT_ROUTE_ROWS_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_graphics_misc/graphics_asset_rows.rs",
        ASSET_BUDGET_NAMING_GRAPHICS_MISC_GRAPHICS_ASSET_ROWS_PATH,
        110,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_graphics_misc/scene_platform_rows.rs",
        ASSET_BUDGET_NAMING_GRAPHICS_MISC_SCENE_PLATFORM_ROWS_PATH,
        90,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_graphics_misc/plugin_banned_rows.rs",
        ASSET_BUDGET_NAMING_GRAPHICS_MISC_PLUGIN_BANNED_ROWS_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/naming_graphics_misc/row_data_owner.rs",
        ASSET_BUDGET_NAMING_GRAPHICS_MISC_ROW_DATA_OWNER_PATH,
        80,
    ),
    (
        "plan_status/status_output_tables/expected_status_row_data/runtime_15/m3/asset_budget_tests/row_data_owner.rs",
        ASSET_BUDGET_ROW_DATA_OWNER_PATH,
        80,
    ),
];
