[package]
name = "zircon_plugin_sdk_examples_editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Plugin SDK example editor package for Zircon."

[dependencies]
zircon_editor.workspace = true
zircon_plugin_sdk = { workspace = true, features = ["editor"] }
zircon_runtime.workspace = true
