[package]
name = "zircon_plugin_rendering_editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rendering umbrella editor plugin package for Zircon."

[dependencies]
zircon_editor = { workspace = true }
zircon_plugin_rendering_runtime = { path = "../runtime" }
zircon_runtime = { workspace = true }
