use super::super::super::super::super::*;
use super::super::*;

pub(super) fn assert_typed_error_review_status_maps_are_synced(
    sources: &TypedErrorStatusDocSources,
) {
    assert_contains_all(
        "status/date expected-slice maps",
        &sources.status_maps,
        &[
            "Runtime 15 M3 code review findings typed-error structure guard child-owner split",
            "runtime_15_code_review_findings_typed_error_structure_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 typed-error structure assertions guard child-owner split",
            "runtime_15_typed_error_structure_assertions_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 typed-error structure assertions guard folder-backed split",
            "runtime_15_typed_error_structure_assertions_guard_folder_backed_static_passed_cargo_deferred",
            "Runtime 15 M3 typed-error native plugin loader structure guard child-owner split",
            "runtime_15_typed_error_native_plugin_loader_structure_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 typed-error structure moved-guard absence child-owner split",
            "runtime_15_typed_error_structure_moved_guard_absence_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 typed-error structure status-doc guard child-owner split",
            "runtime_15_typed_error_structure_status_docs_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 typed-error source inventory guard child-owner split",
            "runtime_15_typed_error_source_inventory_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 native live-host typed-error review guard child-owner split",
            "runtime_15_native_live_host_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 native live-host lifecycle-paths typed-error review guard child-owner split",
            "runtime_15_native_live_host_lifecycle_paths_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 native live-host replay-runtime typed-error review guard child-owner split",
            "runtime_15_native_live_host_replay_runtime_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 native ABI surfaces typed-error review guard child-owner split",
            "runtime_15_native_abi_surfaces_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 native plugin descriptor ABI typed-error review guard child-owner split",
            "runtime_15_native_plugin_descriptor_abi_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 UI input typed-error review guard child-owner split",
            "runtime_15_ui_input_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 native manifest sources typed-error review guard child-owner split",
            "runtime_15_native_manifest_sources_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 scene world typed-error review guard child-owner split",
            "runtime_15_scene_world_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 script host typed-error review guard child-owner split",
            "runtime_15_script_host_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 asset loader typed-error review guard child-owner split",
            "runtime_15_asset_loader_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 asset records typed-error review guard child-owner split",
            "runtime_15_asset_records_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "Runtime 15 M3 shader prewarm CLI typed-error review guard child-owner split",
            "runtime_15_shader_prewarm_cli_typed_error_review_guard_child_owner_split_static_passed_cargo_deferred",
            "2026-07-02",
            "2026-06-30",
        ],
    );
}
