use super::*;

pub(crate) const STATUS_SUPPORT_ROW_DATA_GUARD_CHILDREN: &[(&str, &str, &str)] = &[
    (
        "anchor_mirror",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/anchor_mirror.rs",
        ANCHOR_MIRROR_CHILD_SPLIT_GUARD_NAME,
    ),
    (
        "delegation",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/delegation.rs",
        FOLDER_BACKED_GUARD_NAME,
    ),
    (
        "row_ownership",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/row_ownership.rs",
        CHILD_OWNER_GUARD_NAME,
    ),
    (
        "row_data_and_budget",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/row_data_and_budget.rs",
        ROW_DATA_AND_BUDGET_CHILD_SPLIT_GUARD_NAME,
    ),
    (
        "root_inventory",
        ROOT_INVENTORY_GUARD_PATH,
        ROOT_INVENTORY_CHILD_SPLIT_GUARD_NAME,
    ),
    (
        "expected_slice_maps",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_maps.rs",
        EXPECTED_SLICE_ROW_DATA_GUARD_NAME,
    ),
    (
        "expected_slice_review_guard_structure",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/expected_slice_review_guard_structure.rs",
        REVIEW_GUARD_STRUCTURE_ROW_DATA_GUARD_NAME,
    ),
    (
        "runtime_index_anchors",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/runtime_index_anchors.rs",
        "runtime_15_status_support_runtime_index_anchor_rows_are_child_owned",
    ),
    (
        "export_chain",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/export_chain.rs",
        "runtime_15_status_support_row_data_export_chain_is_current",
    ),
    (
        "status_mirrors",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/status_mirrors.rs",
        "runtime_15_status_support_row_data_folder_backed_status_mirrors_are_current",
    ),
    (
        "budgets",
        "tests/runtime_absorption/structure_convention/test_file_budget/row_data/rt15_status_support/budgets.rs",
        "runtime_15_status_support_row_data_child_budgets_stay_focused",
    ),
];
