#[derive(Clone, Debug, Default)]
pub(in super::super) struct ProjectedDragOverlayData {
    pub popup_open: Option<bool>,
    pub text: Option<String>,
    pub value_text: Option<String>,
    pub payload_kind: String,
    pub payload_label: String,
    pub payload_reference: String,
    pub has_cursor: bool,
    pub cursor_x: f32,
    pub cursor_y: f32,
    pub offset_x: f32,
    pub offset_y: f32,
    pub preview_width: f32,
    pub preview_height: f32,
    pub drop_allowed: bool,
    pub has_drop_target: bool,
    pub drop_target_x: f32,
    pub drop_target_y: f32,
    pub drop_target_width: f32,
    pub drop_target_height: f32,
    pub drop_indicator_edge: String,
    pub drop_indicator_text: String,
    pub drop_source_summary: String,
}
