[package]
name = "zircon_plugin_rendering_reflection_probes_editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0.18"
zircon_editor = { workspace = true }
zircon_plugin_rendering_reflection_probes_runtime = { path = "../runtime" }
zircon_runtime = { workspace = true }
