pub use zircon_plugin_neural_runtime::{
    NEURAL_POST_PROCESS_FEATURE_ID as FEATURE_ID,
    NEURAL_POST_PROCESS_RUNTIME_CAPABILITY as RUNTIME_CAPABILITY,
};

pub const RUNTIME_CAPABILITIES: &[&str] = &[RUNTIME_CAPABILITY];
